### ISSUE TITLE
minor detail: Learn CSS: Selectors (quiz move to next question)

### ISSUE THREAD

**Issue by the-lazy-learner** [GoogleChrome/web.dev#10000]
**Description**
On completing the first Quiz question for the quiz at the bottom of the page, the button text should say `Next` instead of saying `Reset`. 

**Screenshots**
![Button says RESET instead of NEXT unlike other quizzes on page](https://user-images.githubusercontent.com/13695177/236229237-131b757e-c06c-40f9-ae3d-f8872595dd4e.png)

**Comment by Ilon4ik1** [comment]
Next

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
