### ISSUE TITLE
Stale While Revalidate article [web.dev/blog]

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web.dev#1000]
**A one to two sentence description of your post**

Stale-while-revalidate (SWR) is used by the Cache-Control header. It defines an extra window of time during which a cache can use a stale asset while it revalidates it asynchronously. This improves subsequent page load latencies as stale assets are non longer in the critical path.

We would like to author an article on SWR as it's shipping in Chrome. @jeffposnick has kindly offered to author this and is in touch with Kenji and Dave Tapuska on implementation questions.

**Target publish date:** `<yyyy-mm-dd>`

- [ ] Check this box if this is a hard deadline.

**Process**

Take a moment to look over the [web.dev handbook](https://web.dev/handbook) and
familiarize yourself with the process.

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal `<add a link to your proposal doc>`
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc. https://docs.google.com/document/d/1f55OIGCqevtWpuL04RuIGGlv981Ew5AVa0A_6Tdd33Q/edit
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1140 
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by robdodson** [comment]
Hey @addyosmani do y'all have a tentative date when you'd like this article to go live?

**Comment by jeffposnick** [comment]
I'm working on the draft now. It should be ready for review next week, tentatively?

**Comment by addyosmani** [comment]
I think that if we can publish within the next two to three weeks that would be ideal. Having a draft that we can take a look at next week sounds great. Thank you, Jeff!

**Comment by jeffposnick** [comment]
There's a draft of this post available for review at https://docs.google.com/document/d/1f55OIGCqevtWpuL04RuIGGlv981Ew5AVa0A_6Tdd33Q/edit (requires an `@google.com` Google Docs account).

**Comment by robdodson** [comment]
OK I'm going to see if @mfriesenhahn has cycles to take a look. We have a lot of docs in the queue at the moment so I'm not sure what our ETA will be but I'll update y'all when I know more.

**Comment by jeffposnick** [comment]
Friendly ping to see how this fits in with the current docs sprint.

Can I pull in an alternative reviewer if @mfriesenhahn doesn't have the bandwidth?

**Comment by mfriesenhahn** [comment]
Apologies, this didn't make it onto the spring board (my fault), so it fell through the cracks. When does it need to go out?

**Comment by jeffposnick** [comment]
The feature shipped in Chrome 75, so I guess it's not time-sensitive. (Or it's extra time sensitive, looking from a different point of view.)

Would it help if I asked @jpmedley if he had time to review it? He does normally handle reviews tied to new Chrome functionality.

**Comment by jpmedley** [comment]
Just assigned myself, because yes, I regard it as extra time sensitive. Unfortunately, I probably wont' get to it until Monday. I'm hung up on another matter just now.

**Comment by jpmedley** [comment]
@jeffposnick Is the content stable? I don't want to copy edit if someone is going to rewrite anything.

**Comment by jeffposnick** [comment]
Yup. It's stable.

**Comment by jpmedley** [comment]
I made some suggestions to Jeff's draft. I'm basically done.
