### ISSUE TITLE
Image lazy loading: Lazysizes is not using 

### ISSUE THREAD

**Issue by khempenius** [GoogleChrome/web.dev#1004]
It was reported that LazySizes is not using Intersection Observer.

Relevant web.dev content: https://web.dev/use-lazysizes-to-lazyload-images/

Context: https://twitter.com/serulux/status/1139163944311017473

**Comment by addyosmani** [comment]
This is correct. My understanding is you have to use https://github.com/aFarkas/lazysizes/blob/gh-pages/src/lazysizes-intersection.js for IO support

**Comment by serulux** [comment]
Hi Addy, 

I recently asked the library's author about the use of IO and yes, the answer is that you need to user that version (see thread: https://github.com/aFarkas/lazysizes/issues/263#issuecomment-501632534).

There are quite a few Google's pages where is said that Lazysizes uses IO, without clarifying that is not part of the main file,. I think that can be confusing.  

Thanks.

**Comment by robdodson** [comment]
@khempenius friendly ping, do you think you'll have bandwidth to update the article with a note about IO?
