### ISSUE TITLE
Explore page error

### ISSUE THREAD

**Issue by xiaoqingdaisuki** [GoogleChrome/web.dev#10043]
**Describe the bug**
when I select button but button active error

**To Reproduce**
1. Go to 'https://web.dev/explore'
2. Click on 'collection nav'
3. See error

**Expected behavior**
select nav button is correct.

**Screenshots**
![image](https://github.com/GoogleChrome/web.dev/assets/27540830/8758dbd9-28aa-4219-b45a-216c63198d00)
![image](https://github.com/GoogleChrome/web.dev/assets/27540830/c384758c-d3bc-48ef-b406-37cce9051eac)

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
