### ISSUE TITLE
Blog post for I/O19 web components lightning talk

### ISSUE THREAD

**Issue by arthurevans** [GoogleChrome/web.dev#1005]
**Describe the article you'd like to see**
Provides overview of latest news about web components. 

**Publish date**
7/20/2019, hard deadline.

**Comment by robdodson** [comment]
@arthurevans I'm temporarily assigning this to you. Would you mind reassigning it once you have a new owner? Everyone on web devrel should be part of this project. If they're not part of the team then you can just assign it back to me.
