### ISSUE TITLE
Layout instability on mobile Safari

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1009]
**Describe the bug**
Blog posts seem to have a horizontal shift on iOS Safari when the page loads.

This doesn't seem to occur on Chrome and Android (at least not that I've seen). Possibly related to loading the cookie banner?

**To Reproduce**
1. Using Mobile Safari, go to https://web.dev/layout-instability-api/

**Expected behavior**
The page loads like normal.

**Screenshots**
https://twitter.com/choonkeat/status/1138842305731878912
https://twitter.com/dcsturm/status/1138705054800781312

**Comment by robdodson** [comment]
We should see if this still happens when we're off devsite.

**Comment by robdodson** [comment]
Assigning to myself to verify.

**Comment by samthor** [comment]
@robdodson I'd close this if we can't repo.
