### ISSUE TITLE
Content overflow on ~1280-1400 px wide screens

### ISSUE THREAD

**Issue by CharleyGordon** [GoogleChrome/web.dev#10103]
**Yep, an overflow**

**To Reproduce**
1. Go too https://web.dev/learn/forms/validation/
2. Open devtools
3. Open to reponsive mode
4. Scale screen width up to ~1300px
5. Inspect an error

**Expected behavior**
clear content overflow on code samples and iframes

**Comment by gkm0001** [comment]
Hey @CharleyGordon I want to work on this project. As a frontend developer I know how to solve it effectively and I am interested to work on this project.  Please assign me this project.
