### ISSUE TITLE
Blog Feed is invalid 

### ISSUE THREAD

**Issue by ecancino** [GoogleChrome/web.dev#10100]
**Describe the bug**
The blog feed (https://web.dev/feed.xml) is not valid.

**To Reproduce**
1. Go to https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fweb.dev%2Ffeed.xml

**Expected behavior**
It should validate like: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwpostats.com%2Ffeed.xml

**Screenshots**
Not applicable

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
