### ISSUE TITLE
The Learn CSS article on inheritance (005) incorrectly uses the term "inheritable"

### ISSUE THREAD

**Issue by jernwerber** [GoogleChrome/web.dev#10109]
**Describe the bug**
The Learn CSS page on inheritance uses the term "inheritable" which is both potentially misleading and not used in the CSS spec. This is potentially misleading because the word "inheritable" can be interpreted as "able to be inherited" as opposed to how it is being used here "inherited by default". Additionally the CSS spec does not use the word "inheritable" instead referring to properties that inherit their values by default as "inherited properties".

**To Reproduce**
1. Go to https://web.dev/learn/css/inheritance/
2. Search for the term "inheritable".

**Expected behavior**
"Inheritable" should be replaced with a different term. I am proposing "inherited by default", which seems to be how "inheritable" was employed on this page.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298216470
