### ISSUE TITLE
Feed link appears at wrong position in the DOM and isn't announced on the site

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#1012]
Two feed-related issues:

1. On the [home](https://web.dev/), the [feed link](https://web.dev/feed.xml) appears at 
`#gc-wrapper > div > devsite-content > article > article > div > link`, which is clearly off.
  ```
  <link rel="alternate" href="/feed.xml" type="application/atom+xml" data-title="web.dev 
feed">
  ```
  ![Screen Shot 2019-06-18 at 15 44 37](https://user-images.githubusercontent.com/145676/59689472-fecb9480-91df-11e9-8ea9-ed7c0cb672dd.png)

2. It also seems like the link is nowhere visually announced on the page. This means feed readers like Feedly (or Google Reader 😿) will find it, but people new to RSS (in 2019 🙀) may never discover the option even exists.

**Comment by robdodson** [comment]
> On the home, the feed link appears at

This is a limitation of devsite unfortunately. We're planning to move off as soon as we can.

> It also seems like the link is nowhere visually announced on the page

Yeah we could probably add a link at the bottom. My hunch was most folks tend to use feed readers these days and search by site/url (as opposed to manually copy/pasting xml links into their readers). But I'm not a heavy RSS user so maybe folks would prefer to have the direct link?

**Comment by robdodson** [comment]
> This is a limitation of devsite unfortunately. We're planning to move off as soon as we can.

Specifically, we can't add anything to `<head>`. Our site gets kind of injected into the middle of their page template. It is a very suboptimal setup.

**Comment by tomayac** [comment]
> Specifically, we can't add anything to <head>. Our site gets kind of injected into the middle of their page template. It is a very suboptimal setup.

Got it, consider this one closed then (and hopefully once we migrate off devsite it should fix itself).

> [M]aybe folks would prefer to have the direct link?

I think especially given the current move back to blogs and blog like pages it's a nice gesture to our (future) readers…

**Comment by carolrivero** [comment]
Moving to internal tracking
