### ISSUE TITLE
content: Optimize CSS Background Images with Media Queries

### ISSUE THREAD

**Issue by demianrenzulli** [GoogleChrome/web.dev#1013]
**A one to two sentence description of your post**
- **Guide:** How to apply CSS media queries to request a background image for the user's device.
- **Codelab:** Using Webpack’s media query plugin, to extract each media query definition to its own CSS file. Loading the resulting CSS files with HTML media attribute and dynamic imports.

**Target publish date:** 2019-08-xx
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal https://docs.google.com/document/d/1XuQegHCNCJnvEBkcqDFzYfwZq4ZRBUNpUwDz_0ySiws/edit?usp=sharing
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by demianrenzulli** [comment]
The article and codelab have been written already (in doc format), and is currently awaiting review.

**Comment by mfriesenhahn** [comment]
Hi, Demian, can you include the content from the "Propose New Content" issue template so we can move this through our review process more easily? Link: https://github.com/GoogleChrome/web.dev/issues/new?assignees=&labels=content+proposal&template=content_proposal.md&title=content%3A+%3CAdd+your+title%3E

**Comment by demianrenzulli** [comment]
Hi @mfriesenhahn, adding the content here. 
Let me know if there's need for a separate issue:

**A one to two sentence description of your post**

**- Guide**: How to apply CSS media queries to request a background image for the user's device.
**- Codelab**: Using Webpack’s media query plugin, to extract each media query definition to its own CSS file. Loading the resulting CSS files with HTML media attribute and dynamic imports.

**Target publish date:** `<2019-08-XX>`
- [ ] Check this box if this is a hard deadline.

**Process**

- [X] 1. I've done my proposal.
- [X] 2. Proposal approved.
- [X] 3. I've added a draft to my proposal doc
- [X] 4. Draft approved — https://docs.google.com/document/d/1XuQegHCNCJnvEBkcqDFzYfwZq4ZRBUNpUwDz_0ySiws/edit?usp=sharing
- [ ] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

cc @robdodson

**Comment by mfriesenhahn** [comment]
I think it needs to be in the body of the issue for the bot to work, so I'll just add it. Thanks!

**Comment by robdodson** [comment]
Hey folks, checking in. @demianrenzulli are you still planning to write this post? Is there anything blocking you?

**Comment by demianrenzulli** [comment]
Hi @robdodson! Thanks a lot for reaching out.

I think this topic was de-prioritized in favor of other ones that needed to be addressed more promptly at the moment (for example, the [Link prefetch guide](https://web.dev/link-prefetch/) we released a couple of months ago).

While the [draft of the article](https://docs.google.com/document/d/1XuQegHCNCJnvEBkcqDFzYfwZq4ZRBUNpUwDz_0ySiws/edit) and [codelab](https://docs.google.com/document/d/1MqeVwchNafsEppwzobC2eP6r39PRJEUKHg1pAHJMeg0/edit) are ready, I would love to count with the feedback from some CSS experts to make sure we still want to follow the approaches outlined there.

Would be possible to work with @argyleink, for example, on this?
I'd be happy to re-do the article, if necessary.

What do you guys think?

**Comment by argyleink** [comment]
just re-read a couple times, seems good to me! The approach is stable, focused and articulated. I'd like to do another review when staged so the markdown is expanded, but otherwise I give it a thumbs up 👍 

Was there anything in particular that you wanted me to check out?

**Comment by demianrenzulli** [comment]
Thanks a lot @argyleink for taking a look at it! Sorry I didn't provide more details before, here are some things I wanted double-check:

- If we should use `image-set` instead of `@media`. I guess nothing has changed since last time, and the paragraph I added at the end is the best we can suggest at this point.
- For the codelab part, If we should continue using [media-query-plugin](https://www.npmjs.com/package/media-query-plugin) to split the CSS into different files, or if you know any other tool. I guess this one is tricky, as it took some time for us to decide. Assuming this is fine as it is also!

@robdodson I think we are good to go, should I move this to markup now so Adam can take a final look at it?

**Comment by demianrenzulli** [comment]
Hi @kaycebasques: this is an article that was submitted some months ago, as part of the "Optimize CSS" series of web.dev/fast and we decided to put it on hold because there were other higher priority guides. 

@robdodson brought it to our attention this week, and we thought this could be a good time to move it to markdown. You can take a look at the previous comments in this thread for more context.

Please, let me know if I should start passing it to code.

**Comment by kaycebasques** [comment]
@demianrenzulli please give me edit access to the [draft](https://docs.google.com/document/d/1XuQegHCNCJnvEBkcqDFzYfwZq4ZRBUNpUwDz_0ySiws/edit)
