### ISSUE TITLE
content: Use Prefetching for faster navigations

### ISSUE THREAD

**Issue by demianrenzulli** [GoogleChrome/web.dev#1014]
**Author**: @demianrenzulli 
**Reviewer**: @mihajlija 

**Target publish date:** <2019-09-XX>
- [x] Check this box if this is a hard deadline.
- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [X] 1. I've done my proposal - [link](https://docs.google.com/document/d/1HMhSWAmCoEvfMGC3R6KBsmWOpZqdxRw8NyLzduGZH_o/edit?usp=sharing)
- [x] 2. Proposal approved — _reviewer checks this_
- [X] 3. I've added a draft to my proposal doc [link](https://docs.google.com/document/d/151jkrA3nhUApMYq7o0rPRDQrlj5gndxEafvtjHAeAYg/edit)
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1468 
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by addyosmani** [comment]
Thanks for filing this after our discussion @demianrenzulli. I was thinking there are at least two codelabs in here:

* How to take advantage of `<link rel=prefetch>` (just the tag) to add prefetching to a multi-page site. Something easily applicable regardless of your tech stack.
* How to add prefetching to a simple SPA using Webpack's magic comments ( `import(/* webpackPrefetch: true */ "...")`) syntax (e.g prefetching a route or component chunk for a future navigation)

**Comment by demianrenzulli** [comment]
Thanks, @addyosmani!  That makes sense. 

From your comment seems like the template would be similar to [this other guide](https://web.dev/preload-critical-assets/) around link="preload", including a general introduction, plus two codelabs to cover each case.

Regarding the site to use as demo, my idea was having something with a feed, that could be either an e-commerce or a news site (to achieve something like [this](https://thepracticaldev.s3.amazonaws.com/i/sf32qj3fc4dof4dfgyuh.gif)).

Talking to @robdodson, it doesn't seem we have a demo we can reuse for this use case, so I guess I might put something together from scratch.

Let me know if you have any other thoughts!

**Comment by demianrenzulli** [comment]
@mihajlija @mfriesenhahn as discussed I've updated this issue, based on the new template. It wasn't clear to me where I should attach the draft of the guide, so I added it directly below the document info in the [proposal](https://docs.google.com/document/d/1HMhSWAmCoEvfMGC3R6KBsmWOpZqdxRw8NyLzduGZH_o/edit?usp=sharing).

**Comment by carolrivero** [comment]
@jpmedley  to do a quick editorial pass.

**Comment by carolrivero** [comment]
@jpmedley to do this today.

**Comment by kaycebasques** [comment]
@mihajlija it sounds like you reviewed this. Is it ready to assign back to @demianrenzulli?

**Comment by mihajlija** [comment]
Reviewed the PR in #1468, cc @demianrenzulli to link the codelab in the metadata and @robdodson  to give the final approval.

**Comment by mihajlija** [comment]
Congrats @demianrenzulli 🥳
