### ISSUE TITLE
The link src of [inert] content of Dialog article is wrong, and click it result to 404 page.

### ISSUE THREAD

**Issue by HellMagic** [GoogleChrome/web.dev#10159]
**Describe the bug**
In the [Dialog]() part, there is have some content like that "The rest of the page is [inert](https://web.dev/learn/html/dialog/learn/html/focus/) and, by default, obscured by a semi-transparent backdrop.", but the the link src of the [inert] is not correct -- from element panel it use relative path format like "learn/html/focus", so that the final path is "https://web.dev/learn/html/dialog/learn/html/focus/", but the correct path should be "https://web.dev/learn/html/focus/".

**To Reproduce**
1. Go to https://web.dev/learn/html/dialog/
2. find "The rest of the page is inert and, by default, obscured by a semi-transparent backdrop." content part
3. Click on 'inert'
4. See error: it will go to a 404 page

**Expected behavior**
it should go to https://web.dev/learn/html/focus/

**Screenshots**
<img width="1586" alt="image" src="https://github.com/GoogleChrome/web.dev/assets/1937669/e71b9c16-becc-4a7d-8da3-2e065a8dae31">

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/u/1/issues/298703874
