### ISSUE TITLE
content: Missing closing `p` tag on audio and video lesson from HTML module

### ISSUE THREAD

**Issue by itsdevdeepak** [GoogleChrome/web.dev#10161]
Closing of `p` tag is missing inside `video` tag on audio and video lesson

### What page(s) need to be updated?
https://web.dev/learn/html/audio-video/

### Screenshot
![image](https://github.com/GoogleChrome/web.dev/assets/105926677/d4e2e5cf-a87a-4081-a265-b9929df41253)
![image](https://github.com/GoogleChrome/web.dev/assets/105926677/6cde1a1d-86b5-4f45-a788-7d1ff5fae860)

### Additional Info 
I would like to work on this

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
