### ISSUE TITLE
Error in code example under enable-https/#make-intrasite-urls-relative 

### ISSUE THREAD

**Issue by pnavarrc** [GoogleChrome/web.dev#10167]
**Describe the bug**

The last example in the section [Make intrasite URLs relative](https://web.dev/enable-https/#make-intrasite-urls-relative) has the `<b>` tag in the `href` attribute of a link. Also, the opening `<` of the paragraph element is escaped:

```html
<h1>Welcome To Example.com</h1>
<script src="/jquery.js"></script>
<link rel="stylesheet" href="/assets/style.css"/>
<img src="/images/logo.png"/>;
<p>A <a href="/2014/12/24/">new post on cats!</a></p>
&lt;p>Check out this <a href="<b>https://foo.com/</b>">other cool site.</a></p> ← HERE
```

**To Reproduce**
1. Go to https://web.dev/enable-https/#make-intrasite-urls-relative
2. Review the last code example in the section (the "Do" example labeled "Use HTTPS URLs for intersite URLs (where possible).")
4. See that the last link has an incorrect `href` attribute

**Expected behavior**

The example should be

```html
<h1>Welcome To Example.com</h1>
<script src="/jquery.js"></script>
<link rel="stylesheet" href="/assets/style.css"/>
<img src="/images/logo.png"/>;
<p>A <a href="/2014/12/24/">new post on cats!</a></p>
<p>Check out this <a href="https://foo.com/"><b>other cool site.</b></a></p>
```

**Screenshots**

<img width="778" alt="image" src="https://github.com/GoogleChrome/web.dev/assets/114084/b8243844-acae-469e-8dfe-63790f953b46">

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/297890504
