### ISSUE TITLE
content: update wording

### ISSUE THREAD

**Issue by likelytwitchdollop** [GoogleChrome/web.dev#10176]
### What page(s) need to be updated?
https://web.dev/learn/accessibility/

### Why is this update needed?
There's a word missing in this sentence: "Design and build websites and web apps ~so~ that disabled people can interact **with** in a meaningful and equivalent way."

The sentence appears twice in the document.

**Comment by dstmarthe** [comment]
Hi, thanks for this. We're taking your advice. I've made the change internally on a staging area. Right now content on this site is frozen because we are migrating to a new platform, but this and all changes will be applied after the move. Thanks again.
