### ISSUE TITLE
Recommend specific dimensions (or at least a specific aspect ratio) for author images

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChrome/web.dev#1018]
This is about [the author images](https://github.com/GoogleChrome/web.dev/tree/master/src/site/content/en/images/authors). The relevant section on the wiki is <https://github.com/GoogleChrome/web.dev/wiki/How-to-write-a-post#create-a-new-post>. It doesn’t mention any aspect ratio or dimensions.

For v8.dev for example, all our avatar images are 1:1 JPEGs of 192×192px for the @2x version and 96×96px for the @1x version.

For web.dev, the author images currently all seem to have different aspect ratios and dimensions. It feels like we’re wasting bytes as a result.

@robdodson Could you recommend any specific dimensions (or at least a specific aspect ratio) for author images? We can then capture this recommendation in the wiki and crop/resize/standardize the existing images accordingly.

https://github.com/GoogleChrome/web.dev/pull/1010#issuecomment-502994783

**Comment by robdodson** [comment]
Assigning to @mfriesenhahn to include in our upcoming handbook.

I think using the same dimensions you mention above might be good, especially if we decide to make our author images a tad bigger in the future (something i've considered in the past).

It would also mean we could (in theory) share author images between v8.dev and web.dev maybe? At least it would be easy for folks on our teams to just grab the same copies and put them into each project's repo instead of having to make 4 different sizes.

**Comment by mfriesenhahn** [comment]
Added to the handbook.

**Comment by mathiasbynens** [comment]
Where is the handbook?

Can https://github.com/GoogleChrome/web.dev/wiki/How-to-write-a-post#create-a-new-post be updated as well?

Once I'm 100% clear on how you're moving forward, I'll happily submit a PR to crop + optimize the existing images.

**Comment by mfriesenhahn** [comment]
It should be published in the next couple days. (It'll replace the whole wiki.) And that sounds awesome!

**Comment by robdodson** [comment]
@mathiasbynens it's available at web.dev/handbook now

**Comment by mathiasbynens** [comment]
https://web.dev/handbook/contributor-profile/

**Comment by mathiasbynens** [comment]
https://github.com/GoogleChrome/web.dev/wiki/How-to-write-a-post#create-a-new-post still has the old content. Can this be updated to point to the new handbook?

**Comment by robdodson** [comment]
@mfriesenhahn are you cool with us pointing all the contributing info in the README and wiki over to the handbook?

**Comment by mfriesenhahn** [comment]
Yes, by all means. That was already on my to-do list :)
