### ISSUE TITLE
Bug when trying to copy image from https://web.dev/patterns/clipboard/copy-images/demo.html

### ISSUE THREAD

**Issue by mhu-fdm** [GoogleChrome/web.dev#10199]
**To Reproduce**
1. Go to [https://web.dev/patterns/clipboard/copy-images/demo.html](https://web.dev/patterns/clipboard/copy-images/demo.html)
2. Click on the copy button
3. The image isn't copied. I'm using Chrome
4. There is an error in the Console, "NotAllowedError Type image/svg+xml not supported on write."

**Expected behavior**
Should copy image

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
