### ISSUE TITLE
content: fix broken link in web browsers 5/23 post

### ISSUE THREAD

**Issue by moshfeu** [GoogleChrome/web.dev#10204]
### What page(s) need to be updated?

https://web.dev/web-platform-05-2023/

### Why is this update needed?
 The link to the High definition CSS color guide post is broken.

### What's the deadline?
Asap?

#### Is it a hard deadline?
Don't know

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re in the process of migrating to a new platform and so we’ll fix this over there. This may be more than a simple link fix, as I can't seem to find the article. Again, thanks! I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/u/1/issues/299314616
