### ISSUE TITLE
URL (High definition CSS color guide.) doesn't exist

### ISSUE THREAD

**Issue by Kikerss** [GoogleChrome/web.dev#10206]
**Describe the bug**

**To Reproduce**
1. Go to '[ https://web.dev/web-platform-05-2023/ ]'
2. Click on ' [High definition CSS color guide](https://web.dev/articles/high-definition-css-color-guide/) '
3. Scroll down to ' CSS Color Level 4 features [#](https://web.dev/web-platform-05-2023/#css-color-level-4-features) .'
4. See error: 404, Sorry, we couldn't find that page.

**Expected behavior**
Link to page, that doesn't exist, 404

**Screenshots**

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
