### ISSUE TITLE
Trojan Found by Windows Security

### ISSUE THREAD

**Issue by Christofosho** [GoogleChrome/web.dev#10213]
**Describe the bug**
Windows Security flagged the following file as `Trojan:PHP/Obfuse.AS!MSR`

https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/secure/fixing-the-japanese-keyword-hack/index.md

**To Reproduce**
1. Clone repository
2. Scan with Windows Security

**Expected behavior**
There should be no Trojans within the repository.

**Screenshots**
![image](https://github.com/GoogleChrome/web.dev/assets/1461425/19add4cc-f0b1-4fc3-89fe-9fe2b634c8bf)

**Comment by dstmarthe** [comment]
Thanks for raising this. Closing because we're migrating to a new platform so this shouldn't be an issue after the move.
