### ISSUE TITLE
Home page is broken if the language is other than English

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChrome/web.dev#10212]
**Steps to reproduce**
1. Go to https://web.dev
2. Change the language in the footer to anything other than English
3. Look at the page

**Screenshots**

![home](https://github.com/GoogleChrome/web.dev/assets/7892779/e2aa20bb-1320-4148-8311-06451d18bc38)

**Comment by tomayac** [comment]
We’re in the middle of switching to internal infrastructure that will handle this case better than the way the customized Eleventy infrastructure is set up at present. That’s why the issue is not handled here. Thank you very much for caring, though!
