### ISSUE TITLE
Multiple PWA apps on same domain : article outdated ?

### ISSUE THREAD

**Issue by christopheblin** [GoogleChrome/web.dev#10220]
We have multiple PWA apps on the same domain with different paths : apps.company.net/home, apps.company.net/notification-center etc

So, referring to  https://web.dev/building-multiple-pwas-on-the-same-domain, we are "Same origin, non-overlapping paths"

At the moment, when we open apps.company.net/home in chrome (android), it is correctly proposing "Installtion promotion"

Installing and Opening the app, it is asking for notification permission => ok (and accepted, I can see that in chrome parameters)

Now, if we click on a link to access apps.company.net/notification-center 
1. the link is opened in a new "embedded web-page" without installation promotion
2. if we click on "add to home" and then open the app, the permission for notification is asked again
3. if we click on the home button in the notification-center app, the home app is opened

So
1. Installation promotion is indeed not proposed in 2nd app (that's bad for us but ok we will educate our users to use the 3-dots menu top-right and "add to home")
2. Cookies seems correcyly shared (since we do not need to redo authentication)
3. Link capturing works correctly

BUT it does not match what is told for permissions

> Permissions are tied to the origin. That means if the user grants a permission to one app, it will apply to all apps on that origin simultaneously

In our experience, the permission for notification is asked on each app

I can provide (privately)  a video that demonstrate the behavior

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298159437

I believe you can receive updates if you comment on the issue.
