### ISSUE TITLE
https://web.dev/setting-up-a-payment-method/ has incomplete information regarding URL dereferencing

### ISSUE THREAD

**Issue by brycethomas** [GoogleChrome/web.dev#10251]
**Describe the bug**
https://web.dev/setting-up-a-payment-method/ claims that the Browser issues a GET request to URl-based payment method identifiers, and that the expected response is a payment method manifest.  If I understand correctly, this is not universally true, either in Chrome or in the relevant web specifications.  For example, the guide at https://developer.chrome.com/docs/android/trusted-web-activity/receive-payments-play-billing/#build-the-purchase-flow uses a payment method identifier "https://play.google.com/billing" in  the following snippet:

```
   const paymentMethods = [{
       supportedMethods: "https://play.google.com/billing",
       data: {
           sku: sku,
       }
   }];
```

This URL does not resolve to a payment method manifest (`curl --include https://play.google.com/billing` generates a HTTP 404 response).  It appears that specialized handling of this URL may be hardcoded in Chromium: https://source.chromium.org/search?q=https:%2F%2Fplay.google.com%2Fbilling&ss=chromium.

The payment method identifier spec also states that fetching the URL is optional.  From https://www.w3.org/TR/payment-method-id/#fetching-dereferencing:

> It is OPTIONAL for user agents to [fetch](https://fetch.spec.whatwg.org/#concept-fetch) a [URL-based payment method identifier](https://www.w3.org/TR/payment-method-id/#dfn-url-based-payment-method-identifier).

Further discussion of that statement can be found in https://github.com/w3c/payment-method-id/issues/33

**Ask:** would it be possible to update the documentation to clarify which payment method identifiers Chrome special-cases?

Thank you!

**Comment by brycethomas** [comment]
cc @agektmr

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298215271
