### ISSUE TITLE
Update /storage-for-the-web to reflect the latest

### ISSUE THREAD

**Issue by morsssss** [GoogleChrome/web.dev#10253]
**Is your feature request related to a problem? Please describe.**
https://web.dev/storage-for-the-web/ is a great quick overview of web storage types. But new storage options have come to the web since then. And it would be useful to include some information about what sort of storage is useful for which purposes.

**Describe the solution you'd like**
* We might want to put unrecommended options like the File System API and FileWriter at the bottom, so people don't get confused with similar-sounding options they seldom need to be aware of
* We could offer SQLite-over-Wasm as a migration path for Web SQL
* We could say more about File System Access. If it was possible to mention that work is proceeding on persistence, that would be nice!
* We should mention OPFS for low-level byte file access and for general private file storage
* We could mention that indexedDB is currently the standard for sophisticated storage and for building database abstractions, but you can now migrate other databases to the web, and you might want to use SQLite. Unless that's TMI for this article.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298215275
