### ISSUE TITLE
Content displayed on Dark theme needs improvement

### ISSUE THREAD

**Issue by ghadzhigeorgiev** [GoogleChrome/web.dev#10255]
**Is your feature request related to a problem? Please describe.**
When using Dark theme on page https://web.dev/patterns/web-vitals-patterns/, some of the content on pages is barely visible and/or readable.
![Screenshot 2023-07-14 180344](https://github.com/GoogleChrome/web.dev/assets/432307/7a62f16b-58cf-4111-aaf3-f48a0093d243)

**Describe the solution you'd like**
Content parts to be more visible/readable with Dark theme.

**Describe alternatives you've considered**
Dark Reader plugin for example, produces much better result:
![Screenshot 2023-07-14 181030](https://github.com/GoogleChrome/web.dev/assets/432307/8ff6ece7-c4ae-4277-9d0f-107d6491a0a9)

or as it is on some of the other pages on web.dev like https://web.dev/patterns/components/
![Screenshot 2023-07-14 181535](https://github.com/GoogleChrome/web.dev/assets/432307/6d7d50b7-7d5e-4b0c-9c5e-67ce540ae563)

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
