### ISSUE TITLE
content: Best practices to order elements in <head>

### ISSUE THREAD

**Issue by MrHBS** [GoogleChrome/web.dev#10267]
I would like to see an article that talks about ordering elements in the head tag

**Comment by matthiasrohmer** [comment]
Thanks for the suggestion! In the meantime you might find @rviscomi's [capo.js](https://rviscomi.github.io/capo.js/) useful 🙂

**Comment by dstmarthe** [comment]
Hi, thanks for raising this. We are moving to a new non-Github platform, and migrating issues to a new issue tracker. Consequently I must close this.  I've replicated this request at out new tracker so we may write this in the future. See moved issue here:https://issuetracker.google.com/issues/298540722

**Comment by dstmarthe** [comment]
@MrHBS Yea, sorry, wasn't sure if I could, but it's Devsite.

**Comment by dstmarthe** [comment]
@MrHBS Correct.
