### ISSUE TITLE
content: Out of date reference to an article using Google Analytics Universal

### ISSUE THREAD

**Issue by Tiggerito** [GoogleChrome/web.dev#10265]
### What page(s) need to be updated?

[Loading Third-Party JavaScript - Analytics can be complicated](https://github.com/GoogleChrome/web.dev/blame/main/src/site/content/en/blog/optimizing-content-efficiency-loading-third-party-javascript/index.md#analytics-can-be-complicated)

### Why is this update needed?

The third-party article referenced in the "Analytics can be complicated" section provides solutions for Google Analytics Universal. As that is no longer a thing, most of what the article talks about is no longer relevant, as GA4 works quite differently. i.e. it uses beacons and batching to delay events automatically. Maybe Phil will write an update?

While editing the article, there are some missing spaces before links in this section.

[Lazy load Third-Party Resources](https://web.dev/optimizing-content-efficiency-loading-third-party-javascript/#lazy-load-third-party-resources)

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/297891069
