### ISSUE TITLE
content: fix typo on 009 Lists

### ISSUE THREAD

**Issue by diegotc86** [GoogleChrome/web.dev#10270]
### What page(s) need to be updated?
[009 Lists
Provide a list of URLs.](https://web.dev/learn/html/lists/)

### Why is this update needed?
In the following text it should say `<li>` instead of `<body>`

```
Thus far, we have looked at list items containing only text nodes. List items can contain 
all flow content, meaning any element found in the body that can be nested as a direct 
child of the <body>, including headings, thereby sectioning content.
```

### What's the deadline?
No deadline

#### Is it a hard deadline?
No

**Comment by dstmarthe** [comment]
I believe the original is correct. The paragraph is basically saying List items can contain anything one can find in a <body> tag including headings etc... 

@rachelandrew I'm not sure who is the original author(s) but I think this was their intent?

**Comment by rachelandrew** [comment]
Yep I think the original is correct.

**Comment by dstmarthe** [comment]
Thanks for being vigilant though, Diego.
