### ISSUE TITLE
content: Unfinished article and inconsistency in Learn HTML 003 Metadata

### ISSUE THREAD

**Issue by owyaggy** [GoogleChrome/web.dev#10284]
### What page(s) need to be updated?

https://web.dev/learn/html/metadata/#other-useful-meta-information

### Why is this update needed?

The current instruction about the <head> of the demo website indicates web manifests are a useful tool, but are not under the purview of this module, and as such the <head> element is somewhat long and unwieldy. This tracks with the code block shown at the end of the page.

However, the following paragraph inconsistently states: 
It's pretty long, but it's done. It would have been much longer, but you've summed up all the icons, short name, etc. in a manifest file, enabling you to omit many <meta> and <link> tags,

**Including the sentence fragment** - "tags," is the end of a paragraph, so this content is clearly unfinished, as well as inconsistent.

Since web manifests are covered in the PWA series and relevant articles are already linked, it seems the solution is changing this penultimate paragraph of the article to state instead:

"It's pretty long, but it's done."

### What's the deadline?

N/A

#### Is it a hard deadline?

No.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/297891065
