### ISSUE TITLE
content: Fix grammar in Learn HTML 011 Tables

### ISSUE THREAD

**Issue by owyaggy** [GoogleChrome/web.dev#10287]
### What page(s) need to be updated?

https://web.dev/learn/html/tables/#merging-cells

### Why is this update needed?
A simple typo - omission of the word "as."

Correcting:
"...but they are important to have in your toolbelt your tables grow in complexity."

To:
"...but they are important to have in your toolbelt as your tables grow in complexity."

**Comment by dstmarthe** [comment]
Hi, thanks for catching this! I went ahead and fixed this, though it's not viewable on the live site because content is frozen and we're migrating to a new internal platform. After the move, the changes will be there. Again, thanks for catching this.
