### ISSUE TITLE
content: Constructable Stylesheets: adoptedStyleSheets.push now works

### ISSUE THREAD

**Issue by SimonSiefke** [GoogleChrome/web.dev#10294]
### What page(s) need to be updated?

https://web.dev/constructable-stylesheets/#using-constructed-stylesheets

### Why is this update needed?

From the article:

```js
// Apply the stylesheet to a Shadow Root:
const node = document.createElement('div');
const shadow = node.attachShadow({ mode: 'open' });
shadow.adoptedStyleSheets = [sheet];
```

> Notice that we're overriding the value of adoptedStyleSheets instead of changing the array in place. This is required because the array is frozen; in-place mutations like push() throw an exception, so we have to assign a new array. To preserve any existing StyleSheets added via adoptedStyleSheets, we can use concat to create a new array that includes the existing sheets as well as additional ones to add

Since this article was created, there have been some great changes to `adoptedStylesheets`, specifically `adoptedStyleSheets.push` is now allowed  and `adoptedStyleSheets` is not immutable anymore.

### Proposed changes to the article

- Using `adoptedStyleSheets.push` in the example code
- Removing the paragraph about `adoptedStyleSheets` being immutable and in-place mutations not being allowed

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/297891068
