### ISSUE TITLE
selection disabled?

### ISSUE THREAD

**Issue by SimonSiefke** [GoogleChrome/web.dev#10299]
**Describe the bug**
Text selection is disabled/doesn't work.

**Environment information**

- Browser: Chrome 115
- OS: Ubuntu 23.04

**To Reproduce**

https://github.com/GoogleChrome/web.dev/assets/23744935/8e384254-39d8-4552-a06a-04aa978d3659

1. Go to https://web.dev/adapting-typography-to-user-preferences-with-css/
2. Try to select text
3. It's not possible
4. Go to https://prismjs.com/
5. Try to select text
6. It works as expected

**Expected behavior**
Text selection works

**Comment by Twaha-Rahman** [comment]
@SimonSiefke I tried it out on my end and everything seems to be working just fine. I can select and code without any problem.

OS: Windows 11 (22H2)
Browser: Firefox 115.0.3 (64-bit) and Chrome 115.0.5790.171 (Official Build) (64-bit)

**Comment by aaronstezycki** [comment]
Was just about to submit an issue for this. I was reading the [custom elements](https://web.dev/custom-elements-v1/) page, and tried to select a line of code. I was taken aback when no text seemed to be highlighted upon dragging my cursor. I copied and pasted said text, which had worked. I assume that `::selection { background: color ; }` is not working.

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
