### ISSUE TITLE
content: `prefetch` should not has `as` attribute

### ISSUE THREAD

**Issue by Teamop** [GoogleChrome/web.dev#10306]
### What page(s) need to be updated?

https://web.dev/link-prefetch/#how-to-implement-rel=prefetch

### Why is this update needed?

From the above document, the prefetch has an `as` attribute, but from the [MDN - prefetch](https://developer.mozilla.org/en-US/docs/Glossary/Prefetch), [HTML SPEC](https://html.spec.whatwg.org/#link-type-dns-prefetch), no `as` is mentioned there. Also from the [MDN - link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link), the `as` is only used with `preload` and `modulepreload`, so seems error in the above document.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/297891067
