### ISSUE TITLE
Typo: Missing an article

### ISSUE THREAD

**Issue by Twaha-Rahman** [GoogleChrome/web.dev#10309]
**Describe the bug**

The [Focus](https://web.dev/learn/css/focus/) module in the `Learn CSS` page has a small grammatical error.

Under the [How elements get focus](https://web.dev/learn/css/focus/#how-elements-get-focus) heading, on the second paragraph an article is missing.

I think it should be corrected as shown below:

`...which is order in which elements are focused...` ---> ` ...which is the order in which elements are focused...`

**Comment by dstmarthe** [comment]
Hi, thanks for catching this! I went ahead and fixed though, though it's not viewable on the live site because content is frozen and we're migrating to a new internal platform. After the move, the changes will be there. Again, thanks for catching this.
