### ISSUE TITLE
Lighthouse CI page seems like it's missing closing block tag

### ISSUE THREAD

**Issue by koddsson** [GoogleChrome/web.dev#10311]
**Describe the bug**

**To Reproduce**
1. Go to 'https://web.dev/lighthouse-ci/#github-status-checks'
2. Scroll down to 'Step 7 of the "GitHub Status Checks" section'
3. See that the formatting of the content is not very clear or readable.

**Expected behavior**
I expected the formatting to be clear and readable.

**Screenshots**
![image](https://github.com/GoogleChrome/web.dev/assets/318208/d310c64a-300f-485f-801d-7039e11f3625)

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/297890500
