### ISSUE TITLE
`openModal` needs to be replaced with `showModal`

### ISSUE THREAD

**Issue by PatricioEzcurra** [GoogleChrome/web.dev#10327]
**Describe the bug**
Just an error with an example. The text says:
"...When a modal dialog is opened using openModal(), the inertness or deactivation comes for free..."

**To Reproduce**

**Expected behavior**
It should be showModal() method not "openModal()"

**Screenshots**
![2023-08-11 14 05 58 web dev 190537f31edc](https://github.com/GoogleChrome/web.dev/assets/45321153/8f4cbd61-e81b-465c-a1f7-6c0f6034bca7)

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298216469
