### ISSUE TITLE
Adding entries to the browser history stack on /animations-guide

### ISSUE THREAD

**Issue by kevinfarrugia** [GoogleChrome/web.dev#10326]
**Describe the bug**
When navigating to https://web.dev/animations-guide/ and scrolling downwards, the browser history is populated with many identical entries for the same page. This does not happen on other pages, for example https://web.dev/script-evaluation-and-long-tasks/

**To Reproduce**
1. Go to https://web.dev/animations-guide/ (you could use Incognito)
2. Scroll down until you reach the footer.
3. Right click on the browser's back button.
4. See that there are numerous identical entries and pressing the back button does not navigate to the previous page.

**Expected behavior**
Back button should take the user back to the previous page.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/297891064
