### ISSUE TITLE
Typo / mistake in Learn PWA > Service Workers

### ISSUE THREAD

**Issue by julamb** [GoogleChrome/web.dev#10331]
The [Registering a service worker](https://web.dev/learn/pwa/service-workers/#registering-a-service-worker) sections states: 

> Before a service worker takes control of your page, it must be registered for your PWA. That means the first time a user comes to your PWA, network requests **will not** go directly to your server because the service worker is not yet in control of your pages.

That seems to be a mistake: on first load, the requests won't be intercepted by the PWA, and **will** go directly to your server.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/297891063
