### ISSUE TITLE
View source link goes to main repository instead of the actual page

### ISSUE THREAD

**Issue by zeritonius** [GoogleChrome/web.dev#10345]
When I access this:
https://web.dev/learn/html/
there is an "view source" button at the bottom of the page. When I click on it, I am sent to https://github.com/GoogleChrome/web.dev which is the root page of the repository, instead of being sent to the appropriate folder, which is https://github.com/GoogleChrome/web.dev/tree/main/src/site/content/en/learn/html

Is this the desired behavior?

Thank you.

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
