### ISSUE TITLE
clarify browser cache behaviour for large files

### ISSUE THREAD

**Issue by timruffles** [GoogleChrome/web.dev#10343]
**Is your feature request related to a problem? Please describe.**

I've observed that there is little clarity on how browsers decide whether to cache a large file (specifically HTTP caching, rather than Cache API etc). Some browsers
have had configuration flags for this (e.g. Firefox exposes `browser.cache.disk.max_entry_size`, Chrome/chromium doesn't as far as I can see, [e.g.](https://groups.google.com/a/chromium.org/g/chromium-discuss/c/ls_YD-trdRU)).

**Describe the solution you'd like**

A rule of thumb guide for whether browsers will consider a file cacheable based on size. I understand this is a complex and changing landscape, but a rule of thumb would be helpful for developers, e.g.

"At time of writing, files large than 25Mb are not likely to be considered cacheable by all major mobile and desktop browsers."

**Describe alternatives you've considered**

A link to someone who's documented this elsewhere, or a test page which allows users to determine this for a specific browser. [This page](https://web.archive.org/web/20120616100846/https://stevesouders.com/tests/cachesize/) apparently used to achieve this.

**Additional context**

[Lots](https://serverfault.com/questions/338722/what-is-the-maximum-file-size-that-will-be-cached-by-a-browser) [of](https://stackoverflow.com/questions/63891436/chrome-refuses-to-cache-large-binary-data-files) [people](https://stackoverflow.com/questions/60646737/how-to-cache-large-fie-in-chrome#:~:text=I%20do%20some%20simple%20tests,would%20not%20be%20cached%20too.) [have](https://superuser.com/questions/1031723/what-is-the-maximum-file-size-that-will-be-cached-by-a-browser) [asked](https://support.mozilla.org/en-US/questions/1262578) this over time in various venues.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/297890499
