### ISSUE TITLE
content: TODO pwa enhancements needs to be updated for IOS/MacOS changes

### ISSUE THREAD

**Issue by ClinMyk2018** [GoogleChrome/web.dev#10342]
### What page(s) need to be updated?
- https://web.dev/learn/pwa/enhancements/

### Why is this update needed?
- IOS/MacOS has made changes to PWA features/capabilities and this page does not reflect all of them. To include the capability to add to home screen from chrome.
- There also out of data implementations that do not work like the fullscreen code.

### What's the deadline?
- Technically none, but would help to have it up to date so others will use PWA for IOS/MacOS more potentially by seeing its further capabilities.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll address this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/297890498.
