### ISSUE TITLE
Copy button is not visible on focus

### ISSUE THREAD

**Issue by pradeepanvi** [GoogleChrome/web.dev#10363]
**Describe the bug**

**To Reproduce**
1. Go to 'https://web.dev/csp/'
2. Go to 'Use case : lockdown ' Section via tab key. 
3. Then you can see Focus is going to the copy button but it's not visible. 
4. It is showing only with mouseover.

**Expected behavior**
Should be visible by focus or tab key too.

**Screenshots**
Focus
![Screenshot (23)](https://github.com/GoogleChrome/web.dev/assets/20303132/53becf05-46bd-46d8-bff7-368df5dd1bd2)

Hover
![Screenshot (24)](https://github.com/GoogleChrome/web.dev/assets/20303132/89352f93-5f63-402d-ac6a-0cdbcd27a11a)

The issue in running the development code:-
![Screenshot (25)](https://github.com/GoogleChrome/web.dev/assets/20303132/2291de72-932c-4623-ad6a-76f806af1b39)

Fix:
![Screenshot (26)](https://github.com/GoogleChrome/web.dev/assets/20303132/880bc034-9fe4-42be-8708-174b97c1a8e3)

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.

**Comment by dstmarthe** [comment]
@MrHBS As for as I know right now, no. We're migrating to Devsite, which is a content management system. That's why I've been tasked with migrating content and closing engineering issues, because we won't be making system/backend changes after the move.
