### ISSUE TITLE
content: Correct the information about cover value in background-size property

### ISSUE THREAD

**Issue by dv3lah** [GoogleChrome/web.dev#10384]
* Use this template to request updates to existing content.
* Delete any fields that aren't relevant to your issue. 
* Update the title of this issue with a brief summary of the work to be done.

### What page(s) need to be updated?

[https://web.dev/learn/css/backgrounds/](https://web.dev/learn/css/backgrounds/)

### Why is this update needed?

Because there is wrong information on the page.

We need to update the content about background-size property:

**Current information on the web.dev:**

cover: Covers the entire area of the background layer. This may mean the image is stretched or cropped.

But it's not mean the image is stretched. It's better to use the word "scale" instead of "stretch".

[According to MDN, the image will be scaled while preserving it's ratio.](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size)

So it's better to update the content based on that. 

It's better not using the word "stretch" because it means the ratio will not be preserved.

### What's the deadline?

9/8/2023

#### Is it a hard deadline?

No, it's not!

If yes, please explain why.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at 
https://issuetracker.google.com/u/1/issues/299602342
