### ISSUE TITLE
Is the meta descrition used for ranking?

### ISSUE THREAD

**Issue by Citizen-Zoo** [GoogleChrome/web.dev#10387]
**Describe the bug**
The meta description is a brief summary of the content on a webpage that appears below the title tag in search engine results. It should accurately describe the content of the page and entice users to click through to your website. The meta description is _not directly_ used for ranking in search engines. While it does not have a direct impact on a page's ranking, it can influence whether users click on your page in search results.

**To Reproduce**
1. Go to [Learn HTML Metadata](https://web.dev/learn/html/metadata/)
2. Scroll down to [description](https://web.dev/learn/html/metadata/#description)
3. See error in the text. The description value, however, is _super important for SEO_; _in addition to helping sites rank based on the content_, the description content value is often what search engines display under the page's title in search results.

**Expected behavior**
This text should reflect that although the description _doesn't_ affect rankings, a well-crafted meta description can improve the click-through rate and drive more traffic to your site. Only used for display purposes by Google and not _directly_ for ranking. 

References:
[Better snippets for your users](https://developers.google.com/search/blog/2017/06/better-snippets-for-your-users)
[SEO starter guide](https://developers.google.com/search/docs/fundamentals/seo-starter-guide)
[John Mueller](https://twitter.com/JohnMu/status/1699477271847817575)

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at 
https://issuetracker.google.com/u/1/issues/299602343
