### ISSUE TITLE
Document webpush notification expiration procedure

### ISSUE THREAD

**Issue by kmomberg** [GoogleChrome/web.dev#10392]
### WebPush notification expiration procedure

When subscribing webpush notifications, you commonly receive an `expirationTime: null`, meaning the subscription doesn't expire.

In practice, after some time your subscription do expire and a 410 error response is received in the server when trying to send webpush notifications to the user. User then needs to re-subscribe manually to get notifications again.

I found workarounds for this:

* Add an event listener for `pushsubscriptionchange` event. This seems to be supported by Firefox only.
* Send a push message to the SW with the instruction to unsubscribe -> subscribe -> update-subscription-data. While this can work, violates the `userVisibleOnly: true` directive you send when subscribing. Even more, some UA can consider these non-showing push messages a reason to cancel the subscription.
* Re-subscribe on each notification received. This won't work if notifications aren't frequent enough.

Explaining this use case will help us build better web sites and service workers.

#### What content already exists on this topic?

I didn't find any. Some content can be added in:

* https://web.dev/push-notifications-faq/
* https://web.dev/push-notifications-common-issues-and-reporting-bugs/

#### Who will be authoring the content?

Someone with  deep knowledge on this. This is something I haven't found good info about.

#### What area is your content related to?

PWAs/Capabilities, Frontend

**Comment by dstmarthe** [comment]
Thanks for raising this. We’ve moved to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at
https://issuetracker.google.com/issues/324615949
