### ISSUE TITLE
Link to example.com in OPFS article

### ISSUE THREAD

**Issue by leumasme** [GoogleChrome/web.dev#10394]
https://github.com/GoogleChrome/web.dev/blob/33d159d19500ea65e028e8f63504bbf33f8ed728/src/site/content/en/blog/origin-private-file-system/index.md?plain=1#L92

On https://web.dev/origin-private-file-system/, there is an incorrect link to example.com
`skip down to [Using the origin private file system in a Web Worker](https://example.com).`
It should instead link down to the `#using-the-origin-private-file-system-in-a-web-worker` heading

**Comment by dstmarthe** [comment]
Thanks, has been fixed.
