### ISSUE TITLE
Metrics: For each performance metric, indicate which opportunities/diagnostics are most related

### ISSUE THREAD

**Issue by demianrenzulli** [GoogleChrome/web.dev#1039]
**Feature request summary**

Currently there's no way of knowing which performance suggestion, under "Opportunities" or "Diagnostics" is related to which metric(s) in the Lighthouse report.

Some optimizations might not impact a single metric alone, but are definitely more related to one metric, than others. For example: [Eliminate Render blocking resources](https://developers.google.com/web/tools/lighthouse/audits/blocking-resources?utm_source=lighthouse&utm_medium=unknown), will likely affect [FCP](https://developers.google.com/web/tools/lighthouse/audits/first-contentful-paint), more than others.

Ways to achieve this could be:

- Suggestions may contain a label indicating which are the metrics that will be more impacted by applying them. 
- Suggestions could  be grouped by metric.

**What is the motivation or use case for changing this?**

First thing developer see in LH reports are metrics and their values, and whenever they see metrics in red, they want to know how to improve them.
Today Opportunities are ranked by overall performance impact, but it's not clear to which metrics the potential savings are related to, and which might be the metric that will more likely be impacted by applying these changes.

**How is this beneficial to Lighthouse?**

- Connects the different sections of the report more clearly.
- Makes reports more actionable.

**Comment by paulirish** [comment]
moved to web.dev and retitled.

**Comment by robdodson** [comment]
@addyosmani do you know if it would be possible to get a member of the LH team to create this mapping between metrics and diagnostics/opportunities? I think @egsweeny attempted some work around this at one point but it got stalled. Maybe we can resurrect what she started?

**Comment by paulirish** [comment]
we took a pass on this several months ago, fwiw.

corp-only sheet: https://docs.google.com/spreadsheets/d/1M8iQWCb_GBzxZy7xYOa_ustx-iNQvke8X94vRViUhYg/edit#gid=0

**Comment by robdodson** [comment]
Seems like maybe we could add it to this doc? https://web.dev/performance-scoring/

@kaycebasques @mfriesenhahn wdyt?
