### ISSUE TITLE
content: samesite-cookie-recipes bug link should be changed

### ISSUE THREAD

**Issue by sbingler** [GoogleChrome/web.dev#10401]
### What page(s) need to be updated?

https://web.dev/samesite-cookie-recipes/#getting-help

### Why is this update needed?

The link to the SameSite cookies bug template is being used to spam the cookie team with meaningless bug reports.
This template has not been used for a actual bug report in years, I recommend replacing it with a generic link to crbug.com

### What's the deadline?

None, but sooner would be nice.

#### Is it a hard deadline?
No

If yes, please explain why.

**Comment by dstmarthe** [comment]
We've moved to a new issue tracker for web.dev. I urge you to open this issue there if it's still a problem.
I'd migrate this myself but there might be some correspondence or resolution you won't be cc'd on. 
New tracker is here: https://issuetracker.google.com/issues?q=status:open%20componentid:1400680&s=created_time:desc
