### ISSUE TITLE
Link to a resource is expired

### ISSUE THREAD

**Issue by daxter-army** [GoogleChrome/web.dev#10404]
**Link to a resource is expired**
In the **Resources and references** at [antialiasing-101](https://web.dev/antialiasing-101/), this link is expired [CSS properties that affect type rendering](http://blog.typekit.com/category/type-rendering/). Please take care of this.

**To Reproduce**
1. Go to [https://web.dev/antialiasing-101/](https://web.dev/antialiasing-101/)
2. Navigate to [Resources and references](https://web.dev/antialiasing-101/#resources-and-references)
3. Click on [CSS properties that affect type rendering](http://blog.typekit.com/category/type-rendering/)
4. The link is expired, the original content has been shifted from that link

**Expected behavior**
A Page with the expected article would have been opened.

**Comment by khubaibalam2000** [comment]
Can I work on this issue ?

**Comment by khubaibalam2000** [comment]
Opened Pull Request for this issue #10406.

**Comment by dstmarthe** [comment]
Fixed.
