### ISSUE TITLE
Unwanted characters in PWA Section

### ISSUE THREAD

**Issue by yashrajbharti** [GoogleChrome/web.dev#10432]
**Describe the bug**
The text after alt-tab doesn't look right. The `"**` after the **alt-tab** should be removed. Just a low-hanging fruit.

**To Reproduce**
 
* Go to [Optimizing Design For Desktop | Web.dev](https://web.dev/learn/pwa/app-design/#optimizing-design-for-desktop)
* See the unwanted `"**` underneath the heading.

**Expected behavior**
N/A

**Screenshots**
![Screenshot 2023-10-03 at 4 38 45 PM](https://github.com/GoogleChrome/web.dev/assets/43868318/b4409ef1-b387-47b5-96fb-eba1a5fea1b5)

**Comment by dstmarthe** [comment]
Fixed, thanks for opening the issue.
