### ISSUE TITLE
content: Misleading platform value given in Web App Manifest spec.

### ISSUE THREAD

**Issue by yashrajbharti** [GoogleChrome/web.dev#10438]
### What page(s) need to be updated?

[PWA | Detection](https://web.dev/learn/pwa/detection/#related-applications)

### Why is this update needed?

Misleading and Outdated platform value is given to related applications member of the `Web App Manifest spec` as it can be seen in the screenshot(s) below.
![Screenshot 2023-10-05 at 3 55 42 AM](https://github.com/GoogleChrome/web.dev/assets/43868318/dc9159aa-b766-40f6-a497-53faa20ef3ef)

This has to be updated as per the [W3C Guidelines | Platforms](https://github.com/w3c/manifest/wiki/Platforms) 

![Screenshot 2023-10-05 at 4 02 57 AM](https://github.com/GoogleChrome/web.dev/assets/43868318/c3d1d1dd-b1ae-4d79-8dba-81ab1609a22f)
![Screenshot 2023-10-05 at 3 56 25 AM](https://github.com/GoogleChrome/web.dev/assets/43868318/3b100697-8313-458f-8eb6-9256d99595e9)

### What's the deadline?

That being said, `iTunes` is misleading which concerned me to look into it at a deeper level and I am glad it's removed from the W3C standards. For the deadline, I can only request if it can be done soon. I am glad to help as well.

**Comment by dstmarthe** [comment]
Thanks for raising this. I've migrated this issue the the new tracker and you can see it here:
https://issuetracker.google.com/issues/324621201
