### ISSUE TITLE
content: PWA Detects transfer using a deprecated method

### ISSUE THREAD

**Issue by yashrajbharti** [GoogleChrome/web.dev#10437]
### What page(s) need to be updated?

[Detection | PWA](https://web.dev/learn/pwa/detection/#detecting-the-transfer)

### Why is this update needed?

`MediaQueryList.addListener()` method is deprecated and Not for use in new websites. Thus the logic handling provided in the chapter needs an updation.

### Screenshots 

![Screenshot 2023-10-05 at 3 15 35 AM](https://github.com/GoogleChrome/web.dev/assets/43868318/63371106-1a70-4976-b547-ad5589efcc09)

![Screenshot 2023-10-05 at 3 17 24 AM](https://github.com/GoogleChrome/web.dev/assets/43868318/8ba3eb49-f93b-4e47-917a-f39de81c0cd3)

### What's the deadline?

N/A

**Comment by dstmarthe** [comment]
Thanks for raising this. We’ve moved to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/324601876
