### ISSUE TITLE
Clarity: SSR Term Definition

### ISSUE THREAD

**Issue by Tiberriver256** [GoogleChrome/web.dev#10442]
**Describe the bug**
I felt like the description for the term **Server Side Rendering** [here](https://web.dev/rendering-on-the-web/) was a bit misleading.

> **Server-side rendering (SSR)**: rendering a client-side or universal app to HTML on the server.

This makes it seem, to me, that the only two ways to achieve SSR is with a client-side or universal app that supports server side rendering which I believe is untrue because SSR was around before client-side or universal apps were being built.

Suggestion:
> **Server-side rendering (SSR)**: rendering on a web server responses that are customized for each user's (client's) request.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’ve moved to a new platform and so we’ll address this over there. I’ve moved the issue to our new tracker and you can see it at
https://issuetracker.google.com/issues/324609510
