### ISSUE TITLE
Not working jumplinks

### ISSUE THREAD

**Issue by Gerg95** [GoogleChrome/web.dev#1044]
Jumplinks appear on https://web.dev/fast when the h2's are hovered over, however these links (https://web.dev/fast#optimize-your-images for example) do not lead anywhere as the content is not on the page.

**Comment by robdodson** [comment]
That link works for me. It takes you to the section heading.

![image](https://user-images.githubusercontent.com/1066253/60211294-9306ae80-9813-11e9-8e85-d331aaee7e3c.png)
