### ISSUE TITLE
Browser inconsistencies with explanation of :focus

### ISSUE THREAD

**Issue by alexandersandberg** [GoogleChrome/web.dev#1047]
**Describe the bug**
The [Style focus article](https://github.com/GoogleChrome/web.dev/blob/master/src/site/content/en/accessible/style-focus/index.md) explains that *"Regardless of whether you use a mouse to click on it or a keyboard to tab to it, **the button's focus indicator will *always* look the same.**"*

However, this is not the case for all browsers, as we can see below.

* Clicking with the mouse in Chrome:
![Chrome behavior](https://user-images.githubusercontent.com/35671299/60211062-94a99400-985e-11e9-88c0-b262b663fd05.png)
The focus indicator is shown, as explained in the article.

* Clicking with the mouse in Safari:
![Safari behavior](https://user-images.githubusercontent.com/35671299/60211097-a3904680-985e-11e9-9bdb-6987a4e0e4c4.png)

* Clicking with the mouse in Firefox:
![Firefox behavior](https://user-images.githubusercontent.com/35671299/60211281-fec23900-985e-11e9-8c06-c07cb8a4852c.png)
In both Safari and Firefox, the—according to the article, expected—orange focus indicator is not shown.

**Expected behavior**
Add a note about browser inconsistencies.

**Comment by robdodson** [comment]
ah I think this is because Safari and Firefox don't actually focus the button. if you change it to a `<div tabindex=0>` it'll apply the focus indicator. I can update the post

**Comment by alexandersandberg** [comment]
Forgot to add that this testing was done on macOS 10.14.5, with the latest browsers. I found [this section about 'Clicking and focus' on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus) that show inconsistencies between windows and macOS as well.

I also tested on Opera:
![Opera behavior](https://user-images.githubusercontent.com/35671299/60240043-04943a80-98b0-11e9-93c7-3c09da7676f2.png)
Opera behaves like Chrome; adding `:focus` when clicking.

---

Then I decided to test the same thing for `<a>` tags as well and found something interesting (at least to me). The behavior when *clicking the link with the mouse* differs depending on if you're using the browser's default `:focus`, or if you're using your own (again, only tested on macOS 10.14.5).

I created two links: one without any custom styling, and one using the following rule:
```
.custom:focus {
  outline: 5px dashed orange;
}
```
![Summary of click test](https://user-images.githubusercontent.com/35671299/60242555-301a2380-98b6-11e9-9cc5-8a586b486905.png)
As we can see here, the `:focus` style is only applied when clicking with the mouse **if there is a custom style set**. And in Safari, even this won't apply the styling.

**Comment by alexandersandberg** [comment]
Here's another resource I just found that summarizes these inconsistencies between default and custom styling: [ally.js — Default Browser Focus Outline Styles](https://allyjs.io/tests/focus-outline-styles/#style=focus&key=text,radio,checkbox,textarea,button,link,div&browser=firefox,chrome,safari,ie11)

**Comment by robdodson** [comment]
@alexandersandberg thank you for the detailed follow ups. I've updated the article to try to explain the situation better.
