### ISSUE TITLE
content: Overview of Feature Policies

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web.dev#1048]
**A one to two sentence description of your post**
What are you planning to teach folks in this post?

> Feature Policy allows web developers to selectively enable, disable, and modify the behavior of certain APIs and web features in the browser. It's like CSP but instead of controlling security, it controls features!

Eric Bidelman originally published our first article about FPs over at https://developers.google.com/web/updates/2018/06/feature-policy. We would like to migrate and update this content to account for what FPs have actually shipped in that time. My thinking right now is that we treat this content as an entry to /blog, but I otherwise like the content.

An updated guide to point to https://web.dev/image-policies/.

I am not planning on moving FPs into /fast just yet. Would like to wait until they are further along in the web standards process before considering it good guidance for the longtail of developers.

**Target publish date:** `<2019-07-30>`
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal `<add a link to your proposal doc>`
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by addyosmani** [comment]
Current policies: https://chromestatus.com/features#feature%20policy

**Comment by robdodson** [comment]
> My thinking right now is that we treat this content as an entry to /blog, but I otherwise like the content.

So this would only get published as a blog post, correct?

**Comment by addyosmani** [comment]
Yep. That's correct. Just as a blog post.

**Comment by robdodson** [comment]
Going to close this as stale because there's no immediate owner. Happy to reopen when there are concrete next steps.
