### ISSUE TITLE
content: How to think about speed tools

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web.dev#1050]
**A one to two sentence description of your post**
What are you planning to teach folks in this post?

> Google has put out a lot of guidance around performance data and performance tooling. The goal of this  doc is to consolidate this guidance for developers and marketers to help them understand how to think about performance and navigate all of Google's performance tool offerings.

This doc was an effort to capture where each of Google's speed tools currently fits. We probably want to look at a revision (at some point). I can think of at least a few changes:

- web.dev/measure now exists
- Search Console support for speed dashboard
- Firebase performance monitoring 
- Test My Site refresh etc.

**Target publish date:** `<2019-09-30>`
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal `<add a link to your proposal doc>`
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by robdodson** [comment]
Might also be related to: https://github.com/GoogleChrome/web.dev/pull/977

**Comment by robdodson** [comment]
Going to close this as stale because there's no immediate owner. Happy to reopen when there are concrete next steps.
