### ISSUE TITLE
content: Using rel=preconnect to eliminate round-trips

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web.dev#1051]
**Author: @mihajlija**
**Reviewer: @katejeffreys**

**A one to two sentence description of your post**
What are you planning to teach folks in this post?

> <link rel="preconnect"> informs the browser that your page intends to establish a connection to another origin, and that you’d like the process to start as soon as possible.Establishing connections often involves significant time in slow networks, particularly when it comes to secure connections, as it may involve DNS lookups, redirects, and several round trips to the final server that handles the user’s request. Taking care of all this ahead of time can make your application feel much snappier to the user without negatively affecting the use of bandwidth. Most of the time in establishing a connection is spent waiting, rather than exchanging data.

We previously published https://developers.google.com/web/fundamentals/performance/resource-prioritization#preconnect but a dedicated guide explaining what preconnect does / a codelab highlighting how to apply preconnects and see the before/after wins would be useful.

**Target publish date:** `<2019-08-14>`
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal https://docs.google.com/document/d/1oxgb1MxXOjrL7RSSrgx3f4JYiw4_nPudltwB63uly2Y/edit#
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1222
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by mihajlija** [comment]
I'll start on this immediately, ideally this work will also unblock the 3rd party resources optimization codelab. 🤞

**Comment by robdodson** [comment]
@mihajlija hey milica, before diving in would you be ok having a quick meeting with myself and @mfriesenhahn to discuss the new writing process we're trying to roll out?

**Comment by mihajlija** [comment]
@robdodson Of course, anytime (except tomorrow) between 9-17h CEST works for me, just send a calendar invite. 👍
