### ISSUE TITLE
content: Rendering on the web

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web.dev#1053]
**A one to two sentence description of your post**
What are you planning to teach folks in this post?

This article would capture an overview of how to render content on the web (e.g server-rendering, client-side rendering, static, progressive rendering etc). It aims to inform developers unsure about the 'right' approach to opt for when rendering their experiences. We have already published this content to https://developers.google.com/web/updates/2019/02/rendering-on-the-web and this issue is about migrating it to /fast.

More from the article:

As developers, we are often faced with decisions that will affect the entire architecture of our applications. One of the core decisions web developers must make is where to implement logic and rendering in their application. This can be a difficult, since there are a number of different ways to build a website. Our understanding of this space is informed by our work in Chrome talking to large sites over the past few years. Broadly speaking, we would encourage developers to consider server rendering or static rendering over a full rehydration approach.

In order to better understand the architectures we’re choosing from when we make this decision, we need to have a solid understanding of each approach and consistent terminology to use when speaking about them. The differences between these approaches help illustrate the trade-offs of rendering on the web through the lens of performance.

**Target publish date:** `<2019-07-25>`
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal `<add a link to your proposal doc>`
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by addyosmani** [comment]
@robdodson do you think an article of this length could still fit the current notion of a guide? We could split it up into much more granular small guides, but I am open to input here. I personally like it as is :)

**Comment by robdodson** [comment]
hm I'd have to read through the post to get a sense for whether or not we'd want to break it up.

Do you have a sense for a revised IA for /fast that you'd want this to fit into? Or would you just want it to be a blog post?

**Comment by robdodson** [comment]
The post is ~2600 words.

One option would be to break it into two posts. The first would cover the different types of rendering and the second would cover the two strategies + SEO considerations.

**Comment by robdodson** [comment]
Going to close this as stale because there's no immediate owner. Happy to reopen when there are concrete next steps.
