### ISSUE TITLE
Likes/Favorites/Claps counter

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/web.dev#1055]
**Is your feature request related to a problem? Please describe.**
I want to express my appreciation for an article

**Describe the solution you'd like**
A FAB or button at the top/bottom of the article that leverages my logged in state to allow me to express a like

**Describe alternatives you've considered**
Claps, favorites

**Additional context**
Would be rad if backed by firebase and live updated on the site as folks liked it

**Comment by carolrivero** [comment]
Moving to an internal tracking tool
