### ISSUE TITLE
content: Native lazy loading

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1059]
**Author**: @housseindjirdeh 
**Reviewer**: @mfriesenhahn 

**A one to two sentence description of your post**
This post covers the loading attribute and how it can be used to defer the loading of images and iframes.

**Target publish date:** `<2019-07-16>`
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal `note- skipped because this post predates the current process.`
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1016 
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by Malvoz** [comment]
Just noting that once this has landed, the link "_Use lazysizes to lazyload images_" here: https://web.dev/fast#optimize-your-images should perhaps link to this content instead?

**Comment by mfriesenhahn** [comment]
Hey, @housseindjirdeh, since we're waiting to hear back about when this post can land, we're going to move it to the next sprint.

**Comment by housseindjirdeh** [comment]
Sounds good, thanks @mfriesenhahn!
