### ISSUE TITLE
content: Route-level code-splitting in Angular

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1060]
**A one to two sentence description of your post**
What are you planning to teach folks in this post?

**Target publish date:** `<2019-07-16>`
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal https://docs.google.com/document/d/1DtfQF9wFB01CZjjUCf091eWmaMr8it6b7tnj279ByVQ/edit
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1113
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by mgechev** [comment]
I'm on it.

**Comment by milky2028** [comment]
Hello! This article is great! One thing though, it makes mention of component-level code-splitting, but doesn't provide any feedback on how to do so. It's also currently the first result when you Google "angular code split components."

**Comment by mgechev** [comment]
Hope we'll update/add content after the version 9 release.

**Comment by milky2028** [comment]
Thank you!

**Comment by mgechev** [comment]
@milky2028 since we're planning simplification of the APIs in version 10, it'll be best to delay the content until then. I'm sure that after the Ivy release more and more folks will blog about component-level code-splitting, which should fix the search engine ranking.

**Comment by milky2028** [comment]
Thanks! I really appreciate your sharing where you guys are heading with this. And the component-based code-splitting is a huge win as well.
