### ISSUE TITLE
Wiki: overview section typo

### ISSUE THREAD

**Issue by IvanBila** [GoogleChrome/web.dev#1062]
**Describe the bug**
I think there is a typo on the overview section of the wiki, borne was used instead of born.

**To Reproduce**
Visit [Overview](https://github.com/GoogleChrome/web.dev/wiki/Overview)

**Screenshots**
![Screenshot from 2019-06-27 19-34-31](https://user-images.githubusercontent.com/13482373/60287779-093e0a80-9913-11e9-8882-4fe3490db351.png)

**Comment by robdodson** [comment]
I had to look this up :) I think "borne" may be technically correct

![image](https://user-images.githubusercontent.com/1066253/60306119-e0f2e380-98f3-11e9-960d-55e8b90a9d44.png)
