### ISSUE TITLE
content: CSS backdrop-filter

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1064]
**A one to two sentence description of your post**
Blog post showing folks how to use the new CSS backdrop-filter property.

**Target publish date:** `<2019-07-30>`
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal `note-this predates the current process`
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1131
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by argyleink** [comment]
accepted many suggestions
asked a few questions
didnt accept a few suggestions
made a decent amount of updates to the article, find them here: https://deploy-preview-1038--web-dev-staging.netlify.com/backdrop-filter/

**Comment by mfriesenhahn** [comment]
Moving to next sprint since we need input from @argyleink.
