### ISSUE TITLE
content: Faster Web Navigations with Predictive Prefetching

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1066]
**A one to two sentence description of your post**
Code-splitting allows you to speed up your applications, but it may slow down subsequent-navigations. Predictive prefetching is an efficient way to empower data analytics to smartly prefetch what the user is likely to use next, optimizing the network utilization.

**Target publish date:** `2019-07-08`
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal `note-predates current process so these steps were skipped.`
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1052 
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by robdodson** [comment]
@mgechev we're planning to roll this out Monday after the break 👍

**Comment by mgechev** [comment]
Sounds good! Thanks!

**Comment by robdodson** [comment]
This is now live @ https://web.dev/predictive-prefetching

Thank you for all your work on this @mgechev!
