### ISSUE TITLE
content: Set up static server-side rendering with Angular

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1070]
**Author**: @MarkPieszak
**Reviewer**: @mfriesenhahn

**A one to two sentence description of your post**
What are you planning to teach folks in this post?

**Target publish date:** `<2019-08-14>`
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal https://docs.google.com/document/d/1dhNTymO5UW03AGeIhbZgblSYED09CvBbivKgCcsHKeo/edit
- [x] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by mgechev** [comment]
I can take this!

**Comment by MarkPieszak** [comment]
Commenting here so you can find me @mfriesenhahn ! :) 
Let me know if you're all set reviewing/editing and I should start applying those requested updates.

**Comment by mfriesenhahn** [comment]
Many thanks!

**Comment by carolrivero** [comment]
@MarkPieszak will have a new draft by Aug 9

**Comment by carolrivero** [comment]
@MarkPieszak - please provide an update on draft. Thanks.

**Comment by kaycebasques** [comment]
Mark is still drafting

**Comment by kaycebasques** [comment]
When Mark & Michael finalize the draft, Michael will submit the PR

**Comment by robdodson** [comment]
Going to close as stale but happy to reopen if folks are still working on this.

**Comment by mfriesenhahn** [comment]
Actually, @mgechev just emailed me about finishing this up on Thursday. I pinged @kaycebasques to check on priorities.

**Comment by kaycebasques** [comment]
Carol and I will discuss this shortly.

**Comment by kaycebasques** [comment]
This work seems to have stalled so I'm going to close the issue.
