### ISSUE TITLE
content: Set up dynamic server-side rendering with Angular

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1071]
**Author**: @MarkPieszak
**Reviewer**: @mfriesenhahn

**A one to two sentence description of your post**
What are you planning to teach folks in this post?

**Target publish date:** `<2019-08-14>`
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal https://docs.google.com/document/d/1zZhhmadfm6BhcygUk1U7m1Gc2r969ZTsR6pwPW6l3mA/edit#heading=h.ikawx3mcorf4
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1591
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by mgechev** [comment]
I can take this!

**Comment by carolrivero** [comment]
mfriesenhahn meeting w/ Minko and Mark this Fri.

**Comment by MarkPieszak** [comment]
👋
Will post Docs links to rough outline for new content asap

**Comment by carolrivero** [comment]
@MarkPieszak will have a new draft by Aug 9

**Comment by carolrivero** [comment]
@MarkPieszak - please provide an update to comments provided. Thanks.

**Comment by kaycebasques** [comment]
Minko will get back to @mfriesenhahn about this next week

**Comment by MarkPieszak** [comment]
PR almost finished, will post here when submitted!

Apologies for any delay everyone! Thank you 🙏

**Comment by kaycebasques** [comment]
There are some suggestions for Mark to address and then this will be done.

**Comment by carolrivero** [comment]
@mfriesenhahn to follow up w/ @MarkPieszak

**Comment by kaycebasques** [comment]
This work seems to have stalled so I'm going to close the issue.
