### ISSUE TITLE
content: Using Signed HTTP Exchanges

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web.dev#1075]
**A one to two sentence description of your post**
What are you planning to teach folks in this post?

> Signed HTTP Exchange (or "SXG") is a subset of the emerging technology called Web Packages, which enables publishers to safely make their content portable, i.e. available for redistribution by other parties, while still keeping the content’s integrity and attribution. Portable content has many benefits, from enabling faster content delivery to facilitating content sharing between users, and simpler offline experiences.

This article would migrate (and refresh) the material currently in https://developers.google.com/web/updates/2018/11/signed-exchanges. We are currently thinking this would initially move across as a blog post on /blog.

**Target publish date:** `<2019-08-10>`
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal `<add a link to your proposal doc>`
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by robdodson** [comment]
Going to close as stale as it seems like there hasn't been any progress. Happy to reopen if we plan to work on this in the near term.
