### ISSUE TITLE
content: HTTP/2 Server Push is problematic

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web.dev#1081]
**A one to two sentence description of your post**
What are you planning to teach folks in this post?

Chrome is likely to disable HTTP/2 Server Push at some point in the not too distant future. Until we are in a position to post an intent-to-deprecate, we would like to publish a blog post on why H/2 Push remains a footgun. We believe this content will be equally useful for developers targeting other browsers. This would be an updated position on Jake's existing (well known) piece https://jakearchibald.com/2017/h2-push-tougher-than-i-thought/. 

As this is not your typical guidance that we think will fold into /fast over time (we wouldn't for example have an article on AppCache in there), we think a blog post is a format that works best here.

**Target publish date:** `<2019-08-01>`
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal `<add a link to your proposal doc>`
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by robdodson** [comment]
Going to close as stale as it seems like there hasn't been any progress. Happy to reopen if we plan to work on this in the near term.
