### ISSUE TITLE
Improve connection between 1st use of a key term and the related aside

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1088]
**Problem**
When a key term aside is placed _after_ the first use of the term, the user doesn't immediately know that a definition has been provided, which may lead them to start googling before they read on. However, if the aside is placed _before_ the first use of the term, the user doesn't know why the definition matters since they don't yet have the relevant context.

**Proposed solution**
Provide a short code that creates a visual indicator on the first use of a key term to convey to the reader that a definition is coming. The ideal solution won't be _too_ assertive to avoid completely disrupting the reading process. Possibilities:
- Bold the term and apply the key-term aside color.
- Add the key-term icon immediately after the term.
- Both. (Perhaps a bit much.)

**Additional context**
A larger problem with current aside styling is that they disrupt the flow of the body copy. This issue is especially relevant for key term definitions, which are really only there if you need them and would ideally be easily ignorable--or hidden--if you don't. One way other content platforms handle this is to stick key terms in popups. That won't work for other aside types, though, so an alternative strategy is to place asides to the right or left of the main body column when there's sufficient room in the viewport. For reference, Vulture uses a combination of both approaches: https://www.vulture.com/2019/06/always-be-my-maybe-i-punched-keanu-reeves-song-lyrics.html

**Comment by jpmedley** [comment]
A traditional way of doing this would be to define the terms within the flow of the text, with the term itself italicized. Icons within the flow of text should be avoided so that the text does not start to look like a ransom note.

**Comment by mfriesenhahn** [comment]
Other references:

- [Grantland](https://grantland.com/features/blades-of-glory/)
- [Bloomberg](https://www.bloomberg.com/features/2019-workers-of-the-world/)
