### ISSUE TITLE
Fast content: Responsive image preloading 

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web.dev#1090]
**A one to two sentence description of your post**
What are you planning to teach folks in this post?

> We recently shipped support for imagesrcset and imagesizes attributes on <link rel=preload as=image>, that correspond to the srcset and sizes attributes of HTMLImageElement. This allows sites to preload responsive images, such as those needed for above the fold content like hero images and logos. https://chromestatus.com/features/5164259990306816

**Target publish date:** `<2019-07-20>`
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal `<add a link to your proposal doc>`
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by robdodson** [comment]
I think https://github.com/GoogleChrome/web.dev/issues/1136 is referring to this so I'm going to close. Feel free to reopen if I'm mistaken.
