### ISSUE TITLE
Fast content: Signed Exchange Subresource prefetching (Origin Trial)

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web.dev#1091]
**A one to two sentence description of your post**
What are you planning to teach folks in this post?

Support for prefetching signed exchange subresources will be coming to Chrome via an Origin Trial within the next few quarters. The team would like to write an article about why this matters, what it enables and where it fits in with https://github.com/GoogleChrome/web.dev/issues/1075 (once migrated) in a blog post form.

**Target publish date:** `<2017-09-20>`
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal `<add a link to your proposal doc>`
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by robdodson** [comment]
Going to close as stale as it seems like there hasn't been any progress. Happy to reopen if we plan to work on this in the near term.
