### ISSUE TITLE
content: Efficiently load third-party JavaScript

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/web.dev#1098]
**Author**: @mihajlija
**Reviewer**: @katejeffreys

**A one to two sentence description of your post**
Explain techniques for optimizing the loading process of third-party scripts. 

**Target publish date:** `<2019-08-14>`
- [ ] Check this box if this is a hard deadline.

**Process**

- [x] 1. I've done my proposal https://docs.google.com/document/d/1oxgb1MxXOjrL7RSSrgx3f4JYiw4_nPudltwB63uly2Y/edit?usp=sharing
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1221
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@katejeffreys reviewed and approved.
