### ISSUE TITLE
Issue with & not being escaped / not being included in ?url= param

### ISSUE THREAD

**Issue by gmspromo** [GoogleChrome/web.dev#1105]
I'm having an issue with testing PHP pages with more than one GET variable attached to them; trying to view the results page throws an error.
Take the following example;

test.php?variable1=one&variable2=two

I think the issue relates to the ampersand ... if I escape it/replace it with %26 then *sometimes* (not often but sometimes) I can view the results page, but it seems hit and miss. Is there something I am doing that causes this problem or is this an actual error?

A live example of a page I am trying to test is this;

https://www.romaheritage.co.uk/beta/search.php?forename=&surname=small&rec_type=baptisms&firstyear=&lastyear=&fforename=&mforename=&submit=Search

**Comment by robdodson** [comment]
ah I see. So when you click `View results` and try to navigate to https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://www.romaheritage.co.uk/beta/search.php?forename=&surname=small&rec_type=baptisms&firstyear=&lastyear=&fforename=&mforename=&submit=Search it breaks.

I'll see if we can fit this into our next sprint.
