### ISSUE TITLE
content: Optimize Loading Performance for Feature Phones

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web.dev#1109]
**A one to two sentence description of your post**
What are you planning to teach folks in this post?

The purpose of this blog post is to educate developers about specific loading performance techniques that can help when they're building for very constrained low-end feature phones. The audience are 

**Target publish date:** `<2019-07-15>` (tentative, can move)
- [ ] Check this box if this is a hard deadline.

**Process**

- [ ] 1. I've done my proposal https://docs.google.com/document/d/1COssHz5gT6w0hNbb9ErIpxTU35wGf4dR-fy9_-vfVzE/edit#
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by robdodson** [comment]
@addyosmani are you the author for this?

**Comment by carolrivero** [comment]
We'll be tracking this one in buganizer and add it to our feature phone work.
