### ISSUE TITLE
content: Fast content - Fixing speed - cross-functionally

### ISSUE THREAD

**Issue by linachansson** [GoogleChrome/web.dev#1110]
**Solving site speed is not only dependent on developers – they need the help from marketing, web designers, the analytics team and stakeholders to succeed. These four articles describe how developers can set up collaboration with each department, and get great help in fixing speed.**
What are you planning to teach folks in this post?

**Target publish date:** `<yyyy-mm-dd>`
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [X] 1. I've done my proposal `<https://docs.google.com/document/d/1L7j3qG4-pbKBu52BmX_p4rcERiIMUzxFX8YNoAxDdug/edit?usp=sharing>`
- [ ] 2. Proposal approved — _reviewer checks this_
- [X] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by robdodson** [comment]
Hey @linachansson thanks for opening this. We recently implemented a sprint process for reviewing content so we should be able to triage this post during our next sprint planning meeting next week.

**Comment by kaycebasques** [comment]
Howdy @linachansson this proposal fell through the cracks, but it seems like potentially interesting content. I'd be happy to revisit this if you're still interested.
