### ISSUE TITLE
content: link to Jason's modern script loading doc in the serve modern code guide

### ISSUE THREAD

**Issue by housseindjirdeh** [GoogleChrome/web.dev#1116]
In the [Serve modern code](https://web.dev/serve-modern-code-to-modern-browsers/) guide, we tell readers to use the module/nomodule pattern to minimize the amount of unnecessary polyfilled shipped to newer browsers:

```
<script type="module" src="main.mjs"></script>
<script nomodule src="compiled.js"></script>
```

Although useful, this has been found to [double-fetch](https://gist.github.com/jakub-g/5fc11af85a061ca29cc84892f1059fec) in certain versions of Edge and Safari.

We should include a note about this and point readers to an article that explains more. @developit published a [post](https://jasonformat.com/modern-script-loading/) that lists a few options to circumvent this.

**Comment by robdodson** [comment]
That sounds good to me. Are you ok doing a PR to add this @housseindjirdeh ?

**Comment by housseindjirdeh** [comment]
Done! #1135 adds a note 🕺
