### ISSUE TITLE
updating "use lazysizes to lazyload images" guide when native lazy loading article is shipped

### ISSUE THREAD

**Issue by housseindjirdeh** [GoogleChrome/web.dev#1120]
There's an open PR (#1016) that lands a native lazy loading article (`<img loading="lazy">`) to the blog. We currently have a [guide/codelab](https://web.dev/use-lazysizes-to-lazyload-images/) that shows readers how to use lazysizes to lazy load images and we should probably update it when the native lazy loading post lands.

Thoughts on what we can do:

1. Add a note/section early in the article that points readers to the blog post and mentions that they should try to only use lazysizes as a fallback for other browsers (and that they can find more details in the post)
2. Update the entire guide and codelab to show developers how to use the `loading` attribute along with lazysizes as a polyfill 

Although I think option 2 should be the long-term goal, it may take a few Chrome releases for the final spec-revised version of the `loading` attribute to land, so I think option 1 can work for the meantime until things settle.

Thoughts?

@khempenius @addyosmani @Malvoz

**Comment by robdodson** [comment]
I'm a fan of option 1 for now. Do you want to update that blog post in your same PR?

**Comment by housseindjirdeh** [comment]
Pushed a [commit](https://github.com/GoogleChrome/web.dev/pull/1016/commits/69bddf9622f4615ecfe4c02a2c19c0c648d3ee7e) that adds a note!

**Comment by housseindjirdeh** [comment]
We can close this issue when the PR gets merged (and re-open it if we decide to update the whole guide)

**Comment by robdodson** [comment]
I'm going to close this as (tentatively) fixed just to make sprint planning a bit easier.
