### ISSUE TITLE
content: Blog post for CSS pseudo-class :picture-in-picture

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1121]
**A one to two sentence description of your post**
A basic how-to article describing the CSS pseudo-class :picture-in-picture, which helps web developers customize the media player when videos enter and exit Picture-in-Picture.

**Target publish date:** 2019-09-19
- [x] Check this box if this is a hard deadline.

**Chrome Status entry:** https://www.chromestatus.com/feature/6259534815297536

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal `<add a link to your proposal doc>`
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by robdodson** [comment]
Wanted to include a link to the handbook in case folks haven't seen it yet. I've updated the content proposal template so future tickets will include this link.

https://web.dev/handbook

**Comment by jpmedley** [comment]
@beaufortfrancois I've gone ahead and assigned this to you even though it's not part of a beta release yet. This will help keep it on our radar.

**Comment by beaufortfrancois** [comment]
Thank you!

**Comment by robdodson** [comment]
Hey @beaufortfrancois were you planning to work on this during the next two weeks or were you going to wait till the next Chrome release? I wanted to know if we should budget time for a review of the article.

**Comment by beaufortfrancois** [comment]
We still want to see how the [Picture-in-Picture V2 API](https://github.com/WICG/picture-in-picture/issues/113) is gonna be before launching this as it could impact how this pseudo-class is specified.

So I'd definitely wait until the next Chrome release. No need to budget time for this yet. 

Thank you!

**Comment by jpmedley** [comment]
This ticket isn't stale because it's less of a priority. It's stale because the feature it supports is stuck in development.

**Comment by robdodson** [comment]
>  It's stale because the feature it supports is stuck in development.

I think in that case it may still make sense to let the bot close the ticket and reopen it when the feature seems closer to shipping
