### ISSUE TITLE
content: Blog post for CSS Properties and Values API L1

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1122]
**Author**: @Snugug
**Reviewer**: @jpmedley

**A one to two sentence description of your post**
A basic how-to article describing the CSS Properties and Values API Level 1 (Houdini), which is an API that expands the existing CSS custom properties to improve usability of other Houdini APIs.

**Target publish date:** `2019-09-19`
- [x] Check this box if this is a hard deadline.

**Chrome Status entry:** https://www.chromestatus.com/feature/5640265926705152

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal https://docs.google.com/document/d/14QeJKjqVV0nD3w0S6E0Afcimp041cEeYaMMdSIsYfRU/edit?usp=sharing
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request `#1497`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by Snugug** [comment]
I'm happy to take this on!

**Comment by Snugug** [comment]
Here is my content proposal, pre-draft. Once we're all sorted I'll start writing the draft
https://docs.google.com/document/d/14QeJKjqVV0nD3w0S6E0Afcimp041cEeYaMMdSIsYfRU/edit#

**Comment by robdodson** [comment]
Hey @Snugug thank you for putting together the outline. We're going to be doing a big sprint planning next week on Wednesday and should be able to pull in the proposal for review then. Is that ok?

**Comment by jpmedley** [comment]
The feature this is related to is [no longer shipping in 77](https://groups.google.com/a/chromium.org/forum/?utm_medium=email&utm_source=footer#!msg/blink-dev/QjcyhPZ_sNI/KRR77NZOCwAJ).

**Comment by jpmedley** [comment]
I've taken this as far as it can go. Does someone else need to do the merge? Regardless, this needs to be published before the beta release post. Can someone get to this today?

**Comment by jpmedley** [comment]
@robdodson @mfriesenhahn

**Comment by robdodson** [comment]
yeah i can take a look at the PR

**Comment by robdodson** [comment]
Added a few small comments. Assigning back to @jpmedley.

**Comment by Snugug** [comment]
Thanks y'all!

**Comment by jpmedley** [comment]
Thank you.
