### ISSUE TITLE
content: Blog post for Form-associated custom elements

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1124]
**Author**: @arthurevans 
**Reviewer**: @jpmedley 

**A one to two sentence description of your post**
A basic how-to article describing Form-associated custom elements, which enable web authors to define and create custom elements which participate in form submission.

**Target publish date:** `2019-08-08`
- [x] Check this box if this is a hard deadline.

**Chrome Status entry:** https://www.chromestatus.com/feature/4708990554472448

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal `<add a link to your proposal doc>`
- [ ] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc https://docs.google.com/document/d/1yEIPq1d6_MbF2Uchq1PHk352_qZ1Z-EmgxqCmpJJd_M/edit
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request `#1287`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by robdodson** [comment]
@azakus

**Comment by robdodson** [comment]
Wanted to include a link to the handbook in case folks haven't seen it yet. I've updated the content proposal template so future tickets will include this link.

https://web.dev/handbook

**Comment by carolrivero** [comment]
Arthur is still writing - still needs to launch 8/8

**Comment by robdodson** [comment]
This post is live at https://web.dev/more-capable-form-controls/

**Comment by jpmedley** [comment]
Great!
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*
