### ISSUE TITLE
content: Blog post for Largest Contentful Paint

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1125]
**Author**: @philipwalton
**Reviewer**: @jpmedley

**A one to two sentence description of your post**
A basic conceptual article describing a new page load metric, which describes page speed as the speed of delivering the largest contentful element to the screen.

**Target publish date:** `2019-08-08`
- [x] Check this box if this is a hard deadline.

**Chrome Status entry:** https://www.chromestatus.com/feature/5666250908762112

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal `<add a link to your proposal doc>`
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request `#1266`
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by robdodson** [comment]
Wanted to include a link to the handbook in case folks haven't seen it yet. I've updated the content proposal template so future tickets will include this link.

https://web.dev/handbook

**Comment by carolrivero** [comment]
waiting on markdown conversion
