### ISSUE TITLE
content: Eliminate round-trips with rel=preconnect [codelab]

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/web.dev#1127]
**Author:** @mihajlija 
**Reviewer:** @jpmedley 

**A one to two sentence description of your post**
A codelab to go along with #1051 guide. It shows how to apply preconnects on a demo app and before/after wins. 

**Target publish date:** `<yyyy-mm-dd>`
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal https://docs.google.com/document/d/1y38Daq9UpqdJhFo3XTDjwAscb3AHLkxOtfW8ViAegLM/edit?usp=sharing
- [x] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by kaycebasques** [comment]
@mihajlija any update on this?

**Comment by mihajlija** [comment]
Added the proposal, I'll submit the draft on Monday but I don't think I'll be able to hit the publishing date in this sprint.

**Comment by mihajlija** [comment]
I got sidetracked with #1504 and ad speed content planning, so no draft yet. I do have two demo apps, the before/after difference is not very strong but I'll make it work. Expect the draft early next week.

**Comment by carolrivero** [comment]
@mihajlija - is this still a valid issue? There hasn't been movement since Sept. Thx.

**Comment by mihajlija** [comment]
@carolrivero Still valid. I talked to Addy and Phil Walton and the plan to tackle it after CDS posts.

**Comment by carolrivero** [comment]
@mihajlija Thanks for your quick response. I'll change the milestone to the next Dec milestone.

**Comment by kaycebasques** [comment]
Putting this in the Icebox until Milica resumes work.
