### ISSUE TITLE
content: Optimize third-party JavaScript

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/web.dev#1128]
**Author**: @mihajlija
**Reviewer**: @mfriesenhahn

**A one to two sentence description of your post**
A codelab to go along with #1098 guide. It shows how to apply async/defer, lazy-loading, and preconnect on a demo app to improve performance.

**Target publish date:** `<2019-08-14>`
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal https://docs.google.com/document/d/1noEHdWIMpgT_dHqMT0OPtNVaF_b6nsAMwRUT3CjGDxM/
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request  #1276
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
Need to create images and video and need to code review tomorrow

**Comment by carolrivero** [comment]
@mfriesenhahn to resolve comments in code w/ @mihajlija
