### ISSUE TITLE
Add new cases to Instruction widget

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1133]
**Is your feature request related to a problem? Please describe.**
- The Instruction widget includes a `reload` case that contains an instruction to reload embedded sample apps, but the wording doesn't make sense for reloading a full page.
- There's no case for opening the DevTools **Command** menu, which is needed fairly often.

**Describe the solution you'd like**
- Add a `devtools-command` case that reads: "Press `Control+Shift+P` (or `Command+Shift+P` on Mac) to open the **Command** menu."
- Change the name of the current `reload` case to `reload-app`.
- Add a new `reload-page` case that reads: "Reload the page."

**Comment by mfriesenhahn** [comment]
Also need a case for creating a new file in a Glitch, as  @mihajlija pointed out.

**Comment by mihajlija** [comment]
@mfriesenhahn  I can take this if I'm absolved from the reviewing #1231 ? cc @robdodson

**Comment by mfriesenhahn** [comment]
> @mfriesenhahn I can take this if I'm absolved from reviewing #1231 ? cc @robdodson

Ha, I thought you already had because it was in code review :)

So, yes, you are absolved. Go forth and create wondrous short codes!
