### ISSUE TITLE
content: Preloading responsive images

### ISSUE THREAD

**Issue by yoavweiss** [GoogleChrome/web.dev#1136]
**Author**: @yoavweiss 
**Reviewer**: @mihajlija 

[Proposed article](https://docs.google.com/document/d/1YUKCRFNjWX1gWwVrQmeUfkcjSVdRPlwwGkSecmk6M3E/edit#)

**A one to two sentence description of your post**
This post will explain the recently shipped responsive image preload feature, how to use it and its benefits.

**Target publish date:** 8/14/2019
- [ ] Check this box if this is a hard deadline.

**Process**
Make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my [proposal](https://docs.google.com/document/d/12G-2yQsM3dDwYyKlyOQ4nNFD7ac0D8e7-ERcytbNEsg/edit?usp=sharing)
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1555 
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by yoavweiss** [comment]
Friendly ping! :)

**Comment by carolrivero** [comment]
@yoavweiss - your post was moved to the sprint ending on 8/28. Thanks.

**Comment by robdodson** [comment]
If it's ok I'd like to take a shot at reviewing this because it's been in the queue for quite some time. I'll add it to the current sprint and assign it to myself.

**Comment by robdodson** [comment]
Added comments to the draft doc. Assigning back to @yoavweiss for him to rework. Give me a shout when you're ready for another look :)

**Comment by carolrivero** [comment]
@yoavweiss to work on this when he's back on Aug 8.

**Comment by carolrivero** [comment]
@yoavweiss - please provide an update to feedback from @mihajlija

**Comment by yoavweiss** [comment]
Currently OOO (again) - will provide feedback on Friday when I'm back

**Comment by carolrivero** [comment]
@yoavweiss - please provide an update. thanks.

**Comment by yoavweiss** [comment]
Responded to feedback

**Comment by kaycebasques** [comment]
@mihajlija it seems like you're up for review

**Comment by robdodson** [comment]
@kaycebasques Milica pinged you in the doc for a few editorial questions.

**Comment by kaycebasques** [comment]
@robdodson @mihajlija thanks, checking out now. Next time please re-assign the issue to me. It's hard for me to keep track of what's blocked on me unless I'm assigned...

**Comment by kaycebasques** [comment]
I responded to the comments in the doc that were addressed to me. Back to @mihajlija to finish her review, or @yoavweiss to incorporate the feedback. @mihajlija if you're finished reviewing then please assign this to @yoavweiss. Thank you.

**Comment by kaycebasques** [comment]
I am reviewing the post now

**Comment by kaycebasques** [comment]
@yoavweiss good stuff. Please address my feedback and then proceed straight to drafting the PR.

**Comment by mihajlija** [comment]
I can pick up the code review this week.

**Comment by kaycebasques** [comment]
@yoavweiss to submit PR

**Comment by kaycebasques** [comment]
@yoavweiss, @mihajlija is going to submit the PR because she has free time.

**Comment by kaycebasques** [comment]
I reviewed the PR and asked @mihajlija to make a few small changes.

**Comment by mihajlija** [comment]
I've updated the PR and asked @robdodson for help with adding author profile pics.

**Comment by yoavweiss** [comment]
> @yoavweiss, @mihajlija is going to submit the PR because she has free time.

Thanks @mihajlija! Apologies for lack of responsiveness (TPAC travel...)

**Comment by kaycebasques** [comment]
Looks like the only thing left is for @mihajlija to add Yoav's profile image and then this can be merged

**Comment by kaycebasques** [comment]
Milica added author image so @robdodson is up to review and merge

**Comment by robdodson** [comment]
this post is now live @ https://web.dev/preload-responsive-images/
