### ISSUE TITLE
content: Image CDN article

### ISSUE THREAD

**Issue by khempenius** [GoogleChrome/web.dev#1144]
**Author**: @khempenius
**Reviewer**: @mihajlija

**A one to two sentence description of your post**
Overview of image CDNs.

What are you planning to teach folks in this post?
How image CDNs work, how to use them, how to choose, etc.

**Target publish date:** `<2019-08-14>`

- [ ] Check this box if this is a hard deadline.

**Process**

- [x] 1. I've done my [proposal](https://docs.google.com/document/d/1g6sXM1zY49YQsUkmnxfnc9SpVpTcncYKb97B3Dvr5CI/edit?usp=sharing)
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1215
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by kaycebasques** [comment]
Draft LGTM

**Comment by carolrivero** [comment]
Need to confirm a few things will go out today.
