### ISSUE TITLE
content: Codelab: Use imgix to optimize images

### ISSUE THREAD

**Issue by khempenius** [GoogleChrome/web.dev#1145]
**Author**: @khempenius
**Reviewer**: @kaycebasques

**A one to two sentence description of your post**
Codelab on imgix.

What are you planning to teach folks in this post?
How to optimize images with imgix.
Parent article: "Use Image CDNs to optimize images" (https://github.com/GoogleChrome/web.dev/issues/1144)

**Target publish date:** 2019-08-14

- [ ] Check this box if this is a hard deadline.

**Process**

- [x] 1. I've done my [proposal](https://docs.google.com/document/d/18d0tIv1kak2KomUUfkflGTuglw-agJOas78fknXpXAU/edit?usp=sharing)
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1321
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
What is the status of this review?

**Comment by khempenius** [comment]
@kaycebasques has reviewed this and the doc has LGTM.

**Comment by kaycebasques** [comment]
Yes LGTM

**Comment by carolrivero** [comment]
@khempenius - please provide an update on PR. Thanks.

**Comment by khempenius** [comment]
Imgix (@sherwinski - I think?) will be opening the PR for this.

**Comment by sherwinski** [comment]
Yep! I'll be opening a PR either today or tomorrow. Thanks

**Comment by carolrivero** [comment]
@kaycebasques will review the PR today.

**Comment by kaycebasques** [comment]
I reviewed the doc. @sherwinski or @cindy-imgix are going to address my feedback.

**Comment by kaycebasques** [comment]
@sherwinski will be the one updating the doc to address my feedback but is on vacation until Aug 20

**Comment by kaycebasques** [comment]
Work is being completed in #1321. This [comment](https://github.com/GoogleChrome/web.dev/pull/1254#issuecomment-520923896) gives context on why the work was moved to another PR.

**Comment by kaycebasques** [comment]
@robdodson or @mfriesenhahn or @khempenius need to approve PR #1321
