### ISSUE TITLE
codelab: Use Akamai Image Manager to optimize images

### ISSUE THREAD

**Issue by khempenius** [GoogleChrome/web.dev#1147]
**A one to two sentence description of your post**
Codelab on Akamai Image Manager.

What are you planning to teach folks in this post?
How to optimize images with Akamai Image Manager.
Parent article: "Use Image CDNs to optimize images" (https://github.com/GoogleChrome/web.dev/issues/1144)

**Target publish date:** `<2019-07-31>`

- [ ] Check this box if this is a hard deadline.

**Process**

- [ ] 1. I've done my [proposal](https://docs.google.com/document/d/1bqEnuvD2w8Y_WDLQk5JdwO-64Oc9TdTvDXVvaltAYKw/edit?usp=sharing)
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by robdodson** [comment]
Going to close as stale as it seems like there hasn't been any progress. Happy to reopen if we plan to work on this in the near term.
