### ISSUE TITLE
blog: How to Install Thumbor

### ISSUE THREAD

**Issue by khempenius** [GoogleChrome/web.dev#1148]
**Author**: @khempenius
**Reviewer**: @kaycebasques

**A one to two sentence description of your post**
Instructions on how to install Thumbor.

What are you planning to teach folks in this post?
How to install Thumbor.

**Target publish date:** `2019-08-14`

- [ ] Check this box if this is a hard deadline.

**Process**

- [x] 1. I've done my [proposal](https://docs.google.com/document/d/1SSq8tkwYfNn2bGbp_eqIlA6VsV-IE8q47PnSzUVUz3I/edit?usp=sharing)
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — @kaycebasques LGTM
- [x] 5. I've submitted a pull request #1214
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@kaycebasques - could I ask you to review the PR? And mfriesenhahn will take a look. Thanks.

**Comment by carolrivero** [comment]
@kaycebasques to review the PR today.

**Comment by kaycebasques** [comment]
I reviewed the doc and asked @khempenius to make some changes

**Comment by kaycebasques** [comment]
I've reviewed @khempenius changes and LGTM'd the PR
