### ISSUE TITLE
codelab: Use Thumbor to optimize images

### ISSUE THREAD

**Issue by khempenius** [GoogleChrome/web.dev#1149]
**A one to two sentence description of your post**
Codelab on using Thumbor.

Author: @khempenius 
Reviewer: @mihajlija 

**What are you planning to teach folks in this post?**
How to optimize images with Thumbor.
Related blog post: "How to Install Thumbor" (https://github.com/GoogleChrome/web.dev/issues/1148)

**Target publish date:** `<2019-07-31>`

- [ ] Check this box if this is a hard deadline.

**Process**

- [x] 1. I've done my [proposal](https://docs.google.com/document/d/1cfFyi0EaCJF3iEjiYWffWVgrf9ruwMVzQxF0peT3y08/edit?usp=sharing)
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1490
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by robdodson** [comment]
oh @mfriesenhahn I just noticed this was in the current sprint but not on the project board yet. Seems like it's been delayed a fair amount and we should try to roll it out if we can.

**Comment by carolrivero** [comment]
@khempenius - do we still want to launch this one? If so, do you have a date in mind? I'm going to remove this from the milestone for now until we make a decision on the date.

**Comment by khempenius** [comment]
@carolrivero Yes, we still want to launch this. Date is flexible, but ideally as soon as possible. This was originally going to go out with the other image CDN content at the end of July.

**Comment by carolrivero** [comment]
@robdodson Added this to the Sprint 2019-09-11 and assigned review to @mihajlija for now. Thanks.

**Comment by carolrivero** [comment]
@kaycebasques - please review draft.

**Comment by kaycebasques** [comment]
Will get to this today

**Comment by kaycebasques** [comment]
Howdy @khempenius good start. Would you please address my feedback and then assign this issue back on me when you're done. FYI I didn't get to the end of the post, so I might have another round of feedback after this.

**Comment by kaycebasques** [comment]
Kayce is reviewing today

**Comment by kaycebasques** [comment]
@khempenius please address the feedback I left in the doc and then you can go straight to submitting the PR.

**Comment by kaycebasques** [comment]
Just reviewed. Back to @khempenius to make the requested changes.

**Comment by khempenius** [comment]
Changes made. Assigning back to @kaycebasques

**Comment by kaycebasques** [comment]
@khempenius just a couple small formatting bugs in the rendered page to address

**Comment by kaycebasques** [comment]
Will review today

**Comment by kaycebasques** [comment]
LGTM. Needs @robdodson's code owner review to merge.

**Comment by robdodson** [comment]
added one comment on the PR

**Comment by kaycebasques** [comment]
@kaycebasques to merge the doc
