### ISSUE TITLE
content: "Game Over: Principles of a good first time user experience in web games"

### ISSUE THREAD

**Issue by tcmg** [GoogleChrome/web.dev#1151]
**A one to two sentence description of your post**

Many game developers design their games with complex systems, interfaces and “assumed knowledge” of the player. They don’t realise how easy it is to lose a user during the first few minutes of them playing a game (i.e. the user churns from game) and how critical the user’s first-time user experience is including both the technical loading time of the page and how the beginning of the game is design (tutorialisation, pacing, game difficulty and complexity). This post will highlight to game developers the importance of creating an excellent initial user experience. 

**Target publish date:** 2019-08-12

- [ ] Check this box if this is a hard deadline.

**Process**

https://docs.google.com/document/d/1tCXEk8xCNfPdxsqlCsf-fVTmsaamV04zF1oTb9HTTok/edit#heading=h.dsyrc6p9wo1s

- [X] 1. I've done my proposal `<add a link to your proposal doc>`
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by robdodson** [comment]
Going to close as stale as it seems like there hasn't been any progress. Happy to reopen if we plan to work on this in the near term.
