### ISSUE TITLE
content: Games on Web.Dev - Section Plan

### ISSUE THREAD

**Issue by carolrivero** [GoogleChrome/web.dev#1152]
**Author**: @tcmg
**Reviewer**: @mfriesenhahn

**A one to two sentence description of your post**
Games on Web.Dev will be a new vertical section of web.dev that provides guidance across 3 pillars: game design, business and technical advice. These three topics will be explored through the cross section of two lenses: the web and games. The aim is to provide guidance that can help game developers understand the potential of supporting/exploring game development on the web.

**Target publish date:** TBD

- [ ] Check this box if this is a hard deadline.

**Process**

This document:

https://docs.google.com/document/d/1tCXEk8xCNfPdxsqlCsf-fVTmsaamV04zF1oTb9HTTok/edit

Provides an overall plan of all the content. We intend to launch with just the V1 content. Please review the overall structure and outlines of the proposals that have been completed thus far.

- [x] 1. I've done my proposal <https://docs.google.com/document/d/1tCXEk8xCNfPdxsqlCsf-fVTmsaamV04zF1oTb9HTTok/edit>
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
This is still in the 8/28 milestone - should this be moved to spring ending on Sept 11? Thanks.

**Comment by carolrivero** [comment]
@tcmg - do you have a date in mind for when you want to launch this one? This sprint is full - would the next one ending on 9/25 work? Thanks.

**Comment by tcmg** [comment]
Could we aim for the next sprint after 9/25 ?

I'm happy to aim for 9/25 but I already feel I'll need more time than that for this content.

**Comment by carolrivero** [comment]
@tcmg - added this to the spring ending on 10/09

**Comment by carolrivero** [comment]
@tcmg - is this issue still valid? There hasn't been movement since Sept. Thanks.

**Comment by robdodson** [comment]
Going to close as stale as it seems like there hasn't been any progress. Happy to reopen if we plan to work on this in the near term.
