### ISSUE TITLE
content: "Ready Player Web: Building games for the modern web"

### ISSUE THREAD

**Issue by tcmg** [GoogleChrome/web.dev#1153]
**Author**: @tcmg 
**Reviewer**: @kaycebasques 

**A one to two sentence description of your post**

To recap my Google I/O talk “Modern Web Game Development” and explain a few fundamental concepts of web games.

**Target publish date:** 2019-08-28

- [ ] Check this box if this is a hard deadline.

**Process**

https://docs.google.com/document/d/1dyNuzg2c6uvm3VmlHUc21tdKbRsX5uEgm8AlXr_QE2Q/edit#

- [x] 1. I've done my proposal `https://docs.google.com/document/d/1dyNuzg2c6uvm3VmlHUc21tdKbRsX5uEgm8AlXr_QE2Q/edit#`
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1289
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
Hey Kayce
Friendly nudge. Any updates you can provide is helpful as we're ending this sprint tomorrow. Thanks.

**Comment by kaycebasques** [comment]
There's a couple small changes in the doc but it mostly LGTM

**Comment by robdodson** [comment]
ok, next steps would be for @tcmg to turn it into a PR

**Comment by carolrivero** [comment]
@tcmg - please submit a PR for this one. Thanks.

**Comment by carolrivero** [comment]
@tcmg - is ready for us to review the PR? If so, please assign to @kaycebasques and check #5 and provide the PR number. Thanks.

**Comment by carolrivero** [comment]
note: I found the PR and updated the issue myself and reassigned the ticket to @kaycebasques

**Comment by kaycebasques** [comment]
I'll review on Monday

**Comment by kaycebasques** [comment]
Looking busy today. Planning to review tomorrow.

**Comment by kaycebasques** [comment]
Forgot to review on Friday. Just reviewed now. #1289 LGTM. Assigned to @robdodson.

**Comment by robdodson** [comment]
This is live now! https://web.dev/ready-player-web/
