### ISSUE TITLE
_include snippet explaining Origin Trials

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/web.dev#1163]
**Is your feature request related to a problem? Please describe.**
I'm writing a post for web.dev/blog explaining how to use a feature that's in Origin Trial. I don't want to have to explain _what_ an Origin Trial is.

**Describe the solution you'd like**
There should be boilerplate description of Origin Trials that can be pulled in to any post, via a file somewhere under https://github.com/GoogleChrome/web.dev/tree/master/src/site/_includes

**Comment by jeffposnick** [comment]
CC: @petele as I hear he has some language that he's prepared, which might be extractable.

**Comment by robdodson** [comment]
```
Origin trials allow you to try new features and give feedback on their usability, practicality, and effectiveness, both to us, and to the web standards community. For more information, see the [Origin Trials Guide for Web Developers][https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md].
```

**Comment by jeffposnick** [comment]
I'm not sure who the "us" refers to in "both to us".

I'm going to leave that out.
