### ISSUE TITLE
content: Progressive Web Apps in multi-origin sites

### ISSUE THREAD

**Issue by demianrenzulli** [GoogleChrome/web.dev#1166]
**Author**: @demianrenzulli
**Reviewer**: @jpmedley 

**A one to two sentence description of your post**

Multi-origin architectures can present many challenges. In particular, the same-origin policy, imposes restrictions for sharing things like Service Workers and caches, permissions, and for achieving a standalone experience across multiple origins.
The article explains these challenges in detail, proposes workarounds and guides developers on the right long term strategy for cases like these.

**Target publish date:** `<2019-08-14>`

- [X] Check this box if this is a hard deadline.

**Process**

- [X] 1. I've done my proposal. [Link](https://docs.google.com/document/d/1LMh892LZPGXxpV8gIEMR8G-7NuYpKiiqB69BqEmY9OQ/edit?usp=sharing)
- [X] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1322
- [x] 6. Pull request approved — _reviewer checks this_

Note: For context, this article has been initially proposed to @b1tr0t, and it's in complete state.
It was reviewed by @dominickng, Paul Covell and @petele (that's why "Proposal Approved" is checked, and it doesn't include a separate template for the proposal).
This is a PWA article, which in the absence of a PWA section could work as a blog post.

Any thoughts or change to this submission are highly welcomed.

cc // @robdodson

**Comment by jpmedley** [comment]
I've requested a few more changes from Demián. I'm hoping we'll move to the next stage tomorrow.

**Comment by demianrenzulli** [comment]
Note: changes suggested by @jpmedley have been added in the doc.

**Comment by carolrivero** [comment]
@jpmedley - Can we mark this one as ready for coding? Thanks.

**Comment by jpmedley** [comment]
Yes.

**Comment by demianrenzulli** [comment]
@jpmedley thanks again for all the help and guidance during the process.

@carolrivero moving forward with the coding today.

**Comment by demianrenzulli** [comment]
@carolrivero just submitted the PR (#1322), checked the corresponding field and added it to the form, at the beginning of this issue.

**Comment by robdodson** [comment]
This post is now live! https://web.dev/multi-origin-pwas/

**Comment by demianrenzulli** [comment]
This is great Rob, thank you!
