### ISSUE TITLE
content: add/move perf budget content for Angular and React 

### ISSUE THREAD

**Issue by housseindjirdeh** [GoogleChrome/web.dev#1167]
There's an entire section in web.dev/fast that captures [performance budgeting](https://web.dev/fast#set-performance-budgets). We should make sure every framework collection of guides also includes guide(s) on how to set and use budgets effectively.

* For React: There currently is no guide that explains how to set performance budgets. We'll need to create a new one.
  - Create React App doesn't support performance budgeting. Is there a React-specific guide we can write on this topic that doesn't involve setting budgets through webpack?
* For Angular: We already have a [Performance budgets with the Angular CLI](https://web.dev/performance-budgets-with-the-angular-cli/) guide. Similar to how we [moved perf budget guides](https://github.com/GoogleChrome/web.dev/pull/1037) to the start of /fast, we should also move this article to earlier in the page (in the `Introduction` principle for example)

cc @addyosmani @mgechev @mihajlija @slightlyoff

----

**Target publish date:** `<2019-08-01>`

- [ ] Check this box if this is a hard deadline.

**Process**

Take a moment to look over the [web.dev handbook](https://web.dev/handbook) and
familiarize yourself with the process.

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal `<add a link to your proposal doc>`
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by mgechev** [comment]
SGTM! Currently, for Angular we have performance budgets after code-splitting to show how to ship fewer bytes of JavaScript (code-splitting) and as the second step, do not regress over time. In the same time, I can see how the reverse order would work if we have the correct introduction.

**Comment by robdodson** [comment]
Going to close as stale as it seems like there hasn't been any progress. Happy to reopen if we plan to work on this in the near term.

**Comment by housseindjirdeh** [comment]
Looks like this moved to the back burner, but let's reopen this.

I'll find the time to put up a PR in the coming weeks.

**Comment by carolrivero** [comment]
@housseindjirdeh - are you going to submit a PR for this one? If so, we can move this to sprint ending Mar 31.

**Comment by housseindjirdeh** [comment]
@carolrivero I'll submit a PR soon! Can we move it to the next sprint in case I don't before the 31st?

**Comment by carolrivero** [comment]
Thanks @housseindjirdeh 
@kaycebasques  - this is in the icebox right now w/c means we don't plan to work on this in the next 6 months.  Are you okay queueing this up for the April sprint time frame?

**Comment by housseindjirdeh** [comment]
If we can't queue it up for April, that's fine too! 

I can make sure the ticket gets moved once I start working on it :)
