### ISSUE TITLE
Firefox shows red outline for required input on load

### ISSUE THREAD

**Issue by alexandersandberg** [GoogleChrome/web.dev#1180]
**Describe the bug**
Firefox adds a red outline to any input with the `required` attribute on load (see image 1). This leads to inconsistencies between browsers (see image 2).

**To Reproduce**
Visit [/measure](https://web.dev/measure) in Firefox.

**Expected behavior**
Since there's already a warning displayed through an event when the required input is empty, this default warning should probably be removed, or at least made consistent with other browsers.

**Screenshots**

![Screenshot of input warning in Firefox on load](https://user-images.githubusercontent.com/35671299/61596036-90bf2680-abfe-11e9-97e8-ceae7201e9df.png)
_Image 1. What the input looks like in Firefox, on page load._

![Graphic showing inconsistency with Firefox's styling of an input with the required attribute](https://user-images.githubusercontent.com/35671299/61595944-b5ff6500-abfd-11e9-875a-651ac87821c3.jpg)
_Image 2. After clicking 'Run audit' with empty input value, in different browsers._

**Comment by robdodson** [comment]
Just submitted a fix. It will take a few days to roll out. Thanks for flagging this!
