### ISSUE TITLE
Origin trial blurb should link to specific origin trial.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1183]
**Is your feature request related to a problem? Please describe.**
I should have thought of this before. The origin trial blurb should include a link to the registration page as well as to the guide.

https://developers.chrome.com/origintrials/#/trials/active

**Comment by robdodson** [comment]
@jpmedley would you be interested in doing a PR to add that?

**Comment by jpmedley** [comment]
Just assigned myself. 

I originally intended to make the request to link to a specific OT. Then decided to request merely the registration page and forgot to change the title. 

Which would you rather do? If the former, how do I pass an argument to a shortcode?

**Comment by robdodson** [comment]
> The origin trial blurb should include a link to the registration page as well as to the guide.

Which guide are you referring to? Can you provide an example?

> I originally intended to make the request to link to a specific OT. Then decided to request merely the registration page and forgot to change the title.

FWIW you can click 'Edit' next to the title to change it :)

> Which would you rather do? If the former, how do I pass an argument to a shortcode?

I think I prefer just linking to the registration page. I believe Jeff was originally using this blurb to help folks understand what the term "origin trial" meant so maybe it doesn't need to link to specific ones. If we're not linking to specific ones then I think you can update the include with the link to the registration page.

**Comment by jpmedley** [comment]
> > The origin trial blurb should include a link to the registration page as well as to the guide.
> 
> Which guide are you referring to? Can you provide an example?

This is [the developers guide](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md) already linked to in the blurb. The [registration page is here](https://developers.chrome.com/origintrials/#/trials/active). 

> 
> > I originally intended to make the request to link to a specific OT. Then decided to request merely the registration page and forgot to change the title.
> 
> FWIW you can click 'Edit' next to the title to change it :)

I knew that. I was really just saying I had two ideas about how this should be done.
> 
> > Which would you rather do? If the former, how do I pass an argument to a shortcode?
> 
> I think I prefer just linking to the registration page. I believe Jeff was originally using this blurb to help folks understand what the term "origin trial" meant so maybe it doesn't need to link to specific ones. If we're not linking to specific ones then I think you can update the include with the link to the registration page.

Will do.
