### ISSUE TITLE
Change "realize what the web can be" to a more proactive call-to-action

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1205]
**Describe the bug**

The call-to-action for our core content should express that all of these sections are core parts of a good web experience. The current tagline, `Realize what the web can be`, doesn't quite convey that. If you look at that call-to-action literally, what action are we directing readers toward? We're just directing them towards "becoming aware of" the web's potential. I know that "realize" also has another meaning more along the lines of "cause something to happen" but if you look at its definition you'll see the main definition is just "to become aware of". We want to go further than that. We want to direct them towards actually *building* good web experiences.

**To Reproduce**

1. Go to https://web.dev/learn

**Expected behavior**

Rephrase the call-to-action to be more action-oriented. Not just becoming aware of the web's potential. But actually building it. Something like "Learn how to build world-class web experiences"

**Screenshots**

![image](https://user-images.githubusercontent.com/4713486/61820697-62ae3200-ae0a-11e9-8339-2e20183e0b4a.png)

**Comment by robdodson** [comment]
I believe Harleen and Meggin worked with a UX writer on this phrasing. Might be worth doing an internal email discussion to pull in those same folks so we can talk through this.

**Comment by kaycebasques** [comment]
No concrete plans to work on this. Will probably happen in Q1 as our narrative evolves.
