### ISSUE TITLE
/measure's URL text input could use some left padding

### ISSUE THREAD

**Issue by alexandersandberg** [GoogleChrome/web.dev#1206]
**Describe the bug**
Not sure if this is a bug or a feature request, but the text input for URLs on [/measure](https://web.dev/measure) could use some padding to the left.

![prototype for what the text input would look like with more padding](https://user-images.githubusercontent.com/35671299/61829586-8e143980-ae69-11e9-9a67-5f07eb03e96e.jpg)
_Top left: Current. Top right + bottom: Proposal._

I think it should either be aligned with the 'Performance' text below it—as I propose above—or according to Google's style guidelines when it comes to input paddings.

**Comment by robdodson** [comment]
Good catch. @samthor do you think you can make this fix in the updated CSS you're working on?
