### ISSUE TITLE
Make $ un-selectable

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1209]
**Describe the bug**

When users go to copy CLI code, the `$` that we use as a convention is copy-able. In DevSite this symbol is omitted so that the code that's copied to the clipboard is correct. https://developers.google.com/style/code-syntax#prompt

**To Reproduce**

1. Go to https://web.dev/precaching-with-the-angular-service-worker/#introducing-the-angular-service-worker
1. Copy the CLI code

**Expected behavior**

The `$` symbol is omitted from the clipboard

**Screenshots**

![image](https://user-images.githubusercontent.com/4713486/61837821-4e365d80-ae3b-11e9-9856-9c1b6a5dc42f.png)

**Comment by robdodson** [comment]
What do you think about asking folks to remove the `$`. I don't think we include it in most of our snippets. Devsite has a custom widget they use for this but that almost feels like more effort than it's worth.

**Comment by kaycebasques** [comment]
SGTM. Let me put in a note in the web.dev style guide.

**Comment by kaycebasques** [comment]
Handbook specifies that people should omit `$`: https://web.dev/handbook/markup-code/#code-blocks
