### ISSUE TITLE
content: Best Practices for Video Playback on the Web

### ISSUE THREAD

**Issue by dougsillars** [GoogleChrome/web.dev#1220]
**Author**: @dougsillars
**Reviewer**: @jpmedley

**A one to two sentence description of your post**
I'm proposing a ~1000 word blog post on the various attributes available for video delivery, and best practices in the use of the various attributes that are available: ensuring that the video playback is quick and efficient with no stalls, and also fully featured and awesome for end users.

**Target publish date:** `<2019-08-14>`

- [ ] Check this box if this is a hard deadline.

**Process**

Take a moment to look over the [web.dev handbook](https://web.dev/handbook) and
familiarize yourself with the process.

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal https://docs.google.com/document/d/1E3j0ryqzqWFQ5ldU8oDaZCDgvZXOqoun0wTb7i4LXWw/edit?usp=sharing
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1467 
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@jpmedley - Rob will help w/ this one so we're assigning it to him. Thanks.

**Comment by carolrivero** [comment]
To clarify, Rob will help w/ the proposal review only. Then we'll reassign back to you. Thanks.

**Comment by jpmedley** [comment]
I can get to it tomorrow for sure. What's the rush?
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by jpmedley** [comment]
@dougsillars The proposal looks right so you can proceed with the writing. 

We have a concern, though. This article will eventually sit beside other video related content. The feeling here at Google is that we don't want to try teaching people how to implement a player if they need something more complex than a `<video>` element. We'd prefer they use a player such as Shaka, Plyr, or VideoJS. We ask that you please keep that idea in the back of your mind as you write.

**Comment by dougsillars** [comment]
@jpmedley with just 1k words, it's probably best to just stick to vanilla html5 <video> tags.  Trying to add in streaming + players would be a rollercoaster ride in that length. :)

**Comment by robdodson** [comment]
@dougsillars yep sticking to the vanilla `<video>` tag sounds good 👍

**Comment by dougsillars** [comment]
Hi @jpmedley  I've added a draft.  Thanks!

**Comment by carolrivero** [comment]
@jpmedley - please provide an update on status of review. Thanks,

**Comment by jpmedley** [comment]
@dougsillars Can you please give me comment access to your draft. It will make copy editing go faster.

**Comment by dougsillars** [comment]
@jpmedley Thanks!  I've accepted all of your suggestions.

**Comment by kaycebasques** [comment]
@robdodson will review the PR
