### ISSUE TITLE
v2 doesn't rebuild on CSS changes

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/web.dev#1223]
**Describe the bug**
Saving a CSS file doesn't cause a Rollup run.

**To Reproduce**
Save a CSS file (modified or not). See no rebuild. Save a related JS file, rebuild happens.

**Expected behavior**
Rebuild.

**Screenshots**
¯‍\‍_‍(‍ツ‍)‍_‍/‍¯

**Comment by robdodson** [comment]
oh yeah I think that's because I switched to using chokidar in the package.json to watch files and didn't tell it to watch the scss.
