### ISSUE TITLE
Attempt to download report using download link on Android Pixel 2xl fails with error.

### ISSUE THREAD

**Issue by logicalphase** [GoogleChrome/web.dev#1224]
Attempts to download report on Android fails with unknown error. Pixel 2 xl (beta).

**Comment by robdodson** [comment]
Can confirm. Android says "Download failed" and clicking "Details" opens the download manager with no details.

**Comment by logicalphase** [comment]
Also can confirm this with attached screenshot.
![Screenshot_20200312-195555](https://user-images.githubusercontent.com/25212653/76580043-7511d480-649c-11ea-94e4-69d2f321434e.png)

**Comment by MichaelSolati** [comment]
It looks like Chrome for Android may not support downloading HTML files. It seems to be a commonly reported issue on the Chrome product forums, see [[1]](https://support.google.com/chrome/thread/5535084?hl=en), [[2]](https://support.google.com/chrome/thread/15277772?hl=en), [[3]]https://support.google.com/chrome/thread/9576848?hl=en), [[4]](https://support.google.com/chrome/thread/9576848?hl=en). Seems like we may need another solution, @robdodson or @samthor what do you guys think about serving the file as PDF or serve it as a regular HTML page instead?

**Comment by MichaelSolati** [comment]
UPDATE: Seems like this is an [issue with chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1041209). So for now we will remove the button until there's a proper fix in Chrome.
