### ISSUE TITLE
content(docs): Create canonical samples

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1243]
Create at least one example each of:
- a post
- a codelab
- an IA

**Comment by jpmedley** [comment]
Posts probably need multiple canonical examples. Off the top of my head:

* CSS post
* Javascript feature
* New complete API based on a spec ([Example](https://www.chromestatus.com/feature/6577673212002304))
* New interface or interface member for an existing spec. ([Interface example](https://www.chromestatus.com/feature/5689383275462656), [member example](https://www.chromestatus.com/feature/5765569655603200))

I have been meaning to take an inventory.

**Comment by mfriesenhahn** [comment]
> Posts probably need multiple canonical examples. Off the top of my head:
> 
> * CSS post
> * Javascript feature
> * New complete API based on a spec ([Example](https://www.chromestatus.com/feature/6577673212002304))
> * New interface or interface member for an existing spec. ([Interface example](https://www.chromestatus.com/feature/5689383275462656), [member example](https://www.chromestatus.com/feature/5765569655603200))
> 
> I have been meaning to take an inventory.

Given that web.dev is more problem-oriented than feature-oriented, I think we may want to continue thinking through the breakdown. But I definitely agree there should ideally be more than one example per format. I just wanted to be realistic about what we can accomplish this sprint :)

**Comment by kaycebasques** [comment]
Would be cool to do an inventory of existing content and see if any clear patterns emerge.

We can re-open this in the future if we decide to set aside time to work on it.
