### ISSUE TITLE
content(docs): Revise audience section of handbook

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1246]
Revise audience section of handbook. Goals:
- Include guidance about how to use personas.
- Generalize details in existing personas (e.g., tech stacks) to make them more broadly applicable.
- Include info in personas that build empathy (e.g., photos, likely affective responses).
- Include signals indicating provenance of the details (e.g., linking to data where we have it).
- Ensure parallel information is provided for each persona.
- Include information about how to make content accessible regardless of which persona is targeted.
- Consider ways to make the audience section digestible for contributors who want a TL;DR.

**Comment by mfriesenhahn** [comment]
@katejeffreys, I tried to capture our previous conversations succinctly. Please feel free to amend as needed!

**Comment by jpmedley** [comment]
I've been looking for a place to capture something. This discussion started because of someone's comment that their article didn't fit any of the personas and it fit all of them. This is a problem I will always have with posts related to the beta release. Beta release posts are frequently about features that have never existed before in the history of the universe. Though a particular feature might eventually be part of a metrics or a design learning path, for a new feature post the answer to 'who is the audience' is 'everybody who works on the web'.

**Comment by mfriesenhahn** [comment]
> I've been looking for a place to capture something. This discussion started because of someone's comment that their article didn't fit any of the personas and it fit all of them. This is a problem I will always have with posts related to the beta release. Beta release posts are frequently about features that have never existed before in the history of the universe. Though a particular feature might eventually be part of a metrics or a design learning path, for a new feature post the answer to 'who is the audience' is 'everybody who works on the web'.

Yeah, that's an interesting problem. I guess I'm wondering (naively) whether the latest features can realistically be taken on board by literally all devs. Like, in at least some cases, it seems like you need a fair amount of domain knowledge to understand why a feature is valuable?

**Comment by jpmedley** [comment]
Well, hopefully we explain why something is valuable to people who don't have the domain knowledge. I'm not sure how valuable we've been. In some cases we might not need to explain it even if it does require domain knowledge. WebRTC ("real time communications") is a good example of this. The people who work on WebRTC are specialists working on WebRTC products. What they need to know is what changed and how does it work now.

**Comment by mfriesenhahn** [comment]
> Well, hopefully we explain why something is valuable to people who don't have the domain knowledge. I'm not sure how valuable we've been. In some cases we might not need to explain it even if it does require domain knowledge. WebRTC ("real time communications") is a good example of this. The people who work on WebRTC are specialists working on WebRTC products. What they need to know is what changed and how does it work now.

If I'm reading you correctly, I think you're saying that some beta release posts really are for a narrow audience, while others should ideally be pitched to a much wider range of devs. That makes sense to me. For the Audience page, @katejeffreys and I talked about including strategies for making content accessible to everyone, regardless of target audience. Perhaps that would get at the issue you're raising? Or do you think we really should allow contributors to indicate a post is for a general dev audience? My fear is that it'll be very tempting to say that for most posts, which could lead to less than optimal targeting.

Very interested to hear what Kate thinks too.

**Comment by jpmedley** [comment]
Correct, some really are for narrow audiences.

I was also thinking that we suggest some audiences then leave a blank labeled "other". We might find some cowpaths to pave.
