### ISSUE TITLE
Angular Article - Virtualize large lists with Angular CDK

### ISSUE THREAD

**Issue by juristr** [GoogleChrome/web.dev#1260]
**Describe the bug**

The code samples are correct in the GitHub source, but not visualized properly on the web.dev platform. For instance if you go to https://web.dev/virtualize-lists-with-angular-cdk/, then all occurrences of the following

```
<div *ngFor="let item of list"></div>
```

are wrongly displayed, missing the `{{ item }}` in between the divs, such as

```
<div *ngFor="let item of list">{{item}}</div>
```

This is most probably a compilation issue, when the markdown files are being transformed. Maybe the `{{` need to be escaped 🤔. Not sure what is being used to render `web.dev`.

**To Reproduce**
1. Go to https://web.dev/virtualize-lists-with-angular-cdk/

**Screenshots**

![image](https://user-images.githubusercontent.com/542458/62412754-ffd94980-b606-11e9-88ae-60d514dbe0c1.png)

..and all the other occurrences :)

**Comment by robdodson** [comment]
yeah I think we're failing to escape them properly. I can look into fixing this.
