### ISSUE TITLE
content: Making PROXX work on feature phones - part 1

### ISSUE THREAD

**Issue by surma** [GoogleChrome/web.dev#1270]
**Author**: @surma
**Reviewer**: @kaycebasques  

**Target publish date:** As soon as it's done.
- [ ] Check this box if this is a hard deadline.
- [x] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [x] 1. I've done my [proposal](https://docs.google.com/document/d/1wMGwJiijyYReMLup-HRoKDMMVSfqvAi-B9dW14o8BeQ/edit?usp=sharing)
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1531 
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by surma** [comment]
The draft is ready for review!

cc @robdodson

**Comment by robdodson** [comment]
Hey @surma. It looks like this is slated for the upcoming sprint that starts tomorrow. We should be able to assign a reviewer then.

**Comment by kaycebasques** [comment]
Just reviewed the draft. Looking good! Back to @surma to incorporate my feedback.

**Comment by surma** [comment]
Thanks for the thorough review, @kaycebasques! I am on vacation til the 31st, I’ll get back to this then :)

**Comment by surma** [comment]
PR opened 🎉

**Comment by kaycebasques** [comment]
Just reviewed it. Back to @surma to address some small requests.

**Comment by surma** [comment]
PTAL!

**Comment by kaycebasques** [comment]
LGTM. Assigning to @robdodson because the PR needs a code owner's approval to merge.
