### ISSUE TITLE
How do you decide what audits to show in scores-audits table?

### ISSUE THREAD

**Issue by hintyu** [GoogleChrome/web.dev#1271]
There are many audits performed in lighthouse module but only a few audits are shown in **scores-audits table**(I mean, the table of audits on '/measure' page, under Metrics table).

How do you decide what audits to show in the table, and what is the creteria for determining IMPACT?(High, Medium, Low) I tried to analyze lighthous JSON report, but couldn't find the mention about the audits' impact.

I don't know which place is appropriate for this kind of question, so I'm very sorry if I'm at the wrong place and disturbing you. 
Thank you.

**Comment by robdodson** [comment]
Hi @hintyu 

> How do you decide what audits to show in the table, and what is the creteria for determining IMPACT?(High, Medium, Low) I tried to analyze lighthous JSON report, but couldn't find the mention about the audits' impact.

We show all of the audits that the user fails. There should be a button at the bottom to show more audits if the list is long.

![image](https://user-images.githubusercontent.com/1066253/62557561-157b8880-b82c-11e9-99ec-e606f217679c.png)

To determine impact we look at the audit's weight (lighthouse audits internally list their weight in the json report). For performance audits they list the estimated milliseconds savings if the audit was to be fixed. So we use these two items to determine the impact.

**Comment by hintyu** [comment]
Thank you very much! It helped a lot! 😄 😄
