### ISSUE TITLE
content: Making PROXX work on feature phones - part 2

### ISSUE THREAD

**Issue by surma** [GoogleChrome/web.dev#1272]
**Author**: @surma
**Reviewer**: @kaycebasques 

**Target publish date:** As soon as it's done.
- [ ] Check this box if this is a hard deadline.

- [x] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [x] 1. I've done my [proposal](https://docs.google.com/document/d/1FCwGvBidKcvhX3l67CCvBFendKnx8RoxTy7tEg9uK2E/edit?usp=sharing)
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by kaycebasques** [comment]
@surma looking good so far. Can you try posting the key points to the proposal? They don't have to be in order. I just want to see the main ideas. I left a comment in the doc with more detailed instructions.

**Comment by kaycebasques** [comment]
Status: I have reviewed the proposal and asked Surma to add something to the proposal. He's back from vacation on Sept 1.

**Comment by kaycebasques** [comment]
I will review today

**Comment by kaycebasques** [comment]
Ah, just checked the doc. Looks like @surma hasn't drafted yet.

**Comment by robdodson** [comment]
@surma any update?

**Comment by surma** [comment]
Sorry, I had to reprioritize. I’ll implement the review on part 1 soon, but part 2 is gonna be on ice for a while. I’ll let you know when I can get back to it :)

**Comment by kaycebasques** [comment]
Thanks for the update 👍

**Comment by kaycebasques** [comment]
@robdodson said that @surma that he'll work on this after CDS

**Comment by carolrivero** [comment]
@kaycebasques which sprint should this be added to? The issue is now past due. Thanks.

**Comment by surma** [comment]
This is basically obsolete in light of the excellent write-up by @mfriesenhahn in #1955
