### ISSUE TITLE
Web.dev doesn't save state of report when pressing back button

### ISSUE THREAD

**Issue by ljme** [GoogleChrome/web.dev#1274]
Version: https://web.dev/as of 8/6/19
Browser: Any, for this issue I used Chrome OS 77.0.3849.0 (Official Build) dev (64-bit)

Steps to reproduce:
# Navigate to https://web.dev/measure 
# Analyze any site, for example I used www.wyep.org
# Click on any of the recommended results how-to articles, for example, I clicked on "Eliminate render-blocking resources" - note that these open in the current tab
# Press the back button 
Expected: return to testing results
Actual: report is gone, site back to default state

Workaround: open the links in a new tab or save report

**Comment by robdodson** [comment]
Should be fixed in v2.
