### ISSUE TITLE
content: migrate "Registering as a Share Target with the Web Share Target API"

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1279]
**Author**: @petele 
**Reviewer**: @jpmedley 

**Target publish date:** 2019-10-16
- [x] Check this box if this is a hard deadline.

- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal https://developers.google.com/web/updates/2018/12/web-share-target
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1828
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by kaycebasques** [comment]
@jpmedley what's the next step here?

**Comment by jpmedley** [comment]
Waiting for Pete to review a draft. He's at a conference in Sunnyvale this week.

**Comment by kaycebasques** [comment]
PR will probably land today or Monday.

**Comment by jpmedley** [comment]
I don't quite have a PR. The content is in markdown and in a development branch. I have a few things I need to work out. Then I'll open a PR.

**Comment by kaycebasques** [comment]
@mfriesenhahn #1828 is ready for your review. IIRC this is @jpmedley's rewrite of a post that originally appeared on developers.google.com/web.

**Comment by mfriesenhahn** [comment]
@kaycebasques, this is ready to merge, though it shouldn't be published until the companion post, #1829, is published.

**Comment by jpmedley** [comment]
To be clear, #1828 and #1829 (share and share target) are linked to each other. They MUST BE part of the same deployment.

**Comment by kaycebasques** [comment]
I'll merge this once #1828 is ready. Going to review it now.
