### ISSUE TITLE
content: "Recovering from a problematic service worker"

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/web.dev#1283]
**Author**: @jeffposnick
**Reviewer**: [Leave blank. web.dev team will assign a reviewer.]

**Target publish date:** 2019-10-01
- [ ] Check this box if this is a hard deadline.

- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal <add a link to your proposal doc>
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by jeffposnick** [comment]
This involves migrating https://stackoverflow.com/questions/33986976/how-can-i-remove-a-buggy-service-worker-or-implement-a-kill-switch/38980776#38980776 to live under https://web.dev/reliable as part of our service worker guidance.

CC: @addyosmani

**Comment by kaycebasques** [comment]
@jeffposnick do you still want to land this? Please re-open the issue if yes.
