### ISSUE TITLE
content: Codelab: Use Link Prefetch with HTML Tags and HTTP Link: header

### ISSUE THREAD

**Issue by demianrenzulli** [GoogleChrome/web.dev#1284]
**Author**: @demianrenzulli 
**Reviewer**: @mihajlija 

**Target publish date:** <2019-09-xx>
- [ ] Check this box if this is a hard deadline.
- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [X] 1. I've done my proposal - [Link](https://docs.google.com/document/d/1pUaRAwreF1t3efCo_J7D6GrIrZoBl0wCCQnZPhkOmGs/edit?usp=sharing)
- [x] 2. Proposal approved — _reviewer checks this_
- [X] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1468
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by demianrenzulli** [comment]
This codelab should be linked from the guide submitted at: #1014.

cc // @mihajlija @mfriesenhahn

**Comment by carolrivero** [comment]
@kaycebasques to work w/ @mihajlija on this one.

**Comment by carolrivero** [comment]
@demianrenzulli is working on update

**Comment by demianrenzulli** [comment]
Hi @carolrivero,

We received some additional technical suggestions and we have a final draft now.
Will be working in the PR today.

This post contains a Codelab, which is almost finished, but won't be available at the time of this PR.
I guess we can update the post with the link to the codelab, once it's ready.

**Comment by demianrenzulli** [comment]
@carolrivero sorry, I confused this issue with the one for the guide.
I'm working on an update to the codelab, which I hope to have ready very soon.

Thanks.

**Comment by kaycebasques** [comment]
@mfriesenhahn to provide editorial review

**Comment by mfriesenhahn** [comment]
Hey, @demianrenzulli, I'll be doing a quick editorial review. Which doc should I look at? The [one linked in the issue](https://docs.google.com/document/d/1pUaRAwreF1t3efCo_J7D6GrIrZoBl0wCCQnZPhkOmGs/edit?usp=sharing) is different from the [one you and Milica have been working on](https://docs.google.com/document/d/1TvCi4Y3B9haFZBWPXoRUXbFn1YkRvkaXkqCh2jOfU7U/edit?ts=5d6d3d4c).

**Comment by demianrenzulli** [comment]
Hi @mfriesenhahn, I've just re-shared the doc of [the codelab](https://docs.google.com/document/d/1TvCi4Y3B9haFZBWPXoRUXbFn1YkRvkaXkqCh2jOfU7U/edit?usp=sharing).

You'll find that's the one that contains the latest comments from the other reviewers. 

I've just updated [the proposal](https://docs.google.com/document/d/1pUaRAwreF1t3efCo_J7D6GrIrZoBl0wCCQnZPhkOmGs/edit), adding a link to the file at the end, instead of the text (which, as you said, was outdated).

**Comment by mfriesenhahn** [comment]
Thanks! One more question: can you give me the link to the Glitch? I'm having trouble evaluating whether the instructions make sense without it, and I can't seem to find it.

**Comment by demianrenzulli** [comment]
@mfriesenhahn here's the link to the glitch: https://glitch.com/edit/#!/join/110b5212-50c3-438c-911b-9af9350888cd.

Let me know if you need anything else!

**Comment by mfriesenhahn** [comment]
OK, I did an editorial pass and noted a couple concerns I had about the instruction. I don't want to block this but did feel I should note them. @demianrenzulli and @mihajlija, do with them what you will :)

**Comment by demianrenzulli** [comment]
I've just accepted the suggestions about grammar, style, etc, and left some comments on the ones related to content and structure.

Thanks.

**Comment by mihajlija** [comment]
Reviewed the PR in #1468, @demianrenzulli to add a few changes later today and @robdodson to give the final approval.

**Comment by kaycebasques** [comment]
Woohoo thank you @demianrenzullu for the content and @mihajlija for the review
