### ISSUE TITLE
Code in headers has left margin.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1288]
**Describe the bug**
When a `<code>` element is the first child in a heading it has a left margin that doesn't look good.

**To Reproduce**
Write a heading like ``## `Hello` ``

**Expected behavior**
It should not have a left margin.

**Screenshots**
![image](https://user-images.githubusercontent.com/1066253/62668913-81e8ab80-b942-11e9-92d1-94670a88af41.png)

**Comment by samthor** [comment]
Cannot repro. I think someone removed padding/margin on code in headings. That works fine.

<img width="514" alt="Screen Shot 2020-03-12 at 13 13 03" src="https://user-images.githubusercontent.com/119184/76480586-3f042e80-6463-11ea-9868-67bcee1fbd01.png">
