### ISSUE TITLE
"What you'll learn" section should be clickable

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1290]
**Is your feature request related to a problem? Please describe.**

The list under "What you'll learn" is not clickable even though it's essentially a table of contents.

![image](https://user-images.githubusercontent.com/4713486/62722702-e3049380-b9c3-11e9-90eb-02da6cbf852b.png)

**Describe the solution you'd like**

Make each of these list items a link.

**Comment by jpmedley** [comment]
Or, it should be an actual description of what you'll learn. "Introduction" is not something you learn.

**Comment by mayankkt9** [comment]
Hi, can I work on this? Also, what is the requirement here? Is it decided to remove "introduction" from the list or make these list items as links or both?

**Comment by robdodson** [comment]
I think the easiest first step would be to turn them into in-page links. I'd leave introduction for now.
