### ISSUE TITLE
content: migrate "Experimenting with Periodic Background Sync"

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1295]
**Author**: @petele 
**Reviewer**: @jpmedley 

**Target publish date:** 2019-10-16
- [ ] Check this box if this is a hard deadline.

- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal https://docs.google.com/document/d/1CNrSJxLcoUTpUojLPiiJYvR1SgGC_YVjpfBfhrVn-gM/edit#heading=h.s6q03wgfh878
- [x] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1835
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by jpmedley** [comment]
The WebFu version [has been merged](https://github.com/google/WebFundamentals/pull/7993). We will need to rewrite before moving to web.dev.

**Comment by jpmedley** [comment]
There is a version of this on [/Updates](https://developers.google.com/web/updates/2019/08/periodic-background-sync) that will need considerable rework before moving to web.dev.

**Comment by jeffposnick** [comment]
Hey @jpmedley & co. (@petele)—I see that there's a deadline of Oct. 9 associated with this, and just wanted to check in to see what's specifically needed from me.

I know that Joe would like to see a rewrite of what was initially published on WebFu.

If I'm going to perform the rewrite, I'll need some additional guidance as to what needs to be cut. Or was Joe planning on taking a first stab at the rewrite?

**Comment by jpmedley** [comment]
@jeffposnick I've been traveling. Sorry about the delay. 

Some of the dates on these things are more aspirational that not.

I had assume that I would be the one to rewrite this. If you wish to do so, I have no objection. My objection with the old version was that it read like a design document instead of an article for a web developer. For that reason, my intention had been to throw out the old article and do a new one from scratch.

**Comment by jeffposnick** [comment]
Thanks for the additional context, Joe!

I am happy to let you take the lead in rewriting, especially since the deadline is aspirational. I'm happy to review your rewrite to ensure nuance about sensitive matters is retained.

**Comment by kaycebasques** [comment]
Next step: Figure out whether @jpmedley is still going to rewrite the article.

**Comment by jpmedley** [comment]
@kaycebasques Ping me about this.

**Comment by kaycebasques** [comment]
This review can only be minor copyedits only. Any substantive changes will introduce major delays.

**Comment by jpmedley** [comment]
@petele discussed this this morning. We're not literally migrating the existing doc. (Apologies @tomayac). I'll be submitting a PR for a new article, but it will include some content that was previously required by sec/priv.

**Comment by tomayac** [comment]
Since my [PR](https://github.com/GoogleChrome/web.dev/pull/1431) contains @jeffposnick's previous content 1:1, but in the web.dev Markdow syntax, it could probably still make sense to base your rewrite on it, @jpmedley. If you want to start from scratch, I'm also happy to close it in favor of an upcoming PR of yours instead. Just let me know. Thanks!

**Comment by kaycebasques** [comment]
Given that @jpmedley just submitted #1835 I assume he wants to use that one and close #1752.

@jpmedley is #1835 ready for my review or does someone else need to review it first?

**Comment by jpmedley** [comment]
It is ready for review.
