### ISSUE TITLE
Make Important Content Visible in Project View

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1299]
I want to suggest rearranging content tickets so that the most important information is on top and hence more likely to be visible when I open a ticket in the Projects view. 

The image below shows what I see when I open a ticket in Projects view. Everything up to is "Check this box if this is a hard deadline." is important. Then I have to click "Show more" and scroll past several minor items before I get to the next important thing: the steps/status list. It would be nice if these items were together. 

![image](https://user-images.githubusercontent.com/8204171/62731431-fbca7480-b9d6-11e9-84a4-9bef9613b5ba.png)

**Comment by kaycebasques** [comment]
I think this is outdated now.
