### ISSUE TITLE
content: Keep request counts low and transfer sizes small (audit)

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1305]
**Author**: @kaycebasques
**Reviewer**: @mfriesenhahn

**Target publish date:** <yyyy-mm-dd>
- [ ] Check this box if this is a hard deadline.

- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal <add a link to your proposal doc>
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1456 
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by kaycebasques** [comment]
Kayce to incorporate feedback today

**Comment by kaycebasques** [comment]
I just updated #1456 so @mfriesenhahn is up for review again

**Comment by robdodson** [comment]
I think this should be live now. Pretty sure it went out with this CL
https://critique.corp.google.com/#review/267183128
