### ISSUE TITLE
content: Third-party Usage (audit)

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1306]
**Author**: @kaycebasques 
**Reviewer**: @mfriesenhahn 

**Target publish date:** <yyyy-mm-dd>
- [ ] Check this box if this is a hard deadline.

- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal <add a link to your proposal doc>
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1457
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by kaycebasques** [comment]
PR #1457 is in-flight. @mfriesenhahn to review.

**Comment by mfriesenhahn** [comment]
Reviewed. Looks good. Back to @kaycebasques to get his take on a few things.

**Comment by kaycebasques** [comment]
Kayce to incorporate feedback today

**Comment by kaycebasques** [comment]
Salutations comrade @mfriesenhahn I have incorporated your feedback accordingly, would you kindly audit the aformentioned technical documentation again

**Comment by mfriesenhahn** [comment]
LG. Caught one usage error. Once you accept the suggestion, it's ready to merge!

**Comment by kaycebasques** [comment]
Suggestion added. @robdodson or @mfriesenhahn to merge.
