### ISSUE TITLE
content: When do I use PWA/TWA/WebView/CCT 

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1313]
**Author**: @andreban
**Reviewer**: @jpmedley

**Comment by petele** [comment]
Note to self - Should include what is/is not supported in WebViews

**Comment by kaycebasques** [comment]
I imagine this is @andreban's area now

**Comment by kaycebasques** [comment]
I think @andreban will eventually get to this but in the meantime we can close it.
