### ISSUE TITLE
Native lazyloading (`loading` attribute) is not enabled by default in M76

### ISSUE THREAD

**Issue by myakura** [GoogleChrome/web.dev#1317]
**Describe the bug**
[The current version of the article](https://github.com/GoogleChrome/web.dev/blob/2a98cbfe0df58bbe8f2a134926e7790056f03e7c/src/site/content/en/blog/native-lazy-loading/index.md) says it's available in M76, but it isn't. Quick testing shows it is enabled by default in M77 Beta, M78 Dev, and M78 Canary.

Looking at the commit log, [it's just enabled by default last week](https://chromium.googlesource.com/chromium/src/+/0fc50ca2d3c81f74f73aae8aab6079a516d9b8fb). So I don't think it's enabled by default in M76.

(I still don't know why I got `true` in Beta. Looking at https://crbug.com/990967#c4 it's not merged to M77 branch atm... perhaps you've been running field trials for this feature?)

**To Reproduce**
1. open Chrome stable (76) with all the flags to be default
2. open DevTools
3. type `"loading" in HTMLImageElement.prototype`
4. check if the snippet returns `true`

**Expected behavior**
from the article it should return `true`

**Comment by addyosmani** [comment]
Thank you for this bug report. Hmm...I can 100% confirm it is enabled by default in M76 based on our data. We used the Finch platform to roll this feature into M76 last week - this allows dynamically rolling features into Chrome without the need for cutting a completely fresh milestone.

Would it be possible to do a fresh pull of M76 to see if you might be in an outlier set that haven't seen the update get patched yet?

**Comment by myakura** [comment]
sorry for being late. I rechecked it and now it returns true...
sorry for the noise 🙇
