### ISSUE TITLE
Missing "Next article" button on "Identify slow third-party JavaScript"

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/web.dev#1327]
The "Next article" button is missing on "Identify slow third-party JavaScript"

**Steps to reproduce**
1. Go to [https://web.dev/identify-slow-third-party-javascript/](https://web.dev/identify-slow-third-party-javascript/)
3. Scroll down to the bottom
4. See only "Return to all articles", no "Next article"

**Expected behavior**
At the end of the post, there should be a "Next article" button linking to [https://web.dev/efficiently-load-third-party-javascript/](https://web.dev/efficiently-load-third-party-javascript/).

**Screenshots**
![image](https://user-images.githubusercontent.com/17127567/63086251-c205ea80-bf4f-11e9-985c-fb5e9e37afd4.png)

**Comment by robdodson** [comment]
This fix should be live now.
