### ISSUE TITLE
Automatic Link Checker

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1332]
**Is your feature request related to a problem? Please describe.**
Typically, site managers and content authors aren't aware of broken links until somebody stumbles over them and reports them. Consequently, broken links can hang around for weeks, months, or even years. 

**Describe the solution you'd like**
A job that runs on a regular schedule or perhaps when the server is under a light load that trolls for broken links. When it finds one, it would autocreate a GitHub ticket and assign it to the author of the page that contains the broken link.

**Describe alternatives you've considered**
There are manual tools available for such things. For whatever reason, site contributors tend not to use them, perhaps because it's hard to prioritize such things. Broken links can grow to the point that the tool returns so many results that its user has a choice between two time-consuming tasks: fixing the links themself or notifying authors to fix the links themselves.

**Comment by robdodson** [comment]
I think remark-lint (the linting tool we're currently using) has a plugin for this. I can look into adding it.

**Comment by robdodson** [comment]
let's keep this one open. I think there are easy remarklint plugins that we can use to address this and it would be worth having. I feel like a good portion of our community contributions are folks just fixing busted links.

**Comment by jpmedley** [comment]
Additional information: I opened this because a link fix in a recent PR was not quite the right action. In this case the broken link was the symptom, not the problem. The article _itself_ had gotten slightly out of sync with the feature it defined. Demo URLs changed as a consequence of that. The PR in question merely replaced the link and made no move to address the underlying problem.

**Comment by jpmedley** [comment]
There's an applause emoji, but no standing ovation emoji.

**Comment by robdodson** [comment]
It looks like there's maybe a good link checking tool mentioned in #4469 that we could use.

**Comment by jpmedley** [comment]
MDN just implemented one on its PR toolchain. Broken links are a complete tsunami. Now, MDN is a 12-year old site that previously was not policing links. I suspect our site will be much better because it's a newer site with more recent content. Still, I'd consider making this feature a warning for a week or five just in case. I know the thought of leaving broken links is making your cringe, but we need some way to manage possible effects on work velocity.

**Comment by robdodson** [comment]
Yeah it's on the Eng board now which should, in theory 😅  , mean that someone gets to it when they have a spare cycle.

**Comment by dstmarthe** [comment]
We’re moving to a new platform. Not sure if there is a native link-checker so I will move this issue to our new tracker. You can see it at https://issuetracker.google.com/issues/298490624
