### ISSUE TITLE
Site forces sequential headers for situations that aren't sequential

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1337]
**Is your feature request related to a problem? Please describe.**

The standard design for index pages has a numbered heading next to each H2. In many cases the content isn't actually sequential. For [example](https://web.dev/lighthouse-pwa):

![image](https://user-images.githubusercontent.com/4713486/63125056-9b50af80-bf61-11e9-954a-50545a27094f.png)

I don't think we're necessarily intentionally suggesting that people make it fast and reliable first, and then installable, and then PWA optimized, and then to do the manual checks. But because "fast and reliable" has a 1 next to it, installable has a 2 next to it, and so on, that's what our design is implying.

Another [example](https://web.dev/discoverable):

![image](https://user-images.githubusercontent.com/4713486/63125166-df43b480-bf61-11e9-9b58-c7899c11d5da.png)

In this case we definitely don't want to imply that 2 comes before 3. If anything 3 should come before 2.

Another [example](https://web.dev/react):

![image](https://user-images.githubusercontent.com/4713486/63125309-32b60280-bf62-11e9-98b2-9a2614854c36.png)

We definitely don't want to imply that accessibility is the last sequential consideration here.

**Describe the solution you'd like**

In some cases we can re-order the content to follow the actual intended sequential order. In other cases we'll need a design that doesn't enforce a sequential path.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by robdodson** [comment]
this is fixed
