### ISSUE TITLE
Provide a way to manage tags across the whole site.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1338]
**Is your feature request related to a problem? Please describe.**
There is a long-term management problem common to keyword indexes and tag collections that occurs when contributors are allowed to add to them in an ad-hoc manner. Specifically, inconsistencies and needless variations in terms creep in. For example, if some writers use the term 'function' and other use the term 'method', content that should be in the same category will not be. In other cases, writers will differ in use of singular or plural forms of a word, reference different levels of specificity, or mix API names in interface names. (Think service worker vs. ServiceWorker.)

Correcting these issues after the fact is time-consuming and tedious. Though I've never tracked it precisely, my impression is that the time required to correct these issues grows faster than the number of actual issues. (This is probably an example of the mathematical phenomenon where the number of possible combinations of items in a set grows faster than the number of items in the set.)

**Describe the solution you'd like**
Provide a system whereby the addition of a tag forces consideration all tags that exist. For example, WebFundamentals did this with a [common tags file](https://github.com/google/WebFundamentals/blob/master/src/data/commonTags.json). Any new tag that is introduced in an article has to be added to the tags file, which means authors can review and possibly reuse existing tags. It also enables WebFu to lint for new tags, which ensures that authors must go through this step.

I'm not saying this feature has to do it the WebFu way, merely that WebFu illustrates my request.

**Describe alternatives you've considered**
As already stated, the alternative is a manual process that I believe is contraindicated.

**Comment by kaycebasques** [comment]
I think tags work is being tracked in #1808
