### ISSUE TITLE
content: Tidy Accessibility Lighthouse audit posts

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1341]
**Author**: @mfriesenhahn
**Reviewer**: @kaycebasques 

**Target publish date:** 2019-10-17
- [x] Check this box if this is a hard deadline.

Sections ready for review:
- [x] ARIA
- [ ] Audio and video
- [ ] Best practices
- [x] Contrast
- [x] i18n
- [ ] Names and labels
- [ ] Navigation
- [ ] Tables and lists
- [ ] Manual audits

**Comment by kaycebasques** [comment]
No update.

**Comment by kaycebasques** [comment]
The scope of this PR is to normalize the content. We'll do a more thorough review of the content in a subsequent PR.

**Comment by kaycebasques** [comment]
Status: Normalization is done. Michael is fixing some docs that aren't talking about what the audit is actually measuring.

**Comment by kaycebasques** [comment]
Michael is going through ARIA post now, continuing work

**Comment by kaycebasques** [comment]
Michael is including the Lighthouse 6.0 docs work in this issue because they share an include.

**Comment by kaycebasques** [comment]
Rob and Michael are reviewing the PR. Rob is doing in-depth reviews and doesn't think that it's necessary to have a writer review it as well. So once Rob thinks the PR is good, we can merge.

**Comment by robdodson** [comment]
added my LGTM to the PR. I'm cool with landing whenever.

**Comment by mfriesenhahn** [comment]
@kaycebasques, please don't merge until I give the go-ahead.

**Comment by kaycebasques** [comment]
Looks like @robdodson merged #1648 but this issue didn't automatically close.

**Comment by kaycebasques** [comment]
Thank you again for all this work, @mfriesenhahn!
