### ISSUE TITLE
content: Tidy Best Practices Lighthouse audit posts

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1342]
**Author**: @mfriesenhahn
**Reviewer**: @kaycebasques 

**Target publish date:** <yyyy-mm-dd>
- [ ] Check this box if this is a hard deadline.

- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal <add a link to your proposal doc>
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1485
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by mfriesenhahn** [comment]
Comments from @patrickhulce, originally in [Lighthouse PR 9538](https://github.com/GoogleChrome/lighthouse/pull/9538):
- Update `/external-anchors-use-rel-noopener` based on [Lighthouse issue 9531](https://github.com/GoogleChrome/lighthouse/issues/9531).

Comments from @paulirish, originally in email:
- `/appcache-manifest`: "Use the Cache API instead of AppCache" should say "use a service worker instead of appcache".   
- `/uses-passive-event-listeners`: the 1,2,3,4 is no longer accurate. It doesn't filter out 3rd party hosts. (that filter is available in the report UI though).  Technically Lighthouse uses the same passive-event listener collection that you see in the devtools console if you turn on verbose logging. (I can't seem to trigger it right now.. maybe the interventions have made it moot by now). But basically Lighthouse looks at any event listeners for the touch/wheel events listed and is upset if the passive attribute is not set.
- `/no-vulnerable-libraries/`: can you update the snyk link to `https://snyk.io/vuln?type=npm`?
- `/js-libraries/`: I think this article should just be title "Detected JavaScript Libraries"... otherwise, seems good.

**Comment by kaycebasques** [comment]
@mfriesenhahn is working on it

**Comment by kaycebasques** [comment]
@mfriesenhahn estimates to be done today

**Comment by mfriesenhahn** [comment]
@kaycebasques, ready for your review!

**Comment by kaycebasques** [comment]
Just reviewed. @mfriesenhahn you can incorporate or ignore my changes, then work through the merge conflicts.

**Comment by mfriesenhahn** [comment]
Made some updates and asked a couple questions.

**Comment by kaycebasques** [comment]
I reviewed it. Back to @mfriesenhahn to finish & merge.

**Comment by mfriesenhahn** [comment]
To @robdodson for final review and merge.
