### ISSUE TITLE
content: Tidy PWA Lighthouse audit posts

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1343]
**Author**: @mfriesenhahn
**Reviewer**: @kaycebasques 

**Target publish date:** <yyyy-mm-dd>
- [ ] Check this box if this is a hard deadline.

- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal <add a link to your proposal doc>
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1587
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by mfriesenhahn** [comment]
Comments from @patrickhulce, originally on [Lighthouse PR 9539](https://github.com/GoogleChrome/lighthouse/pull/9539):
- The `/redirects-http` doc seems to give the opposite advice, we want them to redirect their http traffic to https and the doc is mostly talking about avoiding redirects.
- Do we plan to move the PWA checklist over?

**Comment by kaycebasques** [comment]
No updates.

**Comment by kaycebasques** [comment]
The scope of this PR is to normalize the content. We'll do a more thorough review of the content in a subsequent PR.

**Comment by kaycebasques** [comment]
Status: Normalization is done. Michael is fixing some docs that aren't talking about what the audit is actually measuring.

**Comment by mfriesenhahn** [comment]
Both normalization and quality work complete. Ready for @kaycebasques to review.

Note: I didn't add content where it might be helpful because I didn't want to step out of scope, but there are some posts that are very slim. Most immediately, `/pwa-cross-browser`.

**Comment by kaycebasques** [comment]
@kaycebasques to do a tech writer review, there's an open question around heading wording. Look at redirects post and redirects HTTPS posts. These were re-written.

Michael did quality fixes too

FYI Rob checked consistency of normalization, skimmed content, mostly looking for normalization stuff

**Comment by kaycebasques** [comment]
Done! Woohoo! Off to @robdodson to publish.

**Comment by mfriesenhahn** [comment]
@kaycebasques, you introduced a title error when you committed your changes. See PR for details.

**Comment by kaycebasques** [comment]
Thanks @mfriesenhahn for fixing my goof, off to @robdodson to publish

**Comment by robdodson** [comment]
it's uuuuuup
