### ISSUE TITLE
content: Tidy Performance Lighthouse audit posts

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1344]
**Author**: @mfriesenhahn
**Reviewer**: @kaycebasques 

**Target publish date:** <yyyy-mm-dd>
- [ ] Check this box if this is a hard deadline.

- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal <add a link to your proposal doc>
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1609
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by mfriesenhahn** [comment]
Comments from @patrickhulce, originally on [Lighthouse PR 9540](https://github.com/GoogleChrome/lighthouse/pull/9540):

- The metrics docs are especially important to get right IMO and I'm a bit worried about using screenshots from a major version behind that all the reports point to. For example, we've removed EIL and replaced it with mpFID (which needs a doc) in 5.0 so the screenshots are already out of date the day they go live with more metric changes planned in the next 2 months. It seems like it would be a challenge to try to keep these up to date and even if we could the fact that they all point to the same doc means everyone in the old version will be looking at something different. Maybe this is the one area we would want to version our docs?
- The score table and explanation for several of the metrics is a bit off. It looks like the values for green/red cutoffs were taken from the median and PODR but that's not exactly what they map to. It's correct that the median is the cutoff for orange/red but the PODR is more like a ~98 and the cutoff for green since 4.0 is a score of 90, not 75.
- In some of the metric score tables it also expresses that the score is the HTTPArchive %-ile but that's a little off. We derive the score curve from the httparchive percentiles, yes, but the 75th percentile in httparchive is a 50 in Lighthouse and the 95th percentile in httparchive is a ~98. It might be tricky or at least confusing to our users to try to present this exact curve mapping.
- Bootup time and mainthread breakdown are some of the most important audits that can't tell users to do anything about automatically. This to me is a big important place to deliver on guides and link to topics like bundle splitting, alternatives to beefy libraries and third-parties, etc. I would love to see these fleshed out.
- Defer offscreen images in an important and common topic that comes up a lot, I would personally prioritize fleshing this doc out a bit more.
- dom-size audit doesn't have a new link, is that expected?

**Comment by carolrivero** [comment]
@mfriesenhahn - to check w/ @paulirish on drop dead date cc: @kaycebasques

**Comment by kaycebasques** [comment]
Pending response from Paul. Kayce will follow up.

**Comment by robdodson** [comment]
Oct 17 is drop dead date. I'm adding these tickets to a LH specific milestone so we can keep tabs on them.

**Comment by mfriesenhahn** [comment]
@kaycebasques, I'll handle the normalization pass if you'll handle verifying content is clear and accurate.

**Comment by kaycebasques** [comment]
Status: Michael is making some qualitative changes to the metrics docs (he's going to DRY up some duplicated content) and then will assign to me to do a quality review of the rest of the Performance docs.

**Comment by kaycebasques** [comment]
Michael is cleaning up metrics posts, there's something wrong with metrics posts

**Comment by kaycebasques** [comment]
Screenshots are updated. I'll follow up with Rob and Michael after standup to figure out scope, deadline, etc.
