### ISSUE TITLE
content: PWA Landing Page

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1345]
**Author**: @petele
**Reviewer**: [Leave blank. web.dev team will assign a reviewer.]

**Target publish date:** 2019-11-11
- [X] Check this box if this is a hard deadline.

- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [ ] 1. I've done my [proposal](https://docs.google.com/document/d/1GbQf3FUU1OdifOsYQpjZfs59y_kZb2JwHhfqD0AEVBo/edit)
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@Snugug please add a link to your doc. Thanks.

**Comment by petele** [comment]
Landed in #1817
