### ISSUE TITLE
content: What are Progressive Web Apps

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1346]
**Author**: @Snugug 
**Reviewer**: @jpmedley 

**Target publish date:** 2019-11-11

- [X] Check this box if this is a hard deadline.
- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [x] 1. I've done my [proposal](https://docs.google.com/document/d/1wA_ZXBD6-v8GTaVskmkftUjMEY7BsTTLCBmQtJIbo1w/edit)
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #2049
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by Snugug** [comment]
Ping on getting this reviewed

**Comment by carolrivero** [comment]
According to our timelines for Wave 3 of CDS related posts, https://docs.google.com/spreadsheets/d/1_tGAAlpYlpVjGsSo3kz_jvhxLIj7oVdVvWgTwL6SriM/edit#gid=12070013
- this will fall under Wave 3. Drafts are due on Oct 28 and we will start reviewing then for a launch date of on or before Nov 6.

All reviewers are booked up until then. Thanks.

**Comment by carolrivero** [comment]
@kaycebasques please assign a reviewer. should it be jpmedley?

**Comment by kaycebasques** [comment]
@petele have you gotten around to reviewing this?

**Comment by jpmedley** [comment]
Richard is processing my feedback now. We should be ready for markdown
conversion soon.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by petele** [comment]
Yep, I've reviewed and asked Joe to take the next steps.

**Comment by kaycebasques** [comment]
Joe has reviewed this. Needs to follow up with Sam. Joe thinks it's ready for Markdown conversion but not sure.

**Comment by Snugug** [comment]
There were a few questions Joe had that I answered and am waiting on follow up on but if he thinks it's ready to go I do to!

This is meant to be part of a new Progressive Web App section of web.dev and I don't know if the work needed to make that happen has been put in place with.  There is a bunch of content tagged with PWA for that section or related to that section.

**Comment by jpmedley** [comment]
Sam,

I apologize. I thought the ball was in your court. Looking now.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by kaycebasques** [comment]
@jpmedley to double-check if this ready to move forward or if we need to keep iterating

**Comment by jpmedley** [comment]
This is blocked. Sam is out until Nov 1.

**Comment by kaycebasques** [comment]
@kaycebasques to shelf this because we're going to revisit PWA later

**Comment by Snugug** [comment]
Hey, before we do, this is ready to go, as is https://github.com/GoogleChrome/web.dev/issues/1349. All comments have been addressed.

**Comment by kaycebasques** [comment]
Thanks @Snugug, I had heard this content was far along but the PR didn't reference this issue so I was unaware that they were related.

@petele @jpmedley since Joe has already reviewed the Google Doc and there is a PR for it, I think we should just see it through and land the content. We can mark it as `draft: true` so that it doesn't show up prematurely.

**Comment by kaycebasques** [comment]
Whoops, my last comment was inaccurate.

Next step is for @Snugug to submit a PR.

**Comment by Snugug** [comment]
I haven't "been taught" how to submit PRs for web.dev yet; @jpmedley has been submitting them. If someone has a couple minutes to walk me through the stuff I may not already know from my time doing OSS work, I'm happy to submit this as a PR

**Comment by jpmedley** [comment]
I'm on it.

**Comment by kaycebasques** [comment]
@jpmedley is #1838 ready for a web.dev style review from @mfriesenhahn or do you need to review the PR first?

**Comment by jpmedley** [comment]
It's ready. I reviewed it in Docs.

**Comment by mfriesenhahn** [comment]
Hi, folks. Is this supposed to go in `/installable`? (Right now, it's in a new `pwas` folder, which seems duplicative.

**Comment by petele** [comment]
No, it should go in the PWAs folder, installable will get a more specific focus as we work through things.

**Comment by Snugug** [comment]
No. Pete and I are working on building out a new PWA section

**Comment by Snugug** [comment]
Hey all, just giving this a post-Thanksgiving bump
