### ISSUE TITLE
content: How Progressive Web Apps Drive Business Success

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1347]
**Author**: Sébastien Fourault
**Reviewer**: @jpmedley 

**Target publish date:** 2020Q2 (April)

- [ ] Check this box if this is a hard deadline.
- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [ ] 1. I've done my [proposal](https://docs.google.com/document/d/1r24LqXyjBJwzs78Qd7TMKLrXMtxC4qlQp6748olYbzo/edit)
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@Snugug  please provide an update on draft. Wave 3 drafts are due today. Thanks.
