### ISSUE TITLE
content: Strategies for Adopting Progressive Web Apps

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1348]
**Author**: @snugug
**Reviewer**: @jpmedley 

**Target publish date:** 2019-11-11
- [X] Check this box if this is a hard deadline.

- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [ ] 1. I've done my [proposal](https://docs.google.com/document/d/1NhV8NN3-x35Q2eLyTNc1P_WDI77aKkU5dsOIAlLXmDg/edit#)
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@Snugug  please provide an update on draft. Wave 3 drafts are due today. Thanks.
