### ISSUE TITLE
content: Create a reliable offline experience

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1354]
**Author**: @petele 
**Reviewer**: @jpmedley 

**Target publish date:** 2019-11-11
- [ ] Check this box if this is a hard deadline.

- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [ ] 1. I've done my [proposal](https://docs.google.com/document/d/1k0x7yVf4-B66BWiw5OANar319eqbnIZWbPRZ8mTT1NQ/edit)
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@jpmedley  please provide an update on draft. Wave 3 drafts are due today. Thanks.
