### ISSUE TITLE
content: Patterns for promoting installation

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1357]
**Author**: @jpmedley @tropicadri 
**Reviewer**: @jpmedley 

**Target publish date:** 2019-11-11
- [X] Check this box if this is a hard deadline.

- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [x] 1. I've done my [proposal](https://docs.google.com/document/d/1DEkvbCZEW2tP_N1ibyCUgo9vZP2xFKW1hVP1m_fGb_0/edit)
- [X] 2. Proposal approved — _reviewer checks this_
- [X] 3. I've added a draft to my [proposal](https://docs.google.com/document/d/1DEkvbCZEW2tP_N1ibyCUgo9vZP2xFKW1hVP1m_fGb_0/edit)
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@Snugug  please provide an update on draft. Wave 3 drafts are due today. Thanks.

**Comment by jpmedley** [comment]
@petele I couldn't review this. Not only does it have open issues, but it also needs to be broader than Android. That could be written in several different ways. We should talk about this when you get back.
