### ISSUE TITLE
content: Detecting if your app is running in an installed state

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1359]
**Author**: @petele 
**Reviewer**: @jpmedley 

**Target publish date:** 2019-11-11
- [X] Check this box if this is a hard deadline.

- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [ ] 1. I've done my [proposal](https://docs.google.com/document/d/1Epqi8TXYJOPrmsm1fZWzbIYqR3FU6MdSNUK7YpUUkHw/edit)
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@jpmedley  please provide an update on draft. Wave 3 drafts are due today. Thanks.

**Comment by petele** [comment]
Closing, rolled into install docs.
