### ISSUE TITLE
content: Getting your PWA listed in app stores

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1361]
**Author**: @snugug
**Reviewer**: [Leave blank. web.dev team will assign a reviewer.]

**Target publish date:** 2019-11-11
- [X] Check this box if this is a hard deadline.

- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [ ] 1. I've done my [proposal](https://docs.google.com/document/d/1GtDsZ_WZepvhm6LBQcPti9cwYR61Hf6GWmOL6xZeipQ/edit)
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
moving this to post cds since priority changed to P2.

**Comment by carolrivero** [comment]
@kaycebasques - Please assign a reviewer.

**Comment by carolrivero** [comment]
@kaycebasques which sprint should this be added to?

**Comment by jpmedley** [comment]
Activity!

**Comment by carolrivero** [comment]
@jpmedley -  this issue was opened in Aug last year. Do you have an ETA when you plan to kick this back up? If it's not for another quarter. I recommend closing this issue and submitting a new issue once you're ready to start the work. Thanks.

@kaycebasques - FYI
