### ISSUE TITLE
Rebuild search box.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1368]
**Is your feature request related to a problem? Please describe.**
As part of our devsite migration we'll need to recreate the search box that appears on every page.

**Describe the solution you'd like**
A new search box that's actually keyboard and screen reader accessible!

**Additional context**
We might want to use something like [Algolia](https://www.algolia.com) to power our search. If so, perhaps we can reuse their search widget and style it to match our site?

**Comment by samthor** [comment]
See #1424.
