### ISSUE TITLE
Rebuild search results page.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1369]
**Is your feature request related to a problem? Please describe.**
Related to #1368. As part of the devsite migration we need to redo our search results landing page.

**Describe the solution you'd like**
A new page to replace https://web.dev/s/results. Probably powered by [Algolia](https://www.algolia.com)

**Comment by rajasekarm** [comment]
I can work on this. Do we've a new design for search landing page?

**Comment by robdodson** [comment]
Going to close this for now. I think @samthor and I decided to see if we can get by with just using the search box itself and not needing a result page.
