### ISSUE TITLE
Image helper classes?

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#137]
It might be nice to give authors the ability to justify-left/right, center, and stretch their images. I (think?) webfu does something similar. Creating this ticket to expose some helper classes for folks.

**Comment by prabodh1194** [comment]
Hi,

This says "good first issue". I'm looking to help. Is there some form of onboarding that I should go through?

Thanks.

**Comment by robdodson** [comment]
I think this may be fixed.

On the site you can do `.attempt-left/right` to float left or right. If you want an image to be full width, just make it larger than 633px and the DevSite build pipeline will handle creating smaller sizes and setting up srcset.
