### ISSUE TITLE
Rebuild service worker.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1370]
**Is your feature request related to a problem? Please describe.**
As part of the devsite migration, we'll need to author our own service worker and PWA manifest. We'll need to make sure we transition smoothly off of the old service worker.

**Describe the solution you'd like**
A new service worker that dynamically caches pages as the user views them. Likely built with [Workbox](https://developers.google.com/web/tools/workbox/).

**Comment by jeffposnick** [comment]
Just wanted to throw some random thoughts out there after being looped in on the discussion from https://github.com/GoogleChrome/web.dev/pull/1719#discussion_r337572735

First,

https://github.com/GoogleChrome/web.dev/blob/93694df6ec4874a85975127ce4a1856066e76bf5/src/lib/sw.js#L9

is not a good idea. (See https://github.com/GoogleChrome/workbox/issues/2259.) It will precache the contents of `/offline.html` once for each user, when the service worker is first installed, and then never update it, even if you change the contents of `/offline.html` and rebuild your site. The recommended approach is to use one of the Workbox build tools to generate the precache manifest (which will add a revision parameter containing a hash of the current `/offline.html` contents automatically), or alternatively, to use something like [this recipe](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#warm_the_runtime_cache) to manually add `/offline.html` to the cache, which will end up refreshing things each time an updated service worker is installed.

I'm also concerned about an approach that caches full HTML documents and serves them via a stale-while-revalidate strategy,

https://github.com/GoogleChrome/web.dev/blob/93694df6ec4874a85975127ce4a1856066e76bf5/src/lib/sw.js#L20-L23

You're going to end up caching a lot of duplicated HTML (basically, all of the common headers/footers on a page), and more importantly, whenever you do update those headers/footers and redeploy your site, users are going to effectively see an arbitrarily old version of HTML for each URL that they revisit.

There's background on why this is a problem at
- https://jeffy.info/2017/01/24/offline-first-for-your-templated-site-part-2.html
- https://developers.google.com/web/updates/2018/05/beyond-spa#common_pitfalls

Working around this issue requires a more nuanced response strategy than runtime caching of full HTML.

CC: @philipwalton

**Comment by jeffposnick** [comment]
Just a couple of notes based on our further conversation:

There are instructions at https://developers.google.com/web/tools/workbox/modules/workbox-sw#using_local_workbox_files_instead_of_cdn about switching to a local copy of Workbox, since there's really no reason for you all too pull things in from the CDN.

**Comment by samthor** [comment]
Thanks for the hints @jeffposnick . We know that caching full HTML isn't ideal but we might still ship with it for now just in the interest in getting it out.

* Offline page precache: thanks, we'll include that in the proper precache manifest

* I thought general advice was to use the CDN, but we're happy to serve it locally

**Comment by jeffposnick** [comment]
Using the CDN is definitely the simplest approach, but starting with Workbox v5, we're going to be encouraging more folks to use their own (custom, local) Workbox bundles.

Since you all definitely have the technical know-how and ability to serve a local copy of Workbox, I figured I'd point you in that direction today.

**Comment by samthor** [comment]
Not related to other comments: we also need to make sure we nuke the DevSite SW when ours gets installed.
