### ISSUE TITLE
Recreate our cookies banner.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1386]
**Is your feature request related to a problem? Please describe.**
As part of the DevSite migration we'll need to recreate the cookie banner notification.

**Describe the solution you'd like**
A cookies banner!

**Comment by rajasekarm** [comment]
Can I work on this? Do we've a design for the cookies banner?

**Comment by rajasekarm** [comment]
Sure, Thanks.

**Comment by robdodson** [comment]
Fixed by #1552
