### ISSUE TITLE
Celebrate URLs with good Lighthouse scores

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1387]
**Is your feature request related to a problem? Please describe.**

1. Go to web.dev/measure
1. Audit a page that gets 99 or 100 in each category

**Describe the solution you'd like**

web.dev celebrates the page's success in some way. E.g. the Lighthouse UI in DevTools has animations of fireworks when a page gets good scores.

Also note that the current UI looks a little incomplete. It's expecting to have to surface some opportunities for improvement, but there are none. At minimum, this section can say "Congratulations!" or something instead of being blank.

![web dev_measure](https://user-images.githubusercontent.com/4713486/63393890-017a6f80-c372-11e9-979a-72d6e7077e0e.png)

**Comment by rajasekarm** [comment]
I tried to work on this, But When I sign in with google it redirects to web.dev from localhost. 

@kaycebasques - Can you help in understanding how to set up auth in local machine?
