### ISSUE TITLE
collection: Capabilities IA

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1420]
**Author**: @petele 
**Reviewer**: @jpmedley 
**Process**

Drop a link to your proposal doc in the 1st step below and check the box. A
member of the web.dev team will assign a reviewer, who will help you complete
the remaining steps.

- [ ] 1. I've done my proposal <add a link to your proposal doc>
- [ ] 2. Proposal approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@petele - we added this to this sprint. Please provide an update if you have an IA ready. Thanks.

**Comment by kaycebasques** [comment]
Joe & Pete might start on IA this week but Joe is traveling so deferring to next sprint.

**Comment by robdodson** [comment]
I think the idea is that capabilities will be rolling out as blog posts so they wouldn't have an IA.
@petele mentioned that the list of capabilities docs he knows about are labeled in our issue tracker: https://github.com/googlechrome/web.dev/issues?q=is%3Aopen+is%3Aissue+label%3Acapabilities

I think we can close this and track the individual posts.

**Comment by jpmedley** [comment]
I'll get Pete's take on this. (He'll be in my office shortly.) I frankly had a problem with constructing capabilities around a single IA. "Capabilities" (Fugu) is a somewhat arbitrary category which means there are things that meet the definition of a capability but are not included. An example of this is WebXR. On the flip side are things like changes to the a web app's storage abilities that might seem to an outsider to be unrelated to bringing native features to the web.' In general, I think there's a potential for confusion that I'm uncomfortable with.

**Comment by robdodson** [comment]
Right, I think that's why we've decided to not do an IA for capabilities and instead initially publish them as blog posts. We may choose to represent them in a different way in the future, but for now, blog posts will work.

**Comment by petele** [comment]
+1

Once it moves out of origin trial and into stable, we'll need to figure out how to put them into a sane IA, but that's a few months off yet, and we can pick it up after CDS and all of the other craziness.

**Comment by robdodson** [comment]
ok. let's close this ticket. We're tracking the individual articles in our CDS spreadsheet.

**Comment by jpmedley** [comment]
No 'backlog' bucket then?

**Comment by robdodson** [comment]
> No 'backlog' bucket then?

For stuff that doesn't have immediate actions I'd prefer to close the tickets. Mostly to keep the repo from filling up with stale items. When we have a plan for what we want to do next we can create a new ticket.
