### ISSUE TITLE
collection: Metrics IA

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1421]
**Author**: @philipwalton 
**Reviewer**: @kaycebasques 

**Process**

Drop a link to your proposal doc in the 1st step below and check the box. A
member of the web.dev team will assign a reviewer, who will help you complete
the remaining steps.

- [x] 1. I've done my proposal https://docs.google.com/document/d/1VhwPicdM9klxu05Bp9rfsc2zRG7BtQH6BSOQKK7UguE/edit?ts=5d3761ed
- [x] 2. Proposal approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@kaycebasques - this is . ready for review.

**Comment by kaycebasques** [comment]
I will review today

**Comment by kaycebasques** [comment]
Just reviewed. The IA LGTM. There's a few unresolved questions but none of them should block @philipwalton from starting to draft the content. So @philipwalton you can start drafting content.

**Comment by robdodson** [comment]
@kaycebasques are you cool moving this one to Done?
