### ISSUE TITLE
collection: Notifications

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1422]
**Author**: @katejeffreys 
**Reviewer**: @kaycebasques  

Related issues:

* #1673
* #1672 
* #1671 
* #1662
* #1657
* #1588

Related PRs:

* #1933
* #1732 
* #1730
* #1693 
* #1678

**Comment by carolrivero** [comment]
@katejeffreys to set up a meeting to review.

**Comment by kaycebasques** [comment]
This is ready to review but @jpmedley doesn't know when he can get to it

**Comment by kaycebasques** [comment]
@mfriesenhahn to check with @jpmedley about whether @mfriesenhahn should review this instead

**Comment by kaycebasques** [comment]
Unclear how much of this IA wants to land by CDS

**Comment by kaycebasques** [comment]
Rob is asking Rowan if we can launch at end of November and Joe is tentatively back on reviewing this.

**Comment by robdodson** [comment]
Rowan said he was tentatively ok deferring this work until after CDS.

**Comment by katejeffreys** [comment]
Spoke with @PaulKinlan - I want to get as much done as possible over the next 6 weeks

**Comment by carolrivero** [comment]
Please refer to go/cds19-webdev-content-proposals for the workload we have slated for the team leading up to CDS. We'll need to include this in our priorities. Thanks.

**Comment by carolrivero** [comment]
@kaycebasques this looks like an old request - can we mark this as obsolete (closed)?
