### ISSUE TITLE
collection: Feature phone IA

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1423]
**Author**: @kosamari 
**Reviewer**: @robdodson @mfriesenhahn 

**Process**

Drop a link to your proposal doc in the 1st step below and check the box. A
member of the web.dev team will assign a reviewer, who will help you complete
the remaining steps.

- [x] 1. I've done my proposal  https://docs.google.com/document/d/1nW-H6vs7VJpNKWHglOvvTQpxx1MQ55YgUd-H9qJu19E/edit?usp=sharing
- [ ] 2. Proposal approved — _reviewer checks this_

**Comment by kaycebasques** [comment]
Rob is meeting to discuss latest plans today.

**Comment by kaycebasques** [comment]
@kosamari after you draft out your introduction and IA please assign back to me and @robdodson

**Comment by kosamari** [comment]
@kaycebasques 
Link to doc : https://docs.google.com/document/d/1nW-H6vs7VJpNKWHglOvvTQpxx1MQ55YgUd-H9qJu19E/edit?usp=sharing

**Comment by kosamari** [comment]
note: this collection will be renamed to something else, not sure that yet but it'll include other devices like Android Go

**Comment by kaycebasques** [comment]
@kosamari you mentioned previously that you're drafting an introduction for this content. Are you still working on that?

**Comment by kaycebasques** [comment]
@robdodson to review the IA

**Comment by robdodson** [comment]
Left a few comments. My biggest question is if the doc titles are still a work in progress. They seem a bit short right now.

**Comment by kaycebasques** [comment]
Feature phone content probably won't need to launch in CDS timeline. Surma might work on PROXX 2 but that also is not in CDS timeline.

**Comment by kaycebasques** [comment]
There doesn't appear to be any concrete plans to work on this in the short-term, so I'll close for now.
