### ISSUE TITLE
content: WebXR Device API

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1436]
**Author**: @jpmedley
**Reviewer**:  @kaycebasques 

**Target publish date:** 2019-09-19

- [x] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal <add a link to your proposal doc>
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1726
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by jpmedley** [comment]
@kaycebasques Can I get a copy edit of this? It needs to go out soon. 

I think I may have labeled it wrong. I apologize.

**Comment by kaycebasques** [comment]
Just reviewed. Back to @jpmedley to incorporate feedback.

**Comment by jpmedley** [comment]
How do we handle series content (see as how this is part I of a series)?

**Comment by jpmedley** [comment]
I mean how do we handle it in GitHub tickets.

**Comment by kaycebasques** [comment]
@jpmedley create a separate issue for each post if they are landing one at a time. If multiple posts are landing at the same time then it's OK to reference them all in a single issue and PR if that makes more sense. In general smaller issues and PRs are easier to review so I prefer that route.
