### ISSUE TITLE
content: Progressively Enhance Your PWA

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1442]
**Author**: @petele
**Reviewer**: @jpmedley 

**Target publish date:** 2019-11-11
- [X] Check this box if this is a hard deadline.

- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [ ] 1. I've done my [proposal](https://docs.google.com/document/d/1esuUa4UGgqbjlc__wsmFYkufcHffMkXXK3171Zw4s5w/edit)
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@kaycebasques which sprint should this be added to?

**Comment by tomayac** [comment]
On my radar 🤖

**Comment by tomayac** [comment]
🤖
