### ISSUE TITLE
I can create a folder for the Spanish language?

### ISSUE THREAD

**Issue by rosepac** [GoogleChrome/web.dev#1445]
Hello, I would like to translate the project into Spanish. I understand that the folder would go in the path of: web.dev / src / site / content / es I guess it would imply some configuration other than that, but I could work on the translation; for the moment. Until the rest of the parameters are modified.

Is there a problem creating a fork and translating? Or I generate a parallel project.

Despite being registered with Github for quite some time, I don't have much experience in creating commits on global projects and I'm a little afraid of "messing up something".

A Greeting

**Comment by robdodson** [comment]
Hey @rosepac, we're not quite ready to add translation support yet but we're working on it!
I would suggest following this issue: https://github.com/GoogleChrome/web.dev/issues/836
@agektmr and I did some work on this recently, but it may be a few more months before we're ready to ship anything. When we are ready, we plan to accept community contributions.
