### ISSUE TITLE
<source> element support for lazy loading

### ISSUE THREAD

**Issue by puzumaki** [GoogleChrome/web.dev#1448]
**Is your feature request related to a problem? Please describe.**
Recently read the native lazy loading feature, which only mentions use for `<img>` and `<iframe>`. What about `<source>` for `<picture>`, so it may be applied to WebP formats or at minimum support the HTML5 elements?

**Describe the solution you'd like**
Add the loading attribute to <source> as well, if it isn't already.

**Describe alternatives you've considered**
NA

**Additional context**
This may already be an element included, it wasn't in the documentation though.

**Comment by robdodson** [comment]
@housseindjirdeh do you have any thoughts?

**Comment by bazzadp** [comment]
@addyosmani has [an article which suggests this is already present](https://addyosmani.com/blog/lazy-loading/):

> **Examples**
> 
> The loading attribute works on `<img>` (including with srcset and inside `<picture>`) as well as on `<iframe>`:
> 
> ```
>
> <picture>
>   <source media="(min-width: 40em)" srcset="big.jpg 1x, big-hd.jpg 2x">
>   <source srcset="small.jpg 1x, small-hd.jpg 2x">
>   <img src="fallback.jpg" loading="lazy">
> </picture>
> ```

So if I’m reading that correctly and that’s accurate (no offence meant Addy!) then is it just a matter of updating: https://web.dev/native-lazy-loading/ to state this should be set on the fall back `<img>` element within the `<picture>` element?

**Comment by robdodson** [comment]
hm, what about the `<source>` elements themselves tho?

**Comment by bazzadp** [comment]
> hm, what about the `<source>` elements themselves tho?

Not sure what you mean? `srcset` is an attribute on `<source>` tags within `<picture>` tags and is included according to Andy's comment and that attribute is the only way of specifying images with a `<source>` element (at least [according to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source)).

**Comment by robdodson** [comment]
I may be misunderstanding, but I was wondering if it's possible to specify that `<source srcset="small.jpg 1x, small-hd.jpg 2x">` should be loaded lazily. In the example above the `loading=lazy` attribute is set on the fallback image, but it doesn't mention how to lazily load `small.jpg` or `small-hd.jpg`. It seems weird that the fallback image can be lazy loaded but the other sources can't. I would imagine folks would want to do something like `<picture loading=lazy>`

**Comment by bazzadp** [comment]
Yes it does. Emphasis mine:

> The loading attribute works on <img> **(including with srcset and inside <picture>)**

And then the comment in the code states how this is driven off the `<img>` element, even for `<source srcset=...>` elements:

```
<!-- Lazy-load images in <picture>. <img> is the one driving image
loading so <picture> and srcset fall off of that -->
```

I admit it may not be the most obvious way of doing this, but seems to me this covers it. You agree?

**Comment by robdodson** [comment]
ah I see. Maybe we should move that explanation out of the comment and into the text above. For whatever reason I just glanced at the comment but it didn't compute. Maybe because it's getting close to 4pm here 😅
