### ISSUE TITLE
Angular CLI module option --route not avaialble

### ISSUE THREAD

**Issue by marcorpsa** [GoogleChrome/web.dev#1449]
In the article https://web.dev/route-level-code-splitting-in-angular/
There is this command
`ng g module nyan --module app --route nyan`

With Angular CLI 8.0.3 if I run 
`ng generate module --help`
I get 
`options:
  --defaults 
    When true, disables interactive input prompts for options with a default.
  --dry-run (-d)
    When true, runs through and reports activity without writing out results.
  --flat
    When true, creates the new files at the top level of the current project root.
  --force (-f)
    When true, forces overwriting of existing files.
  --help
    Shows a help message for this command in the console.
  --interactive
    When false, disables interactive input prompts.
  --lint-fix
    When true, applies lint fixes after generating the module.
  --module (-m)
    The declaring NgModule.
  --project
    The name of the project.
  --routing
    When true, creates a routing module.
  --routing-scope
    The scope for the new routing module.`
No --route option - what am I missing?

**Comment by robdodson** [comment]
@mgechev do you have any thoughts?

**Comment by mgechev** [comment]
@marcorpsa thanks for the interest! You're using an old version of the Angular CLI. In the [post](https://web.dev/route-level-code-splitting-in-angular/#route-level-code-splitting) we mention that we introduced the lazy-route generator as part of version 8.1.0.

@robdodson, we can close the issue.
