### ISSUE TITLE
Need site stylized PWA logo for PWA collection

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1450]
@robdodson - this is the title image we talked about for the PWA collection. 

Not sure how to tag it for artwork, can you help out?

Date needed: 2019-11-11

**Comment by robdodson** [comment]
@carolrivero would it be possible to request help from either Huge or someone on Hwi's team for this?

**Comment by carolrivero** [comment]
@robdodson I'm checking w/ Hwi. Stay tuned!

**Comment by carolrivero** [comment]
Jiwoong confirmed that he is able to create this tile. I cannot find him in GH though. @robdodson - does he have access to our repo? Thanks.

**Comment by robdodson** [comment]
cc @jimoong

**Comment by jimoong** [comment]
Thanks for inviting me here. Will work on this.

**Comment by carolrivero** [comment]
Thanks, jimoong. I'm adding this to our current sprint ending on Sept 11.

**Comment by jimoong** [comment]
Sorry for delay. I've been focused on other priority work last week and this week. Here is the first try of the PWA illustration that fits into web.dev illustration style. Please take a look and let me know if it works for this case.
[pwa.svg.zip](https://github.com/GoogleChrome/web.dev/files/3659526/pwa.svg.zip)

**Comment by robdodson** [comment]
That looks good to me. @petele what do you think?

**Comment by petele** [comment]
The PWA logo overlaid on the shield doesn't fit the similar style to the other image that are on https://web.dev/learn. I was more thinking stuff along these lines: [1](https://web.dev/images/collections/reliable.svg), [2](https://web.dev/images/collections/installable.svg), [3](https://web.dev/images/collections/lighthouse-performance.svg).

At the same time, the Frameworks sections appears to just use the product logos, or maybe a slightly tweaked version of that. If we want to use the PWA logo, I think we should keep to it's more natural form.

**Comment by jimoong** [comment]
Thanks for the feedback. I was also thinking tweaking the logo would fit nicely to the Framework section, so the version that I created was the sort of attempt to achieve that. Actually, I had hard time to find the official logo of the PWA since I couldn't find it from the Google Developer site (https://developers.google.com/web/progressive-web-apps). Could anyone point me to the official logo? Or do we want the illustration to be aligned with other older illustrations?

**Comment by robdodson** [comment]
I thought the one in Lighthouse was the official one, but I could be mistaken. Pete, do you know?

![image](https://user-images.githubusercontent.com/1066253/65732873-b5ad9b00-e080-11e9-8df6-133e6c756d70.png)

> The PWA logo overlaid on the shield doesn't fit the similar style to the other image that are on https://web.dev/learn. I was more thinking stuff along these lines: 1, 2, 3.

Maybe one option would be to do something illustrative like these sections, but ensure it contains the PWA logo? How important is it to you that the logo be in there Pete?

**Comment by petele** [comment]
The official PWA logo is at https://github.com/webmaxru/progressive-web-apps-logo

The one on the Lighthouse page is an amalgamation of several different logos.

**Comment by robdodson** [comment]
@petele if you'd like an illustration that's a bit more like the other ones at the top of learn could you provide some suggestions around what kind of imagery you'd want to incorporate into that? Maybe a phone with the PWA logo on it? Any other iconagraphic elements or themes you'd want to try to include?

**Comment by jimoong** [comment]
Could we confirm which section that this content would be belong to? Because each section has unique style to its illustrations, it'd be easier for me to think about the style of illustration of this.
And I just found this type of PWA logo(?) and it seems sort of official? It looks better and seems to work better as illustration material. What do you think?
![www youtube com_watch_v=1QILz1lAzWY](https://user-images.githubusercontent.com/1054804/66170534-77bcf380-e5f9-11e9-8edb-cd4901e14bac.png)

**Comment by robdodson** [comment]
Hey Jiwoong, I'm pretty sure the illustration you've shared is not official. I think we made that a couple years back for a conference. @petele can confirm. I think the logo here https://github.com/webmaxru/progressive-web-apps-logo is what we should be using.

> @petele if you'd like an illustration that's a bit more like the other ones at the top of learn could you provide some suggestions around what kind of imagery you'd want to incorporate into that? Maybe a phone with the PWA logo on it? Any other iconagraphic elements or themes you'd want to try to include?

Pete can you respond to this point? Want to make sure we can move forward on this and not hold up the docs.

**Comment by robdodson** [comment]
Hey @jimoong 

I spoke with Pete today. We were thinking of seeing if we could use this logo https://github.com/webmaxru/progressive-web-apps-logo inside of an illustration of a mobile device. This will go into the "Realize what the web can be" section at the top of /learn.

Let me know if you have any questions.

**Comment by jimoong** [comment]
Sorry for late update. There was a week long team workshop last week. Here are draw an illustration with the devices and the PWA official logo to match the style of other illustrations in the section
[pwa.svg.zip](https://github.com/GoogleChrome/web.dev/files/3780395/pwa.svg.zip)

. Let me know what you think.

**Comment by robdodson** [comment]
![image](https://user-images.githubusercontent.com/1066253/67721048-d411f980-f992-11e9-8a2f-cac4698ac6b1.png)

Looks cool, @petele what do you think?

**Comment by jimoong** [comment]
In terms of alignment with other illustrations

![illustrations overview](https://user-images.githubusercontent.com/1054804/67724930-e3e30b00-f99d-11e9-8b5c-96c884794fc9.png)

**Comment by petele** [comment]
Looks great - this was landed in #1817
