### ISSUE TITLE
content: What are the criteria for an installable PWA

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1451]
**Author**: @petele
**Reviewer**: @jpmedley 

**Target publish date:** TBD

- [ ] Check this box if this is a hard deadline.

- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [x] 1. I've done my [proposal](https://docs.google.com/document/d/16CVtmHtk0dJj2FAx5_IHhyNKqVZeEu9mNO2LnhOZY-c/edit)
- [x] 2. Proposal approved — _reviewer checks this_
- [X] 3. I've added a draft to my [proposal](https://docs.google.com/document/d/16CVtmHtk0dJj2FAx5_IHhyNKqVZeEu9mNO2LnhOZY-c/edit)
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by jpmedley** [comment]
@petele I have reviewed the draft and made a few suggestions. Looks good otherwise.

**Comment by petele** [comment]
Dupe of #1353
