### ISSUE TITLE
content: PWAs on iOS

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1453]
**Author**: @[Author's GitHub username.]
**Reviewer**: [Leave blank. web.dev team will assign a reviewer.]

**Target publish date:** Q4
- [ ] Check this box if this is a hard deadline.

- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

- [ ] 1. I've done my [proposal](https://docs.google.com/document/d/1tXtg5jzUw74trufMPs_BmMyaO55_E4nWZ0qXCGkGmE8/edit)
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

CC: @b1tr0t

**Comment by kaycebasques** [comment]
@petele going to close this under the assumption that it's an older idea that may not happen. Feel free to re-open if you're planning on working on it.
