### ISSUE TITLE
Checklist Component

### ISSUE THREAD

**Issue by Snugug** [GoogleChrome/web.dev#1455]
**Is your feature request related to a problem? Please describe.**
Needed for #1349, is the ability to display content in a way that can be checked off of a list, like a checkbox, that saves progress either locally or to a logged i account

**Describe the solution you'd like**
A component, compatible with https://github.com/GoogleChrome/web.dev/issues/1454 (or possibly an extension of it) that includes a circle/clickable area that, when clicked, indicates to the user that it has been selected, allowing for all items to be selected in this way. When selected, a user who returns to the page will have those items selected for them again

**Describe alternatives you've considered**
HTML checkboxes, not having them?

**Additional context**
Preferred experience for #1349

**Comment by robdodson** [comment]
Is this a blocker for your content? I'd like to have an agency or perhaps a member of chrome UX provide design help on it. Also, we currently reside inside of DevSite and are pretty limited in what kinds of client-side JS we can run. We're currently working to migrate out of DevSite which will give us a lot more freedom in this area. So if it's possible to consider this as a "phase 2" feature for your content, I think that might be the easiest approach.

**Comment by Snugug** [comment]
Yah we can consider this as Phase 2 of our content if that's easier. The #1454 unfortunately isn't.
