### ISSUE TITLE
content: SameSite cookies

### ISSUE THREAD

**Issue by carolrivero** [GoogleChrome/web.dev#1460]
**Author**: @rowan-m 
**Reviewer**: @jpmedley  

**Target publish date:**
- [ ] Check this box if this is a hard deadline.
- [x] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

- [x] 1. I've done my proposal
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1367
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@katejeffreys to check w/ @rowan-m

**Comment by kaycebasques** [comment]
@katejeffreys & @rowan-m any update here?

**Comment by kaycebasques** [comment]
@kaycebasques to sort out whether this issue overlaps with #1461

**Comment by kaycebasques** [comment]
@rowan-m please assign this issue to me when it's ready for review

**Comment by kaycebasques** [comment]
@rowan-m does this need to go out before CDS?

**Comment by carolrivero** [comment]
@rowan-m - also if you could confirm if this is CDS related, that would be helpful. Thanks.

**Comment by rowan-m** [comment]
Sorry for the delays! #1367 is now updated with the latest drafts separating this into two articles.

**Comment by rowan-m** [comment]
And yes, going live before CDS would be super helpful.

**Comment by kaycebasques** [comment]
@rowan-m you're up to incorporate @jpmedley's feedback. Once Joe approves the PR we can merge.

**Comment by kaycebasques** [comment]
Looks like @jpmedley has finished his review, so off to @rowan-m to incorporate the feedback

**Comment by jpmedley** [comment]
The updates are not going out as planned.

**Comment by kaycebasques** [comment]
@jpmedley please create a new issue for updates to the samesite cookies article. This issue (#1460) was created to track the original work.
