### ISSUE TITLE
content: Same site cookies placeholder 2

### ISSUE THREAD

**Issue by carolrivero** [GoogleChrome/web.dev#1461]
**Author**: @rowan-m 
**Reviewer**: @katejeffreys 
**Target publish date:**
- [ ] Check this box if this is a hard deadline.

- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

- [ ] 1. I've done my proposal
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@katejeffreys to check w/ Rowan

**Comment by kaycebasques** [comment]
@katejeffreys have you got an update from @rowan-m?

**Comment by kaycebasques** [comment]
@kaycebasques will review PR #1367 which is related to this topic

**Comment by kaycebasques** [comment]
All of the work seems to be happening in #1367. Issue #1460 is tracking that work so I'll close this one.
