### ISSUE TITLE
Mysterious server side "changes".

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1466]
**Describe the bug**
On Wednesday I pushed a new branch to GitHub so that my in-progress work will be backed up. There have been [no server-side commits to this branch](https://github.com/GoogleChrome/web.dev/commits/video).  My local status shows that I am behind 1.

```
* video   496465c2 [origin/video: ahead 1, behind 1] Start work on video article.
On branch video
Your branch and 'origin/video' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
```

The `git pull` command does indeed resolve this issue. But `git log` and `git show` display no actual changes to the branch after the pull.

I don't think I've seen this on other repos. 

**To Reproduce**
I don't know.

**Expected behavior**
A branch without server-side changes won't show 'behind `' as it's status.

**Screenshots**
![Screen Shot 2019-08-30 at 7 27 27 AM](https://user-images.githubusercontent.com/8204171/64029931-6c5a4200-cafa-11e9-861f-5c7f0e04e5bd.png)

(The `git ls` command is one of my aliases: `alias.ls=show --pretty=format: --name-only`.)

**Comment by jpmedley** [comment]
I now believe this to be some kind of local index corruption. I've recloned the repo. I'll let you know if it happens again.

**Comment by robdodson** [comment]
Hey Joe, do you mind if we close the issue and reopen if it occurs again?
