### ISSUE TITLE
Handle posts that appear in multiple collections

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1469]
**Is your feature request related to a problem? Please describe.**
Various Lighthouse audits appear in multiple report sections and therefore need to appear in multiple web.dev collections. However, the current UI assumes each post appears in only one collection. (The breadcrumb and **Next article** components are based on the post's path.)

**Describe the solution you'd like**
- Remove the breadcrumbs component.
- Remove the **Next article** component.
- Add previously designed components for signposting:
  - A component indicating what collection(s) a post belongs to.
  - A tags component
  - A **Related posts** component
- Add a footer that includes top-level links.

**Describe alternatives you've considered**
Any solution that assumes a single position in the IA for each post won't work. Any solution that relies on a user journey to generate signposts won't work because users won't always enter a post from another location on web.dev.

**Comment by kaycebasques** [comment]
Let's re-open this if we commit to actually working on it.
