### ISSUE TITLE
<portal> blog post: rephrase the expression to emphasize that <portal> is still a proposal

### ISSUE THREAD

**Issue by uskay** [GoogleChrome/web.dev#1472]
As discussed in [the thread](https://twitter.com/tomayac/status/1168087512931274752?s=20), would like to fix the expression and set the tone of the article to state that `<portal>` is a new Web platform API which is still in the __ **proposal** __ phase.

@tomayac @robdodson could you please check?

**Comment by kaycebasques** [comment]
@uskay needs to commit the changes to his fork and then I can merge
