### ISSUE TITLE
content: SMS OTP Retrieval API

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#1482]
**Author**: @agektmr 
**Reviewer**: @sso-google @rowan-m @katejeffreys 

**Target publish date:** ASAP

- [x] Check this box if this is a hard deadline.
- [x] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

- [x] 1. I've done my proposal 
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a [draft to my proposal doc](https://docs.google.com/document/d/1f3DbSEi6rMDmQE4yyFhf0qELOcqUUBbb310t3T7AlO8/edit#)
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1550
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by robdodson** [comment]
Hey @agektmr, do you have a link to your proposal doc? I think you instead sent a link to the CDS tracker.

**Comment by robdodson** [comment]
You can use [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit) for your proposal.

**Comment by agektmr** [comment]
@robdodson attached the header template to the draft (sill WIP).

**Comment by petele** [comment]
Sorry for the late request on this, but it likely needs to go into the current milestone as it's tied to the m78 beta launch.

**Comment by jpmedley** [comment]
I just review the draft for @agektmr. I had some questions.

**Comment by kaycebasques** [comment]
I've reviewed the doc. @petele also requested some changes. After you have addressed the requested changes @agektmr please assign the issue back to me.

**Comment by agektmr** [comment]
The article hasn't got signed off yet, plus some technical issues on Chrome side. It's being worked on but needs some more work. I'll assign back to you for final edits once we get sign off from reviewers @kaycebasques

**Comment by kaycebasques** [comment]
@agektmr any movement on this?

**Comment by agektmr** [comment]
@kaycebasques Yes. There was an issue in the origin trial logic, but the fix has been merged and became available in Chrome Beta publicly today. Most of comments in the doc has been approved (still missing some LGTMs though). The pull request is the latest status.
I'd like this to be published as soon as I get sign-offs from reviewers.

**Comment by kaycebasques** [comment]
Great, thanks @agektmr. Please re-assign this to me when all of the technical content has been approved and you're ready for a final technical writer review (by me).

**Comment by kaycebasques** [comment]
@robdodson please publish this no later than 10/9

**Comment by jpmedley** [comment]
Eiji,

Which Chrome beta version did this end up in?

Joe
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by agektmr** [comment]
This is landed on Chrome 78 beta. Updating the 78 beta announcement blog post will be appreciated.
https://blog.chromium.org/2019/09/chrome-78-beta-new-houdini-api-native.html

**Comment by kaycebasques** [comment]
Feedback request done.
