### ISSUE TITLE
content: Preload critical assets to improve loading speed

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/web.dev#1483]
**Author**: @mihajlija @housseindjirdeh 
**Reviewer**: [Leave blank. web.dev team will assign a reviewer.]

**Target publish date:** <2019-10-09>
- [ ] Check this box if this is a hard deadline.

- [x] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

- [x] 1. I've done my proposal https://docs.google.com/document/d/1ieb84XnLeaR1wK3Hevfo_sya3mQWYQcOMXR5IcfcbTw/edit?usp=sharing
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1506 
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by kaycebasques** [comment]
@mihajlija is finishing the draft

**Comment by mihajlija** [comment]
Added draft to the proposal, time to assign a reviewer.

**Comment by kaycebasques** [comment]
@mihajlija please give me comment access to the doc

**Comment by kaycebasques** [comment]
Good stuff. Various small suggestions. @mihajlija you can address the feedback and then go straight to the PR stage. No need for more reviews on this draft.

**Comment by mihajlija** [comment]
@kaycebasques PTAL, I restructured the post a bit to fit in more details in a "how to" section.

**Comment by kaycebasques** [comment]
@robdodson content is ready for deploy

**Comment by robdodson** [comment]
sorry for the delay. Was out last week so still catching up a bit. I'll add this to my calendar to deploy tomorrow!
