### ISSUE TITLE
Remove unused CSS

### ISSUE THREAD

**Issue by pcsingh** [GoogleChrome/web.dev#1492]
According to PageSpeed Insights, On page https://web.dev/ shows that on removing unused CSS it improves the rendering of the page and reduces unnecessary bytes consumed by network activity.

**To Reproduce**
1. Go to 'https://developers.google.com/speed/pagespeed/insights/'
2. Copy this url 'https://web.dev/'
3. Paste it on the above website press ANALYZE button then scroll down in MOBILE type.
4. On Remove unused CSS row, you can see the unused CSS file.

**Screenshots**
![unused_css](https://user-images.githubusercontent.com/44555033/64541698-f480e880-d33f-11e9-9d29-bba4393a6033.PNG)

**Comment by robdodson** [comment]
Hey @pcsingh thanks for sending this along.

Currently web.dev is hosted on a piece of internal infrastructure and we're required to pull in their CSS. We're in the process of migrating off of that infrastructure and when we do, we should be able to remove the unused stuff.

I'm going to close this for now but add a label that it's related to our migration.
