### ISSUE TITLE
Slugs for internal links

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1495]
**Is your feature request related to a problem? Please describe.**
Currently, when authors want to link to another page on web.dev, they must manually enter the page title using Markdown's link syntax. For example, `[Does not use HTTPS](/is-on-https)`

If a page title changes (e.g., when a Lighthouse audit name is updated, the accompanying post title must also be updated), authors have to search the project for instances of the title and manually update them.

This will get more and more onerous as the project grows.

**Describe the solution you'd like**
Allow authors to use a page slug (based on the folder name), which the build process parses into a title (based on the YAML value) and link. For example, `[is-on-https]` would be parsed as:
```html
<a href="/is-on-https">Does not use HTTPS</a>
```

**Comment by mfriesenhahn** [comment]
Here's a use case: various Lighthouse audit titles have changed, so I'm having to manually search the project for their paths to make sure the link text is updated.

Also, a complication: how to handle anchor links?

**Comment by robdodson** [comment]
Maybe related to this? https://github.com/11ty/eleventy/issues/544
