### ISSUE TITLE
Support for code font in titles

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1500]
**Is your feature request related to a problem? Please describe.**
Many post titles, especially those of Lighthouse audit posts, include code. The GDDSG [specifies that code be presented in code font](https://developers.google.com/style/code-in-text), which web.dev does everywhere else except for titles.

**Describe the solution you'd like**
Support for backticks to indicate code font in titles

**Describe alternatives you've considered**
`<code>` tags would be less than ideal since authors will have to remember that titles work differently than the rest of the page.

**Comment by mihajlija** [comment]
Slightly related to this, there's a bug with formatting codelab title which includes "`<link>`". Bug filed #1501

**Comment by mfriesenhahn** [comment]
> Slightly related to this, there's a bug with formatting codelab title which includes "`<link>`". Bug filed #1501

Actually, I think that's more related to #1488.
