### ISSUE TITLE
Prefetch codelab title is not displayed correctly in the codelab card

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/web.dev#1501]
**Describe the bug**
Codelab title which includes "`<link>`" is not displayed correctly in the codelab card. The word "`<link>`" is missing.  

**To Reproduce**
1. Go to https://web.dev/link-prefetch/
2. Scroll down to the codelab card at the end of the post.
3. See the codelab title is "Two ways to prefetch: tags and HTTP headers"

**Expected behavior**
Title should be ["Two ways to prefetch: `<link>` tags and HTTP header"](https://web.dev/codelab-two-ways-to-prefetch/])

**Screenshots**
![Screenshot (13)](https://user-images.githubusercontent.com/17127567/64849380-90964280-d613-11e9-9922-097ddeb56a48.png)

cc @demianrenzulli @robdodson

**Comment by demianrenzulli** [comment]
Good catch! Thanks @mihajlija.
Will push a fix today.

**Comment by demianrenzulli** [comment]
Tried the following:
- Using the HTML element directly (as it is now): hides the text in the codelab link and shows the text, without formatting in the codelab title.
- Using `<link>`: hides the text inside the apostrophes in the codelab link and shows the text with apostrophes (without styling) in the codelab page.
- Using the html code: hides the text in the codelab link and shows the HTML code around the text in the the codelab title.

The only solution at this point seems to write something like: "Two ways to prefetch: link tags and HTTP headers".

**Comment by mfriesenhahn** [comment]
I believe this is related to #1488.
