### ISSUE TITLE
Can't subscribe on blog, error 403 Forbidden

### ISSUE THREAD

**Issue by shdq** [GoogleChrome/web.dev#1503]
Hello.

Subscribe link redirects me to https://services.google.com/fb/forms/web-dev-subscribe/ and gives a 403 error.

**Comment by robdodson** [comment]
Hi @shdq,

Unfortunately there some tricky legal restrictions around which countries we can provide the newsletter in. I know Russia is one of those countries. I've just followed up with the team to ask if there's anything I can do to unlock it. I'll keep you posted.

**Comment by shdq** [comment]
Thank you, Rob

**Comment by wellington1993** [comment]
@robdodson https://services.google.com/fb/forms/web-dev-subscribe/ 
Not working at Brazil...

**Comment by robdodson** [comment]
@wellington1993 It looks like there are a number of folks who have previously signed up from Brazil. Can you tell me what kind of error you're seeing?

**Comment by wellington1993** [comment]
403. But working now. :+1:

**Comment by robdodson** [comment]
Going to close, unfortunately it's a limitation of the service we use to collect email addresses :(
