### ISSUE TITLE
Improve formatting of definition lists.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1535]
As per [this PR](https://github.com/GoogleChrome/web.dev/pull/1497/files#r325436722) `<dl>` structures don't render very nicely. The alternative is to use headings as requested in the PR. That's not semantic.

**Comment by jpmedley** [comment]
You can ask him if you want. I wouldn't overthink this. Most definition lists just bold the term and indent the definition. Regardless of what you do, just keep it simple.

**Comment by PratyushSawan** [comment]
@robdodson and @jpmedley can you please give me a brief detail about what i have to do in this issue. I want to contribute on this.

**Comment by jpmedley** [comment]
As I said on the 29th, most definition lists just bold the term and indent the definition. Regardless of what you do, just keep it simple. Text size would be the same as body text. This is just a recommendation because the design is Rob's call.

**Comment by robdodson** [comment]
yeah i think something like this could work:
![image](https://user-images.githubusercontent.com/1066253/99308669-27105600-280d-11eb-8101-356d63ce33f9.png)

For what it's worth, i'm working on a lot of typography for a new site which I plan to bring back to web.dev at the start of 2021

**Comment by jpmedley** [comment]
It looks good. I would not use all upper case for the terms. Upper case slows down reading. More importantly, if we don't already have a term where letter case is important, we will.
