### ISSUE TITLE
content: Fixing layout instability blog post

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/web.dev#1540]
**Author**: @rviscomi
**Reviewer**: @kaycebasques

**Target publish date:** 2019-09-19

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

- [x] 1. I've done my [proposal](https://docs.google.com/document/d/1aadKmzxqoKkTO-3pRfnx5UDV5vNenYz58I8fVaUZr54/edit?usp=sharing)
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by robdodson** [comment]
@kaycebasques Rick previously published this post on dev.to and was wondering about mirroring it over to web.dev. Do you want to assign someone for a quick review?

**Comment by kaycebasques** [comment]
Bah, sorry, just seeing this now. I'll review today.

**Comment by kaycebasques** [comment]
LGTM. Great narrative arc, @rviscomi. Please approve or reject my suggestions and then move directly to the PR phase. No need for another review on the draft.

**Comment by kaycebasques** [comment]
A couple small suggestions in the PR for Rick to address, and then we need Rob's input on the hero image.

**Comment by robdodson** [comment]
This post is now live @ https://web.dev/fixing-layout-instability/

**Comment by rviscomi** [comment]
Thanks! I've updated the [original post](https://dev.to/chromiumdev/fixing-layout-instability-176c)'s canonical URL to point here.
