### ISSUE TITLE
content: Using ImageEngine to optimize images

### ISSUE THREAD

**Issue by jonarnes** [GoogleChrome/web.dev#1542]
**Author**: @jonarnes
**Reviewer**: [Leave blank. web.dev team will assign a reviewer.]

**Target publish date:** 2019-01-10
- [ ] Check this box if this is a hard deadline.

- [x] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal https://docs.google.com/document/d/1Gxgqb6oKDMYYbryAAXBj76_UKbUmABgQt7mCsUOBxco/edit?usp=sharing
- [ ] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by khempenius** [comment]
Adding this to the post-CDS sprint.

**Comment by khempenius** [comment]
Hi @jonarnes, Proposal-wise this looks good to me. As I mentioned previously, for web.dev code labs that use third party services, we require that users be able to sign up synchronously (i.e. they don't need to request an account) and for free. We do this to make it easy for developers to try out new technologies. It's up to you as to whether ImageEngine would want to support this type of signup flow, but it would be requirement for adding an ImageEngine code lab on web.dev.

**Comment by jonarnes** [comment]
Thank you for the feedback @khempenius. Not sure I understand the "free" part as only one of the other listed image CNDs seem to have a free tier. We ca discuss offline though. Meanwhile, we'll do our best to adapt and submit a new proposal soon.

**Comment by khempenius** [comment]
Replying here in case someone comes across this thread in the future and has questions about this:

It doesn't need to be a free tier per se, but a user should be able to signup and try out the service for free. So for example, these are fee structures corresponding to the two image CDN code labs currently on web.dev: a) free-tier b) pay-as-you-go with a $10 credit on signup, good for up to 3 months. The latter is okay because the user would not need to pay anything upfront and the $10 credit /3 month-window provides the user with ample opportunity to try the service out for free.

**Comment by jonarnes** [comment]
@khempenius @kaycebasques FYI I've updated the doc including visuals. We've changed the signup process to accommodate your requirements.

**Comment by kaycebasques** [comment]
I think our plans around image CDN guidance have changed. @khempenius can follow-up if needed.
