### ISSUE TITLE
content:  Identifying ad-related requests

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/web.dev#1545]
**Author**: @thebengeu
**Reviewer**: @mihajlija 

**Target publish date:** <2019-10-xx>
- [ ] Check this box if this is a hard deadline.

- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [x] 1. I've done my proposal https://docs.google.com/document/d/1wgw4-52vKvgj0FKel14E0eNcI0F2AzBXlcxT6J7hXK0/edit?ts=5d80fc5f
- [x] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@mihajlija - please provide an update on status of the issue. This was due on Nov 6. Should this be added to the milestone ending on Dec 16? Thx.

**Comment by mihajlija** [comment]
@carolrivero The post is not on track to get done by Dec 16. Paging @bengeu and @gernberg for an estimate for the codelab.
