### ISSUE TITLE
Enable markdown lint rule to force lines to 80 or 100 characters.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1559]
**Is your feature request related to a problem? Please describe.**
When authoring markdown, if you rely on editors which soft wrap lines at 80 or 100 characters, then the actual text will be one long string. This makes diffing text changes in GitHub pull requests difficult to follow.

**Describe the solution you'd like**
Enable the remark max line length rule and set it to either 80 or 100 characters (whichever the team prefers).

**Additional context**
We should add a note, possibly in the handbook, explaining how this rule works (and the difference between soft line wrapping and inserting newline characters). We could also link to [Rewrap](https://marketplace.visualstudio.com/items?itemName=stkb.rewrap) which is a VS Code plugin for hard wrapping lines.

**Comment by IvanBila** [comment]
I tried to enforce the 80 characters(`['lint-maximum-line-length', 80]`) per line rule and I get the following warnings:

![Screenshot from 2020-01-11 00-09-35](https://user-images.githubusercontent.com/13482373/72189884-b5a29280-3406-11ea-8f42-131fa0fdba7c.png)

I think that adding this rule would require to update all existing articles with lines exceeding 200 characters, I checked if remark has an option like `--fix` in eslint but it seems like it doesn't exist but they [do have](https://github.com/remarkjs/remark-lint#using-remark-to-fix-your-markdown) an example, another thing that could be used is prettier but in my tests it didn't fix the line width.

**Comment by robdodson** [comment]
@kaycebasques @jpmedley @mfriesenhahn your thoughts?

**Comment by mfriesenhahn** [comment]
IIRC, we considered enforcing this but decided against it? FWIW, my preference is to ask folks to break lines on semantic units (typically clauses) and not enforce a character limit, but I don't have strong feelings, TBH. I see pros and cons to both approaches, so defer to others!

**Comment by jpmedley** [comment]
Reviews are a pain if we don't break characters. Text editors have a way to do this automatically. WebFundamentals has a code that can bypass some of the test stack. If we implement something similar we can create a work-around that prevents asking people who submit typo fixes from updating complete files.

**Comment by robdodson** [comment]
> WebFundamentals has a code that can bypass some of the test stack. If we implement something similar we can create a work-around that prevents asking people who submit typo fixes from updating complete files.

@jpmedley can you explain this a bit more, i'm not sure I follow?

**Comment by jpmedley** [comment]
Pete has codes that he can stick somewhere in a PR that causes portions of the test sequence to be bypassed. I use them rarely enough that I always have to ask him to tell me what they are and where to put them. (He's out until Friday.)

The one I use most often is for exactly the situation described here. I want to ignore the line length requirement because I'm only adding a missing comma or something. I put this code in and I get no linter warnings about line length and the tests show as passing so that I can merge the PR. If the change to a file is bigger then breaking lines of an existing file might be required. Gradually, files that violate the rule decline.

The reason I don't use the code often enough to know it off the top of my head.

**Comment by robdodson** [comment]
ah ok. Are the codes you're referring to a comment that you add to the files in the PR? For example:

```
<!--lint disable maximum-line-length-->
```

**Comment by jpmedley** [comment]
They've become so rare, I just don't remember.

**Comment by jpmedley** [comment]
I think it was something done to the conversation thread, not to the source files. @petele, can you help us out?
