### ISSUE TITLE
content: Performance as a default with Next.js

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1561]
**Author**: @housseindjirdeh 
**Reviewer**: @kaycebasques

**Target publish date:** 2019-10-16

- [x] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my [proposal](https://docs.google.com/document/d/1qBRGMY1XBwjUPnXSt72sBzT8TVdr7BJMfrTf7nGFTTY/edit)
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1658 
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by kaycebasques** [comment]
I just reviewed the draft. Next step is for Houssein to address my feedback.

**Comment by kaycebasques** [comment]
Houssein is planning on updating this draft tomorrow and estimates for it to be complete by 10/9 or 10/10.

**Comment by kaycebasques** [comment]
I submitted the PR. Rob and Houssein need to review the PR.

**Comment by kaycebasques** [comment]
@housseindjirdeh has LGTM'd the PR.

I need to Rob to provide feedback on:

- [ ] How to increase the height of the embedded Glitch
- [ ] Provide a second pair of eyes of the new organization of web.dev/react
- [ ] Provide a code maestro review if he wants

**Comment by robdodson** [comment]
Looks good to me. Left a few small notes in the PR. Assigning back to Kayce
