### ISSUE TITLE
content: Route prefetching with Next.js

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1562]
**Author**: @mihajlija  
**Reviewer**: @mfriesenhahn

**Target publish date:** 2019-10-16

- [x] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal <add a link to your proposal doc>
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc https://docs.google.com/document/d/1Vt6ZDofArQRGOA9PAzQu0wCQQSm96WQBzqzHYojFlmk/edit?usp=sharing
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1696 
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by kaycebasques** [comment]
Hi @mihajlija I'm pretty sure you said you'll write this one, so I assigned the issue to you

**Comment by kaycebasques** [comment]
@mihajlija is doing research on when prefetch is appropriate and waiting on @housseindjirdeh to answer some questions.

**Comment by mihajlija** [comment]
Got feedback from Next.js team on some issues with prefetching and finally have a working production app on Glitch. I've added a rough draft, I'll update it tomorrow with the new info and the polished example app. Expecting to be ready for review tomorrow.

**Comment by mihajlija** [comment]
I need to retake some screenshots and work on CSS, but the post is ready for review.

**Comment by mfriesenhahn** [comment]
Did a very quick copy edit and commented on a couple instructional details but didn't dive deep so as not to hold things up.

**Comment by mihajlija** [comment]
I'll submit a PR first thing tomorrow 👍

**Comment by mfriesenhahn** [comment]
Hey, @mihajlija, I'll be taking the code review for this one.
