### ISSUE TITLE
content: Precache assets with next-offline

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1565]
**Author**: @housseindjirdeh 
**Reviewer**: @kaycebasques

**Target publish date:** 2019-11-06

- [x] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal <add a link to your proposal doc>
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@housseindjirdeh - draft for cds wave 2 is due today (Oct 21). please add a link to your doc so we can assign a reviewer. Thanks.

**Comment by carolrivero** [comment]
@housseindjirdeh  please provide an update on draft. Wave 3 drafts are due today. Thanks.

**Comment by kaycebasques** [comment]
We can re-open if/when Houssein has concrete plans to implement.
