### ISSUE TITLE
content: Intro to metrics

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1568]
**Author**: @philipwalton 
**Reviewer**: @kaycebasques 

**Target publish date:** 2019-11-06

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [x] 1. I've done my proposal
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a [draft](https://docs.google.com/document/d/1mQzjSTNKs6_yoOzVfaPZma7Uh6KzuOnb-OmCKIj7R5w/edit) to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by philipwalton** [comment]
Draft docs: https://docs.google.com/document/d/1mQzjSTNKs6_yoOzVfaPZma7Uh6KzuOnb-OmCKIj7R5w/edit#

**Comment by kaycebasques** [comment]
@philipwalton is this ready for review? Or is it going to change as you draft out the other docs?

**Comment by kaycebasques** [comment]
Looking good. I don't see any major issues that need to be addressed. So next step is to let Phil continue drafting the collection and we can revisit this once we see how all the content fits together. It'll probably still be good, but it's common for intros to change after the whole collection gets drafted out.
