### ISSUE TITLE
content: First Contentful Paint

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1569]
**Author**: @philipwalton 
**Reviewer**: @kaycebasques 

**Target publish date:** 2019-11-06

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [x] 1. I've done my proposal <add a link to your proposal doc>
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a [draft](https://docs.google.com/document/d/1dPqXmTI9mR9Zn2eM4a1ySJmxxP7YLmRiR6i6rSySEoM/edit#) to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@philipwalton 
Please provide your draft for this post. We are starting wave 2 now and the draft is due on Oct 21 for Wave 2 posts. Thanks.

**Comment by philipwalton** [comment]
Draft doc: https://docs.google.com/document/d/1dPqXmTI9mR9Zn2eM4a1ySJmxxP7YLmRiR6i6rSySEoM/edit#

**Comment by philipwalton** [comment]
Draft doc: https://docs.google.com/document/d/1dPqXmTI9mR9Zn2eM4a1ySJmxxP7YLmRiR6i6rSySEoM/edit#

**Comment by kaycebasques** [comment]
@philipwalton is this ready for review?

**Comment by philipwalton** [comment]
This guide is now ready for review.

**Comment by kaycebasques** [comment]
Looking good! General structure and content looks great. I didn't do an in-depth copyedit.

**Comment by kaycebasques** [comment]
I think next step here is to let Phil keep writing content and then once we're happy with the general collection I'll do the detailed copyedits.
