### ISSUE TITLE
content: Largest Contentful Paint

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1570]
**Author**: @philipwalton 
**Reviewer**: @kaycebasques 

**Target publish date:** 2019-11-06

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [x] 1. I've done my proposal <add a link to your proposal doc>
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a [draft](https://web.dev/largest-contentful-paint/) to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@philipwalton draft for wave 2 posts is due on Oct 21. Please add a link to your doc. Thanks.

**Comment by philipwalton** [comment]
The draft for this already exists at: https://web.dev/largest-contentful-paint/

**Comment by kaycebasques** [comment]
Next step: @philipwalton if you expect we'll need to make a lot of edits to this doc to get it aligned with the rest of the collection, then we should move this to a Google Doc. If you think the changes are minimal then we can make the updates as a PR.
