### ISSUE TITLE
content: Time To Interactive

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1571]
**Author**: @philipwalton 
**Reviewer**: @kaycebasques 

**Target publish date:** 2019-10-28

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [x] 1. I've done my proposal <add a link to your proposal doc>
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a [draft](https://docs.google.com/document/d/17fzYlWJfVted19kb_QkqqgmWTv0m_G9iYPyQ_2LSLxQ/edit#) to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by philipwalton** [comment]
Draft doc: https://docs.google.com/document/d/17fzYlWJfVted19kb_QkqqgmWTv0m_G9iYPyQ_2LSLxQ/edit#

**Comment by kaycebasques** [comment]
Next step: @philipwalton is this draft ready for review or is it still changing?

**Comment by philipwalton** [comment]
This draft is now ready for review.
