### ISSUE TITLE
content: Total Blocking Time

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1572]
**Author**: @philipwalton 
**Reviewer**: @kaycebasques 

**Target publish date:** 2019-11-06

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [x] 1. I've done my proposal <add a link to your proposal doc>
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a [draft](https://docs.google.com/document/d/17Yri2mw-WrAABekfJj2yv_vXutndFGi9UgGf1NUu1PA/edit#) to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by philipwalton** [comment]
Draft doc: https://docs.google.com/document/d/17Yri2mw-WrAABekfJj2yv_vXutndFGi9UgGf1NUu1PA/edit#

**Comment by kaycebasques** [comment]
Next step: @philipwalton to finish drafting the content and then re-assign to me for review

**Comment by philipwalton** [comment]
I've added some more content to the draft if you want to re-review. Though it's also fine if you want to wait until all of these are done before doing an in-depth copy edit.
