### ISSUE TITLE
content: First Input Delay

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1573]
**Author**: @philipwalton 
**Reviewer**: @kaycebasques 

**Target publish date:** 2019-10-28

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal <add a link to your proposal doc>
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
  * [Related article](https://developers.google.com/web/updates/2018/05/first-input-delay)
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
Draft is due Oct 21 for CDS wave 2 posts.

**Comment by philipwalton** [comment]
The draft for this is what's currently at: https://developers.google.com/web/updates/2018/05/first-input-delay

**Comment by kaycebasques** [comment]
Next step: @philipwalton please put [the /web article](https://developers.google.com/web/updates/2018/05/first-input-delay) into a Google Doc. We might need to edit it to make it consistent with web.dev style and the rest of the metrics docs.
