### ISSUE TITLE
content: Cumulative Layout Shift

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1574]
**Author**: @philipwalton 
**Reviewer**: @kaycebasques 

**Target publish date:** 2019-10-28

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal <add a link to your proposal doc>
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
Draft is due on Oct 21 for all wave 2 posts. Please add link to your draft here @philipwalton

**Comment by philipwalton** [comment]
The draft for this is what's currently at: https://web.dev/layout-instability-api

**Comment by kaycebasques** [comment]
Next step: @philipwalton to submit a PR to update the old doc so that it's aligned with the rest of the collection

**Comment by carolrivero** [comment]
@philipwalton friendly nudge - can you tell us if we're going to update that old article, or create a new doc based on that article?

**Comment by philipwalton** [comment]
I'm planning to update the article (and rename it to "cumulative-layout-shift" to reflect the metric name), but I plan to do this last so that new docs are prioritized.
