### ISSUE TITLE
content migration: getInstalledRelatedApps

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1578]
**Author**: @petele 
**Reviewer**: @jpmedley 

**Target publish date:** 2019-10-16
- [x] Check this box if this is a hard deadline.

- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

migrate https://developers.google.com/web/updates/2018/12/get-installed-related-apps to web.dev as part of the fugu migration

**Comment by mfriesenhahn** [comment]
Finished the copy edit and passed back to Joe.
