### ISSUE TITLE
content: Codelab: Get started with the Notifications API

### ISSUE THREAD

**Issue by ghost** [GoogleChrome/web.dev#1588]
**Author**: @katejeffreys 
**Reviewer**: @mfriesenhahn

**Target publish date:** CDS
- [ ] Check this box if this is a hard deadline.

- [x] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal https://docs.google.com/document/d/1scYRHxr1Fpjf4xBq2rRqKLApvgYjN9tHmMP44dBOxH4/edit
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1678
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by katejeffreys** [comment]
https://deploy-preview-1590--web-dev-staging.netlify.com

**Comment by kaycebasques** [comment]
Next step: @katejeffreys to address @mfriesenhahn's feedback

**Comment by carolrivero** [comment]
reprioritized to help w/ bandwidth for cds related posts.

**Comment by katejeffreys** [comment]
Review feedback incorporated. https://github.com/GoogleChrome/web.dev/pull/1732 will have a preview once build completes

**Comment by carolrivero** [comment]
Any updates on status of merge/push. Can we close this one out? @mfriesenhahn

**Comment by mfriesenhahn** [comment]
GH isn't showing that this has been merged, and I'm assuming it shouldn't be published until the rest of the collection is ready.
