### ISSUE TITLE
content: image CDN comparison proposal

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1592]
**Author**: @khempenius 
**Reviewer**: @kaycebasques 

**Target publish date:** 2019-12-01

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

@khempenius please use this doc where I've added notes from our discussion: https://docs.google.com/document/d/1B0p4iAkd4lULQqZHUn6_LpBnlNz6dN1wDpV1i-rXsHU/edit#

When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal <add a link to your proposal doc>
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@kaycebasques which sprint should this be added to?

**Comment by kaycebasques** [comment]
Pretty sure our plans around image CDN guidance have changed and this is no longer relevant.
