### ISSUE TITLE
Next article widget doesn't support Markdown

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1594]
**Describe the bug**
Post titles can now include Markdown (for example, to allow for code font). However, that Markdown isn't being parsed in the **Next article** component.

See screenshot below for an example.

**Expected behavior**
Markdown in post titles should be parsed.

**Screenshots**
![image](https://user-images.githubusercontent.com/14199217/66013312-98613e00-e47f-11e9-994c-11e495118314.png)

**Comment by mfriesenhahn** [comment]
Particularly important for posts with tags in their titles:
![image](https://user-images.githubusercontent.com/14199217/66356656-92a4a600-e920-11e9-89de-b0b1104cc841.png)

**Comment by robdodson** [comment]
oof ok, yeah that seems bad. I'll take a look.
