### ISSUE TITLE
SW flakiness

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1599]
**Describe the bug**
I think the work done in #1583 is causing issue with the service worker. If I comment out the content handler and remove the lines that set `index: false` on the static routes then things work again. Otherwise I get 404s for content pages. My fault for not reviewing better.

**To Reproduce**
1. Check out the current v2 branch.
2. Try to visit a page other than the homagepage. For example `/stale-while-revalidate/`
3. Get 404

**Expected behavior**
The page loads.

**Comment by samthor** [comment]
Is this versus DevSite's SW? Since we... didn't have our own until yesterday.

**Comment by robdodson** [comment]
Nah we can close this. I was hitting the index: false thing and thought we had already landed your prior SW stuff.
