### ISSUE TITLE
content: Add rel=noopener to external links in existing content

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1612]
Links to external sites should use the `rel=noopener` attribute. We need to conduct a pass of existing content to convert all external links from the Markdown shorthand to `<a href="somesite.com" rel="noopener">Link text</a>`.

**Comment by robdodson** [comment]
I think #1621 may have addressed this. I'm not sure if our markdown parser supports external links using markdown syntax so the only ones we have might be the ones captured in that PR.

**Comment by mfriesenhahn** [comment]
Actually, for this I meant doing a sweep of existing content and converting MD-syntax links pointing to external sites over to HTML and rel=noopener. We have a bunch of those, obvs. It'd be a project.

**Comment by robdodson** [comment]
ah got it

**Comment by kaycebasques** [comment]
This is only an issue when the link uses `target="_blank"` so there weren't that many links that needed updating.
