### ISSUE TITLE
content: Notification Triggers

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1615]
**Author**: @tomayac 
**Reviewer**: @jpmedley 

**Target publish date:** 2019-10-30
- [X] Check this box if this is a hard deadline.
- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [x] 1. I've done my [proposal](https://docs.google.com/document/d/1o77exhyDrJck_1XQySbgh-lX_dg9RCSDd7LZ7PTD5Io/edit)
- [X] 2. Proposal approved
- [X] 3. I've added a draft to my proposal doc
- [X] 4. Draft approved
- [x] 5. I've submitted a pull request #1744
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by petele** [comment]
This has slipped to Chrome 79 (from 78), will update and move into the the appropriate wave/sprint when we're closer to knowing it's landing date.

**Comment by kaycebasques** [comment]
Next step: @tomayac to address @jpmedley's feedback

**Comment by jpmedley** [comment]
This is merged, but is hidden with a draft tag. We need this ticket open because:
* The article is blocked because the feature it describes is unreleased.
* We need a reminder to sanity check the article before releasing it.

**Comment by jpmedley** [comment]
This will start an origin trial in Chrome 80. We need to make sure the OT information is up to date.

**Comment by carolrivero** [comment]
Tentative Date is Dec 16. Otherwise it will be in Feb. @jpmedley will confirm here.

**Comment by carolrivero** [comment]
@jpmedley confirm if this can get published by next week.
