### ISSUE TITLE
content migration: Web Share API

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1616]
**Author**: @petele
**Reviewer**: @jpmedley 

**Target publish date:** 2019-10-16
- [X] Check this box if this is a hard deadline.
- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [X] 1. I've done my proposal (merged version of https://developers.google.com/web/updates/2019/05/web-share-files and https://developers.google.com/web/updates/2016/09/navigator-share)
- [X] 2. Proposal approved
- [X] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved
- [x] 5. I've submitted a pull request #1829
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
Moving this to wave 2 since publish date for wave 1 has passed

**Comment by kaycebasques** [comment]
Joe is adding new content of this topic

**Comment by kaycebasques** [comment]
@jpmedley have you finished the new content? Is the next step to submit a PR to migrate the content to web.dev?

**Comment by jpmedley** [comment]
This and web share target will be delayed a few days. Pete needs to review and he's attending google.dev in Sunnyvale. I don't have an ETA.

**Comment by kaycebasques** [comment]
PR will probably land today or Monday.

**Comment by jpmedley** [comment]
I don't quite have a PR. The content is in markdown and in a development branch. I have a few things I need to work out. Then I'll open a PR.

**Comment by kaycebasques** [comment]
@mfriesenhahn this is ready for your review. This is also a @jpmedley rewrite of developers.google.com/web content.

**Comment by jpmedley** [comment]
#1828 and #1829 (share and share target) are linked to each other. They MUST BE part of the same deployment.
