### ISSUE TITLE
Clarify when use of "we" is OK

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1619]
* If someone uses "we" conversationally, as in "now we're going to do X", I can be lenient with that
* If someone uses "we suggest doing X" where "we" actually means a specific group, like the Chrome team, we should replace "we" with "the Chrome team"

**Comment by robdodson** [comment]
> If someone uses "we" conversationally, as in "now we're going to do X", I can be lenient with that

I thought we tried to avoid this because it comes across as a bit professorial. Isn't the usual writing advice to make it "you do X" or an implicit you, e.g. "do X" ?

**Comment by kaycebasques** [comment]
Here's the GDDSG basis for avoiding "we": https://developers.google.com/style/person

In practice we've seen a lot of web.dev contributors gravitate towards using "we" in the conversational sense and it often feels like an unnecessary nitpick to have them change it.

**Comment by kaycebasques** [comment]
Rationale for avoiding "we" when we actually mean "Chrome": https://github.com/GoogleChrome/web.dev/pull/1614#discussion_r333143069
