### ISSUE TITLE
Create a FUGU feedback component

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1625]
All of the Fugu feedback sections are essentially identical, it'd be great to have a widget we could drop in and use.

Ideally there would be three variables we would be able to set:
* API-NAME (eg Contacts Picker API)
* COMPONENT (eg Blink>Storage)
* TWITTER-TAG (eg 'contactpicker')

Template is below.

```
## Feedback {: #feedback }

We want to hear about your experiences with the {{API-NAME}}.

### Tell us about the API design {: .hide-from-toc }

Is there something about the API that doesn't work as expected? Or
are there missing methods or properties that you need to implement your idea?

* File a spec issue on the [{{API-NAME}} GitHub repo][issues],
  or add your thoughts to an existing issue.

### Problem with the implementation? {: .hide-from-toc }

Did you find a bug with Chrome's implementation? Or is the implementation
different from the spec?

* File a bug at <https://new.crbug.com>. Be sure to include as much
  detail as you can, provide simple instructions for reproducing the bug, and
  set *Components* to `{{COMPONENT}}`. [Glitch](https://glitch.com) works great
  for sharing quick and easy repros.

### Planning to use the API? {: .hide-from-toc }

Are you planning to use the {{API-NAME}}? Your public support helps us
prioritize features, and shows other browser vendors how critical it is to
support them.

* Share how you plan to use it on the [WICG Discourse thread][wicg-discourse]
* Send a Tweet to [@ChromiumDev](https://twitter.com/chromiumdev) with 
  `#{{TWITTER-TAG}}` and let us know where and how you're using it.
```

**Comment by robdodson** [comment]
I'm not sure I'm fully on board with this idea but I'm happy to discuss.

My main concern is that this feels like functionality that might fit better on chromestatus.com. We're beginning to have conversations around what the next iteration of chromestatus would look like, and creating a place to give feedback is high on the list.

Another concern is around creating components that have to live indefinitely in our source but may not be used by other collections. Could this instead be a link that has query params to pre-populate a form hosted elsewhere?

**Comment by petele** [comment]
I'm find duplicating that block in all of our content if you are.
