### ISSUE TITLE
content: Lighthouse doc for Largest Contentful Paint

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1628]
**Author**: @kaycebasques 
**Reviewer**: @mfriesenhahn  

Note that this is different than #1570.

**Target publish date:** 2019-10-17 (Chrome 79 Branch Point)

- [x] Check this box if this is a hard deadline.
- [x] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal <add a link to your proposal doc>
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1639 
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
Please confirm who the reviewer is for this one. Thx.

**Comment by kaycebasques** [comment]
Status: Lighthouse team provided technical review. The metric hasn't been implemented in the Lighthouse report yet so there's still some technical content that needs to be added to the doc.

**Comment by kaycebasques** [comment]
Irish provided some data so I might be able to finish this content today.

**Comment by kaycebasques** [comment]
The data that Irish provided doesn't resolve the questions so this is still blocked on technical details.

**Comment by kaycebasques** [comment]
This seems stalled on technical stuff so I'm moving to wave 3

**Comment by kaycebasques** [comment]
The audit still hasn't landed in Lighthouse so I think we can just punt this to post CDS.

**Comment by kaycebasques** [comment]
Lighthouse audit has landed: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/metrics/largest-contentful-paint.js

**Comment by carolrivero** [comment]
@kaycebasques to finish drafting.
