### ISSUE TITLE
content: New a11y audit docs for Lighthouse 6.0

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1629]
**Author**: @mfriesenhahn 
**Reviewer**: @kaycebasques 

[List of docs](https://github.com/GoogleChrome/lighthouse/issues/7127#issue-405436641)

**Target publish date:** 2019-10-17 (Chrome 79 Branch Point)

- [x] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal <add a link to your proposal doc>
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1648
- [x] 6. Pull request approved — _reviewer checks this_

**Comment by mfriesenhahn** [comment]
@kaycebasques, see the PR for notes about status.

**Comment by mfriesenhahn** [comment]
Oh, and @robdodson, since you're the SME for this, it'd be ideal if you could review also.

**Comment by mfriesenhahn** [comment]
@kaycebasques, as noted in the PR, all outstanding questions have been resolved with the LH team. All new audits ready for your review.

**Comment by kaycebasques** [comment]
Rob and Michael are reviewing the PR. Rob is doing in-depth reviews and doesn't think that it's necessary to have a writer review it as well. So once Rob thinks the PR is good, we can merge.
