### ISSUE TITLE
content: Learn:  Use notifications to enage and re-engage users

### ISSUE THREAD

**Issue by ghost** [GoogleChrome/web.dev#1657]
**Author**: @katejeffreys 
**Reviewer**: @mfriesenhahn 

**Target publish date:** Wave 1
- [ ] Check this box if this is a hard deadline.

- [x] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [x] 1. I've done my proposal https://docs.google.com/document/d/1f4jNYMfYoSCwYs0Zk4rkjIWp-iX548lrW_qFosZl4DE/edit
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1730 
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by mfriesenhahn** [comment]
Finished review. Back to @katejeffreys!

**Comment by carolrivero** [comment]
reprioritized to help w/ bandwidth for cds related posts.

**Comment by katejeffreys** [comment]
Review feedback incorporated. https://github.com/GoogleChrome/web.dev/pull/1732 will have a preview once build completes

**Comment by mfriesenhahn** [comment]
Ready to merge!

**Comment by carolrivero** [comment]
@kaycebasques which sprint should this be added to?
