### ISSUE TITLE
Content process: specify scope of desired writer review

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1663]
**Is your feature request related to a problem? Please describe.**
The desired scope of Tech Writer reviews varies from post to post. For some posts, a review using the full content checklist is desired; for others, it's just a copy edit. Asking what review scope is desired for each post can be inefficient and doesn't leave a record unless TWs proactively indicate scope in the PR comments.

**Describe the solution you'd like**
Probably a default (likely a full content checklist review) with a way to indicate when you want something else. GH issues seem to be our source of truth for process info, so it could go there. Though those are already getting dense.

**Comment by kaycebasques** [comment]
Notes from writer's meeting: https://docs.google.com/document/d/12T4mcM8cz6ZBULwTycISwN6pr_W5AKwuCE9C4N1A8PI/edit#heading=h.pdoizi3k20zb

**Comment by kaycebasques** [comment]
This article defines 3 types of review:

* `Proofreading`: correction of typing mistakes and mispellings
* `Copyediting`: correction of minor problems, such as awkward sentences, grammatical mistakes, adherence to a style guide
* `Comprehensive editing`: suggestions about considering readers, content, organization, page design, style, and use of illustrations

EATON, ANGELA, et al. “Examining Editing in the Workplace from the Author's Point of View: Results of an Online Survey.” Technical Communication, vol. 55, no. 2, 2008, pp. 111–139. JSTOR, www.jstor.org/stable/43092427.

**Comment by kaycebasques** [comment]
This one adds the category of `usability editing`, in which the reviewer responds to the content like a typical user might. Also has interesting analogies between types of software testing and editing (unit testing = copyediting)

CORBIN, MICHELLE, et al. “Technical Editing as Quality Assurance: Adding Value to Content.” Technical Communication, vol. 49, no. 3, 2002, pp. 286–300. JSTOR, www.jstor.org/stable/43095561.
