### ISSUE TITLE
Blog: 5 ways AirSHIFT made their React app responsive

### ISSUE THREAD

**Issue by uskay** [GoogleChrome/web.dev#1669]
**Author**: @uskay
**Reviewer**: @kaycebasques 

**A one to two sentence description of your post**
This case study explains how the AirSHIFT team optimized the responsiveness of their desktop React SPA and satisfied their users.

**What are you planning to teach folks in this post?**
A real world case study of React SPA performance optimization.

**Target publish date:** TBD
- [ ] Check this box if this is a hard deadline.
- [x] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**
- [x] 1. I've done my [proposal](https://docs.google.com/document/d/15BIuSdtnU90ra4VA6EoDXUBARtQ9iWyvvAjk2BsfCrI/edit?usp=sharing)
- [x] 2. Proposal approved
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved [Partner approved / @addyosmani approved]
- [x] 5. I've submitted a pull request #1796 
- [ ] 6. Pull request approved

cc/ @kaycebasques @robdodson

**Comment by uskay** [comment]
@kaycebasques Partner PR review done. Could you kindly check the Pull Request?

**Comment by kaycebasques** [comment]
Next step is for @uskay to: 

* re-submit the PR as a branch on this repo (googlechrome/web.dev), not his fork
* minimize the images

**Comment by kaycebasques** [comment]
Thank you @uskay for the in-depth content and it was my pleasure to work with you again. I just merged the PR.
