### ISSUE TITLE
Override markdown-it parser to add rel=noopener

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1670]
Per @mfriesenhahn's comment on #1652 
> We've been starting to use `rel=noopener` on external links 

Can we update the markdown parser to do this for us automatically please?

Instructions on how to do that are essentially at https://github.com/markdown-it/markdown-it/issues/46, and requires an easy override of the renderer rules.

**Comment by robdodson** [comment]
Would we want this on all links, or just external links? I think to override the markdown parser we'd need to check that the link contains a domain and that the domain is not web.dev.
