### ISSUE TITLE
content: Learn: Notification permission UX

### ISSUE THREAD

**Issue by carolrivero** [GoogleChrome/web.dev#1671]
**Author**: @katejeffreys 
**Reviewer**: @mfriesenhahn 

**Target publish date:** 2019-10-30

- [x] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal <add a link to your proposal doc>
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@katejeffreys - please add a link to your draft so we can assign a reviewer. Thanks.

**Comment by carolrivero** [comment]
@kaycebasques which sprint should this be added to?

**Comment by kaycebasques** [comment]
Going to close these old issues. There's some content that may get published eventually but if that happens I'll create a new issue.
