### ISSUE TITLE
Consider enforcing IDs for all sections

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1676]
When we don't specify an ID for a section, the ID gets auto-generated from the text of the section heading. For example:

```
## Changes to the default behavior without SameSite
```

Becomes: `https://web.dev/samesite-cookies-explained#changes-to-the-default-behavior-without-samesite`

If we change that section heading text, the ID changes:

```
## Changes to the default SameSite behavior
```

Would (probably) become: `https://web.dev/samesite-cookies-explained#changes-to-the-default-samesite-behavior`

Old links referencing the old ID would no longer jump to the correct section.

We have the ability to specify specific IDs:

```
## Changes to the default behavior without SameSite {: #changes }
```

It could be a good practice to enforce this for all section headings.

cc @robdodson

**Comment by kaycebasques** [comment]
Another example of this problem: https://github.com/GoogleChrome/web.dev/pull/1658#discussion_r335600100

**Comment by robdodson** [comment]
IMO this feels like it might be rather tedious for authors to have to remember to slugify every heading they use.

We currently support this syntax:
```
## Changes to the default behavior without SameSite {: #changes }
```

So another option would be if we see someone _changing_ a heading, we ask them to add the `{: #... }` annotation to use the previous heading's anchor so they don't break anything.
