### ISSUE TITLE
content: Trusted Web Activity(TWA)- OYO case study

### ISSUE THREAD

**Issue by prash-mi** [GoogleChrome/web.dev#1682]
**Author**: @AnkitJainAJ
**Reviewer**: @mfriesenhahn 

**Target publish date:**  2019-11-6
- [x] Check this box if this is a hard deadline.

- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal https://medium.com/@ankitjainaj/3dd327d7afc5
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1832
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@kaycebasques - please assign a reviewer. thx.

**Comment by carolrivero** [comment]
Updated author to: @AnkitJainAJ per request from @prash-mi

**Comment by carolrivero** [comment]
Updated launch date to Nov 6 for Wave 3 completion.

**Comment by carolrivero** [comment]
Timeline for Wave 3: Draft needs to be approved by Nov 5, Review/Approve/Merge is due on Nov 6 for a publish date of Nov 7.

**Comment by mfriesenhahn** [comment]
> Timeline for Wave 3: Draft needs to be approved by Nov 5, Review/Approve/Merge is due on Nov 6 for a publish date of Nov 7.

Is this timeline realistic given we wanted to use this as an opportunity to think through the desired format for web.dev case studies and don't yet have a draft of a version of this case study that reflects that format? If we need this done in six business days, I'd suggest we de-scope this effort to tidying up the Medium post. cc @kaycebasques and @robdodson

**Comment by mfriesenhahn** [comment]
Draft in #1832 and staged here: https://deploy-preview-1832--web-dev-staging.netlify.com/oyo-case-study/

Note that the native aspect ratio of the GIF in the Medium post was stretched out. I converted it as-is to video for now, but, @AnkitJainAJ, do you have the correct original?

**Comment by kaycebasques** [comment]
I've started reviewing.

**Comment by kaycebasques** [comment]
@mfriesenhahn the content flows well and covers all the bases. And it's a great foundational overview of TWAs that we'll probably be able to separate later. So thank you! I appreciate that you took a one-off case study and turned it into something that we'll be able to build off of later.

Take a look at this comment and LMK if we should get a technical review: https://github.com/GoogleChrome/web.dev/pull/1832#discussion_r342344778

I'm not sure I have all the context so I want to check with you first.

**Comment by mfriesenhahn** [comment]
> Take a look at this comment and LMK if we should get a technical review: [#1832 (comment)]

 +1 to technical review

**Comment by kaycebasques** [comment]
Next step is for PJ to provide links to support the statement that other browsers are supporting TWAs

**Comment by mfriesenhahn** [comment]
@kaycebasques, can you loop me into conversations about this post so I know what decisions are being made?

**Comment by kaycebasques** [comment]
There were no conversations other than me finding TWA people and giving them the background context on this post. The next step is based on this comment from PJ (https://github.com/GoogleChrome/web.dev/pull/1832#issuecomment-550027791) and my review of the aside that you proposed

**Comment by kaycebasques** [comment]
Oh, I just saw that my review was still pending and hadn't been submitted. Just submitted a comment on the proposed aside.

**Comment by kaycebasques** [comment]
This is humming along. Michael's just tying up some loose ends.

**Comment by mfriesenhahn** [comment]
@kaycebasques, the browser support statement has been updated per the thread with PJ. Can you approve and merge?

**Comment by mfriesenhahn** [comment]
We also just got an LGTM from OYO. This is good to go.
