### ISSUE TITLE
Add underlines to links in articles.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1683]
For accessibility we shouldn't be relying on color alone to convey that something is interactive. The original design for links in our content posts did not call for them to have underlines, but I think it might be good for us to add this affordance.

![image](https://user-images.githubusercontent.com/1066253/66942531-27349580-effe-11e9-8f5e-e419c98ba17c.png)

**Comment by MichaelSolati** [comment]
@robdodson if that's the case this should likely be applied to blog posts too, no?
