### ISSUE TITLE
content: Lighthouse a11y cleanup

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1687]
**Author**: @mfriesenhahn
**Reviewer**: @robdodson

TODOs for a11y audit post updates:
- Update example in `button-name`. (#1723)
- Update guidance in `color-contrast` about how to check contrast for non-HTML text. ([Conversation for reference](https://github.com/GoogleChrome/web.dev/pull/1648#discussion_r334739868).) (#1723)
- Remove broken Glitch from `custom-control-roles`. (#1723)
- Follow up with axe folks about fix for `layout-table` check. Once done, determine whether post needs updated.
- Review following sections for quality:
  - Audio and video (#1701)
  - Best practices (#1711)
  - Names and labels
  - Navigation (#1722)
  - Tables and lists
  - Manual audits (`use-landmarks` already done.)

**Comment by robdodson** [comment]
> Update example in button-name. (Proposed Glitch to be reviewed by @robdodson. Conversation for reference.)

This demo looks good to me. Is there a previous Glitch that we were linking to? If so I could replace the contents of that Glitch or we could switch to using this one.

> @robdodson to fix Glitch in custom-control-roles.

Is that this Glitch? https://github.com/GoogleChrome/web.dev/issues/1641

**Comment by mfriesenhahn** [comment]
> This demo looks good to me. Is there a previous Glitch that we were linking to? If so I could replace the contents of that Glitch or we could switch to using this one.

There's just a code sample currently. Will replace!

> > @robdodson to fix Glitch in custom-control-roles.
> 
> Is that this Glitch? #1641

Yep, that's the one! It's used in both posts. I believe you said you'd fix it in the comments on the a11y updates PR.

**Comment by mfriesenhahn** [comment]
@robdodson, looks like you deleted

**Comment by robdodson** [comment]
> @robdodson, looks like you deleted

I think the Glitch is marked as private. It uses a weird project that I'm not sure I want folks to actually use (chromevox-lite). I'll take a look and consider if we want to just remove this Glitch.

**Comment by robdodson** [comment]
I suggest we remove the Glitch from custom-controls because I don't think I'm going to get around to open sourcing it anytime soon. It requires some special thought. We should probably also remove it from the semantics doc that refers to it.
