### ISSUE TITLE
The `Source code for Current page does not respond with a 200 when offline audit` link gives a 404

### ISSUE THREAD

**Issue by talentedandrew** [GoogleChrome/web.dev#1694]
The link for `Source code for Current page does not respond with a 200 when offline audit
` gives a 404. Check [Here](https://web.dev/works-offline) and [Source code for Current page does not respond with a 200 when offline audit](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/works-offline)

**Comment by robdodson** [comment]
@mfriesenhahn are you cool taking this one?

**Comment by mfriesenhahn** [comment]
Et, voila: #1695

**Comment by talentedandrew** [comment]
@robdodson @mfriesenhahn thanks
