### ISSUE TITLE
Task: Determine how to add JS to components

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1704]
**Is your feature request related to a problem? Please describe.**
Proposed components like the vocabulary definition popup and self-assessments need JS. Need to determine how best to add it.

**Comment by robdodson** [comment]
In v2 we can do these as custom elements. Probably best to do any client-side JS in that branch. I can show you around that branch tomorrow if you'd like?

**Comment by mfriesenhahn** [comment]
Sounds good!

**Comment by robdodson** [comment]
Going to close this. We'll want to put custom elements in the `lib/` directory of v2. There are a bunch there already to copy.
