### ISSUE TITLE
Send automated reminders to link Lighthouse report UI to new web.dev docs

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1707]
**Is your feature request related to a problem? Please describe.**

1. Create a Lighthouse audit doc ([example](https://github.com/GoogleChrome/web.dev/pull/1688)
1. Merge the PR

**Describe the solution you'd like**

A GitHub bot reminds me to link the Lighthouse report UI to the doc

**Additional context**

Rob said that the bot can detect if we have new content in one of the Lighthouse audit directories... we can use that to trigger the notification rather than having to add a label

Rob should pair program this with me in order to teach an old dog (me) how to fish rather than feeding said old dog one-off fishes

**Comment by robdodson** [comment]
Removing myself from the assignee field if that's ok. I may see if one of the folks onboarding will want to work on this. I've been trying to only have stuff assigned to me if i'm planning to immediately work on it (features or docs reviews).

**Comment by kaycebasques** [comment]
This is on our roadmap but there's no need to keep it as an open issue in this repository.
