### ISSUE TITLE
Replace navaid

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/web.dev#1715]
We have a bunch of issues with it, listing here:

* We need to rewrite URLs as Navaid's matcher doesn't include trailing slash
* Navaid performs a load even if only the "#" changes

**Comment by robdodson** [comment]
btw if we don't want to mess around with writing our own router, there's also [page.js](https://visionmedia.github.io/page.js/) that might be worth considering.

**Comment by samthor** [comment]
Fixed by #1725
