### ISSUE TITLE
content: How Terra improved app user ratings 25% thanks to TWA

### ISSUE THREAD

**Issue by demianrenzulli** [GoogleChrome/web.dev#1718]
**Author**: @demianrenzulli 
**Reviewer**: [Leave blank. web.dev team will assign a reviewer.]

**Target publish date:** <2019-11-20>
- [ ] Check this box if this is a hard deadline.
- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [X] 1. I've done my [proposal](https://docs.google.com/document/d/1B86M3PfScw4l083s85yA4UBMMLNWlfPul_crEAZY3zg/edit#)
- [x] 2. Proposal approved — _reviewer checks this_
- [X] 3. I've added a [draft](https://docs.google.com/document/d/1732br6jTuzchK4tNMuxU6JD_96BVCpdGYQheRSHQ40o/edit?usp=sharing) to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

This case was requested and reviewed by @b1tr0t and written in collaboration with Carlos Aranha and @andreban.

**Comment by kaycebasques** [comment]
@demianrenzulli please give me edit access to the [draft](https://docs.google.com/document/d/1732br6jTuzchK4tNMuxU6JD_96BVCpdGYQheRSHQ40o/edit).

Next step after that is for me to do a structural edit.

**Comment by demianrenzulli** [comment]
Thanks a lot for your help @kaycebasques! 

I think this post was written before web.dev/handbook came out. Would you prefer me to give a first pass to it, to save you some time?

Just let me know!
Cheers.

**Comment by kaycebasques** [comment]
I think this one is indefinitely stalled because of the new case study criteria.
