### ISSUE TITLE
content: Updates to badging API

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1736]
**Author**: @petele 
**Reviewer**: @jpmedley 

**Target publish date:** ASAP

- [ ] Check this box if this is a hard deadline.
- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

The [Badging API](https://web.dev/badging-api/) is changing in Chrome 79.

**Comment by kaycebasques** [comment]
Next step: @petele to incorporate the review feedback

**Comment by kaycebasques** [comment]
@carolrivero to create a milestone for m81 and move this issue to that milestone

**Comment by carolrivero** [comment]
This issue has been removed from the Content Project Board and milestone "Sprint 2019-12-18" has been added.

**Comment by petele** [comment]
I just noticed this was tagged Chrome 81 - these changes are for m79, this needs to go out ASAP. The PR is ready to go and has been approved by @jpmedley
