### ISSUE TITLE
Footer tap targets are not large enough.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1767]
**Describe the bug**
To get 100 on Lighthouse's SEO audit we need our `a.w-footer__linkbox-link` elements to be larger. We can probably add a little bit of padding to get them there.

**To Reproduce**
1. Go to https://web.dev
2. Run the LH SEO audit.

![image](https://user-images.githubusercontent.com/1066253/67808552-22d39800-fa54-11e9-9a03-9bec54f1247d.png)

**Comment by evlnyng** [comment]
I would like to give this a shot!
