### ISSUE TITLE
Why and how Chromium plans to support all the things 

### ISSUE THREAD

**Issue by ThomasTheDane** [GoogleChrome/web.dev#1769]
**Author**: @ThomasTheDane 
**Reviewer**: 

**Target publish date:** <2019-11-11>
- [X] Check this box if this is a hard deadline.

- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

- [x] 1. I've done my proposal https://docs.google.com/document/d/1Kh2BVXORdGfUNTzWMKdmr5YLaCTl-OqDLb7fu5D8S3o/edit# 
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@kaycebasques please assign a reviewer

**Comment by ThomasTheDane** [comment]
Apologies for the confusion! I submitted this one yesterday
<https://github.com/GoogleChrome/web.dev/issues/1769> and it looks like
Pete had already submitted one (which I should have seen). I am only trying
to publish one blog post and these two are the same. Feel free to kill
either of them
