### ISSUE TITLE
Measure page categories and scale have too much space on mobile

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1772]
Old site:
![image](https://user-images.githubusercontent.com/1066253/67812584-c45ee780-fa5c-11e9-8e99-cb8d10f4ae1b.png)

New site:
![image](https://user-images.githubusercontent.com/1066253/67812547-b0b38100-fa5c-11e9-87b0-2fca1f3a6526.png)

**Comment by robdodson** [comment]
@devnook if you're interested in taking this on, it might be a good one to fix soon since it's a user facing bug.

**Comment by devnook** [comment]
Fixed via #1800
