### ISSUE TITLE
Blog: Web Bundles

### ISSUE THREAD

**Issue by uskay** [GoogleChrome/web.dev#1774]
Author: @uskay
Reviewer: @jpmedley 

A one to two sentence description of your post
This article explains how the Web Bundle proposal makes your website portable. 

What are you planning to teach folks in this post?
Learn how Web Bundles make your website portable

Target publish date: CDS wave 3 (right before CDS)

- [x] Check this box if this is a hard deadline.
- [x] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

Process

- [x] I've done my proposal : [web.dev article | Web Bundles](https://docs.google.com/document/d/1NFStsELbOiW5ajKWVKSGlj-sYuF6YbLb0Iq8zUl_xHQ/edit?usp=sharing)
- [x] Proposal approved
- [x] I've added a draft to my proposal doc
- [x] Draft approved
- [x] I've submitted a pull request
- [ ] Pull request approved

cc/ @kaycebasques @robdodson

**Comment by kaycebasques** [comment]
@jpmedley from the email thread it sounds like @uskay thinks this is stable enough to review. I haven't looked at the doc, though, so it's your call.

**Comment by kaycebasques** [comment]
Next step is for @jpmedley to review the Google Doc.

**Comment by uskay** [comment]
Do let me know if you wanted me to send over a PR. I'll be flying to SFO end of this Friday PST (Nov 8) so will I'll make myself flexible in fixing things before that.

**Comment by jpmedley** [comment]
I've reviewed the draft and made suggestions. Please look this over. I'm happy to help you with the PR, especially given the short timeline we're on.

**Comment by uskay** [comment]
@jpmedley thank you for the review. I accepted the suggestions and left ones with comments to confirm the best way to frame each of the writing. Once the folks who I looped in (mainly @jyasskin and @kinu ) is okay with the suggestion, could you please help us out with the PR? Much appreciated.

 - The drive folder for all the img / video assets are here: https://drive.google.com/drive/folders/1ashog7rTSE66ui5Zaf00HtYCfe8uA5UT?usp=sharing
 - We want myself (@uskay) and  @KenjiBaheux as an author. For Kenji, I think he's new to web.dev so added his 96x96 and 192x192 profile pics in the drive as well. The profile below should be good.
```json
  "kenjibaheux": {
    "name": {
      "given": "Kenji",
      "family": "Baheux"
    },
    "org": {
      "name": "Google",
      "unit": "Product Management"
    },
    "country": "JP",
    "twitter": "KenjiBaheux"
  },
```
