### ISSUE TITLE
Need to signal current active page in SideNav

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1784]
**Describe the bug**
The Header component shows which page is active with an underline. We should add something similar to the SideNav.

**To Reproduce**
1. Got to web.dev/learn
2. Notice that the header has a blue underline under "Learn"
3. Resize the browser and click the hamburger menu to open the SideNav

**Expected behavior**
The Learn tab in the SideNav should have an active state indicator.

**Comment by robdodson** [comment]
Happy to discuss. My gut reaction is that it may add complexity that might not be worth the trade off. But I haven't spent a good deal of time looking into it so maybe it's easier than I anticipate.

**Comment by mayankkt9** [comment]
Hi, I was looking at this issue as my potential first issue. I see that the `box-shadow` style is not present for the element, unlike the normal desktop size where `web-header__link[active]` applies that style.
On adding the same box-shadow style, the SideNav would appear like the image provided?
Is this how you are expecting it to behave? I was thinking to add one more CSS for class .web-side-nav__link for active link as `web-side-nav__link[active] : -webkit-box-shadow: 0 -2px 0 #3740ff inset;
    box-shadow: 0 -2px 0 #3740ff inset;`
Let me know what you think.
![snapshpt](https://user-images.githubusercontent.com/37381526/71554453-1330eb00-29d4-11ea-8b0f-53ffea0d0caf.png)

**Comment by robdodson** [comment]
I think something like that could work. If you want to put together a pull request we can take a look.
