### ISSUE TITLE
Update handbook to mention that directory name should match article title

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1785]
When creating a post called `How to blob with gorp` the directory structure should be `src/site/content/en/blog/how-to-blob-with-gorp`

**Comment by mihajlija** [comment]
We were following that convention initially, until the handbook advertised:

> Keep the name as short as possible while still being meaningful.

When you update the handbook, please remember to remove the above sentence.

**Comment by kaycebasques** [comment]
Thanks for the context, @mihajlija
