### ISSUE TITLE
Analytics don't fire for initial page view.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1795]
**Describe the bug**
When a user first lands on the site, analytics don't fire a pageview.

**To Reproduce**
1. Go to any page on web.dev

**Expected behavior**
There should be a pageview ping to GA.

**Comment by samthor** [comment]
I'm confused because if anything I see the opposite behavior—_further_ pages don't send pageviews. I've included a PR: #1814

**Comment by robdodson** [comment]
> I'm confused because if anything I see the opposite behavior—further pages don't send pageviews. I've included a PR: #1814

Ah that might be because [I snuck in a commit to fix](https://github.com/GoogleChrome/web.dev/commit/cb0208cf7943963c498592c6143f00c7a79dd781) this and forgot to close the ticket.

I'll take a look at #1814
