### ISSUE TITLE
Is a service worker a requirement for an installable manifest?

### ISSUE THREAD

**Issue by bazzadp** [GoogleChrome/web.dev#1797]
The https://web.dev/installable-manifest/ page states that:

> If a page doesn't meet all the following criteria, it will fail the audit:
>
> ...
>
> - The page registers a service worker with a fetch event handler.

However there are many pages that don't have a service-worker but according to Lighthouse the manifest meets the installability criteria.

For example https://www.dropee.com/ gets the following on Lighthouse:

![image](https://user-images.githubusercontent.com/10931297/67940033-baf38d80-fbca-11e9-9d9c-bc0b393eee27.png)

55,675 sites in HTTPArchive's July 2019 run meet this criteria (warning this query uses 1.22TB so don't run unless you have credit!):

```
SELECT *
FROM `httparchive.lighthouse.2019_07_01_mobile`
WHERE JSON_EXTRACT_SCALAR(report, '$.audits.installable-manifest.score') = '1'
and JSON_EXTRACT_SCALAR(report, '$.audits.service-worker.score') = '0'

```

In fact only 20,000 sites meet both criteria (uses a service worker and is installable) so this is over reporting by a large factor IMHO!

It seems to me that the Lighthouse check and/or the documentation could be clarified here. Is audits->installable-manifest meant to measure just the 5 manifest items (`short_name`/`name`, `icons`...etc.) or also the other installability criteria listed on [this page](https://web.dev/installable-manifest/) (HTTPS and Service Worker)? And if just the former should this be made clear on the page rather than stating this is part of the "Web app manifest does not meet the installability requirements" criteria?

**Comment by robdodson** [comment]
Assigning to @mfriesenhahn to take a look. Per our team chat, the doc should be updated to mention that the audit is only checking for specific items in the manifest file.

**Comment by mfriesenhahn** [comment]
I already submitted a PR for this: #1819
