### ISSUE TITLE
Is every deploy causing a SW forced reload?

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1803]
**Describe the bug**
Just deployed the site and noticed when I visited the page that it seemed to do a force reload again.

**To Reproduce**
1. Deploy a new version of the site.
2. Visit the site.

**Expected behavior**
The page should not reload but I _think_ it does. Maybe because the kill switch is looking for `v2` but the sw is `v201910311622`. Need to investigate more.

**Comment by samthor** [comment]
We aren't importing the "build" version into the SW whatsoever—the "v2019..." doesn't exist in "sw.js".

We are logging debug when we're doing a forced refresh.

**Comment by robdodson** [comment]
yeah this may be a non-issue. I'll close it and reopen if I notice it happening again.
