### ISSUE TITLE
Laggy scrolling on web.dev (all pages)

### ISSUE THREAD

**Issue by samtstern** [GoogleChrome/web.dev#1811]
**Describe the bug**
On my phone or MacBook (any device with inertial scrolling) scrolling web.dev pages is really laggy.

**To Reproduce**
1. Go to web.dev
1. Flick up and down to scroll
1. See choppiness

**Expected behavior**
Smooth scrolling

**Screenshots**
I believe this scroll event listener on `window` in `router.js` is to blame:
![image](https://user-images.githubusercontent.com/8466666/67988984-bf31a200-fbee-11e9-970b-0db717c31d17.png)

I am just a lowly Android developer but a web friend suggested `requestAnimationFrame` here.

**Comment by samtstern** [comment]
cc @abeisgoat who found the event listener.

**Comment by robdodson** [comment]
Hmmmm I'll take a look. [That listener should be passive](https://github.com/GoogleChrome/web.dev/blob/master/src/lib/utils/router.js#L141) but perhaps it causes layout thrashing. cc @samthor

**Comment by samthor** [comment]
Yeah, this is my bad. `requestAnimationFrame` and some deduping is correct.
