### ISSUE TITLE
Suggestions for lazy-loading FAQ

### ISSUE THREAD

**Issue by bazzadp** [GoogleChrome/web.dev#1850]
In the [Native Lazy Loading](https://web.dev/native-lazy-loading/) article it does not make it clear if adding lazy-loading to every image (even those definitely in the view port) element is a bad thing.

Will it cause hero images to take slightly longer to download as the browser evaluates whether it's needed or not?

Could we add something to the FAQ about that as seen this question asked a lot?

On a similar point is native lazy-loading a recommended alternative to prevent double downloads (e.g. `mobile-hero.jpg` and `desktop-hero.jpg`) where only one of which is shown due to CSS? Many people currently use background-images with the parent element displayed or not, which are not accessible and the `picture` element can be more complex to use. Obviously this would only prevent the double download on supported browsers, but it's a lot easier to implement to exisiting sites than other solutions so could be a quick win.

Could we add something to the FAQ about that this use case too and whether it's appropriate use of this or not?

**Comment by robdodson** [comment]
Those are great questions. @housseindjirdeh when you have some spare cycles would you be able to look into this?

**Comment by housseindjirdeh** [comment]
Thanks for this @bazzadp! That's a great point, I'l circle back to look into this in a week's time or so when things slow down after Chrome Dev Summit :)

**Comment by jitendravyas** [comment]
I had asked these question on twitter to Addy but didn't get response

**Comment by bazzadp** [comment]
> On a similar point is native lazy-loading a recommended alternative to prevent double downloads (e.g. mobile-hero.jpg and desktop-hero.jpg) where only one of which is shown due to CSS? 

Testing this, it would appear that this doesn't work - both images are still loaded even though one will be hidden by CSS (so arguably not in the viewport).

**Comment by kaycebasques** [comment]
@housseindjirdeh can you put in these updates? See also #1448.

**Comment by housseindjirdeh** [comment]
PR #2075 to address this 🚀 

@bazzadp I added a FAQ on the potential issues of lazy-loading in-viewport elements. Let me know if you think that covers things up. I didn't add one on using native lazy loading to prevent double downloads but if you think it's worth addressing - please let me know!

**Comment by bazzadp** [comment]
> @bazzadp I added a FAQ on the potential issues of lazy-loading in-viewport elements. Let me know if you think that covers things up.

Thanks @housseindjirdeh ! LGTM

> I didn't add one on using native lazy loading to prevent double downloads but if you think it's worth addressing - please let me know!

Hmmm... I still think there is an opportunity to clear up some potential confusion here. What about expanding the FAQ after it?

From this:

> How does the loading attribute work with images that are in the viewport but not immediately visible (for example, behind a carousel)?

To this:

> How does the loading attribute work with images that are in the viewport but not immediately visible (for example, behind a carousel, or hidden by CSS on this screen width)?

**Comment by housseindjirdeh** [comment]
@bazzadp Good call! The next FAQ is a good place to include a mention of that 👍 

Updated #2075!

**Comment by bazzadp** [comment]
LGTM - thanks for that! Feel free to close this issue when merged.

**Comment by noell** [comment]
FAQ makes no mention of how, or even if, the lazy loading attribute affects developers writing `let image = new Image()` in their JS code.  Some developer guidance on that matter would be good, imho.

**Comment by bazzadp** [comment]
> FAQ makes no mention of how, or even if, the lazy loading attribute affects developers writing `let image = new Image()` in their JS code. Some developer guidance on that matter would be good, imho.

I’m not sure what you mean. The `loading` attribute is just another attribute like any other. So if creating an image in JavaScript you can chose to set that or not and once the image is added to the DOM it will be read and the `loading` attribute treated appropriately. Not sure what guidance you’re looking for? Confirmation that adding to the DOM like this will lazy-load images if added sufficiently off screen? That should be easy enough to test but see no reason why it would not (and personally I would consider it a bug if it did not).

Regardless this issue has been actioned and closed so suggest you raise a new issue if you have new requests.
