### ISSUE TITLE
Bug: Distorted images on web.dev/blog 

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1876]
**Describe the bug**

Images on web.dev/blog are distorted and grainy.

![1B2880B8-F539-4843-85B7-DFE64DB4F4D5](https://user-images.githubusercontent.com/4713486/68551008-0f61ee80-03bd-11ea-9be7-0b86ac1a0641.png)

![Uploading 36AC919F-808B-4D68-8522-8DF64793F75F.png…]()

**To Reproduce**

iOS 13.1.3

Chrome 76

**Comment by robdodson** [comment]
@kaycebasques are you still seeing this issue? I wasn't able to reproduce it on my phone.

**Comment by kaycebasques** [comment]
Seems OK now.
