### ISSUE TITLE
Algolia includes promise polyfill

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/web.dev#1879]
Algolia includes a Promise polyfill in its code. We should remove it somehow.

**Comment by robdodson** [comment]
Assigning to Sam to verify if it's still there and if we feel like messing with it.

**Comment by samthor** [comment]
Looks like v4 doesn't include polyfills anymore 🎉 https://www.algolia.com/doc/api-client/getting-started/upgrade-guides/javascript/

I'll upgrade us.
