### ISSUE TITLE
Mention DevTools/Puppeteer support in `prefers-color-scheme` article?

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChrome/web.dev#1886]
https://web.dev/prefers-color-scheme/ continues to be the one-stop shop for all things dark mode. 👍🏻

Would it make sense to mention the recently-added DevTools/Puppeteer support for emulating `prefers-color-scheme` and other CSS media features? cc @tomayac

**Comment by tomayac** [comment]
Definitely! Thanks for the nudge! I will address this once the Chrome Dev Summit and BlinkOn dusts have settled.
