### ISSUE TITLE
Fix Glitch code associated to Next.js dynamic imports doc

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1895]
@mihajlija can you fix the code in the dynamic-imports-no-ssr Glitch?

Context: #1894

**Comment by mihajlija** [comment]
Fixed, thanks for letting me know!

**Comment by kaycebasques** [comment]
Sorry, forgot another step. @mihajlija can you please give glitch.com/@webdev ownership of the Glitch, too.

**Comment by mihajlija** [comment]
I've added the project to the team page and here's the [invitation link](https://glitch.com/edit/#!/join/24425973-a9b3-4b16-918c-f43202546364). (I've also fixed the thumbnail.)

**Comment by kaycebasques** [comment]
Thank you @mihajlija
