### ISSUE TITLE
content: Experimenting with the Content Indexing API

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/web.dev#1896]
**Author**: @jeffposnick
**Reviewer**: @jpmedley 

**Target publish date:** 2019-12-19
- [X] Check this box if this is a hard deadline.

- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal <add a link to your proposal doc>
- [ ] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft [Draft here](https://docs.google.com/document/d/1JT6vrMzP3Yvt9JGxjAjAietu58Txqn9_tUxUQK0k3QY/edit#heading=h.n7wmdjicgi05)
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by jpmedley** [comment]
We need to merge this today, please.
