### ISSUE TITLE
content: "Privacy Sandbox: Privacy Model for the Web"

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1898]
Soft deadline: 3 Mar 2020
Author: @samdutton 
Reviewer: @kaycebasques

**Comment by carolrivero** [comment]
@kaycebasques follow up w/ @rowan-m to link to doc.

**Comment by kaycebasques** [comment]
Rowan outlined the doc, Sam is going to flesh out the draft. This isn't ready for reviews so I think we can remove it from the sprint schedule.
