### ISSUE TITLE
All glitches should include a link back to the host page, and learning path

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChrome/web.dev#190]
Low-pri for launch, but we should make sure all Glitch Samples link back to the:

* web.dev site, 
* the embedder page (so people can quickly get to the instructions if they land on the actual glitch)
* the learning path so people can explore more.

It doesn't have to be a prominent link, but it will help with discovery and visibility for everyone (search and people).

**Comment by robdodson** [comment]
@PaulKinlan I think these links would need to be in the source for the Glitch itself. In other words, the user would see them when they're doing an exercise or lesson. I guess that's ok?

**Comment by robdodson** [comment]
Going to close because this ticket hasn't been addressed in a year and isn't part of our current OKRs. It may be something we revisit in the future.
