### ISSUE TITLE
content: Introduction of SXG.

### ISSUE THREAD

**Issue by kumagi** [GoogleChrome/web.dev#1903]
**Author**: @kumagi
**Reviewer**: TBD

**Target publish date:** 2020-01-20

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal https://docs.google.com/document/d/1j5Ib3YuonGkPqMDtIfebnqTnPxhR_bYzwBEal6DDI1U/edit?usp=sharing
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by kaycebasques** [comment]
@kumagi there's no detail in the Google Doc and I'm unsure where this content proposal is coming from. Please send me an email explaining:

* Why this content is a priority
* Who in Web DevRel can help you with the content

We can re-open this issue later if it becomes clear that this is content that we want to publish.

**Comment by kaycebasques** [comment]
@kumagi I reviewed your content. Please read below for the next steps that you need to take.

I didn't have edit access to your Google Doc so I made [a copy of the Doc](https://docs.google.com/document/d/11UZ22mx8HlXMtNOUDLlPijbdzXHXYaLSMu82bRdTAGo/edit#).

Please review all of my suggestions and accept them or leave comments if they can't be accepted for some reason.

Assign this issue back to me and leave a comment when you're done reviewing my suggestions. You can ping me on Chat or email if I'm not responsive here.

**Comment by kaycebasques** [comment]
@kumagi as mentioned in the Google Doc, the content LGTM now. So next step is for you to update #2083 & #2096 to have the latest content.

Sorry for the delay and thank you for contributing, I look forward to landing your content on web.dev.

**Comment by kumagi** [comment]
@kaycebasques OK, thank you very much for reviewing. I'll update the PR.
