### ISSUE TITLE
Update Cookie articles to indicate shipping in Chrome 80

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1908]
https://web.dev/samesite-cookies-explained/
https://web.dev/samesite-cookie-recipes/

**Target publish date:** 2019-12-19
- [x] Check this box if this is a hard deadline.

**Comment by mfriesenhahn** [comment]
Reviewed! LGTM.

**Comment by jpmedley** [comment]
Reverted by #2007 because the described changes did not ship.
