### ISSUE TITLE
Update getInstalledRelatedApps() article to indicate shipping

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1909]
https://web.dev/get-installed-related-apps/

**Target publish date:** 2019-12-19
- [x] Check this box if this is a hard deadline.

**Comment by jpmedley** [comment]
The feature itself is blocked:

* TAG committee still has issues.
* Lacks three LGTMs.

**Comment by kaycebasques** [comment]
Removed `DO NOT MERGE` label because of this comment: https://github.com/GoogleChrome/web.dev/pull/1992#issuecomment-586447469
