### ISSUE TITLE
All glitches should have a canonical link to the original glitch

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChrome/web.dev#191]
Following on from #190 - we want to be respectful in search and not spammy. If we make sure that each glitch has a link rel canonical pointing to the original glitch then we won't get a heap of duplicate domains with nearly exactly the same content messing up search.

**Comment by robdodson** [comment]
so if I create a glitch called hello-world you'd like every remix to include a link rel=canonical href=https://hello-world.glitch.me?

**Comment by carolrivero** [comment]
@PaulKinlan bumping this up. Thanks.

**Comment by robdodson** [comment]
Closing as stale, see #190
