### ISSUE TITLE
SEO links needs to be fixed.

### ISSUE THREAD

**Issue by technbuzz** [GoogleChrome/web.dev#1914]
**Describe the bug**
Some URL's in Seo section aren't linked properly linked to their respective TOC.

**To Reproduce**
1. Go to [Document Title](https://web.dev/document-title/)
2. Scroll down all the way to the bottom
3. Click on **Return to all articles**
4. You will be redirected to **Accessibility Section** rather than **Seo**

**Comment by robdodson** [comment]
Yeah this is kind of an unfortunate known issue. Since this doc appears in both the accessibility and seo collections, that breadcrumb chooses whichever one came first. We've been discussing getting rid of these footer breadcrumbs for this reason.

**Comment by kaycebasques** [comment]
Thanks for the report @technbuzz. We're aware of the issue but don't have any short-term plans to fix it. I'll let Rob re-open this one if he has different thoughts on the matter.

**Comment by robdodson** [comment]
I'd like to reopen this one if it's ok. We need to figure out what to do with breadcrumbs for articles that appear in more than one collection.

**Comment by robdodson** [comment]
We have a partial fix for this now that we show all the paths a post is part of in the breadcrumbs:
![image](https://user-images.githubusercontent.com/1066253/76475724-16c1f480-63bd-11ea-80a8-4a8d19a754d2.png)

But we still have the two buttons at the bottom. We'll have to come up with another plan to fix those.

**Comment by robdodson** [comment]
keep it alive bot

**Comment by robdodson** [comment]
Changing the assignee to @devnook who is currently working on removing the confusing next/previous buttons.

In addition, we've added a "Appears in" breadcrumb at the top which shows when content exists in multiple collections.

![image](https://user-images.githubusercontent.com/1066253/83701838-c3c49b80-a5bf-11ea-8bc5-fbae092d5ae6.png)

**Comment by robdodson** [comment]
I'm going to mark this as fixed. We removed the confusing next/previous buttons and now rely on the breadcrumbs at the top to take people back to the relevant sections.
