### ISSUE TITLE
content: Companion blog for "Speed tooling evolutions"

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1922]
https://youtu.be/iaWLXf1FgI0

**Author**: @egsweeny  
**Reviewer**: @mihajlija 

**Target publish date:** 2019-12-04

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done [my proposal](https://docs.google.com/document/d/1rLYekEgcXsanFQV8PJBgoeexYM_m_zQG33nZvUZ6kx4/edit)
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1962
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by kaycebasques** [comment]
@egsweeny already has a draft in the works around this topic: https://docs.google.com/document/d/1rLYekEgcXsanFQV8PJBgoeexYM_m_zQG33nZvUZ6kx4/edit

So @mihajlija perhaps you can just edit that draft and help them land it on web.dev by submitting the PR and so on

**Comment by kaycebasques** [comment]
@carolrivero content process problem: Milica was ready to review the content but couldn't because she didn't have access to the Google Doc draft.

**Comment by mihajlija** [comment]
Submitting a PR first thing tomorrow.

**Comment by carolrivero** [comment]
Waiting for feedback from @egsweeny then PR will be ready.

**Comment by mihajlija** [comment]
Got feedback and assets from Elizabeth, but I was busy finishing the adaptive loading post review. I'm out of office until Thursday, I'll wrap up the PR when I get back.
