### ISSUE TITLE
content: Companion blog for "Adaptive loading"

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1923]
https://youtu.be/puUPpVrIRkc

**Author**: @mihajlija 
**Reviewer**: TBD

**Target publish date:** 2019-12-04

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal <add a link to your proposal doc>
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc https://docs.google.com/document/d/1SgSOJlLfjI7Y3TLb06bad4nG2k00_zs2iFEEG4u_c8A/edit?usp=sharing
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #2000
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@mihajlija - please provide an update on next steps. Do you want the Google Docs reviewed or do you have a PR coming?

**Comment by carolrivero** [comment]
UPDATE:  @kaycebasques needs to assign a reviewer. Doc is ready for review.

**Comment by carolrivero** [comment]
@jpmedley to review.

**Comment by jpmedley** [comment]
@mihajlija Nice work! It's a clean draft. My comments are nits.

**Comment by mihajlija** [comment]
Addressed the review and added a new section on Addy's request. Started working on the PR, I'll submit it when I get back to work on Thursday.
