### ISSUE TITLE
content: Companion blog for "Main thread is overworked"

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1924]
https://youtu.be/7Rrv9qFMWNM

**Author**: @mfriesenhahn 
**Reviewer**: TBD

**Target publish date:** 2019-12-04

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my [proposal](https://docs.google.com/document/d/19sJP166m_CAbiTEaIHUrhXqUnioiHdyzRg6xGmvsMvc/edit?usp=sharing)
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1955
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@surma to review.

**Comment by mfriesenhahn** [comment]
Need access to talk assets and need responses from Surma on last few outstanding issues in draft.

**Comment by mfriesenhahn** [comment]
Videos added and issues addressed. Ready for content review. @kaycebasques to assign TW.
