### ISSUE TITLE
content: Companion blog for "Next generation web styling"

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1925]
https://youtu.be/7Rrv9qFMWNM

**Author**: @mfriesenhahn  
**Reviewer**: @kaycebasques 

**Target publish date:** 2019-12-04

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my [proposal](https://docs.google.com/document/d/1Ar08YZPbd1Dm2SmuT6_HLvxygd6A6S4KgAwuqUvY6GQ/edit?usp=sharing)
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1963
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@mfriesenhahn - draft will be done before Thanksgiving.

**Comment by carolrivero** [comment]
@argyleink - please review and provide feedback by Dec 5. Thanks.

**Comment by argyleink** [comment]
i've done a review pass 👍

**Comment by argyleink** [comment]
@una should get a ping as well to review her content. y'all have invited her to the same docs and relevant github convos yeah?

**Comment by una** [comment]
I haven’t received anything yet

- Una

**Comment by mfriesenhahn** [comment]
@una, I wanted to respond to @argyleink's comments before sharing with you so I could address one set of feedback at a time. That's done, so it's all yours :) LMK if you didn't get the link in your email.

**Comment by mfriesenhahn** [comment]
PR is up. Needs @una's review and a quick once over from Adam to make sure everything made it into MD as intended.

**Comment by mfriesenhahn** [comment]
@argyleink's review complete. @una needs to do a technical review of her sections, and @kaycebasques needs to assign a TW to do a content review.
