### ISSUE TITLE
content: Companion blog for "PWAs and the installable web"

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1926]
https://youtu.be/Hp_dQvQyYEI

**Author**: @jpmedley  
**Reviewer**: TBD

**Target publish date:** 2019-12-04

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal <add a link to your proposal doc>
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

@jpmedley to start draft on Mon, Dec 2. Need an actual video for this.

**Comment by kaycebasques** [comment]
Here's the transcript, @jpmedley: https://drive.google.com/file/d/1MCinhApzCjw-VjlSQyswTKu-9axgA1ml/view?usp=sharing

**Comment by carolrivero** [comment]
@jpmedley will reach out to Sam to review the article. ETA for review: by Dec 4 or Dec 5.

**Comment by carolrivero** [comment]
@jpmedley haven't gotten to this - working on app gap

**Comment by kaycebasques** [comment]
Blocked until Joe gets back from vacation in January.

**Comment by kaycebasques** [comment]
Joe plans on working on this but Sam is busy for the next few months. Joe asked Pete to find a new reviewer for this. Late January is the soonest this can potentially get published.

**Comment by samthor** [comment]
I don't think we'll write content for this.
