### ISSUE TITLE
content: Companion blog for "Bridging the native app gap"

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1927]
https://youtu.be/JKVZMqpiY7w

**Author**: @jpmedley  
**Reviewer**: TBD

**Target publish date:** 2019-12-04

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal <add a link to your proposal doc>
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

@jpmedley to start draft on Mon, Dec 2

**Comment by kaycebasques** [comment]
@jpmedley this video doesn't have a transcript.

**Comment by kaycebasques** [comment]
@jpmedley disregard that last comment. Here's the transcript: https://drive.google.com/file/d/1tmtJx7psUHAqAFUTZ3Utt6-sLkeZrh1l/view?usp=sharing

**Comment by carolrivero** [comment]
@jpmedley will reach out to Sam to review the article. ETA for review: by Dec 4 or Dec 5.

**Comment by carolrivero** [comment]
1st article is getting a sanity check then will go into PR. 
2nd article will send a sanity check today or tomorrow.
3rd article will check if it needs to go out w/ this issue.

**Comment by kaycebasques** [comment]
1st article is Share Targets With Workbox. 

2nd article is in draft format, "Bridging Native App Gap, part 1". Probably won't land before Joe is back before vacation, Jan 3.

3rd article will probably be delayed. Mostly functionality that hasn't been built. Working title is "Bridging Native App Gap, part 2" but final title will probably be different.

**Comment by carolrivero** [comment]
@jpmedley - can we close this one out?

**Comment by jpmedley** [comment]
No.

**Comment by carolrivero** [comment]
@jpmedley - Can you provide a deadline when you want this to launch?

**Comment by jpmedley** [comment]
I thought I had some time today, but a more urgent issue came up.
