### ISSUE TITLE
Add table of contents to articles.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1931]
We'll need some design help on this. I think having each article lead off with a TOC may push a bunch of stuff down the page, so we might consider using a button to open the TOC?

There are eleventy plugins for generating TOCs (https://www.npmjs.com/package/eleventy-plugin-toc) so we probably just need to chuck one of these into our project and style it.

**Comment by MichaelSolati** [comment]
I guess I'd need an idea as to what it should look like... Heres the default style:

![image](https://user-images.githubusercontent.com/11811422/70565643-61766b00-1b47-11ea-982e-dd20dc45cef8.png)

**Comment by robdodson** [comment]
@kaycebasques do you have examples of TOCs from other sites that you like? Personally I'm concerned that adding one forces content further down the page (especially on mobile) and they don't seem to be used on other sites like css-tricks, alligator.io, or smashingmagazine. I think you may have shared an example with me in the past where the TOC was inside of a button that folks could click to expand it, thereby saving on screen real estate. I wonder if something like that would be an option?

**Comment by kaycebasques** [comment]
Next step is for @kaycebasques to provide examples of ToCs.

**Comment by MichaelSolati** [comment]
@kaycebasques no rush, but is there any update?
