### ISSUE TITLE
content: Companion blog for "Protecting users on a thriving web"

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1934]
https://youtu.be/WnCKlNE52tc

**Author**: @mihajlija 
**Reviewer**: TBD

**Target publish date:** <yyyy-mm-dd>

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal <add a link to your proposal doc>
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@kaycebasques - Please advise if this issue needs to stay in the 2019-12-18 milestone. Otherwise, please update milestone to the appropriate one. Thanks.

**Comment by kaycebasques** [comment]
@kaycebasques to connect @mihajlija with the talk presenters so that she can get further information

**Comment by kaycebasques** [comment]
Duplicate of #2017

**Comment by kaycebasques** [comment]
@mihajlija as I just discovered in the email thread with the Privacy/Security people, we probably don't need this blog post. Check out our 1:1 doc for requested upcoming work.
