### ISSUE TITLE
Google Fonts and Page Speed Insights Score Lighthouse receommendations

### ISSUE THREAD

**Issue by mrbm** [GoogleChrome/web.dev#1939]
Reviewing: https://web.dev/font-display?utm_source=lighthouse&utm_medium=unknown

It suggests using: font-display: swap;

However, is the google fonts family using this for their code?

ie when using:

https://fonts.googleapis.com/css?family=Montserrat%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%7CQuestrial%3Aregular%7CUbuntu%3A300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C700%2C700italic%7CPermanent+Marker%3Aregular&subset=latin%2Clatin-ext

(which I believe google page speed is complaining about)

It is not using: font-display: swap;

Why is it not using that?

**Comment by robdodson** [comment]
hi @mrbm, I think you need to add `&display=swap` to your snippet of code to tell Google Fonts that you want it to use `font-display:swap`.
