### ISSUE TITLE
Not properly tracking signed in state.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1941]
I noticed when we moved off of DevSite that we stopped tracking when the user is signed in/out.

We have the ability to track signed in state by setting an analytics custom dimension:
```
ga.set(site.analytics.dimensions.SIGNED_IN, true);
```
This means all subsequent pings will contain this info so we can discern actions that occurred from signed in versus signed out users.

I'd suggest that we move the code we currently use to set the signed in state out of fb.js, and into actions.js. Then we can set the custom dimension as a side effect.

Phil suggested that we also consider delaying the send event for our initial pageview, and wait until firebase auth has returned so we can track whether the user was signed in/out for the initial page view. He suggested we set a timeout to ensure we capture the pageview event if fb is taking too long to return.

**Comment by robdodson** [comment]
@samthor what do you think about the above proposal?

**Comment by samthor** [comment]
I'm not an expert re: custom dimensions but it sounds good. Remember that users can transition in both directions signed in <=> signed out on the same page.

We could also add a `beforeunload` handler and log pageview on timeout via beacon. Just to track bounces.

**Comment by robdodson** [comment]
> Remember that users can transition in both directions signed in <=> signed out on the same page.

Yeah I think we currently have a `clearSignedInState` action and I was wondering if we should have an action for signing in. Then we would set the custom dimension in those two actions to indicate either signed in or signed out.

This also got me thinking about analytics middleware and if we may want to have an easier way of setting analytics events/states/whatever as side effects of actions.

**Comment by robdodson** [comment]
Spoke with Sam today.

We discussed setting the dimension and firing an event when the client side js boots up and we are able to see that the user is signed in. @devnook happy to discuss this more over VC.

**Comment by robdodson** [comment]
@samthor @devnook I've assigned this to both of you. I was thinking, whoever is free first can claim this issue and work on it. Just be sure to leave a comment here and remove the other assignee.

I spoke with Addy today related to other projects and it sounds like having this stat would be useful so we should prioritize adding this back to the site soon if we can.

**Comment by samthor** [comment]
There's a pending PR (which to be fair is superseded). Keeping this alive. 👨‍🎤
