### ISSUE TITLE
Cannot run website locally

### ISSUE THREAD

**Issue by isa3bel** [GoogleChrome/web.dev#1946]
**Describe the bug**

When I run `npm run dev` I get this error in localhost: `Error: ENOENT: no such file or directory, stat '/Users/ibolger/Code/web.dev/dist/en/404/index.html'`
**To Reproduce**

**Expected behavior**

**Screenshots**
![Screen Shot 2019-11-26 at 3 54 59 PM](https://user-images.githubusercontent.com/18249360/69682077-206d5980-1065-11ea-97f1-81e1d8f184a5.png)

**Comment by brittanystoroz** [comment]
@isa3bel I received this error at first too, I believe it was just from trying to access the site before the build was completely finished for the first time. I refreshed my http://localhost:8080 a couple seconds later and it worked fine. Maybe give that a try?? If this is actually what's causing the issue, maybe we can update the README to be more explicit about waiting for the build to finish before trying to access localhost:8080

**Comment by isa3bel** [comment]
ok sounds good I'll wait and see if that works! Is there an indicator that the build is "done" or do I simply need to wait for a few moments? @brittanystoroz

**Comment by IvanBila** [comment]
Hi @isa3bel here's the message it shows when the build is done.

![Screenshot from 2019-12-01 08-16-22](https://user-images.githubusercontent.com/13482373/69910363-faeca100-1412-11ea-8f4e-5b1569e18731.png)

**Comment by IvanBila** [comment]
@robdodson what is the minimum version of Node for running this project? I think maybe that should be added to the README, moreover, you could add a .nvmrc file that specifies the version.

**Comment by isa3bel** [comment]
it worked after upgrading node js! Thanks!
