### ISSUE TITLE
content: User idle detection

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#1948]
**Author**: @tomayac.
**Reviewer**: 

**Target publish date:** tbd
- [ ] Check this box if this is a hard deadline.

- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

- [X] 1. I've done my [proposal](https://docs.google.com/document/d/1mQfS2Bv_tJVubqy75GdhsRScqlrjZTeYEZz1kH9qdzc/edit#)
- [ ] 2. Proposal approved — _reviewer checks this_
- [X] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

Also see https://github.com/google/WebFundamentals/issues/7715.

**Comment by carolrivero** [comment]
@tomayac - please add an estimated time for publish date to help us plan our workload and so we can slot this in to the appropriate sprint milestone.

**Comment by tomayac** [comment]
@samuelgoto, can you give us some timeline guidelines for the Idle Detection API, please?

**Comment by jpmedley** [comment]
My reading of the tea leaves is that this couldn't go any earlier than Chrome 81. To link to it from the Chromium blog beta post we would want its date to be before Feb 13 (Chrome 81) or before March 26 (Chrome 82).

**Comment by carolrivero** [comment]
Moving this to the end of 2020-Feb-26 milestone. We are removing Sprint 2019-02-19 from the milestone list.
