### ISSUE TITLE
How do I contribute and make changes?

### ISSUE THREAD

**Issue by isa3bel** [GoogleChrome/web.dev#1950]
Hi all,

I am new to open source, and would like to contribute to this website. How do I make changes? I am trying to change the .njk files but when I save and reload the localhost, my changes are not reflected. Similar to when I change an .md file, the changes are not reflected. Do I need to rebuild the project every time I make a change? Thanks for the advice all

**Comment by MichaelSolati** [comment]
You shouldn't have to rebuild the content from a markdown file, however the generated HTML page may be cached by the service worker though. (In the Network tab of Chrome DevTools you can "Disable cache" which will keep the cache off as long as DevTools are open)

I do believe that template/structure filed (njk and js) do require you to kill and rebuild the dev server though.

**Comment by isa3bel** [comment]
changing the templates or any file and rebuilding does not result in any change on the local host website. not sure why my changes aren't displaying @MichaelSolati

**Comment by robdodson** [comment]
It may be the service worker caching things. You can try pressing shift-R (or shift-F5 on windows) to do a hard refresh.

You might also try opening DevTools (right click on the page and click 'Inspect'), going to the Applications tab, clicking on "Service Workers", and checking the Bypass for network checkbox.

![image](https://user-images.githubusercontent.com/1066253/70480501-b86f3800-1a94-11ea-99dc-87efbc187312.png)

**Comment by robdodson** [comment]
@isa3bel did you get things working? I'm going to close this issue but happy to reopen if you're still hitting issues.
