### ISSUE TITLE
content: Share Targets in Workbox

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1953]
**Author**: @Snugug, @jpmedley 
**Reviewer**: @kaycebasques 

**Target publish date:** <yyyy-mm-dd>
- [ ] Check this box if this is a hard deadline.

- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal [Share Targets in Workbox]
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #1994 
- [ ] 6. Pull request approved — _reviewer checks this_

# Why this proposal exists

This article solves a problem created by #1927. As stated elsewhere, I'm experimenting with turning the CDS presentation transcript into an article. At more than 5000 words, that transcript is too long for a web.dev article.

In trying to shorten it, I've identified this block of text as one that can function as a stand-alone article. 

The draft is still being sanity checked by Sam.

@kaycebasques

**Comment by carolrivero** [comment]
@kaycebasques should this be added to the 2019-12-18 milestone? If so, it's been added to the content project board since this milestone is now active.

**Comment by carolrivero** [comment]
@kaycebasques to review PR
