### ISSUE TITLE
Throw linting error when `updated` field is not updated

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1959]
**Is your feature request related to a problem? Please describe.**

1. Someone updates content
1. They forget to update the `updated` field in the front matter

**Describe the solution you'd like**

1. The automated build/linter system throws an error instructing them to update the field

Assigning to @robdodson for triage

**Comment by robdodson** [comment]
I've started work on this as a form of perfcrastination. Hope to have something to share soon. cc @petele

**Comment by jpmedley** [comment]
The WebFu version of this updated the date for you. It would be nice if this could too.

**Comment by robdodson** [comment]
I have a YAML linter that i've written that fixes but I need to put together the PR for it. Keep this one open bot.

**Comment by robdodson** [comment]
I'm going to close this because our pre-commit hook seems to be doing a good job of handling it now.
