### ISSUE TITLE
Update Periodic Background Sync article for shipping by default.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1964]
https://web.dev/periodic-background-sync/

Target publish date: 2019-12-19

 - [ ] Check this box if this is a hard deadline.

**Comment by mfriesenhahn** [comment]
@jpmedley, for this issue, #1980 is the right PR, yeah?

**Comment by jpmedley** [comment]
Yes.

**Comment by mfriesenhahn** [comment]
Reviewed!

**Comment by jpmedley** [comment]
We need to merge this today, please.
