### ISSUE TITLE
Typo - What is speed page

### ISSUE THREAD

**Issue by rahuls360** [GoogleChrome/web.dev#1974]
**Describe the bug**
Spelling mistake in the image. 'smoth and natural' used instead of 'smooth and natural'

**To Reproduce**
1. Go to 'https://web.dev/what-is-speed/'
3. Scroll down to 'First image'. Read under Is it delightful?
4. See error.

**Expected behavior**
'smoth and natural' must be smooth and natural

**Screenshots**
![screenshot](https://i.imgur.com/lOin5JC.png)

**Comment by robdodson** [comment]
@bojanpavic do you happen to have another version of this graphic?
