### ISSUE TITLE
Add LightWallet to the measure tool

### ISSUE THREAD

**Issue by martinschierle** [GoogleChrome/web.dev#1978]
**Is your feature request related to a problem? Please describe.**
Lighthouse can audit against custom set perf budgets via the LightWallet feature. However, this isn't possible in the measure UI.

**Describe the solution you'd like**
For own tests after login it would be great if you could also add a URL to your own custom bvudgets.json file, and then see results with respect to this.

**Describe alternatives you've considered**
Right now there doesn't seem to be a nice and easy UI for lightwallet around

**Additional context**
This would make adoption of performance budgets probably much easier, if there is a ready-to-use UI available for it.

**Comment by robdodson** [comment]
That's an interesting idea. We're discussing ways  that we can improve the experience of the measure tool so I'll share this with the LH team.
