### ISSUE TITLE
samesite-cookies-explained

### ISSUE THREAD

**Issue by KolyaKorruptis** [GoogleChrome/web.dev#1990]
https://web.dev/samesite-cookies-explained/

www.web.dev & static.web.dev = samesite
your-project.github.io & my-project.github.io = cross-site

Explanation: "public suffix list defines this"

¯\\\_(ツ)\_/¯

**Comment by robdodson** [comment]
tagging @rowan-m for his thoughts

**Comment by kaycebasques** [comment]
Hi @KolyaKorruptis what's the feedback here? Is it that we need to explain this idea better?

**Comment by KolyaKorruptis** [comment]
Yes. There is no explanation why the first example is samesite and the second cross-site, except "public suffix list defines this".
This doesn't seem helpful. And it's not obvious what the distinction is.

**Comment by kaycebasques** [comment]
Got it, thank you for clarifying.
