### ISSUE TITLE
Backticks appear in title elements

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1993]
**Describe the bug**
When an author uses backticks in a page title to display code font, the backticks are included in the page's `<title>` element. For example:

![image](https://user-images.githubusercontent.com/14199217/70746183-4d16a780-1cda-11ea-9584-4b4391263ad7.png)

**To Reproduce**
1. View source for the page and expand the `<title>` element.
1. See error.

**Expected behavior**
Backticks are stripped from `<title>` elements.

**Comment by NickolasBenakis** [comment]
I can take this one
