### ISSUE TITLE
appengine-test.web.dev should not be crawled.

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#2024]
**Describe the bug**
Searching on Google returns results for the domain **appengine-test.web.dev**

![Screen Shot 2019-12-19 at 9 57 05 AM](https://user-images.githubusercontent.com/718038/71183889-c36d5980-2246-11ea-8ab3-c7e92f31803e.png)

**To Reproduce**
1. Go to https://www.google.com/search?q=pwa+multi+origin+demian
2. Second result is pointing to appengine-test.web.dev

**Expected behavior**
web.dev not appengine-test.web.dev

**Comment by robdodson** [comment]
I asked search console to crawl the URL again and I think that may have fixed it.

![image](https://user-images.githubusercontent.com/1066253/71190744-fd842e80-2239-11ea-815d-ffab1191675a.png)

But I'm curious why this happened in the first place. I'm not an SEO expert but a few thoughts:

- When we publish something as a draft it still gets deployed but it has a `noindex` tag to prevent it from being crawled. However, I wonder if it might still be in the sitemap and if that affects things? I'm also curious if we need to make sure each page has a canonical tag?

**Comment by samthor** [comment]
We can also just disable this domain. It was literally as it says on the tin, for testing before we changed our serving infra.

I honestly wonder how it got indexed at all.

**Comment by robdodson** [comment]
+1 for disabling.
