### ISSUE TITLE
content: Create first batch of self-assessments

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#2025]
**Author**: @mfriesenhahn 
**Reviewer**: @kaycebasques 

**Target publish date:** <yyyy-mm-dd>
- [ ] Check this box if this is a hard deadline.

- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

- [x] 1. I've done [my proposal](https://docs.google.com/document/d/1oXHvmpvXWFeEUHALWlfsIaVjMj6ppTR3PD8BQO0OODM/edit?usp=sharing)
- [x] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [x] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #2052
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by mfriesenhahn** [comment]
Sets ready for review in the [Google doc](https://docs.google.com/document/d/1oXHvmpvXWFeEUHALWlfsIaVjMj6ppTR3PD8BQO0OODM/edit?usp=sharing). To make it easier to see how the content fits in the UI, I went ahead and created a PR. You can view staged versions of the sets at the following links:
- [control-focus-with-tabindex](https://deploy-preview-2052--web-dev-staging.netlify.com/control-focus-with-tabindex/)
- [use-semantic-html](https://deploy-preview-2052--web-dev-staging.netlify.com/use-semantic-html/)
- [labels-and-text-alternatives](https://deploy-preview-2052--web-dev-staging.netlify.com/labels-and-text-alternatives/)
- [same-origin-policy](https://deploy-preview-2052--web-dev-staging.netlify.com/same-origin-policy/)

**Comment by robdodson** [comment]
I reviewed all of these and found them to be both fun and really well written! The only hiccup I experienced was in the control-focus doc when the same question was used for sample 1 and 2 but then slightly changed for sample 3. I missed that it had been changed and got the question ever so slightly wrong.

**Comment by mfriesenhahn** [comment]
Thanks, @robdodson! I addressed the other comments you made and, for now, tried to tackle the stem variation in the control-focus post by resequencing the items so 1 and 2 are no longer adjacent. I'm definitely open to a larger revision if you think that'd help!

@kaycebasques, it'd probably be worth having a tech writer take a look at the PR to make sure there aren't any other issues.

**Comment by carolrivero** [comment]
@kaycebasques to review PR

**Comment by kaycebasques** [comment]
#2052 was merged so for our purposes at the moment I'll close this
