### ISSUE TITLE
Update image optimization requirements in the handbook

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/web.dev#2030]
We need to add specific instructions for uploading images to web.dev that balance:

1. Keeping the repo size down https://github.com/GoogleChrome/web.dev/pull/1962#pullrequestreview-334229282
2. Serving high-quality images on large and retina displays https://github.com/GoogleChrome/web.dev/pull/1962#issuecomment-567683908

Considerations:
- Hero images are optimized by a CDN but should be cropped to 3200 x 960 px.
- Content images need to be optimized manually, but we should aim for 1600px width for high-quality.

To do:
- Explain different requirements for hero and content images.
- Suggest tools for optimizing images such as [tinypng.com](tinypng.com) (CLI and web), [squoosh.app](squoosh.app) (web), or other.
- Explain when it's appropriate to use JPG, PNG, and SVG.
- Suggestions?

cc @kaycebasques @robdodson @mfriesenhahn

**Comment by robdodson** [comment]
I think the above points sound good to me. A while back Michael did create a bit of guidance around the hero images here: https://web.dev/handbook/markup-media/#hero-images

**Comment by mfriesenhahn** [comment]
SGTM also. Since this is about technical details rather than how to use images to support writing goals, I think it'd probably go in `/markup-media`.

@mihajlija, do you want to take a stab at drafting this? 😁

**Comment by mihajlija** [comment]
I can take it when I get back to work in January. 

It would help to set a performance budget for images per post + we could later enforce it with Lighthouse CI. I think some of the recent hero/thumbnail images on /blog turned out poor because of double optimization (for example, Lighthouse and Web Share API posts). cc @kaycebasques
