### ISSUE TITLE
Try out the Content Indexing API

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/web.dev#2031]
The [Content Indexing API](https://web.dev/content-indexing-api/) is running as an Origin Trial in Chrome 80.

Since all web.dev posts under `/blog/` that a user has visited are cached and should work offline, web.dev should consider trying out the Content Indexing API.

Using the API when you already have an offline-capable PWA is pretty straightforward. [Here are some examples](https://twitter.com/jeffposnick/status/1207764802271154178) of adding it to some PWAs that I maintain. If you're open to the idea but there's no engineering time from the core team available, I could submit a PR to add support.

CC: @petele

**Comment by robdodson** [comment]
If you have the bandwidth to submit a PR I know we'd appreciate it. It sounds like a rad feature but wasn't something we had immediate plans to work on.

**Comment by jeffposnick** [comment]
Cool! This is what I came up with as a first cut: https://github.com/GoogleChrome/web.dev/compare/content-indexing-support

It definitely needs some more work, and I'd love to chat with the eng team about how page loading and your service worker caching setup works to ensure that I'm making the right decisions.

On Chrome 80+ for Android, you'd end up seeing something like this after browsing around a bit:

![Screenshot (Dec 20, 2019 2_07_13 PM)](https://user-images.githubusercontent.com/1749548/71285035-3273ac80-2332-11ea-9eb7-41129c609a31.png)

**Comment by jeffposnick** [comment]
So I would still like to do this, especially now that the SW caching stuff seems more settled.

I can revise my original code into something more production-y.

**Comment by robdodson** [comment]
Thanks @jeffposnick. @samthor if we move ahead with this would you feel comfortable maintaining it? Should we have sw tests in place before we add it so we can ensure we don't break it?

**Comment by jeffposnick** [comment]
I speculatively refactored the service worker partial JSON output, so that it includes extra `description`, `url`, and `imageSrc` fields, when those values are available. This should be backwards compatible with the existing cache storage entries, so I didn't bump the versioning in the cache name.

That makes using the Content Indexing API a lot easier, as I can just do a sweep through all of the indexed JSON once inside of `bootstrap.js`, and use the values directly from cache storage to keep the index up to date. Otherwise, I had to put some code inside of `loader.js` that would react to every page load and pull out the required metadata, using CSS class names to figure out the `description` and/or `imageSrc` values, and that was messy.

Let me know what you think about that approach by taking a look at https://github.com/GoogleChrome/web.dev/compare/content-indexing-support

(I think the new `git` hook that bumps the `updated` field in the Markdown source files is too aggressive, as each time I do a `npm run build` locally, new Markdown files with updated dates end up being committed.)

**Comment by robdodson** [comment]
hm I don't think the hook should be triggered on build, it should run when `commit` gets called. If you do `git commit --no-verify` it will not run.

**Comment by robdodson** [comment]
@jeffposnick would you be ok with opening a PR so we can review? Might be easier to do it that way so we can comment on lines versus doing the branch diff

**Comment by jeffposnick** [comment]
Sure. Let me create a clean branch and I'll file a PR.

**Comment by jeffposnick** [comment]
I filed https://github.com/GoogleChrome/web.dev/pull/2798

**Comment by jeffposnick** [comment]
#2798 is still waiting on feedback from @samthor.
