### ISSUE TITLE
RSS feed doesn’t contain code samples

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#2039]
**Describe the bug**

Articles in the RSS feed don’t contain code samples (at least not in a readable by Feedly format; sorry, on mobile and couldn’t easily check).

**To Reproduce**
1. Subscribe to web.dev via a feed reader like Feedly. 
2. See how the code samples are missing. 

**Expected behavior**

The code samples should be contained. 

**Screenshots**

![973BED3F-603A-4C34-B042-643B16A56F75](https://user-images.githubusercontent.com/145676/71408533-e335c080-263e-11ea-9143-36c6f60364e4.png)

**Comment by tomayac** [comment]
I could trace this back to all code samples being wrapped in `<web-copy-code>`.

**Comment by robdodson** [comment]
hm... I wonder why that would mess up the RSS representation. I figured the outer tag would be ignored. Tagging in @MichaelSolati for his thoughts.

**Comment by tomayac** [comment]
Well, it doesn’t work in Feedly, and that’s one of the major feed readers. `¯\_(ツ)_/¯`
