### ISSUE TITLE
Navigation missing from https://web.dev/plugins/

### ISSUE THREAD

**Issue by anubhavyadav** [GoogleChrome/web.dev#2042]
As I was going through the list in https://web.dev/lighthouse-seo/ , I found navigation at bottom missing from https://web.dev/plugins/ . Not a big deal, it often happens while creating such large & rich content.

**Comment by robdodson** [comment]
It may be easy to miss but there is a  button which will take you back to the lighthouse seo section at the  bottom.

![image](https://user-images.githubusercontent.com/1066253/71855990-628faf00-3097-11ea-8d73-c66850cea0fd.png)
