### ISSUE TITLE
Web.dev by google seems to lag navigation

### ISSUE THREAD

**Issue by anubhavyadav** [GoogleChrome/web.dev#2044]
I feel many pages are not ordered well as well as many of them are missing navigation like https://web.dev/web-share/ which you cannot navigate from HOME.

**Comment by robdodson** [comment]
Those pages are blog posts and are accessible from https://web.dev/blog/

**Comment by anubhavyadav** [comment]
Ya rob I had found this when I have gone through whole web.dev

**Comment by robdodson** [comment]
I'm not sure if there are immediate steps for us on this one but next time we do some design work we'll try to think if there are ways to improve on the navigation.

**Comment by anubhavyadav** [comment]
Yes, yes why not. I have started so many threads in futility. Sorry for that.
