### ISSUE TITLE
Most of Codelab demos have a blank screen on the right

### ISSUE THREAD

**Issue by anubhavyadav** [GoogleChrome/web.dev#2045]
Who designed these https://web.dev/codelab-remove-unused-code/ may have not tested well, as right side panel in desktop screen is blank. And this happened in almost all codelab demos.

I feel there can be problem on my side as well. plz let me know.

**Comment by robdodson** [comment]
It should look like this:

![image](https://user-images.githubusercontent.com/1066253/71855818-f0b76580-3096-11ea-9df6-9c567f4196d1.png)

But it can sometimes take a moment to load. Are you able to view this page? https://glitch.com/~fav-kitties-starter

**Comment by robdodson** [comment]
@anubhavyadav are you still getting a blank screen? Sometimes it can take a long time for the embed to load. I'm going to close this for now but let me know if you're still having issues.

**Comment by anubhavyadav** [comment]
Sorry Rob, I was not able to reply, as I was robbed...... sorry for the pun. As I have finished reading WEB.DEV, I was trying to finish WEB FUNDAMENTALS and currently at https://developers.google.com/web/fundamentals/design-and-ux/animations/css-vs-javascript

Hey, one thing that improved since I last visited WEB.DEV is the login functionality, with which I was facing some trouble earlier, but now as you can see top-right in the screenshot that I was able to Login successfully.

The other issue of Codelab exercise may still be persistent as the box is still appearing to be empty in the same screenshot



![ScreenHunter_ Mar  15 11 41 34](https://user-images.githubusercontent.com/32266762/76696539-ab28a180-66b2-11ea-930a-d0160a265a13.jpg)
.
