### ISSUE TITLE
Navigation on Web.dev is serious issue

### ISSUE THREAD

**Issue by anubhavyadav** [GoogleChrome/web.dev#2046]
I am now confused between https://web.dev/unminified-css/ and https://web.dev/minify-css/ . My flow of completing the study of this web.dev is breaking now & then. I hope You will fix it soon. Or tell me if I can be of some help.

**Comment by robdodson** [comment]
Hi @anubhavyadav, can you explain a bit more what is confusing  to you?

**Comment by anubhavyadav** [comment]
I feel I am raising so many issues unnecessarily. But When I read a nicely designed website like WEB.DEV , I wish there were less distraction like in a PDF. But here cross linkages are repetitive and some content repeated somewhere gives a feeling of confusion whether I have gone through this page or not.

However, as You were so kind to ask for problem explanation, I wish to share 1 bug and 1 suggestion to you : 

1- Suggestion - It will be great if tree-navigation of web.dev looks like https://developers.google.com/web/fundamentals/ . This way I can be sure of exactly where I am going within the site.

2- Bug - SIGN IN - is not working on WEB.DEV . I don't know if it does not work for me only or anyone else is also not able to sign in. I have tried it for both website and its PWA.

**Comment by robdodson** [comment]
> 1- Suggestion - It will be great if tree-navigation of web.dev looks like https://developers.google.com/web/fundamentals/ . This way I can be sure of exactly where I am going within the site.

I understand the need for more breadcrumbs. I don't think we're planning to add the side navigation from /web/fundamentals in the near term because I think our team is still figuring out how they want to organize content on the site. But we may look into this in the future.

> 2- Bug - SIGN IN - is not working on WEB.DEV . I don't know if it does not work for me only or anyone else is also not able to sign in. I have tried it for both website and its PWA.

Hm... I tested it and it was working for me. Which country are you in? Do you have errors?

**Comment by anubhavyadav** [comment]
> > 1- Suggestion - It will be great if tree-navigation of web.dev looks like https://developers.google.com/web/fundamentals/ . This way I can be sure of exactly where I am going within the site.
> 
> I understand the need for more breadcrumbs. I don't think we're planning to add the side navigation from /web/fundamentals in the near term because I think our team is still figuring out how they want to organize content on the site. But we may look into this in the future.
> 
Oh yes, plan should be first laid out.
> > 2- Bug - SIGN IN - is not working on WEB.DEV . I don't know if it does not work for me only or anyone else is also not able to sign in. I have tried it for both website and its PWA.
> 
> Hm... I tested it and it was working for me. Which country are you in? Do you have errors?
I am from India. It does not give any error to me. But nothing does happens when I click on it, despite being signed in Google as well as Chrome.

**Comment by robdodson** [comment]
> I am from India. It does not give any error to me. But nothing does happens when I click on it, despite being signed in Google as well as Chrome.

Hm ok... It should open a little popup window and ask you to sign in. Could you click on it and then look in the developer console to see if there are any errors?

**Comment by anubhavyadav** [comment]
> > I am from India. It does not give any error to me. But nothing does happens when I click on it, despite being signed in Google as well as Chrome.
> 
> Hm ok... It should open a little popup window and ask you to sign in. Could you click on it and then look in the developer console to see if there are any errors?

So when I click on Sign in, the popup box with nothing in it except a loading ring, comes up and disappears and nothing happens after that. The Sign In box remains as it is instead of showing my thumbnail.

**Comment by robdodson** [comment]
> The Sign In box remains as it is instead of showing my thumbnail.

Hey @anubhavyadav, I think this has become an issue about sign in. Do you have any errors in the console? I'm planning to close this issue but if it's still happening, let's open a new one to specifically address the sign in issue.
