### ISSUE TITLE
"View Report" doesn't work for URLs containing encoded characters

### ISSUE THREAD

**Issue by xojoc** [GoogleChrome/web.dev#2050]
**Describe the bug**
Lighthouse gives an error if an encoded character is passed. Example: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https://www.keepmeon.top/discussions?url=%3A

**To Reproduce**
1. Run an audit for https://www.keepmeon.top/discussions?url=https%3A%2F%2Fwww.python.org%2Fpsf%2Fpress-release%2Fpr20191220%2F
2. Click on "View report"
3. Lighthouse reports: {"errors":"No results found for \"https://www.keepmeon.top/discussions?url=https://www.python.org/psf/press-release/pr20191220/\"."}

**Comment by robdodson** [comment]
Maybe related to https://github.com/GoogleChrome/web.dev/issues/1105. I think query strings in general may not work.

**Comment by samthor** [comment]
Dup of #1105
