### ISSUE TITLE
SameSite changes are not backwards compatible

### ISSUE THREAD

**Issue by Tratcher** [GoogleChrome/web.dev#2054]
**Describe the bug**
https://github.com/GoogleChrome/web.dev/blame/48e66b9e5a1d3df7425c990a3fbd6ae52718c4fa/src/site/content/en/blog/samesite-cookies-explained/index.md#L407
`Both of these changes are backwards-compatible with browsers that have correctly implemented the previous version of the SameSite attribute`

The spec changes are not backwards compatible. The prior RFC said that any unknown value should be treated as Strict.

https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00#section-3.2
```
   samesite-value = "Strict" / "Lax"

   If the "SameSite" attribute's value is "Strict", or if the value is
   invalid, the cookie will only be sent along with "same-site"
   requests.
```

The introduction of SameSite=None had the opposite of the desired effect on those browsers. This causes significant compt issues with iOS 12 and Mac OS 10.14 that required OS upgrades to fix. There are several other affected clients, but none so large.

Applications cannot safely use SameSite=None without accounting for clients like iOS/Mac that strictly implemented the prior spec.

**Comment by rowan-m** [comment]
Ack, looking at this. There's definitely discrepancy between the SameSite draft and RFC6265 versions. I'll get this clarified.

**Comment by kaycebasques** [comment]
@rowan-m are you going to work on this this month?
