### ISSUE TITLE
RSS feed's global update date is wrong

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#2064]
See the current [feed](https://web.dev/feed.xml):

```xml
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>web.dev</title>
  <subtitle>Let&#39;s build the future of the web.</subtitle>
  <link href="https://web.dev/feed.xml" rel="self"/>
  <link href="https://web.dev"/>
  <updated>2018-11-05T01:00:00+01:00</updated>
```

It looks like `2018-11-05T01:00:00+01:00` is the date of the first post instead of the last post. The [code](https://github.com/11ty/eleventy-plugin-rss/blob/f7a1c5f11eed8511598d497e7f84e313f1061696/.eleventy.js#L12) confirms this theory. The easiest way to deal with this would be to reverse `collections.posts`.

**Comment by robdodson** [comment]
ah ok, I think we already reverse the post collection here:

https://github.com/GoogleChrome/web.dev/blob/9f0e8c71368a579c656fb8fc5391e005567e98af/.eleventy.js#L133

https://github.com/GoogleChrome/web.dev/blob/master/src/site/_collections/post-descending.js

I guess the RSS feed would like it to go in the other direction :P
