### ISSUE TITLE
Stale-While-Revalidate isn't the right strategy for content pages

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#2069]
I just fell for a stale article and wasted time updating it until I realized that I had a stale version of it in my cache.

I *strongly* suggest instead of the current [`new workbox.strategies.StaleWhileRevalidate()`](https://github.com/GoogleChrome/web.dev/blob/a5102ed4e19d14ebafe0976fbcdb7a709a7a2cd9/src/lib/sw.js#L119-L124) we use [`new workbox.strategies.NetworkFirst()`](https://developers.google.com/web/tools/workbox/modules/workbox-strategies#network_first_network_falling_back_to_cache).

**Comment by samthor** [comment]
Ideally I'd like to serve stale, then tell the foreground page there's an update, and have the content magically swap out.

But you're right that stale on its own is probably not ideal.

**Comment by tomayac** [comment]
> Ideally I'd like to serve stale, then tell the foreground page there's an update, and have the content magically swap out.

Personally, I follow you up until "update", but disagree with the "have the content magically swap out" part. I think it's very confusing when a page swaps the content while I'm reading it. I'd rather prefer a "this content has been updated, please reload" toast. Other thoughts?

**Comment by robdodson** [comment]
I've also been thinking we should switch this behavior. If you've previously visited web.dev/blog, then you visit web.dev you'll see a list of new articles on the front page. When you click 'See More' it will take you to the (cached) version of the blog and now you don't see those new articles unless you refresh.

I'm ok switching to network first and then we can think if there's a nicer update strategy we would like to use in the future.

**Comment by philipwalton** [comment]
FWIW, on my blog I use `StaleWhileRevalidate`—along with the [`workbox-broadcast-update`](https://developers.google.com/web/tools/workbox/modules/workbox-broadcast-update) plugin—for all my content requests, and that seems to work pretty well.

Whenever there's an update, I do one of two things (depending on whether the user has interacted with the page, e.g. scrolled, clicked, etc.):

- **If no user interaction yet:** swap out the content without notice
- **If user interaction has occurred:** leave the content as-is, but show a toast indicating that the content has been updated

In my testing, most users never re-visit pages for which there's been a content update. And when they do, most of the time the SW detects an update well before the user first interacts with the page. Thus, given how rarely an update is detected after a user interaction, I've found it's acceptable to show an update in those cases.

Of course, this could all be very specific to my audience, so I think it's worth tracking this for web.dev before making any changes that could annoy users.

**Comment by robdodson** [comment]
That sounds very cool. I'll add a feature request for us to explore adding that approach.
