### ISSUE TITLE
Ensure all code examples under /metrics work cross-browser

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/web.dev#2078]
I discovered today that some of the code examples for the docs under [web.dev/metrics](https://web.dev/metrics/) will now error in Safari. This is due to the fact that Safari recently added support for the `PerformanceObserver` API, but it doesn't support entry types such as `paint`, `first-input`, or `longtask`, nor does it support the new `type` observe option. Furthermore, when using these options Safari will throw an error rather than silently failing.

It's probably worth updating all the code examples to add proper feature detection and error handling for such cases.

**Comment by kaycebasques** [comment]
Sounds good, I'll assume that you're going to submit the PR, @philipwalton

**Comment by carolrivero** [comment]
@philipwalton - please provide an update if this update is still valid. The issue has been open for 2 months now. If we don't hear back in 48 hours, we will move this into the icebox (won't work on it until 6 months from now). Thanks.

**Comment by philipwalton** [comment]
It's still valid, I haven't gotten to it yet, but I'll move it up on my TODO list since it's pretty important.

**Comment by carolrivero** [comment]
thanks, @philipwalton - do you have an ETA? The issue has been open since Jan. Thx.

**Comment by philipwalton** [comment]
Submitted #2378
