### ISSUE TITLE
PWA Guidance Should be Generalized Beyond Android

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#2080]
While editing PWA content I've noticed that it refers almost exclusively to an Android context, or at least to a mobile context. It does this by referring to "installing to the home screen" or "from an app store". (The use of 'app store' is itself misleading because it implies availability from their app store, which, last I heard, is not true. That's another issue.)

But PWAs are now installable on desktop, including Mac, Windows, Linux, and Chrome OS. Language surrounding installability needs to reflect this fact whenever appropriate.

**Comment by jpmedley** [comment]
@petele FYI.

**Comment by kaycebasques** [comment]
@jpmedley any plans to work on this in March or April?

**Comment by jpmedley** [comment]
I forgot I opened this. I didn't open it because I thought I was going to do it. I meant it as a marker that this is something we need to discuss in Fugu team (or at least between me and Pete).

@petele

**Comment by carolrivero** [comment]
Ideally, we would prefer to track issues in GH for all content requests only as this will. skew our reporting. I recommend using a different tool outside of GH to plan future work. Thanks in advance for your help.
