### ISSUE TITLE
GitHub labels for team verticals

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#2086]
This is less of a feature request and more of a request for a change of practice.

As a web.dev contributor and a member of a DevRel subgroup, I'd like labels corresponding to the subgroups within the DevRel team. This would make it easier to find all issues and PRs related to that subgroup. In addition to applying to content proposals, this proposal would also replace the practice of adding specific names to content bugs.

For example, Issue #1973 was updated yesterday without input from anyone in the PWA/Fugu. I don't blame anyone for pushing this out the door. Pete or I should have jumped on this. There's no question that the issues assigned to us would be easier to find if they were properly labeled.

**Comment by carolrivero** [comment]
@jpmedley 
I'm already working w/ @kaycebasques on this one. Look out for more details by next week. Thanks.

**Comment by kaycebasques** [comment]
I think this is mostly fixed now.

**Comment by jpmedley** [comment]
What is the solution?

**Comment by kaycebasques** [comment]
We now have labels for the most common team verticals:

* `capabilites`
* `pwa`
* `performance`
* `frontend`
* `media`
* `lighthouse`
* `games`
* `privacy/security`
