### ISSUE TITLE
content: QUIC Transport

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#2093]
**Author**: @jeffposnick 
**Reviewer**: @jpmedley 

**Target publish date:** 2020-05-27
- [x] Check this box if this is a hard deadline.

- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal <add a link to your proposal doc>
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@jpmedley - please provide an update. Thx.

**Comment by jeffposnick** [comment]
`QUICTransport` is scheduled to go to origin trial in M84. I'm currently working on material for web.dev to go live prior to the M84 beta release.

**Comment by jeffposnick** [comment]
I have a draft of this post available as a `@google.com`-siloed Google Doc at https://docs.google.com/document/d/1dvSqBzBubeSmsZGnEXi6pYaN-_L44BG4TVW856gyxCM/edit

There are still a few loose ends to tie up regarding the possibility of a demo/sample app, but most of the pieces relevant for an editorial review are in place at this point.
