### ISSUE TITLE
content: Update "Hands-on with Portals"

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#2094]
**Author**: @uskay, @jpmedley
**Reviewer**: [Leave blank. web.dev team will assign a reviewer.]

**Target publish date:** Unknown
- [] Check this box if this is a hard deadline.

- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal [Existing article](https://web.dev/hands-on-portals/)
- [ ] 2. Proposal approved — (NA)
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@jpmedley - please confirm if this is still happening. Thx.

**Comment by jpmedley** [comment]
It might slip to Chrome 83.

**Comment by carolrivero** [comment]
Updated the milestone to sprint ending on Apr 30. Feel free to update once the release this is related to is confirmed. In in the interim,  I will leave this in the sprint-ready pipeline on the content planning board for now.

**Comment by jpmedley** [comment]
If it ships in Chrome 82, it has to be live before the beta release post. (As an example, here's the Chrome 81 beta release post.) That means the date is actually a hard deadline of April 25 to be sure it's live before the beta post is.

**Comment by kaycebasques** [comment]
@jpmedley is this still happening?

**Comment by lousscott** [comment]
Take it down
