### ISSUE TITLE
Details elements and footer links focusable when sidenav is open

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#2102]
**Describe the bug**
`<details>` elements in `<main>` and anchor elements in the footer remain focusable when the modal side nav is open.

**To Reproduce**
1. View the [web.dev components Handbook page](https://web.dev/handbook/web-dev-components/) at a viewport width <865px.
2. Click the hamburger button.
3. Begin tabbing through the page.
4. All `<details>` elements and footer links are focusable.

**Expected behavior**
`<details>` elements and footer links should not be focusable when the side nav is open.
- Looks like the footer just needs to be set to `aria-hidden=true` and `inert` when `<web-header>` and `<main>` are.
- Looks like the WICG inert polyfill [fixed the `<details>` problem](https://github.com/WICG/inert/commit/06bd9fd230cf5abb4a28e69aa13f4fef58fe5685) in October, but I'm inferring web.dev is using the GoogleChrome inert polyfill. Perhaps the latter needs to be updated?

**Comment by robdodson** [comment]
We're using wicg-inert but our version may be outdated. Would you mind revving it to the latest to see if it fixes the issue?

**Comment by mfriesenhahn** [comment]
#2106 ready for review
