### ISSUE TITLE
content: Performance monitoring [apr 21]

### ISSUE THREAD

**Issue by khempenius** [GoogleChrome/web.dev#2107]
author: @khempenius 
reviewer: @kaycebasques
draft: https://docs.google.com/document/d/124jv9cYPfk1ew8z1EC-b-7MPNMRPVXf9Xt6J1zF_UeA/edit?usp=sharing

**Comment by kaycebasques** [comment]
@khempenius please incorporate my feedback in the google doc and then submit a PR

**Comment by khempenius** [comment]
Closing this.

(This morphed into the "Measuring Web Vitals" article that was added by https://github.com/GoogleChrome/web.dev/pull/3039.)
