### ISSUE TITLE
content: lighthouse CI guide [2020 Jun 30]

### ISSUE THREAD

**Issue by khempenius** [GoogleChrome/web.dev#2108]
author: @khempenius 
reviewer: @kaycebasques
draft: https://docs.google.com/document/d/1UFs-hadHSkv3VwQAS9KpRy2d7unRB-yRjphayZ6etRU/edit?usp=sharing
next step: @khempenius to incorporate @samdutton's usability review feedback

History:

* @samdutton usability reviewed on 17 July 2020

**Comment by kaycebasques** [comment]
@khempenius I finished my review. I hit some usability troubles while trying out the guide. Please check out my feedback and then leave me a comment here when you're ready for another review. Valuable content!

**Comment by kaycebasques** [comment]
@khempenius are you still planning on landing this?

**Comment by khempenius** [comment]
Yes, I'm still planning on landing this. Originally I was planning on having this accompany the performance monitoring article but I now think it makes more sense for this to exist as a standalone blog post.

**Comment by khempenius** [comment]
not stale.

**Comment by kaycebasques** [comment]
@samdutton you're up for review!

**Comment by kaycebasques** [comment]
@khempenius please make sure @samdutton has comment access (at minimum) on your Doc

**Comment by samdutton** [comment]
Added comments. Good article!

LGTM with minor suggestions.

**Comment by samdutton** [comment]
I've finished doing my usability review: added comments to the doc.  

Overall, the structure and instructions worked really well for me (apart from the `LHCI_BUILD_CONTEXT__CURRENT_BRANCH` glitch described in my comments).
