### ISSUE TITLE
content: Media Session

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/web.dev#2122]
**Author**: @beaufortfrancois 
**Reviewer**: [Leave blank. web.dev team will assign a reviewer.]

**Target publish date:** February
- [ ] Check this box if this is a hard deadline.

- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my [proposal](https://docs.google.com/document/d/1crooDQSlen_6HOPdtlOwfnhyjmuFBwpyKDGc91zC_Ik/edit?usp=sharing)
- [ ] 2. Proposal approved — _reviewer checks this_
- [x] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [x] 5. I've submitted a pull request #2310
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by beaufortfrancois** [comment]
@jpmedley Can you review the document draft?

**Comment by carolrivero** [comment]
@beaufortfrancois - please provide us access to the doc
@jpmedley - please provide status if this in in review.

**Comment by jpmedley** [comment]
The draft is still being reviewed. Expect a PR some time this week.

**Comment by beaufortfrancois** [comment]
@jpmedley Why did you close this issue? I thought we would use it to track progress of the article.

**Comment by jpmedley** [comment]
I must have fat-fingered it.
