### ISSUE TITLE
content: How to request new browser features [title tbd.]

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#2127]
**Author**: @tomayac 
**Reviewer**: @kaycebasques 

**Target publish date:** any
- [ ] Check this box if this is a hard deadline.

- [X] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Quick summary:** Web developers are asking how they can make their voice heard and request a feature to be implemented by the different browser vendors. This article will be an attempt at documenting the best way for each vendor to make this happen.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal <add a link to your proposal doc>
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by carolrivero** [comment]
@tomayac -please provide a draft and we will add this in the current sprint ending Mar 31.

**Comment by carolrivero** [comment]
@tomayac - will you get to this in Mar? if not, we will move it to next month.

**Comment by tomayac** [comment]
> @tomayac - will you get to this in Mar? if not, we will move it to next month.

Since I have some other things in the pipeline that have higher priority and are time-critical, please move this to next month.

**Comment by JohnRiv** [comment]
Just wanted to say I know this would be super useful for developers, so I hope to see an article available on this topic soon 😃

**Comment by tomayac** [comment]
The current milestone target is May 31.

**Comment by tomayac** [comment]
@kaycebasques I re-open this. The stale bot was busy, while I was on vacation. Thanks!

**Comment by tomayac** [comment]
`backlog++`  🤡 Activity

**Comment by tomayac** [comment]
Re-opening.

**Comment by tomayac** [comment]
Active, active, this issue is so active!

**Comment by tomayac** [comment]
Re-opening.

**Comment by tomayac** [comment]
Keep, please

**Comment by tomayac** [comment]
\o/

**Comment by tomayac** [comment]
Meeep

**Comment by tomayac** [comment]
Active

**Comment by tomayac** [comment]
Active

**Comment by stopmotio** [comment]
Weird question: Why did you not put the "accepted" label on sooner? Looks like stalebot was really adamant, haha.

**Comment by tomayac** [comment]
In theory it's meant to be used by the eng team only, see the description in https://github.com/GoogleChrome/web.dev/labels.

**Comment by tomayac** [comment]
I'm closing this for now, since whatever we publish might be misread like a recipe for success, which is not the message we want to send.
