### ISSUE TITLE
Firebase hosting config

### ISSUE THREAD

**Issue by farah** [GoogleChrome/web.dev#2147]
Hey guys,

First off thanks for open sourcing this site. It looks great. I have two quick questions:
1. Is there any reason why you guys are using netlify for hosting and not one of Googles own hosting services?  Like firebase hosting?

2. Could someone help me convert the netlify.toml config to a firebase.json config? I spent a whole day  trying to get it to work but am unable to.

netlify.toml
```
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200
  force = false
```

firebase.json (attempt)

```
{
  "hosting": {
    "public": "dist",
    "rewrites": [ {
      "source": "**",
      "destination": "/en/:splat*",
    }],
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
}

```

**Comment by robdodson** [comment]
Hi there,

We only use netlify for staging pull requests, we don't use it for hosting.

I'm not familiar enough with firebase's setup to know how to convert. But I don't know if they use "splat". That might be a netlify or toml keyword.
