### ISSUE TITLE
content: Update Next.js web.dev guide to use prefetch, not preload

### ISSUE THREAD

**Issue by housseindjirdeh** [GoogleChrome/web.dev#2152]
### What page(s) need to be updated?

https://web.dev/route-prefetching-in-nextjs/

### Why is this update needed?

Next.js changed how they prefetch routes. They use `<link rel="prefetch">` now instead of `<link rel="preload">`

### What's the deadline?

Feb 21st.

#### Is it a hard deadline?

Nope.

**Comment by carolrivero** [comment]
@housseindjirdeh - friendly nudge on this one. You indicated a deadline of Feb 21. Is this still a valid request? If so, what is the new deadline?  If we don't hear back within 48 hours, we''ll move this to the Icebox (won't work on it in 6 months) Thanks.
