### ISSUE TITLE
It's hard to find the tags from the homepage

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChrome/web.dev#2159]
I love looking at the content based on tags. I would love to 

1) discover all the tags more easily - https://web.dev/tags/ 404's. I would love to get a list of the tags if possible.
2) See tags linked to from the homepage (low pri), but if https://web.dev/tags/ doesn't 404 then it would be nice to make it more discoverable.

**Comment by robdodson** [comment]
I was wondering if we could leverage the search field a bit more as well. Algolia has a notion of tags and we can include that with the json we send to them for each article.

Also like the idea of making /tags/ display all the tags somehow. Might need a pretty design for it...

**Comment by robdodson** [comment]
Assigning to @MichaelSolati to look into creating a /tags landing page as a start.
