### ISSUE TITLE
Need lint test for updated field

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#2175]
**Is your feature request related to a problem? Please describe.**
I've noticed a number of posts have been updated, but the person forgot to update the `updated` field in the post YAML. 

**Describe the solution you'd like**
Can we have a lint test that shows a warning if the post was updated but the `updated` field was not changed?

It should only be a gentle warning, so that if you fix a typo or something minor that doesn't deserve an actual update, it's not a hard requirement

**Additional context**
We have a script on [WebFu](https://github.com/google/WebFundamentals/blob/master/gulp-tasks/wfUpdatedOn.js) that will do this automatically, but it ALWAYS updates the field, even for minor updates, which isn't exactly ideal.

**Comment by robdodson** [comment]
Merging into #1959
