### ISSUE TITLE
content: Add citations and fix dubious claim in /promote-install/

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2194]
### What page(s) need to be updated?

https://web.dev/promote-install/

### Why is this update needed?

See https://github.com/GoogleChrome/web.dev/pull/2178#issuecomment-588551877

**Comment by petele** [comment]
@b1tr0t wrote the article originally and may have more context or data that we can use for citations.

**Comment by kaycebasques** [comment]
More context: https://github.com/GoogleChrome/web.dev/pull/2178#issuecomment-589776491

**Comment by jpmedley** [comment]
@petele @kaycebasques Did this need to stay open?
