### ISSUE TITLE
non-canonical pages with i18n

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/web.dev#2204]
All content can now be accessed at both:

https://web.dev/en/about/
https://web.dev/about/

And we don't have any `rel="canonical"` tags.

**Comment by mfranzke** [comment]
@MichaelSolati I can't find the `rel="canonical"` tags being rendered on the website (like e.g. the homepage https://web.dev/ or https://web.dev/contact-picker/) at all - before opening an issue for that, is there (a known and unknown to me) reason that for, like e.g. that the code change out of this ticket hasn't made it to PROD so far?
