### ISSUE TITLE
content: conversion measurement [2020-10-14]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2218]
* [draft](https://docs.google.com/document/d/1Z5Wv28QkMNx1awkw-SNETm1TEQL6SoVQZ9WqLKpEgAo/edit#)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/EnJN80pWl34)

**Comment by samdutton** [comment]
The Privacy Sandbox posts are on hold, but the intention is still to publish.

**Comment by samdutton** [comment]
This post is on hold at present. Feel free to close if necessary.

**Comment by maudnals** [comment]
Will do, thanks!

**Comment by jpmedley** [comment]
This got an [Intent to Experiment yesterday](https://groups.google.com/a/chromium.org/g/blink-dev/c/Ib9-tDFitns/m/Sm9RXTNaBwAJ), which means it is probably starting an origin trial in Chrome 87. Do you all need any help getting this into a PR?

**Comment by maudnals** [comment]
Thanks @jpmedley, we're awaiting cross-functional reviews. No PR yet, since I must have the reviews in, first. I'm hoping to have them in this week. FYI the feature implementers are aware of this.

**Comment by jpmedley** [comment]
@maudnals Are the cross-functional reviews in?

**Comment by kaycebasques** [comment]
@jpmedley I reviewed the first draft and can review the PR
