### ISSUE TITLE
content: Font loading optimizations in Chrome 82 (Publish Date: Mar 25)

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2221]
Author: @housseindjirdeh 
Stakeholders: @petele 
Hard Deadline: 2020 March 25

**Comment by kaycebasques** [comment]
@housseindjirdeh is this on track?

**Comment by kaycebasques** [comment]
@housseindjirdeh it seems like this is Chrome 82 Beta related which has a hard deadline of March 25. If you can't work on it you should let @jpmedley so that he can find someone else to work on it otherwise he might be forced to write the content himself under a lot of pressure and tight deadline.

**Comment by jpmedley** [comment]
Can I get some clarification. Houssein's Docs draft has some minor issues from me, but I basically told him he was ready for markdown conversion.

Does that status here mean it's been done, or its ready to do?

**Comment by carolrivero** [comment]
@jpmedley - if you're asking about what the "markdown conversion" pipeline means --> It is for holding issues that are waiting to merge.

**Comment by jpmedley** [comment]
That is what I was asking. What status should this be?

**Comment by carolrivero** [comment]
if you decide it's ready for markdown conversion, it should be in the markdown conversion pipeline (in the Zenhub board)

**Comment by carolrivero** [comment]
Next step: @housseindjirdeh - please create the PR if this needs to launch on Mar 25. Thx.
