### ISSUE TITLE
Author image not appearing on codelab

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#2225]
**Describe the bug**
Author image is not appearing on https://web.dev/codelab-make-installable/ Instead it appears to be serving `src="/images/authors/.jpg"`

**To Reproduce**
1. Go to https://web.dev/codelab-make-installable/

**Expected behavior**
See my face

**Screenshots**
Broken image where my avatar should be.

**Comment by robdodson** [comment]
Hm I do see your face:

![image](https://user-images.githubusercontent.com/1066253/75278922-9053c300-57bf-11ea-9ada-ed57b0aa5e95.png)

Can you try doing a hard refresh? We _did_ fix a bug related to this recently (within the last week or so).

**Comment by petele** [comment]
Seems working now, I swear it wasn't working yesterday when I filed this. :(
