### ISSUE TITLE
Standardize on Fugu or Capabilities tag for associated posts

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#2227]
Our current Fugu/Capabilities content is inconsistently tagged with either `fugu` or `capabilities`. We should standardize on only one tag. 

For example, see the [contact picker](https://raw.githubusercontent.com/GoogleChrome/web.dev/master/src/site/content/en/blog/contact-picker/index.md) post, which is tagged with both `fugu` and `capabilities`, where as other posts are just `fugu`, or just `capabilities`.

I recommend choose and tag everything under **`capabilities`** but am open to opposing views.

CC @jpmedley @tomayac @robdodson @kaycebasques

**Comment by jpmedley** [comment]
Several weeks ago, I made sure that all fugu articles had both tags. (I will double-check that.)

Until we have redirects we need both. 

Tags serve the same function in an online documentation set as an index in a book. In a book you would write something like this:

fugu
    see capabilities

The point of this is that we don't know which word the reader has in their head. Until we can redirect from fugu to capabilities the only way to account for someone knowing the name fugu, but not capabilities is to use both.

**Comment by petele** [comment]
Though tags only show up on the bottom of each page, so if we only list one, then there will be less opportunity for people to see the other tag.

To address the concern about redirects, we could easily set those up in _redirects.yaml.

**Comment by robdodson** [comment]
+1 to unifying on one tag. I mentioned something similar [in this PR](https://github.com/GoogleChrome/web.dev/pull/2212#issuecomment-590543385). Since we haven't had the tags feature for very long, it may make sense to go all in on `capabilities` since (I think) that's the public term y'all want folks to use right?

**Comment by tomayac** [comment]
> [I]t may make sense to go all in on capabilities since (I think) that's the public term y'all want folks to use right?

Do we, though? https://web.dev/fugu-status/

**Comment by jpmedley** [comment]
This is the problem. Fugu has gotten out. We shouldn't make things hard to find just because its more convenient for us.

**Comment by tomayac** [comment]
Just for the record, the unwritten decision seems to have been for us to just add both tags, `"capabilities"` and `"fugu"`.

**Comment by jpmedley** [comment]
Tags, like indexes before them, are not about the terms we want to push. They are about the terms that are already in people's heads. We need both because the name 'Fugu' got out.

**Comment by petele** [comment]
I made the decision to standardize on `capabilities`, and add `fugu` to the description for the capabilities tag page. Fugu isn't an official name, and we shouldn't be pro-actively using it when possible.
