### ISSUE TITLE
Content review for "Identify resources loaded from the network"

### ISSUE THREAD

**Issue by alankent** [GoogleChrome/web.dev#223]
The following is feedback for the page: .../reliable/identify-resources-via-network-panel. Overall I was able to follow the page and complete the task - the following is mainly grammatical improvements.

* “You’re” -> “you are”, “what’s” -> “what is” -- I was taught to avoid contractions in written documents. Contractions are only for speech.
* “Subject to all kinds of dark forces” -- I get wary of phrases like “dark forces” as it is hard to keep a consistent tone across all content.
* “A few small CSS files” -- Should this have a comma?
* “might not be starting to load” -- “might not start to load”? Not sure, but the "be" sounded funny to me. Page could do with a general grammatical scrub from someone who is gooder at English than me.
* “Note: Advanced techniques outside the scope of this guide, like the `[<link rel="preload">](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content)`, add a twist” -- I assume the text in square brackets is meant to be the link text - markdown seems to have failed here.
* I find the page structure a little confusing - e.g. the “Know what you load” section is generic advice, “Know when you load” is generic advice, but “The Name and Type columns help with the what” dives immediately into concrete details. I think needs a transition sentence. E.g. “Now that we understand what we are looking for, how do we use Chrome’s DevTools to understand the what and when?” To make the transition from generic to specific.
* “The answer to what’s loading is a total of four URLs…” - maybe add “in the above example” for clarity? (It is not *always* 4 URLs.)
* “The last few characters of the URL's path, following the period (e.g. "css"), are known as the URL's extension.” - this sentence is at the end of a paragraph, but I think should be the first sentence in the following paragraph.
* “The URL extension generally tell you what type of resource...” -- I suggest "The URL’s extension generally tells you." (apostrophe and plural)
* “For example, v2.html is a document; main.css is a stylesheet.” -- Not sure why a semicolon instead of just a comma. Also “.css” is not in the same font as “main”.
* “The Waterfall column helps with the when” -- with this section, again the text jumps directly in. My understanding of the correct way to write documents is you should be able to read the text without the headings present and it should read fluently. The text here I think assumes the heading is part of the text and so sets the context for the content. It comes across jarring as a result.
* The “Return to all guides” button at the bottom of the page leaves me on the current page. I was also expecting to see a NEXT link to the first step of lesson 2.

**Comment by robdodson** [comment]
@jeffposnick related issue if you have time to take a look at this one as well. I think the two issues I tagged you on are the only ones we currently have related to the reliable content.
