### ISSUE TITLE
Update PWA icon text

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#2234]
I was wondering if we could revise the text in the add manifest post to be less Chrome specific?

@tomayac suggested documenting what we did in https://github.com/GoogleChrome/web.dev/pull/2197

@tomayac would you be ok owning this task?

**Comment by tomayac** [comment]
Reassigning to @petele after internal discussion.

**Comment by tomayac** [comment]
Ping @petele.

**Comment by tomayac** [comment]
@petele Do you still consider this? Or is this fine to stay closed?
