### ISSUE TITLE
Fix Inconsistencies in tags

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#2239]
**Describe the bug**
I found the following tag inconsistencies in web.dev articles. These are tags for the same idea or concept that are rendered differently in different articles. Here are inconsistencies I've found so far.

* progressive-web-apps and "Progressive Web Apps"
* case-study, "Case Study", and "case study"
* "Performance" and "performance"

**Comment by robdodson** [comment]
I believe this specific issue is fixed now. But we still need to do #2240.
