### ISSUE TITLE
Lint tags for consistency

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#2240]
**Is your feature request related to a problem? Please describe.**
Tags are inconsistent across posts as demonstrated by #2239. 

**Describe the solution you'd like**
We should create a canonical list in a single location and lint all posts agains that list. It should be some place where new tags can be added to the list in the same PR as an article that may need it. 

**Describe alternatives you've considered**
Human could grep for variations of tags when they create content PRs. The consistency of this approach is only as good as a human's ability to think of alternative spellings.

**Comment by jpmedley** [comment]
@kaycebasques @robdodson Resolving inconsistent tags requires reading some portion of every document that contains said tag. This problem potentially grows every time a new article is written. This means that unlike most other feature requests, the cost of solving this grows with time. This needs to be prioritized.

**Comment by robdodson** [comment]
> We should create a canonical list in a single location and lint all posts agains that list.

I think there's two parts to this:

1. [postTags.js](https://github.com/GoogleChrome/web.dev/blob/master/src/site/_data/postTags.js) is our canonical list of tags. If someone puts a tag on their post and it's not already in that .js file then the tag won't show up on the site.
1. we don't currently lint against that list, but that would be a nice thing to add. I should probably just bit the bullet and try to land my yaml linter stuff that I wrote.

One thing I would like to avoid is folks adding lots of new tags to postTags.js file. In some CMS's the cost of adding a tag is quite low, but in ours it's (kinda) high. For ever tag in postTags.js we will generate a landing page in /tags/ and we'll generate an RSS feed for that tag (in case folks want to follow the topic). So for every tag that gets added we're creating a minimum of two new files in the `dist` output. IMO it's best to keep the tags pretty coarse grained for now and if folks seem to be having problems finding what they want then we can consider adding more fine grained tags.

cc @kaycebasques @MichaelSolati for their thoughts.

**Comment by jpmedley** [comment]
>One thing I would like to avoid is folks adding lots of new tags to postTags.js file. In some CMS's the cost of adding a tag is quite low, but in ours it's (kinda) high. For ever tag in postTags.js we will generate a landing page in /tags/ and we'll generate an RSS feed for that tag (in case folks want to follow the topic). So for every tag that gets added we're creating a minimum of two new files in the dist output. 

I wish I had thought about that before now. (I apologize.) Long-term that's a sticky wicket. If the tag list doesn't grow with the content, its usefulness declines over time.
