### ISSUE TITLE
Block quotes are missing a quote

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#2241]
**Describe the bug**
Block quotes are formatted with a Material icon in the shape of quotes. Only opening quotes are currently shown.

**To Reproduce**

Follow [this link](https://web.dev/image-support-for-async-clipboard/#security) to view the problem live. I've added a screen capture below.

**Expected behavior**
I expect to see bot opening and closing quotation marks instead of just opening quotation marks.

**Screenshots**
![image](https://user-images.githubusercontent.com/8204171/75388285-8d2d0580-5899-11ea-8d5d-d608910f84b5.png)

**Comment by robdodson** [comment]
Going to close for now as this isn't a case where the code is running incorrectly, but instead that we have made a stylistic choice to only show the opening quote.
