### ISSUE TITLE
content: color-scheme [Mar 31]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2265]
Deadline: 2020 Mar 31 (Soft)

**Comment by carolrivero** [comment]
@tomayac please provide an update. thx.

**Comment by jpmedley** [comment]
This shipped in Chrome 81. I would think the Chrome 82 material would come ahead of this.

Here's the [commit in Omaha Proxy](https://storage.googleapis.com/chromium-find-releases-static/3d7.html#3d7a78f579dd910f44a264d361d71fbab9035bfa) showing the landing of this feature. If you would all like, I'll show you some time how I found this and what it means.

**Comment by tomayac** [comment]
> @tomayac please provide an update. thx.

Sorry for the delayed reply; I'm just back from a vacation, but this is on my radar for the initial deadline March 31.

**Comment by kaycebasques** [comment]
@tomayac are you working on this? Does this still need to be published by Mar 31?

**Comment by tomayac** [comment]
This is WIP. The deadline would still be nice to respect, but nothing these days is obligatory of course.

**Comment by kaycebasques** [comment]
Cool, I'll push this back to a target of Apr 30 just because I can't tell how far along you are in the drafting process and you don't seem to have a hard deadline to meet and we're starting to get COVID-19-related work popping into the timeline. Please link me to a draft when you have one.

**Comment by tomayac** [comment]
> Cool, I'll push this back to a target of Apr 30

@kaycebasques Yuck, this is actually close to the finish line: https://github.com/GoogleChrome/web.dev/blob/color-scheme/src/site/content/en/blog/color-scheme/index.md. I'll have a last go tomorrow and deliver as promised on March 31. I'd appreciate if we could still get it out in the current round.

**Comment by kaycebasques** [comment]
I'll review it but please understand that it's not just a matter of you sending a PR and then us automatically approving it - we need time to review all content PRs

Our content lifecycle is documented here: https://sites.google.com/corp/google.com/webdev-hub/content/content-lifecycle
