### ISSUE TITLE
content: WebSocketStream [Publish Date: March 25]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2266]
Deadline: 2020 March 25 (Soft)

@tomayac please make sure to mention at the top of the article that no other browsers have given public signals about this API. [Example](https://deploy-preview-2235--web-dev-staging.netlify.com/snap-after-layout/#interoperability).

**Comment by carolrivero** [comment]
@tomayac - please provide an update on your draft. This is currently in the Mar deadline.

**Comment by jpmedley** [comment]
This is shipping in Chrome 82. The deadline is March 25 and it is hard.

**Comment by tomayac** [comment]
> @tomayac - please provide an update on your draft. This is currently in the Mar deadline.

Sorry for the delayed reply; I'm just back from a vacation, but this is on my radar for the *updated hard deadline* March 25.

**Comment by kaycebasques** [comment]
@tomayac are you still working on this? Is the deadline still accurate?

**Comment by tomayac** [comment]
Yes, this is WIP.

**Comment by jpmedley** [comment]
@tomayac Obviously this no longer needs to be done by today, but I've so far been unable to get an exact date for the 83 beta. Please assume that it will come at any time and treat this article as high. priority.

**Comment by tomayac** [comment]
I knew this wasn't due today anymore and put out some other fires, but am nevertheless working on it again as I'm responding here and am treating this as high prio.
