### ISSUE TITLE
We should have an Authors collection

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChrome/web.dev#2275]
**Is your feature request related to a problem? Please describe.**
I wanted to see a complete list of authors on the site, yet https://web.dev/authors/ 404's

**Describe the solution you'd like**
That page should have all of our authors on the site.

**Comment by jpmedley** [comment]
You should probably add some sorting options to this, especially as the site ages. Imagine clicking through several pages of one-time contributors to get to get to Jeff or Pete. (I'd hope there would be a search, but there are multiple reasons someone might have trouble with the spelling of a name.) Somebody who left might appear higher in a count sort than someone who is still here, but producing more recent articles.

I could describe other scenarios, but I think you get the point.

**Comment by MichaelSolati** [comment]
@jpmedley probably could/should but for now just having the page would be good, I think I also need to look into an issue with algolia indexing (#2347) so author search can be added then.
