### ISSUE TITLE
Non-blog content is showing up on staging versions of blog index page

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2285]
**Describe the bug**

https://deploy-preview-2235--web-dev-staging.netlify.com/blog/ is showing PWA content, such as this *Provide a custom install experience* page:

![image](https://user-images.githubusercontent.com/4713486/75910038-04b2e580-5e02-11ea-9bdf-148876e68bb4.png)

Note that this issue **does not** seem to occur in production

**To Reproduce**

1. Go to the `/blog` page on a staging server

**Expected behavior**

Only content under `src/site/content/<language>/blog/` is shown on `https://deploy-preview-XXXX--web-dev-staging.netlify.com/blog/`

**Comment by robdodson** [comment]
oh yeah that's kind of working as intended. If you click on the post it should have a banner saying 'this post is a draft'. I wanted people to have a way to share draft content with others but I can also see why this is bad...
