### ISSUE TITLE
Shouldnt the percentages make 100% in lighthouse 6?

### ISSUE THREAD

**Issue by schroef** [GoogleChrome/web.dev#2286]
### What page(s) need to be updated?
https://web.dev/performance-scoring/
https://github.com/GoogleChrome/web.dev/blob/master/src/site/content/en/lighthouse-performance/performance-scoring/index.md

### Why is this update needed?
Ive noticed in some cases the percentage either dont make up 100% or exceed 100%.
Lighthouse 6 for instance i 95% in total and Light 3-4 is 103%
Its a kind of embarassing to see this is all about a test of 0 to 100 and then the numbers dont match up?

### What's the deadline?
No deadline, would be good if its corrected

#### Is it a hard deadline?
No

**Comment by kaycebasques** [comment]
Good catch, @schroef!

@paulirish the LH6 section adds up to 95%

![image](https://user-images.githubusercontent.com/4713486/76564851-a2dc2680-6466-11ea-8af1-953759a53f68.png)

3 & 4 adds up to 103%

![image](https://user-images.githubusercontent.com/4713486/76564902-bbe4d780-6466-11ea-9640-86a641267149.png)

2 adds up to 99%

![image](https://user-images.githubusercontent.com/4713486/76564940-d0c16b00-6466-11ea-836f-0cceec30988e.png)

**Comment by schroef** [comment]
Was going bananas over the numbers ;)

**Comment by connorjclark** [comment]
this is source of truth: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/config/default-config.js#L392-L397

CLS is missing in that draft table
