### ISSUE TITLE
content: getInstalledRelatedApps update for m81/82 [Publish Date: Mar 17]

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#2289]
New functionality - testing for installed PWAs

**Comment by carolrivero** [comment]
Please advise on next steps for this one.

**Comment by petele** [comment]
Information is in the linked PR.

**Comment by carolrivero** [comment]
Thanks, Pete. Do you have a date in mind?

**Comment by petele** [comment]
It'll need to go out with Chrome 81 - so March 17th.
