### ISSUE TITLE
Big sign-in button doesn't go away on /measure

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#2291]
**To Reproduce**
1. (If you are signed out) Go to web.dev/measure.
2. Click on the large sign-in button in the center of the screen.
3. Complete sign-in flow.

**Expected behavior**
The big sign-in button disappears.

**Screenshots**
![image](https://user-images.githubusercontent.com/1066253/75935786-1d88be80-5e35-11ea-9719-35aea3a588d4.png)

**Comment by robdodson** [comment]
@samthor are you cool taking a look at this one?

**Comment by samthor** [comment]
This is a dup of #2272
