### ISSUE TITLE
content: Native lazyload fallback sample cuts of LazySizes Ajax capability

### ISSUE THREAD

**Issue by magnogaspar** [GoogleChrome/web.dev#2292]
### What page(s) need to be updated?
https://web.dev/native-lazy-loading/

### Why is this update needed?
Lazysizes has the ability to detect and apply lazyload in elements added dinamically after page load, but the sample code on the web.dev only applies the right attributes in elements already in page. The sample code is expecting that the same validation it does, be done twice when any element is added and it can be easily fixed adding event listeners instead of firing the attribute update on page load.

### What's the deadline?
No deadline.

#### Is it a hard deadline?
No.

**Comment by kaycebasques** [comment]
@housseindjirdeh please review this feedback and leave a comment on whether you plan to update this content based on this feedback or not.

**Comment by housseindjirdeh** [comment]
Thanks for filing this @magnogaspar.

I'm not sure if I understand, is the [cross-browser snippet](https://web.dev/native-lazy-loading/#how-do-i-handle-browsers-that-don't-yet-support-native-lazy-loading) in the article not working for your use case?

If you're referring to the demo link not working as it should in Firefox/Safari, I've [fixed it](https://github.com/GoogleChrome/web.dev/pull/1016#issuecomment-604734773) and the changes should be live soon!

**Comment by kaycebasques** [comment]
@magnogaspar if Houssein's change didn't address your concern please re-open this issue
