### ISSUE TITLE
Overflowing tables on mobile can look like they only have one column.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#2300]
Visible on [this post](https://web.dev/nfc/) if you enable mobile emulation.

![image](https://user-images.githubusercontent.com/1066253/76002441-769b3580-5ebb-11ea-8906-1b0f2fb24749.png)

Maybe we should set a max-width on `th` of 30vw or something like that. That would allow the 2nd heading to be in the viewport.

**Comment by Malvoz** [comment]
Removing the fixed `min-width` of tables:
https://github.com/GoogleChrome/web.dev/blob/e589da3280dad1db78abfb58c313c12ecc2b03f6/src/styles/generic/_tables.scss#L22

results in:

<img width="250" src="https://user-images.githubusercontent.com/26493779/78040390-a7ae3f00-736f-11ea-9e29-f93fc8c71324.png">
