### ISSUE TITLE
Page title is "undefined" for the handbook

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/web.dev#2302]
**Describe the bug**
Page title looks like a bug as it's not related to the page content and represents typical js error syntax. 

**To Reproduce**
1. Go to https://web.dev/handbook/
2. Look at the page title in your browser

**Expected behavior**
Page title is "Handbook"

**Screenshots**
![image](https://user-images.githubusercontent.com/1134620/76012010-6a6aa480-5eca-11ea-96b1-d8de6d9b8191.png)

**Comment by samthor** [comment]
I should probably fix this by setting any page with a blank title to "web.dev".

**Comment by samthor** [comment]
This is fixed now.
