### ISSUE TITLE
web.dev landing page is 404 after PWA installed

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/web.dev#2311]
**Describe the bug**
The landing page of the web.dev PWA is 404 if not visited previously when user launches web.dev PWA.

**To Reproduce**
1. Visit a post web.dev page such as https://web.dev/nfc
2. Add "web.dev" to your home screen or desktop
3. Later on, when you don't have internet connection anymore, launch previously installed web.dev PWA to continue reading article

**Expected behavior**
User should be able to catch up with articles that were previously cached.

**Screenshots**
![image](https://user-images.githubusercontent.com/634478/76076037-585a3600-5f9e-11ea-8cde-9f871b552447.png)

**Comment by beaufortfrancois** [comment]
Maybe Chrome should not prompt user to install web.dev as start_url does not reply with a 200 as raised in Audits panel.

![image](https://user-images.githubusercontent.com/634478/76076267-d0286080-5f9e-11ea-85ee-58035c5d19ea.png)

**Comment by samthor** [comment]
Ah, this is the "we don't cache the first page's partial" problem, since it's just served as real HTML.

I'll do a quick fix.

**Comment by samthor** [comment]
Actually, we also don't cache /. I think this is the real issue. I'll fix that too.

**Comment by beaufortfrancois** [comment]
For info, here's the chromium counterpart bugs:

https://bugs.chromium.org/p/chromium/issues/detail?id=965802#c14 
https://bugs.chromium.org/p/chromium/issues/detail?id=1059925
