### ISSUE TITLE
content: imgproxy

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2322]
* Authors
  * @khempenius 
* Deadline: 2020 June 1 (Soft)
* [Draft](https://docs.google.com/document/d/1fw9sxx3bqw0ljgyYdCAkznQ7rhafCWq_AHA2r3vMhNk/edit?usp=sharing)
* Related content
  * https://web.dev/image-cdns
* Stakeholders
  * @philipwalton

**Comment by khempenius** [comment]
Not stale.
