### ISSUE TITLE
content: ad speed codelab

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2324]
* Authors
  * @gernberg  
* Deadline: 2020 April 9 (Soft)
* [Draft](https://docs.google.com/document/d/1-GCHyWWdxIXc8JkAPWa-9Fq0g6Zq8VCQ7bwmO2EReA0/edit)
* Stakeholders
  * @thebengeu  
  * @philipwalton

**Comment by carolrivero** [comment]
@kaycebasques - this should be in the Sprint Backlog pipeline if it's going to be in the sprint ending in April 30

**Comment by kaycebasques** [comment]
Looks like the next step is for @gernberg to incorporate the feedback
