### ISSUE TITLE
content: variable fonts

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2329]
* Authors
  * @mustafa-x    
* Deadline: 2020 April 9 (Soft)
* Drafts
  * https://developers.google.com/web/fundamentals/design-and-ux/typography/variable-fonts

**Comment by jpmedley** [comment]
@mustafa-x,

@tomayac has a script for converting WebFu articles to web.dev articles.

**Comment by carolrivero** [comment]
@kaycebasques - Since this is set for the Apr milestone, this should move to the "Sprint Backlog" pipeline.

**Comment by mustafa-x** [comment]
Will we need an extra step for edits, the current WebFu is being updated. OR will all of the edit be done here?

**Comment by jpmedley** [comment]
They will be done here. We'll add a banner or a redirect to the WebFu article.

**Comment by kaycebasques** [comment]
@mustafa-x recommended workflow:

1. use the script to convert the markdown
1. submit pr with the unedited original content from webfu
1. push up commits (so that I can see how the article is changing if needed)
1. once the article is updated we'll do a review here in the PR

**Comment by kaycebasques** [comment]
@mustafa-x are you still going to work on this or should I defer it to later?

**Comment by tomayac** [comment]
I have kick-started this now. See https://github.com/GoogleChrome/web.dev/pull/2844.
