### ISSUE TITLE
content: trusted types [Publish Date:  Mar 25]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2330]
* Authors
  * @koto
* Deadline: 2020 March 25 (**Hard**)
* Drafts
  * https://docs.google.com/document/d/1ZbZgc-4-FgKxyN1koL43holj-E-zZR0x5jeaZGWBS2w/edit
* Related content
  * https://developers.google.com/web/updates/2019/02/trusted-types
* Stakeholders
  * @jpmedley

**Comment by carolrivero** [comment]
@kaycebasques - who should be in the Assignee field?

**Comment by jpmedley** [comment]
The origin trial for this ended in December in Chrome 78. That means soonish is better than later, but the deadline is not hard. Furthermore, with a deadline of March 26, it could get swamped by articles related to the beta release.

**Comment by koto** [comment]
We wanted to have the content available for authors as the feature reaches
Beta, or even before that. From our pov that would make it a hard deadline
I guess.

**Comment by jpmedley** [comment]
I have no information saying this is related to any upcoming beta. You're saying it's in 82 beta?

**Comment by jpmedley** [comment]
For things shipping in beta, I recommend the day before as the hard deadline. Dates are usually taken to mean "some time before the end of that day. To link to an article from the beta release post, the article needs to be live before the beta release post. The beta release post can go live as early as 11:00 a.m. Pacific on beta release day. So I always make the deadline the day before.

**Comment by koto** [comment]
That sounds good. I'll make sure the content is reviewed and submitted
before that new deadline.

**Comment by jpmedley** [comment]
I appreciate that.

**Comment by jpmedley** [comment]
@koto Is your draft ready for review?

**Comment by koto** [comment]
Hey, sorry, WFH delays. I'll submit the PR tomorrow, now finishing the text.

**Comment by koto** [comment]
Ready in #2372.
