### ISSUE TITLE
Status in Chromium field not visible

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#2335]
[This status entry](https://www.chromestatus.com/features/6068482055602176) is for an item that ended its origin trial in Chrome 80 and became stable in Chrome 81. When I edit, I can see the milestone fields, but I cannot see the drop down that lets me change its status from "Origin trial" to "Enabled by default." That field should be right above the milestone boxes. As shown below, it is not.

![image](https://user-images.githubusercontent.com/8204171/76333291-a7f67580-62ae-11ea-8a19-03b315f273be.png)

**Comment by robdodson** [comment]
@jpmedley did you mean to file this on chromestatus?

**Comment by jpmedley** [comment]
Yes I did.
