### ISSUE TITLE
Index virtual pages

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/web.dev#2347]
**Is your feature request related to a problem? Please describe.**
We want to return e.g. Author pages inside Algolia search results, weighted highly.

**Describe the solution you'd like**
We need to plumb these through to the Algolia indexer, which currently _only_ indexes Markdown nodes (see #2247).

**Describe alternatives you've considered**
Not doing this. Or indexing author data in articles.

**Comment by robdodson** [comment]
keep this one open bot friend

**Comment by samthor** [comment]
I haven't looked at the code; is this solved because we're stealing the Algolia indexable content at a different point now (in the transforms)?

(If so, I'm actually concerned(?) that we're indexing every single numbered page of content that has many pages).

**Comment by robdodson** [comment]
> I haven't looked at the code; is this solved because we're stealing the Algolia indexable content at a different point now (in the transforms)?

I don't think we're using transforms for any of the algolia stuff. The `algolia-posts.js` collection powers algolia.njk and seems like it only grabs stuff with the `post` or `pathItem` tag.

I did notice this line which seems like it could be updated:
https://github.com/GoogleChrome/web.dev/blob/master/src/site/_collections/algolia-posts.js#L47

eleventy has a [`getFilteredByTags()` function](https://www.11ty.dev/docs/collections/#getfilteredbytags(-tagname-secondtagname-[...]-)) now
