### ISSUE TITLE
Images not loading inside posts.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#2392]
**Describe the bug**
Image links are showing up as broken on initial load. Refreshing the page will load the images.

**To Reproduce**
1. Go to https://web.dev/blog
2. Click on an article that has images
3. Notice broken images

![image](https://user-images.githubusercontent.com/1066253/77083269-779f8d00-69ba-11ea-8d3d-6d5d2bb024b7.png)

3. Refresh the page. See that image loads.

**Comment by robdodson** [comment]
![image](https://user-images.githubusercontent.com/1066253/77084717-92730100-69bc-11ea-802e-ad71a6336b7c.png)

When I navigate from the blog to the web share target post the above it's requesting `localhost:8080/blog/wst-send.png` which is the wrong directory. It should be fetching the image from `/workbox-share-targets/`

**Comment by devnook** [comment]
It looks like when router.listen(swapContent) happens, the router is still on old url (blog)

**Comment by robdodson** [comment]
yeah, `updateDom()` in `loader.js` seems to be running against the previous path not the current one.

**Comment by devnook** [comment]
Side effect: we record wrong path in analytics too for these pageviews

**Comment by devnook** [comment]
The reason is that updateDom is called first here https://github.com/GoogleChrome/web.dev/blob/master/src/lib/loader.js#L169 and update to the location href only happend in the "ready" function afterwards: https://github.com/GoogleChrome/web.dev/blob/master/src/lib/loader.js#L172
