### ISSUE TITLE
Web.dev links are broken in Firefox

### ISSUE THREAD

**Issue by jamesgecko** [GoogleChrome/web.dev#2395]
**Describe the bug**

When using Firefox, clicking on a link on the main `https://web.dev` page just reloads the page.

On initial page load, I see the console error, `InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.`. Clicking on a link logs the console error `TypeError: content.querySelector is not a function`.

I'm on macOS 10.15.3
This happens in Firefox 74.0 (64-bit), as well as Firefox Developer Edition 75.0b5. It also happens in Private Window mode with all extensions disabled.
The site version logged to the console is `web.dev v202003191520`

**To Reproduce**
1. Go to https://web.dev/
2. Click on any article. I clicked on _Customize media notifications and playback controls with the Media Session API_.

**Expected behavior**
The selected article loads. I am on https://web.dev/media-session/

**Actual behavior**
The page reloads. I am on https://web.dev

**Screenshots**
![Screen Shot 2020-03-19 at 4 03 52 PM](https://user-images.githubusercontent.com/44252/77110175-85293700-69fb-11ea-92a4-0512d248ab10.png)

**Comment by robdodson** [comment]
thanks james, taking a look now
