### ISSUE TITLE
Author Image Hosting

### ISSUE THREAD

**Issue by MichaelSolati** [GoogleChrome/web.dev#2404]
I don't want to boil the ocean, but it feels like we're working around the fact that the PostCard and PathCard elements aren't very extensible. I see this happening on the podcast page as well (https://github.com/GoogleChrome/web.dev/pull/2368#issuecomment-601855753).

I'm concerned about us shipping workarounds that create technical debt in the long run. I keep wondering if we should instead look at writing an [eleventy transform](https://www.11ty.dev/docs/config/#transforms) that converts _all_ image paths to be from the CDN if it's in the prod environment and hopefully our components wouldn't need to manually call and request CDN paths.

Also I noticed the images that are being served on the authors page seem to have an intrinsic size of 192 x 192 which seems quite small. Basically they all look pixelated and I'm assuming that's because we never asked anyone to upload an image in these larger dimensions. So I'm kind of wondering if we want to go with this design at all. We could omit the hero image and go with their name and try and work in the smaller profile image..? Or we'll want to ask everyone to upload a higher res headshot.

_Originally posted by @robdodson in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM5NTkzNzgxOQ==/pull_request_review_threads/reply_

**Comment by robdodson** [comment]
Here's what the chromeos folks are doing: https://github.com/chromeos/static-site-scaffold-modules/tree/master/modules/eleventy-plugin-local-respimg

**Comment by robdodson** [comment]
> I'm concerned about us shipping workarounds that create technical debt in the long run. I keep wondering if we should instead look at writing an eleventy transform that converts all image paths to be from the CDN if it's in the prod environment and hopefully our components wouldn't need to manually call and request CDN paths.

We did this! So we can close this ticket.
