### ISSUE TITLE
content: Add iOS and Windows 10 Media Session API images

### ISSUE THREAD

**Issue by Poopooracoocoo** [GoogleChrome/web.dev#2405]
### What page(s) need to be updated?

Provide a list of URLs.
https://web.dev/media-session/

### Why is this update needed?
The article is awesome! I'd just like some images of the System Media Transport Controls (on Windows) and the Control Center (on iOS and iPadOS). It's particularly important for people who don't know why adding media metadata is important. 

Windows example:
https://visualstudiomagazine.com/articles/2016/10/01/universal-windows-platform-media-app.aspx
![image](https://user-images.githubusercontent.com/51363864/77247713-cd5c8980-6c87-11ea-9a5f-f67ba9f1f045.png)
iOS example: 
https://support.apple.com/en-us/HT202769
![image](https://user-images.githubusercontent.com/51363864/77247723-df3e2c80-6c87-11ea-95e7-8e10040d1a31.png)

**Comment by kaycebasques** [comment]
@beaufortfrancois WDYT?

**Comment by beaufortfrancois** [comment]
The Media Session is not implemented *yet* on iOS/macOS: https://bugs.webkit.org/show_bug.cgi?id=145411. The only thing that is "working" is mentioned in the article:

> The title attribute of the media HTML element is used in the "Now playing" macOS widget.

Regarding Windows, it is "just" another place where metadata are shown when integrated properly in the OS. I could have shown Linux integration as well for instance. I've decided to show one example per type of platform: desktop, mobile, wearable.

![image](https://user-images.githubusercontent.com/634478/79201532-81d96d80-7e38-11ea-941b-e46b783a9292.png)

**Comment by Poopooracoocoo** [comment]
@beaufortfrancois but a lot more people have experience with the Windows media controls than the GNOME notification and KDE media control panel (can't quite remember the Linux experience). I totally understand that adding a Windows screenshot would ruin the ~flow\~ but it helps people understand what it is and can convince people to add metadata to their media. When people adjust their volume on Windows they see the controls. I'm sure you knew all this and came to your decision though.

**Comment by beaufortfrancois** [comment]
I guess we could add an "extra" screenshot in https://web.dev/media-session/#let-users-control-what's-playing. @mounirlamouri What do you think?

If that looks good to you, can you share a Windows media controls screenshot of https://googlechrome.github.io/samples/media-session/video.html to me so that I can add it?

**Comment by Poopooracoocoo** [comment]
btw the wicg explainer is pretty neat https://github.com/w3c/mediasession/blob/master/explainer.md 
Only problem is that it's outdated and missing the GMC.

**Comment by Poopooracoocoo** [comment]
this ain't stale

**Comment by Poopooracoocoo** [comment]
once again, i believe this isn't stale.

**Comment by Poopooracoocoo** [comment]
tiktok might be bought by ms o.o
yeah i don't have anything else to say

**Comment by beaufortfrancois** [comment]
I'm adding a Windows 10 screenshot of a media notification powered by the Media Session API to this article at https://github.com/GoogleChrome/web.dev/pull/3701
Note that I don't think we should add an iOS/iPadOS screenshot though as the Media Session API is not implemented on Safari yet. I'll be happy to add one when it is supported though.
