### ISSUE TITLE
An http-cache guide has wrong sample project

### ISSUE THREAD

**Issue by grigory-bogush** [GoogleChrome/web.dev#2409]
**Describe the bug**
An http caching project seems to be missing, with a service worker project shown instead

**To Reproduce**
Go to: https://web.dev/codelab-http-cache/

**Expected behavior**
Expect to access http caching project

**Comment by kaycebasques** [comment]
@jeffposnick which Glitch is your HTTP caching codelab supposed to link to?

**Comment by jeffposnick** [comment]
I think this was changed inadvertently in https://github.com/GoogleChrome/web.dev/commit/69bd63933e23da85e61afcbaae4f20edaca17fe6#diff-44af09f80a24de7c7978dd78ef341e41L10

It should be `glitch: configure-cache-control`
