### ISSUE TITLE
content: content delivery networks [2020 May 29]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2416]
* Author: @khempenius 
* [Draft](https://docs.google.com/document/d/1JNSpYoIBEBHAUUPdT5Tvxok-sjM3GUjyJl1skfpwfOY/edit?ts=5eaafe81)
* Deadline: Apr 30 (Soft)
* next step: @khempenius to address feedback from 7/29

**Comment by khempenius** [comment]
@kaycebasques FYI I just updated the title on this. The CDN content would be completely separate from the image CDN content (despite the overlapping names, "CDNs" and "image CDNs" are fairly different beasts).

**Comment by kaycebasques** [comment]
Ooooooooh OK that's why you submitted the new content form. Yes I understand the difference between the 2 I thought you were just adding more guidance to the image CDN stuff.

**Comment by kaycebasques** [comment]
@khempenius please link me to a draft when you have one - I pushed the target publish date to Apr 30 just as a soft target (can potentially get it out sooner)

**Comment by kaycebasques** [comment]
Katie confirmed with me that she's still working on this.

**Comment by kaycebasques** [comment]
@khempenius draft LGTM. Please submit a PR.

**Comment by kaycebasques** [comment]
Just checked the Google Doc draft. Looks like others have commented on it and Katie is incorporating the feedback.

**Comment by kaycebasques** [comment]
@khempenius it looks like this is waiting on you to address Ilya's and Yoav's feedback

**Comment by kaycebasques** [comment]
@khempenius it looks like you've addressed the feedback and updated the doc. Are you ready for another technical writer review?

**Comment by khempenius** [comment]
@kaycebasques Not yet. I'll update this thread when it is.
