### ISSUE TITLE
Wrong link in "A long cache lifetime can speed up repeat visits to your page" section of Lighthouse report.

### ISSUE THREAD

**Issue by victorwestmann** [GoogleChrome/web.dev#2422]
#### Provide the steps to reproduce
1. Run LH on <www.profissaocanada.com>
1. Go to the Developer Tools
1. Run the Lighthouse tool to generate the report
1. Go to the Performance section.
1. Go to the section "Serve static assets with an efficient cache policy" (10 resources found)
1. Expand it and click on the learn more from the text "A long cache lifetime can speed up repeat visits to your page. Learn more."
1. You just went to an INVALID URL.
  

#### What is the current behavior?
When you follow the steps described above you go to an invalid URL
(`https://web.dev/uses-long-cache-ttl?utm_source=lighthouse&utm_medium=devtools///////////////////`)

#### What is the expected behavior?
It should take the visitor to a valid URL
(`https://web.dev/uses-long-cache-ttl`)

#### Environment Information
* Affected Channels: 
* Lighthouse version: 5.7.1
* Chrome version: Version 83.0.4094.0 (Official Build) canary (64-bit)
* Node.js version:
* Operating System: Windows 10 Version 1903 (OS Build 18362.657)

**Related issues**

**Comment by robdodson** [comment]
Assigning as a p0 because it seems like all LH links may be broken by this?

**Comment by robdodson** [comment]
I think this is caused by our service worker.

- Open an incognito window
- Got to web.dev/lcp? (it will work, and replace the ? with a /)
- In the address bar, replace the trailing slash with a ? and press enter
- It will fail
