### ISSUE TITLE
Safari: Change cookie banner to use cookies instead of localStorage

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#2434]
Per this article: https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/
Safari will be wiping all localStorage after seven days so we'll need to switch our cookie banner over to using an actual cookie. Boo.

**Comment by samthor** [comment]
So using an actual cookie (via `document.cookie`) doesn't get us out of this; it also has a 7-day expiry.

Using a cookie that's set by a HTTP response is allowed. I think we just have to bounce the response around and perhaps add an endpoint which sets a long-lived cookie (so "OK" does a fetch which... etc).

Orthogonally, I wonder how Firebase does its login, and whether this will expire after 7 days too. But I agree that cookie banners are so annoying that it's low-hanging fruit to get it right, even if the user gets signed out or whatever.
