### ISSUE TITLE
content: Fix "cross-browser support" section for signed exchanges

### ISSUE THREAD

**Issue by twifkak** [GoogleChrome/web.dev#2452]
### What page(s) need to be updated?

https://web.dev/how-to-set-up-signed-http-exchanges/

### Why is this update needed?

The "cross-browser support" section says that Chrome is the only supporting browser. However, some other browsers based on the Chromium rendering engine also render SXG. I would file a PR, but I'm not sure how you'd prefer this be worded.

### What's the deadline?

No deadline.

**Comment by twifkak** [comment]
cc @kumagi

**Comment by kumagi** [comment]
Oh, I didn't know that, nice catch.

**Comment by kaycebasques** [comment]
@kumagi & @twifkak do we know exactly which Chromium-based browsers support it?

**Comment by twifkak** [comment]
I've tested that Chrome, Edge, Opera, Opera Mini, and Brave support it. I haven't tested others; there's kind of an infinite list of Chromium browsers. :P

**Comment by jpmedley** [comment]
I would say include Samsung and Edge. Even MDN doesn't include the less common Chromium forks.

**Comment by twifkak** [comment]
Okay, thanks. Tested that it works on Samsung Internet. I'll send a PR.
