### ISSUE TITLE
content: performance.measureMemory [Apr 15]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2475]
* [Draft](https://docs.google.com/document/d/1eytQ-wgg4iekCo46NzcXMyh08shzqSR5TvNvpBKpI1Y/edit)
* Authors
  * ulan@
* Stakeholders
  * domenic@
* Deadline: Apr 15 (Hard)

**Comment by jpmedley** [comment]
Guys, this scheduled to ship in Chrome 83, which would give it a hard deadline of April 15.

**Comment by kaycebasques** [comment]
status: I reviewed the doc and instructed Ulan to incorporate my feedback and then submit a PR (unless further discussion in the Google Doc is needed)

**Comment by kaycebasques** [comment]
@jpmedley I updated the target publish date, thank you

**Comment by jpmedley** [comment]
This feature is mentioned in the beta release post, making April 15 a hard deadline.
