### ISSUE TITLE
/lean mastheads have too much margin on mobile.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#2483]
![image](https://user-images.githubusercontent.com/1066253/78062192-23de5d80-7343-11ea-96c5-5e909eba9a21.png)

Removing the margin on the h1 seems to make things look better.

**Comment by mum-never-proud** [comment]
@robdodson can i raise a PR for this?

**Comment by robdodson** [comment]
@mum-never-proud sure!

**Comment by mum-never-proud** [comment]
@robdodson I guess this has already been fixed? or am I looking at the wrong page

![web dev_](https://user-images.githubusercontent.com/58324637/79294477-e73e6480-7ef3-11ea-80c3-0ec7d5c0a872.png)

**Comment by robdodson** [comment]
Sorry, click on the card and you should see it. web.dev/discoverable

**Comment by mum-never-proud** [comment]
sorry was stuck with other work, but still, I think instead of removing margin we should set a lower margin, removing margin reduces around 8px in mobile view and 12px in a tab view, but still, I think we should lower the margin-top further 

let me know your thoughts on this @robdodson

**Comment by robdodson** [comment]
@mum-never-proud thanks for working on this. I needed to get in there and work on it as well to fix something for an upcoming section so I think it's fixed now.
