### ISSUE TITLE
Service worker can prevent redirects from working

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#2488]
**Describe the bug**
If a post accidentally goes live and we remove it and ship a redirect the service worker will cause the user to see a 404 instead of the redirect.

These are the steps I observed today:

- We accidentally shipped /digging-into-the-privacy-sandbox/
- We moved the post to `_drafts` and add a redirect to `_redirects.yaml`
- If you visit the site in a new incognito window and type https://web.dev/digging-into-the-privacy-sandbox/ into the url bar you'll get the redirect.
- However, if you first visit http://web.dev and then type https://web.dev/digging-into-the-privacy-sandbox/ into the URL bar you'll get a 404.

**Comment by samthor** [comment]
This example is no longer useful as we did actually ship that article.

There's still an issue, but we need a new example :)
