### ISSUE TITLE
content: 'same-site' & 'same-origin' [apr 13]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2500]
[draft](https://docs.google.com/document/d/1bprwXaQM6ZD5K8iEMnx-n-iKpNeCTSp3pabRor2YUVI/edit#)

deadline: apr 13 (hard)

**Comment by kaycebasques** [comment]
Current status seems to be that @agektmr is still incorporating feedback.

**Comment by agektmr** [comment]
Yes, I'm hoping I can finalize the article on Monday so @rowan-m and @samdutton can give it LGTM.

**Comment by agektmr** [comment]
The draft is ready for review by a tech writer.
https://docs.google.com/document/d/1bprwXaQM6ZD5K8iEMnx-n-iKpNeCTSp3pabRor2YUVI/edit#
@kaycebasques

**Comment by kaycebasques** [comment]
OK I'll review it.
