### ISSUE TITLE
Add markdown-it-figure to site

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#2517]
**Is your feature request related to a problem? Please describe.**
It's a bit of a chore to have to write out `<figure><img><figcaption>` on the site. Instead, let's use the [chromeos.dev's markdown-it-figure plugin](https://github.com/chromeos/static-site-scaffold-modules/tree/master/modules/markdown-it-figure).

Note that [figcaption is not a replacement for alt text](https://www.scottohara.me/blog/2019/01/21/how-do-you-figure.html#a-figcaption-is-not-a-substitute-for-alt-text) so if we go back and update existing content we should use the syntax provided by the markdown-it-figure plugin to do both caption and alt text.

```
[Caption](/url/to/image.png [Alt Text]) - Advanced figure, including a figure number and alt text for image. Outputs figure id="figure-1234"><img src="/images/foo.png" alt="Alt Text"/><figcaption><p><span class="figure-id">1234: </span>Caption</p></figcaption></figure>
```

**Comment by samthor** [comment]
My criticism of this module:

* no clear way to specify width/height
* no implicit `<video>` support, e.g. for mp4s

To be fair, Markdown by default doesn't do these either.

**Comment by robdodson** [comment]
> no clear way to specify width/height

yeah i think they're solving this with their follow up responsive images transform and maybe we should as well. Otherwise we're going to lose points for cumulative layout shift.
