### ISSUE TITLE
Status "draft: true" name is at odds with how it's used

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#2519]
Recently an article was [accidentally merged](https://github.com/GoogleChrome/web.dev/pull/2515/files) with `draft: true` field set. The writer in question was under the impression that this was needed to correctly indicate the state of the article. However this designation is redundant with the fact that the article is unapproved and unmerged. It would seem to be unneeded for this use.

What the flag is intended to do is hide a *finished* article publishing on the site. A finished article is definitely not a draft. 

I propose that `draft: true` be changed to something like `hidden: true` or `unpublished: true`. I care less about what this field is called than I do about clearing the ambiguity around it.

If `draft: true` has another use case I've overlooked, then I further propose taking some action to address that case rather than maintaining the status quo.

**Comment by kaycebasques** [comment]
I'm fine with the change but it seems like a fair of amount of work for not much gain. If @robdodson also agrees to the change and you want to submit the PR, @jpmedley, then I think that would be the path forward. I'm doubtful that Rob's team would prioritize fixing the bug but that's just my take and I'll let Rob agree or disagree with that. So if no one agrees to work on this we should close it.

**Comment by kaycebasques** [comment]
@jpmedley in the example that you mentioned, did the author intend for the article to get published and they were confused about why it wasn't showing up?

**Comment by jpmedley** [comment]
That is correct.

**Comment by jpmedley** [comment]
Sure, you could make sure this is clear in the handbook. I'd do that anyway. If the handbook is the solution to every problem, especially one's we could automate, it will get bigger, while the number of people who have completely internalized it gets smaller.

**Comment by robdodson** [comment]
Based on [this comment](https://github.com/GoogleChrome/web.dev/pull/2481#issuecomment-610812910) it seems that Thomas was confused as to who was supposed to actually change the flag. It seems like he may have added the original `draft: true` out of an abundance of caution (not wanting the post to get published too early) but it's just as likely he would have done the same thing if the property was named `unpublished: true`.

FWIW, I don't think it's necessarily wrong to put `draft: true` on an article while you're still working on it in a PR. It provides an extra level of protection in case it does, for whatever reason, get accidentally merged. It also seems like the person submitting the PR should be the one to remove `draft: true` as they're ultimately the one deciding when the article should go live.

A reviewer can give them a heads up, and we can probably add a linter warning of some kind to flag that `draft: true` is set.

**Comment by jpmedley** [comment]
I'm not sure I agree with all of that, but I agree with adding to the linter warning.
