### ISSUE TITLE
checkbox misalignment on

### ISSUE THREAD

**Issue by hwikyounglee** [GoogleChrome/web.dev#2521]
Only tested on macOS,

https://services.google.com/fb/forms/web-dev-subscribe/

**Expected behavior**
Checkbox before the label, and both aligned in one line
**Screenshots**
![image](https://user-images.githubusercontent.com/7561395/78602710-c1d29c00-780b-11ea-85c5-5428308b03eb.png)
Checkbox comes after the label, and they're stacked in two lines

Thanks for looking into it!

**Comment by robdodson** [comment]
Hoping to fix this by switching to our own custom form. Going to technically assign to Michael who is working on the new form.

**Comment by MichaelSolati** [comment]
@robdodson does it make sense to close this, or wait until we remove the `/subscribe` route?

**Comment by robdodson** [comment]
i think we should leave it open until we switch over to the new page
