### ISSUE TITLE
Redirect from /pwa/ fails

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#2529]
**Describe the bug**
Redirects are failing.

**To Reproduce**
1. Go to https://web.dev/pwa/ 
2. Go to https://web.dev/pwa 

**Expected behavior**
Both: Redirect to https://web.dev/progressive-web-apps/

**Actual behavior**
1. User sees a 404 page (does not work)
2. Works as expected and user is redirect to https://web.dev/progressive-web-apps/

Redirects are set-up at https://github.com/GoogleChrome/web.dev/blob/master/src/site/content/en/_redirects.yaml#L168

**Comment by kaycebasques** [comment]
@robdodson any idea why this is borking?

**Comment by robdodson** [comment]
It looks like the service worker is messing up. Try the above links in new incognito windows.

**Comment by robdodson** [comment]
same bug as #2488 I believe
