### ISSUE TITLE
WebNFC content suggestion: No current peer-to-peer support

### ISSUE THREAD

**Issue by mrj** [GoogleChrome/web.dev#2538]
Please add a note to the introduction of the [WebNFC docs](https://github.com/GoogleChrome/web.dev/blob/master/src/site/content/en/blog/nfc/index.md) that only passive NFC tags are currently supported. Peer-to-peer NFC, for example phones exchanging information, isn't supported.

**Comment by kaycebasques** [comment]
@beaufortfrancois WDYT?

**Comment by beaufortfrancois** [comment]
Thanks for filing this feedback!

P2P is indeed not supported in Web NFC because it only allows interaction with NFC tags. See https://web.dev/nfc/#terminology

> An NFC tag is a passive NFC device, meaning that is powered by magnetic induction when an active NFC device (.e.g a phone) is in proximity. NFC tags come in many forms and fashions, as stickers, credit cards, arm wrists, etc.

I'll update https://web.dev/nfc/#use-cases to be more clear.

**Comment by beaufortfrancois** [comment]
And I've opened https://github.com/GoogleChrome/web.dev/pull/2584 to fix it.
