### ISSUE TITLE
Typo: "File a bug" in a footer

### ISSUE THREAD

**Issue by aTastyCookie** [GoogleChrome/web.dev#2544]
**Describe the bug**
Typo? Or an easter egg? :)

**To Reproduce**
1. Go to https://web.dev/
2. Scroll down to the footer
3. See typo "File a bug"

**Expected behavior**
Change "File a bug" to "Found a bug?"

**Screenshots**
- https://gyazo.com/366ca6f6ee00a458e5860bdf0bda342c

**Comment by kaycebasques** [comment]
Thanks for the report. "File a bug" sounds OK to me. Lots of sites use the phrase: https://www.google.com/search?q=%22file+a+bug%22&oq=%22file+a+bug%22&aqs=chrome..69i57j0l3j69i64l3j69i61.1967j0j7&sourceid=chrome&ie=UTF-8
