### ISSUE TITLE
Switch to type:module in package.json

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/web.dev#2582]
**Is your feature request related to a problem? Please describe.**
It's hard to test parts of our build system, or have shared logic, since we can't import across different package types.

**Describe the solution you'd like**
Switch to ESM for the project. We should use `"type": "module"` in our 'package.json'.

**Describe alternatives you've considered**
* We could have tests that run both CJS _and_ ESM.
* We could use Rollup's support, but this would only allow CJS => ESM, and not the other way around.

**Comment by robdodson** [comment]
I'm cool with it if eleventy doesn't barf

**Comment by samthor** [comment]
There's only.... oh, 394 references to `require()`. How hard could the fix be?!

**Comment by samthor** [comment]
It seems like there's a [workaround](https://github.com/11ty/eleventy/issues/836#issuecomment-606691848) to make this work now but that it's officially unsupported. So maybe this goes on the backburner for a bit.

**Comment by samthor** [comment]
noooo keep open beep bot

**Comment by robdodson** [comment]
@samthor you can add the `accepted` label to make the bot ignore stuff.
