### ISSUE TITLE
OGP doesn't pickup double quote

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#2627]
**Describe the bug**
When posting a link on Twitter, quote is stripped form the page title
For example, [`Understanding "same-site" and "same-origin"`](https://web.dev/same-site-same-origin/) is displayed as `Understanding`.
https://twitter.com/agektmr/status/1251404023342587906

This is probably caused by the OGP not being html-escaped.

**Comment by robdodson** [comment]
@MichaelSolati did you make some changes here recently?

**Comment by MichaelSolati** [comment]
Interesting, I worked on something _related_  to resolve `'s being in the title (issue #1993, pr #2369). I can take a look at this today though.
