### ISSUE TITLE
content: Storage on the web [May 20 2020]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2634]
hard deadline: no

author: @petele 

draft: https://docs.google.com/document/d/1f-iDXQwrBJWsfAkc8n1w8EEfu--IxjDTRqSBLBkqjkg/edit#

related content: 

* https://developers.google.com/web/fundamentals/instant-and-offline/web-storage/offline-for-pwa
* https://www.html5rocks.com/en/tutorials/offline/quota-research/

**Comment by petele** [comment]
@jpmedley - please assign back to me when you've completed your review.

**Comment by jpmedley** [comment]
Really clean! Nice work.

**Comment by petele** [comment]
Awesome - thanks for the fast turn around Joe!
