### ISSUE TITLE
You will lost all your tabs if you try to open PWA before Chrome.

### ISSUE THREAD

**Issue by aguadotzn** [GoogleChrome/web.dev#2648]
**Describe the bug**
You will lose all your tabs if you open a **PWA** (that you already had in your local) _before_ opening Chrome. Let's make an example: I have 5 tabs open in chrome, I close the browser, I open a **PWA** (because I have _x app_ as a PWA) and you will lose those 5 tabs in Chrome. 

**To Reproduce**
1. Go to Chrome, open some tabs (in your configurations make sure is checked 'Open everything as it was before closing')
2. Close Chrome
3. Open your favourite **PWA** (In my case I have Google Maps as a desktop app)
4. Try to open the **PWA** and you will lose all your tabs. 

**Expected behavior**
I expect to open the **PWA** and to open my tabs. Both.

**Screenshots**
<img width="125" alt="Example" src="https://user-images.githubusercontent.com/22575055/79961368-e8890780-8486-11ea-94d5-c3cf0690f8d9.png">

**Chrome**
81.0.4044.113 (Build oficial) (64 bits)

**OS**
MacOS Catalina (10.15)

**Comment by robdodson** [comment]
Hey @aguadotzn, this bug sounds like it may fit better over on http://crbug.com/. That's where folks can file bugs against Chrome itself. This repo is primarily for the documentation that appears on web.dev. Going to close this issue if that's ok.

**Comment by aguadotzn** [comment]
Ok, @robdodson ! Thanks for the information!
