### ISSUE TITLE
Discoverable content QA: Guide page (write descriptive titles...)

### ISSUE THREAD

**Issue by kusler** [GoogleChrome/web.dev#266]
- [x] The 'Measure,' 'Optimize,' 'Monitor' is getting lost (in this page and in previous)
- [x] **BROKEN LINKS**: 'Add tags to head of the page' and 'Add descriptive link text'
- [x] No 'How to Fix' link for 'Document does not have a title element' (should have "----" if no doc)
- [ ] 'HTML Improvements Report' - I think there is an opportunity throughout the site to use iconography or some sort of a call out to showcase that a tool is being recommended. 
- [ ] Are we purposefully not saying '...for more tips on how to optimize for search in Google?' Because we're only pointing to Google Search resources, not Bing, etc.
- [ ]** BROKEN LINK**: 'make a delicious maple bar with Mary!' and 'Get cooking… here'
- [x] The table with Good and Bad under 'Add descriptive link text' seems very big (way too much padding)
- [x] Format links so that they're easy to spot (by whom - users or search engines? If it is for search engines, how do you do that?)
- [x] The link 'Use links wisely' doesn't take you to a site that is titled that. So, it seems to be countering the very purpose of the guide by not using descriptive text.
- [x] Verify seems weird… Text might be better if it had a second sentence saying 'If you've failed any of them, then….________?'
- [ ] Again, no pictures, illustrations, color...

**Comment by robdodson** [comment]
Going to close as it looks like everything is accounted for except illustrations. Moving those requests over to #533
