### ISSUE TITLE
Origin mixup in `en/blog/get-installed-related-apps` ?

### ISSUE THREAD

**Issue by asankah** [GoogleChrome/web.dev#2663]
**Describe the bug**

In https://web.dev/get-installed-related-apps/#relationship-web, the description says:

> A page can check if its PWA is installed, even if it is outside the scope of the PWA. For instance, `www.example.com` wants to check if its PWA served from `app.example.com` is installed. Or a page under /about/ to check if the PWA served from /app/ is already installed.

However, the example given is:

```json
// Served from https://app.example.com/.well-known/assetlinks.json
{
  "relation": ["delegate_permission/common.query_webapk"],
  "target": {
    "namespace": "web",
    "site": "https://example.com/manifest.json"
  }
}
```

Per https://wicg.github.io/get-installed-related-apps/spec/#installed-app-relatedurls, this should only allow `example.com` to check PWAs installed from `app.example.com`. This shouldn't be granting that privilege to `www.example.com` as the example lays out.

I suggest modifying the JSON snippet to specify `https://www.example.com/manifest.json` as the target site instead of `https://example.com/manifest.json`

**Comment by robdodson** [comment]
@petele would you mind taking this one?

**Comment by petele** [comment]
Yep - will handle!
