### ISSUE TITLE
Use maskable icons in the manifest.webmanifest

### ISSUE THREAD

**Issue by abdonrd** [GoogleChrome/web.dev#2666]
**Is your feature request related to a problem? Please describe.**

Not using the maskable icons.

https://github.com/GoogleChrome/web.dev/blob/2b55278cc97f60dbb26e3bbb0a249f7b19c08023/src/misc/manifest.webmanifest#L9-L20

**Describe the solution you'd like**

Follow the https://web.dev/maskable-icon/ to add it.

**Comment by abdonrd** [comment]
Still waiting response! 😄

**Comment by abdonrd** [comment]
Still waiting response! 😄

**Comment by abdonrd** [comment]
Still waiting response! 😄

**Comment by abdonrd** [comment]
Still waiting response! 😄

**Comment by samthor** [comment]
If you'd like to help, feel free to submit a PR :)
