### ISSUE TITLE
test fails against master branch

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#2668]
**Describe the bug**
`npm run test` return the following error.
```
  1) site
       _transforms
         service-worker-partials
           "after each" hook for "converts a string of html to a partial and writes it to disk":
     Error: ENOTEMPTY: directory not empty, rmdir '.tmp'
```

**To Reproduce**
1. Clone the repo
2. `npm ci`
3. `npm run test`

**Comment by samthor** [comment]
I can't repro this. It might happen if you're before v12.10.0, as `{recursive: true}` was only added then.

I added a note to the [README](https://github.com/GoogleChrome/web.dev/blob/master/README.md#building-the-site-).
