### ISSUE TITLE
Fails when a preferred lang is set in cookie

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#2669]
**Describe the bug**
When a `preferred_lang` is set in cookie, "Internal Server Error" will be returned.

**To Reproduce**
1. Using DevTools, manually set `preferred_lang` as `en` as a cookie.
2. Load https://web.dev/

**Expected behavior**
Switch to the preferred language.

**Comment by devnook** [comment]
@agektmr I think it might not be safe to use raw cookie like this, without escaping it: https://github.com/GoogleChrome/web.dev/commit/d3fb770e9349e874bff5eb8269324aff0a490647#diff-29f5f081d97c7ff61a6c5b73d177f495R59

This is why we only accepted supported languages, sanitized with locale.isSupportedLocale call (en+pl for now). See https://github.com/GoogleChrome/web.dev/commit/d3fb770e9349e874bff5eb8269324aff0a490647#diff-29f5f081d97c7ff61a6c5b73d177f495R56

@samthor wdyt?

**Comment by agektmr** [comment]
I agree escaping it makes sense (unless it is already escaped somewhere else). As long as it is sanitized I think it's ok though.
