### ISSUE TITLE
content: How to define your install strategy [May 22 2020]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2685]
* [Draft](https://docs.google.com/document/d/1RLA6cDjtYriOBghhaPh_RMq2CIPHDKogexQ9dfVe4RQ/edit#)
* Author: @petele 
* Reviewer: @jpmedley

**Comment by petele** [comment]
@jpmedley - please assign back to me when you've completed your review.

**Comment by jpmedley** [comment]
It generally looks pretty good. I left a few comments and suggestions.
