### ISSUE TITLE
content: Persistent Storage (TBD) [May 22 2020]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2686]
* [Draft](https://docs.google.com/document/d/1dGABhaRA1-A5B5ig8OwOMx1uByMqUglz6xqxiVOPrL8/edit)
* Author: @petele 
* Reviewer: @jpmedley

**Comment by petele** [comment]
@jpmedley - please assign back to me when you've completed your review.

**Comment by jpmedley** [comment]
Congratulations on another clean draft. I only had a few nits.
