### ISSUE TITLE
content: Profiling Web Audio Apps in Chrome [May 2 2020]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2700]
* Author: Hongchan
* Reviewer: @jpmedley 
* [Draft](https://docs.google.com/document/d/1A3AnN_-fh7aoyTBeUMTvJvLfQb68QSd913sZgndr46Y/edit)

**Comment by hoch** [comment]
cc/ @hoch

**Comment by hoch** [comment]
Thanks everyone for the review! It was a pleasant process. :)
