### ISSUE TITLE
content: system-ui on macOS: bug fixes and variable fonts [Fri May 29 2020]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2702]
* Author: @argyleink 
* Stakeholders: @drott
* [Draft](https://docs.google.com/document/d/15Sjk7bYm69C1LD97ESRpvoBY8DbAfFvtSAhdHbuK-pY)

**Comment by argyleink** [comment]
draft started, co-author notified

**Comment by argyleink** [comment]
ready for a first review! 

it's undergone a few major rearrangements and outline changes, and i think it's in an overall good spot for technical help and notes. I'd appreciate helping us iron out the SKIA details so we arent so verbose. Thanks!

**Comment by argyleink** [comment]
ping: still ready for a first review

**Comment by drott** [comment]
Timing wise, since the fix went out in M83, this article would be good to be published soon to still coincide / link with the M83 stable release that just went out.
