### ISSUE TITLE
content: Streams [May 31 2020]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2703]
* Author: @tomayac 
* Draft: TODO

**Comment by tomayac** [comment]
This should also talk about [`fetch()` upload streaming](https://www.chromestatus.com/feature/5274139738767360).

**Comment by kaycebasques** [comment]
@tomayac is this now a duplicate of #3525?

**Comment by tomayac** [comment]
> @tomayac is this now a duplicate of #3525?

It's not. #3525 is about new content for a new type of stream: the fetch upload stream. This article (#2703) will be a one-stop shop for all kinds of streams, including the new one.

**Comment by tomayac** [comment]
Activity 💃

**Comment by tomayac** [comment]
Active

**Comment by tomayac** [comment]
Active

**Comment by tomayac** [comment]
Active
