### ISSUE TITLE
content: https://web.dev/measure/ needs to talk about RUM

### ISSUE THREAD

**Issue by npm1** [GoogleChrome/web.dev#2739]
https://web.dev/measure/ is the most prominent performance-related link on web.dev (since it is in the navigation bar). It does not talk at all about RUM performance.

### What page(s) need to be updated?
https://web.dev/measure/

### Why is this update needed?
Measuring performance on real users is more important than measuring performance on the lab. Sure, it is nice to provide the convenience to measure performance in the lab, but the description is "See how well your website performs. Then, get tips to improve your user experience. Sign in to track your progress over time." and it is not clear from it that a big component of performance tracking is missing here.

**Comment by npm1** [comment]
Ping

**Comment by npm1** [comment]
Still not fixed

**Comment by robdodson** [comment]
Hey @npm1. We've had some internal discussions around investing more in the measure tool and that would include pulling in more RUM data. We don't have a timeline for when this will happen (the team is currently heads down working on another site launch) but it is on our radar.

It looks like you're a Googler? If you'd like I'm happy to connect you with our PM. Feel free to shoot me an email.
