### ISSUE TITLE
Page Not Working

### ISSUE THREAD

**Issue by navaranjithsai** [GoogleChrome/web.dev#2766]
**Describe the bug**
Mail subscription page is not working, those text looks like a picture couldn't select ,text boxes , country selection window(drop-down menu), check boxes, everything in that page is dump nothing is # # working. This things happens in normal chrome new tab window but works in incognito tab window.

**To Reproduce**
1. Go to 'web.dev'.
2. Click on 'mail subscription button(on the right bottom button with mail + symbol)'.
3. Scroll down to 'whole page nothing is working in my phone'.

**Expected behavior**

**Screenshots**
I couldn't upload a image or video on it from this page.
@
**Link**
https://services.google.com/fb/forms/web-dev-subscribe/

**Comment by robdodson** [comment]
@navaranjithsai it sounds like the JS is fialing to load on the subscribe form for some folks. We're working on a new form to replace this page so I'm going to close this issue and recommend if other folks are seeing the problem that they use their desktop browser to sign up for now.
