### ISSUE TITLE
Lighthouse test config is unclear

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/web.dev#2789]
**Describe the bug**
I ran a test on /measure that got very poor performance measurements. I'd like to see the test config to get a sense for how much of this is affected by things like network and CPU throttling. However, this info isn't immediately available.

**To Reproduce**
1. Go to https://web.dev/measure/
2. Test a site (eg https://www.nytimes.com)
3. Look for info on the test config
4. Click "View report" ([example report](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.nytimes.com))
5. See "Unknown" network and CPU throttling

**Expected behavior**
Network and CPU throttling should have defined values in the report.

On /measure, I'd expect to see a summary of how the test was configured, including mobile device, effective connection type, and CPU throttling.

**Screenshots**
![image](https://user-images.githubusercontent.com/1120896/81026912-c9588580-8e49-11ea-8525-896006a21a50.png)

![image](https://user-images.githubusercontent.com/1120896/81026892-b47bf200-8e49-11ea-89f8-ee1a539e97e7.png)

**Comment by robdodson** [comment]
it's not much but we do include this at the bottom of the page:

![image](https://user-images.githubusercontent.com/1066253/81033871-058be600-8e4a-11ea-91d4-f5d514d480be.png)

but yeah, we need to do more in this area.

**Comment by rviscomi** [comment]
Ah my brain ignored everything below the report!
