### ISSUE TITLE
content: browser support for "web share"

### ISSUE THREAD

**Issue by mvolkmann** [GoogleChrome/web.dev#2806]
### What page(s) need to be updated?

https://web.dev/web-share/

### Why is this update needed?

It makes no mention of the fact that most popular browsers do not support this yet.

### What's the deadline?

ASAP because people like me waste time trying to use a feature that isn't really ready yet.

**Comment by robdodson** [comment]
@jpmedley @kaycebasques what do y'all think about dropping a link to the MDN table for `navigator.share` into the post?

**Comment by samthor** [comment]
Web Share (according to caniuse) is supported on 50.16% of browsers worldwide right now.

It is new, but just making an observation that more than half of users will see it.

**Comment by mvolkmann** [comment]
Is the information on Web Share at caniuse out of date? See https://caniuse.com/#search=web%20share. It indicates that only Safari and "Chrome for Android" currently support it.

**Comment by jpmedley** [comment]
As far as I can tell Firefox is the only major browser on mobile that doesn't support sharing (and Android WebView, but that's a different issue). I'm looking into whether there are plans for desktop Chromium. There are multiple polyfills available, but I don't know anything about them. I can't tell you either way whether to use them or avoid them.

**Comment by jpmedley** [comment]
I apologize for the delay and for the original error. 

As far as I can determine the MDN and Caniuse data are correct. There are no current plans to implement this on desktop Chromium.
