### ISSUE TITLE
Accessibility: Audit results page

### ISSUE THREAD

**Issue by carolrivero** [GoogleChrome/web.dev#283]
Submitting on behalf of lpalmaro@
On that same audit results page, below the row of screenshots, there is the opportunities section (and the below sections) with expandable elements. With VoiceOver, those are verbalized as "... collapsed, disclosure triangle. you are currently on a disclosure triangle". It's correct to verbalize this as collapsable or expandable, but it's a bit confusing to hear "you are currently on a disclosure triangle". Can you think of any way to make that a bit more intuitive in regards to what's being verbalized?

**Comment by robdodson** [comment]
Hm I'm not sure if this is still part of the design. I don't think we have any expanding/collapsing disclosures anymore. Going to close.
