### ISSUE TITLE
Example in web.dev/codelab-make-installable/  is not working

### ISSUE THREAD

**Issue by supertx2** [GoogleChrome/web.dev#2830]
**Describe the bug**
Inside the example window when the user clicks 'instructions' it will get an error page.

Chrome v81.0.4044.138 without any extension enabled

**To Reproduce**
1. Go to 'https://web.dev/codelab-make-installable/'
2. Click on 'View App' in example window on the right side
3. Click on 'instructions' text

**Expected behavior**
it should show the install prompt.

**Screenshots**
![image](https://user-images.githubusercontent.com/13727650/81424924-93b7e300-914e-11ea-9275-553febe5103f.png)
![image](https://user-images.githubusercontent.com/13727650/81424974-a500ef80-914e-11ea-9908-de8f1c0a61ae.png)

**Comment by jpmedley** [comment]
@petele I'm guessing we need to keep this alive.

**Comment by djhmateer** [comment]
This would be great to get working again.
