### ISSUE TITLE
content: SameSite cookies and checkout [2020-06-07]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2837]
* [draft](https://docs.google.com/document/d/1P3vRF_4iowombkjHclt6hc9WB4CBfK1djGWduXNZOug/edit)
* @rowan-m to incorporate feedback from last round of reviews

**Comment by rowan-m** [comment]
Will get the draft going.

**Comment by kaycebasques** [comment]
@rowan-m it looks like this is waiting on you to incorporate feedback from a round of reviews
