### ISSUE TITLE
content: New Font APIs [2020-06-30]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2839]
* [draft](https://docs.google.com/document/d/1eECkz-Vt94Kqoq_9H1f4rPwFQNyiehZU5W1P0Ta0L7c/edit)

**Comment by jpmedley** [comment]
Thomas is out this week and cannot start this.

**Comment by kaycebasques** [comment]
Do we have a draft for this?

**Comment by tomayac** [comment]
It's in the works. I'll ping the thread once it's review-ready.

**Comment by tomayac** [comment]
A [draft](https://docs.google.com/document/d/1eECkz-Vt94Kqoq_9H1f4rPwFQNyiehZU5W1P0Ta0L7c/edit) is ready for review now. See the [staging link](https://deploy-preview-3615--web-dev-staging.netlify.app/local-fonts/) for a preview.
