### ISSUE TITLE
Accessibility: Audit results page

### ISSUE THREAD

**Issue by carolrivero** [GoogleChrome/web.dev#284]
Submitting on behalf of lpalmaro@
On this same audit results page, I'm noticing that there are the larger numbers indicating the score. On the home page, I hear the nice verbalization of the number in percent with "progress indicator". On this page I just hear the number, then "link" so there isn't much context. Can you add in "progress indicator" and also verbalize the number in percent to make this more meaningful and consistent?

**Comment by robdodson** [comment]
I'm not sure what this is referring to because the circular gauges announce properly. Maybe this was some part of the design we changed during the race to the finish. Going to close.
