### ISSUE TITLE
Accessibility: Focus visibility

### ISSUE THREAD

**Issue by carolrivero** [GoogleChrome/web.dev#285]
Submitting on behalf of lpalmaro@
As a whole, I'm having trouble seeing focus visibility in a lot of areas, in particular on the bottom of the screen where there is white writing on the dark green background, and for the bottom right circular buttons. Would be good to do a pass to see that focus visibility throughout the site is reaching 3:1 ratio against the background. FWIW, I can't tell if I can actually get focus to reach the report error, edit page and view in prod buttons, but I'm assuming these are not going to launch live?

**Comment by robdodson** [comment]
Adding to this that focus states for our flat buttons are low contrast now. This is my mistake, I was fixing focus styles elsewhere and didn't realize it was affecting these buttons.

![image](https://user-images.githubusercontent.com/1066253/48744956-55f39180-ec1e-11e8-8dc8-5ec3d20cdf0f.png)

**Comment by robdodson** [comment]
Should be fixed in my most recent CL. It'll take a while for this to launch on devsite.
