### ISSUE TITLE
content: optimize-cls: mention scroll anchoring

### ISSUE THREAD

**Issue by fabb** [GoogleChrome/web.dev#2855]
### What page(s) need to be updated?

https://web.dev/optimize-cls/

### Why is this update needed?

Scroll anchoring should be mentioned too to reduce CLS. This either applies when the user manually scrolls down, or when the browser navigates to a `#fragment`.
Often scroll anchoring works fine out of the box, but there are cases where manual css intervention is needed.

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor/Guide_to_scroll_anchoring

**Comment by kaycebasques** [comment]
@addyosmani WDYT?

**Comment by kaycebasques** [comment]
@addyosmani @philipwalton is this a practice we should recommend?
