### ISSUE TITLE
Tables shouldn't have a min-width since this causes horizontal overflow

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#2862]
- Seen on: https://web.dev/variable-fonts/#axes-definitions:~:text=Axis%20names%20and%20CSS%20values
- Cause: https://github.com/GoogleChrome/web.dev/blob/5218100bf088a7f36ea0b57ab1ab78298959814e/src/styles/generic/_tables.scss#L32

**Comment by samthor** [comment]
I think Rob had an opinion on this. We're also overriding this on web.dev/live.

**Comment by robdodson** [comment]
happy to take a deeper look at this but as a quick note, all tables should be wrapped in `<div class="w-table-wrapper">` so they can overflow properly.

**Comment by tomayac** [comment]
Turns out this can be closed, since the mentioned article was lacking the wrapper div. Fixed in https://github.com/GoogleChrome/web.dev/pull/2991.
