### ISSUE TITLE
site: Search field shouldn't grow

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#2863]
This scares me and is unexpected. The responsible CSS seems to be here: https://github.com/GoogleChrome/web.dev/blob/95248af2d2f212c816393efbac3d7793492150e9/src/lib/components/Search/_styles.scss#L173-L184

CC: @samdutton who has looked into this, too.

**Comment by samthor** [comment]
What would you suggest? Our current implementation matches developers.google.com. I think the options are:

- remove the resize animation (so it's instant)
- replace small search box with an icon (so it's more like a button press => show large search)
- use small search box and have results appear as if they're rooted in the top right (currently the results appear below the larger, mid-aligned box)

We're not yet ready to have a whole-page search, although that option could be... tap in search box => switch SPA-style to full-screen search.

**Comment by samdutton** [comment]
(Just adding my comments from earlier... Not sure if my suggestions would be possible to implement within the current setup.)

The current design forces your focus to follow what's going on — actually physically moving your head. Goes against the Don't Make Me Think rule :). 

The search input also covers navigation which, again, forces you to think ('Where did the navigation go?')

Also... A search input never needs to be that wide, unless size is used as an unmissable visual indicator that search is available (as on Amazon et al).

I'd prefer if the search input was always shown (you don't need to click anything) and expanded to fit the space between the top navigation and the SIGN IN button:
• Viewport width below 900px: hamburger menu only, search input is always shown, and expands to fit between web.dev logo and SIGN IN button (with nice horizontal margins).  Maybe move the SIGN IN button to the right slightly, so the right padding (whitespace) is equal to the top and bottom padding.
• Viewport width greater than 900px: show the navigation and search.

I built a demo of something similar a while back: https://search-input.glitch.me. We did something similar on https://pie-shop-app.appspot.com.

Would also be good to add search to Analytics, to get field data for changes:
• Search events and goals/funnels: how are people using search (or not)? where are people exiting?
• Queries: support.google.com/analytics/answer/1012264

**Comment by tomayac** [comment]
🤖 Activity

**Comment by samdutton** [comment]
Just realised I never actually responded to this.

The current design forces your focus to follow what's going on — actually
physically moving your head. Goes against the Don't Make Me Think rule :).
The search input also covers navigation which, again, forces you to think
('Where did the navigation go?') Also... A search input never needs to be
that wide, unless size is used as an unmissable visual indicator that
search is available (as on Amazon et al). I'd prefer if the search input
was always shown (you don't need to click anything) and expanded to fit the
space between the top navigation and the SIGN IN button: • Viewport width
below 900px: hamburger menu only, search input is always shown, and expands
to fit between web.dev logo and SIGN IN button (with nice horizontal
margins). Maybe move the SIGN IN button to the right slightly, so the right
padding (whitespace) is equal to the top and bottom padding. • Viewport
width greater than 900px: show the navigation and search. I built a demo of
something similar a while back: search-input.glitch.me. We did something
similar on pie-shop-app.appspot.com. Would also be good to add search to
Analytics: • Search events and goals/funnels: where are people exiting?
• Queries: support.google.com/analytics/answer/1012264

**Comment by tomayac** [comment]
We may want to keep this open… 💃 Activity.

**Comment by tomayac** [comment]
On wide enough viewports, I root for an initially small search field that is always visible (like now), but that grows with the text to a specified max-length. Here's a really [smart solution](https://css-tricks.com/auto-growing-inputs-textareas/#other-ideas) to this challenge.

On narrow viewports, the current behavior seems fine to me.

**Comment by tomayac** [comment]
Active

**Comment by samthor** [comment]
@tomayac I hate to be "that guy" but if you wanted to contribute the change you described on the 28th of July, I think we'd probably accept it.

**Comment by tomayac** [comment]
Active-ish

**Comment by tomayac** [comment]
Active

**Comment by tomayac** [comment]
Alive

**Comment by tomayac** [comment]
This can be closed for good now since the new design is (partly now and eventually fully) live. Thank you!
