### ISSUE TITLE
content: @property: Giving Superpowers to CSS Variables [2020-07-22]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2865]
* [Draft](https://docs.google.com/document/d/1W2N-OLRsl9biFc1EF4cS42WYvAkK1gblKtfw76M0lEY/edit?usp=sharing)
* Author: @una 
* Reviewer: @rachelandrew

**Comment by jpmedley** [comment]
This is finished and scheduled for Chrome 85. This isn't actually needed until late July.

**Comment by kaycebasques** [comment]
@una please let @rachelandrew know when you want an edit (I see that you just invited me to edit the Doc)

**Comment by jpmedley** [comment]
@kaycebasques I've confirmed this is shipping in Chrome 85. It now has a hard deadline of Jul 22.

**Comment by jpmedley** [comment]
How is this coming?

**Comment by una** [comment]
Draft is finished, just tagged @rachelandrew for review

**Comment by una** [comment]
@jpmedley ready for review

**Comment by jpmedley** [comment]
@kaycebasques Who's reviewing this? It looks like Rachel was asked, but the reviewer's list is missing.

**Comment by rachelandrew** [comment]
@jpmedley I did an edit of a Word doc already.

**Comment by jpmedley** [comment]
Is there a PR?
