### ISSUE TITLE
content: Resilient Search Experiences [2020-06-12]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2866]
* [Draft](https://docs.google.com/document/d/1hnB8qqt88fiuvKUJRZ_v5V4fR0Kcquzmd6JWDxtn0oI/edit)
* Authors: @demianrenzulli & @jeffposnick 
* CC: @petele 
* Reviewer: @jpmedley

**Comment by demianrenzulli** [comment]
Currently working on this.

**Comment by demianrenzulli** [comment]
@kaycebasques: note - this article has been broken into two parts a [guide](https://docs.google.com/document/d/15SLsG8aM6PzF35e4YXAml66K3bP-e9hbuFxy1pZjjn8/edit#) and a [codelab](https://docs.google.com/document/d/1PGjNzmAGgKJMvqCl-aHJp6Rg_muBwNdTrt9HtOUKUC0/edit#heading=h.3a73qujlbki7).

Please, let me know if I should create a separate issue for the codelab.
