### ISSUE TITLE
content: Instant Navigation Experience [2020-06-12]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2867]
* [Draft](https://docs.google.com/document/d/1hnB8qqt88fiuvKUJRZ_v5V4fR0Kcquzmd6JWDxtn0oI/edit)
* Authors: @demianrenzulli & @jeffposnick 
* CC: @petele 
* Reviewer: @jpmedley

**Comment by demianrenzulli** [comment]
Currently working on this.
