### ISSUE TITLE
content: App Shell UX with Service Workers and Streams [2020-06-12]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2868]
* [Draft](https://docs.google.com/document/d/1IR0YXEOuZ466iCiegSsGbsSr-vaM-nQX0Ke993_DQu4/edit)
* Authors: @demianrenzulli & @jeffposnick 
* CC: @petele 
* Reviewer: @jpmedley

**Comment by demianrenzulli** [comment]
Currently working on this.
