### ISSUE TITLE
content: Adaptive Loading with Service Workers [2020-06-12]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2869]
* [Draft](https://docs.google.com/document/d/1AE_3FtKPTgw2wSYwU0G8HeKhgJfSMJj0WiSmfPT68f0/edit)
* Authors: @demianrenzulli & @jeffposnick 
* CC: @petele 
* Reviewer: @jpmedley

**Comment by demianrenzulli** [comment]
Currently working on this.
