### ISSUE TITLE
content: 10 modern layouts in 1 line of CSS [2020-06-30]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2871]
* Author: @una 
* Reviewer: @rachelandrew
* [Draft](https://docs.google.com/document/d/1L3MxeJRkdKBNjFDQpgoCxQoKyYe_jZ1tMHLBlrW5WNA/edit)

**Comment by una** [comment]
Article draft: https://docs.google.com/document/d/1PHIZEhKZk0PdlvbYw8Ds5VZvAOSbmmzKhLbrdCLBcLA/edit?usp=sharing

@rachelandrew please review when you have a chance!

**Comment by rachelandrew** [comment]
@una looked at this today in UK time, I noted on the doc the following:

- I made some suggested edits to make this match the style guide in terms of use of second person and the imperative. 
- It needs links to the MDN info for each property, plus links to browser compat info for the later stuff.
- There are a few tech corrections / queries.
- I think your declarations would be much clearer in the context of an entire ruleset with the relevant line highlighted. I changed one to look like that so you can see what I mean.

**Comment by una** [comment]
See PR: #3263 

- Adds links to MDN 
- Updates grammar and structure based on suggestions from @rachelandrew 
- Adds ruleset context

**Comment by una** [comment]
Just a reminder this is going live tomorrow
