### ISSUE TITLE
Demo in Clipboard API article blocked by feature policy

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#2876]
**Describe the bug**
Attempting to use the demo in the article [Image support for the async clipboard API](https://web.dev/image-support-for-async-clipboard/#demo) produces an error stating, "NotAllowedError: Disabled in this document by Feature Policy."

Note that I have stated this occurs on both web.dev and Glitch. This appears to be a problem with Glitch.

**To Reproduce**
1. Go to the demo [on web.dev](https://web.dev/image-support-for-async-clipboard/#demo) or [on Glitch](https://glitch.com/~async-clipboard-api).
2. Click **Copy Chrome Logo**.

The error message appears at the bottom the demo.

**Expected behavior**
An image is copied to the clipboard.

**Screenshots**
To message does not show for long, making it hard to get a screenshot.

**Comment by jpmedley** [comment]
@tomayac I labeled this P0 because I wanted to fork this for raw clipboard and we're running short on time before publication.

@robdodson The impeding feature policy seems to be part of Glitch. Can you please advise on what we need to do?

**Comment by tomayac** [comment]
@jpmedley The demo works just fine if run directly on Glitch: https://async-clipboard-api.glitch.me/. 

<img width="1006" alt="Screen Shot 2020-05-14 at 22 03 20" src="https://user-images.githubusercontent.com/145676/81980356-bf473b80-962e-11ea-9e3b-6138dbf96c89.png">

For running in an iframe, we're dependent on the implementation of https://github.com/w3c/webappsec-feature-policy/issues/322#issuecomment-619276703.

**Comment by robdodson** [comment]
Maybe in the short term we should update the post to link to the glitch instead of embedding it.

**Comment by tomayac** [comment]
> Maybe in the short term we should update the post to link to the glitch instead of embedding it.

Done. It may still work on some versions. Can I get a quick LGTM and can someone merge, please? @kaycebasques @robdodson

**Comment by tomayac** [comment]
Thanks, this was quick!

 :-D
