### ISSUE TITLE
Overlaps subheading by web-header custom element

### ISSUE THREAD

**Issue by sokolovIntterra** [GoogleChrome/web.dev#2882]
**Describe the bug**
Custom element `<web-header>` is overlaps the subheading and the first item in the topic list when you select theme or open link with anchor. For example, if you open this link in chrome [https://web.dev/fast/#introduction](https://web.dev/fast/#introduction) you can't see **"Introduction"** subhead element and **"Why does speed matter?"** link.
I found a bug in Chrome Canary.

**To Reproduce**
1. Go to https://web.dev/fast/
2. Click on any item from "What you'll learn" block
3. See an error

**Expected behavior**
I expect that I'll see subheader **"Introduction"** and first link called **"Why does speed matter?"**

**Screenshots**
![image](https://user-images.githubusercontent.com/46678943/82067319-3df8b300-96d9-11ea-9075-11d7fe41de6d.png)

I think that h2 tag have an "ID" attribute.

**Comment by samthor** [comment]
This is because for some reason this `h3` is set to `display: flex`. The pseudo-`::before` element which extends above the heading isn't placed properly as it naturally goes to the left of the heading, not above it.

**Comment by sokolovIntterra** [comment]
> This is because for some reason this `h3` is set to `display: flex`. The pseudo-`::before` element which extends above the heading isn't placed properly as it naturally goes to the left of the heading, not above it.

Yes, you're right!
