### ISSUE TITLE
content: how-to-stay-fast image mobile version problem

### ISSUE THREAD

**Issue by surajrathod** [GoogleChrome/web.dev#2894]
**Describe the bug**
problem with the mobile view for the image

**Expected behavior**
image needed to the resizable

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/12035730/82140661-03fced80-984e-11ea-8026-5b8212ec8225.png)

**How to fix**
remove the inline style for the image
and add the max-width 100%

**Comment by kaycebasques** [comment]
Thanks for the report @surajrathod 

I'm pretty sure that image should be displaying correctly but it's not worth spending the time figuring out why not… so I think easiest path is for me to just replace it with a table

**Comment by surajrathod** [comment]
you should have added max-width='100%' in style inline.
no problem table is also fine
