### ISSUE TITLE
web.dev/live doesn't support multiple speakers

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/web.dev#2900]
The event data and generation code currently only supports a single speaker.

While this might remove our need to use the `Author` component, and we generate the HTML ourselves in `EventTable`, I still think it's worth fixing in #2897 (so it's easier to use).

**Comment by robdodson** [comment]
We do have a design for multiple authors but the overlapping is kinda 'meh'. It's necessary because cards are pretty tight.
![image](https://user-images.githubusercontent.com/1066253/82360787-be136700-99be-11ea-8686-45d25a33ed9b.png)
