### ISSUE TITLE
web.dev/live speakers without articles go to 404

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/web.dev#2904]
We're adding more speakers (see #), but if those authors haven't written articles, their individual pages (e.g. https://web.dev/author/sebabenz) aren't generated and they 404.

We can either solve this by always generating the page (easier), or perhaps disabling the link if they've not written anything (harder).

**Comment by samthor** [comment]
We see this in #2905.

**Comment by devnook** [comment]
I think it is worth to link to individual author even if they didn't write anything, to get a brief description and social links for their profile.

**Comment by robdodson** [comment]
I spoke about this with Harleen today. She said that a number of folks have said that they won't be publishing a follow up post and so we'd be linking to essentially an empty author page.

She and Carol suggested that we add exceptions for these authors and just link to their twitter profile. I think the easiest way to do this would be in the `event.json` file, we'd add a value like `socialMediaOverride: https://link/to/twitter`

**Comment by carolrivero** [comment]
I will share links to where you can find who is writing a post on web.dev + where to find links to speaker's social links through a separate email thread b/c I'm not sure I can shared links to internal spreadsheets here. Thanks.

**Comment by samthor** [comment]
I think ideally we'd just link to these authors' social profile directly from the event. This could be done by picking the best network and using it as the link, for authors where they have no posts (as the only place their image will show up is on the event page then).
