### ISSUE TITLE
content: Handbook should have advice on term surrounding web standards

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#2909]
Words like 'standard' and 'spec' have specific meanings on the web platform. Incorrect usage of these terms will be interpreted as correct usages with the potential for misunderstanding or the accusation of being misleading. We should begin with the terms below and expand as needed.

* incubation
* spec
* standard

We will probably want @cwilso to advise on this.

**Comment by kaycebasques** [comment]
@jpmedley please submit a PR that documents your recommended usage of each term

**Comment by jpmedley** [comment]
Got it on the list.
