### ISSUE TITLE
Mobile Menu - does not dismiss/collapse after selection

### ISSUE THREAD

**Issue by stewartwarner** [GoogleChrome/web.dev#291]
When you open the menu tray, and selection learn/measure, the mobile menu does not collapse

EXPECTED
* menu should collapse after selection

BROWSER
* Used simulator to view since I do not have a google mobile device to test corp

SCREENSHOT
* https://screenshot.googleplex.com/Tj9TUPvj9Bp

URL
* https://web.devsite.corp.google.com/

**Comment by Malvoz** [comment]
> Extracted into b/119563145

IDK what that means, the issue still exists however.

**Comment by robdodson** [comment]
Yep we plan to drop this component in a month or so. Stay tuned...
