### ISSUE TITLE
Unsynced browser version name

### ISSUE THREAD

**Issue by Chiragmodi1247** [GoogleChrome/web.dev#2916]
**Describe the bug**
Here it says starting from chrome 83 for preloading image https://web.dev/optimize-lcp/#preload-important-resources
Here it says different: https://web.dev/preload-responsive-images/

**To Reproduce**
1. Go to 'https://web.dev/optimize-lcp/#preload-important-resources'
2. Scroll down to 'preload image'
![Screenshot 2020-05-19 at 11 58 34 AM (2)](https://user-images.githubusercontent.com/24935849/82292318-506c3880-99c8-11ea-975d-f6009792e712.png)
![Screenshot 2020-05-19 at 11 58 43 AM 2](https://user-images.githubusercontent.com/24935849/82292324-52ce9280-99c8-11ea-8234-3f5f80aacef4.png)

**Comment by robdodson** [comment]
@philipwalton should your post say 73 instead of 83?

**Comment by jpmedley** [comment]
Pinging this again.

**Comment by philipwalton** [comment]
This is @housseindjirdeh's post, I'll defer to him.

**Comment by jpmedley** [comment]
This is a straight factual correction, not a judgement call. @housseindjirdeh 's article needs to be clear that this is not universally available, which requires a version number. We also need to know which version number is correct in case we need to change @yoavweiss 's article. That this got pulled or delayed after Yoav's article went up is easily within the realm of possibility.
