### ISSUE TITLE
Add missing speaker images.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#2922]
If speakers are missing images we can just grab them from their twitter or internal teams page.

**Comment by carolrivero** [comment]
FYI - I also linked @samthor to the speaker responses sheet where all the speaker photos and social links are captured. We currently have 28 who responded and I think we're just missing ~ 10 some speakers have multiple talks - so it may be less than 10.

Also, some talks will have multiple speakers (2-r4?), we should think of how we plan to design around this as well.

Thanks.

**Comment by carolrivero** [comment]
@harleenkbatra08 FYI

**Comment by robdodson** [comment]
follow up. Harleen noted that the 4 speakers is only happening in opening talks and we'll just stick to showing 1 icon there (probably dion).
