### ISSUE TITLE
Migrate to Lighthouse CI 0.4.0 🎉

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/web.dev#2928]
Hi there! Friendly Lighthouse CI maintainer here 👋 Thanks for being an early adopter of LHCI and a heads up below on an infrastructure change that looks like it will affect you :)

**Is your feature request related to a problem? Please describe.**

Lighthouse CI 0.4.0 will be releasing soon. As part of the release process I will be upgrading `https://lhci-canary.herokuapp.com/`, which as the name implies, was meant to be the *canary* server for testing new releases. This repo is currently using this server, but I noticed the integration here has shifted to use the treo.sh GitHub CI action rather than LHCI directly which means it will break when this happens.

https://github.com/GoogleChrome/web.dev/blob/697c540e579df1afa1c2ea16100493f8bb19828b/.github/workflows/lighthouse-ci-workflow.yml#L36-L42

**Describe the solution you'd like**

Two options, either are fine with me: 

1. Accept a PR that moves this repo's LHCI integration to use `@lhci/cli@next` so this repo can continue to use the canary server and assist with the release process by providing feedback.
2. Migrate off of `https://lhci-canary.herokuapp.com/` to a [self-hosted server](https://github.com/GoogleChrome/lighthouse-ci/tree/master/docs/recipes/heroku-server#setting-up-your-repo) (it's free 😃) if you'd prefer to stay on a stable version and upgrade at your own pace.

**Important Dates**

I am shooting to migrate the canary server to 0.4.0-beta.0 **tomorrow** and can have a PR ready for you by **10PM CDT tonight** if you'd like to stay on the canary managed server. If no action is taken before then, uploads to the LHCI server will start to fail. If this repo followed the official setup documentation for 0.3.x without using assertions, this should not start failing any CI builds and only result in log output, but your exact setup may differ.

**Comment by alekseykulikov** [comment]
The action v3 will be released, as soon, as LHCI v0.4 published https://github.com/treosh/lighthouse-ci-action/issues/52

**Comment by patrickhulce** [comment]
Awesome news @alekseykulikov thanks for chiming in! 🎉 

Definitely not trying to say your great CI action shouldn't be used or that it *won't* be updated after 0.4.0 is released, just that for anyone using the public `lhci-canary` server that I manage, I'd like for them to stay in sync with the canary version of LHCI by using `@lhic/cli@next`. Otherwise I have to chase down everyone to update and it loses its canary purpose (and places unreasonable extra burdens on themselves, like me filing an issue that needs a response within 24 hours 😆).

**Comment by robdodson** [comment]
thanks @patrickhulce 

going with option 1 for now so we can keep providing feedback.
