### ISSUE TITLE
Add link to community guidelines

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#2931]
Need to add a link to our event community guidelines. We could either host this page ourself or see if there's an existing one we can link out to.

**Comment by samthor** [comment]
IANAL, but there's a Google one here: https://www.google.com/events/policy/anti-harassmentpolicy.html

But that is linked to from e.g., last year's CDS site (and I believe previous years' too): https://developer.chrome.com/devsummit/community-guidelines/

**Comment by robdodson** [comment]
yeah i think the updated one talks a bit more about virtual events. I asked them today if they have a hosted version or if they'd like us to self host. They said they'd get back to me. If we don't hear anything by tomorrow we can self host.
