### ISSUE TITLE
Link to "Edit on GitHub"

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/web.dev#294]
Not while this repo is private, or even maybe a blurb on all guide pages, just saying "Edit on GitHub—coming soon".

Just so folks know they can help us with the content.

**Comment by carolrivero** [comment]
Every page on the site should have an "edit on github" button. The button should link back to the markdown file for the page itself. We can implement the functionality using a placeholder button and come up w/ a real design when we land it.
