### ISSUE TITLE
Schedule changes

### ISSUE THREAD

**Issue by harleenkbatra08** [GoogleChrome/web.dev#2954]
### What page(s) need to be updated? web.dev/live

Could you please make the following changes?

- Day 1: move Elizabeth's session to the second talk of the day, so just after the opener
- Day 1: change Addy's session title to: **How to Optimize for Web Vitals**
- Day 1: change the second-last session (Debugging SEO problems) title to: **Debugging JavaScript SEO issues**

- Day 2: update Demian's session to sentence case: **How to Define your Install Strategy**
- Day 2: change PJ's notifications session to: **Quieter Notifications Permissions**
- Day 2: change the last session (Zoom case study) to: **Advanced APIs for bringing people together**

- Day 3: update Mariko's session to sentence case: **Building Better in the World of Build Tools!**
- Day 3: change Una's session to: **10 Layouts in 10 Lines or Less**
- Day 3: update Jason and Jake's session to sentence case: **Writing Rollup Plugins**
- Day 3: update Jake's session to sentence case: **Image Compression Formats Compared**
- Day 3: change Stephen's session title to: **How to Stay Fast and Fresh with Angular**
- Day 3: change Eiji's COOP/COEP session title to: **Prevent info leaks and enable powerful features: COOP and COEP**
- Day 3: change Sam's Issues Panel session title to: **Find and fix problems with Chrome DevTools Issues Tab**
- Day 3: change Maud & Rowan's session title to: **Just the Data you Need**
- Day 3: update Sam's Sign-in form session to sentence case: **Sign-in Form Best Practice**

Thanks Ewa!

**Comment by harleenkbatra08** [comment]
@robdodson since Ewa and Sam are both off, could you please change Sam Dutton's session on Privacy Sandbox to: **Security and Privacy for the Open Web**

Missed this one when it got changed earlier today. Sorry!

**Comment by devnook** [comment]
WIP https://github.com/GoogleChrome/web.dev/pull/2957

**Comment by carolrivero** [comment]
Hi folks
Our tracker, w/c is our source of truth for all title changes has become a living document and changes are coming in on a regular basis. I would recommend reviewing the tracker right before launch to ensure the titles are up to date. If not, I think we can always update before launch. When is Wave 2 update? Is is still June 15? Thanks.
