### ISSUE TITLE
Glitch embeds don't display

### ISSUE THREAD

**Issue by jsejcksn** [GoogleChrome/web.dev#2997]
**Describe the bug**
Embedded Glitch iframe examples momentarily display in articles, then disappear

**To Reproduce**
1. Go to https://web.dev/style-focus/

**Expected behavior**
To be able to view/interact with examples

**Observed behavior**
Examples appear momentarily, and then disappear. Console errors appear for each iframe, in the form of:

```
Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at https://glitch.com/embed/index.version.0b3320671c7a55036e59.js:48:27594
    at sa (https://glitch.com/embed/index.version.0b3320671c7a55036e59.js:74:248899)
    at Ma (https://glitch.com/embed/index.version.0b3320671c7a55036e59.js:74:256552)
    at u (https://glitch.com/embed/index.version.0b3320671c7a55036e59.js:74:279687)
    at d (https://glitch.com/embed/index.version.0b3320671c7a55036e59.js:74:280314)
    at MessagePort.F.port1.onmessage (https://glitch.com/embed/index.version.0b3320671c7a55036e59.js:74:281990)
```

**Screenshots**
<img width="971" alt="Screen Shot 2020-05-26 at 00 31 55" src="https://user-images.githubusercontent.com/868251/82864228-b5082580-9ee9-11ea-96bf-c159dbc2b084.png">

<img width="538" alt="Screen Shot 2020-05-26 at 00 32 20" src="https://user-images.githubusercontent.com/868251/82864232-b9344300-9ee9-11ea-839b-5e111b401f39.png">

**Software**
Chrome `83.0.4103.61`

**Comment by robdodson** [comment]
Filed an issue with Glitch support (https://support.glitch.com/t/glitch-embeds-not-displaying/24647).

**Comment by jsejcksn** [comment]
@robdodson I just read your post. More info: I couldn’t reproduce in Safari, and I have a suspicion that it has to do with the way Chrome manages third-party cookies and other storage.

I have third-party cookies disabled for privacy. Do you as well?

**Comment by robdodson** [comment]
> I have third-party cookies disabled for privacy. Do you as well?

I don't but I think I see some additional info in the logs:

```
Could not save to localStorage. (localStorage is disabled in private Safari windows)
```

That's what it says when I use an incognito window in Chrome (not sure why it's mentioning Safari, maybe that's coming from whatever library they're using).

So it seems like this affects folks who are either browsing using incognito or have enabled opt-in privacy features. I'll email glitch support to let them know.

**Comment by jsejcksn** [comment]
This issue is still unresolved.

**Comment by jsejcksn** [comment]
This issue is still unresolved.

**Comment by samthor** [comment]
So this fundamentally seems like an issue with Glitch not respecting `sessionStorage` not being available.

We've filed it with Glitch. We could disable these embeds and show a notice in private mode(s), but that's not really the right answer.

**Comment by jsejcksn** [comment]
@samthor I agree—that would not be a great experience. Has Glitch provided any kind of response? I didn't see a link to the issue that was filed... if there is one available, I'd like to follow it.

**Comment by samthor** [comment]
See @robdodson 's comment [above](https://github.com/GoogleChrome/web.dev/issues/2997#issuecomment-634148656).

**Comment by jsejcksn** [comment]
@samthor Ah, of course—I thought you meant on GitHub.

**Comment by robdodson** [comment]
Let me try emailing support@glitch.com

**Comment by robdodson** [comment]
They've passed the issue on to their eng team and are looking into it.

**Comment by jsejcksn** [comment]
Not stale

**Comment by robdodson** [comment]
I pinged the glitch support thread again. They said they'd look into it but never followed up.

**Comment by robdodson** [comment]
Glitch reports that they've now fixed this and I was able to verify using an incognito window
