### ISSUE TITLE
/live page without trailing slash doesn't load in Safari

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#3009]
**Describe the bug**
https://twitter.com/gavindoughtie/status/1265334268063936514

Visiting /live without a trailing slash causes an invalid page in Safari. It seems to be SW related as it will kind of work when you first visit /live, but going to /live a second time will break.

**Comment by jeffposnick** [comment]
Using `return Response.redirect(pathname + '/' + url.search, 301);` instead of the code at https://github.com/GoogleChrome/web.dev/blob/e59e00345dece4dcc3a72aae7783a68101981afe/src/lib/sw.js#L175-L180 seems to make Safari happy, when I tested things locally.
