### ISSUE TITLE
web.dev/live speaker name change

### ISSUE THREAD

**Issue by carolrivero** [GoogleChrome/web.dev#3010]
**Describe the bug**
https://web.dev/live/ - Day 2

Please change "Thomas Steiner" to "Tommy Steiner".

@tomayac

**Comment by tomayac** [comment]
Whatever happened here, please just undo it. Someone changed my name to Tommy in the event Trix, I commented asking for the name to change, which apparently was interpreted the wrong way round. 
https://github.com/GoogleChrome/web.dev/pull/3024
