### ISSUE TITLE
Service worker infinite loop

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#3036]
**Describe the bug**

**To Reproduce**
1. In the DevTools application panel, set the service worker to "Update on reload"
2. Visit web.dev
3. Open the console and see the warnings. Note the spinner in the tab flickers as it tries to refresh.

**Expected behavior**
SW should be able to gracefully update on reload.

**Comment by samthor** [comment]
This is interesting. I suppose we force a reload when the SW changes, which forces a reload, which forces a reload, ... (but only in DevTools).
