### ISSUE TITLE
"Get Notified" button on web.dev live is grammatically incorrect

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#3037]
Either "Get Notifications" or "Be Notified" would be correct.

![image](https://user-images.githubusercontent.com/8204171/83069078-2a751280-a01e-11ea-8a4b-e38b0e869ead.png)

**Comment by robdodson** [comment]
Spoke with marketing and they asked that we keep this as "Get Notified" because the term "notifications" has very specific meaning (i.e. push notifications). If it's ok I'd like to just leave it as it is.
