### ISSUE TITLE
content: Service Worker Caching and HTTP Caching [2020-06-27]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3045]
* [draft](https://docs.google.com/document/d/1AWsP-054icCpxE5qdp3lL1Ia7O9guamujl0Xc7yQMcs/edit?ts=5e70cd7a#)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/U9vd1yZBY3U)

**Comment by jeffposnick** [comment]
Just checking as to what's expected of me as an Assignee.

(I've previously reviewed the draft post.)

**Comment by kaycebasques** [comment]
@jeffposnick I think I just assigned you because you were the Web DevRel person closest to the content and I wasn't sure of the next step. Assigning to myself now for TW review.
