### ISSUE TITLE
Make authors and tags files into JSON. Move behavior into other files.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#3055]
**Is your feature request related to a problem? Please describe.**
We'd like to give the tech writers the ability to edit the authors and tags files without needing an eng review. But since these files are `.js` we always require an eng review because we don't want folks sneaking malicious js into our build.

I think we should move the behavioral bits out of these files and into their own .js files that import the authors/tags file and then export the final product. Eng would be owners of these new files and we could have writers own the .json files.

**Describe the solution you'd like**
Convert postTags.js and contributors.js to json, move behavior into separate files.

**Comment by robdodson** [comment]
@MichaelSolati I'm assigning this to you since you've worked with these the most. Give me a shout when you want to discuss.

**Comment by jpmedley** [comment]
Thank you for reopening.

**Comment by MichaelSolati** [comment]
@jpmedley no problem. On the plus side, this is half way done. `contributors.js` is now `authorsData.json`. I'll next work on tag data.
