### ISSUE TITLE
Should FCP code attempt to use performance.getEntriesByType as a fallback?

### ISSUE THREAD

**Issue by npm1** [GoogleChrome/web.dev#3064]
**Describe the bug**
In https://web.dev/fcp/, the code uses PerformanceObserver with 'type' and 'buffered' flag. These are relatively new additions, so I wonder if we can add a fallback to the example, in case WebKit or Gecko begin supporting Paint Timing before adding these observer features

**Expected behavior**
Perhaps in the catch add an onload handler that queries performance.getEntriesByType or performance.getEntriesByName to get FCP.

**Comment by npm1** [comment]
cc @philipwalton

**Comment by kaycebasques** [comment]
@philipwalton PTAL

**Comment by philipwalton** [comment]
Adding the fallback would complicate the code example, so I'd prefer to not do that unless one of these browsers actually adds Paint Timing without full `PerformanceObserver` support.

I'm definitely paying attention to their implementation though.
