### ISSUE TITLE
Update info on buffered flag support for long tasks

### ISSUE THREAD

**Issue by anniesullie** [GoogleChrome/web.dev#3065]
**Describe the bug**
At https://web.dev/custom-metrics/#long-tasks-api it says:

"Caution: The buffered flag does not currently work for Long Tasks (though support is being added). In the meantime, you can track Long Tasks by registering the PerformanceObserver in the <head> of your pages, before loading any other scripts."

Chrome has been updated to support the buffered flag for Long Tasks. Can the wording be updated?

**Comment by npm1** [comment]
cc @philipwalton

**Comment by kaycebasques** [comment]
@philipwalton PTAL
