### ISSUE TITLE
Metrics page should link to Web Vitals

### ISSUE THREAD

**Issue by skobes** [GoogleChrome/web.dev#3066]
The https://web.dev/metrics/ page doesn't have any links to https://web.dev/vitals/.  This seems like a good link to include, perhaps in its own section.

**Comment by npm1** [comment]
cc @philipwalton

**Comment by kaycebasques** [comment]
@philipwalton PTAL

**Comment by philipwalton** [comment]
Reassigning @khempenius who was planning to rethink the organization of all the docs under `/fast`, `/metrics`, and `/vitals`.

Currently I don't think the structure of the template that `/metrics` uses allows it to link to any given page. It has to be a page in its "learn" path.

**Comment by khempenius** [comment]
not stale
