### ISSUE TITLE
content: Editorial suggestions for CLS

### ISSUE THREAD

**Issue by npm1** [GoogleChrome/web.dev#3067]
### What page(s) need to be updated?
https://web.dev/cls/

### Suggested changes:
* The term 'frame' in the web is very overloaded, I suggest defining it (animation frame?) before using it in the document.

* s/entries any time an element that is visible with the viewport changes its start position/entries any time an element that is visible within the viewport changes its start position

* Use of unstable elements should be in italics as it refers to a defined term.

* The purple arrow is almost blue (may be improved for a11y)

* Maybe add a brief explanation on why 500 milliseconds is the cutoff for hadRecentInput

* Can feature detection be done with PerformanceObserver.supportedEntryTypes? (not sure what's the status of that in other browsers)

* First usage of CrUX should probably be the full name, not the acronym. Not everyone knows what CrUX means.

* Understanding CLS talk is with Steve Kobes too.

Overall it looks pretty good though!

**Comment by npm1** [comment]
cc @philipwalton

**Comment by kaycebasques** [comment]
@philipwalton PTAL

**Comment by philipwalton** [comment]
> Can feature detection be done with PerformanceObserver.supportedEntryTypes? (not sure what's the status of that in other browsers)

While technically it could work for CLS, it's not necessarily a future-proof solution because Safari currently throws when calling `observe()` without the `entryTypes` option.

Presumably Safari would change that before implementing the `layout-shift` type, but given that we don't know this for sure, it seemed safer to use a try/catch.

**Comment by philipwalton** [comment]
@npm1 

> Maybe add a brief explanation on why 500 milliseconds is the cutoff for hadRecentInput

I'm not actually sure why that specific number was chosen, can you elaborate?

**Comment by npm1** [comment]
@skobes do we have some explanation for this?

**Comment by skobes** [comment]
The 500ms duration for the input exclusion window was chosen for being, in our estimation, small enough that a shift occurring within it would be perceived by the user as clearly connected to the input, while also large enough to allow the page to do some work between the input and the shift.
