### ISSUE TITLE
content: Editorial suggestions for TBT

### ISSUE THREAD

**Issue by npm1** [GoogleChrome/web.dev#3068]
### What page(s) need to be updated?
https://web.dev/tbt/

### Suggestions
* The article begins with "Total Blocking Time (TBT) is an important, user-centric metric[...]". I think this should clarify that TBT is a lab metric, or at least we only recommend using it as a lab metric.

* s/If the task is long enough (e.g. anything above 50 ms). It's likely that the user will notice the delay and perceive the page as sluggish or janky./If the task is long enough (e.g. anything above 50 ms), it's likely that the user will notice the delay and perceive the page as sluggish or janky.

* Improve guidance regarding potential noise of the metric, since it depends on TTI. It's probably less noisy than TTI but still its dependence on it could make it somewhat volatile in some cases.

**Comment by npm1** [comment]
cc @philipwalton

**Comment by kaycebasques** [comment]
@philipwalton PTAL
