### ISSUE TITLE
Content: Provide better/modern guidance on interpreting TTI vs other metrics

### ISSUE THREAD

**Issue by mmocny** [GoogleChrome/web.dev#3069]
https://web.dev/tti/ article does a fantastic job explaining precisely what TTI is... but I think could do more to help explain how that metric should be used in practice, especially compared to TBT or FID.

> Time to Interactive (TTI) is an important, user-centric metric for measuring load responsiveness. It helps identify cases where a page looks interactive but actually isn't. A fast TTI helps ensure that the page is usable.

Specifically: TTI as a number can jump very inelastically.  It represents the moment in time after which know the page is idle, but it really doesn't say anything about _how busy_ the page was before idle.  TBT does a better job measuring that in the lab (and FID is true goal in the field).

Drastic improvements to your site may not change TTI at all (e.g. one lone 3p script introducing a longtask), while still improving real user experience.

As such, I think the TTI article could do more to direct folks to track TBT/FID first and foremost, and treat TTI as a final boss.

**Comment by npm1** [comment]
cc @philipwalton

**Comment by kaycebasques** [comment]
@philipwalton PTAL
