### ISSUE TITLE
[Pre-event] Add link to community guidelines

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#3071]
![image](https://user-images.githubusercontent.com/1066253/83284778-0b978d00-a192-11ea-9983-e31f21476cb1.png)

**Comment by digitalPlayer1125** [comment]
Hi! I'd like to take up this issue. The link to the https://about.google/community-guidelines/ is to be added, right?

**Comment by robdodson** [comment]
Hey @digitalPlayer1125, we're going to host our own copy of the guidelines on web.dev because they're being updated. I think we can handle this one as we have to get the copy from an internal team.

**Comment by digitalPlayer1125** [comment]
Oh alright. Thanks for your time.

**Comment by samthor** [comment]
To be clear we already host the guidelines, the link is in the footer. We just need a link inline.
