### ISSUE TITLE
Document the fact that CrUX looks at all frames for vitals

### ISSUE THREAD

**Issue by npm1** [GoogleChrome/web.dev#3076]
**Describe the bug**
Right now we just link to https://developers.google.com/web/tools/chrome-user-experience-report and I don't think that explains that these are page-level metrics. So iframes are not ignored, and this can be tricky if you want to compare your web perf RUM data with the CrUX data in some cases. Should web.dev/vitals have concrete messaging explaining this?

cc @philipwalton

**Comment by kaycebasques** [comment]
@philipwalton & @rviscomi PTAL

**Comment by philipwalton** [comment]
I agree with @rviscomi that this guidance should live on the CrUX docs. Then (once updated), the metrics docs can add notes/warnings that their guidance and code samples only cover the top-level frame, and if they want to track the metrics across all frames, they'd have to set up the messaging themselves.

**Comment by npm1** [comment]
So is the right thing to do to change https://developers.google.com/web/tools/chrome-user-experience-report or which site? I thought developers.google.com was being deprecated in favor of web.dev.

**Comment by rviscomi** [comment]
Yes, updating this in the CrUX docs on developers.google.com is the right thing.
