### ISSUE TITLE
Document CLS nuance around infinite scrolling UX patterns

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web.dev#3078]
Add a note to web.dev/optimize-cls regarding infinite scrolling:

"It is critical to reserve sufficient space (e.g a properly sized placeholder that matches content) for any dynamic content that sits behind a network fetch. Not doing so may cause layout shifts. This applies to any UX patterns you might use over the lifetime of a document.

Patterns like infinite scrolling may be subject to layout shifts on fling. Before new dynamic content is rendered into the viewport, attempt to reserve enough space for any skeleton UI (e.g cards) to minimize the impact this has on shifting down other content that is visible. If your users enjoy infinite scroll, we do not recommend removing it just to optimize for CLS, but believe space reservation should be sufficient."

**Comment by addyosmani** [comment]
Still planning to work on this, bot 😂

**Comment by kaycebasques** [comment]
@addyosmani is this still relevant?

**Comment by lebreRafael** [comment]
hey @addyosmani do you think we could also add a documentation for reverse infinite scroll (like chat application where you scroll up to load more messages)? I'm facing an issue trying to prevent CLS on a scenario like that and would be awesome to have some documentation about that.
Let me know if you think I should open another issue for that
