### ISSUE TITLE
Service worker is causing double loads in Lighthouse

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#3089]
**Describe the bug**
Our LH and PSI perf scores seem much worse than they should be. Locally I get around 87 in LH and 61(!) in PSI.

![image](https://user-images.githubusercontent.com/1066253/83363221-84dadf80-a34c-11ea-9208-f580b83f2500.png)

---

Looking at the trace I noticed that the page seems to load twice, even if the url contains a trailing slash. Here's an example from `localhost:8080/`. Note the stats like LCP get logged twice:

![image](https://user-images.githubusercontent.com/1066253/83363122-d5057200-a34b-11ea-9766-27a58f571653.png)

After poking around a bit I think I've narrowed the issue down to our service worker. If I just comment out [the lines that register the SW](https://github.com/GoogleChrome/web.dev/blob/64bcffdf3e82ab1a2d24022e6815f279d0741fae/src/lib/app.js#L62-L66) my local LH score jumps to 100. I also noticed that [we don't register the sw on the staging site](https://github.com/GoogleChrome/web.dev/blob/64bcffdf3e82ab1a2d24022e6815f279d0741fae/src/lib/app.js#L70) and sure enough its PSI score is ~30 points higher:

![image](https://user-images.githubusercontent.com/1066253/83363320-7b05ac00-a34d-11ea-8bac-46c7f5e20384.png)

@samthor I know you've got a lot going on with /live/ so if you'd like I could have the rest of the team dig into this to isolate and fix the issue.

**Comment by samthor** [comment]
So I think in moving some of the service worker stuff around (and just trying to be aggressive about making sure a user has the latest version), we have this code block:

```js
  const isFirstInstall = !navigator.serviceWorker.controller;
  if (isFirstInstall) {
    // Watch for the brand new Service Worker to be activated. We claim this foreground page
    // inside the Service Worker, so this event will fire when it is activated.
    navigator.serviceWorker.addEventListener('controllerchange', () => {
      ensurePartialCache(true);
    });
  } else {
    // This isn't the first install, but ensure some partials are up-to-date.
    ensurePartialCache();

    // We claim active clients if the Service Worker's architecture rev changes. We can't
    // reliably force a reload via the Client interface as it's unsupported in Safari.
    navigator.serviceWorker.addEventListener('controllerchange', () => {
      window.location.reload();
    });
  }
```

There's nothing wrong with this, except that in the second path, the 'controllerchange' event really does fire all the time a SW changes—not just on "version rev" like it used to.

Now this is actually pretty good, because pages like the web.dev/live have new JS and CSS, and in dev (or whatever) I often see the old version for a second before the SW updates and forces a refresh. But it means that for every new deploy where the SW data changes (master partial change?), we reload, which might be what you're seeing.

**Comment by jeffposnick** [comment]
One other point: there's a post about SW registration best practices at https://developers.google.com/web/fundamentals/primers/service-workers/registration

It can often be a good idea to delay SW registration until after you've detected that all of the page's content has loaded (either via `window.onload` or some other event). That way, the process of starting up the SW thread and downloading the precached URLs won't contend with your main page's loading.

I had thought that Lighthouse tests start with an empty cache/SW registrations, but perhaps that has changed? Assuming it is still the case, it seems like `isFirstInstall` would always be `true`.

**Comment by samthor** [comment]
I like your suggestion, @jeffposnick. We don't need to rush into installing the SW.

I don't think #3171 is quite right @robdodson as I'd really like to keep the "major revision forces a reload" behavior. (Even though this issue is still valid, in that we're reloading all the time now.)

**Comment by robdodson** [comment]
> I'd really like to keep the "major revision forces a reload" behavior.

Were you thinking of enforcing that with the `serviceWorkerArchitecture` string in `sw.js`?

**Comment by robdodson** [comment]
I think #3362 is the intended solution for this. My understanding is if the user is online we'll try to fetch the latest partial, and if it has a version mismatch with the assets, then we'll fetch the latest assets as well.
