### ISSUE TITLE
The setting up a payment method has a broken link

### ISSUE THREAD

**Issue by tyohan** [GoogleChrome/web.dev#3101]
[This setting up a payment method article](https://web.dev/setting-up-a-payment-method/) has a broken link on it. The list that mentioned **Empowering payment apps with Web Payments** goes to https://web.dev/empowering-payment-apps instead of https://web.dev/empowering-payment-apps-with-web-payments/

**Comment by cljazouli** [comment]
Good catch @tyohan 👍 !
I have a fix for that in https://github.com/GoogleChrome/web.dev/pull/3105
