### ISSUE TITLE
content: Small suggestions for LCP

### ISSUE THREAD

**Issue by npm1** [GoogleChrome/web.dev#3108]
Feedback for: https://web.dev/lcp/. Overall the page is great so I only have some small suggestions.

* In the sentence "The Largest Contentful Paint (LCP) metric reports the render time of the largest content element visible within the viewport.", maybe note that LCP is restricted to text and image content?

* We note that removed elements stop counting as LCP candidates. I wonder if it's worth noting that this might change in the future due to image carousel problems?

* In the sample code, after the line `po.takeRecords().forEach(updateLCP);`, should the observer be disconnected?

cc @philipwalton

**Comment by kaycebasques** [comment]
@philipwalton PTAL

**Comment by philipwalton** [comment]
@npm1 

> In the sample code, after the line `po.takeRecords().forEach(updateLCP);`, should the observer be disconnected?

I could, I think I didn't do that originally because (IIRC) we were discussing the possibility of re-emitting LCP after bfcache loads or in certain SPA scenarios, but that's probably premature.

**Comment by npm1** [comment]
> @npm1
> 
> > In the sample code, after the line `po.takeRecords().forEach(updateLCP);`, should the observer be disconnected?
> 
> I could, I think I didn't do that originally because (IIRC) we were discussing the possibility of re-emitting LCP after bfcache loads or in certain SPA scenarios, but that's probably premature.

Right, up to you! I don't think it will harm to leave it observing after if it won't get any more entries.
