### ISSUE TITLE
content: Fix typo on Optimizing LCP article

### ISSUE THREAD

**Issue by mmocny** [GoogleChrome/web.dev#3110]
### What page(s) need to be updated?

https://web.dev/optimize-lcp/#preload-important-resources

### Why is this update needed?

"Starting in Chrome 83, **reloading** can be used along with responsive images to combine both patterns for much faster image loading."

Should say **preloading**

**Comment by mmocny** [comment]
(I would submit PR, but somehow I cannot find the optimizing-lcp article...)

**Comment by kaycebasques** [comment]
Thanks @mmocny & FYI there's a **Improve article** link at the bottom of every page that should jump you to the GitHub source code
