### ISSUE TITLE
Handbook references content that doesn't exist

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#3112]
The [Video instructions](https://web.dev/handbook/markup-media/#video) state: "To embed a YouTube video, use the web.dev YouTube component." The word component is linked to the [WebDev components page](https://web.dev/handbook/web-dev-components/). Not only is the component missing from that page, the word YouTube doesn't even appear.

![image](https://user-images.githubusercontent.com/8204171/83684710-55baad00-a59c-11ea-9bef-c0d4fca6fa97.png)

**Comment by robdodson** [comment]
hm ok.

Well in the short term here's how to use it:

```njk
{% YouTube 'some-video-id', 'some-start-time' %}
```

The start time argument is optional.

**Comment by jpmedley** [comment]
So the YouTube component is approved for use? I need to know whether to remove the reference in the video instructions or add the item to the component instructions.

**Comment by robdodson** [comment]
> So the YouTube component is approved for use?

yep we use it in several places already.

> I need to know whether to remove the reference in the video instructions or add the item to the component instructions.

I think we should add the item to the handbook. I can do that.
