### ISSUE TITLE
[During event] Add "Now watching" button to schedule

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#3117]
![image](https://user-images.githubusercontent.com/1066253/83696125-7db40b80-a5b0-11ea-883f-5231dfcfea5d.png)

Clicking "Now watching" should scroll the page up to the video player.

**Comment by samthor** [comment]
This is probably less high priority, nice to have. It requires us perhaps having more confidence about the exact schedule and actually surfacing it to the client in JS.

**Comment by robdodson** [comment]
I think this is not going to happen because they never gave us specific video times.
