### ISSUE TITLE
`"$"` seems to trigger templating system

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3136]
![image](https://user-images.githubusercontent.com/4713486/83795909-04babf80-a655-11ea-8874-83f875c77458.png)

![image](https://user-images.githubusercontent.com/4713486/83795930-0dab9100-a655-11ea-9446-90761e481f18.png)

This was in web.dev/robots-txt but I'm fixing it now

**Comment by robdodson** [comment]
oh...fun...

cc @MichaelSolati @samthor
