### ISSUE TITLE
It's not possible to use GoogleTagManager with require-trusted-types-for 'script'

### ISSUE THREAD

**Issue by tmb-github** [GoogleChrome/web.dev#3160]
The new `require-trusted-types-for 'script'` header would be a wonderful thing to use in production sites, but neither GoogleTagManager nor reCAPTCHA can be used with it, because `src` attributes are used on strings that are not TrustedScriptURLs in the code that is dynamically loaded from Google.

I found the GitHub for reCAPTCHA and logged a thorough description of the problem there as a bug, but I could find no place to do the same for GoogleTagManager. 

It would seem a simple fix for the authors of those routines to modify them to perform feature detection and conditionally provide a TrustedScriptURL in environments where they're supported, otherwise provide standard "dirty" strings for the `src` values.

Until this is done, however, it will be wildly impractical to use the `require-trusted-types-for 'script'` header for any live site, as Google Analytics/Google Tag Manager and reCAPTCHA cannot be used in conjunction with it.

**Comment by robdodson** [comment]
Thanks for reporting this. I've tried to pass it along to the relevant team.
