### ISSUE TITLE
content: International Layouts [2020-07-08]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3161]
* [draft](https://docs.google.com/document/d/1KkEntUEAFg5VxX8g612yQfPRzV1Q4DjX0kuEJn98bFI/edit?ts=5edad6c3)
* [thread](https://docs.google.com/document/d/1KkEntUEAFg5VxX8g612yQfPRzV1Q4DjX0kuEJn98bFI/edit)
* next step: @rachelandrew to review

**Comment by argyleink** [comment]
ready for first editors review 👍

**Comment by argyleink** [comment]
just scrubbed it again, i believe it's in a good spot for review

**Comment by kaycebasques** [comment]
I'll review this one

**Comment by argyleink** [comment]
🧟  not dead

**Comment by argyleink** [comment]
still ready for review!

**Comment by argyleink** [comment]
still get questions about intrinsic design, would love to send them this article

**Comment by una** [comment]
@kaycebasques this looks perfect for @rachelandrew to review if she has availability! Layout internationalization is a great topic 👍

**Comment by rachelandrew** [comment]
@kaycebasques I can have a look if you like, I've done a bunch of work around this so technically it's in my wheelhouse :)

**Comment by argyleink** [comment]
rad @rachelandrew! let me know if you can't get into the draft, looking forward to your review(s) 🙂

**Comment by kaycebasques** [comment]
Sorry for delays. @rachelandrew review SGTM.
