### ISSUE TITLE
content: Signed Exchanges (SXG) [Date: TBD]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3167]
* draft: none provided yet
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/n3zpXLo1nU0)
* next step: katie to draft content and ping the thread when ready for review

**Comment by khempenius** [comment]
Not stale.

**Comment by khempenius** [comment]
@kaycebasques FYI I put 8/25 as the publish date for this (to coincide with M85). However, in reality, we'll probably hold off on publishing for a day or two after that.

**Comment by kaycebasques** [comment]
@khempenius do you have a draft?
