### ISSUE TITLE
content: Serial [2020-07-10 HARD]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3194]
* [draft](https://docs.google.com/document/d/1i5RmYodf0CfMEWYunje6Ei3yPG3aRS1pl39YJ7uVA1k/edit)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/DLAn-HDih3M)
* next step: @beaufortfrancois to address feedback

**Comment by jpmedley** [comment]
@kaycebasques As discussed, I've self assigned and will review the draft today or tomorrow.
