### ISSUE TITLE
Make Tabs widget easier to use

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#3217]
I'm working on some docs that show how to use analytics. Since there are multiple analytics methodologies, I want to show both the `ga` and `gtag` implementation, and potentially other analytics platforms in the future.  To do that, I'd like to use something like the DevSite tab widget (see [example](https://firebase.google.com/docs/analytics/user-properties?platform=ios#set_user_properties_2) below).

<img alt="Screen Shot 2020-06-12 at 3 07 04 PM" src="https://user-images.githubusercontent.com/718038/84537767-69fa5a80-acbe-11ea-9ab5-4a43d0a3416c.png">

**Describe the solution you'd like**
A tab widget, please. I considered using the [details](https://web.dev/handbook/web-dev-components/#details) widget, it could work, but won't be the ideal solution.

[DevSite tab widget documentation](https://developers.google.com/devsite/reference/widgets/tabs) (link is Google only, sorry).

**Comment by samthor** [comment]
We have `<web-tabs>` which we use for our assessments as well as the Live page. Would this help? It's not exposed as a shortcode but it would be pretty easy to do so.

The DevSite tabs, when used as a [code] language picker, persist the user's preference (i.e., if I chose Swift, please keep showing me Swift samples). Do you need anything like that here?

**Comment by petele** [comment]
I think web-tabs would work. 

Nice to have: Persisting language choice between sessions
Nice to have: Switching all tabs to the same language when one is switched

I'd be more than happy to start with just web-tabs, and plan for the nice to haves in the a quarter or two.

**Comment by robdodson** [comment]
Digging back into this.

We have a tabs shortcode but it can be a little funky to use. At a minimum we should at least document how to use it to show different code examples and explore if it needs a larger refactor.

**Comment by robdodson** [comment]
Adding this to the eng project board. If anyone is planning to pick this one up we should chat. I believe the Tabs widget needs a bit of the weird whitespace magic to make the markdown parser kick back in.

**Comment by MichaelSolati** [comment]
@devnook or @petele

Can this be considered done with this tab component we have? => https://web.dev/handbook/web-dev-components/#tabs

**Comment by dstmarthe** [comment]
We are moving to a new platform and content on this site is now frozen. Content creation will also be different. As this is about the site, then it shouldn’t be an issue after the move.
