### ISSUE TITLE
Success Returns API Response.

### ISSUE THREAD

**Issue by yc9274** [GoogleChrome/web.dev#3253]
**Describe the bug**
API is Open - I guess (Look Screenshot) 

**To Reproduce**
1. Go to 'https://web.dev/live/#subscribe'
2. Fill updates form
3. Click 'SUBSCRIBE'
4. See Response

**Expected behavior**
You should be redirected to some success page or same page with success message, this looks bad.

**Screenshots**
![image](https://user-images.githubusercontent.com/32420644/84860509-c679c300-b08c-11ea-9966-a2472720cf52.png)

**Comment by robdodson** [comment]
@yc9274 just curious, did you happen to have JavaScript disabled?

**Comment by MichaelSolati** [comment]
Clicked close by accident, what device and browser are you using?

**Comment by yc9274** [comment]
> Clicked close by accident, what device and browser are you using?
@MichaelSolati I'm using Windows (1909) with Chrome Dev (85.0.4173.0)

**Comment by yc9274** [comment]
> @yc9274 just curious, did you happen to have JavaScript disabled?

@robdodson  JavaScript is enabled for sure.

**Comment by robdodson** [comment]
@yc9274 I'm curious, if you try to sign up for the newsletter again does this issue still happen?

**Comment by yc9274** [comment]
It's fine now, Thanks for comment @robdodson
