### ISSUE TITLE
Need a New Design for Surfacing Tags

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#3270]
Pretend for a moment that a new page isn't generated for every single tag. An index has to get more granular as the information set it describes gets bigger. That means it will tend to grow slighter faster than what it describes. So if I have ten pages and only one of them describes widgets, I only need one tag. If I have a 1000 pages and 30 describe widgets, I need enough tags to save someone from having to review 30 pages to find what they're looking for. Full text search doesn't solve this if the word someone is looking for is overloaded. Nor does it solve it if the word someone is looking for isn't in the actual text.

Generating a single page for every single tag encourages limiting or removing tags, which is the opposite of how tags work.

I will try to find time during the next few months to create mock-ups for how tags could be presented to readers.

**Comment by jpmedley** [comment]
Here's something I still don't understand. How do you guys tell the difference between an untriaged request or proposal and a closed ticket that has been worked on.

**Comment by robdodson** [comment]
> How do you guys tell the difference between an untriaged request or proposal and a closed ticket that has been worked on.

I look at all of the issues that come in, if we plan to work on something I'll add the `accepted` label to it and assign it an owner. A closed ticket that has been worked on will have an associated linked PR.

For a lot of feature requests there's just no bandwidth to do them.
