### ISSUE TITLE
content: "Get started with Web Bundles" links to Google corp resources not accessible to the public

### ISSUE THREAD

**Issue by jeremyroman** [GoogleChrome/web.dev#3271]
### What page(s) need to be updated?

Provide a list of URLs.
https://web.dev/web-bundles/#:~:text=Web%20Packaging%20Proposal

### Why is this update needed?

The links to "Web Packaging" refers to a Google-internal URL shortener which requires corporate credentials to access. (And the document it links to is a non-public document, in any case.)

Either this link should be removed, or it should be replaced with a suitable public URL.

**Comment by jeremyroman** [comment]
@kenjibaheux @uskay fyi

**Comment by jyasskin** [comment]
Thanks! I've suggested a fix at #3280.
