### ISSUE TITLE
content: LCP article should clearly state image/text rendering times

### ISSUE THREAD

**Issue by npm1** [GoogleChrome/web.dev#3283]
### What page(s) need to be updated?
https://web.dev/lcp/

### Why is this update needed?
Currently the article briefly touches on images that have not loaded and text that is in font block period. Perhaps it would be good to explicitly state when we compute the rendering times of LCP candidates:
* For an image, the paint after it has loaded.
* For text, the first paint, even if it is using a fallback font.

cc @philipwalton

**Comment by martinschierle** [comment]
For images it might be worth explicitly calling out behavior for progressive images, placeholders, sceleton pattern.
