### ISSUE TITLE
Code highlight is partially failing

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#3291]
**Describe the bug**
An [embedded HTML code sample](https://github.com/GoogleChrome/web.dev/pull/3289/files#diff-d6df449bce1dba0bb0509c17b0980fabR121) in a new article specifies that lines 3 through 7 should be highlighted. Only lines 3 through 5 are actually behing highlighted.

**To Reproduce**
View the rendered [article](https://github.com/GoogleChrome/web.dev/pull/3289) in any staging environment.

![image](https://user-images.githubusercontent.com/8204171/85171926-d62c0f80-b224-11ea-9621-14c716a48b7c.png)

**Comment by robdodson** [comment]
I think it's the introducing of the newlines that's breaking it. I rewrote the snippet as:

![image](https://user-images.githubusercontent.com/1066253/87998595-3aa0ef80-caad-11ea-91d3-4d1f2c7f1618.png)

and it seemed to highlight ok:

![image](https://user-images.githubusercontent.com/1066253/87998600-3ecd0d00-caad-11ea-833a-11ae68c10d93.png)

Just from an aesthetics perspective, I think I find my version a bit easier to read. I tend to prefer to horizontally scroll code samples if they run long, versus introducing whitespace which can make them a bit awkward to read.

**Comment by jpmedley** [comment]
That's all beside the point. This issue is about the fact that the feature's not doing what I asked or expected.

**Comment by robdodson** [comment]
I think it's doing that because of the introduction of newlines. That's as far as I can dig into it unfortunately.

**Comment by robdodson** [comment]
It might be related to [this issue](https://github.com/11ty/eleventy-plugin-syntaxhighlight/issues/26) but I really don't know. I think this plugin is using prisma so there's a couple of levels of indirection 🤷‍♂️

**Comment by jpmedley** [comment]
With respect, this is not an unreasonable ask. If I ask it to highlight lines 3 through 5 and it doesn't do, it's broken.

**Comment by zachleat** [comment]
Maybe worth filing upstream at the dependency here (I own the dependency, hi): https://github.com/11ty/eleventy-plugin-syntaxhighlight

**Comment by jpmedley** [comment]
[Done](https://github.com/11ty/eleventy-plugin-syntaxhighlight/issues/29).

**Comment by jpmedley** [comment]
Should we keep this open until @zachleat updates 11ty?
