### ISSUE TITLE
Add 'origin-trials' tag when article has `origin_trial` YAML front matter

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#3311]
**Is your feature request related to a problem? Please describe.**
Automatically add the `origin-trials` tag to articles when the article specifies the origin trial details in the YAML front matter.

If the YAML front matter contains origin trial details, it would be nice if the `origin-trials` article tag were automatically added. For [example](https://raw.githubusercontent.com/GoogleChrome/web.dev/master/src/site/content/en/blog/native-file-system/index.md):

```yaml
origin_trial:
  url: https://developers.chrome.com/origintrials/#/view_trial/4019462667428167681
```

**Comment by jpmedley** [comment]
+100

**Comment by jpmedley** [comment]
This will help ensure that the [origin trials page](https://web.dev/tags/origin-trials/) will always be up to date.

**Comment by robdodson** [comment]
This is doable but does add some complexity. In `tags.js` we'd need to change:

```
tag.elements = collections
        .getFilteredByTag(tag.key)
        .filter(livePosts)
        .sort((a, b) => b.date - a.date);
```

to instead look at all markdown files and filter them by tag or origin_trial. The much easier option is to ask authors to include:

```
tags:
  - origin-trial
```

in their post

**Comment by robdodson** [comment]
cc @MichaelSolati

**Comment by jpmedley** [comment]
Granting that I'm the one who asked for tags exactly for use cases like this. The issue here is reliability. What's the point of doing this with computers if we can't automate for reliability?

**Comment by robdodson** [comment]
Per recent discussion, I'm wondering if we should do this on developer.chrome.com first.

**Comment by jpmedley** [comment]
Please see my comment in #3646.
