### ISSUE TITLE
Add fallback images if authors don't have them.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#3318]
**Is your feature request related to a problem? Please describe.**
If we don't fine an image for an author we currently show a broken img.

![image](https://user-images.githubusercontent.com/1066253/85337953-54431d00-b496-11ea-99cc-1aef0b82b0d5.png)

**Describe the solution you'd like**
We should use a fallback img.

**Comment by jpmedley** [comment]
I published one this week where I couldn't get an image from the writer in time. Not ideal, but we need this.

**Comment by robdodson** [comment]
@MichaelSolati do you think you could take this one on? I think it means we need to add back the code we removed that was reading the file system to verify each author had at least one image. If there's no image found then it'll have to use a placeholder.
