### ISSUE TITLE
content: Web 3D Made Simple with <model-viewer> 1.0 [2020-06-26]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3322]
* [draft](https://docs.google.com/document/d/1RJ6xge9RV_SAO5CtXJJNYkxvlqeSBhFDwIi-UBku6X4/edit?ts=5ee3be96#)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/N3vpC9hEJeI)

**Comment by jpmedley** [comment]
Rob is back from vacation. We should be getting around to wrapping this up next week.
