### ISSUE TITLE
content: Intrinsic Navbar Layout [2020-07-03]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3327]
* [draft](https://github.com/GoogleChrome/web.dev/pull/1008)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/0T5ZpbhIXa8)

**Comment by argyleink** [comment]
hydrating the draft branch and will reopen #1008 when it's ready 👍

**Comment by argyleink** [comment]
will allow to go stale until it pumps further up the priority list
