### ISSUE TITLE
content: Centering In CSS [2020-08-06]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3328]
* [draft](https://docs.google.com/document/d/1M5_wJas_B4X9ZvjhVvfBTXU3Y6Wpt2kWS_SY7yWpZ_8/edit)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/9C5ROIDkMlw)
* next step: @argyleink to submit PR

history:

* @kaycebasques reviewed on 7/21

**Comment by argyleink** [comment]
ready for review!

**Comment by kaycebasques** [comment]
Left a comment in the Google Doc

**Comment by argyleink** [comment]
updated link so it's not the initial outline, but the draft

**Comment by kaycebasques** [comment]
@argyleink please review my feedback in the Doc

**Comment by kaycebasques** [comment]
@argyleink please re-assign this to me when you've address all my feedback. It looks like there's a few comments where you say that you're planning on updating the content.

**Comment by argyleink** [comment]
addressed 👍  added the missing videos too, they'll drastically help

**Comment by kaycebasques** [comment]
@argyleink there might be a couple remaining things for us to sort it out but I think we've got enough agreement that you can get a PR started for this (it will be easier to sort out the last remaining things when I see the finished product, too)

**Comment by argyleink** [comment]
i'll PR it next week, thanks Kayce! 👍
