### ISSUE TITLE
Can we disable Youtube recommendations at the end of a video?

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#3335]
I think this might be possible with a query param but need to double check. This would be something we'd add to the YouTube component itself. Just want to make sure YouTube doesn't start recommending off topic videos at the end.

**Comment by samthor** [comment]
We've had absolutely no luck with customization like this for Santa Tracker over the past few years—YT has shut off so many customization options for us so we don't even use it anymore. So any lack of config is at this point a _feature_.
