### ISSUE TITLE
Closing the modal switches the tabs to the current day.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#3336]
**Describe the bug**
If it's day 3, and you click on the day 1 tab and click on a session and then close the modal, the tabs will switch back to day 3.

**Expected behavior**
I think the user expectation is the tabs would stay on day 1 if they taken an action to switch them to day 1.

**Comment by samthor** [comment]
I actually can't repro this. If I open http://127.0.0.1:8080/live/?_now=wdl-day2 and open a modal, the day that modal is from (day 1, 2 or 3) stays selected when I close the modal.

**Comment by robdodson** [comment]
I guess I did it differently. I used the event.js and I made it so day 1 and day 2 were in the past.

![Kapture 2020-06-24 at 18 08 09](https://user-images.githubusercontent.com/1066253/85642248-c86ff300-b645-11ea-8034-6b327697ab85.gif)

**Comment by robdodson** [comment]
I wonder if this is happening because the onStateChanged handler for the schedule sets the tabs to match the activeDay. When you close the modal it triggers this handler I think.

We want the handler to run if the user has left the tab open and we've transitioned from day 1 to day 2. A few options:

- Only run the onStateChanged handler once when the component first boots up. This means it won't transition to day 2 if they leave the tab open but it would fix the current issue.
- Add an additional flag that checks if the user was recently using a modal. If they were then don't update activeTab. Just have to make sure to clear this flag.
