### ISSUE TITLE
A Glitch shortcode

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#3337]
It's easy for authors to accidentally use the wrong url for their glitch embed if they're writing the iframe code directly.

![image](https://user-images.githubusercontent.com/1066253/85455696-02ac9800-b553-11ea-87a0-b923fdb934d4.png)

The top image using /edit/ is bad (it'll try to iframe the literal glitch site). The second image is correct as it uses /embed/.

We should make this easier for folks by providing a Glitch shortcode so they just tell us the id of their project and we do the right thing for them.

**Comment by robdodson** [comment]
@MichaelSolati I _think_ we discussed having you work on this, but I have an awful memory so let me know if I'm mistaken.

**Comment by MichaelSolati** [comment]
> This is looking good but I think we should also add a Glitch shortcode (maybe it can use the IFrame shortcode in its implementation?)
> 
> ```
> {% Glitch 'fav-kitties' %}
> ```
> 
> It'll need to support three arguments:
> - id (the id of the glitch to display)
> - path (this is the file the glitch will display first)
> - previewSize (this controls how much of the app preview is visible)
> 
> If path and previewSize aren't given then it should omit path from the query string, and set the previewSize to 100
