### ISSUE TITLE
maximum-scale value in viewport clarification

### ISSUE THREAD

**Issue by lightningspirit** [GoogleChrome/web.dev#3361]
### What page(s) need to be updated?
- https://web.dev/meta-viewport/
- https://github.com/GoogleChrome/web.dev/blob/master/src/site/content/en/lighthouse-accessibility/meta-viewport/index.md

### Why is this update needed?
The `user-scalable="no"` parameter on the content attribute of the <meta name="viewport"> element disables browser zooming. This is inline with current native mobile Apps behaviour (no native zooming capabilities). As the web is becoming more and more PWA, this parameter seems quite inadequate.

Following the document published by [Deque University](https://dequeuniversity.com/rules/axe/3.3/meta-viewport) that legitimates this rule, this seems to be an opportunity to force PWAs to follow this accessibility best-practice. 

However, the recommended minimum value for `maximum-scale` in the source article is `2` and not `5` as mentioned. I can't find any reason why this number is different. Is there any reason behind?

Therefore, I ask to either add clarification about this value being `5` or reduce the value to `2`.

**Comment by samthor** [comment]
@robdodson is our a11y export. IIRC iOS now ignores `maximum-scale` too (although it's still seemingly possible to enforce it).

**Comment by robdodson** [comment]
> However, the recommended minimum value for maximum-scale in the source article is 2 and not 5 as mentioned. I can't find any reason why this number is different. Is there any reason behind?

I think this is probably a typo. Based on the Deque doc you shared it seems like the source article should recommend:

"Ensures that the user-scalable="no" parameter is not present in the <meta name="viewport"> element and the maximum-scale parameter is not less than 2."

**Comment by rachelandrew** [comment]
Closing as we are about to point all of these docs to the Deque University ones rather than hosting our own advice.
