### ISSUE TITLE
Author names missing from RSS feeds

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#3365]
Probably related: https://github.com/GoogleChrome/web.dev/pull/2897

This affects three files, all called `feed.njk`.

<img width="121" alt="Screen Shot 2020-06-25 at 16 12 47" src="https://user-images.githubusercontent.com/145676/85739137-d6367e80-b700-11ea-93b4-fa8e7b83280c.png">

**Comment by robdodson** [comment]
@MichaelSolati do you think you could give this a look?
