### ISSUE TITLE
eTDL should be TDL if I am not mistaken 

### ISSUE THREAD

**Issue by Wineric** [GoogleChrome/web.dev#3416]
**Describe the bug**
In the image explaining TDL the accronym eTDL is used.

**To Reproduce**
1. Go to 'https://web.dev/same-site-same-origin/#site'
2. In the top image you see, eTDL spans .com and eTDL + 1 spans example.com 

**Expected behavior**
To see a picture explaining TDL

**Screenshots**
![Screenshot 2020-07-01 at 08 23 56](https://user-images.githubusercontent.com/30693188/86210072-38b1d380-bb74-11ea-841b-341ae4d54b10.png)

**Comment by Wineric** [comment]
Hi guys,

I am not sure about this one since I am reading up on it (great article by the way) but I have a strong feeling after reading that TDL should be used in the image instead of eTDL

**Comment by agektmr** [comment]
`.com` is `TLD` but is also an `eTLD`. I'd keep it `eTLD` for simplicity.

**Comment by samdutton** [comment]
[.com in the Public Suffix List](https://publicsuffix.org/list/public_suffix_list.dat#:~:text=%2F%2F%20com)
