### ISSUE TITLE
[Post event] Add Q&A module

### ISSUE THREAD

**Issue by harleenkbatra08** [GoogleChrome/web.dev#3428]
Hey folks,

Here's the first set of questions across the Web Vitals and Performance categories. As a reminder, would love to have a message on top of the Q&A module where we can let folks know that we'll have more Q&A coming soon.

Thanks!

**Comment by harleenkbatra08** [comment]
Oh sorry, here's the link to the final questions: https://docs.google.com/document/d/1_-bo8thRmGMeIL1uNtLpXzgi6sok9atGNqHcqK52u38/edit#

**Comment by samthor** [comment]
I can do this tomorrow.
