### ISSUE TITLE
content: migrate HTML5rocks Drag and Drop

### ISSUE THREAD

**Issue by rachelandrew** [GoogleChrome/web.dev#3457]
* [draft](https://docs.google.com/document/d/1O3-8OkytzyRVAeJ6cd6hlHNNcg5TjygNzdfMrR1Q0X8/edit)
* next step: @rachelandrew to submit PR

history

* @kaycebasques Google Docs draft LGTM
* @kaycebasques reviewed on 7/22

**Comment by kaycebasques** [comment]
I think @mihajlija had already started work on this?

**Comment by rachelandrew** [comment]
there wasn't any note in the spreadsheet I don't think. Well let me know, I'd just run out of stuff to do and it looked like a reasonable target.

**Comment by mihajlija** [comment]
@rachelandrew I'm not working on this, please go ahead with your plan.
