### ISSUE TITLE
When I click on share button Chrome crash

### ISSUE THREAD

**Issue by gulshansainis** [GoogleChrome/web.dev#3466]
**Describe the bug**
When I click on share button Chrome crash 

Chrome Version: Version 83.0.4103.116 (Official Build) (64-bit)

**To Reproduce**
1. Go to https://web.dev/live/
2. Scroll down to Share section
3. Click on the Share button

**Expected behavior**
Once we click on the share button a list of supported websites should be displayed like, Twitter, facebook etc.

**Screenshots**
https://vimeo.com/user117608696/review/436641730/6d7daf7836

**Comment by robdodson** [comment]
@gulshansainis can you share a screenshot of what you see in the console? Unfortunately the vimeo link doesn't work (maybe it's private?)

![image](https://user-images.githubusercontent.com/1066253/87996897-653c7980-caa8-11ea-89f8-219d17449a22.png)

**Comment by gulshansainis** [comment]
Hi @robdodson 

I downloaded the video and made GIF. Please find attached same.

![ezgif-4-84867822fd87](https://user-images.githubusercontent.com/8197984/88042515-a8aaec80-cb69-11ea-9e21-04bdf3d0ae46.gif)

**Comment by robdodson** [comment]
@gulshansainis I'm not able to reproduce the issue, can you tell me a bit more information:

- What Chrome version are you on
- What operating system are you on
- What device are you using (it looks like a desktop computer, but want to make sure)

**Comment by gulshansainis** [comment]
Hi @robdodson 

Thanks for follow up. Please find below required details.

- **What Chrome version are you on**
    - Version 84.0.4147.89 (Official Build) (64-bit)
- **What operating system are you on**
    - macOS High Sierra
- **What device are you using (it looks like a desktop computer, but want to make sure)**
    - MacBookPro15 2018 Model

Please let me know if you need further information. I even disabled all extensions however, the result is same.

**Comment by robdodson** [comment]
@gulshansainis one last question... can you visit the site in an incognito window and try the share button. I'm wondering if you might have a Chrome extension installed that is causing a conflict. If it works in an incognito window then that might be one reason.

**Comment by gulshansainis** [comment]
@robdodson I already tried that. But app even crashed in incognito

**Comment by robdodson** [comment]
hey @gulshansainis, do you have Experimental Web Platform features enabled in chrome://flags ?

**Comment by robdodson** [comment]
It seems like there was an issue related to this a while back
https://bugs.chromium.org/p/chromium/issues/detail?id=736172

**Comment by gulshansainis** [comment]
@robdodson Yes you are correct.

After disabling all experimental features the functionality is working as expected.

Thank you again for investigation and helping me understand why this issue was coming
