### ISSUE TITLE
Update Lazy Loading Article now iFrames are in the spec

### ISSUE THREAD

**Issue by bazzadp** [GoogleChrome/web.dev#3468]
### What page(s) need to be updated?

https://web.dev/native-lazy-loading/

### Why is this update needed?

A warning was added in #2421 by @housseindjirdeh to note that native lazy loading iframes is currently non-standard. Its [now in the standard](https://github.com/whatwg/htm) so can this be removed?

Not sure if anything else needs updating based on what was actually standardised but a quick look suggests not.

**Comment by konojunya** [comment]
Sorry, the issue was duplicated. 
I would like to have a policy of solving with #3469.
