### ISSUE TITLE
The charts look weird in the print view of the homepage (with report)

### ISSUE THREAD

**Issue by pojda** [GoogleChrome/web.dev#3475]
**Describe the bug**
When you print the page, the charts look funny. (see screenshot below)

Chrome Version: 83.0.4103.116 (Official Build) (64-bit)

**To Reproduce**
1. Run a report
2. Hit cmd+p or anything to open the print preview
3. See error (the saved pdf also looks like that)

**Expected behavior**
A proper view of the reports

**Screenshots**
![image](https://user-images.githubusercontent.com/6998653/87133171-3e579980-c297-11ea-92a3-3acf05e62af8.png)

**Comment by pojda** [comment]
It's still there :)

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content/code on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
