### ISSUE TITLE
Have all new issues default to an untriaged status

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#3477]
The current process is that when new issues are created, they sit open for a period before the stalebot issues a warning, then autocloses them or someone comments to keep them alive. This results in three emails going to every GitHub user for every feature request. 

We could cut this spam by 2/3 if we just have new tickets default to to a status of undefined, untriaged, or backlog. (The name makes little difference to me). They could simply remain there until someone wants to use them. In addition to reducing spam, this has the added benefit of keeping new issues separate from closed issues that we actually worked on.

**Comment by robdodson** [comment]
> They could simply remain there until someone wants to use them.

Would the stalebot still close them? I'm not sure how adding an untriaged label would change things.

**Comment by jpmedley** [comment]
I'm suggesting that you create stage that doesn't require the action by the stale bot.

**Comment by robdodson** [comment]
Sorry, I still don't understand. The stalebot is there to close out issues that we haven't shown an interest or ability to work on. Unless I'm misunderstanding, this seems like working around that so issues persist indefinitely?

**Comment by jpmedley** [comment]
If you have the issues go straight to a 'new' bucket you don't need to do anything with them until you evaluate them. That means fewer emails.

Existing system

- Email for new feature.
- Email when it's marked stale.
- Email when someone says, "we need this".

What I'm suggesting

- Email for new feature.

Done.
