### ISSUE TITLE
content: Defer non critical CSS Firefox support

### ISSUE THREAD

**Issue by e111077** [GoogleChrome/web.dev#3512]
### What page(s) need to be updated?

* https://web.dev/defer-non-critical-css/

### Why is this update needed?

Firefox no longer seems to support the onload event on link[rel=preload]. It used to work, but now the glitch demo is broken on FF. Also, Lighthouse links to that article for a fix so it seems like it's a be-all-end-all coding pattern

### What's the deadline?

None

#### Is it a hard deadline?

Nope <3

**Comment by scofennell** [comment]
Works in Chrome, not firefox.

**Comment by kaycebasques** [comment]
@demianrenzulli can you confirm this no longer works in Firefox? Can you update your post if so?

**Comment by e111077** [comment]
Heya Kayce, can confirm that it works on FF stable now – thanks for the update!
