### ISSUE TITLE
The site is not working

### ISSUE THREAD

**Issue by Sebastiangperez** [GoogleChrome/web.dev#3519]
**Describe the bug**
The site is not working, im clicking in every place and nothing is refreshed, nothing is loaded, the site doesn't work. 

**To Reproduce**
1. Go to 'anything'
2. Click on 'anything'

**Expected behavior**
Site works , go to blog , test site , etc , nothing works

**Screenshots**

**Comment by robdodson** [comment]
Hi @Sebastiangperez 

I'm not able to reproduce the issue on my end. Could you open the console and let me know if you see any errors?

**Comment by Sebastiangperez** [comment]
Not errors found in the console only a warning  : 
DevTools failed to load SourceMap: Could not load content for https://web.dev/app.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
Im using Chrome Versión 84.0.4147.89 (Build oficial) (64 bits) on Fedora 30... this is strange , im tested  in Firefox and desn't work either

**Comment by robdodson** [comment]
Hm, it seems to be working for me in 84 on Ubuntu.

@Sebastiangperez can you try it in an incognito window. I was curious if maybe the service worker was doing something weird.

**Comment by robdodson** [comment]
@devnook I'm curious if this might be related to https://github.com/GoogleChrome/web.dev/pull/3503

@Sebastiangperez reported using "Chrome Versión" so I'm assuming the default language in the browser is not set to English (correct me if I'm wrong @Sebastiangperez). Perhaps a different language code is tripping up the spa navigation?

**Comment by Sebastiangperez** [comment]
Yes , its in spanish.

**Comment by robdodson** [comment]
@Sebastiangperez can you do me a favor? Can you try these two versions of the site and tell me if either one works:

- https://20200716t205223-dot-web-dev-production-1.uc.r.appspot.com/
- https://20200716t114456-dot-web-dev-production-1.uc.r.appspot.com/

If the problem is what I think it is then the second one should work.

**Comment by Sebastiangperez** [comment]
Yes , the second one worked 
https://20200716t114456-dot-web-dev-production-1.uc.r.appspot.com/

**Comment by robdodson** [comment]
ok, the first one is from when we deployed #3503 so I guess that's the cause. I'll do a revert and we can keep working on that feature. Thank you for filing the issue!

**Comment by Sebastiangperez** [comment]
Not problem man, I'm glad help.

**Comment by robdodson** [comment]
@Sebastiangperez if you have a chance could you try the site again? The deploy should be finished now.

**Comment by Sebastiangperez** [comment]
Yes , Works now , thanks 
I had to clean the cache.

**Comment by robdodson** [comment]
👍   thanks again!

**Comment by Sebastiangperez** [comment]
Anytime!!! 
If you need a hand in Google ... let me know , im available. ;)
