### ISSUE TITLE
content: Schemeful SameSite [2020-12-02]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3542]
* [draft](https://docs.google.com/document/d/1RuO8nZ2HWSLZFrF0fF0zqP9M2PVd8aa_QL-5VEhbFyw/edit)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/eVxoRTuzqmg)
* next step: @rowan-m to address feedback?

**Comment by jpmedley** [comment]
@kaycebasques This does not yet have an LGTM on an intent to prototype. https://groups.google.com/a/chromium.org/g/blink-dev/c/qB7DKqxkiaA/m/IEqPn3RYDgAJ

**Comment by kaycebasques** [comment]
@rowan-m from the comments in the draft it seems like you're going to edit the doc? LMK when it's ready for a TW review.

**Comment by jpmedley** [comment]
This has a draft, but the feature doesn't have a release date.

**Comment by rowan-m** [comment]
Draft in progress.

**Comment by jpmedley** [comment]
@rowan-m The last information I have is that this is having a staged roll-out in 8 stable. Would it be possible to get this article up for beta? (Beta is on 12/3, but I usually advise going live the day before, 12/2 in this case.)

**Comment by rowan-m** [comment]
Published https://web.dev/schemeful-samesite/
