### ISSUE TITLE
content: CSS Content Visibility [2020-07-28]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3543]
* [draft](https://docs.google.com/document/d/1hLT9of1rENxejNgyZW8E0X4k547nhkzsKMK7U_owCo0/edit#heading=h.skawfgvytwwk)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/0Sd37wv1DUE)
* next step: @kaycebasques to review

history:

* @kaycebasques reviewed on 7/24

**Comment by una** [comment]
Would it be possible to get a review on the draft before putting it a PR format?

**Comment by kaycebasques** [comment]
@una I'll review right now

**Comment by una** [comment]
@kaycebasques post is out of draft state with all of your comments addressed thus far. Let me know if I missed anything! Also added some video/images and adjusted some content. Thank you!
