### ISSUE TITLE
Videos on @property post aren't working on Safari

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3546]
**To Reproduce**

1. Go to https://web.dev/at-property/ in desktop or mobile Safari
2. Scroll to videos

**Expected behavior**

Videos should auto-play

**Screenshots**

![image](https://user-images.githubusercontent.com/4713486/88213383-879bd780-cc0d-11ea-92e5-1f09330e2ef3.png)

**Notes**

The videos are working in desktop Chrome on Mac

Videos are working in other pages on desktop and mobile Safari, so I think there's an issue with these particular video files

I converted the videos from GIF using ffmpeg

**Comment by kaycebasques** [comment]
I'm working on this. I'm going to try converting the videos again and re-uploading.

**Comment by kaycebasques** [comment]
Here are the source GIFs:

![support1](https://user-images.githubusercontent.com/4713486/88215111-07c33c80-cc10-11ea-838b-10a3a1725389.gif)

![demo](https://user-images.githubusercontent.com/4713486/88215121-0a259680-cc10-11ea-869e-54bf8a4b3b3d.gif)

**Comment by kaycebasques** [comment]
Tried this and doesn't seem to have worked: https://unix.stackexchange.com/a/294892/79351

**Comment by kaycebasques** [comment]
Might be a service worker issue: https://storage.googleapis.com/web-dev-assets/at-property/demo.mp4

**Comment by robdodson** [comment]
@kaycebasques what settings did you use to convert the video? I think i hit this once before
https://github.com/GoogleChrome/web.dev/issues/1407

**Comment by robdodson** [comment]
also worth checking: https://adactio.com/journal/14452

**Comment by jpmedley** [comment]
I poked into this (since I know something about video files). This is working locally on Safari Version 13.1.2 (14609.3.5.1.5).
