### ISSUE TITLE
Add a way to remove a URL / Tell the user when their URL is about to be removed.

### ISSUE THREAD

**Issue by hwikyounglee** [GoogleChrome/web.dev#355]
Currently there's no way to remove the URL. A work around is adding a different URL. 

Current: 
![image](https://user-images.githubusercontent.com/7561395/48190982-e5cd3d80-e2f8-11e8-8ba0-46fbd9ba357a.png)

https://web.devsite.corp.google.com/measure#

**Comment by robdodson** [comment]
In the near term, we're going to add a warning when the user is changing their URL to let them know that it will delete the data.

**Comment by robdodson** [comment]
Tracked in #709
