### ISSUE TITLE
Our excellent tags feature should be less buried

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3558]
We have this great tags feature:

![image](https://user-images.githubusercontent.com/4713486/88332436-6ad1d380-cce3-11ea-9065-2acbda8127a0.png)

But there's no mention of it in our navbar:

![image](https://user-images.githubusercontent.com/4713486/88332486-8046fd80-cce3-11ea-8ead-c4264e77de1d.png)

Or our footer:

![image](https://user-images.githubusercontent.com/4713486/88332534-92c13700-cce3-11ea-8333-f0fe882dc72e.png)

Or the homepage.

**Comment by robdodson** [comment]
Seems somewhat related to #3270

**Comment by jimoong** [comment]
We originally had a design like this. Maybe we can put some popular tags and "View all tags" at the end of list?
![Screen Shot 2020-07-29 at 10 06 23 AM](https://user-images.githubusercontent.com/1054804/88830717-33e83b80-d183-11ea-8ffe-9d1e748d8746.png)

And I also think the all tags view seems a bit in efficient (Too large text and redundant messages). Maybe multi column layout with list of tags indexed by alphabet could work. If anybody has capacity to make those changes, I can quickly mock them up.

**Comment by robdodson** [comment]
Thanks @jimoong. I think Joe and Kayce would really like to improve usage of tags on the site so if you're able to do a mock perhaps @MichaelSolati could work on implementing it (he added tags support to the site and our existing tags pages).

I would suggest prioritizing developers.chrome.com work first, and if there's extra time working on the tags feature. Otherwise we can save it for later since it's less time sensitive.

**Comment by Arsinam80m** [comment]
> We have this great tags feature:
> 
> ![image](https://user-images.githubusercontent.com/4713486/88332436-6ad1d380-cce3-11ea-9065-2acbda8127a0.png)
> 
> But there's no mention of it in our navbar:
> 
> ![image](https://user-images.githubusercontent.com/4713486/88332486-8046fd80-cce3-11ea-8ead-c4264e77de1d.png)
> 
> Or our footer:
> 
> ![image](https://user-images.githubusercontent.com/4713486/88332534-92c13700-cce3-11ea-8333-f0fe882dc72e.png)
> 
> Or the homepage.

**Comment by Arsinam80m** [comment]
arsinam80@gmail.com

**Comment by rachelandrew** [comment]
Closing due to DevSite move which has different options via Nomenclature.
