### ISSUE TITLE
Survey that is sent out is inaccessible when using a keyboard

### ISSUE THREAD

**Issue by Kilian** [GoogleChrome/web.dev#3562]
**Describe the bug**
You recently sent out [a survey](https://google.qualtrics.com/jfe/form/SV_0qtCmXB7oVdTkd7?PT=3) to web developers. In this software you can not `tab` to the next input.

**To Reproduce**

* fill in part of the survey until you get to a list of inputs
* focus an input
* press `tab`

**Expected behavior**
After pressing `tab`, I expect the focus to be on the next input, so I can continue typing in it. Unfortunately, focus just disappears.

**Screenshots**
Here's a gif:
![issue](https://user-images.githubusercontent.com/41970/88368055-81346980-cd8d-11ea-9616-fc15e8a08bce.gif)

**Comment by Kilian** [comment]
It seems to be an issue with just this (type of) page. The next page had a 10-item list of inputs in which tabbing _did_ work.

**Comment by robdodson** [comment]
Hi @Kilian, thanks for reporting this. My understanding is this survey was sent out by a vendor and it unfortunately went out before we had a chance to review it 🤦‍♂️

One of our team members also reported this issue to them and we've been told they can't change the basic functionality of the form. I'm going to request that we no longer use this format in the future.

**Comment by Kilian** [comment]
Thanks @robdodson :) :+1:
