### ISSUE TITLE
content: A Sidenav Component [2020-09-03]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3565]
* [draft](https://docs.google.com/document/d/1QJWdvxOwl-V1B7U9_-ZLD86L5gylLlEmDCPTPOBgWts)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/se_huYW36R0)
* next step: @kaycebasques to review

**Comment by argyleink** [comment]
will ship next month, reopening as it's getting worked on again

**Comment by argyleink** [comment]
draft ready for review 👍🏻

**Comment by argyleink** [comment]
The PR has the codelab ready for review as well. The PR's article content isnt far off from the Google doc, so I'm happy to get edits from either location. I'll make sure everything makes it into the PR 👍🏻
