### ISSUE TITLE
content: MercadoLibre [2020-08-17]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3566]
* [draft](https://docs.google.com/document/d/1u6U5sFTzK6j8ny9jN6HKFWrm5CjFxMzKl2FwbeoZjwc/edit)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/UZjovFQ0X1U)
* next step: @demianrenzulli is working with partner to see if any technical content can be expanded upon

**Comment by demianrenzulli** [comment]
Thanks for the update @kaycebasques! 

Right now, Mercado Libre's team is working on two things:

- Providing more technical details on the webpack + babel solution.
- Putting together a nice header for the article to transmit the brand + speed.

Will update this thread when we are ready to move forward.

**Comment by demianrenzulli** [comment]
It was added as a comment in the PR, but just in case the PR for this issue is here: https://github.com/GoogleChrome/web.dev/pull/3814.
