### ISSUE TITLE
content: service workers + payments [2020-09-03]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3567]
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/nZLCKnl5QN8)
* [orchestrating transactions](https://docs.google.com/document/d/15pHZItJqjhM2LDas61zf9ZamffwILHH049PUSjjWk6Y/edit#heading=h.3sphkjo8j8vt)
* [handling payment info](https://docs.google.com/document/d/14DWsGKfNhXaOEcJa1fRkW_F44e09KXSdER1tk6aHXR4/edit#heading=h.3sphkjo8j8vt)
* next step: @kaycebasques to continue reviewing

**Comment by agektmr** [comment]
I've shared the docs with edit access. You may start reviewing them.

**Comment by kaycebasques** [comment]
@agektmr I reviewed both, PTAL

**Comment by kaycebasques** [comment]
@agektmr please submit a PR
