### ISSUE TITLE
content: security collection updates [2020-12-31]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3568]
* [tracker](https://docs.google.com/spreadsheets/d/1UotH1cM_gIEt2HgOF23j_PqxzFtYMz2LK58sM1c1kEs/edit#gid=15561552490)
* next step: @kaycebasques to review the tracker

**Comment by agektmr** [comment]
Building /secure section as described in the tracker is a long term goal and keeping this issue until all is completed doesn't make much sense IMO. I would set the goal of this issue as 'resolve entries marked with "To be added an alias" in the tracker'.
For the rest of the migrations and new contents, they should individually send content proposals.
