### ISSUE TITLE
content: npm publishing best practices [2020-08-28]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3570]
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/nCvQd_YLKA8)
* next step: @developit & @housseindjirdeh to provide a draft

**Comment by GaryLChew** [comment]
Hey Kayce,
Thanks for opening the issue. I actually won't be the one working on this best practices guide anymore. @housseindjirdeh and/or @developit will be taking it over a couple of weeks from now.

**Comment by kaycebasques** [comment]
Thanks for the update @GaryLChew

**Comment by kaycebasques** [comment]
@housseindjirdeh & @developit please send me a link to a draft
