### ISSUE TITLE
Racial Equality Banner Overlapping Page Content

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#3584]
![image](https://user-images.githubusercontent.com/8204171/88710572-b57c9280-d0cb-11ea-8b5a-96a2ca9b12f8.png)

**Comment by robdodson** [comment]
This is working as intended. I believe the banner in that area is always allowed to overlap that image since the image is decorative.

**Comment by jpmedley** [comment]
It looks like crap. You're OK with that?

**Comment by jpmedley** [comment]
Seriously, who would intend to overlap other content?

**Comment by carolrivero** [comment]
@jimoong UX Designer can confirm that it's working as intended. IMHO, I don't see anything bad about the design. This boils down to preference.

**Comment by jpmedley** [comment]
Preference? It's covering other content. Please explain to me why this is acceptable. I genuinely don't understand.

**Comment by jimoong** [comment]
![web dev_ (1)](https://user-images.githubusercontent.com/1054804/88829002-e10d8480-d180-11ea-84c0-88b4be8ff97b.png)
![web dev_](https://user-images.githubusercontent.com/1054804/88829005-e23eb180-d180-11ea-81c4-44b4c5aca7c2.png)

Is the banner really overlapping the content? I see the banner pushes down the content when I tested it. (See the attached images) If the aesthetic is the problem, I may change colors and size a bit.

**Comment by robdodson** [comment]
I think this thread has gotten a bit heated so I'm going to suggest that we continue the discussion over chat.
