### ISSUE TITLE
content: migrate Resource Prioritization from Web Fundamentals

### ISSUE THREAD

**Issue by rachelandrew** [GoogleChrome/web.dev#3589]
#### Provide a brief summary of your content proposal

Migrating the content from https://developers.google.com/web/fundamentals/performance/resource-prioritization

* Place content under a new web.dev/fast section, maybe web.dev/fast#resource-prioritization
* Move the existing Preload guide to this section (it currently lives under https://web.dev/fast/#optimize-your-javascript)
* The Preconnect and Prefetch sections should probably be split up into separate pages
* We already have a Preload guide investigate if there is content from the old Preload guide that should be added to the existing one
* The intro paragraph and Default priorities in the browser section seem like they can be the basis of an overview page, e.g. web.dev/resource-prioritization

Once done redirect the Web Fundamentals page to this new page and delete the content from there.

#### Who will be authoring the content?

@rachelandrew 

#### What area is your content related to?

Performance

#### What kind of content are you creating?

Guide

**Comment by rachelandrew** [comment]
@kaycebasques In working on this, I've found we also already have:

- [Establish network connections early to improve perceived page speed](https://web.dev/preconnect-and-dns-prefetch/) - covers preconnect
- [Prefetch resources to speed up future navigations](https://web.dev/link-prefetch/)

These also cover similar ground to the two articles split out from the Web Fundamentals article. I don't think they are currently linked from /fast though.

Do you want the additional articles or should I merge in anything useful into these and link them in that section?

**Comment by kaycebasques** [comment]
Good catch finding those old articles.

* Let's proceed with creating a web.dev/fast#prioritize-resources section consisting of:
  * https://web.dev/preload-critical-assets/
  * https://web.dev/preconnect-and-dns-prefetch/
  * https://web.dev/link-prefetch/
* If there's anything from the [old guide](https://developers.google.com/web/fundamentals/performance/resource-prioritization) that seems useful and isn't covered in the existing web.dev guides, please migrate that stuff
* Set up the redirect in google/webfundamentals (as per usual) to redirect the old guide to `https://web.dev/fast/#prioritize-resources
* Note that I previously referred to `https://web.dev/fast/#resource-prioritization` but I just realized we should rephrase to `…#prioritize-resources` to make it action-oriented and consistent with the rest of the section headings

Thank you 🙏
