### ISSUE TITLE
Add trust-and-safety tag?

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3601]
* Should we have two tags (`trust` and `safety`) or one? In other words, will we ever have content where `trust` applies but `safety` doesn't and vice versa?
* Is `trust-and-safety` different from `privacy` and `security`?

CC @rowan-m @samdutton @agektmr @maudnals @jpmedley

**Comment by agektmr** [comment]
I don't think it's important to have `trust-and-safety` tag as long as there's `privacy` and `security` even separately.

**Comment by jpmedley** [comment]
I think `security` and `privacy` are the way to go. "Use definite, specific, concrete language." (Strunk and White, rule II-16.) All of these terms are nebulous in some way. But `security` and `privacy` have definite meanings for our audience. Trust and safety sound like terms you'd use with a non-technical audience.
