### ISSUE TITLE
<heading> should be <header> in Lighthouse docs

### ISSUE THREAD

**Issue by Ksan8** [GoogleChrome/web.dev#3606]
**Describe the bug**
The Lighthouse documentation currently has a slight error, where the element `<heading>` (which does not exist) is referred to instead of the correct element, `<header>`.

**To Reproduce**
1. Go to https://web.dev/bypass/?utm_source=lighthouse&utm_medium=devtools
2. Scroll down to the section that begins: "Lighthouse checks that the page contains at least one of the following:"
3. Notice that the first bulleted item is "A `<heading>` element"

**Expected behavior**
The user should see "A `<header>` element" as the first bulleted item.

**Screenshots**
![Screen Shot 2020-07-30 at 2 55 08 PM](https://user-images.githubusercontent.com/20333203/88978564-cfa5a480-d274-11ea-8dc4-2732fd027678.png)

**Comment by robdodson** [comment]
@kaycebasques are you cool taking this one?

**Comment by ecarlisle** [comment]
Hi @robdodson , @kaycebasques : I hope it was ok to put in a PR for this.  Happy to help if I can!
https://github.com/GoogleChrome/web.dev/pull/3731
