### ISSUE TITLE
Not a bug, looking for translated versions of webpage

### ISSUE THREAD

**Issue by nikkihau-mktg** [GoogleChrome/web.dev#3643]
Hi there – I work for Shopify's marketing team and am looking to link to [this page](https://web.dev/performance-scoring/) as part of a performance feature we have that uses Lighthouse to calculate a merchant's store's performance. 

Can't seem to get the translated version for French, German, Italian, Japanese, Brazilian Portuguese, European Portuguese, Chinese, Dutch and Spanish. 

Not sure if this is a bug or this page has just not been translated. Thank you!

**Comment by robdodson** [comment]
Hi @nikkihau-mktg 

We're currently working on localizing the site. Our hope is to start rolling out translated pages this quarter.

**Comment by nikkihau-mktg** [comment]
Thanks @robdodson !
