### ISSUE TITLE
Special banner for features behind a flag, OTs, deprecated, etc

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#3646]
**Is your feature request related to a problem? Please describe.**
It can be hard for developers to understand the availability of an API. Is it available behind a flag? Is it available as an Origin Trial? Has it been deprecated and no longer recommended? Is it mobile only? etc. This is especially true for Fugu features as they move through their life cycle, but there are many other APIs we document on web.dev that have the same issue. While we try to make it clear in the docs that something is OT only, or behind a flag, sometimes it's not clear enough.

**Describe the solution you'd like**
I would love to see a banner (similar to the [Fork me on GitHub banner](https://simonwhitaker.github.io/github-fork-ribbon-css/)) that makes it clear a feature is available in a limited scope. I am open to other ideas since it could be hard to overload the banner for OT+Mobile, or other combinations.

This is somewhat related to #3311, and would be nice to be able to have it happen according to the YAML front matter, for example adding an `ot_completion` attribute with a date that would either remove the banner, or flag it for review.

**Comment by jpmedley** [comment]
+100

**Comment by jpmedley** [comment]
I support this, though you should know that I'm not allowed to mention
flags in the beta post.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by robdodson** [comment]
That sounds like a good addition. @jimoong is this something you work with @petele on? Pete — I think we'd need a list of different banner types that you'd want to see and if Jiwoong has bandwidth we can work on mocking them up.

**Comment by jpmedley** [comment]
Sometimes flags and OTs happen at the same time. It would make pages look less busy if a single banner could reflect two states simultaneously (as opposed to having separate banners.)

**Comment by petele** [comment]
> Sometimes flags and OTs happen at the same time

@jpmedley - can you give an example of that? I can't think of any cases where that's happened and the flag/ot isn't overlapping.

**Comment by petele** [comment]
Here are the things I think would be great to be able to flag:

* **Behind a Flag** - The feature is experimental and is only available behind a flag. (P0)
* **Origin Trial** - The feature is only available in an origin trial. (P0)
* **Deprecation/Action Required** - We're changing/deprecating a feature that will require developer action. I'm thinking things like same-site cookies, removal of AppCache, changes in web components v0/v1 (P1)
* **Mobile Only** - There are a handful of features that are mobile only, let's make it clear that they are mobile only (P2)
* **Desktop Only** - There are a handful of features that are desktop only, let's make it clear that they are desktop only (P2)

**Comment by jpmedley** [comment]
>can you give an example of that?

We don't have anything like that currently. I've seen it though.

>**Deprecation/Action Required**

Need to add Removed. things don't stay deprecated forever.

>**Mobile Only** - There are a handful of features that are mobile only, let's make it clear that they are mobile only (P2)
>**Desktop Only** - There are a handful of features that are desktop only, let's make it clear that they are desktop only (P2)

We may need more granularity than these. 'Mobile only' is sometimes 'Android only' meaning it excludes WebView. Background Sync and Background fetch are examples of this. Since desktop is actually 3 different platforms, hardware APIs have a likelihood of not shipping all at once.

**Comment by robdodson** [comment]
I think this is part of #3807 and we can do a bit of design work around it.

**Comment by jpmedley** [comment]
FYI, over in Chrome development world, 'Behind a flag' is being transitioned to 'Developer trial'.

![image](https://user-images.githubusercontent.com/8204171/113725217-f475d580-96a7-11eb-9a41-52e5ebb0a775.png)

**Comment by robdodson** [comment]
Per recent discussions, I'm wondering if stuff that's behind a flag or origin trial should actually be on developer.chrome.com. I'm not saying that we shouldn't build this banner, but if we do, we may want to do it on d.c.c. first.

**Comment by jpmedley** [comment]
I'm not crazy about putting anything on a standards track on d.c.c., even temporarily. I ask that you hold off on the decision until we've had a chance to talk about the writer's equivalent of technical debt in a 1:1. I'm hoping there's a clever technical solution to my concerns that will satisfy yours as well.

**Comment by rachelandrew** [comment]
Closing due to new channel strategy meaning these experimental things will be moved to DCC.
