### ISSUE TITLE
Only deploy if HEAD is different from what's currently deployed

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#3655]
**Is your feature request related to a problem? Please describe.**
We recently switched to deploying the site hourly. This is great, but it also means we're often deploying the same version of the site.

**Describe the solution you'd like**
We should only deploy if HEAD is different from the current live site.

Pete mentioned that on webfu they used a git-head.txt file to compare versions. I think the only downside to that approach is needing to check the git-head.txt file into source control with every PR.

Other options:

- Write the version to a meta tag on the homepage and fetch the homepage to do the comparison during a build. Pete pointed out that this would mean invalidating the homepage whenever any other part of the site changes, which could cause our service worker to throw out the cached file.
- Have Eleventy generate a file that is git ignored that contains the version number and gets served by the server at `https://web.dev/version.json`. Then compare HEAD to that file.
- Use GitHub Action's artifacts feature to upload the version to GitHub. When an Action runs it can fetch the artifact and compare it against HEAD to see if it needs to deploy.

**Comment by robdodson** [comment]
cc @GoogleChrome/web.dev-eng

**Comment by samthor** [comment]
Another possibility: use the HEAD value as the version deployed to App Engine. We can check if that version is already deployed and skip if so.

**Comment by robdodson** [comment]
Hm... i wonder how this would work in a Firebase world...

I wonder if we should create a version.txt file or something as part of the deploy and dump the info there and sneak it into the firebase deploy. Then we'd fetch that file to check?
