### ISSUE TITLE
Link to Next Article Missing

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#3673]
**Describe the bug**

In the learning section, I thought there were supposed to be links between pages of a section. They seem to be mising.

![JqVxjeMeZcC](https://user-images.githubusercontent.com/8204171/89815094-0becc680-daf9-11ea-96a2-4385f54f7b13.png)

**To Reproduce**
You can view this on any sub page in the Learn section, [here, for example](https://web.dev/apply-instant-loading-with-prpl/).

**Comment by MichaelSolati** [comment]
This was purposely removed. I believe the concern was in scenarios where an article would belong to two learning paths that we couldn't properly direct the user. Though I need @robdodson to confirm.

**Comment by robdodson** [comment]
Correct, it was purposefully removed as folks began filing issues because if a doc is in two collections, we had to choose one to send them to and it was confusing. If someone arrives on a post via Google search, they don't have any history so choosing which collection item is next is a bit of a guessing game.

I think our current collections feature is most similar to what css-tricks uses (https://css-tricks.com/guides/how-to-think-like-a-front-end-developer/) where items are essentially a post first, and part of a collection as a secondary effect.

**Comment by robdodson** [comment]
I should add: I don't think this is an ideal setup, it just is what it is.

Sometimes our team writes a collection all at once, and the docs are clearly related. But just as often they write the posts piecemeal and add them to an existing collection.

One of the things they do on css-tricks is add an additional navigation to posts that are part of an explicit series (https://css-tricks.com/an-introduction-to-web-components/). We could someday explore adding this but we'd want to ensure that those posts would only be used in a single collection.

**Comment by jpmedley** [comment]
I'll have to pay better attention to those things. This actually affects
the text that connects one article to another in things that are definite
collections. Did Kayce take notice of this?
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by robdodson** [comment]
> Did Kayce take notice of this?

cc @kaycebasques 

We may have discussed it but I don't recall. It was a while ago and the decision was a long time in the making. Ewa finally did the work when she had a spare cycle.

FWIW we checked analytics and found that the buttons were almost never used, but I'm happy to brainstorm alternative solutions.

One option would be to let authors create explicit linkages to the next article, maybe an include that they can use or a YAML property.
