### ISSUE TITLE
The Read files in JavaScript post don't have access to Glitch project

### ISSUE THREAD

**Issue by nucliweb** [GoogleChrome/web.dev#3683]
**Describe the bug**
The Read files in JavaScript post don't have access to Glitch project

**To Reproduce**
1. Go to https://web.dev/read-files/
2. Scroll down to see the text `This example lets a user select multiple files using their operating system's built-in file selection UI and then logs each selected file to the console.`
3. You can't see the embebed Glitch project

**Expected behavior**
See the Glitch project into the iframe.

**Screenshots**

<img width="670" alt="You've used all your project hours for this month! Your 1,000 project hours will reset on the first of the next month." src="https://user-images.githubusercontent.com/1307927/89890780-3a8b9f80-dbd4-11ea-9b4f-599b7139e496.png">

**Comment by robdodson** [comment]
Thanks @nucliweb, we're working on it :)

**Comment by robdodson** [comment]
Spoke with @kaycebasques about this. He's getting them boosted now.

**Comment by nucliweb** [comment]
Now it is works fine, thanks @robdodson and @kaycebasques 😊
