### ISSUE TITLE
content: update "Making your website "cross-origin isolated" using COOP and COEP" [2020-09-02]

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#3689]
### What page(s) need to be updated?

https://web.dev/coop-coep/

### Why is this update needed?

[Cross-origin opener policy reporting API](https://www.chromestatus.com/feature/5755687994916864) is expected to ship in Chrome 86.

### What's the deadline?

2020-09-02

#### Is it a hard deadline?

It's shipping in Chrome 86 and changes must be live before beta and the beta release post on September 3.

**Comment by agektmr** [comment]
I think this one is sorted. Thanks @jpmedley for the reviews!
