### ISSUE TITLE
content: WebCodecs [2020-10-14]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3695]
* [draft](https://docs.google.com/document/d/1Ncab_0j2EzFz72qgwmGxbOMLTTnlSWID627j6E8c2YU/edit)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/m6yIXjVdsKY)

**Comment by jakearchibald** [comment]
Fwiw, I'm a little concerned about the state of this API as it approaches origin trial. It wouldn't surprise me if it slipped.

**Comment by jakearchibald** [comment]
Almost certain to slip.

**Comment by kaycebasques** [comment]
Thanks for the update 👍

**Comment by freetoken-Tg1483** [comment]
Thanks for the update 😀

""spread your wings and fly""

**Comment by jpmedley** [comment]
@jakearchibald, WebCodecs has approval for an OT. Do you know if it will make Chrome 87?

**Comment by freetoken-Tg1483** [comment]
No doubt it will reach chrome 87.

""spread your wings and fly""

**Comment by jakearchibald** [comment]
I don't know what the state of this proposal is anymore. It looked like progress was being made, and things were heading in the right direction, but I'm now running against CDS deadlines so won't be taking additional work on.

**Comment by jpmedley** [comment]
Husain Bengali (hbengali@google.com) and Eugene Zemtsov (ezemtsov@google.com) have agreed to step in.
