### ISSUE TITLE
content: camera pan-tilt-zoom [2020-10-15]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3723]
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/f1dzo-Fm_FU)
* [draft](https://docs.google.com/document/d/1SzEmap7LM0V5qYJ1T0LIkslUoAiHmqekrne5beWU-SI/edit)
* next step: @jpmedley to review

**Comment by beaufortfrancois** [comment]
_(leaving a comment)_

**Comment by jpmedley** [comment]
@beaufortfrancois Is this shipping in Chrome 87? We're about four weeks away from beta.

**Comment by beaufortfrancois** [comment]
I don't know yet. We should know in the coming days.

**Comment by jpmedley** [comment]
Do yo have CDS talks, and would you need help getting an article by October 15?

**Comment by jpmedley** [comment]
Reviewed. Time for a PR.

**Comment by beaufortfrancois** [comment]
And here it is: https://github.com/GoogleChrome/web.dev/pull/3923

**Comment by beaufortfrancois** [comment]
This can be closed as https://web.dev/camera-pan-tilt-zoom/ is now live
