### ISSUE TITLE
icate whether to send a cookie in a cross-site request by specifying its SameSite attribute Because a cookie's SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which will prevent the cookie from being sent in a cross-site request in a future version of the browser. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.  Resolve this issue by updating the attributes of the cookie:

### ISSUE THREAD

**Issue by freetoken-Tg1483** [GoogleChrome/web.dev#3733]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by robdodson** [comment]
hm. @rowan-m can you take a look at this?

**Comment by rowan-m** [comment]
There are a number of cookies set from third-party domains, e.g. `googleusercontent.com`. The warning indicating a lack of a `SameSite` attribute is not necessarily an indicator of a problem. Those cookies will have been restricted to first-party contexts only and from what I can see, this does not affect web.dev functionality. DevTools is working to minimise noise from third-party services in the Console / Issues tab where there isn't an immediate action the first-party developer can take.

This bug should be re-opened if there are specific cookies from the `web.dev` domain that are not labelled with a `SameSite` attribute or if one of the third-party cookies is causing something on `web.dev` to break.
