### ISSUE TITLE
Fix typo on content, "Customize media notifications and playback controls with the Media Session API"

### ISSUE THREAD

**Issue by idorenyinudoh** [GoogleChrome/web.dev#3734]
Section with typo - https://web.dev/media-session/#seek-backward-forward

This update is needed because a grammatical error could make readers misunderstand a section of an article.

**Comment by idorenyinudoh** [comment]
@beaufortfrancois it's your articleeeee 😭😭😭

**Comment by beaufortfrancois** [comment]
Can you point out the typo?

**Comment by idorenyinudoh** [comment]
Sure!

The "seekbackward" action indicates that the user wants to **moves** the media playback time backward by a short period while "seekforward" indicates a desire to move the media playback time forward by a short period. In both cases, a short period means a few seconds.

**Comment by beaufortfrancois** [comment]
Thank you! I've filed https://github.com/GoogleChrome/web.dev/pull/3743 to fix it.

**Comment by idorenyinudoh** [comment]
You're welcome!
