### ISSUE TITLE
Turn /en/index.njk file into a layout in the _includes directory,

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/web.dev#3769]
We should turn /en/index.njk file into a layout in the _includes directory, instead of copying it. Current concern is keeping it in sync over time. If we make a change to the HTML we'll want that to show up in all languages but it could be easy to forget to copy it over.

**Comment by devnook** [comment]
From Rob: For the strings of text that appear in this file I think there are a few options. We could either move all of that text into the YAML front matter or the file and just translate those strings. Or we could create a file of translated strings and use eleventy data to access that file. For example, I think something like this might be possible:

/_includes/homepage.njk

<a class="w-button" href="/blog">
  {% helpers.translate('See all articles', lang) %}
</a>

**Comment by devnook** [comment]
I think we could also keep language content in index.md file instead of yaml, e.g. using named blocks.

**Comment by robdodson** [comment]
This seems like it's complete unless i'm mistaken? Going to close.
