### ISSUE TITLE
Localize strings in our js components and shortcodes

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/web.dev#3775]
We need to decide how we want to localize the handful of strings in our js components and shortcodes. It might be that we use the string file + function only for those widgets.

In nunjucks you can put a function into the _data folder and do something like:

// _data/i18n.js
const translate = (key, string) => {...}
module.exports = {translate};

<div>{{ i18n.translate(blah_key, "Blah string") }}</div>

Lighthouse uses this approach 
(https://github.com/GoogleChrome/lighthouse/blob/41175fec205f735d3303bff615b89c6d3d03f9da/lighthouse-core/lib/i18n/README.md)

**Comment by robdodson** [comment]
I think we can implement a system similar to web.dev where we have a yaml file which contains translation strings and a filter that pulls from it.

**Comment by robdodson** [comment]
Closing in favor of #4636
