### ISSUE TITLE
Web App Manifest Generator doesn't work

### ISSUE THREAD

**Issue by peppemath** [GoogleChrome/web.dev#3786]
The Web App Manifest Generator doesn't work (https://app-manifest.firebaseapp.com/):

when i try to generate the zip file i have:
"Go 1.9 is no longer available. Please refer to https://goo.gl/aESk5L for more information."

**Comment by samthor** [comment]
This seems to be fixed for me. Can you try again?

**Comment by samthor** [comment]
Oh, sorry. I noticed it fails only on the final step.

**Comment by samthor** [comment]
I've raised this with the original author of that tool. It's not really a web.dev bug.

**Comment by mbleigh** [comment]
TIL that web.dev pointed to a tool I built five years ago and forgot about... 😆

I will try to dig up the source code and resurrect the service, but I can't make any guarantees. Whoops!

**Comment by peppemath** [comment]
Ok, no problem: the only thing is that if there is a tool this should work otherwise it should be deleted
Ciao!

**Comment by robdodson** [comment]
@peppemath did you see this linked from a web.dev article? Doing a quick search of the site, I don't see any articles linking to the app manifest generator?
