### ISSUE TITLE
content: add description for compositor failure reasons

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/web.dev#3790]
### What page(s) need to be updated?

https://web.dev/nonncomposited-animations/

### Why is this update needed?

Compositor failure reasons can be confusing on their own in Lighthouse.  It would be best to have more detailed descriptions for each failure reason when someone clicks the "Learn more" link.

The detailed descriptions should probably go in the "How to ensure animations are composited" section and be some variation of the following:

"**_Unsupported CSS Property_**": The animation uses a CSS property other than `transform`, `opacity` or `filter`.

"**_Transform related property depends on box size_**":
- Transform value is a percent: `transform: translateY(100%);`
- Transform value is the result of `calc()`: `transform: translateY(calc(100% + 50px));`

"**_Filter related property may move pixels_**":
- Filter is a blur: `filter: blur(5px)`
- Filter is a drop-shadow: `filter: drop-shadow(10px 10px 20px red);`
- Filter is a reference to as SVG element: `filter: url("/example.svg#element-id");`

"**_Effect has composite mode other than "replace"_**":
- Composite mode is additive: `element.animate(myKeyframes, {composite: 'add'});`
- Composite mode is accumulative: `element.animate(myKeyframes, {composite: 'accumulate'});`

"**_Target has another animation which is incompatible_**": Two or more animations on the same element are operating on the same CSS property.

"**_Effect has unsupported timing parameters_**": 
- Effect has 0 playback rate: `myAnimation.playbackRate = 0;`
- Start delay is effectively +/- infinity: `element.animate(myKeyframes, {delay: 9223372036854775807});`
- Effect has non-zero end delay: `element.animate(myKeyframes, {endDelay: 50});`
- Iteration duration is undefined, auto, 0, etc.: `element.animate(myKeyframes, {duration: 'auto'});`

### What's the deadline?

9/26/20

#### Is it a hard deadline?

No

**Comment by kaycebasques** [comment]
@adamraine do you want to update the doc?

**Comment by adamraine** [comment]
Sure, I can put together a PR for this.

**Comment by adamraine** [comment]
Unfortunately I don't think I have the bandwidth to finish this anymore. It's pretty low priority, doesn't seem like there is an urgent need for this on the LH side.

I'm going to close for now.
