### ISSUE TITLE
Table of contents should better reflect the heading hierarchy

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/web.dev#3791]
**Is your feature request related to a problem? Please describe.**

When scanning the TOC in the sidebar for a page that has lots of headings at various hierarchies (e.g. h2, h3, h4), it can be overwhelming to see so many links with no apparent organization.

**Describe the solution you'd like**

Consider the TOC on https://web.dev/fid/, here's how it looks now versus how I think it could be improved:

![toc](https://user-images.githubusercontent.com/326742/91360742-de1ba900-e7ab-11ea-887f-1d812c282582.png)

Even a small amount of indentation help clearly show which headings are part of which larger section blocks.

**Comment by jpmedley** [comment]
+1

**Comment by robdodson** [comment]
btw we had to rollback the ToC because it was causing a horizontal scroll on some screens. We'll try to factor in these changes when we roll it back out

**Comment by MichaelSolati** [comment]
I think this can be enabled with a quick flag change in the config and some styling. But like @robdodson it'll have to wait for the scroll issue to be resolved.

**Comment by jpmedley** [comment]
I may have suggested this elsewhere. Maybe do an inline collapsable ToC like wikipedia does, but have it default to collapsed. 

This would have another advantage. @kaycebasques has asked to collect analytics on ToC usage. I've pointed out that one deficiency of that plan is that doesn't capture who's merely reading the ToC to get a sense of the article. If users must open the ToC to read it, we'll have stats on it.

![image](https://user-images.githubusercontent.com/8204171/92017376-854a9400-ed08-11ea-882d-1ec3dbdab4aa.png)

**Comment by robdodson** [comment]
d.c.c. uses a combination of an inline ToC (on smaller screens) and a ToC on the right for larger screens. I think we should do something like that and maybe redo our ToC implementation using a similar approach as d.c.c.

**Comment by jpmedley** [comment]
All I'm rooting for is hierarchical. When done right, ToCs convey information about the article and, ideally, the story told therein. Where and how is your domain.

**Comment by robdodson** [comment]
Closing in favor of #4352
