### ISSUE TITLE
content: Learning from Mini Apps [2020-09-15]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3794]
* [draft](https://docs.google.com/document/d/1I9RjlSE1XbNgmBOVgxHpUY8yO5pUYgJ7Nop5UopSSyI/edit)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/GKLZuapk9YI)
* next step: @kaycebasques to align on thread

**Comment by tomayac** [comment]
Still active.

**Comment by tomayac** [comment]
Active

**Comment by tomayac** [comment]
Active

**Comment by tomayac** [comment]
Active

**Comment by tomayac** [comment]
Active
