### ISSUE TITLE
content: Origin isolation [2020-10-15]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3795]
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/-dDIqsHcw8E)
* [draft](https://docs.google.com/document/d/1HfZTTXFP8itW8-Z1HuuMap1EpNtdlfa0eAulsuTk6eM/edit?usp=sharing)

**Comment by jpmedley** [comment]
This has been in an origin trial since 84. A little haste would not be out of order.

**Comment by domenic** [comment]
This is ready for review at https://docs.google.com/document/d/1HfZTTXFP8itW8-Z1HuuMap1EpNtdlfa0eAulsuTk6eM/edit?usp=sharing.

**Comment by kaycebasques** [comment]
Thanks @domenic I'll review

**Comment by jpmedley** [comment]
@domenic Is this ending its origin trial in 87?

**Comment by kaycebasques** [comment]
@jpmedley regarding your question:

> Is this ending its origin trial in 87?

I pinged @domenic about that and he said: 

> We're hoping for GA release in 87, indeed, pending API owners approval.

**Comment by domenic** [comment]
Heya, an update here: due to a lack of data from the origin trial so far, we're planning on pushing back the launch plan to 88, and instead extending the experiment through 87. So, any beta blog posts for 87 should not include Origin Isolation (unless you announce experiment continuations?), and this article should change its date to 2020-12-03.

**Comment by jpmedley** [comment]
I think we're good. The announcement of the start of the OT in Chrome 84
did not include an end version. The intro to OTs in beta posts always
includes a link to the OT dashboard where people can see what trials are
open.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by domenic** [comment]
Comment.

**Comment by domenic** [comment]
Comment. @kaycebasques, this feature is launching in M88, so please let me know what the next steps are!
