### ISSUE TITLE
`p` tag above embedded Glitch components overlays them

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#3800]
**Describe the bug**
`<p>` tag above a Glitch component (`{% Glitch %}`) overlays the component.

<img width="894" alt="glitch-embed-broken" src="https://user-images.githubusercontent.com/218144/91536650-f9271e00-e94f-11ea-91f1-2615bd71b012.png">

**To Reproduce**
See Glitch component at: https://deploy-preview-3642--web-dev-staging.netlify.app/orchestrating-payment-transactions/#sample-code

**Screenshots**
You can fix it by adding following CSS:

```
.glitch-embed-wrap {
  margin-top: 28px;
}
```

Here's how it will look
<img width="893" alt="glitch-embed-fixed" src="https://user-images.githubusercontent.com/218144/91536763-2ecc0700-e950-11ea-83e6-b011c412b45c.png">

Since I don't know which file I should add the above code, I'd just leave this issue here.

**Comment by robdodson** [comment]
Ah I think it's because the `w-label` class applies a negative 28px bottom margin, which we probably don't want.
