### ISSUE TITLE
content: Change "Feature Policy" references to "Permission Policy"

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#3801]
* Use this template to request updates to existing content.
* Delete any fields that aren't relevant to your issue. 
* Update the title of this issue with a brief summary of the work to be done.

### What page(s) need to be updated?

The following article are already on web.dev:

- [x] metrics/cls/index.md
- [ ] blog/coop-coep/index.md
- [x] blog/text-fragments/index.md
- [ ] blog/image-policies/index.md
- [ ] blog/migrate-to-ua-ch/index.md
- [x] blog/user-agent-client-hints/index.md
- [ ] blog/reporting-api/index.md
- [ ] blog/reporting-observer/index.md
- [x] blog/async-clipboard/index.md
- [x] https://web.dev/usb/ (6 references) -> now redirects to dcc
- [ ] blog/usb/index.md
- [ ] https://web.dev/coop-coep/

The following pages need to be converted to web.dev:

- [x] https://developers.google.com/web/updates/2017/09/autoplay-policy-changes -> redirects to dcc
- [x] https://developers.google.com/web/updates/2018/10/watch-video-using-picture-in-picture -> dcc
- [x] https://developers.google.com/web/updates/2018/09/reportingapi -> dcc
- [ ] https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/client-hints -> **now 404**
- [x] https://developers.google.com/web/updates/2018/09/inside-browser-part4 -> dcc

This project also includes #3802

### Why is this update needed?

Feature Policy is [being renamed Permission Policy](https://www.chromestatus.com/feature/5745992911552512)

More information: https://docs.google.com/document/d/1xaFsXXq0buy3Wi5lbUZ05WvheFJ4qoIzoK0Bs30z9Kw/edit

### What's the deadline?

Unknown. Will be October 14, if the change makes it into Chrome 87.

#### Is it a hard deadline?

Yes.

**Comment by jpmedley** [comment]
I'm actually working on this. I'm just a little behind.

**Comment by jpmedley** [comment]
This isn't finished.

**Comment by AaronForinton** [comment]
Hi @rachelandrew, wondering if this is one I can support with?

**Comment by rachelandrew** [comment]
@AaronForinton that would be great (I'm just poking around old issues this morning).

The state of things might be different from listed above, but essentially if you find anything that mentions Feature Policy on this site, it likely should be Permission Policy.

**Comment by AaronForinton** [comment]
@rachelandrew I've opened two PRs (I realised there's a few things to clear up in dcc too) on this. I won't link them to this PR until you can say you're satisfied this is all done.

Also I realised a Russian article needed to move that I had left behind in an earlier PR.

**Comment by AaronForinton** [comment]
@rachelandrew I think we might be able to close this one now.
