### ISSUE TITLE
dynamic-import-loading glitch is failing to build.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#3806]
The dynamic-import-loading glitch on this page https://web.dev/code-splitting-with-dynamic-imports-in-nextjs/ is failing with the following error.

![image](https://user-images.githubusercontent.com/1066253/91765239-7d1a1980-eb8d-11ea-9a52-e5fe78f10185.png)

@mihajlija could you take a look?

**Comment by mihajlija** [comment]
@robdodson Fixed. Two .js files were missing from the project, I had a backup so I just added them back in. 

Could this be a glitch (pun intended, sorry) related to project "boosting" process? I checked the rewind to see who/when deleted the files and the history was empty.

**Comment by robdodson** [comment]
Hm good question. I'm really not sure. I heard other folks mention that a few months back Glitch had corrupted one of their projects.
