### ISSUE TITLE
site: Automate Fugu landing page article list

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#3807]
Explore ways to automate the article list on https://web.dev/fugu-status/.

**Comment by tomayac** [comment]
Active

**Comment by tomayac** [comment]
Active

**Comment by tomayac** [comment]
Active

**Comment by tomayac** [comment]
Alive

**Comment by robdodson** [comment]
@tomayac

What would the ideal solution look like to you? Can you share a list of requirements?

**Comment by tomayac** [comment]
- Keep the static parts as is.
- List all articles tagged with `capabilities` (but excluding `case-study`).
- For each article:
  - Blurb that introduces the feature.
  - The feature's progress (Launched in `$version`, Origin Trial `$fromVersion`–`$toVersion`, Dev Trial).
  - Metadata about when the article was last updated.
- Whenever a new article tagged with `capabilities` (but excluding `case-study`) lands on the site, it should be added to the list.

@beaufortfrancois, anything else you'd add? Some metadata may be available through @Snugug's [tracker](https://fugu-tracker.web.app/).

**Comment by tomayac** [comment]
Still interested.

**Comment by tomayac** [comment]
Active

**Comment by robdodson** [comment]
I understand the intent of this proposal but I'm not sure I agree on its scope. I think the general request is for a way to show the status of a set of APIs that are in an initiative, and to link up all of their related docs. Sort of like https://jakearchibald.github.io/isserviceworkerready/.

IMO this feels like a custom page type, something we would want to dedicate some design effort to. And it should be easily discoverable (not hidden in a blog post).

For developer.chrome.com we kicked around an idea of "roadmaps" as a kind of custom page type. We didn't really pursue it, but maybe we should reboot that idea.

I could see it being useful on web.dev as a way to indicate cross browser support for a feature. I'll take a note to see if we can talk about it in our upcoming OKR discussion. Maybe we could do some design explorations around it.

**Comment by tomayac** [comment]
Tagging this with the <3 emoji for sure! Yeah, I'm certain that if this existed more use cases would come up. I can also imagine Houdini folks being interested in this.

From Fugu's side, the scope of the original use case is actually limited to just seeing when an article was updated the last time and getting information about the progress status (shipped, origin trial, dev trial,…) so it can appear in the right spot in a table, but I like how you approach this in the more general case.

**Comment by jpmedley** [comment]
FYI, over in Chrome development world, 'Behind a flag' is being transitioned to 'Developer trial'.

![image](https://user-images.githubusercontent.com/8204171/113725217-f475d580-96a7-11eb-9a41-52e5ebb0a775.png)

**Comment by samdutton** [comment]
We're also interested in doing something similar for Privacy Sandbox APIs. 

I manually maintain a status page at [developer.chrome.com/docs/privacy-sandbox/status](https://developer.chrome.com/docs/privacy-sandbox/status/). 

(Named in honour of [iswebrtcreadyyet.com](http://iswebrtcreadyyet.com) — born 2013, still going strong!)

Of course, pages like this tend to get stale once initial interest/commitment wears off, so some kind of automation would be great. Easier said than done, though. I know there are APIs such as [github.com/chromium/blink-intent-tracker](https://github.com/chromium/blink-intent-tracker), but I haven't worked out how to use that kind of data to build a dashboard.

**Comment by tomayac** [comment]
This can be closed, since we moved to an easier to maintain version of this page by simply linking out to the Fugu API tracker for each section (example: https://web.dev/fugu-status/#in-stable). Thanks!
