### ISSUE TITLE
Investigate deleting old Docker App Engine images

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/web.dev#3830]
We delete the _versions_, but seemingly not the generated images.

**Comment by robdodson** [comment]
Per the discussion it sounds like maybe two things happened.

1. We were deploying so rapidly that we somehow got into a state where the manifest file couldn't find what it was looking for.
2. After a few rounds of this I added a policy to delete the old images after 1 day but some of the stuff the manifest needed was possibly cached for reasons we don't know. This caused us to hit the issue again.

Possible solution is to remove the policy and do nothing and see if it occurs again. If it does, we might try moving our release time out to more like every 3 hours.

**Comment by samthor** [comment]
We've had success with:

1. disabling the retention policy on the generated bucket (deploying generates ~30 unique layer files in App Engine's temporary deploy bucket, some did not change after 1+ day, so they disappeared)
2. deploying every hour (concern multiple deploys were "racing" each other)

The first point seems likely because we saw issues consistently on calendar days (I think probably PST, since @robdodson reported it). But the second point seems likely because the internal folks are confused about why it's broken too.

**Comment by Shuvette** [comment]
> Per the discussion it sounds like maybe two things happened.
> 
> 1. We were deploying so rapidly that we somehow got into a state where the manifest file couldn't find what it was looking for.
> 2. After a few rounds of this I added a policy to delete the old images after 1 day but some of the stuff the manifest needed was possibly cached for reasons we don't know. This caused us to hit the issue again.
> 
> Possible solution is to remove the policy and do nothing and see if it occurs again. If it does, we might try moving our release time out to more like every 3 hours.

Most likely your resolve towards removing this policy would be the best decision at this present time. Seeing how I am not skilled at the matter at hand. I at this point I believe I'm working with the knowledge team. Thank you One-of-a-kind Intuitive Designs.
