### ISSUE TITLE
web.dev is "downloading" pages because of content indexing API

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#3836]
**Describe the bug**
If a user has the experimental web platform features flag enabled then web.dev will show a download indicator as they navigate. This is caused by a bug in the current version of the content indexing API.

I'm sending in a PR to temporarily disable our use of this API until after the bug is resolved.

**Comment by samthor** [comment]
Assigning to @jeffposnick

**Comment by jeffposnick** [comment]
...there's not much to be done at the moment, but once the engineering team responsible for the Content Indexing API resolves the bug in desktop Chrome while running with "experimental web platform features," we can hopefully turn this back on.

**Comment by robdodson** [comment]
@jeffposnick just checking in as i'm doing a big of bug triage. Do you know if the underlying Chrome issue was resolved?

**Comment by jeffposnick** [comment]
I'm not able to reproduce it anymore on https://so-pwa.firebaseapp.com/ (which still uses the Content Indexing API) in macOS Chrome 90.0.4396.0 with the experimental web platform features flag on.

So... I can't say for certain about what would happen if it were re-enabled on https://web.dev/, but it does appear to be resolved elsewhere.

**Comment by robdodson** [comment]
I'm going to close this since we removed the content indexing API. We can look into if we want to add this back when we redo our service worker in the future.

**Comment by jeffposnick** [comment]
(Just for posterity, I can confirm that the Chrome engineering team did fix the underlying issue a month or so ago.)
