### ISSUE TITLE
404's on PL version of the site

### ISSUE THREAD

**Issue by PiotrGrzywa** [GoogleChrome/web.dev#3846]
**Describe the bug**
On polish version of the site some pages shows 404

**To Reproduce**
1. Go to 'https://web.dev/pl/'
2. Click on 'TEST MY SITE' or 'SEE ALL ARTICLES' 
3. You will be redirected to 'https://web.dev/pl/measure/' or 'https://web.dev/pl/blog/'
4. See error '404 Sorry, we couldn't find that page.'

**Expected behavior**
I would like to see those pages, if they are not translated they should be shown in English version.

**Comment by devnook** [comment]
Hi Piotr,

could you tell me which language you have your browser set to? It should be under chrome://settings/?search=languages

**Comment by PiotrGrzywa** [comment]
Hi, in navigator.languages I have:
["pl-PL", "pl", "en-US", "en", "tr"]

The same seems to be in the settings (see attachment).
![Screenshot from 2020-09-09 23-55-55](https://user-images.githubusercontent.com/26554248/92659277-5af46a00-f2f8-11ea-84d7-82cc21f86759.png)

More info about system and browser:
Browser: Chrome, Version 85.0.4183.83 (Official Build) (64-bit)
System: Ubuntu 20.04.1 LTS
