### ISSUE TITLE
What happen behind the scene when a script is loaded as “preload”/“modulepreload”?

### ISSUE THREAD

**Issue by dollysingh3192** [GoogleChrome/web.dev#3848]
Web.dev is awesome place to learn, in very simple words. Thank you!

I was going through one of the [article](https://web.dev/module-workers) and I was trying to understand one of a [paragraph](https://web.dev/module-workers/#preload-workers-with-modulepreload), where we have an ability to load worker's as preloaded module.

There is a saying in this article, which bother's me a lot:

```
Preloaded modules can also be used by both the main thread and module workers. This is useful for modules that are imported in both contexts, or in cases where it's not possible to know in advance whether a module will be used on the main thread or in a worker.
```

Not only webwokers can be loaded as preload module, this is applicable to any js script, font, css etc.. if I am correct! like

```
<link rel="preload" href="fonts/cicle_fina-webfont.woff2" as="font" type="font/woff2" crossorigin="anonymous">

<link rel="preload" href="style.css" as="style">
<link rel="preload" href="main.js" as="script">
```

Does this mean that Module loading caches parsed code, which means modules that are imported in the main thread and in  worker thread will not be parsed again? And If we add a script as preload / modulepreload and get parsed. How can we access same instance in both realm's?

However this does not happen, whenever we import module's on any realm(main thread, worker thread), they execute there import's independently and then future onwards they refer there parsed-cached instance's in there own realms. 

I am really confused, with the statement of author and need help to clear concepts and how to implement this concept.

Thank you!

**Comment by samthor** [comment]
I've cc'ed @developit who wrote the article, in case it can be updated to make this clearer.

> Does this mean that Module loading caches parsed code, which means modules that are imported in the main thread and in worker thread will not be parsed again?

When Chrome caches JS code, it actually caches the already parsed version of that code (i.e., converting raw JS text to a ready-to-use format). That could occur when you first run JS, or at the point of preload. There is a long article about it [here, on the v8 blog](https://v8.dev/blog/code-caching-for-devs).

Importantly, Chrome/v8 does not cache JS code by _filename_. It caches it by source code itself. So if I load "a.js" and "b.js" but they have exactly the same contents, you'll have a performance benefit.

> And If we add a script as preload / modulepreload and get parsed. How can we access same instance in both realm's?

For some background, ES Modules are singletons. If I import `foo.js` multiple times, I always get the same module. But this only applies the same "realm", e.g., the page's scope and the `Worker` scope are _different_. You can't get the same instance. Reflecting on above, you can pretend as if the files have the same contents but different filenames.

> However this does not happen, whenever we import module's on any realm(main thread, worker thread), they execute there import's independently and then future onwards they refer there parsed-cached instance's in there own realms.

There's benefits when v8 parses your JavaScript, so executing it is fast. But in the end the two versions are not running in the same place.

**Comment by developit** [comment]
Hiya - sorry for taking a while to reply. @samthor did a nice job explaining the details here - the paragraph you're referring to is only talking about preloading, instantiation/execution of modules.

Importing a module on the main thread will download it, parse it, then instantiate it there. Importing that same module then in a worker will re-use the parsed code (bytecode technically) to instantiate the module in the Worker.

**Comment by dollysingh3192** [comment]
Thanks @developit...

Doubts are clear now, hence closing the issue...
