### ISSUE TITLE
Feature detection logic is wrong in "More Capable Form Control" doc

### ISSUE THREAD

**Issue by koichirosobue** [GoogleChrome/web.dev#3850]
**Describe the bug**
The feature detection code in the example code in `More Capable Form Control` contains bug.
https://web.dev/more-capable-form-controls/#feature-detection

**To Reproduce**
1. Go to 'https://web.dev/more-capable-form-controls/#feature-detection'.
2. The current example code says:
```
if ('FormDataEvent' in window) {
  // formdata event is supported
}

if ('ElementInternals' in window &&
    'setFormData' in window.ElementInternals) {
  // Form-associated custom elements are supported
}
```

**Expected behavior**
```
if ('FormDataEvent' in window) {
  // formdata event is supported
}

if ('ElementInternals' in window &&
    'setFormValue' in window.ElementInternals.prototype
    // Form-associated custom elements are supported
}
```

**Comment by koichirosobue** [comment]
https://html.spec.whatwg.org/multipage/custom-elements.html#the-elementinternals-interface
This should be a valid issue in the documentation.

**Comment by robdodson** [comment]
oh oops this is already fixed :D
