### ISSUE TITLE
Wondering if I can translate some articles in Korean and contribute

### ISSUE THREAD

**Issue by minseoksuh** [GoogleChrome/web.dev#3858]
Hi

For my team in MeshKorea I recently translated and shared 

https://web.dev/http-cache/ 

as

https://github.com/strangeloop89/super-fun-time/blob/master/translations/http-cache/index.md

Because I loved the content, I thought it could be helpful to others if I can contribute my translation.

I was not sure if this is the right way to contact you guys about this.

Please let me know if I need to request through a different path.

Thanks

**Comment by samthor** [comment]
Thanks for the translation!

@devnook is leading our translation effort and can comment more.

**Comment by kaycebasques** [comment]
Hi @minseoksuh, I'm just following up with your initial offer. We still don't have translation infrastructure on the site. When we do eventually get it, posting issues (like you did) will be a good way to offer to translate for us.

**Comment by fish-404** [comment]
Hi @kaycebasques do you mean when I translate to other language completed, I can open an issuse to let you know?
