### ISSUE TITLE
PWA app hung on splash when switching darkmode in Android

### ISSUE THREAD

**Issue by henke-d** [GoogleChrome/web.dev#3859]
**Describe the bug**
When running web.dev as an PWA and switching between dark mode/light mode, the app hungs on the splash screen. This is a new behavoiur that I haven't seen before?

**To Reproduce**

1. Install web.dev as PWA (add to homescreen) on Android device (Galaxy S10 is my device)
2. Start app
3. Switch dark mode/light mode in Android OS
4. Go back to app which has now hung on splash screen

**Expected behavior**
It should not hang on splash screen when switching to dark mode

Environment: Samsung Galaxy S10, Android 10

**Comment by MichaelSolati** [comment]
Just for clarity, are you using the Samsung Internet Browser, Chrome, or a different browser?

**Comment by henke-d** [comment]
I am using Chrome and the web app is installed as a PWA (added to home screen).

Hämta Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by henke-d** [comment]
My "real" problem with this is for a web app I'm developing for my company but realized that the problem are exactly the same in the web.dev app.

**Comment by kaycebasques** [comment]
@henke-d are you still seeing this bug?

**Comment by henke-d** [comment]
It seems that this is resolved now but maybe the app doesn't react to dark mode change anymore?
________________________________
