### ISSUE TITLE
CSS animations learning path

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3864]
- [ ] Create `src/site/content/en/animations/animations-overview.md` (@rachelandrew)
  * Goal: conceptually explain why some animations are slow and how to create fast ones
  * Draw from [DOM to pixels](https://www.html5rocks.com/en/tutorials/speed/high-performance-animations/#toc-dom-to-pixels) and [Animations and performance](https://developers.google.com/web/fundamentals/design-and-ux/animations/animations-and-performance#tldr)
  * Non-goal: explaining in-depth how to actually create high-performance animations
- [ ] Create `src/site/content/en/animations/animations-guide.md` (@rachelandrew)
  * Goal: high-level general guidance of how to create high-performance animations (i.e. position, scale, rotation, opacity) and which properties to avoid (i.e. go to csstriggers.com and avoid anything that affects layout or paint)
- [ ] Create `src/site/_data/paths/animations.json` (@rachelandrew)
  * We'll fill out it later but for now we just need a prototype
- [ ] Create `src/site/content/en/animations/animations-examples.md` (@rachelandrew)
  * Embed a collection of Glitches (and possibly codepens?) that demonstrate common animation use cases
  * OK to draw from community (i.e. embed other people's examples onto the page)
    * Need to be [minimal](https://stackoverflow.com/help/minimal-reproducible-example) and high-quality however
- [ ] Create `src/site/content/en/animations/animations-tutorial.md` (@rachelandrew)
  * Goal: hands-on experience building the most common animation use case (we'll just have to guess at which one is most common… slide-out menu?) and using DevTools (probably Chrome *and* Firefox)
  * This one will probably require brainstorming between Rachel & Kayce
- [ ] Add support on index pages for external links (@kaycebasques)

**Comment by rachelandrew** [comment]
Just adding a note that I've been referencing:

- https://developers.google.com/web/fundamentals/performance/rendering/stick-to-compositor-only-properties-and-manage-layer-count
- https://developers.google.com/web/fundamentals/performance/rendering/simplify-paint-complexity-and-reduce-paint-areas

The first two articles will cover this content, so it may be we can also redirect these.
