### ISSUE TITLE
Logo - left side looks tiny-bit cut off

### ISSUE THREAD

**Issue by hwikyounglee** [GoogleChrome/web.dev#387]
Shall we give this a try? 

Same size as what we have up on drobdodson, i.e. 125*30px
Just moved the image inside so we have 1 more px on the left

[lockup.svg.zip](https://github.com/GoogleChrome/web.dev/files/2564818/lockup.svg.zip)

![image](https://user-images.githubusercontent.com/7561395/48246690-43b75f00-e3a5-11e8-8ae9-5133899a21d7.png)

**Comment by robdodson** [comment]
I think I fixed this... but I totally don't recall. @hwikyounglee 	does it still look messed up to you?

**Comment by hwikyounglee** [comment]
It does still look cut off a bit on the production web.dev. 

Would it be too much of trouble re-uploading it, so we can compare between devsite and the production? https://github.com/GoogleChrome/web.dev/files/2564818/lockup.svg.zip

Thanks!

**Comment by robdodson** [comment]
It's easy to upload, I can do it tomorrow. Thanks for checking!

**Comment by carolrivero** [comment]
friendly ping on status of fix. thanks.

**Comment by hwikyounglee** [comment]
lgtm

**Comment by robdodson** [comment]
oh wait. I don't know if I ever actually did a change!

Sorry, I disappeared for vacation. Let me take a look today.

**Comment by hwikyounglee** [comment]
My bad, I only viewed via Sketch, looked the difference, and then closed. 
Now I've checked with Photoshop, and right, that's still the old one.

**Comment by robdodson** [comment]
Hwi and I reviewed and it looks ok now.

**Comment by robdodson** [comment]
oops, realized I closed this before the CL landed.

**Comment by robdodson** [comment]
cl/228602976
