### ISSUE TITLE
same-site-same-origin and Websockets

### ISSUE THREAD

**Issue by sosoba** [GoogleChrome/web.dev#3876]
### What page(s) need to be updated?

web.dev/src/site/content/en/secure/same-site-same-origin/index.md

### Why is this update needed?

This article explains topic only in terms of `http` and `https` protocol. It would be useful to include corelation with `ws` and `wss` protocols.

**Comment by kaycebasques** [comment]
@agektmr WDYT?

**Comment by agektmr** [comment]
That's a great idea. @sosoba your pull request will be highly appreciated if you could write that part.

**Comment by agektmr** [comment]
I'll get to this when I have spare time.
