### ISSUE TITLE
content: https for local development [2020-09-16]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3886]
* [draft](https://docs.google.com/document/d/16VAEbBbrP7P3NCx7qWeuypsK0y3kForchr_AZ-fsrvA/edit#heading=h.g0po04lpxofi)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/Mbi58f36wlI)

**Comment by mihajlija** [comment]
In progress, just waiting for Maud to come back from holidays.
