### ISSUE TITLE
User can't share a post

### ISSUE THREAD

**Issue by diegonvs** [GoogleChrome/web.dev#3907]
**Describe the bug**

**To Reproduce**
1. Go to https://web.dev/aria-poison-or-antidote/
2. Click on the "share button"
4. See the following error:

The page will crash:

![image](https://user-images.githubusercontent.com/7663513/93628112-66acf400-f9bc-11ea-84d5-debdea8c1866.png)

Also, It's being reproduced on the incognito mode and when hard reloading and cleaning the cache.

I added a GIF for a quick understanding of the problem:

![webdev](https://user-images.githubusercontent.com/7663513/93628179-85ab8600-f9bc-11ea-918d-a8ea9b889f14.gif)

**Expected behavior**
The user can share an article

**Comment by robdodson** [comment]
hey @diegonvs can you tell me which version of Chrome you're using and if you have any flags enabled? You can check in chrome://flags. In particular, can you tell me if you have the experimetnal web platform features flag turned on?

**Comment by diegonvs** [comment]
For sure. Here it goes:

Everything is settled to default except `#enable-experimental-web-platform-features`.

See: 
![image](https://user-images.githubusercontent.com/7663513/93842183-5d49b300-fc6c-11ea-98ab-85c7002fbbb9.png)

I'm running Chrome 85(on the print screen it was being updated but this was my current version):

![image](https://user-images.githubusercontent.com/7663513/93842219-7c484500-fc6c-11ea-95a8-f44d4fdafd7b.png)

**Comment by diegonvs** [comment]
> I'm running Chrome 85(on the print screen it was being updated but this was my current version):

When I updated to the same major(85) but a new patch it still being reproducible

![image](https://user-images.githubusercontent.com/7663513/93842316-ce896600-fc6c-11ea-8ee7-c85fabe0e6d7.png)

**Comment by diegonvs** [comment]
FYI, 

When disabling "experimental-web-platform-features" flag It can solved.

**Comment by robdodson** [comment]
yep i'll close it. thank you!
