### ISSUE TITLE
Discrepancy in maximum-scale it should be 5 or 2

### ISSUE THREAD

**Issue by DesigningStudios** [GoogleChrome/web.dev#3917]
**Describe the bug**
There is a discrepancy from what google suggests and expected fix. Who is correct?

**To Reproduce**
1. Go to 'https://web.dev/meta-viewport/'
2. Scroll down to 'Resources'

**Current behavior**
web.dev site says maximum-scale parameter is not less than 5

**Expected behavior**
Deque University link says maximum-scale parameter is not less than 2

**Comment by robdodson** [comment]
Tentatively assigning to Kayce to triage

**Comment by rachelandrew** [comment]
Closing as this content now redirects to Deque.
