### ISSUE TITLE
The parameter 'entries' passed into 'workbox-precaching.PrecacheController.addToCacheList()' must be an array.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#3935]
**Describe the bug**
I see this intermittently but if I refresh it goes away.

![image](https://user-images.githubusercontent.com/1066253/94087243-21c0fd00-fdc2-11ea-9fef-7ace46bb923f.png)

**Comment by rajneshbiz** [comment]
HI @robdodson, any update on this ?

**Comment by robdodson** [comment]
@rajneshbiz I think it should have stopped happening because we recently removed the service worker and added a script to uninstall them. We're going to explore adding a more simplified service worker back later in the year.
