### ISSUE TITLE
"Return to articles" button in codelabs not working

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/web.dev#3939]
The "Return to all articles" button on some of the codelabs is not working, it links to [https://web.dev/undefined/](https://web.dev/undefined/). 

Here are the affected pages that I've found:

[https://web.dev/codelab-two-ways-to-prefetch/](https://web.dev/codelab-two-ways-to-prefetch/)
[https://web.dev/codelab-preload-critical-assets/](https://web.dev/codelab-preload-critical-assets/)
[https://web.dev/codelab-preload-web-fonts/](https://web.dev/codelab-preload-web-fonts/)

This is related to #3928 but since these links are generated I'm not sure what's the problem.

cc @robdodson

**Comment by robdodson** [comment]
Hey @mihajlija these codelabs are broken because they're missing the `related_post` key in their YAML.

Compare them to this one https://github.com/GoogleChrome/web.dev/blob/master/src/site/content/en/reliable/codelab-explore-network-panel/index.md

**Comment by samthor** [comment]
@mihajlija I had a go at this in code, but as Rob points out it's also an error in the articles themselves.

**Comment by mihajlija** [comment]
@robdodson @samthor Thank you both for identifying the issues, PR #3941 will fix these three posts.
