### ISSUE TITLE
Native lazy loading demo does not lazy load on non-chromium browsers

### ISSUE THREAD

**Issue by jochan** [GoogleChrome/web.dev#3944]
**Describe the bug**
On [the native lazy loading page](https://github.com/GoogleChrome/web.dev/blob/master/src/site/content/en/fast/native-lazy-loading/index.md), the demo that is linked (https://lazy-loading.firebaseapp.com/lazy_loading_native.html) to show the fallback to using lazysizes on browsers that do not support `loading="lazy"` does not work as intended. All the images are eagerly downloaded on Safari, for example.

**To Reproduce**
1. Go to https://lazy-loading.firebaseapp.com/lazy_loading_native.html on Safari or Firefox
2. Check your inspector and see that images are all downloaded on load

**Expected behavior**
Lazy loading happens.

In the example (https://lazy-loading.firebaseapp.com/lazy_loading_native.html), just change all the `src` attributes to `data-src` and add the `lazyload` class instead.
e.g. `<img src="./images/high-res/Image01.jpg" loading="lazy" class="inline">` to `<img data-src="./images/high-res/Image01.jpg" loading="lazy" class="inline lazyload">`

**Screenshots**
![image](https://user-images.githubusercontent.com/2473272/94213991-2c949400-fe8d-11ea-88a6-aff988e29aa0.png)

**Comment by robdodson** [comment]
@housseindjirdeh could you take a look at this?

**Comment by beaufortfrancois** [comment]
https://github.com/GoogleChrome/web.dev/pull/4192 should fix it.
