### ISSUE TITLE
Update RSS feed `<updated>` field when new article gets removed

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/web.dev#3949]
**Describe the bug**
RSS feed updated date doesn't reflect changes after a new article gets removed.

**To Reproduce**
1. Publish an article on web.dev
2. Visit https://web.dev/feed.xml
3. The `<updated>` date reflects the published date of the article
4. Remove article
5. Refresh https://web.dev/feed.xml
6. The `<updated>` date reflects the published date of the more recent article.

**Expected behavior**
The `<updated>` date should reflect the date of when the article was removed.
Otherwise, RSS readers won't fetch new information and will still keep the previous cached article.

https://github.com/GoogleChrome/web.dev/blob/e55a204e500a4b3fd6291d5f0ff304545c1122bf/src/site/_includes/feed.njk#L7

One possible way to solve this would be to change `<updated>` to the time of publication (changes every hour sadly).
Note that according to https://tools.ietf.org/html/rfc4287#page-25, 

> the "atom:updated" element is a Date construct indicating the most
>  recent instant in time when an entry or feed was modified in a way
>  the publisher considers significant.

**Comment by jpmedley** [comment]
To add some context around this, once in a while somebody accidentally merges a document they shouldn't. By "somebody" I mean me, at in one specific case.

**Comment by robdodson** [comment]
> One possible way to solve this would be to change <updated> to the time of publication (changes every hour sadly).
Does this mean every article's updated date would change every hour?

**Comment by beaufortfrancois** [comment]
Nope. Only the top level feed entry `<updated>` of https://web.dev/feed.xml.

![image](https://user-images.githubusercontent.com/634478/95437206-ffe48000-0954-11eb-9156-85bfd08be4ba.png)

**Comment by beaufortfrancois** [comment]
@robdodson (gentle ping)

**Comment by robdodson** [comment]
hey @beaufortfrancois, the team is really heads down working on the developers.chrome.com relaunch so I don't think we'll be able to prioritize this at least until after CDS.

**Comment by beaufortfrancois** [comment]
No problem.
Shall I send a PR or it is better to wait until after CDS?

**Comment by beaufortfrancois** [comment]
@robdodson I've uploaded a PR at https://github.com/GoogleChrome/web.dev/pull/4071. No rush.
