### ISSUE TITLE
content: Digital Goods API [2020-12-02]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3959]
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/_8LkzngJffw)
* draft: TBD

**Comment by jpmedley** [comment]
This got pushed back to 88 because of a problem with how this integrates with Play Billing Policy. [Details here](https://groups.google.com/a/chromium.org/g/blink-dev/c/syI9_M9dANY/m/txk_2LNCCgAJ).

**Comment by jpmedley** [comment]
I'll be able to put correct dates on this as soon as I learn from the feature owners which version of Chrome this is shipping in.

https://www.chromestatus.com/feature/5339955595313152

**Comment by jpmedley** [comment]
It looks like the origin trial is starting in 88.

**Comment by jpmedley** [comment]
Digital Goods did go out in 88. Do we no longer want an article about this? I'm asking that we make this decision deliberately rather than by virtue off a bot that closes the ticket.
