### ISSUE TITLE
content: Logical layout enhancements with flow-relative shorthands [2020-10-14]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3960]
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/M87zSnf_XIo)
* [draft](https://docs.google.com/document/d/1offfipj-2IQlBSC0nhMIuUTubGs8djQa2qcObKa7-oI)

**Comment by argyleink** [comment]
draft link added.

**Comment by jpmedley** [comment]
@argyleink , this feature [will be in the upcoming](https://storage.googleapis.com/chromium-find-releases-static/141.html#14115cf9e3e8f32e494208f4c10dd96f2c28fb60) Chrome 87 beta. Is there any chance of publishing this by October 14th?. I can help in any way needed.

**Comment by argyleink** [comment]
There's a chance sure! I'm putting lots of bandwidth on it, but it's competing with a few other things. I'm clear on what needs to be written, just doing the work at this point. I'll reach out if anything in particular pops up tho! Thanks for the offer.

**Comment by argyleink** [comment]
Draft ready for review 👍

**Comment by jpmedley** [comment]
@kaycebasques The content is not my swim lane, but I can edit this if everyone else is backed up. Please let me know.

**Comment by argyleink** [comment]
up for review #2, i'll make a PR next I hope

**Comment by argyleink** [comment]
thanks for the swift review @rachelandrew 🔥 all feedback has been implemented into the PR at #4018, much easier to read now it's not in a doc!
