### ISSUE TITLE
content: min(), max(), and clamp() [2020-10-13]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3963]
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/dYRrgUVo-c4)
* [draft](https://docs.google.com/document/d/1vFxeXe0OpuZZ03qxIS76WqWDuq93vcxOV1qZb4YuHBk/edit?usp=sharing)

**Comment by rachelandrew** [comment]
@una looks like you are working on this so let me know here when you want a review and I'll get onto it.
