### ISSUE TITLE
content: Extending Workbox: Custom Strategies & Plugins [2020-10-22]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3964]
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/Dq06nXsnVWo)
* [draft](https://docs.google.com/presentation/d/1fnp_nAuMkuP_h2QjtxJ7Lg8TT-DHT3V7l9oQzHiyOMc/edit?usp=sharing)

**Comment by jeffposnick** [comment]
A draft of the article accompanying the CDS talk is available at https://docs.google.com/document/d/1xr416b8gaGkdQUIvPFVtxs-o7utxLJzmfIDalGNTGj4/edit?usp=sharing&resourcekey=0-zvR3Gn1FUzdqUJBWFw-I4A (`@google.com` login required).
