### ISSUE TITLE
content: Range request header in a Service Worker [2020-10-14]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3974]
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/D176Jqwlwjk)
* [draft](https://docs.google.com/document/d/1FxqIQlC0Ft0WT0tvAHRRMGPEsdyrvXECUcXzoKkJWuI/edit#)

**Comment by jeffposnick** [comment]
The link to the (`@google.com` restricted) draft document is https://docs.google.com/document/d/1T03yXt2FgKk2oLuEqbtCZLXjMqD8kHFyIHxtFGmn1Xk/edit?usp=sharing

**Comment by jpmedley** [comment]
Looking now.

**Comment by jpmedley** [comment]
This looks pretty good. I had a few nits. After correcting them, please proceed to a PR.
