### ISSUE TITLE
content: CORS-RFC1918 [2020-10-15]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3988]
* [draft](https://docs.google.com/document/d/1JpYy2b27UHcZMlenHxdfr88MsUCkddhmJ91q9ecmPpU/edit)
* [discussion](https://groups.google.com/a/google.com/g/webdev-content/c/vpfk6Ra-VWU)
* next step: @agektmr to provide draft access to @mihajlija and me

**Comment by agektmr** [comment]
This is still actively being worked on.
