### ISSUE TITLE
Landing pages to appear in search for relevant content

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#4027]
**Describe the bug**
For example, "Network reliability" does not appear in search results for "reliability".

**To Reproduce**
Type "reliability" in the site's search box. Results look like this:
![image](https://user-images.githubusercontent.com/8204171/95477520-48903f00-093d-11eb-9af6-db3985663588.png)

**Expected behavior**
"Network reliability" appears when I search for "reliable" or "reliability"

**Comment by jpmedley** [comment]
@petele FYI

**Comment by jpmedley** [comment]
Thank you for accepting this. Pete and I uncovered another aspect of this problem this morning. We think constructed landing pages should take precedent over tag landing pages. You may recall that my reason for requesting tag-based landing pages was to serve ad-hoc use cases. If a particular concept has a constructed landing page, it should be what readers find first.

**Comment by robdodson** [comment]
@MichaelSolati maybe this is something we can work on together

**Comment by MichaelSolati** [comment]
This is presently being worked on!
