### ISSUE TITLE
Codelab content doesn't scroll unless you click on it

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/web.dev#404]
More a UX/UI problem than a bug, but...

If you attempt to scroll a codelab page, the codelab content doesn't scroll unless you click on it. This might lead people to think there isn't any more content than what they can see on first load.

[example page](https://web.devsite.corp.google.com/fast/remove-unused-code/codelab-remove-unused-code)

[screencast](https://drive.google.com/file/d/1ZLKf3a9AxFfPJd26WWhk8LebQDI9oM73/view?usp=sharing)

**Comment by robdodson** [comment]
Also reported on twitter https://twitter.com/eccegostudio/status/1083421130319372289

The sticky header is too big and not scrollable. Which seems like a high priority thing to fix.

In addition, the codelab is purposefully 100% heigh, forcing the footer offscreen, which can lead to other weird scrolling issues.

**Comment by robdodson** [comment]
I'd like to add this to our next milestone. We should be able to disable the devsite footer on these codelab pages.

**Comment by robdodson** [comment]
This'll be fixed when we do #807 in the upcoming sprint.
