### ISSUE TITLE
Error: Error: Quota exceeded

### ISSUE THREAD

**Issue by km-river-dk** [GoogleChrome/web.dev#4056]
**Describe the bug**
Error: Error: Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'pagespeedonline.googleapis.com' for consumer 'project_number:873913213263'.

**To Reproduce**
Go to https://web.dev/measure/ and test the following URL: https://www.primo.com/

**Expected behavior**
A test being performed

**Screenshots**
![image](https://user-images.githubusercontent.com/60741476/95821385-152d2600-0d2a-11eb-8ab9-7d0c3e2cc4e7.png)

**Comment by raquo** [comment]
We're still facing this issue too, for https://www.goodcover.com/ url. Same error message, only earlier today it mentioned queries "per 100 seconds", then switched to "per day". Also with the same project_number 873913213263, even though of course it's a different project than OP.

Probably 90% of my "run audit" button clicks result in this message. Some times I can get through, although very inconsistently. The error started on my very first "run audit" button click today after a few days of not using it at all (and I was never a heavy user), so I am not exceeding any quotas unless the quota is zero. Google API console for our project does not show any usage for this API, as far as I can tell, and that's expected, as we don't have any automations hitting it.

This error persists across different IP addresses, user devices, google accounts, and even domain names tested. Definitely something is broken on the web.dev servers.

This wouldn't be a big deal if I could get perf numbers even slightly close to what web.dev lighthouse reports in my local Chrome, but alas, locally I'm at 99% perf, yet web.dev results are in the 70-s or 80-s. So I do need access to web.dev to test my changes against it.

**Comment by robdodson** [comment]
Thanks for filing this! I'm reaching out to the pagespeed team to see what's up.

**Comment by raquo** [comment]
Thanks, it seems to be working fine today, haven't gotten an error once yet.
