### ISSUE TITLE
content: PointerLock unadjustedMovement [2020-11-14]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#4067]
* [draft](https://docs.google.com/document/d/1Dzm1yHhM9oukHmv6wCqCtPdt9obMIyDP6KmZ3wdJDms/edit#)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/lC8eLmdqJvM)
* next step: @jpmedley to review [PR](https://github.com/GoogleChrome/web.dev/pull/4098)

**Comment by jpmedley** [comment]
This will be enabled by default in Chrome 88. this has a hard deadline of December 2. (Beta is the following day.) I suspect Fraçois wants to get this article out sooner.

**Comment by jpmedley** [comment]
Reviewed. Please move on to the PR.

**Comment by beaufortfrancois** [comment]
Stil active
