### ISSUE TITLE
Statuses with version ranges should show both values on rendered entry

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#4092]
**Is your feature request related to a problem? Please describe.**
Issue #1011 enhanced the underlying dataset used by Chrome Status to include beginning and ending version numbers for developer trials, origin trials, and deprecation. Currently only the beginning number is displayed on the rendered card for a status entry. You can see an example in the image below.

![image](https://user-images.githubusercontent.com/8204171/96514924-45d4fa00-1219-11eb-98dd-7618bb17069a.png)

**Describe the solution you'd like**
A rendered status entry would display both values. The second value would always be termed and "expected" value such as in the image below. This text would work for both developer and origin trials. For deprecations the column headers should be "starting in" and "expected removal".

![image](https://user-images.githubusercontent.com/8204171/96515945-0dceb680-121b-11eb-9c44-29ca233ba5e4.png)

**Additional context**
Users are currently are currently duplicating origin trial and deprecation ranges in the comments box so that they will display on the rendered card.

![image](https://user-images.githubusercontent.com/8204171/96516185-86ce0e00-121b-11eb-98fa-57e88c4e9c34.png)

**Comment by samthor** [comment]
beep bot 🤖
