### ISSUE TITLE
View-source no longer wraps lines in Canary 88

### ISSUE THREAD

**Issue by tmb-github** [GoogleChrome/web.dev#4096]
Chrome Canary 88.0.4297.2 (Official Build) canary (64-bit)
OS: Windows 8.1

Go to: view-source:https://thomasbrodhead.com/ 
The minified source code no longer wraps, but continues off the page, requiring scrolling to view.
This was not the case previously, and there's no apparent mechanism for restoring the previous line-wrapping display.

**Comment by robdodson** [comment]
Hi @tmb-github, if this is a Chrome issue you'll need to file it over at crbug.com
