### ISSUE TITLE
Accessibility check for authenticated pages - when I am giving URL for my site (not welcome page but page that comes after login)

### ISSUE THREAD

**Issue by swat1508** [GoogleChrome/web.dev#4104]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by robdodson** [comment]
Our tool can't access pages that require authentication. But you can run Lighthouse from the chrome devtools on your local machine to check the performance of those pages.

https://developers.google.com/web/tools/lighthouse
