### ISSUE TITLE
content: Lazy load third-party resources with facades [2020-11-10]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#4121]
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/ZleQcBIprvg)
* [draft](https://docs.google.com/document/d/1WCDboioqEuoBGLKQ0UDe9-ptg41lEPk9-93wzTWrZ6M/edit?usp=sharing)

**Comment by mihajlija** [comment]
Working on it
