### ISSUE TITLE
content-visibility: auto prevents js scroll to the elements below on the page

### ISSUE THREAD

**Issue by kirav** [GoogleChrome/web.dev#4124]
**content-visibility: auto prevents js scroll to the elements below on the page**
although this new property does make a big difference on performance, it seems to interfere with js scroll to elements below the content parts that it is applied to

**To Reproduce**
1. Go to 'https://codepen.io/kirav/pen/xxOZzVP'
2. Click on 'Scroll to comments section' on top
3. You are not getting to the comments' section at the bottom of the page. presumably because the boxes on the page are not rendered yet you stop somewhere in the middle.
4. if you comment out line 9 '.box:not(:nth-of-type(1)){content-visibility:auto}', you are able to reach comments' section below.

**Comment by kirav** [comment]
i watched the video with the contain-intrinsic-size hack (adding it fixed the straightforward scrollTo issue).

but setting contain-intrinsic-size to 5000px high conflicts with components that are lazyloaded on the page and the experience is very jumpy

**Comment by kaycebasques** [comment]
@una PTAL

**Comment by kirav** [comment]
thank you @kaycebasques. i contacted @una but did not get a response. tried to look more into the issue, as it seems like such a potent property, but still lazy loading images screw up the offset.

**Comment by robdodson** [comment]
@kirav would you be ok moving this issue to http://crbug.com/ ? I think it sounds like a Chrome bug and it may get a faster response over there.
