### ISSUE TITLE
content: explain why  FCP should occur within 1 second

### ISSUE THREAD

**Issue by kkdev163** [GoogleChrome/web.dev#4128]
* Use this template to request updates to existing content.
* Delete any fields that aren't relevant to your issue. 
* Update the title of this issue with a brief summary of the work to be done.

### What page(s) need to be updated?
https://web.dev/fcp/#what-is-a-good-fcp-score
> To provide a good user experience, sites should strive to have First Contentful Paint occur within 1 second of the page starting to load.

### Why is this update needed?
As the rule mentioned below, it seem ```1 second``` is the  8th percentile  of HTTPArchive' desktop data. Why Core Vitals like LCP use the mobile data (2500ms) as its good line, but FCP use the desktop data.  

https://web.dev/performance-scoring/#metric-scores
> The 25th percentile of HTTPArchive data becomes a score of 50 (the median control point), and the 8th percentile becomes a score of 90 (the good/green control point)

https://httparchive.org/reports/loading-speed#fcp
![image](https://user-images.githubusercontent.com/34838245/97254064-87ccf400-1848-11eb-889c-3332ff2bb2c4.png)

https://googlechrome.github.io/lighthouse/scorecalc/#FCP=2336&SI=4074&LCP=2500&TTI=4742&TBT=370&CLS=0.13695024197592273&FMP=1962&FCI=3249&device=mobile&version=6&version=5
![image](https://user-images.githubusercontent.com/34838245/97254566-9d8ee900-1849-11eb-9344-005f29030fb5.png)

https://googlechrome.github.io/lighthouse/scorecalc/#FCP=940&SI=4074&LCP=1200&TTI=4742&TBT=370&CLS=0.13695024197592273&FMP=1962&FCI=3249&device=desktop&version=6&version=5
![image](https://user-images.githubusercontent.com/34838245/97254603-b5ff0380-1849-11eb-94c8-c65ed93cae6e.png)

Another question,  it seems HTTPArchive have not provide the LCP distribution data,  can we find the LCP distribution in other site?

**Comment by kaycebasques** [comment]
@philipwalton WDYT?
