### ISSUE TITLE
On iPad, a white bar covers website contents at the top of the keyboard.

### ISSUE THREAD

**Issue by mileonsas** [GoogleChrome/web.dev#4132]
**Describe the bug**
On iPad device, when keyboard is open on textarea, a white bar appears at the top of the keyboard. In several cases, this white bar covers website contents. This issue cause problems when user try to access what is typing if textarea is fixed at the bottom of the page.

**To Reproduce**
1. Use an iPad and open a google search request
2. On the results page, click on search request (textarea form), then the keyboard will appears
3. You could see this white bar at the top of the keyboard
4. This issue cause more problems on conversation pages

**Expected behavior**
To fix this issue, we detect the browser and device used. If Google Chrome and iPad are detected we add a margin bottom to our footer page (margin-bottom: 44px), but the white bar remains apparent.

**Comment by nickwelp** [comment]
I've seen this issue in many scenarios as well. Most chat applications with a chat input on the bottom of the screen, have said input get covered by the white box.  Here is an example, using an iPad, Chrome, to look at Google News 
<img width="575" alt="Screen Shot 2020-11-30 at 5 34 01 PM" src="https://user-images.githubusercontent.com/7506220/100783116-fd415c80-33d2-11eb-9793-dd17a74274a2.png">
