### ISSUE TITLE
content: :is() & :where() [2020-11-12]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#4134]
* [draft](https://docs.google.com/document/d/1-rS4KxqRBxijvgS9TKTfPnnFPuM3NCSUpeV-6-HbDSg/edit)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/ow3RtA2qGDU)

**Comment by argyleink** [comment]
rad 👍

**Comment by argyleink** [comment]
draft ready for review 👍🏻

**Comment by argyleink** [comment]
still ready!

**Comment by argyleink** [comment]
not stale, still delicious! 🍞

**Comment by rachelandrew** [comment]
@kaycebasques is this one it might be helpful for me to edit?

**Comment by rachelandrew** [comment]
@argyleink are you still working on this one?

**Comment by argyleink** [comment]
i'd love to carry this across the finish line yeah! 👍🏻

**Comment by rachelandrew** [comment]
@argyleink still up for working on this? Let me know if I can help.

**Comment by argyleink** [comment]
i just reviewed the draft again, looks ready for a review rachel if you're interested?

**Comment by rachelandrew** [comment]
@argyleink bunch of comments in the doc :)

**Comment by argyleink** [comment]
I gave it a pretty big rewrite! 👍🏻
