### ISSUE TITLE
SourceMap URLs are included in web.dev (not just dev)

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/web.dev#4151]
**Describe the bug**
SourceMap URLs are included in prod version of web.dev.

**To Reproduce**
1. Go to web.dev/blog
2. Open DevTools Console
3. See error

```
DevTools failed to load SourceMap: Could not load content for https://web.dev/app.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Expected behavior**
There should be no errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/634478/97710883-a2a79e80-1abc-11eb-9a9b-c887004b5fde.png)

From what I understand from the code below, the SourceMap should only be included in dev environment.
https://github.com/GoogleChrome/web.dev/blob/891fedb19dd898bb3b36d8c3b7dd9cb65bcfae42/compile-css.js#L111-L116

**Comment by beaufortfrancois** [comment]
It's still happening...

**Comment by beaufortfrancois** [comment]
Still happening!

**Comment by beaufortfrancois** [comment]
@samthor Do you know what is happening?

**Comment by robdodson** [comment]
I believe this is fixed now that we inline all of our CSS
