### ISSUE TITLE
Wrong window.innerHeight after cookie clear on IOS devices

### ISSUE THREAD

**Issue by Astroluset** [GoogleChrome/web.dev#4152]
**Describe the bug**
window.innerHeight calculated wrong after the cache clear

**To Reproduce**
1. Create a dummy html page with alert or console.log window.innerHeight;
2. Visit the page from step 1 by the latest GoogleChrome on IOS;
3. You can see a log/alert with window.innerHeight;
4. Pres on 3 dot icon on toolbar;
5. Select history clear;
6. Select clear cookie;
7. Press done;
8. Press done;
9. Wait for the page reload;
10. See log/alert

**Actual behavior**
Log from step 10 !== log from step 3.

**Expected behavior**
Log from step 10 === log from step 3.

**Comment by robdodson** [comment]
@Astroluset this sounds like you're trying to file an issue for the Chrome browser, correct? If so, those should be filed at crbug.com

**Comment by Astroluset** [comment]
> @Astroluset this sounds like you're trying to file an issue for the Chrome browser, correct? If so, those should be filed at crbug.com

Yes! Ok.
