### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by jlbarn11** [GoogleChrome/web.dev#4156]
**Describe the bug**
The "external" links in the sidebar under the topics don't work properly. They all just take me to the web.dev landing page. Example: The links about image optimization all over Google's web.dev and support.google.com all land here: https://web.dev/#optimize-your-images

**To Reproduce**
1. Go to https://developers.google.com/web/fundamentals
2. Click on Performance
3. Scroll down to Loading Performance and expand, then click to open Optimizing Content Efficiency
4. Try to click on Image Optimization, Automating Image Optimization, or Web Font Optimization. The links lead to web.dev. There was at least one more that I noticed, but I didn't check them all. 

**Expected behavior**
I expected links about image optimization to include information about image optimization, or at least to link to a page somewhere on the topic. I was hoping to share the info with my students :)

**Comment by samthor** [comment]
Thanks for the report. This was caused by #4087. We'll roll it back for now.
