### ISSUE TITLE
content: sizing (learn css) [2021-05-01]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#4171]
* [draft](https://docs.google.com/document/d/1Lm1jKds3QI79tlOGW0KEoK-ClXQaZAFieJxBB9fRh-E/edit)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/V2Y8nylAPX4)

**Comment by rachelandrew** [comment]
Demos for this one, also linked in doc: https://glitch.com/@rachelandrew/learn-sizing

**Comment by kaycebasques** [comment]
I can close these because we're tracking the work elsewhere now.
