### ISSUE TITLE
content: replace glitch embed with link

### ISSUE THREAD

**Issue by maudnals** [GoogleChrome/web.dev#4184]
### What page(s) need to be updated?

https://web.dev/what-is-mixed-content/

### Why is this update needed?

Inception: because of the glitch demo embed, there's a mixed-content issue on that page, making web.dev appear "insecure".
The idea is to replace the embed with a link to the glitch.
![image](https://user-images.githubusercontent.com/9762897/98140699-07506800-1ec6-11eb-9d93-6a12e10707d0.png)

### What's the deadline?
/

#### Is it a hard deadline?
n/a

**Comment by kaycebasques** [comment]
Noting that this was fixed. I don't have the PR handy.
