### ISSUE TITLE
Add publish status to guide yaml

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#419]
Sometimes it's nice to be able to check a guide or codelab into the repo without it actually being shipped. Or sometimes something may already be published and you'd like to unpublish it without removing it from the repo. I'm currently in that position with a few of the codelabs that still need more work and might not make the launch cutoff.

Post-launch it might be worth adding a `status: {draft|published}` field to the YAML front matter.

**Comment by robdodson** [comment]
@TimvdLippe would you be interested in working on this next?

**Comment by TimvdLippe** [comment]
Sure!

**Comment by robdodson** [comment]
Closing in favor of #725
