### ISSUE TITLE
PWA launch icon in address bar does not appear

### ISSUE THREAD

**Issue by zhechka** [GoogleChrome/web.dev#4190]
**Describe the bug**
In some cases icon for launch PWA in address bar does not appear after switch from PWA
![image](https://user-images.githubusercontent.com/39065662/98218052-58ab3680-1f5c-11eb-97d5-a5fb9830d7a2.png)

**To Reproduce**
1. Go to 'web.dev'
2. Click on '+ button' in address bar to install pwa
3. in opened PWA window click in more menu (three dots) and click "Open in Microsoft Edge"
4. in address no launch icon 
![image](https://user-images.githubusercontent.com/39065662/98218272-a32cb300-1f5c-11eb-8aed-5f17f3d4838d.png)

**Expected behavior**
Launch icon is present

**Comment by cleytontiagosorinho** [comment]
Já fechou

**Comment by kaycebasques** [comment]
@zhechka is this feedback in relation to a specific page of our documentation?
