### ISSUE TITLE
content: replace console warnings with Issues

### ISSUE THREAD

**Issue by maudnals** [GoogleChrome/web.dev#4205]
### What page(s) need to be updated?
https://web.dev/what-is-mixed-content/

### Why is this update needed?
The screenshots show DevTools warnings, which have been replaced with Issues in newer versions of DevTools.
=> Update screenshots and text.

### What's the deadline?
/

#### Is it a hard deadline?
n/a

**Comment by kaycebasques** [comment]
@maudnals this still seems relevant. Can you PR a fix?
