### ISSUE TITLE
Étendue 0 là haut 

### ISSUE THREAD

**Issue by jessicah2109** [GoogleChrome/web.dev#4214]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by jessicah2109** [comment]
[Backup-codes-jessicahuard888.txt](https://github.com/GoogleChrome/web.dev/files/5531527/Backup-codes-jessicahuard888.txt)

**Comment by jessicah2109** [comment]
[Backup-codes-jessicahuard58.txt](https://github.com/GoogleChrome/web.dev/files/5531534/Backup-codes-jessicahuard58.txt)

**Comment by jessicah2109** [comment]
[Fiche animal.docx](https://github.com/GoogleChrome/web.dev/files/5531538/Fiche.animal.docx)

**Comment by lucalves** [comment]
Same as #4117.
