### ISSUE TITLE
content: Cross-browser Paint Worklets and Houdini.how [2020-12-09]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#4250]
* [draft](https://docs.google.com/document/d/16FXNWV4a2vl8NxnAbGPQtsVAxMjsJaec807umO-9TTU/edit?usp=sharing)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/qlmYyBQ4g-I)

**Comment by una** [comment]
This should be 12/10/20 (my talk is the second day AFAIK)
