### ISSUE TITLE
content: add checklist item to check that we're using other people's products as intended

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#4256]
### What page(s) need to be updated?

https://web.dev/handbook/content-checklist

### Why is this update needed?

In a general way, we need a reminder to check for whether we are using other people's products in a way that they didn't intend for it. Interesting/creative hacks that increase productivity and which the product owner would probably approve of are OK (on the other hand, though, how can we be sure?). But explaining how to do something that would make the product owner upset should be flagged for discussion.

**Comment by tomayac** [comment]
Still need to do this.
