### ISSUE TITLE
Big CLS regression

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#4263]
Here's what we're seeing in search console:
![image](https://user-images.githubusercontent.com/1066253/99568304-1b936b00-2984-11eb-8bbc-255ed5249624.png)

Here's the current scores:
![image](https://user-images.githubusercontent.com/1066253/99568330-23530f80-2984-11eb-8e22-6e88934b7d25.png)

Here's the previous scores:
![image](https://user-images.githubusercontent.com/1066253/99568365-2d750e00-2984-11eb-8c50-28715901af59.png)

@beaufortfrancois It seems strange but I'm wondering if preloading the css maybe broke something? The dates seem to line up?

**Comment by beaufortfrancois** [comment]
Weird... I'll have a look tomorrow.

**Comment by beaufortfrancois** [comment]
Looking at https://web.dev/async-clipboard/ which went from 0.04 to 0.55 according to screenshots above from the Search Console, I can't reproduce in WebPageTest (0.004) but PageSpeed Insights indicates a CLS of 0.23 for Origin Summary while Lab Data shows 0.

I'll continue investigating.

![image](https://user-images.githubusercontent.com/634478/99660816-2d980b00-2a63-11eb-82bf-6e42c2c02609.png)
Source: https://webpagetest.org/result/201119_DiMM_903bf887287185a6a8ab4f1892e2cc0a/

![image](https://user-images.githubusercontent.com/634478/99660993-76e85a80-2a63-11eb-8299-59758f267024.png)
![image](https://user-images.githubusercontent.com/634478/99661190-c29b0400-2a63-11eb-9444-a93e54d9d9e5.png)
Source: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fweb.dev%2Fasync-clipboard%2F

**Comment by beaufortfrancois** [comment]
@robdodson I've uploaded https://github.com/GoogleChrome/web.dev/pull/4266 to fix this. Can you have a look?

**Comment by rviscomi** [comment]
Keep in mind that WPT doesn't scroll the page as a real user would, so if there are layout shifts further down the page it wouldn't report those. Could there possibly be issues lazily loading images in the middle of articles? Or maybe something to do with the hero images?

**Comment by beaufortfrancois** [comment]
How would you diagnose those issues?

**Comment by rviscomi** [comment]
A few options:

- Use WPT scripting to scroll the page and simulate a user experience
- Enable "Show layout shift regions" in DevTools to spot layout shifts as they happen during page use
- Use the [Web Vitals extension](https://chrome.google.com/webstore/detail/web-vitals/ahfhijdlegdabablpippeagghigmibma?hl=en) to see how CLS changes during page use

**Comment by beaufortfrancois** [comment]
As https://github.com/GoogleChrome/web.dev/pull/4286 got reverted, we still have to figure out where the CLS regression comes from.

**Comment by beaufortfrancois** [comment]
As noted at https://github.com/GoogleChrome/web.dev/pull/4266#issuecomment-732983065, I believe the `<web-feedback>` component causes some layout shift. It is fixed when setting a proper height but I'm not sure how to fix this properly

**Comment by beaufortfrancois** [comment]
@robdodson @rviscomi  I'm also investigating setting width and height attributes to images to reduce CLS. See https://github.com/GoogleChrome/web.dev/issues/4263

**Comment by robdodson** [comment]
For what it's worth, on developer.chrome.com we switched to using an eleventy shortcode for images that sets their width/height and responsive srcsets. I was thinking of bringing it over to web.dev but it will take a bit of work because we'll need to upload all of our images to our GCS bucket.

**Comment by beaufortfrancois** [comment]
@robdodson does #4300 makes sense in the meantime?

**Comment by prathamesh-gharat** [comment]
CLS - It's the cookie banner at the bottom.
![Screenshot](https://i.imgur.com/mwMWZTZ.png)
https://webpagetest.org/result/201203_Di3H_3333e04fe1c3fd6998b9d795722d03fb/

webpagetest.org script
```
block	chunk-b9c21372.js
navigate	https://web.dev/async-clipboard/
```

I don't understand why it's registering as a layout shift though since its position is fixed. You might want to look into what's happening in chunk-b9c21372.js

Another CLS issue related to the font loading but not related to the issue being discussed in this thread: https://youtu.be/XmLz6b1Kbmo

**Comment by beaufortfrancois** [comment]
> @robdodson does #4300 makes sense in the meantime?

@robdodson gentle ping post CDS

**Comment by robdodson** [comment]
adding it to our OKRs to dig into this more

**Comment by beaufortfrancois** [comment]
@robdodson added this issue to web.dev OKRs.

**Comment by robdodson** [comment]
It sounds like some of this will be resolved when M91 fixes its CLS bug. I can help dig up the details on it if anyone starts working on this.

**Comment by robdodson** [comment]
I think this is fixed now

![image](https://user-images.githubusercontent.com/1066253/122606320-9a8d7680-d02d-11eb-9a64-66f695fca439.png)
