### ISSUE TITLE
content: improve FAQ usage in schemeful-samesite post

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#4278]
FAQs should **supplement** the main content, not **compete** with the main content.

In the case of the https://web.dev/schemeful-samesite (here is a [snapshot](https://drive.google.com/file/d/1AViW_jGZg5KPD69R0P8rXxFibGWyhNVL/view?usp=sharing) of the content from when I wrote this feedback), the main content mentions this about migrating to HTTPS:

![image](https://user-images.githubusercontent.com/4713486/99852160-44a72d80-2b35-11eb-94da-0d1264a73268.png)

If you scroll down to the FAQ, you see that the FAQ also discusses the topic of migrating to HTTPS more:

![image](https://user-images.githubusercontent.com/4713486/99852231-6d2f2780-2b35-11eb-959e-48ad5324fb0f.png)

This FAQ content is highly relevant to the main content, yet it's not mentioned in the main content. Therefore the FAQ is competing with the main content.

The way to remedy this is to either:

* Discuss this topic in the main content (i.e. move this entire FAQ section into the main content)
* Link to the FAQ from the main content (see the bold text below for an example)

```
If you haven't fully upgraded your website yet then this should be the priority.
However, if there are cases where your site visitors will go between HTTP and
HTTPS then some of those common scenarios and the associated `SameSite` cookie
behavior are outlined below. **See [What if I can't upgrade to HTTPS?](#link-to-section-id)
for more help.**
```

We can have FAQs. I'm not saying here that FAQs are banned from web.dev. FAQs are probably a great SEO tactic, because it allows us to reformulate ideas in the words of our users. But they are not a good way to primarily organize ideas.

This approach to FAQs originally comes from @jpmedley. You can read more about it in https://kayce.basqu.es/blog/faqs

**Comment by mihajlija** [comment]
Working on it 👷🏻‍♀️

**Comment by mihajlija** [comment]
Not stale, I'll get to it this weekend.
