### ISSUE TITLE
Bring back "Progressive Web Apps on Desktop" article

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChrome/web.dev#4295]
I see that most articles related to PWA was moved from Web Fundamentals to web.dev. But I can't find the "Progressive Web Apps on Desktop" article. It seems it was removed from Web Fundamentals and for some reason not published on web.dev. Why?

https://web.archive.org/web/20200217065655/https://developers.google.com/web/progressive-web-apps/desktop

@petele cc.

**Comment by FluorescentHallucinogen** [comment]
This is not stale.

**Comment by robdodson** [comment]
@petele do you know what happened to this post?

**Comment by petele** [comment]
Yah, it's on my TODO list to bring it back. I'll try to get to it next week.

**Comment by FluorescentHallucinogen** [comment]
@petele @b1tr0t PTAL again.
