### ISSUE TITLE
 Code links use wrong styling.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#430]
https://web.dev/reliable/identify-resources-via-network-panel

![image](https://user-images.githubusercontent.com/1066253/48317343-44b6df00-e5a5-11e8-9d67-b34537490e60.png)

It looks like there's a leftover devsite style for `a code { ... }`. I think these should use the same styling we use elsewhere for links.

**Comment by MaximKazionov** [comment]
Hi there, can I be assigned to this issue!?

**Comment by TimvdLippe** [comment]
@MaximKazionov Feel free to work on this and open a PR. We are happy to review :)

The only requirement is that you need to be a Googler to make changes to our styling, as that is sadly not open source at this moment. I am not sure if you are, but if you are not we probably need to leave this issue open for someone else to work on.

**Comment by robdodson** [comment]
Taking a look. It seems like linked code snippets are currently using the wrong color.

![image](https://user-images.githubusercontent.com/1066253/50111531-d2fc3180-01f1-11e9-9f03-06971490e2fe.png)

https://web.dev/reliable/http-cache

But it seems like links inside of notes are working as intended.

**Comment by robdodson** [comment]
Should be fixed in v1
