### ISSUE TITLE
Extension provides good results, online tools do not

### ISSUE THREAD

**Issue by katsar0v** [GoogleChrome/web.dev#4308]
**Describe the bug**
I am not sure if this is a bug, but I cannot explain this functionality for me, which is also maybe unexpected from many users. I have installed the Chrome Extension and it shows almost always better results than https://web.dev/measure/ for example. I am also not sure on what kind of hardware (virtualized) https://web.dev/measure/ runs, but it seems to be kind of slow and because my PC is fast, results look good. Maybe the extension should be used in a specific way?

**To Reproduce**
1. Install the extension
2. Visit a website with your browser
3. Check extension results
4. Run https://web.dev/measure/ and compare results.

**Expected behavior**
I would expect the extension to deliver similar results to these from https://web.dev/measure/

**Screenshots**
Applies basically to any website, so there is no need for a screenshot

**Comment by prathamesh-gharat** [comment]
If you could post the screenshots from both local and online tests it would help identify the reason for the differences.

This might be related to the test server location. More details here https://github.com/GoogleChrome/web.dev/issues/4321

**Comment by katsar0v** [comment]
Sure. Desktop from Browser extension:

![image](https://user-images.githubusercontent.com/7236157/101325894-c8b72000-386c-11eb-8cae-f8986ba085a2.png)

Google PageSpeed desktop:

![image](https://user-images.githubusercontent.com/7236157/101326000-ee442980-386c-11eb-8423-5b855aebd7eb.png)

Mobile:

![image](https://user-images.githubusercontent.com/7236157/101326013-f43a0a80-386c-11eb-9933-7b8654d86d78.png)

Using this extension is confusing and actually does not help me at all...

**Comment by prathamesh-gharat** [comment]
@katsar0v - If you have a better computer locally then the results will be better. These are not scores but metrics which you can use as guide to identify problem areas.

e.g. Try to run lighthouse test locally as 'Mobile' and not 'Desktop', you would see a lower score.

You should also take into consideration that this is just approximate emulation of Moto G4 CPU speed. e.g. If you emulate Moto G4 on a high end PC the scores will be better than if you perform the same test on a 6 year old laptop.

The performance on real device will vary. Similarly Moto G4 is not the only device out there. I hope you can see the point I'm trying to get at.

**Comment by katsar0v** [comment]
@prathamesh-gharat thank you for the clarification. I think we should note this. Google PageSpeed and lighthouse can be pretty misleading...

**Comment by robdodson** [comment]
yeah, it's not super noticeable but we do state the settings that /measure is using at the bottom of the page.

![image](https://user-images.githubusercontent.com/1066253/105415647-db53a180-5bed-11eb-97d4-5b05dd6c303c.png)

But in #4321 @prathamesh-gharat suggested that we also more clearly state that /measure is using a centralized data center to run its tests (whereas PSI is distributed more globally).
