### ISSUE TITLE
content: Provide information about the future contrast algorithm APCA

### ISSUE THREAD

**Issue by OrKoN** [GoogleChrome/web.dev#4315]
### What page(s) need to be updated?

https://web.dev/color-and-contrast-accessibility/

### Why is this update needed?

Chrome DevTools has implemented the support for APCA as an experiment. DevTools links to https://web.dev/color-and-contrast-accessibility/ to provide more context about contrast threshold such as AA/AAA. It'd be helpful to include some information about the new algorithm called APCA that is intended as a replacement for AA/AAA in the future. More context:

1. crbug (https://bugs.chromium.org/p/chromium/issues/detail?id=1121900)
2. Visual Contrast explainer (https://w3c.github.io/silver/guidelines/explainers/visualContrast.html)
3. APCA calculator (https://www.myndex.com/APCA/)

Note that APCA is still an experiment and it is subject to changes.

### What's the deadline?

no deadline

#### Is it a hard deadline?

no

**Comment by mathiasbynens** [comment]
To be clear, adding just a short paragraph about APCA would be sufficient for now (since APCA is still being developed). We just need something to link to from within DevTools so users can learn more.

**Comment by robdodson** [comment]
> To be clear, adding just a short paragraph about APCA would be sufficient for now (since APCA is still being developed). We just need something to link to from within DevTools so users can learn more.

@mathiasbynens do you know if anyone on the devtools team would be willing to send in a PR for the paragraph? I've been so focused on web.dev and developer.chrome.com that I'm not familiar with it (only heard about it in passing from Adam Argyle).

**Comment by mathiasbynens** [comment]
@OrKoN Do you wanna give that a go? I think we don't need much, just a sentence or two mentioning APCA would do.

**Comment by chybie** [comment]
I will submit a paragraph.
