### ISSUE TITLE
Author images not being updated

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#4318]
**Describe the bug**
I updated PJ's author image in #4302 on Wednesday, but today (Monday), it's still serving the old image.

**To Reproduce**
1. Compare image served on https://web.dev/promote-install/
2. To image at https://github.com/GoogleChrome/web.dev/blob/master/src/images/authors/pjmclachlan%402x.jpg

**Expected behavior**
They should be the same.

**Comment by robdodson** [comment]
I think this should be resolved now that we've purged the image CDN. Because we use a stale-while-revalidate service worker strategy it may take a couple of refreshes to clear the old image. Let me know if that doesn't work and I can try something else.
