### ISSUE TITLE
Feature Request - Display server location

### ISSUE THREAD

**Issue by prathamesh-gharat** [GoogleChrome/web.dev#4321]
When we compare web.dev lighthouse results to those from GT Metrix / webpagetest.org we always have certain discrepancies between the scores which we believe can be attributed to the geographically distant web.dev's test server and the target website's server. (i.e. My website server could be located in India and web.dev could be running the test from the US).

Presently the location of the test server is not shown to the end-user in web.dev. The test server location could help us disregard the warnings about high server response time, high LCP (related to loading above the fold banner images), etc if the website is only targetting a specific country.

For the time being, just having visibility into the test server location should help.
A long term goal could be to provide a way to select a data center to run the web.dev test from.

**Comment by prathamesh-gharat** [comment]
Someone, please change the label to 'feature request'.

**Comment by katsar0v** [comment]
Sure. Desktop from Browser extension:

![image](https://user-images.githubusercontent.com/7236157/101325894-c8b72000-386c-11eb-8cae-f8986ba085a2.png)

Google PageSpeed desktop:

![image](https://user-images.githubusercontent.com/7236157/101326000-ee442980-386c-11eb-8423-5b855aebd7eb.png)

Mobile:

![image](https://user-images.githubusercontent.com/7236157/101326013-f43a0a80-386c-11eb-9933-7b8654d86d78.png)

Using this extension is confusing and actually does not help me at all...

**Comment by samthor** [comment]
Thanks for the issue report. As someone not in the US, I definitely appreciate this issue.

I highly suspect but cannot confirm that the Lighthouse serve is running in us-central or similar (whatever the default App Engine region is).

**Comment by robdodson** [comment]
> I highly suspect but cannot confirm that the Lighthouse serve is running in us-central or similar (whatever the default App Engine region is).

yep that's correct. I think adding this label could be good.

**Comment by gkweb** [comment]
This is definitely an issue for us in Australia. I found tests on web.dev to be pretty inaccurate vs tests done within chrome dev tools.

**Comment by jeffposnick** [comment]
Confirmed that it's currently [`us-central1`](https://cloud.google.com/compute/docs/regions-zones#:~:text=Skylake%2C%20Cascade%20Lake-,us%2Dcentral1%2Da,-Council%20Bluffs%2C%20Iowa).

**Comment by jeffposnick** [comment]
Revisiting this: as part of the shift from using a dedicated Lighthouse server running on App Engine to using the PageSpeed Insights API, we lost the ability to definitively know where the report was run.

The PageSpeed Insights API [docs](https://developers.google.com/speed/docs/insights/v5/about#what-device-and-network-conditions-does-lighthouse-use-to-simulate-a-page-load) suggest that:

> PageSpeed also runs in a Google datacenter that can vary based on network conditions, you can check the location that the test was by looking at the Lighthouse Report's environment block... Note: PageSpeed will report running in one of: North America, Europe, or Asia.

However, that information does not appear to be accurate, as the `environment` results that I see from the API [currently only include](https://developers.google.com/speed/docs/insights/rest/v5/pagespeedapi/runpagespeed#environment) `networkUserAgent`, `hostUserAgent`, and `benchmarkIndex` properties. None of those have information about the region of the sever.
