### ISSUE TITLE
content: strict CSP [2020-12-14]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#4326]
* [draft](https://docs.google.com/document/d/1TK7qa3LkKaTEx4klSRRYMmg9y43CW10v_rQm6xk3bV4/edit?resourcekey=0-WyFvJbuwpeAtQvJkUvjHIw)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/xn21rU3Qbuw)

**Comment by mihajlija** [comment]
Review in progress.
