### ISSUE TITLE
content: update LH third party facades audit page

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/web.dev#4334]
### What page(s) need to be updated?

https://web.dev/third-party-facades/

### Why is this update needed?

There are two important changes we discussed in the original PR (https://github.com/GoogleChrome/web.dev/pull/4316) and one minor revision:
- The audit was recently merged in LH, we can add a link to the [source code](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/third-party-facades.js)  as per https://github.com/GoogleChrome/web.dev/pull/4316#discussion_r532528310
- We still need to add the facade additions process link (https://github.com/GoogleChrome/web.dev/pull/4316#discussion_r533717049)
- Instead of having a specific section for a general iframes facade, call out generic iframe loaders in the paragraph above. What do you think of something like:

![Screen Shot 2020-12-03 at 11 54 02 AM](https://user-images.githubusercontent.com/6752989/101061223-3fe37000-355e-11eb-8301-37103b7f6f4e.png)

#### Is it a hard deadline?

Yes, Dec 10. The additions process specifically is something we would like to have when the audit releases in LHv7.

**Comment by adamraine** [comment]
@kaycebasques @mihajlija please take a look when you get the chance.

**Comment by mihajlija** [comment]
@adamraine Hey Adam, could you submit a PR with these updates? I'll be available tomorrow to review/merge it.
