### ISSUE TITLE
A page is reloading infinitely

### ISSUE THREAD

**Issue by prathamesh-gharat** [GoogleChrome/web.dev#4335]
Initially, I thought it was something to do with my browser extensions but recently I observed the same on webpagetest.org
Concerned page: https://web.dev/async-clipboard/
Webpagetest: https://webpagetest.org/lighthouse.php?test=201203_Di23_ec88149484e6c2a65ff504f2120c6f81&run=1

I am unable to consistently reproduce this behavior.

**Screenshots**
https://i.imgur.com/ICjSX58.png

**Comment by robdodson** [comment]
I wonder if this is caused by the Glitch embed? If you have any more details on how to reproduce I'm happy to reopen.
