### ISSUE TITLE
content: mention DevTools support for content-visibility

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChrome/web.dev#4348]
### What page(s) need to be updated?

https://web.dev/content-visibility/

### Why is this update needed?

The current article explains how to implement `content-visibility` but not how to debug and test it. https://twitter.com/slightlylate/status/1336030256629575681 is an example of lesser known DevTools functionality that could be explained as part of this write-up.

### What's the deadline?

asap

#### Is it a hard deadline?

no

**Comment by mathiasbynens** [comment]
(commenting to prevent the issue from being closed) 

@una PTAL once you get back, thanks!

**Comment by mathiasbynens** [comment]
Gentle ping @una

**Comment by una** [comment]
Ah sorry, slipped my TODO, will add!
