### ISSUE TITLE
Quota exceeded from Measure Core Web Vitals Example

### ISSUE THREAD

**Issue by Iazzetta** [GoogleChrome/web.dev#4349]
When we run the command from example we get a Quota Exceeded.

Link: https://developers.google.com/codelabs/chrome-web-vitals-psi-crux?continue=https%3A%2F%2Fdevelopers.google.com%2Flearn%2Fpathways%2Fweb-vitals%3Fhl%3Den%23codelab-https%3A%2F%2Fdevelopers.google.com%2Fcodelabs%2Fchrome-web-vitals-psi-crux&hl=en#1

**response.txt**

```
{
  "error": {
    "code": 429,
    "message": "Quota exceeded for quota group 'default' and limit 'Queries per 100 seconds' of service 'pagespeedonline.googleapis.com' for consumer 'project_number:583797351490'.",
    "errors": [
      {
        "message": "Quota exceeded for quota group 'default' and limit 'Queries per 100 seconds' of service 'pagespeedonline.googleapis.com' for consumer 'project_number:583797351490'.",
        "domain": "global",
        "reason": "rateLimitExceeded"
      }
    ],
    "status": "RESOURCE_EXHAUSTED"
  }
}

```

**Comment by robdodson** [comment]
Reassigning to myself. This is a valid issue but we don't have a good workaround for it just yet. Hoping to have a fix by Q2.

**Comment by robdodson** [comment]
@philipwalton is this something you or your team could look at?

**Comment by philipwalton** [comment]
@addyosmani probably knows. I believe his team maintains this API.
