### ISSUE TITLE
Use the same ToC as developer.chrome.com

### ISSUE THREAD

**Issue by maudnals** [GoogleChrome/web.dev#4352]
**Disclaimer:** Maybe this already exists or has been discussed! I haven't seen it in the [handbook](https://web.dev/handbook/web-dev-components/) or in [open issues](https://github.com/GoogleChrome/web.dev/issues?q=is%3Aissue+is%3Aopen+outline). 

**Is your feature request related to a problem? Please describe.**
When landing on a web.dev article, the structure of the article is not clear at first sight, because it's "buried" within the article body. An outline could help developers be more efficient when reading through a web.dev article.

**Describe the solution you'd like**
Having an easy way to add/generate an outline of the article to an article, with links to all sections. This outline should be positioned at the beginning of the article and I imagine it could be optional.

**Describe alternatives you've considered**
Authors can already create an outline manually.

**Additional context**

**Comment by kaycebasques** [comment]
I think you mean a table of contents? We already have that (top-right of content, below the hero image):

![image](https://user-images.githubusercontent.com/4713486/101700858-a3740e80-3a32-11eb-971b-5d9fd79187b0.png)

![image](https://user-images.githubusercontent.com/4713486/101700885-b1299400-3a32-11eb-9e14-bc3968916d8d.png)

@robdodson & @jimoong I know you two want to maintain a minimal aesthetic on the site but IMO in this case minimalism is interfering with basic usability… the ToC should be enabled by default.

**Comment by robdodson** [comment]
yeah I'm not opposed to rethinking the ToC. On some articles it is _very_ long. Also I feel like the line it creates and the text are too large.

![image](https://user-images.githubusercontent.com/1066253/101706398-d243b200-3a3d-11eb-917a-edc5095d50f7.png)

I'm a lot happier with the ToC on developer.chrome.com. I also think it's easier to discover because it says "Table of Contents".

Maybe we could port it over to web.dev?

**Comment by maudnals** [comment]
+1, the ToC on developer.chrome.com looks great / is easier to discover :)
