### ISSUE TITLE
Make landing pages more customizable

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/web.dev#4367]
It would be great to customize landing pages. For now, they only contain a title, an hero, image, an overview, and list of topics.

For instance, I had to create https://github.com/GoogleChrome/web.dev/pull/4366 to be able to add a YouTube video on a landing page. Hopefully, this could be covered by this feature request.

@robdodson

**Comment by robdodson** [comment]
Moving this to the Eng board temporarily. We have designs and an OKR for more customizable pages so this will probably get its own project board when we start working on it.
