### ISSUE TITLE
Feed's Last-modified set to Tue, 01 Jan 1980 00:00:01 GMT

### ISSUE THREAD

**Issue by alexdebril** [GoogleChrome/web.dev#4382]
**Describe the bug**
The Atom feed is provided with a "Last-Modified" header always set to "Tue, 01 Jan 1980 00:00:01 GMT". Hitting it with a earlier date (like "Tue, 01 Jan 1980 00:00:0**2** GMT") specified in "If-Modified-since" header will always lead to a 304 Not Modified.

**To Reproduce**
1. hit https://web.dev/feed.xml with an empty set of headers -> 200 OK with "Last-Modified" set to "Tue, 01 Jan 1980 00:00:01 GMT" 
2. hit the same URL with "If-Modified-Since: Tue, 01 Jan 1980 00:00:02 GMT" in the headers
3. get a 304 Not Modified although we know the feed was updated several times since 1980

**Expected behavior**
- The date provided by "Last-Modified" should match the last publication in the feed
- We should get a 304 only if there's nothing new in the feed since the date specified in "If-Modified-Since" 

**Screenshots**
not applicable

Thank you very much for taking care of this

**Comment by samthor** [comment]
Thanks, this seems like an unfortunate recent limitation of App Engine.

FWIW, we will be solving this as part of #4381. I don't think we'll fix it before then.
