### ISSUE TITLE
Which solution is the best for the map app?

### ISSUE THREAD

**Issue by oekraiens** [GoogleChrome/web.dev#4385]
I choose Advanced caching, but finally faced with the problem:
"start_url does not respond with a 200 when offlineThe start_url did respond, but not via a service worker."

![advanced](https://user-images.githubusercontent.com/73040546/102136770-88563400-3e62-11eb-9926-dfdd2d9515af.png)
![pwabuilder-sw](https://user-images.githubusercontent.com/73040546/102136789-8ee4ab80-3e62-11eb-9ddf-96213df3a860.png)
![manifest](https://user-images.githubusercontent.com/73040546/102136796-91470580-3e62-11eb-9156-4b7b2ca24da3.png)
![report](https://user-images.githubusercontent.com/73040546/102136801-9310c900-3e62-11eb-9421-d088bcaf3c9d.png)

Could you help, please.

**Comment by robdodson** [comment]
Pinged the folks at PWABuilder https://twitter.com/rob_dodson/status/1338618175294820353

**Comment by jgw96** [comment]
Hey @oekraiens , would you happen to have a repo I could use to reproduce this? Your setup looks right from the screenshots, but I will be able to debug much easier with some code, thanks!

**Comment by oekraiens** [comment]
@jgw96 Done, thank you!

**Comment by oekraiens** [comment]
Thank you, @robdodson !

**Comment by jgw96** [comment]
@oekraiens I'm not seeing the repo in the message, did you post it here or elsewhere? Also @oekraiens , feel free to re-open the issue on our repo https://github.com/pwa-builder/PWABuilder/issues if you want, that would be best as this issue is a PWABuilder related issue.

**Comment by oekraiens** [comment]
@jgw96 Sorry, I invited you as a collaborator.
`https://github.com/oekraiens/airfields`

**Comment by jgw96** [comment]
Hey @oekraiens , figured out the issue! Your app does work offline as my Lighthouse test shows here 
![image](https://user-images.githubusercontent.com/8823093/102271124-c8a1ca80-3ed3-11eb-8d43-651c9f41fd54.png) but your start_url in your manifest is `/index.html` which seems to be tripping up the lighthouse test. This  path for your start_url is actually something i would consider as not best practice anyways though and would recommend that you change your start_url to `/`  as we have here in our starter https://github.com/pwa-builder/pwa-starter/blob/master/manifest.json#L4 . This seems to also solve the testing issue. Thanks again and feel free to open a new issue here https://github.com/pwa-builder/PWABuilder/issues if you run into any more issues.

**Comment by jgw96** [comment]
@robdodson I think this one can be closed now, if @oekraiens runs into any more issues we can cover it on the PWABuilder repo as I mentioned above. Thanks again for the ping!

**Comment by oekraiens** [comment]
@jgw96 It still happens after I change my start_url to /. I follow your advice about PWABuilder hub. 
Appreciate your attention on the issue! Thanks again!
