### ISSUE TITLE
Centering in CSS web.dev article blows up my phone

### ISSUE THREAD

**Issue by steren** [GoogleChrome/web.dev#4391]
See screencast: https://photos.app.goo.gl/bSjUyvxD1GbLcBo86

Opening the article makes everything lag and leads to System UI and Chrome Dev crashing.

**Comment by steren** [comment]
Other articles load fine when. I access them from the blog index

**Comment by robdodson** [comment]
hm weird. We have a number of videos embedded in that article, I'm not sure if their encoding is making the twitter webview do something weird.

@steren are you on iOS or Android?

fyi @argyleink 

btw most of the team is out on holiday break right now so it may take a bit to get this fixed. Tagging in @samthor in case he happens to have spare cycles to look.

**Comment by argyleink** [comment]
it's the first video I've dropped a youtube link in? YT embed related maybe?

**Comment by steren** [comment]
This is Chrome Dev on Android. I can also reproduce in Chrome Dev (outsideof Twitter)

**Comment by robdodson** [comment]
@steren does it blow up if you use Chrome Stable? It's possible that Chrome Dev just has a bug?

**Comment by steren** [comment]
works fine on chrome stable, we can close.

**Comment by steren** [comment]
(or maybe open a bug for Chrome Dev, if it still reproduces)
