### ISSUE TITLE
Wrong initial and link to LCP on FCP page

### ISSUE THREAD

**Issue by edpittol** [GoogleChrome/web.dev#4408]
**Describe the bug**

The explanation between the distinct metrics FCP and LCP has a typo on the initial of Largest Content Paintful and the link URL is https://web.dev/Fcp/.

> You'll notice that though some of the content has rendered, not all of it has rendered. This is an important distinction to make between First Contentful Paint (FCP) and Largest Contentful Paint (FCP) —which aims to measure when the page's main contents have finished loading.

**To Reproduce**
1. Go to 'https://web.dev/fcp/'
3. Scroll down to the last paragraph of 'What is FCP?' section

**Expected behavior**
The initials of Largest Contentful Paint should be LCP and the link URL should be https://web.dev/lcp/.

**Screenshots**
![image](https://user-images.githubusercontent.com/352790/103024181-1babfb00-452e-11eb-9350-d771dd6b0329.png)

**Comment by samthor** [comment]
Thanks. This is a detailed bug report. Can you send us a PR to fix? ;-)
