### ISSUE TITLE
Image is cut off on mobile device window size when using `.w-screenshot--filled` css class

### ISSUE THREAD

**Issue by kazuyaseki** [GoogleChrome/web.dev#4416]
**Describe the bug**
Image is cut off on mobile device when using `.w-screenshot--filled` css class(see screenshots below)
I could check that on Chrome and Safari on iOS 14.3 iPhone.

it's not so good in terms of visual, but also it causes the article content to move as you scroll in Chrome since the image is overflowing which makes harder to concentrate on reading article.

**To Reproduce**
1. Open any page that is using `.w-screenshot--filled` to an img tag with mobile device
ex. https://web.dev/lcp/ or https://web.dev/render-blocking-resources/
2. find a image whose background is gray

**Expected behavior**
appropriate amount of padding around image, no overflow

**Screenshots**
<img width="375" alt="スクリーンショット 2020-12-28 21 29 32" src="https://user-images.githubusercontent.com/6080698/103214484-db94b000-4953-11eb-86dd-581ff03fd4c5.png">
<img width="344" alt="スクリーンショット 2020-12-28 21 29 48" src="https://user-images.githubusercontent.com/6080698/103214490-df283700-4953-11eb-85f0-a5dc13794e82.png">

**Comment by Raushan132** [comment]
I can fix it ....
i fix its center of the screen...
