### ISSUE TITLE
Large difference in LCP between web.dev and PageSpeed Insights

### ISSUE THREAD

**Issue by prathamesh-gharat** [GoogleChrome/web.dev#4419]
**Describe the bug**
As the title describes the LCP different is high across multiple tests between web.dev and PSI.

I believe PSI is in the wrong here since webpagetest.org shows a LCP of 0.663s with Emulated MotoG4 (lighthouse test)
https://webpagetest.org/result/201230_DiJ6_3a8c9afe77311930788732d7d476006b/

**To Reproduce**
1. Test the link: https://www.organicfacts.net/apple-cider-vinegar.html on both web.dev and [PSI](https://developers.google.com/speed/pagespeed/insights/)
2. Compare LCP metric

**Expected behavior**
LCP should not have a large difference.

**Screenshots**
https://imgur.com/a/vkxlVx2 ( Please compare the LCP in the two screenshots in the album )

**Comment by robdodson** [comment]
One issue is that web.dev/measure is not as distributed as PSI. I believe PSI will use whichever datacenter is closest to the client making the request, whereas web.dev/measure uses something like us-central-1 for all requests. So if a site is not distributed on a CDN (but its server is close to us-central-1) then you could see a fast response from the server which might reduce the LCP. That's just a guess though.

In general there's not much we can do about it except to say that we're working on improvements to how web.dev does its measurement work which we hope to share soon.

**Comment by prathamesh-gharat** [comment]
This was added
Ref: https://github.com/GoogleChrome/lighthouse/issues/13209#issuecomment-970720220
