### ISSUE TITLE
web.dev Lighthouse scores are different from DevTools scores

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/web.dev#442]
When I run a Lighthouse audit from web.dev, I get different results than when running from the DevTools. Some of the web.dev Lighthouse warnings seem wrong, e.g. _Does not register a service worker_. I've tried **Clear site data**, etc.

---

**web.dev**

![image](https://user-images.githubusercontent.com/205226/48330991-8aa29000-e603-11e8-8038-8cc76dcafd90.png)

---

**DevTools**

![image](https://user-images.githubusercontent.com/205226/48331014-a148e700-e603-11e8-96d1-e945398e8dbf.png)

---

**DevTools settings**

![image](https://user-images.githubusercontent.com/205226/48331094-d6553980-e603-11e8-80de-3c3eaf25c35a.png)

**Comment by luisalvarado** [comment]
Try https://www.kidstherapyfinder.com it gives me very different results between wed.dev and Google Chrome devtools using the latest stable version of Google Chrome.

**Comment by BluePigMedia** [comment]
We are running into the same issue with significant delta between Google testing platforms for many sites we work on. 

Example: https://davidc353.sg-host.com/

https://web.dev/measure/ 
100 Performance Score
FCP 0.3s
Speed Index 0.6s
LCP 1.2s
Time to Interactive 0.3s
Total Blocking Time 0 ms
Cumulative Layout Shift 0.01

Lighthouse in Chrome Dev Tools (Incognito Mode) on Mac Desktop Running Version 95.0.4638.69 (Official Build) (x86_64) with no extensions running

80 Performance Score
FCP 1.9s
Speed Index 1..9s
LCP 3.4s
Time to Interactive 4.3s
Total Blocking Time 370 ms
Cumulative Layout Shift 0.006

Page Speed Insights 

58 Performance Score
FCP 1.9s
Speed Index 3.4s
LCP 3.0s
Time to Interactive 7.2s
Total Blocking Time 3490 ms
Cumulative Layout Shift 0.01

The reason this is important is Core Web Vital and Page Experience. One Google tools is rating our work as Gods, one as average student and one as a failure. Does anyone have any idea on what is going on and which of the three Google tools we should trust?
![Screen Shot 2021-11-04 at 1 05 07 PM](https://user-images.githubusercontent.com/46525820/140385842-8717e540-835a-49bf-a3db-f322583aab44.png)

![Screen Shot 2021-11-04 at 1 07 27 PM](https://user-images.githubusercontent.com/46525820/140386028-aa34129a-26e1-4a35-8ecd-8c0af85eb857.png)

![Screen Shot 2021-11-04 at 1 07 45 PM](https://user-images.githubusercontent.com/46525820/140386085-c67a5ea8-6fa4-40c4-9a98-a9511a88163b.png)

**Comment by NikkiMather** [comment]
I'm having the exact same issue. I assume the devs have, uh, just stopped caring?

**Comment by devnook** [comment]
Not exactly. Web.dev is using now Pagespeed Insights API, so the results should be the same as on PSI: https://pagespeed.web.dev/
You can read more about the differences in the FAQ at the bottom of the page: https://web.dev/measure/
If you still see discrepancies, please share the url you're measuring and I'll forward it to respective team.
