### ISSUE TITLE
content: Move "Async functions" article from WebFu

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#4437]
* Use this template to request updates to existing content.
* Delete any fields that aren't relevant to your issue. 
* Update the title of this issue with a brief summary of the work to be done.

### What page(s) need to be updated?

https://developers.google.com/web/fundamentals/primers/async-functions

### Why is this update needed?

[Top-level wait](https://www.chromestatus.com/features/5767881411264512) is shipping in Chrome 89. The most logical place to put this is in the existing async functions article. (This feature has already been merged to the Chrome 89 branch, so there's no question about whether it will ship.)

(While we're at it, we should make reciprocal links between this and [JavaScript Promises](https://web.dev/promises/).)

### What's the deadline?

January 28

#### Is it a hard deadline?

Yes. It would be nice to have something to link to in the beta release blog. 

If yes, please explain why.

**Comment by jpmedley** [comment]
By the way, "JavaScript Promises" is in our top 30. I think we're giving incomplete information if we don't also direct readers to async and away.

![image](https://user-images.githubusercontent.com/8204171/103808437-d519ce80-500c-11eb-8bdb-fac506fb2dea.png)

**Comment by jpmedley** [comment]
@jakearchibald Any issues with what I've proposed here?

**Comment by jakearchibald** [comment]
Sounds good to me!

While I've got your attention, I've got a couple of article PRs that have stalled. Is there something I need to do to get them moving? They're ready to merge & go.

- https://github.com/GoogleChrome/web.dev/pull/4322
- https://github.com/GoogleChrome/web.dev/pull/4332
