### ISSUE TITLE
दूध

### ISSUE THREAD

**Issue by svyas845** [GoogleChrome/web.dev#4460]
[ दूध पीनें के फायदें, और नुकसान     भारतीय संस्कृति और समाज में दूध इस तरह से रचा बसा हैं कि बिना दूध के किसी सांस्कृतिक या धार्मिक आयोजन की कल्पना करना भी असंभव हो जाता हैं । यहाँ तक की भारतीयों ने अंग्रेजों से विरासत में मिली चाय को भी दूधमय कर दिया हैं आज के सन्दर्भ में बिना दूध के चाय की  कल्पना भी नहीं की जा सकती हैं ।   दूध का नाम लिया और गोपाल कृष्ण कन्हैया के नाम  का जिक्र न हो तो लेख अधूरा सा लगता हैं कृष्ण भगवान जिनका बचपन ही गाय ,दूध और माखन के इर्दगिर्द घूमता हैं । दूध को सम्पूर्ण आहार माना गया हैं ।और भारत विश्व का सबसे बड़ा दुग्ध उत्पादक राष्ट्र हैं ।   तो आईयें जानतें हैं दूध पीनें के फायदे और नुकसान के बारें में जाननें से पहलें दूध के बारें में कुछ आवश्यक जानकारी के बारें में      गाय के दूध में पाए जानें वाले पौषक तत्व Nutritional value of cows milk    कार्बोहाइड्रेट ---------- 5.26 ग्राम    वसा         -------------- 3.25 ग्राम    प्रोटीन      ---------------- 3.22 ग्राम    विटामीन ए --------------- 28 iu   विटामीन B1---------------- 0.44 मिलीग्राम    विटामीन B2 ----------------- 0.183 मिलीग्राम   विटामीन D -------–----------- 40 IU    कैल्सियम ---------------------- 113 मिलीग्राम   मैग्निशियम ------------------- 10 मिलीग्राम   पोटेशियम -----------------------:143 मिलीग्राम    पानी --–---------------–---------- 88.32 ग्राम                                (प्रति 100 ग्राम)      दूध पीने के फायदे और नुकसान दूध पीने के फायदे और नुकसान    भैंस के दूध में पाए जानें वालें पौषक तत्व Nutritional value of Buffalo milk    प्रोटीन ---------------- 3.5 ग्राम   कार्बोहाइड्रेट----------- 4.9 ग्राम    वसा (फेट)-------------- 6.0 ग्राम    सैचुरेटेड फैट----------3.8 ग्राम    पाली और मोनो सैचुरेटेड------------ 1.8 ग्राम    कोलेस्ट्राँल------------------ 17.0 मिलीग्राम    कैल्सियम -------------------- 0.15 ग्राम    विटामीन A -------------------- 90 mcg    विटामीन‌ D ---------------------- 1.0 mcg   फास्फोरस ---------------------- .09 ग्राम    सोडियम ------------------------ .03 ग्राम    पोटेशियम ----------------------- 0.1 ग्राम    ऊर्जा ------------------------------ 85 Kcal.                                     ( प्रति 100 ग्राम )     दूध पीनें के फायदें    मांसपेशियां मज़बूत बनती हैं      दूध में पर्याप्त मात्रा में प्रोटीन मौजूद रहता हैं जिससे शरीर की मांसपेशी मज़बूत बनती हैं । दूध पीनें वालें व्यक्ति की मांसपेशियां बहुत कम क्षतिग्रस्त होती हैं साथ ही क्षतिग्रस्त मांसपेशी बहुत शीघ्रता से जुडती हैं । प्रोटीन शरीर के क्षतिग्रस्त ऊतकों की मरम्मत और नयें ऊतकों के निर्माण का कार्य करता हैं ।     हड्डीयाँ मजबूत बनती हैं      दूध में मोजूद कैल्सियम, फास्फोरस और विटामीन‌ D हड्डीयों के स्वास्थ्य को बनायें रखता हैं । प्रतिदिन 300 मिलीलीटर दूध पीनें वाले व्यक्ति को ओस्टियोपोरोसीस होनें की संभावना उन लोगों के मुकाबले जो दूध नहीं पीतें हैं के मुकाबलें 90 प्रतिशत कम होती हैं ।   दूध पीनें से चोंट के दौरान हड्डी फ्रेक्चर होनें की संभावना बहुत कम हो जाती हैं ।    दाँतों को मज़बूत बनाता हैं    दूध में मोजूद फास्फोरस और विटामीन‌ D बच्चों एंव बड़ों के दाँतों को स्वस्थ और मजबूत बनाता हैं । दूध पीनें से समय से पहलें दाँत गिरनें की समस्या से निजात मिलती हैं। दाँतों पर प्लांक जमनें की समस्या से मुक्ति मिलती हैं ।      मस्तिष्क का सही विकास होता हैं   दूध पीनें से मस्तिष्क का सही विकास होता हैं । मां के दूध के बाद बच्चे के विकास के लिए गाय का दूध सर्वोत्तम माना जाता हैं , प्रतिदिन गाय का दूध पीनें से बच्चें का मस्तिष्क बहुत तेजी से विकसित होता हैं ।    दूध अवसाद से बचाता हैं    दूध में मौजूद पोटेशियम,सोडियम और कैल्सियम स्ट्रेस ब्रस्टर Stress burster का काम करतें हैं । अत:तनाव को दूर करनें के लिए रात को दूध का सेवन करना चाहिए ।    हाई फेट high fat दूध वजन बढ़ाता हैं    दुबले पतले व्यक्ति यदि वज़न बढानें की कोशिश कर रहें हैं तो उन्हें प्रतिदिन मलाईयुक्त दूध का सेवन करना चाहिए ।    खिलाड़ियों के लिए दूध के फायदें   खेलों की दुनिया में नाम चाहनें वाले खिलाड़ी जो विगन vegan हैं उनके लिए दूध किसी वरदान से कम नहीं हैं । ऐसें खिलाड़ी यदि प्रतिदिन दूध का सेवन करतें हैं तो खेलों में बहुत शीघ्रता से नाम रोशन करतें हैं ।     आंखों के लिए दूध के फायदें   दूध में मौजूद विटामीन ए आंखो के स्वास्थ को उत्तम बनाए रखता हैं । प्रतिदिन दूध के सेवन से आंखो में चश्मा नहीं लगता हैं,मोतियाबिंद होनें की संभावना कम हो जाती हैं ।    समय समय पर आँखों में दूध से निकली मलाई का अंजन करनें से मोबाइल,कम्प्यूटर से निकलनें वाली रोशनी से आँखें सुरक्षित रहती हैं । और Digital eye strain की समस्या नहीं होती हैं ।     दूध वजन नियत्रिंत करता हैं     स्किम्ड दूध जिसमें वसा की मात्रा 0.3 प्रतिशत होती हैं का सेवन वज़न नियंत्रित करता हैं । प्रतिदिन दो गिलास स्किम्ड मिल्क का सेवन करनें से मेटाबॉलिज्म रेट बढ़ जाती हैं और इस तरह शरीर से अतिरिक्त वसा ऊर्जा के रूप में बाहर निकल जाती हैं ।     गर्भावस्था में दूध पीनें के फायदे    गर्भवती महिलाओं के लिए दूध पीना सम्पूर्ण आहार माना जाता है दूध के सेवन से माता और गर्भस्थ शिशु का सम्पूर्ण विकास होता हैं ।     गर्भावस्था के दौरान दूध का सेवन करनें वाली महिलाओं के बच्चें कम रोने वाले,कम चिड़चिड़े और बहुत खुशमिजाज होते हैं ।    गर्भावस्था में दूध पीना अन्य खाद्य पदार्थों की तुलना में बहुत फायदेमंद होता हैं क्योंकि दूध बहुत जल्दी पच जाता हैं जबकि दूसरे खाद्य पदार्थ बहुत देर से पचते हैं इस कारण स्त्री को बदहजमी, उल्टी, सिरदर्द जैसी समस्या नहीं होती हैं ।     कामोत्तेजना बढ़ाने में दूध के फायदे   भैंस का दूध पीनें से स्त्री और पुरुष दोनों की कामोत्तेजना बढ़ती हैं । यदि रात को सोने से एक घंटे पहले एक गिलास दूध स्त्री और पुरूष दोनों पीना शुरू कर दें तो कामोत्तेजना में उल्लेखनीय सुधार आता है ।    दूध पीनें से पुरुष के शुक्राणु की गति बढ़ती है जबकि स्त्री के अंडाणु स्वस्थ बनते हैं ।     दूध पीनें से त्वचा कोमल होती हैं    दूध में मौजूद केसिन नामक प्रोटीन त्वचा की मृत कोशिकाओं की मरम्मत कर नई कोशिका का निर्माण करनें में मदद करता हैं । यदि प्रतिदिन एक गिलास दूध खाली पेट पीया जावें तो चेहरें की त्वचा चमकीली और तंदुरुस्त रहती हैं ।    दूध में पानी मिलाकर दूध पीनें के फायदे   दूध का औसत pH value 6 से 7.50 के बीच होता हैं जो अम्लीय होता हैं पानी का ph value 7 से 8 के बीच होता हैं। जो कि उदासीन से लेकर हल्का क्षारीय होता हैं । यदि हम दूध में उसके भार के मान से 25 प्रतिशत पानी मिलाकर पीतें हैं तो यह मिश्रण हमारें रक्त के ph value के बराबर हो जाता हैं । इस तरह दूध और पानी मिलाकर पीनें से रक्त के सभी अवयव जैसें RBC,WBC आदि अपनें स्वस्थ और नियत अनुपात में बनें रहतें हैं ।     बालों के लिए दूध पीनें के फायदे   दूध में मौजूद प्रोटीन और कैल्सियम बालों को झड़नें से रोकतें हैं । रोज एक गिलास दूध के सेवन से बाल झड़नें और दोमुंहे होनें जैसी समस्या नहीं पैदा होती हैं ।     आपरेशन होनें के बाद दूध पीनें के फायदें   आपरेशन या सर्जरी होनें के बाद प्रतिदिन 300 मिलीलीटर गाय का दूध या डबल टोंड दूध नियमित रूप से पीनें से आपरेशन या सर्जरी के बाद रिकवरी बहुत तीव्र गति से होती हैं और व्यक्ति हास्पिटल से जल्दी डिस्चार्ज होता हैं ।     महिलाओं के स्तनों का सही विकास होता हैं    जिन महिलाओं के स्तन पूरी तरह विकसित नहीं हो पा रहें हैं ऐसी महिलाओं को नियमित रूप से भैंस का दूध सेवन करना चाहिए क्योंकि दूध में मौजूद कैल्सियम स्तन ग्रंथि को विकसित करनें में मदद करता हैं ।     दूध पीनें से कुपोषण समाप्त होता हैं     दूध में अश्वगंधा, शतावर जैसी औषधियाँ मिलाकर कुपोषित बच्चों को दूध पीलानें से कुपोषित बच्चा अतिशीघ्र सामान्य बच्चों के समान वज़न वाला हो जाता हैं ।     दूध पीनें से पाचन तंत्र सुधरता हैं   दूध में मौजूद लैक्टिक एसिड़ पाचन तंत्र को सही करता हैं । यदि किसी व्यक्ति को भोजन नहीं पच रहा हैं तो भोजन की मात्रा आधी कर आधी मात्रा दूध की रखें या रोटी दूध के साथ मिलाकर खायें ऐसा करनें से पेट से पर्याप्त मात्रा में पाचक रस  स्त्रावित होना शुरू हो जाता हैं ।    दूध पीनें से कैंसर नहीं होता हैं     दूध में मौजूद विटामीन और खनिज लवण शरीर में कैंसर कोशिकाओं को विकसित होनें से रोकतें हैं । यदि प्रतिदिन गाय का दूध का सेवन किया जावें तो कैंसर होनें की संभावना नगण्य हो जाती हैं।    एक तथ्य यह भी हैं कि कैंसर कोशिकाओं की प्रकृति क्षारीय होती हैं जबकि दूध अम्लीय होता हैं जिससे कैंसर कोशिकाओं का विकास बाधित होता हैं ।    रोगप्रतिरोधक क्षमता बढ़ानें में दूध के फायदें   गाय के दूध में पाया जानें वाला पीलापन इसमें मौजूद कैरोटीन के कारण होता हैं यह कैरोटीन युक्त दूध पीनें से मनुष्य की रोगप्रतिरोधक क्षमता में बढ़ोतरी होती हैं ।    दूध पीनें से लम्बाई बढ़ती हैं    ऊँटनी के दूध में कैल्सियम की मात्रा गाय और भैंस के दूध की अपेक्षा बहुत अधिक होती हैं। ऊँटनी के दूध में मौजूद कैल्सियम हड्डीयों का विकास बहुत तेजी से करता हैं जिससे लम्बाई बढ़ती हैं । अत:लम्बाई बढ़ाने के इच्छुक व्यक्ति को ऊँटनी का दूध अवश्य पीना चाहियें ।    दूध पीनें से पागल आदमी ठीक हो सकता हैं    गधी का दूध अत्यंत शीतल प्रकृति का होता हैं इस दूध को यदि पागल आदमी को पिलाया जाए तो उसका दिमाग बहुत जल्दी ठीक होता हैं ।    श्वास और टीबी में दूध के फायदें   बकरी और भेड़ का दूध औषधीय गुणों से संपन्न होता हैं यह दूध यदि श्वास रोगीयों और टीबी ग्रस्त रोगीयों को पिलानें से उनकी बीमारी ठीक हो जाती हैं।     दूध प्राकृतिक टीकाकरण का काम करता हैं   गाय,भैंस,बकरी,ऊँट,और भेड़ के बच्चा पैदा होनें से पाँच दिन तक निकला दूध पीनें से शरीर का प्राकृतिक टीकाकरण हो जाता हैं ऐसा दूध सभी बीमारीयों के विरूद्ध शरीर में एँटीबाडी बनाता हैं ।    दूध पीनें से माहवारी नियमित होती हैं    दूध में मोजूद प्रोटीन और कैल्सियम गर्भाशय की आंतरिक दीवारों की कोशिकाओं की मरम्मत कर अत्यधिक रक्तस्त्राव को नियंत्रित करता हैं । यदि प्रतिदिन सुबह शाम एक गिलास दूध महिलाएं सेवन करें तो माहवारी नियमित होकर अधिक रक्तस्राव की समस्या से निजात मिलती हैं।       विभिन्न प्रकार के दूध    स्किम्ड मिल्क क्या होता हैं    जब संपूर्ण दूध में से फैट या वसा को निकाल लिया जाता हैं तो इस प्रकार के दूध को स्किम्ड मिल्क कहतें हैं । स्किम्ड मिल्क में वसा का स्तर 0.3 प्रतिशत होता हैं । जबकि प्रोटीन 10 ग्राम होता हैं ।     टोंड और डबल टोंड मिल्क क्या होता हैं    जब सम्पूर्ण दूध में से वसा को एक बार निकाला जाता हैं तो यह टोंड मिल्क कहलाता हैं जबकि दो बार वसा निकालनें पर यह डबल टोंड मिल्क कहलाता हैं । टोंड मिस्क में वसा 3 प्रतिशत होता हैं वही डबल टोंड मिल्क में वसा 1.5 प्रतिशत रहता हैं ।     स्टेण्डर्ड मिल्क क्या होता हैं    सम्पूर्ण दूध में से वसा की मात्रा निकालकर इसे 4.5 प्रतिशत के स्तर पर लाकर इसे पीनें लायक बनाया जाता हैं ।     फिल्ड मिल्क क्या होता हैं    सम्पूर्ण दूध में से वसा निकालकर उसके स्थान पर वनस्पति वसा मिलाई जाती हैं ।    रि कम्बाइन्ड मिल्क     बटर आइल, स्किम्ड मिल्क और पानी मिलाकर जो दूध बनाया जाता हैं उसे रिकम्बाइण्ड मिल्क कहतें हैं ।    रिकन्स्ट्यूट मिल्क    जब दूध पावडर को पानी में मिलाकर दूध बनाया जाता हैं तो इसे रिकन्स्ट्यूट मिल्क कहतें हैं ।    सिंथेटिक दूध के बारें में यहाँ जानें     आयुर्वेद अनुसार दूध पीनें के फायदे    अत:क्षीराणिवक्षयन्तेकर्मचैषांगुणाश्चये।अविक्षीरमजाक्षीरंगोक्षीरंमाहिषंचयत्।।उष्ट्रीणामथनागीनांवडवाया:स्त्रियास्तथा।प्रायशोममधुरंस्त्रिग्धंशीतंस्तन्यंपय:स्मृतम्।।प्रीणनंबृंहणंवृष्यंमेध्यंबल्यंमनस्करम् ।जीवनीयंश्रमहरंश्वासकासनिबहर्णम्।।हन्तिशोणितपित्तश्चजसन्धानंविहतस्यच।सर्वप्राणभृतांसात्म्यंशमनंशोधनंतथा।।तृष्णान्घंदीपनीयंचश्रेष्ठक्षीणक्षतेषुच।पाण्डुरोगेम्लपित्तेचशोषेगुल्मेतथोदरे।।अतीसारज्वरेदाहेश्चयथौचविधीयते।।योनिशुक्रप्रदोषेषुमूत्रेष्वप्रसरेषुच।।पुरीषेग्रथितेपथ्यंवातपित्तविकारिणाम्।।नस्यालेपावगाहेषुवमनास्थापनेषुच।।विरेचनेस्नेहनेचपय:सर्वत्रयुज्यते।यथाक्रमंक्षीरगुणानैकैकस्यपृथक्।।अन्नपानादिकेध्यायेभूयोवक्ष्याम्यशेषत:       आयुर्वेद मतानुसार भेड़,बकरी,गाय,भैंस,ऊँटनी,हथनी,घोड़ी, स्त्री इनका दूध शीतल ,मीठा,चिकना,मांसवर्धक,वीर्यवर्धक, बुद्धि वर्धक, बलवर्धक श्वास और कास का नाश करनें वाला ,टूटे स्थान को जोड़नें वाला,रक्त को शुद्ध करनें वाला,तृष्णा का नाश करनें वाला होता हैं ।   पाण्डुरोग,अम्लपित्त,शोध,गुल्म,उदररोग,अतिसार, ज्वर,दाह,सूजन,योनि दोष,शुक्रदोष,मूत्ररोग,में दूध का सेवन करवाना चाहिए। दूध का सेवन करनें से वात और पित्त रोगों का शमन होता हैं ।     दूध पीनें के नुकसान    यघपि दूध पीनें के असंख्य फायदें हैं लेकिन इसके कुछ नुकसान भी हैं जैसें   ० दूध में मौजूद लैक्टोज से कई लोगों को एलर्जी की समस्या होती हैं अत:ऐसे लोग जिन्हें दूध पीनें के बाद एलर्जी की समस्या हो उन्हें दूध पीनें से पहलें चिकितकीय परामर्श अवश्य कर लेना चाहिए ।    ० दूध पीनें के बाद कुछ लोगों को पेटदर्द, उल्टी और दस्त की समस्या पैदा होती हैं ऐसे लोगों को दूध नहीं पीना चाहिए ।    ० कच्चा दूध किसी भी हालत में नहीं पीना चाहियें क्योंकि ऐसे दूध में अंसख्य हानिकारक बैक्टीरिया मौजूद रहतें हैं जो मनुष्य को बीमार कर सकतें हैं ।    ० उच्च रक्तचाप, ह्रदयरोग में दूध चिकित्सकीय सलाहनुसार ही पीना चाहिए ।   ० दवाई गोली के साथ दूध तभी लेना चाहिए जब चिकित्सक ने ऐसा करनें की सलाह दी हो यदि अपनें मन से दवाई के साथ दूध ले लिया जाए तो इसके गंभीर परिणाम हो सकतें हैं ।    ० एक साथ उतना ही दूध पीना चाहिए जितना शरीर की बचानें की क्षमता हो यदि एकसाथ अधिक दूध पी लिया तो दस्त,पेट में मरोड़,उल्टी जैसी समस्या हो सकती हैं ।    ० आयुर्वेद मतानुसार दूध शीतल गुण वाला होता हैं अत:जिन लोगों की प्रकृति शीत गुणों वाली हो उन्हें दूध पीनें से पहले वैधकीय परामर्श अवश्य प्राप्त कर लेना चाहिए ।     दूध में हल्दी मिलाकर पीने के फायदे    दूध मे हल्दी दूध मे हल्दी    आजकल दूध में हल्दी मिलाकर पीने का  विशेषज्ञ सुझाव दे रहें हैं । दूध में हल्दी मिलाकर पीने के अनगिनित फायदे हैं और इसके फायदे को देखते हुये आजकल  हल्दी मिले दूध को "Golden milk " कहा जानें लगा हैं तो आईयें जानतें हैं दूध में हल्दी मिलाकर पीने के फायदें    ० हल्दी मिला दूध कैंसर होनें की संभावना समाप्त कर शरीर में मौजूद कैंसर कोशिकाओं को बढ़ने से रोकता हैं ।    ० हल्दी मिला हुआ दूध शरीर की इम्यूनिटी बढ़ाकर शरीर को रोगों से बचाता हैं ।    ० हल्दी मिला हुआ दूध श्वसन तंत्र की सूजन कम करता हैं जिससे अस्थमा, खाँसी,और एलर्जी की बीमारी में आराम मिलता हैं ।    ० हल्दी मिला दूध त्वचा रोगों की उत्तम औषधि हैं नियमित रूप से हल्दी मिले दूध का सेवन करनें से खुजली,फंगल इंफेक्शन, त्वचा में पित्ती उछलना आदि बीमारीयों में आराम देता हैं ।    ० हल्दी मिला दूध पीनें से मधुमेह होनें की संभावना समाप्त होती हैं और यदि मधुमेह हैं तो नियत्रिंत रहती हैं ।    ० हल्दी मिला दूध फैटी लिवर की समस्या में आराम दिलाता हैं ।    ० हल्दी मिला दूध पीने से टाइफाइड़ की बीमारी बहुत जल्दी समाप्त हो जाती हैं । इसके लिए एक गिलास गुनगुने दूध में एक चम्मच हल्दी मिलाकर रात को सोने से तीन घंटें पहले पीना चाहिए ।](https://www.healthylifestylehome.com/2021/01/blog-post.html) **Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by nainardev** [comment]
spam
