### ISSUE TITLE
Enable sharing of results via url

### ISSUE THREAD

**Issue by TimvdLippe** [GoogleChrome/web.dev#447]
Per my friends feedback, he wanted to be able to share the result of the measure page for a particular website. E.g. web.dev/measure?website=https://google.com should automatically fill in the URL in the input field and run the audit.

**Comment by ebidel** [comment]
What happens if we dont know about the site yet? I don't think this should kick off a new LH run.

**Comment by robdodson** [comment]
How is pulling the url from the query string and putting it in the audit field and clicking Run different from the user typing in the url and clicking Run? Any reason not to run the audit if it's not already in the system?

**Comment by schoenwaldnils** [comment]
I would absolutely love the possibility to just add the url to the url.
I currently have a pagespeed insight test on my pull requests. Those are using the psi-api v5
Example: https://github.com/schoenwaldnils/blog/pull/335
But I currently just can link to the pagespeed insight page like this:
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fschoen.world%2F

I'd like to have the more detailed report like this:
https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://schoen.world/
