### ISSUE TITLE
sharedPreferences

### ISSUE THREAD

**Issue by cheveronllcltd** [GoogleChrome/web.dev#4475]
sharedPreferences
        .edit()  // create an Editor
        .putBoolean("key", value)
        .apply() // write to disk asynchronously

__Originally posted by @cheveronllcltd in https://github.com/GoogleChrome/web.dev/pull/2479#issuecomment-762682712__

**Comment by robdodson** [comment]
sorry i'm not sure what this issue is saying. Going to close but happy to reopen if you can provide more description.
