### ISSUE TITLE
content: (GUI challenge) tabs [2021-02-17]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#4486]
* [draft](https://docs.google.com/document/d/1_PiDA6s-kAeCboYnOr7jJkH1YjosyiDXsB_HImk42T8/edit#heading=h.kuz66phghnyu)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/13wHKrRtsNU)

**Comment by argyleink** [comment]
draft ready for review 👍🏻

**Comment by argyleink** [comment]
publish date for the video is 2/17/21
