### ISSUE TITLE
content: sidenav anchor should have role=button

### ISSUE THREAD

**Issue by Malvoz** [GoogleChrome/web.dev#4509]
### What page(s) need to be updated?

https://web.dev/building-a-sidenav-component/

### Why is this update needed?

The nav "button" should be conveyed as a button, using [`role="button"`](https://www.w3.org/TR/wai-aria-1.1/#button).

As a sidenote, I'm not able to "view the glitch in action", perhaps just a temporary issue with Glitch?

cc @argyleink

**Comment by argyleink** [comment]
I'm open to adding this role, but I'm curious what does adding the button role to the link does that it's not already getting right now? I don't want to add it just to add it, as most accessibility suggestions opt for less metadata than more. Clicking the element does link behavior, not button behavior in this case, so why would it need a button role?

**Comment by Malvoz** [comment]
I suppose you're right, if clicking `<a>`  adds to history I'd say it's more of link behavior than button.

**Comment by argyleink** [comment]
I appreciate you thinking deeply and sharing thoughts! This stuff needs that kind of attention and TLC, glad you're head space is considering it all ❤️

**Comment by Malvoz** [comment]
Although... one could argue that such a control should not have link behavior. Anyhow, I hope the demo will be available for testing/play around with soon! 😋
