### ISSUE TITLE
Turn off the Measure categories user don't care about

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/web.dev#451]
Based on initial user feedback, it would be good to be able to turn off the categories user don't care about (similar to what's available in Lighthouse DevTools today). And then getting as fine grained as turning off the individual tests they don't care about.

Moving to an internal tracking tool

**Comment by robdodson** [comment]
![image](https://user-images.githubusercontent.com/1066253/61106667-b3995000-a432-11e9-8999-964508929822.png)

These are the settings that Lighthouse currently offers inside of DevTools that we should think about replicating on web.dev/measure. I think we won't need the `Clear storage` checkbox.
