### ISSUE TITLE
content: scroll survey announcement [2021-02-05]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#4515]
* [draft](https://docs.google.com/document/d/1sPFzK4OJtTm_1uF6FeYhiVESqjNVtPrQ1nOtwUVhmSU)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/1SKh19HJ5Cc)

**Comment by argyleink** [comment]
thanks! working on a draft with others, will share when ready 👍🏻

**Comment by argyleink** [comment]
draft link added. very short post, ready for review

**Comment by argyleink** [comment]
not dead 🧟 , going through final phases
