### ISSUE TITLE
Lighthouse returned error: FAILED_DOCUMENT_REQUEST

### ISSUE THREAD

**Issue by adriangana** [GoogleChrome/web.dev#4538]
Tried it on my website https://dramarun.com/ it's having error like this Error: Error: Lighthouse returned error: FAILED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_FAILED)

**Comment by robdodson** [comment]
Hi @adriangana 

I was able to get it to complete. Sometimes it will throw that error if it takes an especially long time to load the page.

![image](https://user-images.githubusercontent.com/1066253/106675695-688de300-656a-11eb-9c38-d31c96880335.png)
