### ISSUE TITLE
multi-line code snippets are rendered as one line

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/web.dev#4555]
![image](https://user-images.githubusercontent.com/4071474/106321211-93f69200-6239-11eb-84bb-c2432566d308.png)

https://web.dev/trusted-types/#rewrite-the-offending-code

**Comment by robdodson** [comment]
huh weird, it looks like this for me

![image](https://user-images.githubusercontent.com/1066253/106337392-e63db000-6245-11eb-80c4-c04aa6eff46d.png)

are you still seeing the issue? maybe someone shipped a quick fix PR

**Comment by connorjclark** [comment]
Surprisingly, when I disable the axe extension, there is no issue. For some reason `code` element no longer has `<br>` elements when axe is enabled ...
