### ISSUE TITLE
Feedback on "trusted types"

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/web.dev#4557]
https://web.dev/trusted-types/

I found the purpose and usage of TT to be unclear from reading the article. some observations:

* "How to use the api", or even what the api is, is very unclear until "Create a Trusted Type policy" section, near the end of the article. I didn't realize that TT allows you to define a "safe" function that spits out a string until the end of the article, which required me to re-read the article from the beginning.
* It seems the biggest thing about this api is that it reduces the _scope_ of where XSS can occur, and allows security reviewers to simply focus on where how TTs are used. source: https://github.com/w3c/webappsec-trusted-types/blob/master/explainer.md . However, the first paragraph of this article suggests that TT completely fixes XSS. I'm not sure "secure by default" is the right way to frame this API, it seems more like "reduces surface area of XSS bugs" is closer?

**Comment by paulirish** [comment]
cc @koto

**Comment by connorjclark** [comment]
no

**Comment by connorjclark** [comment]
.
