### ISSUE TITLE
Reporting API soon to be enabled by default (M89, March)

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/web.dev#4573]
Means the details about origin trials in https://web.dev/coop-coep/#observe-issues-using-the-reporting-api should be removed at that point.

**Comment by robdodson** [comment]
@agektmr would you be the right person to do these updates?

**Comment by agektmr** [comment]
Yes. This work is on my radar. Thanks for creating an issue.

**Comment by agektmr** [comment]
I'll work on it.

**Comment by agektmr** [comment]
Addressed in #4813
