### ISSUE TITLE
Make embedded glitches resizeable

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#459]
If a glitch is embedded in a guide, it would be great if you could easily resize it by dragging on it.

**Comment by caraya** [comment]
I've taken a look at the embeds and doesn't seem to be a way to add the resize handle programmatically. I've asked in the Glitch forums and will post any reply in this thread.

**Comment by robdodson** [comment]
Thanks @caraya. I think this may be something we'd need to implement on our end using some custom JS.

**Comment by caraya** [comment]
I will see what I can do

**Comment by robdodson** [comment]
I'm going to close this because it's pretty low priority and no one has asked for this functionality.
