### ISSUE TITLE
update iframe-lazy-loading with status of internal youtube ticket

### ISSUE THREAD

**Issue by janosh** [GoogleChrome/web.dev#4596]
### What page(s) need to be updated?

https://web.dev/iframe-lazy-loading ([MD file](https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/blog/iframe-lazy-loading/index.md))

### Why is this update needed?

Out of curiosity and as a follow up. The post says:

> Anecdote: when we switched to lazy-loading YouTube embeds for Chrome.com, we saved 10 seconds off of how soon our pages could be interactive on mobile devices. I have opened an internal bug with YouTube to discuss adding loading=lazy to its embed code.

What happened to that internal ticket? Any progress on YouTube's side?

**Comment by janosh** [comment]
Not stale.

**Comment by kaycebasques** [comment]
@addyosmani what's the status of the YouTube work?

**Comment by janosh** [comment]
Still not stale

**Comment by addyosmani** [comment]
The status of our internal ticket has not changed, I'm afraid. We will be continuing to discuss this change with YouTube over the next few months and will be sure to update the article when sufficient progress has been made.

**Comment by hcharnell7** [comment]
> ### What page(s) need to be updated?
> https://web.dev/iframe-lazy-loading ([MD file](https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/blog/iframe-lazy-loading/index.md))
> 
> ### Why is this update needed?
> Out of curiosity and as a follow up. The post says:
> 
> > Anecdote: when we switched to lazy-loading YouTube embeds for Chrome.com, we saved 10 seconds off of how soon our pages could be interactive on mobile devices. I have opened an internal bug with YouTube to discuss adding loading=lazy to its embed code.
> 
> What happened to that internal ticket? Any progress on YouTube's side?

Not really. Possibly needs a constant bot to remove bugs.
