### ISSUE TITLE
content: How Wix Improved Websites Performance by Evolving Their Infrastructure [2021-02-05]

### ISSUE THREAD

**Issue by alonkochba** [GoogleChrome/web.dev#4598]
[draft](https://docs.google.com/document/d/10rNsEFGNopmysKJKivfZsVwZzCeh7rw0fb5qK9htSR8/edit#)

#### Provide a brief title for your content proposal

How Wix Improved Websites Performance by Evolving Their Infrastructure

#### Provide a brief summary of your content proposal

This is the tale of some major changes we introduced at Wix over the years to improve site loading performance through leveraging industry standards, cloud providers, and CDN capabilities.
Performance remains a very important focus for us across the company, and many improvements are still being worked on and are gradually being rolled out to users.

Many of these solutions and best standards can and should be applied to any website in general.

#### What content already exists on this topic?

None, but some of the topics are discussed in content such as https://web.dev/content-delivery-networks/

#### Who will be authoring the content?

https://github.com/alonkochba

#### Are there any stakeholders who should be informed when this content changes?

https://github.com/alonkochba

#### What area is your content related to?

Performance

#### What kind of content are you creating?

Case Study / Blog Post

**Comment by alonkochba** [comment]
ready for review, thanks.. I have all files and images ready but not creating a PR yet.

**Comment by kaycebasques** [comment]
Hello! Sorry for the delay. I don't get many proposals here and didn't think to check. I'll review tomorrow.

**Comment by alonkochba** [comment]
thanks @kaycebasques, let me know if you want me to open a pull request, it's easier to read with all the images and comment there
