### ISSUE TITLE
Add author bio

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#460]
Here's the design from our mocks. This should go on the guide pages.

![image](https://user-images.githubusercontent.com/1066253/48575060-ca000380-e8c5-11e8-938e-f54ca456d4db.png)

**Comment by robdodson** [comment]
@TimvdLippe maybe this would be a good next thing to work on?

**Comment by TimvdLippe** [comment]
Yes, will do!

**Comment by robdodson** [comment]
This is fixed and live. Great work @TimvdLippe!!!
