### ISSUE TITLE
Using Javascript window.open, I am not able to open the new window in chrome Mac. 

### ISSUE THREAD

**Issue by Chandru22714** [GoogleChrome/web.dev#4629]
Using Javascript window.open, I am not able to open the new window in chrome Mac.  Instead it is opening in new tab, I have changed the settings also in browser by allowing the popups and redirects. Still the issue exists in chrome MAC.

I have used the below code to open the new window in both MAC and windows chrome.

`window.open("https://www.google.com", "_blank", "width=200,height=200");`

But it is failed to work in chrome MAC. Below is the screenshot of trying out the code in console,

![Capture](https://user-images.githubusercontent.com/15182262/107476701-621bee80-6b9c-11eb-9314-0ebf2479f42b.PNG)

**Comment by robdodson** [comment]
@Chandru22714 this repo is only for the docs that appear on web.dev. If you're having an issue with Chrome you can file a bug at crbug.com
