### ISSUE TITLE
INTL: Move language switch to top 

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/web.dev#4641]
Given no direct url language access to users, make the language switch more discoverable (e.g. move to top). We might consider search bar redesign.

**Comment by robdodson** [comment]
Reassigning to myself till we refactor the header a bit better.

**Comment by hcharnell7** [comment]
Thanks ☺️

**Comment by devnook** [comment]
@robdodson should we close in favor of https://github.com/GoogleChrome/web.dev/pull/6259 ?

**Comment by robdodson** [comment]
oh I didn't know that widget had been added. I guess it's up to you and Sam if you prefer that approach?
