### ISSUE TITLE
Feature Request: 'Supported on' widget

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#4645]
**Is your feature request related to a problem? Please describe.**
Some APIs have weird or complex support widgets, for example the [`getInstalledRelatedApps()`](https://web.dev/get-installed-related-apps/) API can test for different app types, on different platforms, in different browsers.

**Describe the solution you'd like**
Some kind of manually populated widget that we can include to indicate what is supported and what isn't.

**Describe alternatives you've considered**
While it'd be awesome if it pulled data from the MDN compat tables, some APIs like `getInstalledRelatedApps()` have support matrices that won't be available in that data, so having something manual would be nice.

**Additional context**
This came up when I used the `{% Compare %}` widget in a slightly different way than designed. See https://github.com/GoogleChrome/web.dev/pull/4626

**Comment by agektmr** [comment]
This is a great idea! I'd love to have this as well.
