### ISSUE TITLE
Website not loading at all

### ISSUE THREAD

**Issue by marksamfd** [GoogleChrome/web.dev#4670]
**Describe the bug**

**To Reproduce**
1. Launching the website from pwa icon or chrome

**Expected behavior**
Get too long to response

**Screenshots**
![Screenshot_2021-02-14-10-28-24-03_820b80da67ca34a12f493dfc8307f092.jpg](https://user-images.githubusercontent.com/62911833/107871989-63f0f500-6eaf-11eb-9947-2263441896b8.jpg)

**Comment by samthor** [comment]
@marksamfd we're not sure that this will fix your problem, but please try loading up the site in a couple of hours (after our next deploy).

**Comment by robdodson** [comment]
Hey @marksamfd which browser did you use to install the pwa?

**Comment by marksamfd** [comment]
> @marksamfd we're not sure that this will fix your problem, but please try loading up the site in a couple of hours (after our next deploy).

Ok its now working well but I I have uninstalled the pwa and now I don't see the install banner
