### ISSUE TITLE
Web vitals isn't updating even my website results is 100/100 but pagespeed still showing 

### ISSUE THREAD

**Issue by Shahzad-raza** [GoogleChrome/web.dev#4676]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

Field DataOver the previous 28-day collection period, field data shows that this page does not pass the Core Web Vitals assessment.

**Comment by robdodson** [comment]
@Shahzad-raza I'm not sure I understand the question but I think PageSpeed Insights collects data from real users running Chrome and it will lag behind any recent changes you have made to your site.
