### ISSUE TITLE
Default to HTTPS for /measure tests

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/web.dev#468]
The URL field has a placeholder of `https://` but if you enter just the domain of a website, it defaults to HTTP. The placeholder is a bit misleading, especially because the Lighthouse test may fail entirely if the site is unavailable on HTTP.

Proposal: change the default protocol to HTTPS if omitted from the URL.

**Comment by ebidel** [comment]
Should we close? We decided to default to http:// b/c some sites don't have https://.

**Comment by robdodson** [comment]
Yeah I sent in a CL to update the text to use what PSI uses:

```
Enter a web page URL
```

**Comment by rviscomi** [comment]
SGTM. I do think http-only sites are in the overwhelming minority ([~20%](https://httparchive.org/reports/state-of-the-web#pctHttps)) but I understand the reasoning.

**Comment by samthor** [comment]
@robdodson we had this request again and it might be worth revisiting the reasoning.
