### ISSUE TITLE
Pages with `noindex` are being added to the sitemap and Search Console complains

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#4684]
I got an email from Search Console noting some errors in our sitemap. It looks like pages in the handbook are being included even though they have `noindex` set. I bet this would be an easy enough fix.

![image](https://user-images.githubusercontent.com/1066253/108143983-918b9900-707d-11eb-9c11-e9abdc97c073.png)

**Comment by MichaelSolati** [comment]
@robdodson this doesn't look right...The urls it's referencing don't exist. Doing some digging it looks like all the sandbox pages were deleted with PR #4839 (which landed on March 10th). It seems this issue on Search Console was resolved March 12th... I'm guessing these two things are related.. Sooo, yay, I fixed it? (I'm closing this issue for now)

![image](https://user-images.githubusercontent.com/11811422/113916034-5875c800-9794-11eb-81a1-236f641bacec.png)
