### ISSUE TITLE
Allow anchoring "Details" sections

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#4685]
**Is your feature request related to a problem? Please describe.**

When authoring a content, I frequently want to link to a section where it describes fairly detailed matters yet people can skip. Spinning that out to another article is too much and more likely to be ignored, but it's too long to embed in the same article as is. That's where "Details" directive is convenient to use.

However, because there is no way to create a fragment on "Details" directive, it's frustrating that I can't link to the section.

**Describe the solution you'd like**

A way to add a fragment to "Details" section

**Describe alternatives you've considered**

Generic syntax to add a fragment to random places

cc: @maudnals

**Comment by agektmr** [comment]
This will be a blocker for one of new articles I'm currently drafting.

**Comment by robdodson** [comment]
@agektmr could you do something like this?

```njk
<a href="#my-id">More details</a>
...

<span id="my-id"></span>
{% Details %}
...
{% endDetails %}
```

**Comment by agektmr** [comment]
The suggestion does seem to work. Thanks!
