### ISSUE TITLE
iOS Safari zooming in on input field causes search bar to close automatically

### ISSUE THREAD

**Issue by limhenry** [GoogleChrome/web.dev#4687]
**Describe the bug**
iOS Safari zooming in on input field causes search bar to close automatically

**To Reproduce**
1. Open web.dev on iOS Safari
2. (Safari) Set page zoom to 85%
3. Click on the "Search" icon on the header
4. Safari will zoom in on the input field, and causes the search bar to close automatically

**Expected behavior**
The search bar should not close automatically on this case

**Screenshots**

https://user-images.githubusercontent.com/4544770/108233043-f7f3e280-7175-11eb-9a5f-b75daa90dfa4.MP4

https://user-images.githubusercontent.com/4544770/108233267-2ec9f880-7176-11eb-8974-b338fe1488dd.mov

**Possible Causes**
`src/lib/components/Search/index.js` (Line 460): [Link](https://github.com/GoogleChrome/web.dev/blob/77e3204458aece94cfbb3b23958189cca3187381/src/lib/components/Search/index.js#L460)
```
// Collapse the search box if the user scrolls while the seach box is
// focused.
window.addEventListener(
  'scroll',
  () => {
    /** @type HTMLElement */ (document.activeElement).blur();
  },
  {passive: true, once: true},
);
```
When Safari zoom in on the input field, it will scroll the page up/down a little, hence the "scroll" listener will causes the search box to close/collapse automatically.

---

_Small unrelated note: There's a typo on the code: `while the seach box is` -> `while the search box is`_

**Comment by limhenry** [comment]
One possible solution is to wait for few milliseconds before adding the "scroll" listener:

```
this.searchTimeout = setTimeout(() => {
  // Collapse the search box if the user scrolls while the seach box is
  // focused.
  window.addEventListener(
    'scroll',
    () => {
      /** @type HTMLElement */ (document.activeElement).blur();
    },
    {passive: true, once: true},
  );
}, 200);

// Remember to call `clearTimeout(this.searchTimeout)` on `onFocusOut()`
```

**Comment by limhenry** [comment]
Or another possible solution is to add `user-scalable=no` to the viewport meta tag (`src/site/_includes/layout.njk`), but this will fail the Lighthouse audit.

**Comment by robdodson** [comment]
Could this be the fix? https://twitter.com/JoshWComeau/status/1379782931116351490?s=19
