### ISSUE TITLE
content: "Link preload" in "Fast playback with audio and video preload" is wrong

### ISSUE THREAD

**Issue by aendrew** [GoogleChrome/web.dev#4699]
### What page(s) need to be updated?

https://web.dev/fast-playback-with-preload/#link_preload

### Why is this update needed?

The "link preload" option doesn't seem to work in any browser. See [me complaining on Twitter here](https://twitter.com/aendrew/status/1362410912548859906) and [MDN article here](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#what_types_of_content_can_be_preloaded):

> Note: video preloading is included in the Preload spec, but is not currently implemented by browsers.

Annoyingly, [this doesn't seem to be indicated by caniuse's support tables for preload](https://caniuse.com/link-rel-preload).

**Comment by aendrew** [comment]
Any update on this? Somebody I know seemingly ran into this independently last night. This seems like an error in documention that is actively misleading people.

**Comment by vaaski** [comment]
I too just ran into this.
Considering how high this article ranks in Google searches, there should definitely be a disclaimer to inform that `as="video"` isn't actually usable today.

**Comment by aendrew** [comment]
Urgh, stupid Stalebot; please reopen! The problem still exists!
