### ISSUE TITLE
Content pages are missing their meta description

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#470]
For example https://web.dev/fast/discover-performance-opportunities-with-lighthouse does not appear to have a description field so it doesn't have a descriptor in social sharing cards:

![image](https://user-images.githubusercontent.com/1066253/48649889-fe002500-e9a8-11e8-8316-fc201be2697d.png)

**Comment by robdodson** [comment]
This was enabled in https://github.com/GoogleChrome/web.dev/pull/485, but all content pages now need to have a description YAML field created.

**Comment by TimvdLippe** [comment]
This was fixed in #494

**Comment by robdodson** [comment]
Good catch, thanks Tim!
