### ISSUE TITLE
Footer message is non-padded after signing in

### ISSUE THREAD

**Issue by TimvdLippe** [GoogleChrome/web.dev#473]
On web.dev, if the user is not signed in, the `Except as otherwise noted` message has the correct padding. However, after signing in, the padding is removed.

**Comment by TimvdLippe** [comment]
For some reason, after signing in, there is a `<div class="container">` missing after the main content (which should wrap the footer). Is this a devsite issue instead?

**Comment by robdodson** [comment]
i think we add that container element but we could remove it and maybe just style the footer thing directly.

**Comment by robdodson** [comment]
It looks like this doesn't specifically have to do with sign-in. You can always trigger it by doing a hard (cmd-shift-r) refresh of the page.

**Comment by robdodson** [comment]
Should be fixed by cl/222415952
