### ISSUE TITLE
content: Security headers cheat sheet [2021-03-05]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#4733]
* [Draft](https://docs.google.com/document/d/11Yc0DQ-D190cCQIeUBMF3w5b_Kds68EceC12huCB9B8/edit#)
* [Discussion](https://groups.google.com/a/google.com/g/chrome-devrel-content/c/t5-RAFL7dfg)

**Comment by agektmr** [comment]
This article has been postponed but not stale yet.

**Comment by agektmr** [comment]
This article is not stale, but published here: https://web.dev/security-headers/
For posterity.
