### ISSUE TITLE
content: Facade warning 

### ISSUE THREAD

**Issue by benschwarz** [GoogleChrome/web.dev#4739]
There's an tiny inaccuracy in the third party facades page that I'd like to clarify

It warns:  

> There are some tradeoffs when lazily loading third-parties with facades as they do not have the full range of functionality of the actual embeds. For example, the Drift Live Chat bubble has a badge indicating the number of new messages. If the live chat bubble is deferred with a facade, users will not see the badge until after first interaction. For video embeds, autoplay may not work consistently if it's loaded lazily.

However, this is not quite the case. The "real" chat widget will be loaded when the page fires `requestIdleCallback` or `idlePeriod` is reached (not after first interaction).

It means that users will see the chat widget button immediately, then sometime later when the real widget is replaced, the message/notifications will appear at that time. 

Links:

* [react-live-chat-loader configuration options](https://github.com/calibreapp/react-live-chat-loader#options) 

cc @mihajlija

**Comment by mihajlija** [comment]
Paging @adamraine for input on this

**Comment by adamraine** [comment]
Thanks for pointing this out @benschwarz!

Do you think this makes more sense?

> users will not see the badge until after first interaction.

change to
> users will not see the badge until an idle period is reached, when the actual chat widget loads in.

**Comment by benschwarz** [comment]
@adamraine That's a good improvement, though I'd say it'd be more detailed to mention `requestIdleCallback` 🤔 

What do you think about: 

> the actual chat widget will be loaded after the browser fires `requestIdleCallback`.

Mentioning the library config option (`idlePeriod`) is a little too much. Folks can reference the official documentation for that.
