### ISSUE TITLE
Put contributing guides on web.dev

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#476]
For initial launch we'll have guides on how to build content on web.dev in our GitHub wiki, but eventually it would be nice to have these on web.dev so we can show examples of all of the components.

Similar to what webfu does today: https://developers.google.com/web/resources/

**Comment by ymschaap** [comment]
Also:
- is there a list of possible topics?

**Comment by robdodson** [comment]
The contributing guides are (roughly) here: https://github.com/GoogleChrome/web.dev/wiki

I don't think we have a list of topics but definitely open to proposals. Right now all written guides have to fall under one of [the 6 main topic areas on the site](https://web.dev/learn) but I'm working on a new design to make it accommodate any topic.

We also have a Medium publication over at https://medium.com/dev-channel. If you're interested in writing a post on Medium we can syndicate it through that publication I think.
