### ISSUE TITLE
Tables show a subtle right border on Chrome

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#4765]
@tomayac I think this is related to the table overflow gradient you worked on. I _think_ it might be a Chrome bug, but I'm not sure (it doesn't reproduce in Firefox, at least). If you go to web.dev/handbook/web-dev-components/#tables and try resizing the screen you should see the 1px black border flicker.

https://user-images.githubusercontent.com/1066253/109369926-4169bf00-7853-11eb-951a-60ed73e9863b.mp4

**Comment by tomayac** [comment]
This is very likely a Chrome issue. Filed https://crbug.com/1183367 to track this. Closing this present Issue.
