### ISSUE TITLE
Selectors [Learn CSS]

### ISSUE THREAD

**Issue by andy-piccalilli** [GoogleChrome/web.dev#4778]
- [Draft](https://docs.google.com/document/d/16XFX3meESsapFYqFAake13ZOPlShR08dCSAml-uC94E/edit)
- [PR](https://github.com/GoogleChrome/web.dev/pull/4983)
- [Preview](https://deploy-preview-4983--web-dev-staging.netlify.app/learn/css/selectors/)

## To do

- [ ] Add a self assessment? There isn't one mentioned in the draft. If no check this as done.
- [ ] Una to review
- [x] Adam to review

**Comment by rachelandrew** [comment]
@hankchizljaw I've done an initial pass on this one for structural comments.

**Comment by rachelandrew** [comment]
@hankchizljaw does this one not have a self-assessment?

**Comment by hankchizljaw** [comment]
Not yet, but we'll get some in there in that last pass before we go live
