### ISSUE TITLE
View Report error with Hebrew characters

### ISSUE THREAD

**Issue by nirpetrank** [GoogleChrome/web.dev#480]
I Run LH on https://www.ichsunbatuach.co.il/%D7%90%D7%97%D7%A1%D7%95%D7%9F-%D7%93%D7%99%D7%A8%D7%94/

I get results, but when I click on View Report I get an error-
{"errors":"No results found for \"https://www.ichsunbatuach.co.il/אחסון-דירה/\"."}

What is the expected behavior?
Report with all the issues on the page.

Can you fix this?

Thank in advance
Nir Petrank

**Comment by ebidel** [comment]
This should be fixed now.

https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://www.ichsunbatuach.co.il/%D7%90%D7%97%D7%A1%D7%95%D7%9F-%D7%93%D7%99%D7%A8%D7%94/
