### ISSUE TITLE
Share/subscribe CTAs icons don't load in subfolder

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/web.dev#4807]
On a page [like this](https://web.dev/handbook/web-dev-components), the CTA buttons look like:

<img width="315" alt="Screen Shot 2021-03-04 at 15 24 43" src="https://user-images.githubusercontent.com/119184/109911226-c7778100-7cfd-11eb-8f6f-95bfd5a79353.png">

The URLs are relative to the current page URL, which seems to assume a single-level. Granted, this is just the handbook page, but we might have more of these around in future.

**Comment by chait04** [comment]
so the issue is icons are not loading right... 
like this
![Screenshot (112)](https://user-images.githubusercontent.com/59140343/109923670-1bc23700-7ce5-11eb-8aef-17bb5a014d35.png)

**Comment by YashKumarVerma** [comment]
> so the issue is icons are not loading right...
> like this
> ![Screenshot (112)](https://user-images.githubusercontent.com/59140343/109923670-1bc23700-7ce5-11eb-8aef-17bb5a014d35.png)

from what I can understand this is because of the links being relative as said in the issue body.
![image](https://user-images.githubusercontent.com/14032427/109932579-64332200-7cf0-11eb-8f64-adf16e6079df.png)

**Comment by adzo261** [comment]
Hi. Can I do this one?

**Comment by robdodson** [comment]
@adzo261 sure :)
