### ISSUE TITLE
some pages do not have descriptive titles

### ISSUE THREAD

**Issue by myakura** [GoogleChrome/web.dev#4815]
**Describe the bug**
quite a few pages have just "web.dev" in the title.

looks like those are contents under https://github.com/GoogleChrome/web.dev/tree/main/src/site/_data/paths

**To Reproduce**
1. Go to https://web.dev/metrics/
2. Look at the title

**Expected behavior**
It should show something like "Metrics - web.dev"

**Comment by robdodson** [comment]
I think Ewa's PR in #4831 will fix this
