### ISSUE TITLE
content: Display_override should mention "window-controls-overlay" instead of "window-control-overlay"

### ISSUE THREAD

**Issue by amandabaker** [GoogleChrome/web.dev#4818]
### What page(s) need to be updated?
`display_override` doc: https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/blog/display-override/index.md

### Why is this update needed?
The doc refers to `"window-control-overlay"` (singular "control") instead of `"window-controls-overlay"` (plural "controls").
See implementation: https://source.chromium.org/search?q=window-controls-overlay
See explainer: https://github.com/WICG/window-controls-overlay/blob/master/explainer.md#proposal

**Comment by tomayac** [comment]
Thanks, fixing in #4827. Luckily I got it right in https://github.com/GoogleChrome/web.dev/pull/4680 😃.
