### ISSUE TITLE
What are the differences between WebHID and Web Serial API？

### ISSUE THREAD

**Issue by kiwenlau** [GoogleChrome/web.dev#4824]
It seems that both WebHID and Web Serial API are used for communicating with hardware. 

- What are the differences between WebHID and Web Serial API？
- When we should use WebHID or Web Serial API？
- Are their usage scenarios exclusive or inclusive?

**Comment by robdodson** [comment]
@beaufortfrancois can you answer this?

**Comment by beaufortfrancois** [comment]
Sorry for the delay @kiwenlau, hopefully https://web.dev/devices-introduction/ will give you some hints.
@reillyeon may have more to say though.

**Comment by reillyeon** [comment]
> What are the differences between WebHID and Web Serial API？

The difference between the Web Serial API and the WebHID API is that one allows you to use devices that are available through the operating system's serial API and the other through the operating system's HID API.

> When we should use WebHID or Web Serial API？

If you are trying to communicate with a particular device then it is probably available through only one of these options (or maybe it is a generic USB device, in which case WebUSB is the right option).

If you are designing your own device then you get to choose how it presents itself to the operating system and so you can choose which API you will have to use. In that case the decision should be based on whether the properties of serial, HID or raw USB communication fit your use case better.

> Are their usage scenarios exclusive or inclusive?

Right now the APIs operate independently. That means that if you are communicating with a physical device that provides serial and HID interfaces you will have to request permission to use the device through each API independently. This is an area where we have considered API and UX changes to make it easier to deal with such hybrid devices.

**Comment by kaycebasques** [comment]
@kiwenlau please let us know if https://web.dev/devices-introduction/ answers your question. Gonna close this for now but we can re-open if needed.
