### ISSUE TITLE
content-visibility and accessibility

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web.dev#4825]
**Is your feature request related to a problem? Please describe.**
Our current content for https://web.dev/content-visibility/ is fantastic, but it has been noted that our guidance for using it with accessibility in mind could be stronger.

**Describe the solution you'd like**
Perhaps we could add a section on accessibility where we go into more detail on how we think developers should balance usage of the `content-visibility` property and impact it can have on screen-readers? 

Marcy Sutton's [blog post](https://marcysutton.com/content-visibility-accessible-semantics) touches on this subject and is also something we could link up to for further reading.

`I recommend keeping headings and landmark elements outside of regions styled with content-visibility: auto.`

**Additional context**
There was some discussion generated regarding the trade-offs (perf, accessibility) in the threads on https://twitter.com/addyosmani/status/1368479029683122180.

@una wdyt?

**Comment by chrishtr** [comment]
@vmpstr FYI

**Comment by una** [comment]
Hi Addy, thanks for raising this. This should be resolved in M90, https://bugs.chromium.org/p/chromium/issues/detail?id=1168771

I'll update the article with a note around this
