### ISSUE TITLE
content: [Case Study] - Business Impact of LCP improvements for RebelMouse properties

### ISSUE THREAD

**Issue by charset-and-forget** [GoogleChrome/web.dev#4853]
Google Doc Link: https://docs.google.com/document/d/1FVXio6TODTJd7D0HV3kti1fXl0WNvOozcmsA--LNOjk/edit?usp=sharing

### Content proposal form for contributors who don't have access to Googlers

Fill out this section ONLY if you want to contribute new content to web.dev but don't have access to
Googlers.

#### Provide a brief title for your content proposal
Web Vitals Case Study: The Impact of Better LCP on RebelMouse
#### Provide a brief summary of your content proposal
Platform-level improvements to the RebelMouse platform in 2020 led to major improvements in LCP for properties powered by RebelMouse. By looking at the actual business impact of these improvements year over year for several publishers, we were able to identify the potential business impact of such improvements to LCP.
Please explain how this content will help me be a better web developer.
A web developer considering the value of improving LCP or trying to justify the importance of LCP improvements will find the results very useful.
#### What content already exists on this topic?
The inspiration for this article was a lack of real world data on the business impact that publishers see when improving LCP scores. There are many articles about what LCP is, or how to improve it (some of which we link to in this article), but finding real examples/case studies are hard to find.

#### Who will be authoring the content?

@charset-and-forget

#### Are there any stakeholders who should be informed when this content changes?

@andreylipattsev

#### What area is your content related to?

Performance

#### What kind of content are you creating?

Case Study

**Comment by kaycebasques** [comment]
Thank you for the proposal! I'll kick off an email now for us to discuss.

**Comment by charset-and-forget** [comment]
@kaycebasques thanks so much! 

I assume you mean an internal email at Google, but if you plan on looping me in, please use charlie `at` rebelmouse `dot` com.
