### ISSUE TITLE
Doesn't wait for Node.JS Website Servers from Repl.it to "Wake Up"

### ISSUE THREAD

**Issue by DREWNOLT** [GoogleChrome/web.dev#4867]
**web.dev doesn't wait for Node.js Web Servers from [Repl.it](https://repl.it)**
When going to /measure and typing in one of my node.js Server Websites that hadn't (as repl.it calls it) "Woken Up" yet, so I didn't get the right stats, and an Error Message Occurred.
**To Reproduce**
1. Go to [Measure on web.dev](https://web.dev/measure)
2. Enter a repl.it web server without visiting it first(EXAMPLE: https://replcoin.drewnolt.repl.co ) NOTE: you should probably do this around early morning(like around 7:30 AM PST), as the website probably hasn't woken up yet.
3. Run an audit
4. See error and stats.
5. Then, go to the website that you just ran an audit on.
6. Wait for it to wake up and load.
7. Then run another audit on that same website.
8. The stats will look different, as the server has been manually started.

**Comment by robdodson** [comment]
Hi @DREWNOLT this isn't really something we can fix on our end. I believe when your site hasn't "woken up" yet it's essentially not being served so Lighthouse is technically correctly reporting that it's not available.
