### ISSUE TITLE
Align the category icons on Measure

### ISSUE THREAD

**Issue by hwikyounglee** [GoogleChrome/web.dev#487]
LH category icons on https://web.dev/measure are sliced in different sizes and result in misalignment. 
Let's use the same bound box to slice images according to the sketch file. 

Current: 
<img width="1057" alt="icons-current" src="https://user-images.githubusercontent.com/7561395/48993403-4f6b8b00-f0f2-11e8-991b-cec00ae68075.png">

Desired:
<img width="773" alt="icons" src="https://user-images.githubusercontent.com/7561395/48993404-4f6b8b00-f0f2-11e8-98ec-d6e11f65a61f.png">

SVGs:
[icons.zip](https://github.com/GoogleChrome/web.dev/files/2614081/icons.zip)

The following css changes would be needed to readjust spacing as the icons already contain spacings:
```
.profile-landing-page .lh-category__icon {
margin-bottom: 3px;
}
.profile-landing-page .lh-category__title {
margin: 0 8px 16px;
}
```

**Comment by ebidel** [comment]
Getting fixed in cl/222312753. Hopefully they'll push to prod soon :\
