### ISSUE TITLE
A broken link

### ISSUE THREAD

**Issue by AM-77** [GoogleChrome/web.dev#4873]
**Describe the bug**
A broken link that redirect to a 404 page in github

**To Reproduce**
1. Go to https://web.dev/offline-start-url/#resources
2. Click on the link  [Source code for start_url does not respond with a 200 when offline audit](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/offline-start-url.js)

**Comment by lucalves** [comment]
Hello @AM-77, I opened PR #4906 to fix this. Let's wait for the review.

**Comment by mihajlija** [comment]
Fixed #4906
