### ISSUE TITLE
I suggest removing firebase app indexing from my phone lawsuit being started now

### ISSUE THREAD

**Issue by jojosweetne** [GoogleChrome/web.dev#4875]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jojosweetne** [comment]
My phones hacked by firebase app indexing I want new software update I'm suing github

**Comment by robdodson** [comment]
Hi @jojosweetne if you have issues with Firebase please file them at https://firebase.google.com/support
