### ISSUE TITLE
Label for hidden input field gives html validation error

### ISSUE THREAD

**Issue by ivarjohansson** [GoogleChrome/web.dev#4880]
Hi, 

When I run an audit on my website, then I get the warning "Form elements do not have associated labels". 

So I create labels for all the input fiels, and your audit doesn't give me any warnings. 

But with labels for all input fields, [https://validator.w3.org](https://validator.w3.org) displays errors for the hidden input fields that have a label. 

It seems as your audit doesn't look if input fields are visible or hidden. 

How can this bes solved? 

Many thanks in advance, 

Ivar

**Comment by ivarjohansson** [comment]
A clarification: 

The input fields are set to type="hidden".

**Comment by robdodson** [comment]
@ivarjohansson can you post an example of the html that you're using?
