### ISSUE TITLE
Allow sharing report privately

### ISSUE THREAD

**Issue by robins** [GoogleChrome/web.dev#4893]
**A clear and concise description of what the problem is.** 

I have a website report which seems helpful but there's no way to (1) email or make a self-note for myself when I get to a computer... And (2) send this report to the Dev team who may way to review this in more detail.

**Describe alternatives you've considered**
Twitter YouTube are not what I need since the idea isn't to post publically.

**Additional context**
Great tool.. but I don't change websites.. the dev teams do and it'd be great if I could just route this to someone via a Link or just send it to myself via email or something for future reference..

**Comment by robdodson** [comment]
Hey @robins. After you use the measure tool you can click on the **View Report** link to open it in a new window.
![image](https://user-images.githubusercontent.com/1066253/111381271-b5cd9c00-8662-11eb-93ba-9ec2ad33182a.png)

The new window generates a unique url that you can share. I agree it might be nicer to have a share button. We're working on some upcoming changes to measure and I'll add that as a note.
