### ISSUE TITLE
Content proposals are showing up not identified as such and without context

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#4898]
Earlier today @robnyman submitted a content proposal using the internal form. The [issue generated])https://github.com/googlechrome/web.dev/issues/4897) by the chrome-devrel-review-bot did not indicate that it was a proposal or who the author was.

![image](https://user-images.githubusercontent.com/8204171/111167054-f2fc3600-855d-11eb-8425-2f6d03c9df81.png)

To proceed with this, the writing team needs to know who submitted it and what the context is around it. Kayce, the writer who knew what was going on with this has left on vacation. Our new TVC almost picked this up prematurely. Milica may know what's going on, but seems unavailable this morning.

**Comment by robdodson** [comment]
ok, I think the code for the reviewbot lives here: https://github.com/kaycebasques/reviewbot

I went back and looked at the previous issues that the review bot created and they all look like this one. It seems like Kayce was manually assigning reviewers.

**Comment by jpmedley** [comment]
It's the lack of context or links to context that concern me. This was fine when it was just Kayce doing this. It's a tad inconvenient when he's not. We may need to put up with this for the next 3 1/2 weeks, but for business continuity reasons, it would be nice to address this for the long term.

**Comment by robdodson** [comment]
I'm not super familiar with Kayce's process here but I think folks may need to glance at chrome-devrel-content@google.com which is where all of the proposals go. Those contain links to the github issues they create.

**Comment by malchata** [comment]
I updated the app script for the proposal form for an actual piece of content I need to migrate over from WebFundamentals and it generated [this issue](https://github.com/GoogleChrome/web.dev/issues/6307). Thoughts? Good enough? Too much info?

**Comment by jpmedley** [comment]
I got the biggest thing I want: who made the proposal.
Joe Medley | Technical Writer, Chrome DevRel | ***@***.*** |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by malchata** [comment]
@devnook weighed in and let me know that the email should probably be stripped down to the LDAP username. I'll need to tweak the app script and look at the execution details to make sure whatever changes I make to the app script will do that. Once I've got it good to go, I'll mark this issue as resolved and close it.

**Comment by malchata** [comment]
Tested and good to go! Feel free to reopen this issue if anything comes up related to it.
