### ISSUE TITLE
"Background and foreground colors do not have a sufficient contrast ratio." bug

### ISSUE THREAD

**Issue by agamemnus** [GoogleChrome/web.dev#491]
It identified "failing elements" as my share buttons, which have a high contrast (e.g.: white against black, etc.). Probably a problem of the code not being able to figure out the background correctly:
````
<div> <--- background-color set here
 <div> <--- background: inherit tried. Didn't work to fix this issue.
  <div>share</div> <--- the element it complains about.
 <div>
</div>
````

**Comment by TimvdLippe** [comment]
This issue was moved to GoogleChrome/lighthouse#6682
