### ISSUE TITLE
content: "Create an offline fallback page" declares OFFLINE_VERSION variable but never uses it

### ISSUE THREAD

**Issue by elisee** [GoogleChrome/web.dev#4912]
### What page(s) need to be updated?

https://web.dev/offline-fallback-page/
https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/progressive-web-apps/offline-fallback-page/index.md

### Why is this update needed?

The `OFFLINE_VERSION` variable is declared but never used. The comment says:

    // Incrementing OFFLINE_VERSION will kick off the install event and force
    // previously cached resources to be updated from the network.
    const OFFLINE_VERSION = 1;

But `OFFLINE_VERSION` is never used so I doubt that would work? Looks like it should be concatenated to the `CACHE_NAME`?

**Comment by elisee** [comment]
Oh, I'm realizing maybe changing the value makes the serviceWorker JS file different and that's what's triggering a new install. If that's it, maybe it could be made more explicit in the comment? something adding something to the effect of "(or in fact, any change to this file)"

**Comment by mihajlija** [comment]
cc @tomayac @petele
