### ISSUE TITLE
Windows 10 Eleventy config error when trying to run the project

### ISSUE THREAD

**Issue by rachelandrew** [GoogleChrome/web.dev#4926]
I am on Windows 10 and trying to run the project. It fails with the following:

```
> Error in your Eleventy config file '/mnt/c/users/rache/local/google/webdev/.eleventy.js'.

`EleventyConfigError` was thrown
> Unexpected token '.'

`SyntaxError` was thrown:
    /mnt/c/users/rache/local/google/webdev/node_modules/webdev-infra/filters/toc.js:76
      const childrenPart = node?.children?.length
                                ^

    SyntaxError: Unexpected token '.'
```

Tried this just on the main branch: e7a43e98c79addae31663b8fbd2fc20b60c04578

node -v on Ubuntu via WSL v12.21.0

**Comment by robdodson** [comment]
@rachelandrew ah sorry for the issue there. You'll need to use node 14+

**Comment by robdodson** [comment]
I'm going to close this issue but happy to reopen if you hit any other snags.

**Comment by rachelandrew** [comment]
@robdodson the readme says 12.10 https://github.com/GoogleChrome/web.dev#building-the-site- so guess we should update that. Usually when I upgrade node everything breaks so I tend to leave it until forced.

**Comment by robdodson** [comment]
oh shoot sorry about that! yes let me send in a quick update.

For upgrading node do you use a tool like [nvm](https://github.com/nvm-sh/nvm)? I've found it can be quite helpful so I can jump between versions. The site has a [`.nvmrc` file](https://github.com/GoogleChrome/web.dev/blob/main/.nvmrc) which you can use to have nvm automatically switch you to the right version.
