### ISSUE TITLE
"Defer offscreen images" detection...

### ISSUE THREAD

**Issue by agamemnus** [GoogleChrome/web.dev#493]
Sometimes it works (great) and sometimes it doesn't (and I get a huge performance score hit).

I don't use lazy loading. Instead, I load the images just a bit after (1000ms), in case the user wants to scroll right away. This might be messing up the detection...

**Comment by TimvdLippe** [comment]
This is (probably) a duplicate of https://github.com/GoogleChrome/lighthouse/issues/6677
