### ISSUE TITLE
Why there are not 'move forward/back' buttons between the articles?

### ISSUE THREAD

**Issue by MenaiAla** [GoogleChrome/web.dev#4940]
**Describe the bug**

When I finish reading the article, I expect to find <code> Next > </code> button for reading the next article.

**To Reproduce**
1. Go to the topic for example:  Accessible to all
2. Click on 'What's accessibility?'
3. Read and scroll down to end of the page.
4. Find feedback section.

**Expected behavior**

Find <code> Next > </code> button for reading the next article.

**Found**

Just the feedback section.

**Comment by robdodson** [comment]
This was removed because articles appear in multiple parts of the site (on the blog as well as in the /learn/ sections). It's less than ideal but I think we have to stick with this decision until we do a bigger design refactor in the future.
