### ISSUE TITLE
Consider using <em> and <strong> more in articles

### ISSUE THREAD

**Issue by simevidas** [GoogleChrome/web.dev#4948]
Example article: https://web.dev/generic-sensor/

Before:

![before](https://user-images.githubusercontent.com/716405/112077534-01a9a500-8b7d-11eb-98a4-cd09170c8706.jpg)

After:

![after](https://user-images.githubusercontent.com/716405/112077541-066e5900-8b7d-11eb-9d5b-683a4da5caa4.jpg)

If you agree that this is an improvement, consider instructing your authors to use `<em>` and `<strong>` to emphasize key words and phrases in their texts and avoid the ”large block of text” problem.

**Comment by jpmedley** [comment]
Thank you for your suggestion. If you're trying to improve the scanability of the list, the solution is a writing one, not a formatting one. Generally, lists like this should have parallel sentence structure. It could look something like this:

* Extensibility with new sensor classes. These new sensor classes…
* Configurability such as, for example, setting the sampling frequency to suit your application.
* Detectability: is the sensor available on the current platform. 
* etc.

This is only an example. Obviously some of these bullets don't easily lend themselves to beginning with an adverb. Fixing this through writing requires some thought. I don't know who edited this originally, so I can only guess at why it wasn't corrected: judgement call, short timeline. Who knows?

In general, the best practice is to achieve emphasis through sentence structure and not formatting. This is true regardless of other considerations. The built-in screen reader on mac doesn't treat this text differently when reading. Extra formatting also tends to make pages look busier.

**Comment by simevidas** [comment]
That’s an interesting perspective. Personally, I feel that large blocks of completely unemphasized text are a problem when trying to convey information effectively, but that could be just me. There are probably user studies on this. 

Please close this issue at your own discretion.
