### ISSUE TITLE
Web.dev site scores differ from DevTools Lighthouse scores

### ISSUE THREAD

**Issue by petedegraw** [GoogleChrome/web.dev#4977]
**Describe the bug**
The scores shown in the Chrome DevTools Lighthouse Panel differ from the posted ranges on web.dev pages.

Example: testing performance via DevTools gave a result of 2.3s (red/slow) but the FCP table on [https://web.dev/first-contentful-paint](https://web.dev/first-contentful-paint/?utm_source=lighthouse&utm_medium=devtools) shows 2-4s as orange/moderate.

**To Reproduce**
1. Go to [https://www.equinix.com/](https://www.equinix.com/) or any website
2. Open DevTools and run a Lighthouse audit
3. Observe a metric such as FCP and the indicator icon/color
4. See the range of scores on [https://web.dev/first-contentful-paint](https://web.dev/first-contentful-paint/?utm_source=lighthouse&utm_medium=devtools)

**Expected behavior**
The scores in the DevTools Lighthouse Panel should reflect the same range of scores as the web.dev site.

**Screenshots**
![devtools-vs-webdev-site](https://user-images.githubusercontent.com/2252478/112659634-f2e81a00-8e2a-11eb-8b9e-05d35d07be88.jpg)

**Comment by robdodson** [comment]
Merging into #4321
