### ISSUE TITLE
The Offline Cookbook: On user interaction section is misleading

### ISSUE THREAD

**Issue by scytacki** [GoogleChrome/web.dev#4978]
**Describe the bug**
The [On user interaction](https://web.dev/offline-cookbook/#on-user-interaction) section of The Offline Cookbook is misleading.  Particularly this last part "...meaning you don't need to involve the service worker to add things to the cache."

While you *can* add things to the cache from the page, those things are still downloaded through the service worker. So the only way to not "..involve the service worker..." is to make sure the service worker does not handle the fetch events for the urls being added to the cache by the page.  In other words the scenario described in that section is more complicated than it is made out to be.

**To Reproduce**
I tested this locally. Unfortunately I do not have an example site where you can verify it yourself. 

This behavior is logical based on how `cache.add` is described here: https://developer.mozilla.org/en-US/docs/Web/API/Cache/add

**Comment by robdodson** [comment]
@jakearchibald wdyt?

**Comment by jakearchibald** [comment]
Yeah, I think it's fair to tweak the wording here. Something like "…meaning you can add to the cache directly from the page."

I'll have a think.
