### ISSUE TITLE
How does Google Chrome parses CSS selectors?

### ISSUE THREAD

**Issue by ianthedev** [GoogleChrome/web.dev#4981]
Years ago, MDN [published an article on how to write efficient CSS selectors](https://web.archive.org/web/20120505043119/https://developer.mozilla.org/en/Writing_Efficient_CSS). That arouses my interest in knowing how Google Chrome parses CSS selectors and optimizing my CSS selectors for Google Chrome. I'm not sure if this is the right place to start such a discussion. If not, kindly suggest a place.

**Comment by robdodson** [comment]
@una @argyleink is this something y'alls CSS course will be covering?

**Comment by argyleink** [comment]
I don't think so no. Not currently a topic type on the docket.

**Comment by kaycebasques** [comment]
This is a relevant place for the discussion but @una and @argyleink would be the ones to cover the content. So if @argyleink says it's not likely they'll cover the topic then I think that I should close this issue. @una & @argyleink maybe you can informally discuss it here or provide pointers on where @ianthedev can learn more?
