### ISSUE TITLE
What is a "long" cache lifetime?

### ISSUE THREAD

**Issue by y-a-v-a** [GoogleChrome/web.dev#5014]
**Is your feature request related to a problem? Please describe.**
The problem is that I do not understand what is considered "long" in "long cache lifetime" with regard to Cache TTL.

**Describe the solution you'd like**
Describe in more detail what Lighthouse or Google considers "long". 60 days apparently isn't, since my assets with a Cache TTL of 60 days are shown in the list...

**Describe alternatives you've considered**
Show a table with what is considered "long", for example on the read more page (uses-long-cache-ttl/index.md)

**Comment by robdodson** [comment]
@y-a-v-a which page did you see mentioning the long cache time? Just want to make sure we update it in the correct place(s)

**Comment by y-a-v-a** [comment]
Ah I eventually found:

> When possible, cache immutable static assets for a long time, such as a year or longer.

Seen on https://web.dev/uses-long-cache-ttl/ and found in https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/lighthouse-performance/uses-long-cache-ttl/index.md

I completely missed it due to the density of info around it, sorry.

But still, the above remark sounds very loose: "such as a year or longer", but don't we have a responsibility as web developers to not clutter consumer's disk space? Why is 60 days not sufficient?

What's the threshold Lighthouse will stop marking these assets? My managers (and manager's managers) want to see Lighthouse improvements, so I'd like to know the threshold.

**Comment by kaycebasques** [comment]
@jeffposnick WDYT?

**Comment by jeffposnick** [comment]
This sounds partly like a product question for Lighthouse—I am not sure why it would warn for 60 days, or what its cutoff is.

Regarding the concern around cluttering a user's disk if a long lifetime is used, the dates are just guidelines around the maximum age that the content should be considered fresh, and not guarantees that the browser will actually keep the content on disk for that long. Each browser has its own heuristics for determining what cached content to clean up, but all of them will prune the HTTP cache to some extent when there is low disk space.

**Comment by y-a-v-a** [comment]
We noticed that Lighthouse maintains a threshold at 100 days so Lighthouse doesn't seem to show the cache life time warning when we configure our servers to add a >100 days value for cache invalidation, so we've set it to 101 days.
