### ISSUE TITLE
JSON response object received on submitting web.dev newsletter subscription form

### ISSUE THREAD

**Issue by sakettawde** [GoogleChrome/web.dev#5015]
**Describe the bug**
When you subscribe to the web.dev newsletter, you are greeted with a json response object which says:
{
result: "accepted"
}

**To Reproduce**
1. Go to web.dev
2. Fill up the form on the bottom of the page
3. Check the checkboxes
4. Click on the 'Subscribe' button to see this behaviour

**Expected behavior**
Probably just a toast, or being redirected to a confirmation screen.

**Screenshots**
A look at the page that I received
![image](https://user-images.githubusercontent.com/14161564/113291056-14a43e00-9310-11eb-8371-6974e3a382d3.png)

**Comment by robdodson** [comment]
@sakettawde can you try again in a few hours and let us know if it's still broken. Sometimes this happens because the service we use breaks down. cc @MichaelSolati

**Comment by MichaelSolati** [comment]
Also do you have an ad blocker, or is Javascript disabled in your browser?

**Comment by sakettawde** [comment]
Problem still persists.

Yes I have an ad blocker.

Tested with and without an ad blocker. Issue occurred both times. Javascript is not disabled in my browser.

Inputs:
First Name: Saket
Last Name: Tawde
Email: <doesn't seem to matter provided it is valid>
Country: India
