### ISSUE TITLE
Videos Missing in `optimize-cls`

### ISSUE THREAD

**Issue by MichaelSolati** [GoogleChrome/web.dev#5050]
In `src/site/content/en/blog/optimize-cls/index.md` there is a video (around line 192), that doesn't work/isn't live.

They('re)

https://storage.googleapis.com/web-dev-assets/optimize-cls/top-ad-after.webm
https://storage.googleapis.com/web-dev-assets/optimize-cls/top-ad-after.mp4

I'm not sure what happened to them but if you visit https://web.dev/optimize-cls/ and try to click the video with the caption "Ads with sufficient space reserved." Well, nothing happens.

I'm about to land a biggish PR moving images/video to the cdn, but above it I'll have the shortcode ready to go. I just need the videos uploaded to the bucked and the srcs generated added to the src array. My PR should land within the next hour or two, so if we could hold off on fixing this for a lil bit (or send me the vids directly and ill fix it), that'd be awesome.

**Comment by addyosmani** [comment]
Will email :)
