### ISSUE TITLE
Add filtering to learn page

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#5054]
Jiwoong made a nice mock for this:
![image](https://user-images.githubusercontent.com/1066253/114203872-6ac74180-990d-11eb-987f-0647479ab34a.png)

It shrinks the cards a bit and adds a row at the top to filter by topic area. Maybe we'd revisit our topic area descriptions to make the filtering more useful?

**Comment by robdodson** [comment]
Maybe. I think HelloMonday might include something like this in their redesign. I guess we'll see what they show tomorrow?

**Comment by MichaelSolati** [comment]
fixes w/ #6454
