### ISSUE TITLE
Search Bar Tabs Me Out When Typing In Article Pages

### ISSUE THREAD

**Issue by AveryTheDev** [GoogleChrome/web.dev#5067]
Sometimes when I attempt to make a search, the bar tabs me out of input field as soon as I start typing. For obvious reasons, this means I cannot make a search.

This is what it looks like on my screen.

https://user-images.githubusercontent.com/23192489/114411774-7d927e00-9b7a-11eb-93df-61067ed2ee1b.mov

I am not certain what the particular trigger for this bug is yet, because I had encountered this bug a couple days ago but failed to reproduce again when I attempted to make a recording that day.

**Comment by AveryTheDev** [comment]
I just realized that this only happens when I try to search when an article is opened up. I do not experience this on the home screen or on the main pages for Learn, Measure, Blog, and About

**Comment by robdodson** [comment]
Probably related to #5043 

I think we must have introduced a regression in the search bar at some point. @AveryTheDev does it still happen if you scroll the page to the top?

**Comment by AveryTheDev** [comment]
Hmmm after reading your comment, this behavior does in fact happen on every page. If the the page is not at the top, I cannot search even on the home screen

**Comment by AveryTheDev** [comment]
It does not however, scroll my page up
