### ISSUE TITLE
Search returns more pages than results

### ISSUE THREAD

**Issue by kjue25** [GoogleChrome/web.dev#508]
**Page Affected:** https://web.dev/s/results/?q=images&p=%2F (example search for "images")

**What needs to be done?**

Searching certain terms returns more pages than there are results.  For example, the results for "images" only go up to page 5, but pages 6-8 are also linked at the bottom.  Clicking on 6-8 returns "No results," and only when you click on page 5 specifically do pages 6-8 disappear.

**Comment by ebidel** [comment]
Good catch! b/120443329

**Comment by ebidel** [comment]
" The total count is an estimate because actually calculating results is expensive.

DevSite uses Custom Search Engine for search, and this is what Custom Search Engine provides. CSE is basically just Google Search with the "site:" keyword."
