### ISSUE TITLE
content: Preventing FLoC misunderstanding 

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#5112]
There is a lot of misunderstanding around whether pages need to share their visitors’ data with FLoC. There should be a **big green box** prominently on the page that includes the following phrase:

*“A page visit will **only** be included in the browser's FLoC calculation if `document.interestCohort()` is used on the page. During the current FLoC origin trial, a page will also be included in the calculation if (and only if) Chrome detects that the page load ads or ads-related resources.”*

This phrase appears below, but it’s easy to overread.

**Comment by tomayac** [comment]
Context: https://twitter.com/Log3overLog2/status/1383430203137945606

**Comment by rowan-m** [comment]
An `{Aside}` after the initial sentence linking to https://developer.chrome.com/blog/floc/ and providing a brief explanation of origin trial eligibility would be appropriate here.

**Comment by tomayac** [comment]
Fixed in #5118.
