### ISSUE TITLE
Google Pay Button's does not process the Payment and throws 404 error

### ISSUE THREAD

**Issue by merajali294** [GoogleChrome/web.dev#5117]
Describe the bug
I’m trying to modify Javascript so that the I can make the Payment successfull, but it does not work and gives me the 404, can someone here check and fix this?

My use case is,
I want the Chrome PopUp to process my Payment and give me a success message and rerdirect to the ORDER CREATED SUCCESSFULLY PAGE.

Have implemented similar part here, it works, https://sravan523.com/product/prdct-2/
Thank you for your help!

Environment (please complete the following information):
Expectd use case, Once the Payment is done, it should give me success message, always throws error 404.
WordPress Version 5.7
WooCommerce Version 5.1.0
Browser chrome

**Comment by robdodson** [comment]
@merajali294 For tech support related to Google Pay you can go to their support FAQ
https://developers.google.com/pay/api/faq

I might also suggest trying on StackOverflow
