### ISSUE TITLE
Measure - Url textbox has double x for close Win10 Edge

### ISSUE THREAD

**Issue by stewartwarner** [GoogleChrome/web.dev#515]
I thought this was entered but could not find an issue, so I wanted to raise it again.

URL: 
- https://web.dev/measure

Browser:
- Win10 Edge

Steps:

1. Go to the Measure page
2. Enter a url and run audit
3. Switch url
4. As soon as you focus on the text box, there is a double X in the textbox

Screenshot
![image 1](https://user-images.githubusercontent.com/2489799/49665003-62daf800-fa08-11e8-9970-dbf8dae717b5.png)

**Comment by robdodson** [comment]
There's a lot of interesting things going on in that screenshot, especially that error message.

cc @ebidel @TimvdLippe

**Comment by robdodson** [comment]
That makes sense. Tim—do you have Edge running on a corp machine? I've always used BrowserStack to look at staging sites but I bet that won't work with our internal staging. If you're able to verify staging could you send in a CL to fix this?

**Comment by TimvdLippe** [comment]
I was running a VM on my machine. But the VM does not allow me to open the developer tools. I can of course apply the selector and see if that fixes it.

**Comment by TimvdLippe** [comment]
Nope, my VM does not allow me to debug it. I suppose we can just push the fix and see if it fixes? We can always revert if it does not work out.

**Comment by ebidel** [comment]
I'm unable to repro the error message. Anyone else?

**Comment by robdodson** [comment]
yeah i can't repro the error. But we did land Tim's CL to fix the double X's
