### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by almo** [GoogleChrome/web.dev#5189]
**Describe the bug**
The link included in the text

 "_This page is not translated yet. Consider improving it by [contributing your translation](https://web.dev/gitlocalize.com/repo/5395/pl/src/site/content/en/index.md)._"

is broken

**To Reproduce**
1. Go to web.dev
2. Scroll down
3. At the bottom, change the language clicking on "Polski (PL)"
3. Scroll up to see  on the top the message "_This page is not translated yet. Consider improving it by [contributing your translation](https://web.dev/gitlocalize.com/repo/5395/pl/src/site/content/en/index.md)._"
4. Click on the link See error "[contributing your translation](https://web.dev/gitlocalize.com/repo/5395/pl/src/site/content/en/index.md)._"
5. You get a 404

**Expected behavior**
I would expect to have instruction to translate the content.

**Screenshots**
![broken link](https://user-images.githubusercontent.com/344279/116416838-ff50ff80-a83a-11eb-8bb2-1625ef8dd13d.jpg)
![404](https://user-images.githubusercontent.com/344279/116416868-0aa42b00-a83b-11eb-9cce-e7f68f1e7437.jpg)

**Comment by devnook** [comment]
The banner is disabled now.
