### ISSUE TITLE
Creating WebP Images with the Command Line  ‘node’: No such file or directory

### ISSUE THREAD

**Issue by feco93** [GoogleChrome/web.dev#520]
In the console after typing
cwebp -q 50 images/flower1.jpg -o images/flower1.webp
command, there's an error message:
/usr/bin/env: ‘node’: No such file or directory
according to the message, probably the node hasn't installed in this environment.

**Comment by robdodson** [comment]
Taking a look. I'm pretty sure this used to work. Possible that Glitch changed something in their embeds.

**Comment by robdodson** [comment]
Should be fixed now (after some updates!) Let me know if you still hit issues.
