### ISSUE TITLE
Removed Elements and LCP

### ISSUE THREAD

**Issue by alexkuc** [GoogleChrome/web.dev#5202]
While reading [Largest Contentful Paint (LCP)](https://web.dev/lcp/) I have come across this inconsistency:

> However, (as mentioned above) an element will be removed from consideration if it's removed from the DOM or if its associated image resource changes.

However, according to _previous_ sentence:

> If an element that is currently the largest contentful element is removed from the viewport (or even removed from the DOM), it will remain the largest contentful element unless a larger element is rendered.

The same is corroborated by W3C:

https://github.com/WICG/largest-contentful-paint#removed-elements

> In order to correctly compute LCP in cases such as image carousels, the LCP algorithm considers removed elements. If a content element is removed from the DOM tree, the element is not excluded from being an LCP candidate. See examples here.

Is this an oversight in the web.dev page or did I misunderstand something?

**Comment by robdodson** [comment]
@philipwalton can you weigh in?

**Comment by philipwalton** [comment]
Thanks for reporting!

> However, (as mentioned above) an element will be removed from consideration if it's removed from the DOM or if its associated image resource changes.

Yes, this is no longer correct. It _was_ correct  when it was first written, but it looks like this sentence was missed when we updated the post with the [change to LCP to consider removed elements](https://chromium.googlesource.com/chromium/src/+/master/docs/speed/metrics_changelog/2020_11_lcp.md).
