### ISSUE TITLE
Two-way communication guide doesn't warn about keeping Service Workers awake

### ISSUE THREAD

**Issue by taymonbeal** [GoogleChrome/web.dev#5224]
https://web.dev/two-way-communication-guide/#message-channel offers the following code snippet:

```javascript
let communicationPort;

//Save reference to port
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'PORT_INITIALIZATION') {
    communicationPort = event.ports[0];
  }
});

//Send messages
communicationPort.postMessage({type: 'MSG_ID'});
```

However, as https://web.dev/service-worker-mindset/#watch-out-for-global-state explains, it's not safe to rely on this. If the browser chooses to stop the Service Worker, then when it restarts again, `communicationPort` will be reinitialized to `undefined` and the `message` listener won't trigger again unless the page sends another message. You have to take specific measures to prevent that from happening, such as by using `waitUntil` in the message handler to prevent the worker from being stopped until the page is done talking to it.

**Comment by kaycebasques** [comment]
@demianrenzulli @jeffposnick PTAL

**Comment by demianrenzulli** [comment]
Thanks for flagging this @taymonbeal!

I'll be updating this article along with other content submissions I'm making.

**Comment by taymonbeal** [comment]
This is still a live issue and shouldn't be closed yet.

**Comment by taymonbeal** [comment]
Nope, the page is still wrong.

**Comment by AaronForinton** [comment]
Hello @taymonbeal. I'm just letting you know that this has now fallen under my remit and it'd be awesome to know if you're still around to connect on this.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and content on this site is now frozen, so we’ll fix this on the new platform. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298526954
