### ISSUE TITLE
Illustration - How search works

### ISSUE THREAD

**Issue by carolrivero** [GoogleChrome/web.dev#526]
Migrated from Buganizer.

Need illustration for "How Search Works"
Suggested illustrations:
something along the lines of this: https://code-cartoons.com/a-cartoon-intro-to-facebook-s-relay-part-1-3ec1a127bca5 - though, it should be a lot less technical here!
I'm imagining all illustrations would be in a library, showing different things happening (looking up a book, finding a book, checking it out, etc)

**Comment by robdodson** [comment]
Consolidated into #533
