### ISSUE TITLE
Clicking on a blog that is not yet released goes nowhere with no feedback to the user as to why?!

### ISSUE THREAD

**Issue by andystevenson** [GoogleChrome/web.dev#5260]
**Describe the bug**
I tried to access Andy Bell's - Learn CSS blog posts.
As of today if you click on any of Andy's posts they go nowehere with no user feedback as to why

**To Reproduce**
1. Go to Blog section
2. Click on an Andy Bell - Learn CSS blog post
3. See nothing... page just refreshes and stays where it is

**Expected behavior**
There should be some user feedback that shows the blog is locked or an icon on the card showing it is locked

**Screenshots**
<img width="590" alt="image" src="https://user-images.githubusercontent.com/1989620/117174806-042b2b80-adc6-11eb-85da-1af2e993b668.png">

**Comment by kaycebasques** [comment]
Thanks for the bug. That series of content hasn't been published yet and shouldn't be showing up on the site. Can you provide links and screenshots of where exactly you're seeing it?

**Comment by kaycebasques** [comment]
Can reproduce that Learn CSS posts are showing up on https://web.dev/authors/andybell/

**Comment by andystevenson** [comment]
Hi Kayce,

https://web.dev/tags/css/ <https://web.dev/tags/css/>

I was on the above link when I clicked on any of Andy Bell’s posts.

Regards, Andy

**Comment by andystevenson** [comment]
Noted thanks!
