### ISSUE TITLE
Third Party report missing in script renderd by lighthouse

### ISSUE THREAD

**Issue by spham** [GoogleChrome/web.dev#528]
Hi

it seems have issue on report from lighthouse when report concerns all third party use with GTM or Tag Commander.

For exemple, we don't see facebook javascript, but see it on chrome dev tools.

regards

**Comment by robdodson** [comment]
Hi @spham can you share a URL we can test with?

**Comment by TimvdLippe** [comment]
Closing this issue as we have not received a response. Please reopen this issue with the requested URL.
