### ISSUE TITLE
[bug] Missing image: learn-css Grid module

### ISSUE THREAD

**Issue by una** [GoogleChrome/web.dev#5285]
Missing image `https://web-dev.imgix.net/image/VbAJIREinuYvovrBzzvEyZOpw5w1/YxpjWBUDsqQB2fr6rzU3.jpg`

**Screenshots**
![Screen Shot 2021-05-07 at 1 38 00 PM](https://user-images.githubusercontent.com/1693164/117487726-73755c80-af39-11eb-9f0e-7841c52c2521.png)

**Comment by rachelandrew** [comment]
The image is loading now.
