### ISSUE TITLE
Adjust sizing for Courses Sidebar

### ISSUE THREAD

**Issue by una** [GoogleChrome/web.dev#5322]
Sidebar can stay in base view for longer

**Comment by devnook** [comment]
@una Where do you think we should have a breakpoint? Also, do we want to have this "minimal sidebar" view? 
<img width="254" alt="Screenshot 2021-05-14 at 11 32 16" src="https://user-images.githubusercontent.com/1914261/118251695-2f89d680-b4a8-11eb-844f-18f8df69fb19.png">

**Comment by una** [comment]
I do like the minimal sidebar view — if it’s not too much trouble to
implement, I think it helps with context.

- Una
