### ISSUE TITLE
Add illustrations to guides

### ISSUE THREAD

**Issue by carolrivero** [GoogleChrome/web.dev#533]
- [ ] [web.dev/fast/reduce-javascript-payloads-with-code-splitting](web.dev/fast/reduce-javascript-payloads-with-code-splitting)
Illustration request - someone waiting
- [ ] [web.dev/fast/remove-unused-code](web.dev/fast/remove-unused-code)
An illustration of someone getting frustrated maybe?
- [ ] [web.dev/fast/preload-critical-assets](web.dev/fast/preload-critical-assets)
Somebody getting frustrated or almost giving up, etc...
- [ ] [web.dev/fast/apply-instant-loading-with-prpl](web.dev/fast/apply-instant-loading-with-prpl)
- [ ] [web.dev/accessible/what-is-accessibility]( web.dev/accessible/what-is-accessibility)
- [ ] [web.dev/discoverable/how-search-works](web.dev/discoverable/how-search-works)
something along the lines of this: code-cartoons.com/a-cartoon-intro-to-facebook-s-relay-part-1-3ec1a127bca5 - though, it should be a lot less technical here!
I'm imagining all illustrations would be in a library, showing different things happening (looking up a book, finding a book, checking it out, etc)

**Comment by robdodson** [comment]
@addyosmani do you think Susie might be available for these?

**Comment by robdodson** [comment]
Or if that's not her art style, I think I know someone else we could try.

**Comment by robdodson** [comment]
Assigning to @carolrivero for now. My thinking is maybe Carol would own setting up the relationship with the illustrator. Happy to reassign if that's a bad fit.

**Comment by carolrivero** [comment]
Happy to own this for now. 

I would also suggest we hold off on acting on immediate tasks (similar to this and new feature/designs) associated w/ V2 until we have a more defined scope (PRD). 

Thanks.

**Comment by robdodson** [comment]
yep, sgtm

**Comment by robdodson** [comment]
Going to close this as stale.
