### ISSUE TITLE
Typo in article title for passive event listeners

### ISSUE THREAD

**Issue by chrishtr** [GoogleChrome/web.dev#5331]
Load https://web.dev/uses-passive-event-listeners/

Title is: "Does not use passive listeners to improve scrolling performance"

Should be: "Use passive listeners to improve scrolling performance"

**Comment by robdodson** [comment]
I think our page titles were derived from the lighthouse audit title

![image](https://user-images.githubusercontent.com/1066253/119011944-65b4d380-b94a-11eb-84dc-40bec3f58ac6.png)

but I agree it's a bit weird to read. I'll do a PR to fix.
