### ISSUE TITLE
Staging server: add tests

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/web.dev#534]

**Comment by ebidel** [comment]
Fixed partially in https://github.com/GoogleChrome/web.dev/pull/552.

**Comment by robdodson** [comment]
What other tests were you thinking of adding?

**Comment by ebidel** [comment]
Verify that remote pages can be fetched and wrapped properly. The "verification" part is the tricky part.

**Comment by ebidel** [comment]
It might be ok to close this for now since it would be obvious if the pages stopped rendering correctly when you preview them.
