### ISSUE TITLE
Typo in URL "/is-crawable/"

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/web.dev#5356]
**Describe the bug**
https://web.dev/is-crawable/ contains a typo of the word "crawlable"
Also the audit actually checks indexability, not crawlability

**To Reproduce**
https://web.dev/is-crawable/

**Expected behavior**
https://web.dev/is-indexable/

**Screenshots**
![image](https://user-images.githubusercontent.com/1120896/118320856-ca93a800-b4ca-11eb-9b71-09996c7cdc24.png)
![image](https://user-images.githubusercontent.com/1120896/118320902-dc754b00-b4ca-11eb-859b-f78c03e64bd7.png)

**Comment by robdodson** [comment]
I believe our URLs are supposed to match the IDs used by lighthouse (https://github.com/GoogleChrome/lighthouse/blob/bfa5351639f81ea8a034bed6fb752864ff71f580/lighthouse-core/audits/seo/is-crawlable.js) so we may have to keep the url, but I can do a redirect to fix the typo.
