### ISSUE TITLE
Learn CSS in French

### ISSUE THREAD

**Issue by Bam92** [GoogleChrome/web.dev#5397]
**Is your feature request related to a problem? Please describe.**
I've seen that the course materials are in other lnaguages but French.
**Describe the solution you'd like**
Translate the course in French.
**Describe alternatives you've considered**

**Additional context**

**Comment by robdodson** [comment]
Thank you for the request @Bam92. We're currently in the process of planning translations for the site. I don't think French will be part of our initial batch of translations, but we will see about including it in the future.
