### ISSUE TITLE
app-bar should not be covered

### ISSUE THREAD

**Issue by yikayiyo** [GoogleChrome/web.dev#5403]
**Describe the bug**
Sometimes .app-bar is covered which doesn't look good ; )

**To Reproduce**
1. Go to *Check your understanding*
2. Chose one question, CHECK
3. Scroll down, you will find that .app-bar is covered. ( even before CHECK, it is covered.

**Expected behavior**
.app-bar should be at top.  How about giving it a larger z-index, like 100? Is anyway better?

**Screenshots**
![image](https://user-images.githubusercontent.com/22975826/118837510-7851ed00-b8f7-11eb-8113-b35bf7903904.png)
![image](https://user-images.githubusercontent.com/22975826/118835719-d5e53a00-b8f5-11eb-9c8c-1fe0e1487481.png)

**Comment by robdodson** [comment]
ooooh good catch!
