### ISSUE TITLE
Discovery: prototype pattern library in 11ty context

### ISSUE THREAD

**Issue by andy-piccalilli** [GoogleChrome/web.dev#5408]
I’ve got some rough exploration done where patterns can have multiple variants and inherited context data, so will create a simple prototype for us to look at.

**Comment by andy-piccalilli** [comment]
Howdy, @robdodson, I reckon I can stick a fork in this now.

Here's a little demo of the prototype: 

<div style="position: relative; padding-bottom: 56.25%; height: 0;"><iframe src="https://www.loom.com/embed/0bc530b844644096bdbdf688c54dec17" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe></div>

Here's a repo: https://github.com/andy-piccalilli/11ty-pattern-library

I think a good next step with this would be to start applying some of this into the web.dev repo as a draft PR to see if I can get something running in that context.

**Comment by robdodson** [comment]
@andy-piccalilli this looks so cool!!! amazing work 👍 

I'm going to read through the code and mess around with it running locally today. I may drop some questions into chat later, but I'm really excited to see where this is heading.

**Comment by andy-piccalilli** [comment]
It's really not been too difficult to get running so the world is our oyster, essentially. Definitely glad I explored this direction!

**Comment by robdodson** [comment]
@andy-piccalilli I read through it all and sent in a small PR with some tweaks. https://github.com/andy-piccalilli/11ty-pattern-library/pull/1

I think it looks really great! A few questions that popped into my head as I was reviewing it.

- How might we show shortcodes?
- Should we look into running the docs markdown through prism? Kind of like what eleventy-plugin-syntax-highlighter does? This is definitely not urgent, but would be a nice to have.
- Should we add nunjucks to the package.json? It seems like right now it works because it's a transitive dependency of eleventy but we may want to install it just to really belt and suspenders the whole thing.

**Comment by andy-piccalilli** [comment]
> How might we show shortcodes?

I reckon we create a specific “category” out in the sidebar and render them as patterns.

> Should we look into running the docs markdown through prism? Kind of like what eleventy-plugin-syntax-highlighter does? This is definitely not urgent, but would be a nice to have.

We could run a transform to do exactly this. I think the 11ty prism plugin already does that though, so it might just work outa the box.

> Should we add nunjucks to the package.json? It seems like right now it works because it's a transitive dependency of eleventy but we may want to install it just to really belt and suspenders the whole thing.

Yeh, better to be safe than sorry.

**Comment by andy-piccalilli** [comment]
A question I have, @robdodson: Do we try to integrate the new search stuff in too?

**Comment by robdodson** [comment]
Are you referring to the work Ewa is doing to make the search bar more componentized?

**Comment by andy-piccalilli** [comment]
Yeh that's right. This sorta thing 👇
![CleanShot 2021-05-28 at 16 09 13](https://user-images.githubusercontent.com/8672583/120004982-50394c80-bfcf-11eb-9f3c-a2eec1598e46.gif)

**Comment by robdodson** [comment]
oh neat. Yeah it'd be cool to see about adding that. I'm not sure how it works in Fractal, but the current search component is set up to do a query to some endpoint like Algolia.

**Comment by andy-piccalilli** [comment]
Yeh agreed, it's got a whiff of scope creep on it for sure. Like I said in our sync yesterday too: we gotta keep things as simple as possible!
