### ISSUE TITLE
Broken link on learn/css/selectors page

### ISSUE THREAD

**Issue by romanrolan** [GoogleChrome/web.dev#5411]
**Describe the bug**
Link on learn/css/selectors to /learn/css/pseudo-elements is broken

**To Reproduce**
1. Go to 'learn/css/selectors'
2. Click on 'Learn more in the module on pseudo-elements' link at the bottom of [Pseudo-element section](https://web.dev/learn/css/selectors/#pseudo-element)
3. See 404 error

**Expected behavior**
Pressing the link opens /learn/css/pseudo-elements page

**Comment by rachelandrew** [comment]
Thanks for the report, I have added the missing forward slash in the PR above which should make this link correctly link again.
