### ISSUE TITLE
zClosurez values in results

### ISSUE THREAD

**Issue by jhvanderschee** [GoogleChrome/web.dev#542]
See image below (Firefox on Linux with uBlock):
![screenshot_2018-12-18 measure web dev](https://user-images.githubusercontent.com/13737508/50187628-f53f9d80-031e-11e9-857d-5a078dabb363.png)

**Comment by robdodson** [comment]
Can confirm this is busted on Chrome on macOS as well. Thanks for filing the issue!

**Comment by jhvanderschee** [comment]
![screenshot_2018-12-29 measure web dev](https://user-images.githubusercontent.com/13737508/50540895-b28d8900-0b9a-11e9-9c97-18eac9ab8df1.png)

Not fixed for me.

**Comment by TimvdLippe** [comment]
Simply opening the page makes it break as well. Seems like the culprit is the "show results from your last interesting url". Not sure why this is happening yet...

**Comment by TimvdLippe** [comment]
I think this is related to https://github.com/Polymer/polymer-resin/blob/master/getting-started.md However, that should not be running on our website. @rictic do you maybe know if this is broken in some way with your recent work on lit-html and Polymer-resin?

**Comment by TimvdLippe** [comment]
Thinking more about this: it is probably related to the polymer-resin update, but our test suite did not catch this particular regression. We (e.g. I) should write more tests for the measure page, to make sure other changes do not regress our site. (that would help the devsite team as well with their css breakages)

**Comment by paulirish** [comment]
also reported by Twitter eng here: https://twitter.com/paularmstrong/status/1081287675934662659

**Comment by robdodson** [comment]
Closing as this was fixed a while back.
