### ISSUE TITLE
isCompatible() code in article should use .includes(), not .contains()

### ISSUE THREAD

**Issue by tmb-github** [GoogleChrome/web.dev#5434]
The code in the article for filtering brands is flawed: `.contains()` is a method of Nodes (see https://developer.mozilla.org/en-US/docs/Web/API/Node/contains). The correct method to use is `.includes()` (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)

Proof: Run the code as provided in the repo in the DevTools console:

```
function isCompatible(item) {
  // In real life you most likely have more complex rules here
  return ['Chromium', 'Google Chrome', 'NewBrowser'].contains(item.brand);
}
if (navigator.userAgentData.brands.filter(isCompatible).length > 0) {
  // browser reports as compatible
}

```
It will report: 

> Uncaught TypeError: ["Chromium","Google Chrome","NewBrowser"].contains is not a function
>     at isCompatible (<anonymous>:3:54)
>     at Array.filter (<anonymous>)
>     at <anonymous>:5:36

**Comment by robdodson** [comment]
fixed by cc8d0bf
