### ISSUE TITLE
content: Grammatical Mistake in Flexbox Quiz Question Number 3

### ISSUE THREAD

**Issue by HimanshuKanojiya** [GoogleChrome/web.dev#5436]
### What page(s) need to be updated?
https://web.dev/learn/css/flexbox/#what-can-you-do-with-a-flex-layout

### Why is this update needed?
In Quiz, question number 3 written as "Be default, flex items are aligned to stretch. If you want content height used for child items, which of the following styles would you use?"

And it should be "By default, flex items are aligned to stretch. If you want content height used for child items, which of the following styles would you use?"

**Comment by rachelandrew** [comment]
Thank you! I've just made a PR that should fix this.
