### ISSUE TITLE
Learn CSS BoxModel incorrect example for intrinsic maximum width

### ISSUE THREAD

**Issue by kfdf** [GoogleChrome/web.dev#5437]
[The content and sizing section](https://web.dev/learn/css/box-model/#content-and-sizing) states that

> The max-content keyword tells the box to only be as wide as the intrinsic maximum width of its content (the word "awesome").

Doesn't the word "awesome" define the intrinsic **minimum** width, and the intrinsic **maximum** width is defined by the entire paragraph?

**Comment by rachelandrew** [comment]
Good catch 💯 thanks for the report, I've just made a PR that should fix this along with the CodePen example change.
