### ISSUE TITLE
Login button issue

### ISSUE THREAD

**Issue by ThomasWT** [GoogleChrome/web.dev#544]
**Page Affected:** https://web.dev/measure

**What needs to be done?**

This button does absolutely nothing.. at all.

![dwacl_0woaa_muh 1](https://user-images.githubusercontent.com/1246641/50655251-d92f3380-0f8f-11e9-841b-a2a9773692f1.jpg)

**Comment by robdodson** [comment]
Will take a look, thanks for filing!

**Comment by ebidel** [comment]
b/122362764

**Comment by ebidel** [comment]
Should be fixed now
