### ISSUE TITLE
Broken video link re: Route preloading in Angular

### ISSUE THREAD

**Issue by I82Much** [GoogleChrome/web.dev#5442]
**Describe the bug**
https://web.dev/route-preloading-in-angular/ has an embedded video which does not play. 

**To Reproduce**
1. Go to https://web.dev/route-preloading-in-angular
2. Click on embedded video

You can also see that the srcs it links to give an error: https://storage.googleapis.com/web-dev-angular/preloading/preload-all.webm -> 
```
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist.</Message>
</Error>
```

same with https://storage.googleapis.com/web-dev-angular/preloading/preload-all.mp4

**Expected behavior**
Video plays

**Screenshots**
![Video playback does not work](https://user-images.githubusercontent.com/20299/119388371-0b37b200-bc7f-11eb-917b-58604cb57d87.png)

**Comment by I82Much** [comment]
Note that this also affects other videos on the same page e.g. https://storage.googleapis.com/web-dev-angular/preloading/ngx-quicklink.webm

**Comment by robdodson** [comment]
@MichaelSolati do you think this may have been tied to our image/video migration?

**Comment by MichaelSolati** [comment]
This isn't me, but I'll ping @mgechev to see if he knows what happened, or has the original videos that I can add to our cdn and update the videos.
