### ISSUE TITLE
Cannot change preferred language

### ISSUE THREAD

**Issue by sebasjm** [GoogleChrome/web.dev#5443]
**Describe the bug**
I can't get the spanish version of the site.

**To Reproduce**
1. Go to https://web.dev/learn/css/
2. Scroll down
3. Select spanish in `select[id=preferred-language]`
4. It should be spanish, is english

**Expected behavior**
I expect the site in spanish

**Screenshots**
It shouldnt be necessary

**Comment by robdodson** [comment]
Ah, that dropdown shouldn't really be enabled just yet. @devnook do you think we should hide the select element until we ship translations?
