### ISSUE TITLE
learn/css/specificity css color bug when hover

### ISSUE THREAD

**Issue by lomocc** [GoogleChrome/web.dev#5445]
**Describe the bug**
[A matching specificity score sees the newest instance win](https://web.dev/learn/css/specificity/#a-matching-specificity-score-sees-the-newest-instance-win)
the gray button hoverColor is change to **blue**

**To Reproduce**
1. open https://web.dev/learn/css/specificity/#a-matching-specificity-score-sees-the-newest-instance-win
2. hover the **gray** button
3. the button background color is **blue**

**Expected behavior**
the button background color is gray

**Screenshots**
<img width="850" alt="WX20210525-164900@2x" src="https://user-images.githubusercontent.com/2075138/119468592-2f77b980-bd79-11eb-8946-6da83661f27d.png">

**Comment by lomocc** [comment]
Error is caused by codepen
https://codepen.io/web-dot-dev/pen/zYNOXKJ

**Comment by argyleink** [comment]
hi! this demo is about background color and not hover specificity and background color. the demo is showing what it needs to show? i think this is more of a design request, or design consistency suggestion?

**Comment by lomocc** [comment]
Just confusing, as a newbie, I dont know why the background color is still blue when hover.

**Comment by argyleink** [comment]
would it be helpful if we added something like:

"The button still has a blue hover color because only the non-hovered background was changed"?

**Comment by lomocc** [comment]
yes, or we can reset the background-color of button.
it displays correct when I use `codesandbox`, so I prefer `codesandbox` than `codepen`:
https://codesandbox.io/s/competent-hopper-csnbz

**Comment by lomocc** [comment]
There is an confusing style in the codesandbox settings: https://codepen.io/web-dot-dev/pen/abpoXGZ.css.

![image](https://user-images.githubusercontent.com/2075138/123051337-4242e400-d434-11eb-9f83-9b8ad7809790.png)

**Comment by argyleink** [comment]
nice yeah, i think this may be the root of the confusion, as many of our demo codepens load a common stylesheet with buttons styles, link styles and some other things to help all the demo's look nice and similar. this is where the button hover color is defined, and why hovering results in blue and not grey 👍🏻 

maybe this whole bug was about finding that stylesheet so you knew "why" a hover color (and all the other button styles) even existed?

**Comment by lomocc** [comment]
yes, I knew now.

I think we can use border instead of background:

```css
.my-button {
  border: 10px blue solid;
}

[onclick] {
  border: 10px grey solid;
}
```
then as a newbie,  no longer confused
