### ISSUE TITLE
Remove release date for GravitySensor,

### ISSUE THREAD

**Issue by arskama** [GoogleChrome/web.dev#5473]
### What page(s) need to be updated?
src/site/content/en/blog/generic-sensor/index.md

### Why is this update needed?
remove release date for gravity sensor. Chrome91 has been released with the feature.

### What's the deadline?
asap

#### Is it a hard deadline?
no

**Comment by beaufortfrancois** [comment]
@tomayac FYI

**Comment by tomayac** [comment]
Thank you, @arskama!
