### ISSUE TITLE
Broken 404 Ressource Link 

### ISSUE THREAD

**Issue by autoschieber** [GoogleChrome/web.dev#5476]
At the end of the page 
https://web.dev/uses-webp-images/
the link 

"Source code for Serve images in next-gen formats audit"
https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/byte-efficiency/uses-webp-images.js

links to a 404 ressource

**Comment by tannerdolby** [comment]
Had a look at https://web.dev/uses-webp-images/ and the link "Source code for Serve images in modern formats audit" correctly takes us to the source code on GitHub. The link text changed a little bit from "in next-gen formats" to "in modern formats" but I'm positive its the same source code file.

https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/byte-efficiency/modern-image-formats.js

I reckon this is ready to be closed @robdodson !
