### ISSUE TITLE
Incorrect value used in repeat

### ISSUE THREAD

**Issue by Tecvoc** [GoogleChrome/web.dev#5485]
**Describe the bug**
The syntax of repeat function as defined in [link](https://www.w3.org/TR/css3-grid-layout/#repeat-syntax) section 7.2.3.1 says that *Automatic repetitions (auto-fill or auto-fit) cannot be combined with intrinsic or flexible sizes*, however in one of the examples its being done, namely a fr unit is used.

**To Reproduce**
1. Go to 'https://web.dev/learn/css/grid/'
2. Scroll down to 'auto-fill and auto-fit'
3. In the 2nd codepen demo in that section, [codepen_link](https://codepen.io/web-dot-dev/pen/MWJbbNe)

**Expected behavior**
A non flexible unit should have been used instead of a fr

**Comment by rachelandrew** [comment]
@Tecvoc it can, when minmax() is used, as the value being repeated is non-flexible, the fr unit is used to distribute the leftover space. There is a spec example showing the behavior here https://www.w3.org/TR/css3-grid-layout/#auto-repeat

**Comment by Tecvoc** [comment]
Hi, I read through the spec and it indeed is so, thanks a lot for the clarification @rachelandrew
