### ISSUE TITLE
Box model size incorrect

### ISSUE THREAD

**Issue by daniel-schroeder-dev** [GoogleChrome/web.dev#5488]
In the *Box Model* tutorial, this sentence has the wrong size for the box:

> The content would break out of your element and it would be 140px wide, rather than 100px.

Given the CSS provided:

```css
p {
    width: 100px;
    height: 50px;
    padding: 20px;
    border: 1px solid;
}
```
The `<p>` element will have a width of 142px (due to the border), not 140px. Pedantic, I know, but it stood out to me as soon as I saw the example.

**To Reproduce**
1. Go to [Box Model](https://web.dev/learn/css/box-model/)
2. Scroll to the first example under the `<p>` CSS shown above
4. Fix the 140px to be 142px

**Expected behavior**
The text should be:

> The content would break out of your element and it would be 142px wide, rather than 100px.

**Screenshots**
![para-css](https://user-images.githubusercontent.com/15895133/120085642-8ba34c00-c09f-11eb-9b3f-28a38aadd466.png)
![para-element](https://user-images.githubusercontent.com/15895133/120085665-b392af80-c09f-11eb-94b8-5a31f0645635.png)

**Comment by robdodson** [comment]
@una @argyleink could y'all take a look?

**Comment by argyleink** [comment]
thank you @daniel-schroeder-dev, great catch! 🎣 
PR with the change in flight 👍🏻
