### ISSUE TITLE
Codepen live example for justify-content / align-content 

### ISSUE THREAD

**Issue by gnehcwu** [GoogleChrome/web.dev#5489]
**Describe the bug**
Values like `space-around | space-between | space-evenly` are missing in expanded list to experiment.

**To Reproduce**
1. Go to https://web.dev/learn/css/grid/#distributing-extra-space
2. Click on the dropdown to choose alignment or justification

**Expected behavior**
Values for alignment or justification like `space-around | space-between | space-evenly` should be listed.

**Screenshots**
![image](https://user-images.githubusercontent.com/5228723/120098191-60b30980-c12c-11eb-9095-f932b7358453.png)

**Comment by robdodson** [comment]
@una @argyleink could y'all take a look?

**Comment by argyleink** [comment]
Nice catch, thank you! 
Codepen updated, bug is resolved 👍🏻  Want to verify?

**Comment by gnehcwu** [comment]
It's working good now, nice quick fix, cheers! @argyleink 👍🏻
