### ISSUE TITLE
Wrong Codepen example for justify-items / align-items

### ISSUE THREAD

**Issue by gnehcwu** [GoogleChrome/web.dev#5490]
**Describe the bug**
Properties "justify-items / align-items" should be used in the example.

**To Reproduce**
1. Go to https://web.dev/learn/css/grid/#moving-content-around
2. See mis-set properties

**Expected behavior**
Correct properties should be used for demoing.

**Screenshots**
![image](https://user-images.githubusercontent.com/5228723/120098393-8ee51900-c12d-11eb-9d64-450477933346.png)

**Comment by argyleink** [comment]
I went looking through the Codepens and I dont think an align-items and justify-items demo was created. We'll need to fork and update the post.
