### ISSUE TITLE
transfer feature flags article to developer.chrome.com

### ISSUE THREAD

**Issue by myakura** [GoogleChrome/web.dev#5496]
**Is your feature request related to a problem? Please describe.**

https://web.dev/browser-flags/ talks about the feature flags in Chrome and other Chromium-based browsers and doesn't talk about web technologies (APIs or best practices).

**Describe the solution you'd like**

Transfer the article to https://github.com/GoogleChrome/developer.chrome.com as it's more suitable for content that is specific to Chrome/Chromium.

**Comment by robdodson** [comment]
@tomayac would you be ok with us migrating this one? I agree that it seems very Chrome/Chromium specific and is probably a better fit on d.c.c.

**Comment by tomayac** [comment]
LGTM to migrate. While the article sets a policy for web.dev, I agree
the core content is Chromium-centric. @robdodson, do you take care of
the migration and adding a redirect, or how does this work?

**Comment by robdodson** [comment]
@tomayac if you have the bandwidth to do the migration that would be ideal but I'm happy to take it if you're busy with other things right now.

**Comment by tomayac** [comment]
I’ll do it.

**Comment by tomayac** [comment]
Was just wondering if maybe you had an automatic process for this already.

**Comment by robdodson** [comment]
> Was just wondering if maybe you had an automatic process for this already.

oh, no unfortunately not
