### ISSUE TITLE
Remove Netlify

### ISSUE THREAD

**Issue by MichaelSolati** [GoogleChrome/web.dev#5521]
In order to remove the netlify previews we need to run two tasks at the same time...

1. We need to disable to netlify bot that adds a comment to the PR.
2. We need to disable autopublish on netlify for PRs.

**Comment by robdodson** [comment]
Maybe we should close this as it seems like switching to Firebase is going to be harder than we thought.

**Comment by robdodson** [comment]
Closing this as wontfix for now. It seems like the firebase preview stuff doesn't play nice with forked branches.
