### ISSUE TITLE
[PWA as URL Handlers article] : Update Acknowledgements

### ISSUE THREAD

**Issue by LuHuangMSFT** [GoogleChrome/web.dev#5525]
### What page(s) need to be updated?
web.dev/src/site/content/en/blog/pwa-url-handler/index.md

### Why is this update needed?
Add [Mandy Chen]() to the acknowledgements section. I.e.:
`PWAs as URL Handlers was specified and implemented by [Lu Huang](https://github.com/LuHuangMSFT) and [Mandy Chen](https://github.com/mandymsft) from the Microsoft Edge team. `

### What's the deadline?
No deadline.

**Comment by LuHuangMSFT** [comment]
@tomayac I'm checking if I can contribute/agree to the CLA for this repo. Using issues in the meantime. Would it better to create separate issues or group some changes into the same issue?

**Comment by tomayac** [comment]
Hey 👋. If you can’t sign the CLA, please open an Issue with the diff, tag me, and I can take it from there. Thanks for your feedback already! I’ll be sure to credit you!

**Comment by LuHuangMSFT** [comment]
👍 Thanks!
