### ISSUE TITLE
[PWA as URL Handlers article] : Content modifications

### ISSUE THREAD

**Issue by mandymsft** [GoogleChrome/web.dev#5527]
### What page(s) need to be updated?

web.dev/src/site/content/en/blog/pwa-url-handler/index.md

### Why is this update needed?
1.
> The `web-app-origin-association` file format for validating out-of-scope URL associations.

The association file is needed not just for out-of-scope associations, but any url_handlers listed in the manifest, including in-scope ones. 

2.
> URLs that match these origins could be handled by this web app. The scheme is always assumed to be `https://`.

Currently the origins need to include `https://`. Examples url_handlers need to be fixed too.

3.
```
{
  "url_handlers": [
    {
      "origin": "music.example.com"
    },
    {
      "origin": "*.music.example.com"
    },
    {
      "origin": "🎵.example.com"
    }
  ]
}
```

With the second origin. the first one won't be necessary, unless it's listed as an example.

4.

> For the browser to discover the web-app-origin-association file, developers have two choices.

We currently only support the second choice (i.e. place in .well-known).

### What's the deadline?

No deadline.

**Comment by tomayac** [comment]
Thanks, @mandymsft. I’ll take care of this tomorrow from my desktop machine. On mobile now. If there’s more changes, just pile them onto the present Issue. Thanks!

**Comment by mandymsft** [comment]
Following up, is there a PR for this yet?

**Comment by tomayac** [comment]
> Following up, is there a PR for this yet?

I'm sorry, this fell through the cracks :-( I have just opened https://github.com/GoogleChrome/web.dev/pull/5651 that fixes these points. Thanks for the review!

**Comment by mandymsft** [comment]
Thank you so much!
