### ISSUE TITLE
Audit results should show failing nodes.

### ISSUE THREAD

**Issue by stuartlangridge** [GoogleChrome/web.dev#553]
The Lighthouse audit is semi-helpful, but as far as I can tell, Lighthouse knows what the actual problem is but doesn't reveal that in the audit. For example, an audited page says "Eliminate render-blocking resources". Running an actual Lighthouse audit using the extension does, if I remember correctly, point out _which_ resources on the page are render-blocking. The web.dev audit doesn't; it just says that there are some and links to general guidance on how to fix this class of problem. It's hard to know what to do next; LH must know which resources are render-blocking (or which IDs are duplicated, or which links don't have a discernable name, etc), and the audit would be considerably more useful if it pointed them out.

**Comment by stuartlangridge** [comment]
Half a point for this stuff being available in the actual Lighthouse report, available from the View Report link, but the very fact that I didn't notice that until after I filed this issue suggests that this stuff maybe should be surfaced more obviously?

**Comment by robdodson** [comment]
Agree. We didn't want to completely duplicate the functionality of LH in our site but we would like to make it easier to pull this info in. Starting with this issue https://github.com/GoogleChrome/lighthouse/issues/6668 to let folks jump into the specific spot in the report that tells them the nodes.

**Comment by robdodson** [comment]
Going to close this for now. We link to the full report which does show failing nodes. Instead of duplicating that functionality we've been discussing integrating the full report more directly with the measure page itself.
