### ISSUE TITLE
Pictures on the home page are inserted incorrectly

### ISSUE THREAD

**Issue by innomerphey** [GoogleChrome/web.dev#5532]
**Describe the bug**
Pictures on the main page are inserted incorrectly.

**To Reproduce**
1. Go to [web.dev](https://web.dev/)
2. Scroll down to the LATEST STORIES section.
4. Check the way the pictures are inserted.

The use of the `sizes` attribute is not allowed with density descriptors. 
![validation](https://user-images.githubusercontent.com/17543596/120712107-12c43b80-c475-11eb-9ae3-dbf24a551042.jpg)

There must be a parsing error, but the browser is smart enough to resolve it. So everything seems to work as expected.

There is a code snippet.
```html
<img alt="Interconnected chains, symbolizing the handling of URLs."
       class="w-card-base__image"
       height="240"
       src="https://web-dev.imgix.net/image/8WbTDNrhLsU0El80frMBGE4eMCD3/tCdgaIMviiwzyggA2dBt.jpg?auto=format&amp;fit=crop&amp;h=240&amp;w=354"
       width="354"
       loading="lazy"
       decoding="async"
       sizes="(min-width: 354px) 354px, calc(100vw - 48px)"
       srcset="https://web-dev.imgix.net/image/8WbTDNrhLsU0El80frMBGE4eMCD3/tCdgaIMviiwzyggA2dBt.jpg?fit=crop&amp;h=240&amp;w=354&amp;auto=format&amp;dpr=1&amp;q=75,
       https://web-dev.imgix.net/image/8WbTDNrhLsU0El80frMBGE4eMCD3/tCdgaIMviiwzyggA2dBt.jpg?fit=crop&amp;h=240&amp;w=354&amp;auto=format&amp;dpr=2&amp;q=50 2x,
       https://web-dev.imgix.net/image/8WbTDNrhLsU0El80frMBGE4eMCD3/tCdgaIMviiwzyggA2dBt.jpg?fit=crop&amp;h=240&amp;w=354&amp;auto=format&amp;dpr=3&amp;q=35 3x,
       https://web-dev.imgix.net/image/8WbTDNrhLsU0El80frMBGE4eMCD3/tCdgaIMviiwzyggA2dBt.jpg?fit=crop&amp;h=240&amp;w=354&amp;auto=format&amp;dpr=4&amp;q=23 4x,
       https://web-dev.imgix.net/image/8WbTDNrhLsU0El80frMBGE4eMCD3/tCdgaIMviiwzyggA2dBt.jpg?fit=crop&amp;h=240&amp;w=354&amp;auto=format&amp;dpr=5&amp;q=20 5x">
```
I suppose the `sizes `attribute was used to tell the browser how much space to allocate. In this case, you have to replace everything with w-descriptors. And you may use something like this.
`sizes="(max-width: 481) calc(100vw-48px), (max-width: 576px) calc(100vw-96px),  (max-width: 865px) 448px, 365.33px"`

If continue using x-descriptors, then need to get rid of the `sizes `attribute.  And specify with CSS, dimensions that the user agent can use before downloading the image. But in this case, I don't quite understand why the first element of the `srcset `attribute is used (with dpr=1). Because the attribute `src `also participates in image resource selection, as if it were specified in the `srcset ` with a 1x descriptor, the browser has 2 candidates with the same pixel density. I don't know what the browser does in such cases, but I suspect one candidate will be removed.

Note that the `src ` attribute is ignored when the `srcset `attribute uses w-descriptors.

Here is a link to the [spec](https://html.spec.whatwg.org/multipage/images.html#srcset-attributes:sizes-attribute).

**Comment by robdodson** [comment]
hm yeah this seems like imgix-core.js is falling back to using density descriptors. I've seen it do this before when we don't pass the params in, in a way that it likes. @MichaelSolati can you take a look?

**Comment by jeffposnick** [comment]
https://validator.w3.org/nu/?doc=https%3A%2F%2Fweb.dev%2F does not currently show errors related to our `<img>` tags (well, it complains about `importance="high"`, but that's intentional).

I also see `w-descriptor` values for the current thumbnails for, e.g., the case studies.

A lot has changed over the last 9 months, so I am going to close this out as not being reproducible. Please let us know if we need to reopen for some reason.
