### ISSUE TITLE
Hero images are much too big

### ISSUE THREAD

**Issue by chrishtr** [GoogleChrome/web.dev#5540]
Load https://web.dev/content-visibility/ on a desktop machine. The hero image pushes the actual content into the bottom half of the page.

This is true of all articles I think (example: https://web.dev/pwa-url-handler/)

It doesn't make sense to me to have such huge hero images, especially ones that have nothing much to do with the content.

I filed this same issue previously, but can't seem to find it, so re-filing it.

**Comment by prsmahajan** [comment]
Hi, I want to work on this issue, can you suggest me ways to get started?

**Comment by robdodson** [comment]
@jimoong should we change up the page design a bit so it's a bit more like https://blog.google/products/flights-hotels/summer-guide-2021/ ?

**Comment by chrishtr** [comment]
> @jimoong should we change up the page design a bit so it's a bit more like https://blog.google/products/flights-hotels/summer-guide-2021/ ?

That one has a huge hero image also...

**Comment by robdodson** [comment]
@chrishtr i think it's pretty common across all google blogs to have large hero images (I looked into a few other examples a while back. Here's a similar one: https://material.io/blog/announcing-material-you and some sites like Medium have pretty gigantic ones https://medium.com/predict/this-long-awaited-technology-may-finally-change-the-world-ec3023a30af2

I think this comes down to a stylistic choice—personally I like the large hero images so I think we're disagreeing on a personal preference. But I do think we could reduce them a bit to allow more content to be visible.

**Comment by prsmahajan** [comment]
Hey, is there anyone to guide me?

**Comment by robdodson** [comment]
@prsmahajan thanks for volunteering. I think we need to do a bit of internal work with our UX designer before we can address this ticket.

**Comment by jimoong** [comment]
Sorry for checking in late. We can limit the width of hero image and apply similar rule like developer.chrome.com articles. Will add specifications here soon.

**Comment by prsmahajan** [comment]
Sure @robdodson
