### ISSUE TITLE
No style element present in the head for CodePen example

### ISSUE THREAD

**Issue by jmmarco** [GoogleChrome/web.dev#5549]
**Describe the bug**
For the lesson "[The Cascade](https://web.dev/learn/css/the-cascade/)" subsection "[Position and order of appearance](https://web.dev/learn/css/the-cascade/#position-and-order-of-appearance)"

For the [CodePen example](https://codepen.io/web-dot-dev/pen/xxgbLoB) you mention:
> The `<style>` element is declared in the `<head>`, while the `<link />` element is declared in the `<body>`. This means it gets more specificity than the `<style>` element"

However, the provided CodePen example doesn't have anything inside the `<head>`.

**To Reproduce**
1. Go to `https://codepen.io/web-dot-dev/pen/xxgbLoB`
2. Click on 'Settings', then select 'HTML'
3. Look for the box labeled "Stuff for `<head>`"
4. It's currently empty, but it should have a style element along with style rules as implied in the example where it states:
  > The `<style>` element is declared in the `<head>` ...

**Expected behavior**
The `<head>` element in the CodePen example should have a `<style>` element along with some style rules inside.

**Screenshots**
<img width="1552" alt="Screen Shot 2021-06-06 at 12 08 02" src="https://user-images.githubusercontent.com/3438337/120929552-de908b00-c6bf-11eb-9e7a-adaeb9b4fd64.png">

**Comment by argyleink** [comment]
Codepen will put the stuff in the CSS code area into the head as a style tag. Definitely a bit of a loopty loop. 

Closing as there's no bug, demo works as expected.

**Comment by jmmarco** [comment]
Understood @argyleink 
Thanks for taking a look!
