### ISSUE TITLE
Google Tag Manager triggers navigator.userAgent warning

### ISSUE THREAD

**Issue by tmb-github** [GoogleChrome/web.dev#5558]
Chrome 93.0.4530.5 (Official Build) dev (64-bit)
OS: Windows 8.1

**To Reproduce**
Navigate to https://thomasbrodhead.com/ and open DevTools Console. The following deprecation warning appears in the Issues Tab:

> Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
> A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. In a future version of Chrome, the amount of information available in the User Agent string will be reduced.
> To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
> Note that for performance reasons, only the first access to one of the properties is shown.
> 
The issue is triggered by GoogleTagManager code that uses `navigator.userAgent`. The team responsible for updating GoogleTagManager needs to revise the code to conform to the upcoming change, but I can't determine how to alert them. Please pass this info to the appropriate team.

**Comment by robdodson** [comment]
Unfortunately I _also_ don't know how to contact them 😅  I would suggest seeing if they have a product forum and trying to post there.
