### ISSUE TITLE
Consider ways to incorporate third-party CPU tool into site

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#556]
This tool reports impact of third-parties on CPU: https://github.com/jpvincent/3rd-party-cpu-abuser. We could look for opportunities in performance docs or in other ways to incorporate this into web.dev.

**Comment by robdodson** [comment]
To keep the bug tracker really actionable I'm going to close this issue and move it to [an ideas board](https://github.com/GoogleChrome/web.dev/projects/3) associated with this repo.
