### ISSUE TITLE
Incorrect code samples in "Building a media scroller component" article

### ISSUE THREAD

**Issue by gauravsoni119** [GoogleChrome/web.dev#5560]
**Describe the bug**
Incorrect code samples in "Building a media scroller component" article in the focus and aspect-ratio section.

**To Reproduce**
1. Go to [aspect-ratio](https://web.dev/building-a-media-scroller-component/#aspect-ratio) section.
3. Scroll down to code sample
4. See the missing `{` on `.horizontal-media-scroller figure > picture`.
5. Go to [focus](https://web.dev/building-a-media-scroller-component/#focus) section.
6. Scroll down to code sample.
7. The `display: inline-block` is on the wrong selector(`.horizontal-media-scroller`).
8. The `outline-offset: 7px` on focus.

**Expected behavior**
1. Missing`{` should be added.
2. The `display: inline-block`  should be on `& a`.
3.  The `outline-offset` on focus should be calc(var(--gap) / 4).

**Comment by una** [comment]
@argyleink ^
