### ISSUE TITLE
Podcast: about inline styles and !important statement

### ISSUE THREAD

**Issue by gunayanil** [GoogleChrome/web.dev#5562]
### What page(s) need to be updated?

https://web.dev/learn/css/the-cascade/

### Why is this update needed?

Podcast (6:59 - 7:06) Una says "Inline styles will typically always override other styles **including ` !important` statements** within your CSS". Inline styles cannot override `!important` statements in CSS.

**Comment by robdodson** [comment]
I'm not sure if we are going to be able to rerecord these podcasts... My hunch is we would either have to close this as a mistake we can't fix, or possibly add an Aside to the article that calls this out.
