### ISSUE TITLE
[Learn CSS]-[007 Sizing Units]-[Percentages]-[Second CodePen] value is wrong

### ISSUE THREAD

**Issue by cheungxi** [GoogleChrome/web.dev#5566]
**Describe the bug**
[Learn CSS]-[007 Sizing Units]-[Percentages]-[Second CodePen] **Both margin and padding are 150px.** is wrong. Because in this env， `box-sizing: border-box`. so `div.width` include `content width + padding  + border `. so `margin-top` is not `div.width` * 50%. it is `div. (content box.width)` (less than 300px) * 50%.

so should be:
```
* {box-sizing:content-box;}
```

**To Reproduce**
1. Go to 'Learn CSS'
2. Click on '007 Sizing Units'
3. Scroll down to '[Percentages]-[Second CodePen] '

**Expected behavior**
Both margin and padding are 150px.

**Screenshots**
![image](https://user-images.githubusercontent.com/11963792/121156586-679ff180-c87b-11eb-9845-ce84b4c9d319.png)

**Comment by argyleink** [comment]
codepen updated with `content-box`! 👍🏻 
verify @cheungxi?

**Comment by rachelandrew** [comment]
This was fixed by @argyleink and issue left open. Closing as have confirmed the fix.
