### ISSUE TITLE
UX on smaller devices should be improved

### ISSUE THREAD

**Issue by thamas** [GoogleChrome/web.dev#558]
I visited the page https://web.dev/fast/serve-modern-code-to-modern-browsers/codelab-serve-modern-code (coming from a Tweet of @addyosmani) using an iPhone 6 Plus and this is what I saw:

![webdev-site-iphone6plus](https://user-images.githubusercontent.com/1244043/51026600-26fafb80-158f-11e9-8b8a-fc46b4959f17.jpg)

I marked the actual post content which is scrollable with green. 
The other elements are fixed:
- the header of the site
- the title of the post
- (the footer of the browser also sticks there – I think because it does not "realise" that the content was scrolled)

On the right side, the slide-in code example / editor(?) also takes some space from content.

When I see it first there was something sticky at the bottom too (maybe cookie message?) but I did not see that next time when I was able to make the screenshot.

I feel it is not the best user experience, and the site (this type of content) should be simplified for smaller devices / narrower screens.

**Comment by robdodson** [comment]
Related to #404

**Comment by robdodson** [comment]
Going to close this to consolidate the discussion in #404
