### ISSUE TITLE
Learn CSS/012 - Spacing: Content modification in Code Pen part

### ISSUE THREAD

**Issue by phulengo** [GoogleChrome/web.dev#5588]
### What page(s) need to be updated?

https://web.dev/learn/css/spacing/#padding

### Why is this update needed?
At the padding section, in the Code Pen part, the second paragraph should be fixed as: 

> If it has a box-sizing value of **border-box** (not **content-box**) it will be 320px wide, regardless of how much padding you add.

<img width="812" alt="Screen Shot 2021-06-10 at 18 24 13" src="https://user-images.githubusercontent.com/30664920/121517214-4bd25200-ca19-11eb-8dbb-8dd921ad6a1c.png">

**Comment by argyleink** [comment]
codepen updated!
