### ISSUE TITLE
Possible error in "Learn CSS" course chapter 11 in the CodePen of the section "Using logical properties pragmatically"

### ISSUE THREAD

**Issue by remigius42** [GoogleChrome/web.dev#5598]
**Describe the bug**
The [section "Using logical properties pragmatically" of chapter 11 in the "Learn CSS" course](https://web.dev/learn/css/logical-properties/#using-logical-properties-pragmatically) features a [CodePen showing a chart](https://codepen.io/web-dot-dev/pen/zYNZNgE). The last sentence of the section states:

> The block-start sides have a red border so you can see them.

However, the CSS in the CodePen sets the color of the axis label borders to `var(--color-stroke)` which at least in my case was not red. I have created a [fork of the CodePen with the adjusted color](https://codepen.io/remigius/pen/jOBeMqr).

**To Reproduce**
1. Go to the [section "Using logical properties pragmatically" of chapter 11 in the "Learn CSS" course](https://web.dev/learn/css/logical-properties/#using-logical-properties-pragmatically).
2. Compare the color indicated in the last sentence of the section with the one used for the border in the [associated CodePen](https://codepen.io/web-dot-dev/pen/zYNZNgE).

**Expected behavior**
The color of the border in the CodePen should either be red in all environments or the text should be updated.

**Comment by argyleink** [comment]
i made it so the lines are red as the text says 👍🏻 
thanks for noticing @remigius42 🙏🏻
