### ISSUE TITLE
Trust Token demo example linked in article doesn't work

### ISSUE THREAD

**Issue by summercms** [GoogleChrome/web.dev#5599]
**Describe the bug**

The article found here: https://web.dev/trust-tokens/

Go to the section `Summary` which points to a demo. Opening the demo doesn't work!

**To Reproduce**
1. Go to https://trust-token-redeemer-demo.glitch.me/
2. Click on `Click me to continue`
3. Demo then hangs and does nothing.

Tested in **Google Chrome Version 93.0.4535.3 with flag enabled** so should work!

**Expected behavior**

Wanted to learn more about Trust Tokens API from the wonderful Google developers, but couldn't see a working demo to see what's going on in Chrome.

**Screenshots**

![image](https://user-images.githubusercontent.com/57409060/121701248-9c54b880-cac8-11eb-9b58-5c8a8ee3f58c.png)

![image](https://user-images.githubusercontent.com/57409060/121701978-5cda9c00-cac9-11eb-9da7-903a1d2454c5.png)

**Comment by devnook** [comment]
Hi @summercms , thanks for reporting!

It seems that the issue you describe is an issue with Chrome, not with with web.dev or the demo (please note the document.hasTrustedToken missing in error log). 
Please bear in mind that you're using an experimental feature on a non-stable Chrome channel.

If you'd like to report it, you can submit an issue for Chrome: https://support.google.com/chrome/answer/95315?co=GENIE.Platform%3DDesktop&hl=en
