### ISSUE TITLE
Cookie banner + PWA banner are confusing

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#560]
A couple of users on Twitter ([1](https://twitter.com/kolombiken/status/1082894994137063424), [2](https://twitter.com/WasteCleaner/status/1082794147491311626)) mentioned that the cookie banner + the "install the PWA banner" both pop up at the same time and make the initial site experience confusing.

We should see if we can get a screenshot of both of these happening at the same time and then possibly do some design work to make them less confusing.

**Comment by TimvdLippe** [comment]
I will happily take the blame for the abomination that the Dutch government invented that we now call "cookie-banner-madness"

**Comment by robdodson** [comment]
🍪🇳🇱😜

**Comment by robdodson** [comment]
On hold until we move off of devsite.
