### ISSUE TITLE
Theme support

### ISSUE THREAD

**Issue by beHitesh** [GoogleChrome/web.dev#5609]
## Provide an option to switch between dark and light themes.
I think it would be handy to have a Theme toggle for users to switch between themes.
> The current light theme wasn't a problem for me until recently, until I found the **Course for CSS **  which raised a need for me to spend significantly more time reading through pages. I did consider using a browser extension to enforce dark theme, but it did have it's own problems... _added screenshot below_.

### Alternatives I tried
We do have browser extensions these days to enforce dark themes...  but it might just over-do things in some cases and might impact reader experience.

example:  with a dark theme enforcing browser extension `Dark Reader`

![image](https://user-images.githubusercontent.com/30905951/121771325-552ffb80-cb8c-11eb-9d31-09a2238c1089.png)
https://web.dev/css-size-adjust/

which other wise looks much better with light theme...
![image](https://user-images.githubusercontent.com/30905951/121771357-8a3c4e00-cb8c-11eb-9103-c18eff87a8ff.png)

Some examples 
An example of the toggle feature from 
- https://surma.dev/
![image](https://user-images.githubusercontent.com/30905951/121771195-8d830a00-cb8b-11eb-998f-e3e55b65efe2.png)
- https://epicreact.dev/
![image](https://user-images.githubusercontent.com/30905951/121771452-18b0cf80-cb8d-11eb-93d1-3560a8f2170e.png)

**Comment by beaufortfrancois** [comment]
FYI @tomayac

**Comment by tomayac** [comment]
The core web.dev team needs to decide if they want this. I’d be down for it, but it’s not a trivial task given the current architecture. Google (well, mostly I) maintains [`<dark-mode-toggle>`](https://github.com/GoogleChromeLabs/dark-mode-toggle), which can help with the toggling once the CSS is there.

**Comment by robdodson** [comment]
We're currently working on this as part of a bigger design system clean up. Hoping to have something to show in Q3.

**Comment by robdodson** [comment]
I'm going to close this as we're tracking the work in #5374
