### ISSUE TITLE
(Learn CSS) : Button OnClick Alert doesn't work

### ISSUE THREAD

**Issue by tinfoil-knight** [GoogleChrome/web.dev#5615]
**Describe the bug**
In the [Matching specificity](https://codepen.io/web-dot-dev/pen/abpoxdR) codepen, clicking the button with an `onclick="alert('hello')"` doesn't do anything while on **web.dev**.

Note: The button works on codepen.io though.

**To Reproduce**
1. Go to https://web.dev/learn/css/specificity/#pragmatically-increasing-specificity
2. In the codepen under that section, click the button.
3. The button won't cause an alert.

**Expected behavior**
An alert pop-up should appear on clicking the button with the `onclick` handler.

Possible Cause: https://blog.codepen.io/2014/02/17/can-iframes-annoying-free/

From the article:
```
Attempt to block alerts, confirms, geolocation permissions, and other browser modal popups.
```

Edit: All Codepens on the [Specificty page](https://web.dev/learn/css/specificity/) with the `onclick` handler have the same behaviour.

**Comment by una** [comment]
This is an `iframe` feature/issue. However, you can open the demo and the button will popup there.
