### ISSUE TITLE
Possible minor issues in "Learn CSS" course chapter 12 about spacing

### ISSUE THREAD

**Issue by remigius42** [GoogleChrome/web.dev#5618]
**Describe the bug**
This bug is about three possible minor issues within [chapter 12 of the "Learn CSS" course](https://web.dev/learn/css/spacing/):

- The [first commit](https://github.com/GoogleChrome/web.dev/pull/5619/commits/3f79058d3e9282193e0a3c02701be19b5ba2d3f8) of the associated pull request removes the solidi in the HTML examples to be consistent with the aside further down in the document, the [MDN HTML tutorial referenced](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML) in [chapter 0](https://web.dev/learn/css/) as well as [(probably retired) Google HTML styleguide](https://google.github.io/styleguide/htmlcssguide.html#Document_Type). Note that if this commit is kept as it is, the [related CodePen](https://codepen.io/web-dot-dev/pen/dyNRJQg) should be adjusted as well.
- The [second commit](https://github.com/GoogleChrome/web.dev/pull/5619/commits/c6dd561a4e6ded5eec1d69a08bba36003645f7b0) changes the `inset` property to its logical counterparts, analogous to the [second commit](https://github.com/GoogleChrome/web.dev/pull/5601/commits/35566b42b5fe79978acd066206acb790e30362cd) of the already closed issue #5600.
- The [last commit](https://github.com/GoogleChrome/web.dev/pull/5619/commits/99f9e67fa690e64a2077090eac8aefc89979d4bd) fixes a probably unintended word split causing a typo. Please note that I am unfamiliar with the typographic guidelines used on this website, which is why I am not sure, whether the dashes should be separated with spaces. Assuming that the intended result is em dashes, I opted to go without spaces, because this seems to be more common.

**To Reproduce**
1. Go to https://web.dev/learn/css/logical-properties/
2. Verify the three issues pointed out in the description.

**Expected behavior**
- It has been decided which of the commits / changes should be kept or whether they need further corrections.
- If the [first commit](https://github.com/GoogleChrome/web.dev/pull/5619/commits/3f79058d3e9282193e0a3c02701be19b5ba2d3f8) is kept as it is, the [related CodePen](https://codepen.io/web-dot-dev/pen/dyNRJQg) has been adjusted as well.

**Comment by robdodson** [comment]
@argyleink are you cool taking a look?
