### ISSUE TITLE
Let authors set twitter card image/description

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#562]
It'd be nice to let authors optionally set a Twitter card image and short description for their posts.

**Comment by Malvoz** [comment]
For sharing measurements (https://web.dev/measure) or as a part of https://web.dev/discoverable you mean?

Consider using Open Graph Protocol (http://ogp.me/) instead? [Twitter falls back to use OGP](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#twitter-cards-and-open-graph) if no twitter card markup is found:

> When the Twitter card processor looks for tags on a page, it first checks for the Twitter-specific property, and if not present, falls back to the supported Open Graph property.

**Comment by robdodson** [comment]
As part of the guides, like web.dev/discoverable. When folks tweet out that they wrote a new guide, it might be nice for them to have a custom screen shot.

We do use the open graph protocol but noticed some issues with it not displaying our twitter cards so we switched to using both.

**Comment by robdodson** [comment]
I think this is on hold until we move off of devsite.
