### ISSUE TITLE
Blog landing page shows other than publish order

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#5636]
**Describe the bug**
When multiple articles are published on the same day, the landing page doesn't show the articles in the order they were committed. The image below shows this. The first two articles show were up for several hours before my PR was merged. 

**On smaller screens, readers may never know that a new article was published.**

![image](https://user-images.githubusercontent.com/8204171/122116059-ff509300-cdd9-11eb-80de-22b80c7eb7be.png)

**Expected behavior**

The first article listed should always be the last article published regardless of publish date.

**Comment by devnook** [comment]
The order of the posts is determined by their published date (field in the frontmatter), and then by the title. If you want to have full control over the order, you can use a more granular date, including the time bit, e.g.: 2021-06-15T23:59:59.1Z
