### ISSUE TITLE
Storage Foundation API article: alert shown on browsers without support

### ISSUE THREAD

**Issue by myakura** [GoogleChrome/web.dev#5648]
**Describe the bug**

The article (technically the demo hosted on glitch) shows an alert to browsers that do not support the API.

**To Reproduce**
1. Go to https://web.dev/storage-foundation/ using non-Chromium browsers
2. wait for a few seconds to load

**Expected behavior**
non-Chromium-browser users should be able to scroll and read the content without clicking on the button on the alert popup.

**Screenshots**
![Screenshot: Firefox showing alert from the glitch demo](https://user-images.githubusercontent.com/413984/122238823-674aca80-cefb-11eb-9a9f-06b4e1033443.png)

**Comment by robdodson** [comment]
yeah i agree, i think it would be a better experience for the Glitch embed to display some text saying that it's not supported. @tomayac would you be able to update it to do that?

**Comment by tomayac** [comment]
This was fixed within a few hours after the article went live, but there seems to have been some caching issue. I have just verified on a fresh Firefox profile that it's indeed not an issue anymore.
