### ISSUE TITLE
Add recommendations for table content and formatting to the handbook

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/web.dev#5654]
Some tables on the site use symbols such as ✔ | ✘ or emoji to signify Yes/No. These symbols are not semantical and don't convey correct meaning to people who use screen readers. ✘ specifically isn't even read out loud.

Example here: [https://web.dev/handbook/web-dev-components/](https://web.dev/handbook/web-dev-components/)

To do:

- [ ] Review tables that are already on the site
- [ ] Write down some guidance in the handbook
- [ ] Consider adding some CSS classes or creating table components with red/green filled cells to visually highlight those Yes/No tables. (Similar to MDN and caniuse table formatting.)

**Comment by robdodson** [comment]
A couple thoughts:

I think if folks want to use these characters they may be able to add an aria-label to the `td`.

```html
<td aria-label="not supported">✘</td>
```

or maybe a span with the [`w-visually-hidden` class](https://github.com/GoogleChrome/web.dev/blob/main/src/styles/utilities/_visually-hidden.scss).

```html
<td><span class="w-visually-hidden">not supported</span>✘</td>
```

In either case we need to be mindful that we're translating either the aria-label or the span when we do localization.
