### ISSUE TITLE
content: Update the item titles of 'What you'll learn' section of every collection's landing page

### ISSUE THREAD

**Issue by codebriefcase** [GoogleChrome/web.dev#5670]
* Use this template to request updates to existing content.
* Delete any fields that aren't relevant to your issue. 
* Update the title of this issue with a brief summary of the work to be done.

### What page(s) need to be updated?
All collection landing pages that can be accessed through https://web.dev/learn , except LearnCss

### Why is this update needed?
The title **(What you'll learn)** doesn't actually match the list item that follows. According to the heading text, users will expect to see all things that they will actually learn if they read the entire collection. But the existing list items show the headings of all sections that exist in that collection. Ideally, it should show the actual topics that were mentioned in that collection. 

Please find the attached image -
![image](https://user-images.githubusercontent.com/61384771/122599926-b5db9e80-d08c-11eb-959a-6015c8c605a2.png)

### What is expected?
![image](https://user-images.githubusercontent.com/61384771/122600372-4ca85b00-d08d-11eb-8ef1-ec0d9a16fb52.png)

_I would love to contribute. Please let me know how can I contribute to this codebase!_

**Comment by robdodson** [comment]
I don't think that we can change this to be a list of topics because I think it will be difficult to keep that in sync as new content is added (some authors will remember, others will forget).

Instead of the title "What you'll learn", it may be better to change that to "On this page" or "Sections". Just some way to indicate that this is really a list of headings.

**Comment by codebriefcase** [comment]
I agree @robdodson

**Comment by codebriefcase** [comment]
@robdodson  Should I raise a PR that replaces "What you'll learn" with "Topics in this collection"?
Please let me know if you have any better suggestions for the title text.

**Comment by robdodson** [comment]
@codebriefcase Maybe we go with "Table of contents" ? That's what we use on developer.chrome.com

![image](https://user-images.githubusercontent.com/1066253/124336351-8b8ce500-db52-11eb-9f90-a0e6560c9411.png)

**Comment by codebriefcase** [comment]
> @codebriefcase Maybe we go with "Table of contents" ? That's what we use on developer.chrome.com
> 
> ![image](https://user-images.githubusercontent.com/1066253/124336351-8b8ce500-db52-11eb-9f90-a0e6560c9411.png)

That seems perfect to me. Will raise a PR for the same
