### ISSUE TITLE
[Learn CSS] Typo in Layout lesson (How to make PR on CodePen?)

### ISSUE THREAD

**Issue by vegerot** [GoogleChrome/web.dev#5685]
**Describe the bug**
On the layout lesson here https://web.dev/learn/css/layout/#flexbox-and-grid , there is a typo in the [CodePen](https://codepen.io/web-dot-dev/pen/jOyWLmg)

It says "with an around their sibling elements" when it should say "with and around their sibling elements"

**Screenshots**
<img width="878" alt="image" src="https://user-images.githubusercontent.com/5297725/122819723-ce280500-d2a8-11eb-9ab3-d930b57d55a1.png">

I tried to find a way to make a PR on the CodePen itself, but couldn't find a good way to

**Comment by MichaelSolati** [comment]
@argyleink or @una I'm not sure who has access to the codepen, but would either of you mind making this small fix?

**Comment by argyleink** [comment]
done!
