### ISSUE TITLE
[Learn CSS]: Update grid justify and align example CodePen to be more helpful

### ISSUE THREAD

**Issue by vegerot** [GoogleChrome/web.dev#5702]
### What page(s) need to be updated?

https://web.dev/learn/css/grid/#distributing-extra-space

https://codepen.io/web-dot-dev/pen/rNjjMVd

### Change

Change `grid-template-columns` to `grid-template-columns: auto auto auto;`.

### Explanation

With the current `.container` style, it's not clear the difference between `justify-content: stretch` and `justify-content: start`.  The proposed change will show how `stretch` and `start` differ.

### Why is this update needed?

To make the difference between `justify-content: {stretch,start}` more obvious

**Comment by vegerot** [comment]
preemptively pinging @argyleink and @una because of https://github.com/GoogleChrome/web.dev/issues/5685#issuecomment-866393964

**Comment by argyleink** [comment]
i like it, i updated the codepen, agree it's much easier now to see those alignments 👍🏻
