### ISSUE TITLE
[Learn CSS] Confusing Psuedo-element codepen

### ISSUE THREAD

**Issue by vegerot** [GoogleChrome/web.dev#5710]
If I am misunderstanding the point of this CodePen, please feel free to close.

### What page(s) need to be updated?

https://web.dev/learn/css/pseudo-elements/#::first-line
https://codepen.io/web-dot-dev/pen/vYgZVaO

### Explanation

The description states that "only if the element with `::first-line` applied has a `display` value of `block`, `inline-block`, `list-item`, `table-caption` or `table-cell`."

However I was confused why in the example you overwrite `p` to have `display: inline` and the pseudo-element still applies.  I think to make the codepen easier you should wrap the `p` in an `article` (or a more appropriate semantic element) to make things clearer.

### Proposed change

```html
<article>
<p>The first line of this paragraph is <code>goldenrod</code>, which is a <em>great</em> color. Here is some lipsum to fill it out Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Sed posuere consectetur est at lobortis.</p>
</article>
```

```css
p {
  font-size: 1.2em;
}

p::first-line {
  color: goldenrod;
  font-weight: bold;
}
```

**Comment by vegerot** [comment]
Adding @argyleink and @una who have CodePen access

**Comment by argyleink** [comment]
nice, thank you! [codepen](https://codepen.io/web-dot-dev/pen/vYgZVaO) updated and `display: inline` removed 👍🏻
