### ISSUE TITLE
content: Update CLS article to mention prefers-reduced-motion under Animation section

### ISSUE THREAD

**Issue by CharlesBelov** [GoogleChrome/web.dev#5720]
### What page(s) need to be updated?

https://web.dev/cls/

### Why is this update needed?

Page recommends animation but doesn't mention prefers-reduced-motion. This could result in sites incorporating animation without allowing that some site visitors don't want animation and it can make them feel ill.

### What's the deadline?

Not applicable, although it would be nice for this to be done before Google uses CLS to impact search rankings.

#### Is it a hard deadline?

No

### Content

From:

Animations and transitions #

Animations and transitions, when done well, are a great way to update content on the page without surprising the user. Content that shifts abruptly and unexpectedly on the page almost always creates a bad user experience. But content that moves gradually and naturally from one position to the next can often help the user better understand what's going on, and guide them between state changes.

To:

Animations and transitions #

Animations and transitions, when done well, are a great way to update content on the page without surprising the user. Content that shifts abruptly and unexpectedly on the page almost always creates a bad user experience. But content that moves gradually and naturally from one position to the next can often help the user better understand what's going on, and guide them between state changes.

Be sure to respect prefers-reduced-motion browser settings, as some site visitors can experience ill effects or attention issues from animation.

**Comment by NegiAkash890** [comment]
Can, I can help here ?

**Comment by mihajlija** [comment]
@NegiAkash890 Yes, thank you! Please fork the repo, open a PR and include a link to the post about this feature https://web.dev/prefers-reduced-motion/. The file you want to edit is here: https://github.com/GoogleChrome/web.dev/blob/50c4939fe02d08e25d2a47978b8432b0ad6610ff/src/site/content/en/metrics/cls/index.md
