### ISSUE TITLE
content: review conflicting statements about Safari in the "Storage for the web" article

### ISSUE THREAD

**Issue by fedetibaldo** [GoogleChrome/web.dev#5746]
### What page(s) need to be updated?

https://web.dev/storage-for-the-web/

### Why is this update needed?

The article provides two conflicting statements about Safari's storage quota.

At the fourth bullet point of the ["how much"](https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/blog/storage-for-the-web/index.md#how-much-can-i-store--how-much-) list, it says:
> Safari (both desktop and mobile) appears to allow about 1GB. When the limit is reached, Safari will prompt the user, increasing the limit in 200MB increments.

While on the last paragraph of the same section, it reports:
> [Safari] prompts at 750MB, asking permission to store up to 1.1GB. If an origin attempts to use more than its allotted quota, further attempts to write data will fail.

### What's the deadline?

I don't think it applies to this issue.

**Comment by robdodson** [comment]
Assigning to @petele to take a look

**Comment by fedetibaldo** [comment]
Is there a known template to test Safari's current limits? If so, I could gather more data myself. Otherwise, is there a record of how the initial reading was done?
