### ISSUE TITLE
content: compute pressure API doc doesn't mention which platforms are ready in origin trial

### ISSUE THREAD

**Issue by hector-ayala** [GoogleChrome/web.dev#5747]
### What page(s) need to be updated?

https://web.dev/compute-pressure/#try-a-demo

### Why is this update needed?

The article highlights that the origin trial is available on Chrome 92+. But it doesn't mention that it is only ready for testing on Chrome OS & Linux [1] while the Mac [2] and Windows [3] implementations will follow.

Not sure if it is practical to keep the article up to date with the release of the additional platforms. But it may help developers who may assume that support on all platforms was added at the same time. Thanks!

[1] https://bugs.chromium.org/p/chromium/issues/detail?id=1183596
[2] https://bugs.chromium.org/p/chromium/issues/detail?id=1183598
[3] https://bugs.chromium.org/p/chromium/issues/detail?id=1183597

**Comment by robdodson** [comment]
@jeffposnick wdyt?

**Comment by jeffposnick** [comment]
I'm not sure what's up with those tracking bugs, but my understanding is that the Compute Pressure API should be available during the origin trial on platforms other than Chrome OS & Linux.

I just visited https://googlechrome.github.io/samples/compute-pressure/index.html using Chrome 93 on macOS, and the demo worked:

![Screen Shot 2021-07-08 at 10 59 28 AM](https://user-images.githubusercontent.com/1749548/124944907-b3a99780-dfdb-11eb-972d-670c3d77e646.png)

It might be worth filing a bug via https://crbug.com/new if you're using Chrome 92+ on a specific platform and you see that the demo doesn't work.
