### ISSUE TITLE
Improve images/video pipeline.

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web.dev#575]
**Page Affected:** https://web.dev/fast/incorporate-performance-budgets-into-your-build-tools, https://web.dev/fast/using-lighthouse-ci-to-set-a-performance-budget 

**What needs to be done?** 

There appears to be an inconsistent resolution in the images used in different guides and tutorials. Have we considered providing a guideline for screenshots/images to help ensure quality is consistent?

**Comment by robdodson** [comment]
@addyosmani I wrote up a little something in our [wiki](https://github.com/GoogleChrome/web.dev/wiki/How-to-write-a-guide#images) but it may be a bit buried there.

Also DevSite runs its own image compression against our assets so I've been telling folks to upload them unoptimized and just let DevSite do its thing. I don't know what settings they use though—they might be aggressive.

**Comment by robdodson** [comment]
Updated issue description.

We need a better pipeline for uploading and sizing images.

**Comment by robdodson** [comment]
Some nice features would be:

- Convert images to webp and serve to supporting browsers.
- Resize images so they're max 800px if they're content and 1600px if they're a hero.
- Automatic srcset (this seems like it could be tricky but I'm not sure how hard it is).

**Comment by robdodson** [comment]
Going to close as our migration to imgix should help solve this.
