### ISSUE TITLE
Invalid parameter 33% resize with ImageMagick CLI

### ISSUE THREAD

**Issue by larsmars** [GoogleChrome/web.dev#576]
**Page Affected:** https://web.dev/fast/serve-responsive-images

**What needs to be done?**
ImageMagick instructions does not work.

convert -resize 33% flower.jpg flower-small.jpg

ImageMagick version:
**ImageMagick-7.0.8-24-Q16-x64-dll**

Node -v:
**v10.9.0**

Gives error:
Invalid Parameter - 33%

Test img file:
https://en.wikipedia.org/wiki/File:Oxalis_tetraphylla_flower.jpg
(rename it to flower.jpg)

Command in terminal:
```
C:\source>convert -resize 33% flower.jpg flower-small.jpg
Invalid Parameter - 33%
```

```
C:\source>convert flower.jpg -resize 300x200 flower-small.jpg
Invalid Parameter - -resize
```

**Comment by larsmars** [comment]
You need to manualy include legacy utilities, this should be included in the recommendations for use of ImageMagick

**Comment by robdodson** [comment]
@khempenius do you think we should update the post?

**Comment by khempenius** [comment]
Ah, it looks like this command breaks on Windows machines because Windows has it's own convert.exe which it tries to execute instead.

I think running this command instead is the simplest fix:
magick convert -resize 33% flower.jpg flower-small.jpg

@larsmars does this fix the issue for you?

@robdodson If this works, I'll update the docs.

**Comment by robdodson** [comment]
@larsmars friendly ping on this?

**Comment by robdodson** [comment]
@khempenius I'm not sure if we're going to get a response but maybe we should go ahead and add your snippet to the codelab to be safe. Would you be ok opening a PR for that?

**Comment by larsmars** [comment]
Thank you, update with snippets sounds like a plan.

**Comment by robdodson** [comment]
@khempenius would you be cool sending in a PR for the snippet change?
