### ISSUE TITLE
Fonts with font-display optional are not preloaded

### ISSUE THREAD

**Issue by tannerdolby** [GoogleChrome/web.dev#5760]
Running a Lighthouse audit on https://web.dev/serve-responsive-images/ reveals a score of 94 in "Best Practices" as many fonts have `font-display: optional` and aren't preloaded. Could the fonts be preloaded by adding `<link rel="preload">` to get a score of 100 in best practices?

I couldn't find those fonts within document metadata for the page, so I'm not entirely sure where they are being placed in HTML or loaded from.

- …regular/cyrillic.woff2(web.dev)
- …regular/greek.woff2(web.dev)
- …regular/vietnamese.woff2(web.dev)
- …regular/latin-ext.woff2(web.dev)
- …bold/cyrillic.woff2(web.dev)
- …bold/greek.woff2(web.dev)
- …bold/vietnamese.woff2(web.dev)
- …bold/latin-ext.woff2(web.dev)

[Preventing layout shifting and FOIT by preloading optional fonts](https://web.dev/preload-optional-fonts/?utm_source=lighthouse&utm_medium=devtools)

_Screenshot of Best practices section of Lighthouse Audit_
<img width="784" alt="Screen Shot 2021-07-05 at 5 55 41 PM" src="https://user-images.githubusercontent.com/48612525/124527700-12dc9180-ddbb-11eb-8693-d09473be0d95.png">

**Comment by robdodson** [comment]
@tannerdolby can you share which version of chrome you're using and which operating system?

I'm surprised that it's trying to load all of those fonts. When I test the site on my machine and separately using PageSpeed Insights, I don't see that list of fonts or that warning.

**Comment by tannerdolby** [comment]
> @tannerdolby can you share which version of chrome you're using and which operating system?

Yeah, sure thing! Chrome is up-to-date and I'm on MacOS High Sierra, details below:

Chrome: Version 92.0.4515.107 (Official Build) (x86_64)
OS: macOS High Sierra 10.13.6

I was surprised when I saw it too. I just ran a test with PageSpeed and I don't receive the list of fonts or warning like you mentioned. But after running a fresh lighthouse audit, it seems to be throwing the warning again.

<img width="1280" alt="Screen Shot 2021-07-26 at 5 02 09 PM" src="https://user-images.githubusercontent.com/48612525/127074341-60e9ce62-168b-4d4c-b1f1-eea02a467170.png">

**Comment by robdodson** [comment]
@tannerdolby just curious, do you have any flags enabled in chrome://flags ?

**Comment by robdodson** [comment]
@housseindjirdeh it's true that we're not preloading the fonts that tannerdolby mentions. Those are our cyrillic and vietnamese versions of google sans I believe. Do you know if we should preload _every_ font face possible? I was nervous about doing that in case it cause an unintended performance issue.

**Comment by tannerdolby** [comment]
> just curious, do you have any flags enabled in chrome://flags ?

I had a look through the entire list (as there wasn't an easy way to filter between "enabled", "default" etc) and it looks like there are 5 flags enabled. The rest are mostly default and some disabled.

<img width="747" alt="Screen Shot 2021-08-12 at 4 13 08 PM" src="https://user-images.githubusercontent.com/48612525/129281646-239168dc-89ad-458b-bc8a-28c8de66a465.png">
<img width="751" alt="Screen Shot 2021-08-12 at 4 13 02 PM" src="https://user-images.githubusercontent.com/48612525/129281653-77868d9d-48c8-4a4f-adfa-e15f272bc9ef.png">
<img width="735" alt="Screen Shot 2021-08-12 at 4 12 53 PM" src="https://user-images.githubusercontent.com/48612525/129281659-fce11444-3e4c-460b-ae93-19c180c7460e.png">
<img width="736" alt="Screen Shot 2021-08-12 at 4 12 44 PM" src="https://user-images.githubusercontent.com/48612525/129281664-a24f7573-aa59-43d2-a6d3-9e0e756b9ed3.png">

**Comment by robdodson** [comment]
hm yeah I doubt any of those would cause weird font loading behavior. I'll keep investigating.

**Comment by brendankenny** [comment]
hi @tannerdolby, I believe this is https://github.com/GoogleChrome/lighthouse/issues/11960

Lots of stuff in that thread if you want to dig in :)

For now this audit has been disabled pending the actions in https://github.com/GoogleChrome/lighthouse/issues/11960#issuecomment-860835674. You'll need Chrome 93+ (currently in Beta) or Canary to get a version of Lighthouse with that updated, though.

**Comment by tannerdolby** [comment]
hi @brendankenny !

Ok thanks, I will dig into [GoogleChrome/lighthouse#11960](https://github.com/GoogleChrome/lighthouse/issues/11960) and go from there :)

> For now this audit has been disabled pending the actions in GoogleChrome/lighthouse#11960 (comment). You'll need Chrome 93+ (currently in Beta) or Canary to get a version of Lighthouse with that updated, though.

Ah i see, ok got it!

**Comment by robdodson** [comment]
thanks @brendankenny. i'm going to close this issue if that's ok
