### ISSUE TITLE
CLS article has CLS. Oh the irony.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#5766]
This article has some CLS on mobile.
https://web.dev/telegraph/

I think it's because there is some element causing horizontal scroll. When you scroll down on mobile, the appearance of the horizontal scroll bar causes the header to shift up.

**Comment by beaufortfrancois** [comment]
The issue seems to be caused by large margins in the "Stats" component.

![image](https://user-images.githubusercontent.com/634478/124734118-1be17600-df15-11eb-870c-ee2f4813b834.png)

**Comment by beaufortfrancois** [comment]
One quick way to fix it is to set it to `margin: 24px -24px;` instead of `margin: 32px -32px;`

**Comment by tannerdolby** [comment]
> I think it's because there is some element causing horizontal scroll. When you scroll down on mobile, the appearance of the horizontal scroll bar causes the header to shift up.

I was able to reproduce this on mobile and noticed the horizontal scroll bar appear. This behavior doesn't happen for other pages on the web.dev blog like https://web.dev/webassembly-threads which makes me think the element causing horizontal overflow is not intended.

**Comment by tannerdolby** [comment]
Confirmed that the overflow and scrollbar no longer appear on mobile after reducing the `margin`.

https://deploy-preview-5806--web-dev-staging.netlify.app/telegraph/
