### ISSUE TITLE
[Learn CSS] - [012-Spacing] - [Margin] Incorrect margin calculation in code pen example

### ISSUE THREAD

**Issue by convict-git** [GoogleChrome/web.dev#5769]
**Describe the bug**
[https://web.dev/learn/css/spacing/#margin](https://web.dev/learn/css/spacing/#margin)
The second code example which states 

> "This means that if your element's containing block has a width of 250px and your element has a margin value of 20%: each side of your element will have a computed margin of 50px."

 is true if the container block either didn't have a `border` or has `box-sizing` property overridden to `content-box`.

Currently the calculations come out wrong giving `margin` as `49.549px` rather than `50px`.

**To Reproduce**
1. Go to [https://web.dev/learn/css/spacing/#margin](https://web.dev/learn/css/spacing/#margin), and view the result of the second code pen in this section.
2. Try Chrome Tools to checkout the computed size of `my-element`.
3. See error

**Expected behavior**
As mentioned earlier, expected margin size should be `50px` rather than `49.549px`

**Screenshots**

<img width="668" alt="Screenshot 2021-07-07 at 6 18 39 PM" src="https://user-images.githubusercontent.com/34399448/124761778-c70f2100-df4f-11eb-820c-dc4bd654d026.png">

**Comment by convict-git** [comment]
**One quick way to resolve**

```diff
.container {
+  box-sizing: content-box;
  background: var(--color-primary-x-light);
  border: 1px solid var(--color-primary);
}
```

<img width="605" alt="Screenshot 2021-07-07 at 6 37 32 PM" src="https://user-images.githubusercontent.com/34399448/124764332-764cf780-df52-11eb-8a71-24bc9ae0f56c.png">

**Comment by tannerdolby** [comment]
Indeed the elements containing block has a width of 250px so 20% of 250 does equal 50. And as stated above,

> ...left/right margins are 50 if the container block either didn't have a `border` or has `box-sizing` property overridden to content-box.

To make sure the default CSS box-sizing behavior is used, adding `box-sizing: content-box` will do the trick. This way, the elements declared width of 250px is the size of the content-box and the width of any `border` or `padding` which is rendered with the final width, whereas with `border-box` any border or padding you add will make the content box shrink to absorb that extra width. The CodePen example just needs to be updated.

**Comment by argyleink** [comment]
> The CodePen example just needs `box-sizing: content-box` added to the `.container` style 

done! 👍🏻

**Comment by tannerdolby** [comment]
Excellent! I reckon this is ready to be closed then.
