### ISSUE TITLE
Unexpected 'NetworkError when attempting to fetch resource' error

### ISSUE THREAD

**Issue by danielbachhuber** [GoogleChrome/web.dev#5771]
**Describe the bug**

When I run web.dev/measure against `https://pinchofyum.com/recipes/dinner`, I see an unexpected 'NetworkError when attempting to fetch resource' error:

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/36432/124785624-dbc1c980-defb-11eb-8735-d2bbbe062f0b.png">

I'd expect to see more diagnostic information so I could understand/fix the issue. As it stands, I have no idea what actions I should take to get web.dev/measure to run successfully.

The site is hosted on WP Engine and uses Cloudflare's APO product.

**Comment by samthor** [comment]
We use an App Engine instance hosted in Google's us-central1 location to try to hit your domain. The request to that service seems to fail to complete. (I can get the logs from that, but it's hard, since it obviously get lots of requests.) Confusingly, hitting your top-level domain seems to work for me.

Not an answer, just working through debugging steps.

**Comment by danielbachhuber** [comment]
> The request to that service seems to fail to complete. (I can get the logs from that, but it's hard, since it obviously get lots of requests.)

Would it be possible to render the entire response in the browser? I'm curious whether Cloudflare is actually responding, and might be including additional detail.

> Confusingly, hitting your top-level domain seems to work for me.

Yeah, the site loads fine. It's the request from the App Engine instance that's failing.

**Comment by robdodson** [comment]
I ran the site through pagespeed insights (which is what web.dev/measure uses under the hood) and it took a very long time to give a result. It came back with a performance score of 19.
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpinchofyum.com%2Frecipes%2Fdinner

![image](https://user-images.githubusercontent.com/1066253/127071389-fc1244c9-6378-4957-98d3-878fd0f83b24.png)

I think we have a timeout set on our API call to pagespeed insights, so what may be happening is PSI is taking too long to audit the page and our request just times out. I visited the page and noticed the spinner is going for a very long time in the browser tab and it seems like there's a lot of network activity (around 5.7MB were transferred when I visited) and a lot of JS execution blocking the main thread. I think addressing the issues highlighted by PSI will make it so web.dev works again.

**Comment by danielbachhuber** [comment]
> I visited the page and noticed the spinner is going for a very long time in the browser tab and it seems like there's a lot of network activity (around 5.7MB were transferred when I visited) and a lot of JS execution blocking the main thread. I think addressing the issues highlighted by PSI will make it so web.dev works again.

Ah, this is probably the ad network activity.

> I think we have a timeout set on our API call to pagespeed insights, so what may be happening is PSI is taking too long to audit the page and our request just times out.

This makes sense. Thanks for your help with diagnosing!
