### ISSUE TITLE
Publishing Modern Javascript uses AMD output format in Rollup example but doesn't expand on AMD loading

### ISSUE THREAD

**Issue by dhavalgshah** [GoogleChrome/web.dev#5774]
### What page(s) need to be updated?
[Publishing Modern Javascript ](https://github.com/GoogleChrome/web.dev/blob/4dcf0045fcf3da25f67df2904854bb93ae82ba19/src/site/content/en/fast/publish-modern-javascript/index.md#rollup)

Provide a list of URLs.
https://web.dev/publish-modern-javascript/

### Why is this update needed?
AMD format is not a native module system for browser and does require external loader. This loader either can be prepended to the given entrypoint or loaded externally using `script` tags. However, this is not obvious to most developers. And article doesn't not clarify that as well.

One would simply copy the example and think that their code will work in legacy browsers. With deadlines, hundred different tasks, a few dozen combinations of browsers x devices to test on, and lack of access to these legacy browsers it is not uncommon to see developers skipping to actually test these.

This happened in a project I'm helping with. And when I took a small survey, hardly anyone knew about AMD and how to work with it. I guess, webpack has spoiled us well in this area.

### What should be updated?

0. Make it clear that AMD is not supported by browser like ESM.
1. Explain module system in a separate article and link to it.
2. Link to AMD module loaders and maybe to [@surma/rollup-plugin-off-main-thread](https://github.com/surma/rollup-plugin-off-main-thread)

OR

Use SystemJS output format in the example and link to systemjs loader. It would be much more production ready, easy to find help with, and will be a great DX compared to any AMD ecosystem which is a bit confusing at this time. It is used in Rollup documentation and [example repository](https://github.com/rollup/rollup-starter-code-splitting) on code splitting and differential loading.

----
Aside: When we start to think that in most web apps we tend to load many non-js dependencies like CSS & images as well in our modules. That also has to be accounted somewhere.

**Comment by developit** [comment]
Ah - took me a minute to realize which part of the article this was in reference to. You're absolutely right, the [example Rollup configuration](https://web.dev/publish-modern-javascript/#@rollupplugin-babel) given is incomplete and could be misleading. Moving it to SystemJS or adding a plugin/example of how to do AMD loading sounds like the right plan.

**Comment by dhavalgshah** [comment]
I can send a PR. What would be the approach would you suggest to take - SystemJS or AMD plugin example?

**Comment by robdodson** [comment]
@developit any thoughts?

**Comment by radum** [comment]
IMHO using AMD with a plugin raises complexity of the example. SystemJS seems to be the right way to present them.

**Comment by developit** [comment]
@dhavalgshah @radum yes, SystemJS for the fallback would be best here. Happy to review - ping me if you open a PR!

**Comment by AaronForinton** [comment]
Just to reiterate this ticket is looking for the following code sample to be corrected/completed:

`// rollup.config.js
import {getBabelOutputPlugin} from '@rollup/plugin-babel';

export default {
  input: 'src/index.js',
  output: [
    // modern bundles:
    {
      format: 'es',
      plugins: [
        getBabelOutputPlugin({
          presets: [
            [
              '@babel/preset-env',
              {
                targets: {esmodules: true},
                bugfixes: true,
                loose: true,
              },
            ],
          ],
        }),
      ],
    },
    // legacy (ES5) bundles:
    {
      format: 'amd',
      entryFileNames: '[name].legacy.js',
      chunkFileNames: '[name]-[hash].legacy.js',
      plugins: [
        getBabelOutputPlugin({
          presets: ['@babel/preset-env'],
        }),
      ],
    },
  ],
};`

**Comment by housseindjirdeh** [comment]
@dhavalgshah Long overdue, but would you still be willing to submit a PR to improve this? I'm no rollup expert, but I assume that we can update this to a config that's similar to what [Lit](https://lit.dev/docs/tools/production/#modern-only-build:~:text=//%20Legacy%20JS%20bundles%20(ES5%20compilation%20and%20SystemJS%20module%20output)) does for legacy SystemJs module output.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new (not github-based) platform  and so we’ll fix this over there. I’ve moved the issue to our new issue tracker and you can see it at https://issuetracker.google.com/issues/298540703
