### ISSUE TITLE
content.js drag/drop error: Cannot read property 'isFile' of null

### ISSUE THREAD

**Issue by Vermilion755** [GoogleChrome/web.dev#5796]
I can't tell if this is the right github repository, so please direct me if it's not. 

The implementation for JavaScript drag/drop is producing an error in Chrome only. See the codepen I've linked and attempt to drag one square onto the other. Everything seems to work fine, but a console error appears saying "content.js:21 Uncaught TypeError: Cannot read property 'isFile' of null". However, no file transfer is being attempted. The text is transferred via the event.dataTransfer object as intended, but content.js seems to error out because calling fileObjects[i].webkitGetAsEntry() returns null. I am not trying to transfer files, just text, per the drag/drop specification. Everything works fine, but this console error shows up seemingly because it's assuming I'm transferring files. https://codepen.io/Grymlot/pen/vYmgNEm

**Comment by MichaelSolati** [comment]
Issues for implementing code or looking for help with code is likely better suited for [StackOverflow](https://stackoverflow.com/). I'd recommend asking this there.

**Comment by Vermilion755** [comment]
> Issues for implementing code or looking for help with code is likely better suited for [StackOverflow](https://stackoverflow.com/). I'd recommend asking this there.

Is that what you think I'm doing? I tried to explain that I'm following the standard instructions for using drag/drop and it works in other browsers just fine. Perhaps you think content.js is my script? It seems to be coming from a built in chrome extension that I didn't install. I will post to StackOverflow as well, but my goal was to submit a bug report to whoever developed this content.js chrome extension.

**Comment by Vermilion755** [comment]
Update: I determined the chrome extension content.js is coming from is the Cyberhaven Security extension my company has installed. I'll find their bug submission process. Thanks, and sorry to waste your time!
