### ISSUE TITLE
Ditching eleventy's collections in favor of _data?

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#5805]
I was chatting with @MichaelSolati about our collections. In particular, in a number of places we use functions from `utils` and Eleventy `before` hooks to modify our collections for pagination. The downside to this approach is that we end up with repeated 11tydata.js files (try searching for `individual.11tydata.js` or `index.11tydata.js`). For each language we'll need to duplicate those 11tydata.js files, which also means editing all of them at once if we need to make changes. The reason we need these hooks is because they need access other Eleventy collections, and due to the way Eleventy's lifecycle works, those collections aren't ready when we are defining our own collections.

One idea we kicked around was moving away from Eleventy's collection API entirely, and instead defining our own collection-like-things in `_data`. For what it's worth, this is exactly how things work in other SSGs like Next.js (take a look at the [getSortedPosts example here](https://nextjs.org/learn/basics/data-fetching/implement-getstaticprops)). The upside to defining collections ourselves in `_data` is that we completely control the lifecycle. If collectionB needs collectionA it can just require it.

This would be a pretty big departure from how we're currently using eleventy, so this isn't an immediate priority. But it is something we might want to consider as a refactoring experiment to see if it reduces the amount of code duplication.

**Comment by devnook** [comment]
This is especially valid when we take multiple languages into account - see https://github.com/GoogleChrome/web.dev/pull/5809
