### ISSUE TITLE
Don't lazy load hero images

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/web.dev#5813]
Per https://web.dev/lcp-lazy-loading/ lazy-loading hero images (LCP candidates) can cause them to load more slowly. Ironically, web.dev lazy-loads hero images 😅 

To verify, go to a web.dev post and run this script:

```js
new PerformanceObserver((entryList) => {
  const entries = entryList.getEntries();
  const latestEntry = entries[entries.length - 1];
  if (latestEntry?.element?.getAttribute('loading') == 'lazy') {
    console.warn('Warning: LCP element was lazy loaded', latestEntry);
  }
}).observe({type: 'largest-contentful-paint', buffered: true});
```

![image](https://user-images.githubusercontent.com/1120896/125823188-69b1f28f-fa8b-4391-b860-04c7c6304d6d.png)

Update web.dev posts so that the hero image is not lazy-loaded.

**Comment by robdodson** [comment]
> Ironically, web.dev lazy-loads hero images 

To be fair, we only learned yesterday that this was bad :P
