### ISSUE TITLE
[Learn CSS] Margin: Computed margin should be 50px not 100px for CodePen example

### ISSUE THREAD

**Issue by tannerdolby** [GoogleChrome/web.dev#5817]
**Describe the bug**
Related #5769

On the https://web.dev/learn/css/spacing/#margin page, the article states:

> This means that if your element's containing block has a width of 250px and your element has a margin value of 20%: each side of your element will have a computed margin of 50px.

and the text content within the CodePen states the same 50px computed margin, but the example says "I have a computed margin of 100px" which is confusing since there isn't 100px margin anywhere in the example.

**To Reproduce**
1. Go to 'https://web.dev/learn/css/spacing/'
2. Click on ''https://web.dev/learn/css/spacing/#margin"
3. Scroll down to 'Percentages with Margin' CodePen example

**Expected behavior**
I expect the CodePen example to say the computed margin is 50px and not 100px.

**Screenshots**
<img width="924" alt="Screen Shot 2021-07-15 at 12 01 25 PM" src="https://user-images.githubusercontent.com/48612525/125843952-adf252e9-b419-4976-ade1-3a1b5d0b182c.png">

**Comment by tannerdolby** [comment]
cc @argyleink

**Comment by una** [comment]
Made this update, thank you

**Comment by tannerdolby** [comment]
Your welcome @una !
