### ISSUE TITLE
[Learn CSS] Conclusion: author.title isn't defined which makes alt text undefined for author images

### ISSUE THREAD

**Issue by tannerdolby** [GoogleChrome/web.dev#5818]
**Describe the bug**
Related to #5797 & #5801 

> From #5657, "If I understand correctly, it seems like the author's title and description are removed from here, and instead moved into the addFields hook and added at a later time, is that correct? If so, why do it that way?"

 > @MichaelSolati The title and description are not removed here per se, they used to exist in the authorsData.json and no longer exist there. [original comment](https://github.com/GoogleChrome/web.dev/pull/5657/commits/1cd5e9e3d7ece6990349151ecfbe0f85d117f475#r65569185)

This behavior of `author.name.given` not being defined along with the description makes perfect sense, it was removed in #5657 and hasn't been updated in `author-stack` to use the appropriate values for title and desc since this update landed

https://github.com/GoogleChrome/web.dev/pull/5657/commits/1cd5e9e3d7ece6990349151ecfbe0f85d117f475#diff-90d12317ec6c6ca3f3aaf045b4132be3e189606ccd6fc5783fab51fcc937ca86L41-L47

The underlying issue is that `{%- set author = authorsData[item] -%}` doesn't have a `title` property or `descriptions` and thats being use to set some Nunjucks variables in the template right after defining `author` like this in `author-stack.njk`:

```njk
{%- set author = authorsData[item] -%}
{%- set authorName = author.name.given + ' ' + author.name.family -%}
{%- set authorDesc = author.descriptions[locale] or author.descriptions.en -%}
```

When we index the `authorsData[item]` global data which is coming from `authorsData.json`, the loop variable `item` represents the author name from

```yml
jakearchibald:
  title:
    en: Jake Archibald
  description:
    en: Human boy working on web standards at Google
```

In `authors.js` the underlying issue is that:
- description: `i18n.authors.${key}.description`
- title: `i18n.authors.${key}.title`

are both returning undefined so the i18n(author.title, locale) seems to be the culprit for the root cause.

I expected the descriptive alternate text for author images to exist, this same thing happens for the Author name and description. I read in a previous PR (#5657), that the i18n filter is handling the title/desc work so I think when its used like this in authors.js:

```js
const title = i18n(author.title, locale);
...

const img = Img({
    src: author.image,
    alt: title,
    width: '64',
    height: '64',
    class: `w-author__image${small ? ' w-author__image--small' : ''}`,
    params: {
      fit: 'crop',
      h: '64',
      w: '64',
    },
  });
````

**To Reproduce**
1. Go to 'https://web.dev/learn/css/conclusion/'
2. Scroll down to list of authors (to see alt text undefined for images, inspect the element with DevTools)

**Expected behavior**
The expected title string to be created from `const title = i18n(author.title, locale);` and used in the image `alt` along with author title. Not sure if this affects `author.description[locale]` but the author description should be defined and rendered as well.

**Screenshots**
<img width="1062" alt="Screen Shot 2021-07-15 at 12 17 59 PM" src="https://user-images.githubusercontent.com/48612525/125844982-c3994d8d-8bf3-4ba3-9551-35173c2671f1.png">

<img width="1070" alt="Screen Shot 2021-07-15 at 12 17 16 PM" src="https://user-images.githubusercontent.com/48612525/125844908-07f5d15d-5b51-4c97-b2df-65c6b75bd717.png">

**Comment by tannerdolby** [comment]
@MichaelSolati I apologize for the information dump, this was just quite a journey to finally find the root cause which was the changes landing in #5657 and the {% set authorName ... %} and description not being updated in `author-stack.njk`

**Comment by MichaelSolati** [comment]
> @MichaelSolati I apologize for the information dump, this was just quite a journey to finally find the root cause which was the changes landing in #5657 and the {% set authorName ... %} and description not being updated in `author-stack.njk`

Lol, don't worry. This is something i didn't notice when we changed how we stored author data (we made the change to be able to support authors, tags, and upcoming features in multiple languages). But this was helpful and will be fixed asap! (I'll need a sec to parse what you wrote then fix it).

**Comment by tannerdolby** [comment]
> Lol, don't worry. This is something i didn't notice when we changed how we stored author data (we made the change to be able to support authors, tags, and upcoming features in multiple languages).

Ok sounds good, yeah the change definitely seems like it was warranted to benefit from authors, tags, upcoming features internationalized. I'm glad this was helpful, let me know if I can assist you at all in fixing things. Otherwise, thank you for handling this @MichaelSolati !

**Comment by robdodson** [comment]
I'm working on a fix for this

**Comment by tannerdolby** [comment]
> I'm working on a fix for this

Excellent @robdodson !
