### ISSUE TITLE
wrong set values (of fast pages) for my domain in web vitals values

### ISSUE THREAD

**Issue by mdromed** [GoogleChrome/web.dev#5829]
Wrong data for my domain https://www.b e b e m o v i l.com   (please remove spaces) 

if you validate any page of product, like this.. 

https://www.b e b e m o v i l.com/inglesina-quid-2-silla-de-paseo-id575  (please remove spaces)

everyone will get 98 or 100 points on web vital metrics validator. So, any page from that domain is fast page.
However, some days ago system has gone pointing down day to day.
Now it indicates 0% fast pages. 
Obviously it is wrong.
please check and repair that part of system please.
I also have seen that for PC values i had to repair many urls. Then i did, and validation result was CORRECT, however system interface keep indicating that all pages from my web are "slow" or sometimes "need to get better".

Generaly all web metric values are wrong.

Please check and repair these issues.
My web is loosing head positions on SERP list so fast. 
![Screenshot_20210721-055011_Chrome](https://user-images.githubusercontent.com/38739377/126429548-a16e5aa1-8fe5-4bd4-b53c-30a2206169e9.png)
![Screenshot_20210721-055128_Chrome](https://user-images.githubusercontent.com/38739377/126429551-7672ec3f-fa68-4e5c-8117-02f56e4dba7c.png)
![Screenshot_20210721-055300_Chrome](https://user-images.githubusercontent.com/38739377/126429553-a9625029-da7b-430b-b0fa-0f3af4259e6d.png)
![Screenshot_20210721-054939_Chrome](https://user-images.githubusercontent.com/38739377/126429559-5761d98a-2de9-4513-aedc-f6207647b9c4.png)
![Screenshot_20210721-055005_Chrome](https://user-images.githubusercontent.com/38739377/126429560-5ca0d3d9-6aaf-45aa-afda-d2a9b4cf855b.png)

**Comment by samthor** [comment]
I appreciate your frustration but this is for issues with web.dev content, not the broader ecosystem of tools.

I'm cc'ing @philipwalton who is the author of our CWV landing page who might be able to provide pointers, but I'm closing this issue.

**Comment by mdromed** [comment]
ok sorry.
I will wait for his response. 
Best Regards
