### ISSUE TITLE
Download & Opening of Pdf File in Chrome

### ISSUE THREAD

**Issue by DizzyEnemy** [GoogleChrome/web.dev#5835]
Whenever I searched for a file in chrome , the Pdf format Doesn't Open but in Google it 

To Reproduce :
Suppose We Searched For CBSE Physics Sample Paper Class 12 in Chrome. Now File appear but it doesn't Open. 
Now Same Search in Google then File Opens.

**Expected behavior**
I Want that File Should also open in chrome.

**Screenshots**

**Comment by samthor** [comment]
This is a developer documentation site. If you have an issue with Chrome's behavior please file a bug on crbug.com.
