### ISSUE TITLE
Update to latest lighthouse version

### ISSUE THREAD

**Issue by gdarko** [GoogleChrome/web.dev#584]
Hello,

I see the lighthouse version is 4.0.0 beta on web.dev. Why not to update to latest version?

Best Regards,

**Comment by robdodson** [comment]
Under the hood our measure tool uses the PageSpeed Insights API (which is powered by Lighthouse). That means we use whatever version they currently use. @paulirish 	do you know if they plan to rev to 4.1.0?

**Comment by paulirish** [comment]
we just finished the update to 4.1.0 tonight. :)

**Comment by gdarko** [comment]
Great!
