### ISSUE TITLE
Console/Logs buttons moved after Glitch interface update

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/web.dev#585]
It used to be that clicking Logs (in the upper right corner) reveals Console button.
There's a new button called Tools now that reveals Logs and Console, so all codelabs that use them need updating.

![glitch-logs](https://user-images.githubusercontent.com/17127567/52052514-f6d3c680-2556-11e9-93c2-aeb94d44df5f.png)

**Comment by robdodson** [comment]
😭 good catch thank you!

**Comment by mihajlija** [comment]
https://github.com/GoogleChrome/web.dev/blob/performance-budgets-codelab/content/fast/incorporate-performance-budgets-into-your-build-tools/glitch-tools.png

Here's the button I made for my codelab that you can use to make the component.

**Comment by robdodson** [comment]
Should be fixed now.
