### ISSUE TITLE
content: feature detection of fetch() upload streaming does not work on recent Safari

### ISSUE THREAD

**Issue by nwtgck** [GoogleChrome/web.dev#5869]
Hi, thank you so much for the wonderful post. I like fetch() upload streaming feature and looking forward to being implemented it in popular browsers. 

### What page(s) need to be updated?

Title: "Streaming requests with the fetch API"

* published URL: <https://web.dev/fetch-upload-streaming/#feature-detection>
* GitHub source: <https://github.com/GoogleChrome/web.dev/blob/c76c5c7bb243da73c9c78f416669f388422ee1bf/src/site/content/en/blog/fetch-upload-streaming/index.md#feature-detection>

### Why is this update needed?

The "feature detection" in the post does not work in Safari, although it is great because it does not require network connection to detect. I confirmed it works on Chrome and Firefox.

The following image shows Safari Version 14.1 returns true, but it does not support actually.
<img width="381" alt="image" src="https://user-images.githubusercontent.com/10933561/126788320-233418f7-1979-4535-88ee-ac9299718f87.png">

The following code shows Safari does not upload ReadableStream.

```js
fetch("", { method: "POST", body: new ReadableStream() })
// => [Error] Unhandled Promise Rejection: NotSupportedError: ReadableStream uploading is not supported
```

maybe related: [203617 – "ReadableStream uploading is not supported" when fetch()ing a Request that has been logged to console](https://bugs.webkit.org/show_bug.cgi?id=203617)

**Comment by jakearchibald** [comment]
Cheers. Pretty sure I tested this back in the day. I guess I'll add it to the "things Safari broke recently" list.

**Comment by jakearchibald** [comment]
Ugh, ok, the annoying thing here is they decided to support streams in request objects, but not when used with fetch. Struggling to find an alternative. I'll keep thinking…

**Comment by nwtgck** [comment]
Yes, I understand the difficultly. I found that Safari supports `body: ReadableStream` now because ReadableStream is read in body in Request as follows. So it seems to be difficult to detect using only `Request`.

```js
const req = new Request("", {
  method: "POST",
  body: new ReadableStream({
    start(c) {
      c.enqueue(new Uint8Array([65, 66, 67]));
      c.close();
    }
  })
});

req.text().then(t => console.log("text:", t));
```

Here is the result in the console. Safari says `text: "ABC"`, not `text: [object ReadableStream]` now.

<img width="359" alt="image" src="https://user-images.githubusercontent.com/10933561/127428105-6ee4d3c6-e8fd-4587-8c02-574dff9ddacf.png">

**Comment by jakearchibald** [comment]
Yep. I don't think there's a way to solve this without a service worker. Sighhhhhhh

**Comment by jakearchibald** [comment]
Ok, I think I've found a way to do this, but I'm getting it double-checked, and might need to add some platform tests so it doesn't break in future https://github.com/whatwg/fetch/issues/1275.
