### ISSUE TITLE
Add `twitter:creator` to article page meta

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/web.dev#5887]
**Is your feature request related to a problem? Please describe.**
Currently the site uses 4 or 5 twitter meta data entries but is missing potential attribution

**Describe the solution you'd like**
On an article where the author twitter account is known (their data is in the repo), we should add additional meta data to help attribute the author with the site content

**Comment by samthor** [comment]
Is this actually shown or used by Twitter at this point? My personal blog has it, and @​samthor does not show up at all:

<img width="514" alt="Screen Shot 2021-08-19 at 15 12 15" src="https://user-images.githubusercontent.com/119184/130011380-94dacdda-8f50-464e-bdb5-0e725918430f.png">

**Comment by samthor** [comment]
(My name is there purely because that was done via the Twitter [card validator](https://cards-dev.twitter.com/validator), but it's not part of the card)

**Comment by argyleink** [comment]
still in all the [docs](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup) and examples, but agree it doesnt appear to be visually present in their cards.

**Comment by samthor** [comment]
This is also tricky because it's not clear it'd support multiple authors. For now I just don't think this is worth adding, sorry.

If Twitter changes its approach to this then we can raise again.
