### ISSUE TITLE
Avoid enormous network payloads / Defer unused CSS doesn't consider compression

### ISSUE THREAD

**Issue by peixotorms** [GoogleChrome/web.dev#592]
Hi there,

I think there was a recent update on PageSpeed Insights, within the past week or so, that started causing this AND it's affecting all scores on most wordpress sites, tremendously on web.dev as well as the PSI tool itself.

I have reported it on pagespeed forum, but no reply yet:
`https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/luQUtDOnoik`

In a specific case, I have an 1.5 MB CSS file with brotli or gzip compression.
`https://04820261391683266720.googlegroups.com/attach/192eafd9497563/Screenshot_1.jpg?part=0.1&view=1&vt=ANaJVrGY1RUBDcca3lTV0FKejNkZepto1Tw-IBO1GNFwS45-HcuONta_4DBEO1OtXK-d1q2lewdtamSA6XSL1aj8B3lQU1QfLaEmaeHG3g_9qf6E-H0UKME`

I can see that Chrome is downloading the correct br file:
[](https://04820261391683266720.googlegroups.com/attach/192eafd9497563/Screenshot_2.jpg?part=0.2&view=1&vt=ANaJVrFoSa7HCInEVW9YKokfvde3imjWdK0TUgKtr7T8jKf_qnA4aHvFbLOpDoIFMTV6vTcWU1QoBaWu0GWLOyToc9mvkl_muYPW6EryJuXaR3gKmbuI7GA)

And so does www.webpagetest.org
`https://04820261391683266720.googlegroups.com/attach/192eafd9497563/Screenshot_3.jpg?part=0.3&view=1&vt=ANaJVrEQkxxD-z9h6_8NT9y8ARZbPTRXYb-UaBQJusk8OzRgcFYV7p3zyuF6FItf9_ruuXWSLQV5yd402KjynB1uH7xZpW63LLkbeAdczIsMaLPNcY5PNq4`

And so does Chrome Lighthouse Version 71.0.3578.98:
`https://04820261391683266720.googlegroups.com/attach/192eafd9497563/Screenshot_4.jpg?part=0.4&view=1&vt=ANaJVrEfsBpQTS6vs5UmeMN76PbqDmBTZwNSnYn7_GwW4zHD97VHL-5pjkGncLUgDFyrW4ZV9FihMbl1VRHiVB7jhOxMnUsoLAhmICLGPEZLLXNz7BxLdU4`

However, on https://developers.google.com/speed/pagespeed/insights/ and web.dev
it looks like this:
`https://04820261391683266720.googlegroups.com/attach/192eafd9497563/Screenshot_5.jpg?part=0.5&view=1&vt=ANaJVrFuyQDLNU2PZK8cDG-eTcE-cL75tHgVcIVtJM930_WXDdlG8h90Y9NdH4GDbbje5yovCDOz6x-atbcyzOht_5kByNydOm2arV2euUTqIfXom5lkUWY`
`https://04820261391683266720.googlegroups.com/attach/192eafd9497563/Screenshot_6.jpg?part=0.6&view=1&vt=ANaJVrGNRquKr1ZAkz3oXlyHWKBcteVmHPGV1wlQ-5IhRWj_cGyKYe5uHeQgz504ao5WzA-n7KbOMFqpDAsLGk-gwXd3OZaHagvSAy8HcPvcUc5ziFFAPkA`

So it seems that suddenly, the PSI tool decided not to download compressed tools with either brotli or gzip, but this also affects https://web.dev

It's fine on
https://www.webpagetest.org/lighthouse
probably because they don't use the api.

**Comment by robdodson** [comment]
Thanks @peixotorms. Looks like this is a Lighthouse issue being handled over at https://github.com/GoogleChrome/lighthouse/issues/7141
