### ISSUE TITLE
Author name is not populated properly in the share action button

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/web.dev#5924]
I believe https://github.com/GoogleChrome/web.dev/pull/5657 caused a regression in the way the share button handles authors. As you can see in the screenshot below, my title "Francois Beaufort" is not used. Instead it says "i18n.authors.beaufortfrancois.title"

You can reproduce by clicking the share web.dev button in https://web.dev/user-preference-media-features-headers/
 
![image](https://user-images.githubusercontent.com/634478/128205493-976669d4-b854-4690-b494-dd49e6fa38cc.png)

@MichaelSolati Can you fix it?

**Comment by MichaelSolati** [comment]
I'll do this today, thank you for raising the issue!
