### ISSUE TITLE
Few images in the article 'animations guide' are not loading

### ISSUE THREAD

**Issue by llamaeager** [GoogleChrome/web.dev#5946]
**Describe the bug**
Two images on the page "[How to create high-performance CSS animations](https://web.dev/animations-guide/)" are not loading. 

Reason: The file URL is leading to 404 page

Github Repo: The [parent directory](https://github.com/GoogleChrome/web.dev/tree/main/src/site/content/en/animations/animations-guide) of the article [markdown file](https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/animations/animations-guide/index.md) does not contain image files referenced in it.

**To Reproduce**
1. Go to the page "[How to create high-performance CSS animations](https://web.dev/animations-guide/)"
2. Scroll down to the section "[Firefox DevTools](https://web.dev/animations-guide/#layout-firefox)"
3. See below the bullet points

**Expected behavior**
Both images should load on the page

**Screenshots**
<img width="1083" alt="How to create high-performance CSS animations" src="https://user-images.githubusercontent.com/20735862/128684758-5d8e7fec-2373-42dd-92de-2ac1b31e2f50.png">

**Comment by Ayushparikh-code** [comment]
can i work on this issue ?

**Comment by MichaelSolati** [comment]
@Ayushparikh-code I appreciate the offer but this is something a googler will have to handle, especially with how we store our images. @evilquail I'm reaching out to the original author to see if I can get the image assets and will follow up here when I hear back from them.

**Comment by Ayushparikh-code** [comment]
Ok 👍🏻

**Comment by Ayushparikh-code** [comment]
Ok 👍🏻
