### ISSUE TITLE
<button> is described as an element that does not accept child elements

### ISSUE THREAD

**Issue by alecgregory** [GoogleChrome/web.dev#5954]
**Describe the bug**
`<button>` is described as an element that does not accept child elements: 

**To Reproduce**
1. Go to https://web.dev/learn/css/pseudo-elements/#::before-and-::after
2. Scroll down to 'Once a ::before or ::after element has been created, you can style it however you want with no limits. You can only insert a ::before or ::after element to an element that will accept child elements (elements with a document tree), so elements such as `<img />`, `<video>`, `<button>` and `<input>` won't work.'
3. `<button>` is in the list even though it _does_ accept children.

**Expected behavior**
`<button>` should not be in the list

**Screenshot**
<img width="973" alt="Screen Shot 2021-08-09 at 6 31 11 PM" src="https://user-images.githubusercontent.com/5311272/128794728-d095b298-236f-4b29-9a89-e502cfcc1e45.png">

**Comment by argyleink** [comment]
nice catch! 

also `input[type="checkbox"]` can have pseudo children too, this seems like a great place to share that exception.
