### ISSUE TITLE
Building a Color Scheme Post's Pens Inappropriately Setting Font Smoothing to Antialiased

### ISSUE THREAD

**Issue by cgrobb** [GoogleChrome/web.dev#5955]
### What page(s) need to be updated?
building-a-color-scheme/index.md

### Why is this update needed?
The CodePens in this page all include a font that inappropriately sets:
`body {
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}`

Discussion of this generally can be found here:
https://github.com/google/fonts/issues/1170, specifically https://github.com/google/fonts/issues/1170#issuecomment-694814423

**Comment by argyleink** [comment]
fixed 👍🏻
