### ISSUE TITLE
Is FID measure affected by async code

### ISSUE THREAD

**Issue by andreamoro** [GoogleChrome/web.dev#5960]
### What page(s) need to be updated?

https://web.dev/fid/

### Why is this update needed?

Provide clarity on whether the FID measurements is affected by asynchronous code. As far as it can be understood, deferring code load is an hack dev might use to improve the FID at the expense of the user experience. 
My concerns however goes on:
- capacity of the API to listen for objects that async injected
- how to identify via the Chrome dev tools and report such a (bad) practice, if any.

A paragraph detailing on the above would be beneficial.

**Comment by AaronForinton** [comment]
Picking up on this to see if we can get it closed.

**Comment by philipwalton** [comment]
I think this issue can be closed.

I think the current document explains pretty clearly that FID only measures the first input, so if a developer chooses to delay running some code until after that input, it won't affect FID.

I don't think we need to comment on whether or not this is a good practice or a bad practice, and I don't think we want to draw attention to the fact that some people do it. Also, this is not a problem with [INP](https://web.dev/inp/), so I think addressing this concern is a low priority.
