### ISSUE TITLE
Homepage card layout is broken on smaller desktops

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#5961]
![image](https://user-images.githubusercontent.com/1066253/128911135-9f684640-b8d7-4fa3-9d18-0397d204a597.png)

The top card is supposed to span two columns but it seems to be broken. The hero image isn't spanning.

**Comment by samthor** [comment]
I finally reproed a possibly related issue. When not in incognito, I get a version of the homepage which has no stories?

<img width="1720" alt="Screen Shot 2021-08-30 at 14 29 24" src="https://user-images.githubusercontent.com/119184/131285369-1a8ed41b-15e0-4ffe-9de7-79ddd7e6aed8.png">

It's literally not in the source on the left page, but it is on the right page. Is Firebase...

- sometimes showing a missing version (and caching forever)
- doing rewriting (??)
