### ISSUE TITLE
Change the animation-play-state pen to use only css

### ISSUE THREAD

**Issue by alecgregory** [GoogleChrome/web.dev#5971]
### What page(s) need to be updated?
https://web.dev/learn/css/animations/#animation-play-state

### Why is this update needed?
The same result can be achieved with CSS

The animation-play-state example could be implemented in css rather than JS by using hover state. See below and example pen: https://codepen.io/alecgregory/pen/QWvoxgq

```
.grower {
  animation-name: grow;
  animation-duration: 2s;
  animation-iteration-count: infinite;
  animation-timing-function: linear;
}

@keyframes grow {
  0% {
    transform: scaleX(1.1);
  }
  50% {
    transform: scaleX(1.8);
    background: darkturquoise;
  }
}

.grower:hover {
  animation-play-state: paused;
  cursor: wait;
}

/* Decorative styles */
.grower {
  width: 200px;
  height: 80px;
  background: lightseagreen;
  position: relative;
  margin-left: auto;
  margin-right: auto;
}

label {
  display: block;
}
```

**Comment by jpmedley** [comment]
@andy-piccalilli What do you think of this proposal?

cc: @rachelandrew

**Comment by andy-piccalilli** [comment]
Yeh that looks great—especially the cursor detail 👏 

I've absolutely no idea why I used JS either. I'll blame working to the deadline 😂

**Comment by alecgregory** [comment]
Keeping this alive.

**Comment by rachelandrew** [comment]
@alecgregory thanks for this and apologies it took so long to update! I've just edited the CodePen.
