### ISSUE TITLE
Use CSS 2/4 way of explaining specificity

### ISSUE THREAD

**Issue by j9t** [GoogleChrome/web.dev#5973]
The [chapter on specificity](https://web.dev/learn/css/specificity/) explains specificity using points, which is potentially misleading.

The point example is problematic because following its logic, a selector `a b c d e f g h i j k` would get 10 × 1 = 11 points, a selector `.foo` 10 points, and therefore `a b c d e f g h i j k` would beat `.foo`. In reality, however, `.foo` has a higher specificity (0,0,1,0) than `a b c d e f g h i j k` (0,0,0,11), which is more clear when explaining it the way [CSS 2](https://www.w3.org/TR/CSS22/cascade.html#specificity) and [CSS Level 4](https://www.w3.org/TR/selectors-4/#specificity-rules) describe it. (The problem probably comes from [CSS Selectors Level 3](https://www.w3.org/TR/selectors-3/#specificity), which _seemed to_ use a points-like system.)

I suggest to switch to explaining specificity only by the system favored in CSS 2 and CSS Level 4. It would make it easier to understand the [section on “Visualizing specificity,”](https://web.dev/learn/css/specificity/#visualizing-specificity) too, as that already alludes to that other system.

**Comment by htbkoo** [comment]
I agree with @j9t !

To be honest, I was slightly confused when [reading that section](https://web.dev/learn/css/specificity/#specificity-scoring) and I nearly created another same issue 😄

I guess even if we want to stick with the [current section about `Specificity scoring`](https://web.dev/learn/css/specificity/#specificity-scoring), we could at least add [this line from the CSS Selectors Level 3 specification](https://www.w3.org/TR/selectors-3/#specificity) to eliminate any possible confusion:
`Concatenating the three numbers a-b-c (in a number system with a large base) gives the specificity.`

**Comment by AaronForinton** [comment]
Investigating this one - @rachelandrew please let me know if there's some way I can support in getting it closed off

**Comment by dstmarthe** [comment]
Thanks for raising this. Content on this site is now frozen. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298526958
