### ISSUE TITLE
content: TODO Check the two links (404) at https://web.dev/serial/

### ISSUE THREAD

**Issue by artisticfox8** [GoogleChrome/web.dev#5974]
### What page(s) need to be updated?
https://web.dev/serial/

### Why is this update needed?
 Links in this paragraph don't work:

To understand the security tradeoffs, check out the security and privacy sections of the Web Serial API Explainer.

The links at https://github.com/reillyeon/serial/blob/gh-pages/EXPLAINER.md#security-considerations and https://github.com/reillyeon/serial/blob/gh-pages/EXPLAINER.md#privacy-considerations

**Comment by jpmedley** [comment]
@reillyeon Does this content exist anywhere else? Even if it does, should we repurpose the text for [MDN's overview](https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API) and return the older source?

**Comment by reillyeon** [comment]
These links can be updated to https://github.com/WICG/serial/blob/main/EXPLAINER.md#security-considerations and https://github.com/WICG/serial/blob/main/EXPLAINER.md#privacy-considerations or you can link to the version of these sections in the specification: https://wicg.github.io/serial/#security and https://wicg.github.io/serial/#privacy

**Comment by jpmedley** [comment]
At this point, I think the spec would be better.
