### ISSUE TITLE
Outline indicator inconsistence

### ISSUE THREAD

**Issue by equinusocio** [GoogleChrome/web.dev#598]
**Page Affected:** All

**What needs to be done?**

The outline indicator is inconsistent between header and focusable elements inside the doc, some elements have the default outline some none, and the search input doesn't have the outline at all. Inside the header, the menu elements are skipped when we press shift+tab.

![kapture 2019-02-07 at 11 45 04](https://user-images.githubusercontent.com/10454741/52406679-97cdfe80-2ace-11e9-9ce0-bfd168c35a08.gif)

**Comment by robdodson** [comment]
yeah the focus styles are not my favorite. We're using some existing google components in the header and are in the process of moving off of them.

**Comment by robdodson** [comment]
Going to close this as having been improved a lot. There are some slight quirks in the top nav still, but we're going to migrate off of that component in the near future.

Adding a label so we remember to circle back to this issue during the migration.
