### ISSUE TITLE
Add a next button in courses

### ISSUE THREAD

**Issue by taran-duba** [GoogleChrome/web.dev#5985]

**Comment by jpmedley** [comment]
@robdodson FYI

**Comment by robdodson** [comment]
Courses already have next and previous buttons. Without a description it's hard to know what we should improve. I'm going to close this, but happy to reopen if folks have further suggestions.

![image](https://user-images.githubusercontent.com/1066253/129812816-ebb9ef1b-3e80-45f3-82c3-78b3e06d2248.png)
