### ISSUE TITLE
Not Secure On data:image/

### ISSUE THREAD

**Issue by panthersdude2001** [GoogleChrome/web.dev#599]
I thought Not Secure warnings were supposed to be for ALL HTTP websites, not any others.
Heres what im getting
![not secure](https://user-images.githubusercontent.com/44646536/52418225-91825700-2abb-11e9-9f7c-f6cebc6b4084.png)
Now, is this going to get fixed or is this a real issue?

**Comment by panthersdude2001** [comment]
If this is in the wrong sub project, move it there. This is supposed to be for the webdev, right?

**Comment by robdodson** [comment]
This repo is specifically for the code that lives on http://web.dev

I think what you're describing is a general Chrome issue. You can file those over at https://crbug.com/.

**Comment by panthersdude2001** [comment]
Thank you rob! I knew it was the wrong thread!
Bryce Monaghan 

    On Thursday, February 7, 2019, 12:37:55 PM EST, Rob Dodson <notifications@github.com> wrote:  
 
 
This repo is specifically for the code that lives on http://web.dev

I think what you're describing is a general Chrome issue. You can file those over at https://crbug.com/.
