### ISSUE TITLE
content: Add more guidance to help debug LCP in the field

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/web.dev#6021]
### What page(s) need to be updated?

https://web.dev/debug-web-vitals-in-the-field/#lcp

### Why is this update needed?

There are more things developers could be looking at to help debug LCP in the field.

See https://stackoverflow.com/questions/68811470/how-to-debug-lcp-as-cls-with-web-vitals-js-sdk/68824589#68824589 for potential content to be added. Specifically:

- LCP element tag name
- FCP and TTFB diagnostics
- viewport size
- scroll position
- ECT
- hero image render time

I can help update the content, but this isn't a high priority.

cc @philipwalton

**Comment by thanhtrieu502** [comment]
malchata:farfetch-case-study

**Comment by thanhtrieu502** [comment]
[malchata:farfetch-case-study]() [](malchata:farfetch-case-study)

**Comment by thanhtrieu502** [comment]
https://github.com/orgs/GoogleChrome/projects/2#card-67071306

**Comment by thanhtrieu502** [comment]
> https://github.com/orgs/GoogleChrome/projects/2#card-67071306

[https://github.com/orgs/GoogleChrome/projects/2#card-67071306](https://github.com/orgs/GoogleChrome/projects/2#card-67071306)

**Comment by AaronForinton** [comment]
Hello @philipwalton, I think you're the right person to approach on deciding on whether this is going ahead?

**Comment by philipwalton** [comment]
A lot of updates have been made to that post since this issue was filed, as well as the attribution build of the `web-vitals` JS library being released.

I think we can close this for now and open up separate issues if there are still specific bits missing.
