### ISSUE TITLE
Add support for headings in the navigation for courses.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#6024]
https://web.dev/learn/css/ does not have any section headings in the left nav, but I've seen a number of upcoming outlines that will need it. 

We would need to add it to https://github.com/GoogleChrome/web.dev/blob/main/src/site/_includes/partials/navigation-drawer-course.njk and we would likely need to modify https://github.com/GoogleChrome/web.dev/blob/main/src/site/_filters/navigation.js to support it.

**Comment by robdodson** [comment]
@samthor tagging you on this to maybe think about who could be a good owner for the task. I think we'll need it in a few weeks/a month as the Learn Forms course starts to get close to shipping.

**Comment by samthor** [comment]
I'm confused - do you mean the ToC on the right that only has "Welcome to
Learn CSS!"? (We're missing all the h2's)

Or is this a design change to the list of different pages in the course?

**Comment by robdodson** [comment]
I'm referring to the navigation on the left

![image](https://user-images.githubusercontent.com/1066253/131545679-37f521a1-96a3-497b-9fa8-1aea298d9f61.png)

We don't need to make any changes for Learn CSS. But the Learn Forms course is organized like this:

- Get started with forms
  - The form element itself
  - Form fields
- Best practices
  - Design basics
  - ...
- Testing and monitoring
  - How to test form usability
  - ...

**Comment by samthor** [comment]
Do we expect the same versatility as in d.c.c., or rather, some Qs:

- could parent items themselves be links
- can these be infinitely nestable
- what happens to the 00x numbers of sub-items?
