### ISSUE TITLE
content: Updates for the Web Share API

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#6037]
* Use this template to request updates to existing content.
* Delete any fields that aren't relevant to your issue. 
* Update the title of this issue with a brief summary of the work to be done.

### What page(s) need to be updated?

- [ ] https://web.dev/web-share/
- [ ] https://web.dev/web-share-target/

### Why is this update needed?

Another implementation of the spec is landing in Firefox. Since the site is called web.dev, not chrome.dev, the articles need to be generalized. There also may be minor spec changes.

There is specific information in [this MDN issue](https://github.com/mdn/content/issues/7749).

### What's the deadline?

None.

#### Is it a hard deadline?

N/A

If yes, please explain why.

**Comment by AaronForinton** [comment]
Hello @jpmedley - I'm looking into this one right now. Is there any way I can help get it closed / is it still applicable?

**Comment by AaronForinton** [comment]
- https://web.dev/web-share/ has got browser compatibility info. I don't necessarily see anything else that goes against the cross-browser ideals of the content there
- https://web.dev/web-share-target/ has been migrated to DCC and redirects there, so no need to generalise that now

@petele I think we can close this one as no longer needed but I'll get your approval first
