### ISSUE TITLE
Over-scrolling in codelabs with aside notes

### ISSUE THREAD

**Issue by kjue25** [GoogleChrome/web.dev#606]
Any codelab with an "aside note" makes the instructions scrollable past the horizontal edge of the "page" of instructions to the left of the Glitch embed.  Screenshot below with example codelabs. (I'm working on a Pixelbook - not sure if that affects it.)

**Page Affected:** 
https://web.dev/fast/use-imagemin-to-compress-images/codelab-imagemin-grunt
https://web.dev/fast/use-imagemin-to-compress-images/codelab-imagemin-webpack

![screenshot 2019-02-07 at 9 14 47 pm](https://user-images.githubusercontent.com/5799031/52460266-5402e580-2b1e-11e9-8642-eee54bd8067e.png)
![screenshot 2019-02-07 at 9 15 23 pm](https://user-images.githubusercontent.com/5799031/52460274-58c79980-2b1e-11e9-89ad-a4f4ce76445b.png)

**Comment by robdodson** [comment]
ah yes. It's a recent devsite CSS change that is affecting us. I'll see about landing a fix.

**Comment by robdodson** [comment]
Temporarily fixed by #618. Although it looks like there is still a style on `devsite-header` that we need to fix as well.

**Comment by robdodson** [comment]
Sending in CLs to fix this next week.
