### ISSUE TITLE
content: Explain the EyeDropper API with an example

### ISSUE THREAD

**Issue by MatanBobi** [GoogleChrome/web.dev#6064]
#### Provide a brief title for your content proposal
The EyeDropper API - A simple "color picker" 

#### Provide a brief summary of your content proposal
The new EyeDropper API has now shipped in Chrome Canary (95 at the moment),
In this post we'll cover how to feature detect it, how to use it and show a simple example

#### What content already exists on this topic?
https://www.chromestatus.com/feature/6304275594477568
https://wicg.github.io/eyedropper-api/

#### Who will be authoring the content?
@matanbobi

#### Are there any stakeholders who should be informed when this content changes? 
Not that I know of.

#### What area is your content related to?
Frontend, new API's supported in Chrome.

#### What kind of content are you creating?
Blog Post, Guide, Example.

**Comment by tomayac** [comment]
Hi @MatanBobi,

The `EyeDropper` team from Microsoft have agreed on writing an article for this feature for `web.dev`. You can _and should_ obviously still write about this, just maybe on your own blog or another outlet like https://www.smashingmagazine.com/, https://css-tricks.com/ or similar. Thanks for your understanding, and apologies if this is a disappointment. 

Cheers,
Tom

**Comment by tomayac** [comment]
FYI, work on this will happen in https://github.com/googlechrome/web.dev/issues/6222, but the linked Google Doc will initially be private. Once the PR that references the Issue is open, you can start to see the content, though. A review of this PR then would also be a great way to contribute.

**Comment by MatanBobi** [comment]
Thanks @tomayac, I subscribed to that issue so I'll be notified when the PR will happen and of course I'd be happy to review and help.
Thanks again!
