### ISSUE TITLE
Private Reports / Dead links in the blog

### ISSUE THREAD

**Issue by aswinsekar** [GoogleChrome/web.dev#6066]
**Describe the bug**
In the blog [2021 Scroll Survey Report Resources section](https://web.dev/2021-scroll-survey-report/#resources) some reports are private. Is it possible to provide reports with public access

**To Reproduce**
1. Go to https://web.dev/2021-scroll-survey-report/#resources
2. Click on Scroll Survey Report
3. You will see access request page from Google Drive

**Expected behavior**
The document can be accessible for general public without request access.

**Screenshots**
![Screenshot 2021-08-31 at 6 47 33 PM](https://user-images.githubusercontent.com/16933310/131509731-c14f38ae-b880-4b57-95c1-3e204cddca58.png)

**Comment by samthor** [comment]
Thanks for the report. I think the failure here is that this should link [to the PDF instead](https://storage.googleapis.com/web-dev-uploads/file/vS06HQ1YTsbMKSFTIPl2iogUQP73/QZopyELSk8T7IpsgOnRU.pdf) (which _is_ correctly linked at the top of the post).

cc @argyleink @samdutton to confirm

**Comment by samdutton** [comment]
Thanks @aswinsekar ! 

#6081 fixes this.
