### ISSUE TITLE
Add 'immutable' to cache-control for long max-age fingerprinted files

### ISSUE THREAD

**Issue by Malvoz** [GoogleChrome/web.dev#608]
Would be a nice addition to include the [`immutable` directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Revalidation_and_reloading) to the `Cache-Control` header in this paragraph:

> When responding to requests for URLs that contain "fingerprint" or versioning information, and whose contents are never meant to change, add `Cache-Control: max-age=31536000` to your responses.

_- https://web.dev/reliable/http-cache#long-lived-caching-for-versioned-urls_

E.g.: `Cache-Control: max-age=31536000, immutable` where `max-age` serves as a fallback for when `immutable` isn't supported.

**Comment by robdodson** [comment]
Sound good @kosamari? If so we can do a PR to update it.

**Comment by kosamari** [comment]
forwarding to @jeffposnick (author)

I think it's fine either way but I know we worked on making each guide short.

**Comment by jeffposnick** [comment]
I did consider that in the original post, but the `immutable` support story is a bit complicated:

- https://bugs.chromium.org/p/chromium/issues/detail?id=611416#c46
- https://www.keycdn.com/blog/cache-control-immutable#browser-support

I don't think that Chrome has to support a feature for it to be recommended in web.dev, but at the same time, there's enough nuance here that just leaving it out seemed like the more straightforward guidance.

**Comment by Malvoz** [comment]
Thanks for the response. The directive is supported in Edge, Firefox and Safari: https://developer.mozilla.org/docs/Web/HTTP/Headers/Cache-Control#Browser_compatibility

Do you still deem this not important/impactful enough to include it in the article?

**Comment by jeffposnick** [comment]
I realize that there are other places where I have an aside note on that document, so I'll just add another one with info about `immutable`, while hopefully not distracting from the main guidance.
