### ISSUE TITLE
[Patterns] Mobile Viewport Demos

### ISSUE THREAD

**Issue by una** [GoogleChrome/web.dev#6084]
**Describe the bug**
Demos on smaller viewports not respecting intended size. Iframe intended size is `400px`, but showing up at `157px`:

**Screenshots**
![Screen Shot 2021-09-01 at 1 30 18 PM](https://user-images.githubusercontent.com/1693164/131716885-79133d37-74fd-48b7-800f-80500e99f4a8.png)

**Comment by devnook** [comment]
Fixed in #6184
