### ISSUE TITLE
[Patterns] Return to Primary Patterns Page

### ISSUE THREAD

**Issue by una** [GoogleChrome/web.dev#6085]
**Is your feature request related to a problem? Please describe.**
When interacting with a patterns page, i.e. CWV patterns, a user clicks on a pattern and opens a separate page with more content. There is no "return" CTA to get back to the initial page of patterns. This is an issue if a user is sent a link to a pattern (and therefore can't use their back button). They lose context. 

**Describe the solution you'd like**
Add some sort of clear link back to a larger patterns page for better discoverability.

**Additional context**
![Screen Shot 2021-09-01 at 1 33 08 PM](https://user-images.githubusercontent.com/1693164/131717270-7989ad29-d559-4537-a7ee-94d3ed8ed9b4.png)

**Comment by devnook** [comment]
Fixed in #6184
