### ISSUE TITLE
Correct the sentence on 'no-cache' - stating it means: don't cache

### ISSUE THREAD

**Issue by Malvoz** [GoogleChrome/web.dev#609]
https://web.dev/secure/cross-origin-resource-sharing#how-does-a-resource-request-work-on-the-web

> Sample Response header
> 
> Content-Encoding: gzip
> Cache-Control: no-cache 
> 
> Above is same as saying "Data is encoded with gzip. **Do not cache this please**"

That statement is incorrect. [`no-cache`](https://tools.ietf.org/html/rfc7234#section-5.2.2.2) tells the client to revalidate with the server before serving the (cached) file, responding with a 304 if nothing changed. 

The explanation should be corrected, unless the intention was to say [`no-store`](https://tools.ietf.org/html/rfc7234#section-5.2.2.3) - then change to that directive?

**Comment by robdodson** [comment]
@kosamari do you agree? If so we can do a PR to update the post.

**Comment by Malvoz** [comment]
I took the liberty to do a PR, I determined `no-store` must've been the intention based on the sentencing "Do not cache this please" as that is what `no-store` does.

**Comment by robdodson** [comment]
Thanks @Malvoz, I'm waiting on @kosamari to respond as she's topic owner. I'll reach out to her to see if she has a chance to look at this issue/PR.
