### ISSUE TITLE
Support for Dark Mode

### ISSUE THREAD

**Issue by demianrenzulli** [GoogleChrome/web.dev#6105]
**Is your feature request related to a problem? Please describe.**

It's not related to a problem, just a nice feature to have in the site.

**Describe the solution you'd like**

I know that Web.dev is not necessarily meant to implement every single feature we cover in the articles, but I thought that Dark Mode would be a good way to practice what we preach at a relatively low effort implementation. It would also help us demonstrate some best practices around it to help developers implement the same on their sites. 

**Describe alternatives you've considered**
There are several ways of doing this, many of them have been covered [here](https://web.dev/prefers-color-scheme/).

**Additional context**

The same goes for https://developer.chrome.com/

cc // @andreban @una @tomayac  @beverloo

**Comment by samthor** [comment]
We have plans for this. relevant #5374

**Comment by devnook** [comment]
Short update: This is in progress.
