### ISSUE TITLE
Explore a more JavaScript-centric rel=preload codelab

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web.dev#615]
**Page Affected:** https://web.dev/fast/preload-critical-assets/codelab-preload-critical-assets

**What needs to be done?**

Our current codelab around `<link rel=preload>` is great but could be better. It currently walks users through an example where JS is initially used to fetch CSS after which we switch over to using preload for the stylesheet instead. In practice, we see teams building apps more heavily using `<link rel=preload>` when they have scripts [vendor, app logic etc] that are critical for rendering the primary content on the page being loaded with a lower priority / later than they should.

It would be great if (when there's time) we could explore a refactor of this codelab. We could start off with an app where FCP and TTI aren't great because scripts aren't prioritized over other resources. We could then show how we improved this through `<link rel=preload>`. I would also love if we could try to keep prefetching separate from preload. It should probably be a separate guide where we can cross-reference between them if folks want to learn more.. :)

![image](https://user-images.githubusercontent.com/110953/52732432-0bf81e80-2f75-11e9-83b6-93c1c6a3ecbd.png)

**Comment by robdodson** [comment]
Going to close as stale. Happy to reopen if we get a concrete proposal.
