### ISSUE TITLE
send me all deleted file on my account meredith8meredith@gmail.com

### ISSUE THREAD

**Issue by cha17lie** [GoogleChrome/web.dev#6153]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by jpmedley** [comment]
Thank you for contacting us. Unfortunately, this is not a venue for help with gmail. Here is an article on [recovering emails](https://support.google.com/mail/answer/7401?hl=en) You can also post on the [Gmail Community](https://support.google.com/mail/community?hl=en) forum, which is monitored by Google employees.
