### ISSUE TITLE
The web.dev live code needs to be fixed.

### ISSUE THREAD

**Issue by digi-booster** [GoogleChrome/web.dev#6159]
**Describe the bug**
- CSS: speak: none; is not a speak value.
- Invalid href link: href=&bsol;"link.tld/query&bsol;"

**To Reproduce**
1. Go to 'https://web.dev/live/'
2. Click on 'view page source'
3. find to 'href=&bsol;"'
4. See an error

**Expected behavior**

- CSS:- speak: never;
- HTML:- href="link.tld/query"

**Screenshots**
![Screenshot (18)](https://user-images.githubusercontent.com/74658643/132442921-a33639ef-3252-41d6-9e32-5507cf133c2f.png)

**Comment by devnook** [comment]
Hi, 

Thanks for escalating. 
1. The HTML part works as intended. The links you see in the source are part of a JSON string and therefore their quotes need to be escaped.
2. The CSS part is fixed in the PR above.

Cheers!

**Comment by digi-booster** [comment]
Oh, I thought it was your server error or something, thank you!
