### ISSUE TITLE
Content Security Policy prevent patterns demo page to work properly

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/web.dev#6235]
**Describe the bug**
Content Security Policy prevent patterns demo page to work properly.

**To Reproduce**
1. Go to https://web.dev/patterns/web-vitals-patterns/carousels/carousel-autoplay/
2. Open JavaScript console from DevTools
3. `demo.html` fails to execute JavaScript because of the Content Security Policy. See error message below

`
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'strict-dynamic' 'sha256-1vXR78YtEYpuZYWhpSNFxaXfTJtlQSCVwdj9gtJSALg=' 'sha256-kg+4R55JyMlByJbRSACJpKDdrs7tgIdwQGHpfDTYZkg=' 'sha256-NQbPmO8f5P/P5YilP9vPLSefdlGHwm6fIEzH7lb11jA=' 'sha256-9FBkyWL+iGrJoGQ60dJZcgLSx70JpTxd6lJXlBMLgFI=' 'sha256-rsdLVIWrJVTWXLWDzh1BioA1YkBtUQAG+DiX8s7avp4=' 'sha256-CzQrDLO2G+xJ7XDEvN1aobq+NYBwPLQU132gkkGlBx4=' 'sha256-Ql9uUZbeAyr494Vb5lo16iTCyjHs7QoYebNCNnK2q1g=' 'sha256-sPzz3ZNvc6iZ6Yqs6qNpzWjD9jcoYeOGYRVr54/OTiQ=' 'sha256-nwHIQsFYGePqH/t4KMRhMH9tOtCfIaLhYVXxFQAQDVM=' 'sha256-sc7wUSxHlGwt6i8OvZfqeQxX+4kOUB5vVhXG8uGPwHk=' 'sha256-ZUzE1TqLzSBMX3pwpIAHWWGIw+3IH1/sT1xYwGA3QzI=' 'sha256-paKl15e+gQSg2YTLqea7KfWQeZ1e06Ijlu9tyQA3z9E=' 'sha256-HUx9ou9njnMC/hhkZLcOJy1imO3saeKtmJqdG8Mkb/8=' 'unsafe-inline' http: https:". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
`

**Expected behavior**
Demo should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/634478/133764160-ae087f07-f497-4d31-b8f9-be7fa24887f8.png)

**Comment by tomayac** [comment]
Just to be clear, this happens for all demos embedded on https://web.dev/patterns/web-vitals-patterns/.

**Comment by devnook** [comment]
This is because they use full-html demo instead of normal one. CSP is solved for normal demos but (apparently) not for full-html ones. Let me look into it.
