### ISSUE TITLE
Script to autofix non-conforming MDN URLs with locales in them

### ISSUE THREAD

**Issue by malchata** [GoogleChrome/web.dev#6276]
**Is your feature request related to a problem? Please describe.**
In response to #6133, a new linter rule was created to warn when MDN links contained locale info (e.g., the `en-US` in `https://developer.mozilla.org/en-US/docs/Glossary/Favicon`). In order to pass the lint rule, the locale must be removed so that MDN decides which locale it should redirect users to . For now, writers and developers have to do this manually.

**Describe the solution you'd like**
There should be an npm script or some other mechanism that searches for offending rules and then automatically fixes the problem.

**Describe alternatives you've considered**
It's possible we could do this in the lint task itself, but I'm not sure if parsing the Markdown AST back to Markdown after modification will result in formatting issues or other unwanted problems.

**Comment by devnook** [comment]
@malchata What do you think of combining this script with a broaden link checker tool? It is explained in more details here: https://github.com/GoogleChrome/web.dev/issues/1332

Other relates issues: #4469 #6172

**Comment by jpmedley** [comment]
This is still needed.
