### ISSUE TITLE
Get started tutorial - learn to build an interactive app

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#630]
The goal of this tutorial is to show developers how to build an interactive web application in 2019 that aligns with core principles that matter to end users. All modern web applications should be fast, reliable, secure, accessible, responsible, work offline, and be discoverable.

What developers will learn:
- How to build something that is fast, installable, works offline, is secure, accessible, responsible, and discoverable.
- How to follow modern development practices, using ES6 and build tools.
- How to test your site as you developer, and monitor the health of your site once it is live.

This interactive web app should cover user sign in, storage, controlling state, and other very important topics that are part of building modern web applications.

**Comment by Meggin** [comment]
@housseindjirdeh - just updating issues to make sure we have a burn-down list for Monday. I'm marking Google IO commitments as p0, but this one feels like it's more a p1-- most likely it will come after IO, but if we still get something in, we get something in.

**Comment by robdodson** [comment]
Going to close. I think we've pivoted our ideas here a bit, but we do plan to address this space in 2020.
