### ISSUE TITLE
Aliasing problem with images

### ISSUE THREAD

**Issue by aslamcode** [GoogleChrome/web.dev#6309]
**Describe the bug**
After 94.0.992.31 update the images in my application now have aliasing. 
In old versions of Chrome this doesn `t happen.

In old version of Microsoft Edge Chromium version 93.0.961.52 this doesn`t happen.

I don't no whats version of Google Chrome this doesn't happen. But a believe one or two versions before this doesn't happen.

**To Reproduce**

I used an SVG to reproduce the problem.
 
To reproduce the behavior load this HTML in new version 94.0.992.31 of chrome:

```

<html lang="pt-br" dir="ltr" style="width: 100%; height: 100%;">

  <body
    style="margin: 0; width: 100%; height: 100%; position: absolute; display: flex; align-items: center; justify-content: center">
        <img src="https://www.webascender.com/Portals/0/Blog/SVG-101/apple.svg" style="width: 50px; height: 50px">
  </body>

</html>
```

**Expected behavior**
The image was prettier. Now have ugly borders with aliasing.

**Screenshots**

_**Note: It's easier to see and compare old and new on a large monitor like 24 inches.**_

**### Old Chrome version**
![Old Version](https://user-images.githubusercontent.com/32587314/135335429-f64c7597-d43c-4828-a7e5-6b0a14a9cc33.jpeg)

**### New Chrome version**
![New Version](https://user-images.githubusercontent.com/32587314/135335335-106971c2-43e3-4138-98f1-7917a96e5d99.png)

**Comment by devnook** [comment]
Hi @aslamcode ! It seems that this bug is related to Chromium, and not we.dev website. Please submit the bug report here instead: https://bugs.chromium.org/p/chromium/issues/list
