### ISSUE TITLE
Trust Token Demo Has 3  js errors in Chrome 94

### ISSUE THREAD

**Issue by 3mrfouad** [GoogleChrome/web.dev#6319]
**Describe the bug**
When trying the trust token demo, the issuer demo stuck at issuing token step. Looking at the dev tools found 3 js errors

**To Reproduce**
1. Go to https://trust-token-issuer-demo.glitch.me/
2. Click on Yes! I'm a human
3. Open dev tools
4. See errors (3 errors)

**Expected behavior**
Demo to issue trust token

**Screenshots**

![image](https://user-images.githubusercontent.com/68440701/135524899-2da340da-29ff-41ae-aff9-09f2ef6a31d6.png)

**Comment by mihajlija** [comment]
Paging @samdutton to take a look

**Comment by samdutton** [comment]
Apologies for the error!

Chrome now uses [TrustTokenV3](https://bit.ly/what-is-trusttokenv3). These demos are being updated to work with that implementation.

I've added a warning to this page: https://trust-token-demo.glitch.me, but we should also add a warning to the page you mention, i.e. https://trust-token-issuer-demo.glitch.me. @JackJey FYI

**Comment by JackJey** [comment]
Updating to v3 is on my list.
I'll add warning to every page until it's done.

**Comment by samdutton** [comment]
Thanks Jack!
