### ISSUE TITLE
Get started tutorial - learn to build your first profile site

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#632]
The goal of this tutorial is to show developers how to build their first profile site in 2019 that aligns with core principles that matter to end users. All modern sites should be fast, reliable, secure, accessible, responsible, work offline, and be discoverable.

What developers will learn:

* How to build a simple profile site that is fast, installable, works offline, is secure, accessible, responsible, and discoverable.
* How to follow modern development practices, using ES6 and build tools.
* How to test your site as you developer, and monitor the health of your site once it is live.

We will introduce the basics of responsive design, linking off to new doc set that dives deeper into creating smooth UI.

**Comment by robdodson** [comment]
Going to close. I think we've pivoted our ideas here a bit, but we do plan to address this space in 2020.
