### ISSUE TITLE
content: Image Lazy Loading demo doesn't use lazy loading pattern described in the article

### ISSUE THREAD

**Issue by djphan** [GoogleChrome/web.dev#6331]
### What page(s) need to be updated?
In: https://web.dev/browser-level-image-lazy-loading/

Specifically the section https://web.dev/browser-level-image-lazy-loading/#how-do-i-handle-browsers-that-don't-yet-support-lazy-loading pointing to the firebase demo app: https://lazy-loading.firebaseapp.com/lazy_loading_lib.html showing the JS snippet about loading lazySizes vs using loading.

The demo branch doesn't use the javascript pattern outlined. On Chrome Version 94.0.4606.61 the demo only loads the image using lazySizes library but doesn't replace the image src field per snippet. It doesn't even use the loading attribute as seen in the screenshot.

![Screen Shot 2021-10-01 at 11 17 37](https://user-images.githubusercontent.com/6673572/135661378-ea74dedc-4cc1-4651-ac69-a2f68820e7ca.png)

### Why is this update needed?

This is confusing to the reader as this suggested solution isn't in the example for Chrome. This example is just a good example of lazySzes working in Chrome though. Since this is an article about how to fall back to lazySizes but also use the loading attribute I can only assume the example suggests to just use lazySizes. 

### What's the deadline?
Recommended when the doc maintainers can update the example

**Comment by jpmedley** [comment]
@mathiasbynens, @addyosmani, and @housseindjirdeh, can one of you help us out?

**Comment by mathiasbynens** [comment]
Unassigning myself as I don't own the Firebase-hosted demo. Houssein, Addy, do you have access to this?
