### ISSUE TITLE
E-commerce guide - Get started selling online

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#635]
This is part of the Introduction to e-commerce section, that covers how to sell online.

First version of the guide will be in the e-commerce guide Drive folder.

**Comment by Meggin** [comment]
Rowan, Sam, we need to add tsteiner and ajkent to our GitHub org, so that this issue can be assigned to them.

**Comment by samdutton** [comment]
Draft ready for tech writer review.

**Comment by Meggin** [comment]
@samdutton and @rowan-m - I'm changing the labels on all doc issues. I'm also closing most of the e-commerce issues that were part of v1 launch with the hope of hitting the reset button. Feel free to re-open this issue if you want to keep it up as a content request for e-commerce docs.
