### ISSUE TITLE
`BrowserCompat` doesn't support `http` MDN compatibility data

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#6353]
**Describe the bug**
When trying to load browser compatibility data with `BrowserCompat` widget, entering `http` data, for example `http.headers.content-security-policy` won't render the widget.

**To Reproduce**
1. Insert `{% BrowserCompat 'http.headers.content-security-policy' %}` to somewhere (outside of `Details` clause to avoid encountering another issue).
2. Locally render it
3. No widget will be displayed.

**Expected behavior**
A browser compatibility widget will be displayed.

**Comment by devnook** [comment]
Hi Eiji,

The browser compat data for this feature is here: https://github.com/mdn/browser-compat-data/blob/main/http/headers/content-security-policy.json

So the correct path would be: 

`{% BrowserCompat 'http.headers.csp.Content-Security-Policy' %}
`
