### ISSUE TITLE
Phishing attempt at google web.dev page

### ISSUE THREAD

**Issue by GrazielyTukozaki** [GoogleChrome/web.dev#6356]
**Describe the bug**

When i entered at the page https://web.dev/responsive-web-design-basics/#optimize-text-for-reading my antivirus alerted me from a malicious threatening of phising. I use Avast antivirus.

**To Reproduce**
1. Go to https://web.dev/responsive-web-design-basics/#optimize-text-for-reading
2. Have an browser antivirus installed
3. Scroll down the page
4. See the antivirus alerts

**Expected behavior**
An alert of a malicious threatening of phising

**Screenshots**
<img width="1440" alt="Captura de Tela 2021-10-06 às 17 01 21" src="https://user-images.githubusercontent.com/71033705/136388913-0a82f784-afad-411d-b2e6-9b0772cba2c3.png">
<img width="1438" alt="Captura de Tela 2021-10-06 às 17 00 29" src="https://user-images.githubusercontent.com/71033705/136388957-fbc0d8be-8d80-446c-8782-d106b0a1c702.png">
<img width="1437" alt="Captura de Tela 2021-10-06 às 17 00 20" src="https://user-images.githubusercontent.com/71033705/136388967-696eec8d-3658-460f-bd59-d2dfb1b8e96b.png">

**Comment by robdodson** [comment]
Looking at the screenshot, it seems to be complaining about cdn.glitch.me but it's not clear what it thinks Glitch has done wrong. We use Glitch for the interactive embeds. @GrazielyTukozaki can you help translate those screenshots to tell us if it says anything about what it thinks Glitch needs to change?
