### ISSUE TITLE
content: browser-level lazy-loading and scripting disabled

### ISSUE THREAD

**Issue by Malvoz** [GoogleChrome/web.dev#6357]
### What page(s) need to be updated?

https://web.dev/browser-level-image-lazy-loading/

### Why is this update needed?

Incorrect information, I believe.

https://web.dev/browser-level-image-lazy-loading/#why-browser-level-lazy-loading:

> Browser-level lazy loading also ensures that deferred loading of images still works even if JavaScript is disabled on the client.

The HTML spec states in https://html.spec.whatwg.org/multipage/urls-and-fetching.html#will-lazy-load-element-steps:

> The **will lazy load element steps**, given an element element, are as follows:
> 
> 1. If [scripting is disabled](https://html.spec.whatwg.org/multipage/webappapis.html#concept-n-noscript) for element, then return false.
>

> 
> This is an anti-tracking measure, because if a user agent supported lazy loading when scripting is disabled, it would still be possible for a site to track a user's approximate scroll position throughout a session, by strategically placing images in a page's markup such that a server can track how many images are requested and when.

#### Is it a hard deadline?

No.

**Comment by robdodson** [comment]
Assigning to @housseindjirdeh @addyosmani @mathiasbynens to take a look
