### ISSUE TITLE
E-commerce codelab -  Make your e-commerce site search friendly

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#638]
This is part of the e-commerce Discovery section, covering how to build a web presence.

First version of the codelab will be in the e-commerce codelab Drive folder.

**Comment by Meggin** [comment]
Rowan, Sam, we need to add johnmu, tomgreenaway, and mmoevato our GitHub org, so that this issue can be assigned to them.

**Comment by samdutton** [comment]
Tom can no longer do this. Have requested new author — awaiting response.

**Comment by samdutton** [comment]
No author available for this — I'll move to possible future content.

**Comment by Meggin** [comment]
@samdutton - I'm changing the labels on all doc issues. I'm also closing most of the e-commerce issues that were part of v1 launch with the hope of hitting the reset button. Feel free to re-open this issue if you want to keep it up as a content request for e-commerce docs.
