### ISSUE TITLE
content: [handbook] How tech writing team uses GitHub

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/web.dev#6381]
Document our GitHub workflow:

- batching suggestions
- applying labels
- draft mode
- required checks
- dismissing a review
- and more

**Comment by samthor** [comment]
Does this need a better title?

**Comment by mihajlija** [comment]
@samthor Fixed, thanks for flagging it!

**Comment by rachelandrew** [comment]
@mihajlija I'm adding this information to the document I'm currently working on as I bring Terry into our processes. So just checking whether you have existing work on this or are happy to assign it to me (or not) as part of your changed focus?

**Comment by mihajlija** [comment]
Draft and outline here: [How we work](https://docs.google.com/document/d/1Sgz5_8VxItFtIO_6W2D2Ni9oZxZA1BirPC85aD4UxOQ/edit?resourcekey=0-VJqob8uK0VdCHq5ZTzNXsQ#)

**Comment by AaronForinton** [comment]
Closing as per conversation with @heyawhite, content is now available
