### ISSUE TITLE
E-commerce guide & codelab - Add search to your website

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#639]
This is part of the e-commerce Discovery section, covering how to build effective search within your site.

First version of the guide will be in the e-commerce guide Drive folder.

First version of the codelab will be in the e-commerce codelab Drive folder.

**Comment by Meggin** [comment]
[Current WIP outline for the guide](https://docs.google.com/document/d/1n-mrtHFE0YcqP1T9MWiAfyxLBNcBmuWKocaQiu0zsDE/edit#heading=h.7mtr70nlpd92).

**Comment by samdutton** [comment]
The outline is close to draft format, but it's nearly 3k words in length.

I think we should prune the outline and divide this guide into two sections:
• Add search to your website
• Choose a full text search engine

**Comment by Meggin** [comment]
That makes sense to me. Would it help to do first review in full format, and reviewer (AKA me), can help chunk it up?

**Comment by samdutton** [comment]
Sounds good — thanks.

**Comment by samdutton** [comment]
Draft ready for tech writer review.

Now in two parts, as agreed.

**Comment by Meggin** [comment]
Updated priority, as this is planned for Google IO. Special note that we will publish guides as blogs in series.

**Comment by Meggin** [comment]
@samdutton - I'm changing the labels on all doc issues. I'm also closing most of the e-commerce issues that were part of v1 launch with the hope of hitting the reset button. Feel free to re-open this issue if you want to keep it up as a content request for e-commerce docs.
