### ISSUE TITLE
E-commerce guide & codelab - Build a great search box

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#640]
This is part of the e-commerce Discovery section, covering how to build effective search within your site.

First version of the guide will be in the e-commerce guide Drive folder. 

First version of the codelab will be in the e-commerce codelab Drive folder.

**Comment by Meggin** [comment]
[Current WIP outline for the guide](https://docs.google.com/document/d/1n-mrtHFE0YcqP1T9MWiAfyxLBNcBmuWKocaQiu0zsDE/edit#heading=h.7mtr70nlpd92).

**Comment by samdutton** [comment]
Outline drafted. 

Adapted from an article I wrote, so shouldn't need too much work to turn into a guide.

Awaiting reviewer availability ;).

**Comment by Meggin** [comment]
Just to confirm-- this one is ready for first review? I went and added an r1 label, so I know it's ready for some eyes. I should be able to get to it next week. Today is crazy.

**Comment by samdutton** [comment]
@rowan-m has agreed to review this, but he's been a tad busy recently ;).

If someone else could take a look (as well), that would be great.

**Comment by samdutton** [comment]
Draft ready for tech writer review.

Too long at the moment — looking for ways to cut down size or divide.

**Comment by Meggin** [comment]
Updated priority, as this is planned for Google IO. Special note that we will publish guides as blogs in series.

**Comment by Meggin** [comment]
@samdutton - I'm changing the labels on all doc issues. I'm also closing most of the e-commerce issues that were part of v1 launch with the hope of hitting the reset button. Feel free to re-open this issue if you want to keep it up as a content request for e-commerce docs.
