### ISSUE TITLE
E-commerce guide & codelab - Successful search results

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#641]
This is part of the e-commerce Discovery section, covering how to build effective search within your site.

First version of the guide will be in the e-commerce guide Drive folder.

First version of the codelab will be in the e-commerce codelab Drive folder.

**Comment by samdutton** [comment]
Outline drafted — pretty close to draft guide format (including images and screenshots).

Awaiting reviewer availability ;).

**Comment by Meggin** [comment]
I've added r1 label so we know this is ready for first round of reviews. I should be able to get time to do this next week.

**Comment by samdutton** [comment]
Draft ready for  tech writer review.

**Comment by Meggin** [comment]
Updated priority, as this is planned for Google IO. Special note that we will publish guides as blogs in series.

**Comment by Meggin** [comment]
@samdutton - I'm changing the labels on all doc issues. I'm also closing most of the e-commerce issues that were part of v1 launch with the hope of hitting the reset button. Feel free to re-open this issue if you want to keep it up as a content request for e-commerce docs.
