### ISSUE TITLE
E-commerce guide & codelab - Build offline search

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#642]
This is part of the e-commerce Discovery section, covering how to build effective search within your site.

First version of the guide will be in the e-commerce guide Drive folder.

First version of the codelab will be in the e-commerce codelab Drive folder.

**Comment by samdutton** [comment]
Outline not yet written.

Might be better to postpone this to the second release of content. Offline search is an interesting topic, and I've done a lot of research and built a demo app, but it's not really a core topic for e-commerce.

**Comment by samdutton** [comment]
Draft ready for  tech writer review.

**Comment by Meggin** [comment]
@samdutton - I'm changing the labels on all doc issues. I'm also closing most of the e-commerce issues that were part of v1 launch with the hope of hitting the reset button. Feel free to re-open this issue if you want to keep it up as a content request for e-commerce docs.
