### ISSUE TITLE
E-commerce guide - Successful navigation for e-commerce

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#644]
This is part of the e-commerce Discovery section, covering how to create successful navigation.

First version of the guide will be in the e-commerce guide Drive folder.

**Comment by samdutton** [comment]
Outline not yet written.

**Comment by Meggin** [comment]
@samdutton and @rowan-m - I'm changing the labels on all doc issues. I'm also closing most of the e-commerce issues that were part of v1 launch with the hope of hitting the reset button. Feel free to re-open this issue if you want to keep it up as a content request for e-commerce docs.
