### ISSUE TITLE
E-commerce guide - Beautiful, efficient images for e-commerce

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#646]
This is part of the e-commerce Acquisition & engagement section, covering images for e-commerce.

First version of the guide will be in the e-commerce guide Drive folder.

**Comment by samdutton** [comment]
Outline reviewed and approved.

Draft in progress.

**Comment by samdutton** [comment]
Draft ready for  tech writer review.

**Comment by Meggin** [comment]
Updated priority, as this is planned for Google IO. Special note that we will publish guides as blogs in series.

**Comment by Meggin** [comment]
@samdutton - I'm changing the labels on all doc issues. I'm also closing most of the e-commerce issues that were part of v1 launch with the hope of hitting the reset button. Feel free to re-open this issue if you want to keep it up as a content request for e-commerce docs.
