### ISSUE TITLE
'Check your understanding' doesn't scroll to correct answer

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/web.dev#6463]
On [web.dev/learn/forms/form](https://web.dev/learn/forms/form/):

1. Go to ** Check your understanding**.
2. Click on `<form>` (the correct answer).
3. Click **Check** button.

Widget should scroll to the correct answer, but it doesn't. (Ideally, only the correct answer would be displayed.)

Same for other pages that use the same widget.

Also, the **Check** button doesn't render properly once it's clicked (see screenshot below).

![image](https://user-images.githubusercontent.com/205226/137959720-a1753534-f044-4f97-a2c2-6bcd0faabb1b.png)

@beaufortfrancois @rachelandrew @justmarkup fyi

**Comment by MichaelSolati** [comment]
@samdutton it looks like the button issue has been resolved as we no longer use the icon, just text. As for the scroll, PR #6835 should fix that.

**Comment by samdutton** [comment]
Thanks Michael!
