### ISSUE TITLE
E-commerce guide - Reliability and performance for e-commerce websites

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#648]
This is part of the e-commerce Acquisition & engagement section, covering how to make your e-commerce site faster and more reliable.

First version of the guide will be in the e-commerce guide Drive folder.

**Comment by samdutton** [comment]
Outline in review.

**Comment by samdutton** [comment]
Need new author — checking if Kate can work on this.

**Comment by Meggin** [comment]
@samdutton - I'm changing the labels on all doc issues. I'm also closing most of the e-commerce issues that were part of v1 launch with the hope of hitting the reset button. Feel free to re-open this issue if you want to keep it up as a content request for e-commerce docs.
