### ISSUE TITLE
E-commerce codelab - Content caching for e-commerce

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#650]
This is part of the e-commerce Acquisition & engagement section, covering how to make your e-commerce site faster and more reliable.

First version of the codelab will be in the e-commerce codelab Drive folder.

**Comment by samdutton** [comment]
Outline in review.

**Comment by samdutton** [comment]
Need new author — checking if Kate can work on this.

**Comment by Meggin** [comment]
@samdutton and @rowan-m - I'm changing the labels on all doc issues. I'm also closing most of the e-commerce issues that were part of v1 launch with the hope of hitting the reset button. Feel free to re-open this issue if you want to keep it up as a content request for e-commerce docs.
