### ISSUE TITLE
<share-action> button gray out on hover

### ISSUE THREAD

**Issue by aungkyawhein** [GoogleChrome/web.dev#6506]
**Describe the bug**

The share button at the bottom right corner of [LCP Lazy Loading page](https://web.dev/lcp-lazy-loading/) gray out on hover state.

**To Reproduce**

1. Go to https://web.dev/lcp-lazy-loading
2. Mouse over on share button at the bottom right corner
4. See error (share button is on top of subscribe button)

**Expected behavior**

The share icon and text shouldn't disappear. If you want to gray out, only the background color should be updated.

**Screenshots**

![image](https://user-images.githubusercontent.com/1414557/138311507-1a8513de-151f-496e-a563-96b39bd167b0.png)

**Source of the issue**

The issue is because of this filter invert CSS.
```
share-action:hover {
    filter: invert(.5);
}
```

**Comment by devnook** [comment]
This is fixed now.
