### ISSUE TITLE
E-commerce codelab - Data caching for e-commerce

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#651]
This is part of the e-commerce Acquisition & engagement section, covering how to make your e-commerce site faster and more reliable.

First version of the codelab will be in e-commerce codelab Drive folder.

**Comment by samdutton** [comment]
@devnook won't be able to work on this. 

We'll need to postpone or get someone else to write it.

**Comment by Meggin** [comment]
I'm move this out of v1 milestone. We can target for next milestone.

**Comment by Meggin** [comment]
@samdutton - I'm changing the labels on all doc issues. I'm also closing most of the e-commerce issues that were part of v1 launch with the hope of hitting the reset button. Feel free to re-open this issue if you want to keep it up as a content request for e-commerce docs.
