### ISSUE TITLE
E-commerce codelab - How to code shopping cart icons

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#653]
This is part of the Acquisition & engagement section, covering shopping cart best practices.

First version of the codelab will be in the e-commerce codelab Drive folder.

**Comment by samdutton** [comment]
Outline reviewed and approved.

Draft in progress, code sample complete.

**Comment by Meggin** [comment]
Updated priority, as this is planned for Google IO. Special note that we will publish guides as blogs in series.

**Comment by Meggin** [comment]
@samdutton - I'm changing the labels on all doc issues. I'm also closing most of the e-commerce issues that were part of v1 launch with the hope of hitting the reset button. Feel free to re-open this issue if you want to keep it up as a content request for e-commerce docs.
