### ISSUE TITLE
E-commerce guide & codelab - Reduce form friction: simple techniques to improve conversion

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#654]
This is part of the Conversion section, covering reducing form friction.

First version of the guide will be in the e-commerce guide Drive folder.

First version of the codelab will be in e-commerce codelab Drive folder.

**Comment by Meggin** [comment]
Sam, we may need to add mdiblasio to our organization so we can assign this issue.

**Comment by samdutton** [comment]
Outline written and currently in third round of reviews.

**Comment by Meggin** [comment]
Updated priority, as this is planned for Google IO. Special note that we will publish guides as blogs in series.

**Comment by Meggin** [comment]
@samdutton - keeping this one open, as we may be able to deliver at least some of the form content in a blog.

**Comment by samdutton** [comment]
@Meggin Sure — I'll look at this again this week.

**Comment by robdodson** [comment]
Going to close as stale but Kayce would like to take a look at the content that was written to see if we can potentially rework it.
