### ISSUE TITLE
E-commerce guide & codelab - Checkout best practice

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#655]
This is part of the Conversion section, covering checkout best practices.

First version of the guide will be in the e-commerce guide Drive folder.

First version of the codelab will be in e-commerce codelab Drive folder.

**Comment by Meggin** [comment]
Sam, we may need to add ajkent to our organization so we can assign this issue. to our organization so we can assign this issue.

**Comment by samdutton** [comment]
Outline under discussion, not written yet.

**Comment by samdutton** [comment]
Draft has had technical review.

Ready for  tech writer review.

**Comment by Meggin** [comment]
@samdutton - I'm changing the labels on all doc issues. I'm also closing most of the e-commerce issues that were part of v1 launch with the hope of hitting the reset button. Feel free to re-open this issue if you want to keep it up as a content request for e-commerce docs.
