### ISSUE TITLE
Search icon in top nav search box has wrong focus styles

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/web.dev#6554]
Search icon in top nav search box has wrong focus styles:
<img width="866" alt="Screenshot 2021-10-28 at 09 34 20" src="https://user-images.githubusercontent.com/1914261/139208835-2839aa1d-b703-4f4f-8f2f-4dd30891fea7.png">

**Comment by hankchizljaw** [comment]
Will be fixed with  #6847
