### ISSUE TITLE
E-commerce guide & codelab - Payment best practice

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#656]
This is part of the Conversion section, covering payment best practices.

First version of the guide will be in the e-commerce guide Drive folder.

First version of the codelab will be in the e-commerce codelab Drive folder.

**Comment by samdutton** [comment]
Outline drafted and reviewed, and currently in second round of reviews.

**Comment by samdutton** [comment]
Draft completed.

**Comment by Meggin** [comment]
@samdutton and @agektmr - do we still want to try and land payment content? Is there a need to re-think post-IO? Keeping the issue open to get a feeling for what you want to do. Changing labels though.

**Comment by samdutton** [comment]
Would be great to get e-commerce payment content of some kind.

@agektmr — is this something you can take on at the moment?

**Comment by agektmr** [comment]
Unfortunately, I don't think enough bandwidth to work on this anytime soon.

**Comment by robdodson** [comment]
Going to close as stale. See #654.
