### ISSUE TITLE
content: Notification best practices

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#657]
**Author**: @katejeffreys 
**Reviewer**: @jpmedley 

**A one to two sentence description of your post**

Use of notifications to encourage re-engagement.

**Target publish date:** `<2019-08-14>`

- [ ] Check this box if this is a hard deadline.

**Process**

Take a moment to look over the [web.dev handbook](https://web.dev/handbook) and
familiarize yourself with the process.

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal [doc link](https://docs.google.com/document/d/1MPa0w7OQUMbSe0DP2x3QyktkL9saSIgMMDs_2h86Tu4)
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #1231
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by Meggin** [comment]
This issue should be re-assigned to Kate Jeffreys, once she's accepted invite to org.

**Comment by samdutton** [comment]
Outline drafted and reviewed.

Draft in progress.

**Comment by samdutton** [comment]
Draft completed by Kate and reviewed by Sam.

**Comment by Meggin** [comment]
Updated priority, as this is planned for Google IO. Special note that we will publish guides as blogs in series.

**Comment by Meggin** [comment]
@samdutton - keeping this one open, as Kate is still working on it. Changing labels.

**Comment by carolrivero** [comment]
Ready for review.

**Comment by robdodson** [comment]
@mfriesenhahn to touch base with folks regarding this doc and #658

**Comment by carolrivero** [comment]
@katejeffreys - Please provide an update. Thanks.

**Comment by mfriesenhahn** [comment]
Closing since the notifications IA has changed, closing this ticket. We can create new tickets for the notifications posts once we know what they are.

**Comment by mfriesenhahn** [comment]
Since the notifications IA has changed, closing this ticket. We can create new tickets for the notifications posts once we know what they are.
