### ISSUE TITLE
Learn course's Test panel shows 'incorrect' even when answer is correct

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChrome/web.dev#6571]
**Describe the bug**
The tests on the learn page show all the inccorrect answers even when you've selected the correct one.

**To Reproduce**
Go to the learn course for forms, click on the first topic and then take the test... It says Correct and shows "Incorrect" answers too.

**Expected behavior**
I'd expect it to just say "Correct" or "Incorrect" on the option that was chosen so that I can pick again if needed.

**Screenshots**

![Screenshot 2021-10-28 21 49 41](https://user-images.githubusercontent.com/45510/139333700-19e1aa9d-b38e-474e-8ed5-32c361cf516c.png)

**Comment by rachelandrew** [comment]
@devnook I'm not sure who is best to look at this but they are behaving pretty strangely having just gone through the forms ones to check them.
