### ISSUE TITLE
When you click "Check" on the test panel in the learn page the button goes weird

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChrome/web.dev#6573]
**Describe the bug**
When you click "Check" on the test panel in the learn page the button goes weird

**To Reproduce**
Go to the test widget, click "Check" and then you see the next button appear, however the "Check" button has a very weird style (almost like a broken ripple effect)

**Expected behavior**
The check button shouldn't look like that, I would expect it to still be visible,

**Screenshots**
Check the bottom right.

![Screenshot 2021-10-28 21 49 41-2](https://user-images.githubusercontent.com/45510/139334134-ac3a2b24-85df-4680-8cac-46761648bc18.png)
.

**Comment by rachelandrew** [comment]
@andy-piccalilli is this another regression? It's happening on all of the courses.

**Comment by andy-piccalilli** [comment]
Yeh unfortunately it's what I call a Zombie component: half dead (from the old system) and half alive (from the new system). I'll put some sticky tape on it.
