### ISSUE TITLE
[priority-hints] duplicate fetches

### ISSUE THREAD

**Issue by yinonov** [GoogleChrome/web.dev#6575]
##### * Not sure if this is a chrome, devtools or a post (least likely) issue. please transfer issue if find more relevant elsewhere.

**Describe the bug**
Following [priority-hints](https://web.dev/priority-hints/) post, preloaded links result in duplicate fetches

**To Reproduce**
I have a plain `index.html` with a single [import with side effects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#import_a_module_for_its_side_effects_only) dynamically loading font and a module script handling inline styling.
These resources are critical for the page to render as desired but discovered late, resulting in FOUC.

as guided, here are the preloading `link` tags
```html
<link rel="preload" as="font" href="https://fonts.resources.vonage.com/fonts/v1/Spezia_Web_Complete_Upright.woff2" importance="high">
<link rel="preload" href="http://localhost:8000/common/scheme/scheme.light.css.js" as="script" importance="low">
```

**Expected behavior**
should be only 1 fetch call of each file in devtools

**Screenshots**
![image](https://user-images.githubusercontent.com/15140652/139388428-dbdcd7ac-ed8c-4fdf-a1cd-5d98afe4c58d.png)

same thing goes with fonts
![image](https://user-images.githubusercontent.com/15140652/139388610-0bde808a-ad62-48f9-b7e0-d07ab5ae78f7.png)

**Environment**
macOS Big Sur version 11.6
Canary (x86_64) version 97.0.4684.2 (Official Build)
@web/dev-server running an index.html

**Comment by yinonov** [comment]
Both. The module as well

**Comment by yinonov** [comment]
oh I remember that post, yeah, `modulepreload` does "fix" it as well, but adopting it brings up some questions -

- `modulepreload` have been around chrome for quite a while but never picked up by safari/firefox
- why are there 2 different ways to prioritize a module
```html
<link rel="preload" crossorigin="anonymous" href="some-module.js" as="script" importance="high">
// or
<link rel="modulepreload" href="some-module.js">
```
- if `modulepreload` exist, why not `stylesheetpreload`? isn't the "as" attribute dedicated to choosing the type?

**Comment by malchata** [comment]
Ah, so I take it that your module script was loaded with `<script type="module">`? If so, there are different preloading concerns. Per the explainer I linked on `modulepreload` above:

> it turns out that a `<script type="module">` with no `crossorigin` attribute indicates a credentials mode of `omit`, which doesn't exist for `<link rel="preload">. This means that you would have to change the `crossorigin` attribute in both your `<script>` and `<link>` to one of the other values, and you might not have an easy way of doing so if what you're trying to preload is a dependency of other modules.

[This section](https://developers.google.com/web/updates/2017/12/modulepreload) of the linked explainer goes into a bit more detail. There's also the issue of module dependencies—that is, if your module script `import`s other modules. `modulepreload` is supposed to recursively preload the entire module tree.

Hope that explains things a bit better!

**Comment by yinonov** [comment]
Ok that totally clears it. Any expectation on `modulepreload` broader support by browsers?

And here's the [part clearing the double fetch issue](https://developers.google.com/web/updates/2017/12/modulepreload#ok_so_why_doesnt_link_relpreload_work_for_modules)

**Comment by malchata** [comment]
Gecko and Webkit currently have issues open, but there doesn't appear to be much movement on either:
- [Gecko issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1425310).
- [Webkit issue](https://bugs.webkit.org/show_bug.cgi?id=180574).

For now, you could use `modulepreload` as a progressive enhancement. Non-supporting browsers will receive a potentially slower experience, but errors shouldn't occur for unrecognized `<link>` element `rel` values.

I'll close this issue. Thanks!
