### ISSUE TITLE
content: Make the most of notifications

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#658]
**Author**: @katejeffreys
**Reviewer**: @mihajlija

**A one to two sentence description of your post**

Use of notifications to encourage re-engagement.

**Target publish date:** `<2019-08-14>`

- [X] Check this box if this is a hard deadline.

**Process**

Take a moment to look over the [web.dev handbook](https://web.dev/handbook) and
familiarize yourself with the process.

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1ydauCufwwavStaKxhIDHuNivVxgQBOdDno4uLjGIjmE/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [x] 1. I've done my proposal [doc link](https://docs.google.com/document/d/1xmwwAJwR2MwbUcawwpar5ZNipNhrgdnRfo4CPmNEkSY)
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request `#<add PR number>`
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by Meggin** [comment]
This issue should be re-assigned to Kate Jeffreys, once she's accepted invite to org.

**Comment by samdutton** [comment]
Outline drafted and reviewed.

Draft in progress.

**Comment by samdutton** [comment]
Draft completed by Kate and reviewed by Sam.

**Comment by Meggin** [comment]
Updated priority, as this is planned for Google IO. Special note that we will publish guides as blogs in series.

**Comment by Meggin** [comment]
@samdutton - not sure if this is one of Kate's notification guides. If it's covered in a different issue, we may want to close this.

**Comment by samdutton** [comment]
@Meggin Yes: this is also one of Kate's.

**Comment by carolrivero** [comment]
On track - need to finish review today

**Comment by carolrivero** [comment]
Need to take over-all look at IA so waiting for content lead to accept proposal

**Comment by samdutton** [comment]
I added comments to #1231 — let me know if I need to do anything else.

**Comment by mfriesenhahn** [comment]
Since the notifications IA has changed, closing this ticket. We can create new tickets for the notifications posts once we know what they are.
