### ISSUE TITLE
E-commerce guide - Measure notification impact

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#659]
This is part of the Retention section, covering use of notifications to encourage re-engagement.

The guide first draft will be in the Retention folder inside the e-commerce guide folder in Drive.

**Comment by Meggin** [comment]
This issue should be re-assigned to Kate Jeffreys, once she's accepted invite to org.

**Comment by samdutton** [comment]
Draft completed by Kate and reviewed by Sam.

**Comment by Meggin** [comment]
Updated priority, as this is planned for Google IO. Special note that we will publish guides as blogs in series.

**Comment by Meggin** [comment]
@samdutton - can we close this one? I know Kate has two notification guides in the work-- but not sure about this one.

**Comment by samdutton** [comment]
@Meggin I think we should keep this open. Draft is completed and LGTM. Need a PR for the content.

**Comment by robdodson** [comment]
Going to close as stale. See #654
