### ISSUE TITLE
Stats and columns component are not rendering in the Learn courses

### ISSUE THREAD

**Issue by rachelandrew** [GoogleChrome/web.dev#6596]
We tried to use the stats and the column components, and they don't seem to be rendering with the new CSS (within courses at least). I don't currently have a live example of this, as I'm working locally. I can update here once this PR preview is up though if it helps.

**Comment by andy-piccalilli** [comment]
The shortcode will need to be updated to use the new design system component. I also need to do the compare shortcode too.

Which module is using the stats component?

**Comment by rachelandrew** [comment]
It's in one of the Learn PWA ones, but I don't have the PR in preview yet

**Comment by rachelandrew** [comment]
In the same modules I can see that blockquotes are rendering in a very strange way, give me a few minutes and I'll push this up as it will be easier to see.

**Comment by rachelandrew** [comment]
https://github.com/GoogleChrome/web.dev/pull/6598

/learn/pwa/progressive-web-apps has columns and stats.

/learn/pwa/foundations has ginormous blockquotes.

@andy-piccalilli

**Comment by andy-piccalilli** [comment]
Ah lovely, thanks, Rachel. We're gonna see a few of these little teething issues as we roll this lot out :)

**Comment by rachelandrew** [comment]
It looks like the browser support component also has no styling in courses.

**Comment by rachelandrew** [comment]
@andy-piccalilli if any of these are not quickly fixable, as in before these launch tomorrow night, let me know as I'll reformat them to avoid using things that will look unstyled.

**Comment by andy-piccalilli** [comment]
As I said in our call, I'll get the stats and compare sorted. We'll get the browser compat stuff done post-CDS when there's less time pressure 👍

**Comment by andy-piccalilli** [comment]
For stats, @rachelandrew, use the newer markup: 

```html
<ul class="stats auto-grid bg-state-good-bg color-state-good-text">
  <div class="stats__item flow">
    <p class="font-brand text-size-6">
      30
      <sub>%</sub>
    </p>
    <p>Lower cost per conversion</p>
  </div>
  <div class="stats__item flow">
    <p class="font-brand text-size-6">
      13
      <sub>%</sub>
    </p>
    <p>Higher CTR</p>
  </div>
  <div class="stats__item flow">
    <p class="font-brand text-size-6">
      4
      <sub>x</sub>
    </p>
    <p>Faster load times</p>
  </div>
</ul>
```

[More info here](https://web.dev/design-system/component/stats/).

We’ll need to update the handbook for that one.

**Comment by rachelandrew** [comment]
We probably don't want to update the handbook yet as the blog is still using the old style. Maybe I'll start a PR of handbook changes to merge at that point?

**Comment by andy-piccalilli** [comment]
Good shout

**Comment by andy-piccalilli** [comment]
For columns, you should be able to replace `w-columns` with `switcher`: https://web.dev/design-system/css-compositions/#switcher

**Comment by andy-piccalilli** [comment]
That PR accounts for the blockquote cite being wrapped in `<p>` elements, thanks to markdown processing.
