### ISSUE TITLE
E-commerce guide & codelab - Enable users to configure notifications

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#660]
This is part of the Retention section, covering use of notifications to encourage re-engagement.

The guide & codelab will be in the Rention folder inside the e-commerce guide folder in Drive.

**Comment by Meggin** [comment]
This issue should be re-assigned to Kate Jeffreys, once she's accepted invite to org.

**Comment by samdutton** [comment]
Outline drafted and reviewed.

Draft in progress.

**Comment by samdutton** [comment]
Draft completed by Kate and reviewed by Sam.

**Comment by Meggin** [comment]
Updated priority, as this is planned for Google IO. Special note that we will publish guides as blogs in series.

**Comment by Meggin** [comment]
@samdutton - is this one of Kate's guides that we hope to still land? Keeping open for now.

**Comment by samdutton** [comment]
@Meggin Yup — this is one of Kate's.

**Comment by robdodson** [comment]
Going to close as stale. See #654.
Kate did create notifications content so perhaps this is covered by that material.
