### ISSUE TITLE
[bug] Markdown parsing on Patterns Pages

### ISSUE THREAD

**Issue by una** [GoogleChrome/web.dev#6603]
**Describe the bug**
Markdown for Aside elements doesn't render in patterns page `index.md`'s

**To Reproduce**
1. Go to the index of a patterns page
2. Try using `{% Aside %}` syntax in the description

**Expected behavior**
Rendering an aside element

**Screenshots**
![image](https://user-images.githubusercontent.com/1693164/139699838-81f87aa5-3845-4d70-b35d-cc15ce4cb28c.png)

**Comment by samthor** [comment]
To be clear, when you load the top-level index e.g., /patterns/web-vitals-patterns/, the helper doesn't work.

When you load it as /patterns/web-vitals-patterns/images/ (using the right sidebar), the helper __does__ work.

<img width="855" alt="Screen Shot 2021-11-02 at 07 28 02" src="https://user-images.githubusercontent.com/119184/139737569-79d7b7f5-288b-4771-b3c4-8651d86c5c1d.png">

Looking now. Probably how we inline MD vs rendering it properly.

**Comment by samthor** [comment]
It occurs to me that we actually want to render Nunjucks here, not MD.

11ty makes it tricky (but not impossible) to pull out the internal Nunjucks renderer.
