### ISSUE TITLE
E-commerce guide - How can performance improve conversion?

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#661]
This is part of the e-commerce Analysis & optimization section, covering how to improve e-commerce website performance.

First version of the guide will be in the e-commerce guide Drive folder.

**Comment by Meggin** [comment]
Sam, we will need to add ajkent to org, so this issue can be reassigned.

**Comment by samdutton** [comment]
Assigned, no outline yet.

**Comment by samdutton** [comment]
@ajkent won't be able to work on this. Still looking for new author.

**Comment by samdutton** [comment]
Martin Schierle has completed a first draft.

**Comment by Meggin** [comment]
Fixed! https://web.dev/what-should-you-measure-to-improve-performance/
