### ISSUE TITLE
Learn PWA logo in card is broken

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/web.dev#6612]
Learn PWA logo in card is broken (missing letters/gradient)
<img width="418" alt="Screenshot 2021-11-01 at 22 01 55" src="https://user-images.githubusercontent.com/1914261/139741802-4bf976e1-d9e9-44e0-a30a-7a1aee4084ed.png">
:

**Comment by devnook** [comment]
@rachelandrew fyi

**Comment by rachelandrew** [comment]
when you open the image in a new tab the PWA part is there https://d33wubrfki0l68.cloudfront.net/dee3df81f7ad37d7b5950947877c319f184a73fc/df653/images/courses/pwa/card.svg

**Comment by devnook** [comment]
This is fixed now
