### ISSUE TITLE
There seems to be a CLS issue on the /measure-psi page.

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/web.dev#6616]
There seems to be a CLS issue on the /measure-psi page.

**Comment by malchata** [comment]
Is this it? If so, might be due to async loading of content.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1635238/139753883-793a04b8-fbdc-47e7-b3ce-efcf153b3575.png">

**Comment by devnook** [comment]
Indeed. Fixed now.
