### ISSUE TITLE
E-commerce guide - What should you measure to improve performance?

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#662]
This is part of the e-commerce Analysis & optimization section, covering how to improve e-commerce website performance.

First version of the guide will be in the e-commerce guide Drive folder.

**Comment by Meggin** [comment]
Sam, we will need to add ajkent to org, so this issue can be reassigned.

**Comment by samdutton** [comment]
Assigned, no outline yet.

**Comment by samdutton** [comment]
@ajkent won't be able to work on this. Still looking for new author.

**Comment by samdutton** [comment]
Martin Schierle has completed a first draft.

**Comment by Meggin** [comment]
Updated priority, as this is planned for Google IO. Special note that we will publish guides as blogs in series.

**Comment by Meggin** [comment]
Keeping this one open, as Martin has a draft in review. Just updating labels.

**Comment by robdodson** [comment]
Going to close as stale. See #654

**Comment by robdodson** [comment]
This may have actually landed and  we forgot to close the issue.
https://web.dev/what-should-you-measure-to-improve-performance/
