### ISSUE TITLE
E-commerce guide - Build analysis and reporting into your e-commerce workflow

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#663]
This is part of the e-commerce Analysis & optimization section, covering how to improve e-commerce website performance.

First version of the guide will be in the e-commerce guide Drive folder.

**Comment by Meggin** [comment]
Sam, we will need to add ajkent to org, so this issue can be reassigned.

**Comment by Meggin** [comment]
Sam, we will need to add ajkent to org, so this issue can be reassigned.

**Comment by samdutton** [comment]
Assigned, no outline yet.

**Comment by samdutton** [comment]
@ajkent won't be able to work on this. Still looking for new author.

**Comment by Meggin** [comment]
@samdutton - I'm changing the labels on all doc issues. I'm also closing most of the e-commerce issues that were part of v1 launch with the hope of hitting the reset button. Feel free to re-open this issue if you want to keep it up as a content request for e-commerce docs.

**Comment by samdutton** [comment]
@Meggin Yes — this can be closed. This guide was landed as part of #886.
