### ISSUE TITLE
E-commerce codelab - Build a customized performance analysis tool for your site

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#664]
This is part of the e-commerce Analysis & optimization section, covering how to improve e-commerce website performance.

First version of the codelab will be in the e-commerce codelab Drive folder.

**Comment by Meggin** [comment]
Sam, we will need to add ajkent to org, so this issue can be reassigned.

**Comment by samdutton** [comment]
Assigned, no outline yet.

**Comment by samdutton** [comment]
@ajkent won't be able to work on this. Still looking for new author.

**Comment by Meggin** [comment]
@samdutton - we can remove this from v1 content scope, yes?

**Comment by samdutton** [comment]
Martin (working on the other content) actually wants to build this. I'll hold off for a day or two.

**Comment by Meggin** [comment]
@samdutton - I'm keeping this one open, as Martin's guides are in later stages of review and could land soon. Changing labels though.

**Comment by samdutton** [comment]
@Meggin Landed in #886. Close if you want.
