### ISSUE TITLE
content: Deliver lightweight resources with Save Data 

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#666]
This covers delivering lightweight resources with save data.

This issue is related to https://github.com/GoogleChrome/web.dev/issues/667

**Comment by Meggin** [comment]
Milica, let me know if you are taking this one, or if I should re-assign.

**Comment by Meggin** [comment]
@mihajlija - you OK if I move this off v1 content milestone, so we'd publish post Google IO?

**Comment by mihajlija** [comment]
Yes 👍

**Comment by robdodson** [comment]
Going to close as there hasn't been movement on this ticket. Happy to reopen if this  is still something folks want to work on and it isn't already covered by existing material.
