### ISSUE TITLE
Create landing pages for multiple tags

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#6664]
**Is your feature request related to a problem? Please describe.**

The use case would be to have pages like `/tags/case-study/productivity/`, so you could see all articles tagged as `case-study` _and_ `productivity`.

**Describe the solution you'd like**

A generic landing page template that pulls the two hash tags from the URL and shows a paginated view of all matching articles.

**Describe alternatives you've considered**

The alternative is the current one tag view like `/tags/case-study`, but it's in some cases not fine-grained enough.

**Additional context**

Google Partnerships would like to showcase case studies by vertical.

**Comment by tomayac** [comment]
On the Project Fugu 🐡 team it would likewise be useful to be able to have pages like `/tags/capabilities/hardware` to see all WebUSB, WebBluetooth, WebHID, etc. articles.

**Comment by tomayac** [comment]
This would still be useful.

**Comment by tomayac** [comment]
This would still be useful.

**Comment by tomayac** [comment]
More evidence that this would be needed in this [tweet](http://twitter.com/anniesullie/status/1577631993273229312) by @anniesullie.

**Comment by anniesullie** [comment]
Agreed, this is about the tenth time this year I've really wished I could share web.dev/case-studies/web-vitals

**Comment by sourav0v0** [comment]
HI! if no one is looking at it can i have a peek on the feature

**Comment by tomayac** [comment]
Note that we’re moving infrastructure soon, so unless @rachelandrew says otherwise, I don’t think that contributing a fix for the current infrastructure would be useful for the coming infrastructure. Thank you very much, though, for considering committing yourself to this.
