### ISSUE TITLE
content: Deliver lightweight resources with Client Hints

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#667]
This covers delivering lightweight resources with Client Hints.

This issue is related to https://github.com/GoogleChrome/web.dev/issues/666.

**Comment by Meggin** [comment]
Milica, let me know if you are taking this one, or if I should re-assign.

**Comment by mihajlija** [comment]
@Meggin Count me in 👍

**Comment by Meggin** [comment]
@mihajlija - you OK if I move this off the v1 content list (so we'd publish post Google IO)?

**Comment by mihajlija** [comment]
Sounds good, I haven't started working on it yet.

**Comment by Meggin** [comment]
Changing labels post-Google IO. Keeping it open though, as I presume we still want this content.

**Comment by robdodson** [comment]
Going to close as there hasn't been movement on this ticket. Happy to reopen if this  is still something folks want to work on and it isn't already covered by existing material.
