### ISSUE TITLE
Search Result Preview is hidden behind the Homepage Learn Section Element

### ISSUE THREAD

**Issue by niyazpoyilan** [GoogleChrome/web.dev#6673]
**Describe the bug**
While searching on the web.dev website the search results are being preview behind the Learn Section which makes it harder to interact with

**To Reproduce**
1. Go to 'https://web.dev'
2. Click on 'Search Icon'
3. Try Searching  'nofollow'
4.  The Preview is now shown behind the Learn Section

**Expected behavior**
The Search preview should appear above all the sections so as to clearly interact with the results

**Screenshots**
Image
<img width="1680" alt="Screen Shot 2021-11-03 at 4 50 17 PM" src="https://user-images.githubusercontent.com/11258129/140072372-8e0169a3-5026-46ef-83b3-bd7922408e76.png">

Video
https://user-images.githubusercontent.com/11258129/140072237-ae1536ca-1ec0-4a3c-a9e0-9db039c573f2.mp4

**Comment by devnook** [comment]
Thanks @niyazpoyilan ! Will close in favour of #6661
