### ISSUE TITLE
Add subscribe fab to new design system

### ISSUE THREAD

**Issue by MichaelSolati** [GoogleChrome/web.dev#6676]
The new design system doesn't have a subscribe fab to push users to `/newsletter`, this should be added and enabled in the pages that required it.

See https://github.com/GoogleChrome/web.dev/pull/6659/#discussion_r741830727

**Comment by MichaelSolati** [comment]
@andy-piccalilli would you mind taking a look at this? I can explain more later if you need details.

**Comment by devnook** [comment]
Actually I think it might be a great component to get us started on adding new patterns to the design system. Would you mind taking this on, @MichaelSolati ?

**Comment by andy-piccalilli** [comment]
Agreed. The FAB buttons already exist (although there's a new bug with the text), so it's just the docked aspect that needs building. https://web.dev/design-system/component/fab/
