### ISSUE TITLE
content: Lazy loading images and video

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#669]
This covers how to lazy load images and video. 

There's some existing content out there in /web that we should investigate if re-usable. Example: https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video/

And we should re-direct from /web to this new content once it exists.

**Comment by Meggin** [comment]
Addy, for some reason I can't seem to assign this to demianrenzulli. I suspect I will be able to once the existing pull request for deferring unused CSS lands. Assigning to you as owner now-- until we can re-assign.

**Comment by Meggin** [comment]
@addyosmani - another one to target post Google IO. Can you confirm?

**Comment by Meggin** [comment]
Changing labels post-Google IO. Keeping it open though, as I presume we still want this content.

**Comment by robdodson** [comment]
I think this may be covered by existing content on the site. We have posts on lazyload attr and using lazysizes.
