### ISSUE TITLE
Default render is now desktop, not mobile

### ISSUE THREAD

**Issue by jwpgroup** [GoogleChrome/web.dev#6694]
Until the recent change https://web.dev/measure/ tested mobile, now it's desktop.

**Comment by brendankenny** [comment]
@MichaelSolati I put up a fix for this in #6716. I saw a report on twitter about this and was opening the PR before actually searching for existing issues. Hope that's ok.

**Comment by MichaelSolati** [comment]
> @MichaelSolati I put up a fix for this in #6716. I saw a report on twitter about this and was opening the PR before actually searching for existing issues. Hope that's ok.

Thank you! I knew I'd have to get to this but I've just been focused on other things. I'm just gonna wait for some tests to run (which they should pass no issue) and this will hopefully be live in the next hour.

**Comment by brendankenny** [comment]
Thanks! And thanks for taking care of the visual review...no idea what that meant :)
