### ISSUE TITLE
Measure Core Web Vitals with the CrUX Report APIs codelab error report and solution

### ISSUE THREAD

**Issue by arp-wtm** [GoogleChrome/web.dev#6696]
_I was in the page_
 https://developers.google.com/codelabs/chrome-web-vitals-psi-crux?continue=https%3A%2F%2Fdevelopers.google.com%2Flearn%2Fpathways%2Fweb-vitals%3Fhl%3Den%23codelab-https%3A%2F%2Fdevelopers.google.com%2Fcodelabs%2Fchrome-web-vitals-psi-crux&hl=en#2
_entering Windows 10 command line_
 `curl -X POST -o response.txt 'https://chromeuxreport.googleapis.com/v1/records:queryRecord?key=YOUR_API_KEY' --header 'Accept: application/json' --header 'Content-Type: application/json' --data '{"url":"https://developers.google.com"}'`
 _I received this message_
curl: (1) Protocol "'https" not supported or disabled in libcurl
curl: (6) Could not resolve host: application
curl: (6) Could not resolve host: application
_I fixed these sintax errors with double quotes and direct url data_
`curl -X POST -o response.txt "https://chromeuxreport.googleapis.com/v1/records:queryRecord?key=YOUR_API_KEY" --header "Accept: application/json" --header "Content-Type: application/json" https://developers.google.com`

**please correct with the right command,
best regards, 
Antonella Rotondo**

**Comment by tunetheweb** [comment]
The command is correct, however depending on your command line it may need some tweaking.

The old DOS prompt for example does not like single quotes so it will need to be written as:

```
curl -X POST -o response.txt "https://chromeuxreport.googleapis.com/v1/records:queryRecord?key=YOUR_API_KEY" --header "Accept: application/json" --header "Content-Type: application/json" --data "{\"url\":\"https://developers.google.com\"}"
```

Similarly Powershell has overridden the curl command so, while that works with single quotes, you need to use the `curl.exe` command to explicitly call curl.

Will work on adding a note to [the official API docs](https://developer.chrome.com/docs/crux/api/) and then close this issue.

**Comment by arp-wtm** [comment]
Ok. Thanks for your note.
