### ISSUE TITLE
Fast content - Optimizing resource compression with Brotli

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#670]
This covers optimizing resource compression with Brotli.

We will need to think about how all resource compression content gets aligned with each other-- so we have a clean, simple narrative.

There's also existing content on /web that covers compression with Brotli, including https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/javascript-startup-optimization/.

Good to get a new, updated, single, centralized, interactive resource in one place.

**Comment by Meggin** [comment]
Addy, this should get re-assigned to Michael DiBlasio. He's not in the org yet, so I can't seem to assign to him.

**Comment by addyosmani** [comment]
Closing as done.
