### ISSUE TITLE
Scrollbar interaction

### ISSUE THREAD

**Issue by kvnamo** [GoogleChrome/web.dev#6700]
**Describe the bug**
Horizontal scroll bar not changing on hover, so it's not clear you can actually interact with it and see the full courses list on https://web.dev/learn/

**To Reproduce**
1. Go to https://web.dev/learn/
2. Hover on the horizontal bar under the courses section
3. No mouse pointer change or blue outline

**Expected behavior**
Mouse pointer change/blue outline/or something that promotes interaction

**Screenshots**
![image](https://user-images.githubusercontent.com/4895770/140393023-d0bc98f2-0899-4793-b819-b9391a6e4629.png)

**Comment by MichaelSolati** [comment]
@andy-piccalilli would you mind taking a look at this one?
