### ISSUE TITLE
Fast content - Preloading important Web Fonts

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#671]
This covers preloading important web fonts, and should be part of Optimizing Web Fonts content.

**Comment by Meggin** [comment]
Addy, assigning this to you until it can be re-assigned to Garima Mimani.

**Comment by Meggin** [comment]
@addyosmani - another one I think we can move out of v1. Can you confirm?

**Comment by robdodson** [comment]
I think this may be covered:
https://web.dev/codelab-preload-web-fonts/
