### ISSUE TITLE
content: Setting up HTTP Caching rules

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#673]
This covers setting up HTTP caching rules for the purpose of speed.

It's good to work out what the overlap is with HTTP caching covered in reliable content, for example, https://web.dev/reliable/http-cache.

As well as caching content in /web, such as https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching.

**Comment by Meggin** [comment]
Addy, this doc is listed in Q1/Q2 fast docs-- wondering if there's overlap with the existing http-cache guide and codelab-- link above?

**Comment by Meggin** [comment]
@addyosmani - fairly sure we can descope this for v1. Can you confirm?

**Comment by robdodson** [comment]
Going to close as stale. Happy to reopen if folks intend to work on it.
