### ISSUE TITLE
Identify all components that feature in articles that need to be refactored 

### ISSUE THREAD

**Issue by andy-piccalilli** [GoogleChrome/web.dev#6739]

**Comment by andy-piccalilli** [comment]
Thanks Rachel!

**Comment by mihajlija** [comment]
I think it's all in there, but here's one article that uses a bunch of components https://web.dev/payment-and-address-form-best-practices/

**Comment by andy-piccalilli** [comment]
Yeh any posts like that with lots going on will be really useful

**Comment by rachelandrew** [comment]
@jpmedley this is the change to the components that I mentioned in the writers meeting. I am putting together a PR which will detail the changes, though it only has the ones so far that we discovered in the Learn area as that is using the new CSS. 

So, I'm just asking if you know of any particularly complex pages, or special cases (outside of the components listed in the handbook) so we can be sure to test them.

**Comment by jpmedley** [comment]
I don't know if they're listed, but a bunch of the capabilities articles use macros to boilerplate certain flag and ot information.
