### ISSUE TITLE
Fast content - Optimize YouTube embeds

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#674]
This guide is part of a collection of guides to help developers load Google resources effectively.

This particular guide covers how to optimize YouTube embeds by lazy-loading, click-to-watch + thumbnail.

Katie, Milica, let me know if you are up for this. Assigning to you both at the start.

**Comment by Meggin** [comment]
I'm pretty sure we aren't launching Google resource guides until after IO, so changing the labeling here. Let me know if this is landing-- I can add the label back in!

**Comment by leobardimpact** [comment]
This is highly welcome. It is unclear which approach leads to both good usability and good rankings. There are three competing recommendations:

1. iframe (what YouTube recommends)
2. LazyLoading 
3. "click the image to have the YouTube video loaded in a lightbox"

Clarity from Web.Dev & YouTube would be great.

**Comment by robdodson** [comment]
Going to close this as stale. But want to tag @philipwalton in case this is a topic the speed team would like to work on in 2020.

**Comment by kaycebasques** [comment]
Relevant: https://github.com/GoogleChrome/web.dev/pull/1882
