### ISSUE TITLE
Fast content - Google Fonts loading

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#676]
This guide is part of a collection of guides to help developers load Google resources effectively.

This particular guide covers how to optimize Google Fonts loading using pre-connect, self-hosting.

Katie, Milica, let me know if you are up for this. Assigning to you both at the start.

**Comment by Meggin** [comment]
There's a lot of web font docs out there... we've got some in /web that are good to re-think as part of creating this content, for example: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.

**Comment by ymschaap** [comment]
@Meggin, would it be interesting to do the same for embedding YouTube videos?

The default embed code pulls in up to 500kb, while it is more performant to create a container with just the thumbnail and an 'play' icon, which loads the embed on click (I think AMP does the same). 

I could help.

**Comment by Meggin** [comment]
I'm pretty sure we aren't launching Google resource guides until after IO, so changing the labeling here. Let me know if this is landing-- I can add the label back in!

**Comment by robdodson** [comment]
Our LH docs on Ligthhouse now explain how to do this. Going to close as I think we have this covered.
