### ISSUE TITLE
Fast content - Optimize Google Analytics loading

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#677]
This guide is part of a collection of guides to help developers load Google resources effectively.

This particular guide covers how to optimize Google Analytics.

Katie, Milica, let me know if you are up for this. Assigning to you both at the start.

**Comment by Meggin** [comment]
I'm pretty sure we aren't launching Google resource guides until after IO, so changing the labeling here. Let me know if this is landing-- I can add the label back in!

**Comment by robdodson** [comment]
Going to close as stale but pinging @philipwalton in case this is something the speed team is interested in working on in 2020.
