### ISSUE TITLE
New web.dev/measure doesn't allow exporting reports (HTML and JSON)

### ISSUE THREAD

**Issue by isAdrisal** [GoogleChrome/web.dev#6770]
**Describe the bug**
Before the recent update to web.dev/measure, it was possible to save Lighthouse reports as HTML or JSON. This feature has been lost in the new design.

**To Reproduce**
1. Go to web.dev/measure.
2. Run an audit of a valid URL.
3. There is no mechanism to save or share the test result.

**Expected behavior**
It should be possible to save Lighthouse reports — not being able to save or otherwise share a Lighthouse report makes the tool far less useful for sharing Lighthouse results in a team or client.

**Screenshots**

**Comment by devnook** [comment]
We include the "View report" link, which allows to export. I'm marking it as fixed.
