### ISSUE TITLE
Carousel on the FireFox Browser seems to not work as expected

### ISSUE THREAD

**Issue by gssakash** [GoogleChrome/web.dev#6771]
**Describe the bug**
I recently checked out the website on the Firefox browser and I noticed that the carousel doesn't work as it is supposed to on it and it also seems to work in a different way as compared to the carousel on the Chrome browser.

**To Reproduce**
1. Open the 'Mozilla Firefox Browser'.
2. Go to the 'web.dev website' 
3. Scroll down to the 'Featured courses carousel'.
4. The carousel on the Firefox browser seems to malfunction.

**Expected behavior**
The carousel does not seem to work on the Firefox browser and looks different as compared to the carousel on the Chrome browser.

**Screenshots**
Screenshot of Carousel in the Firefox Browser 
![moz](https://user-images.githubusercontent.com/52027687/141466786-878f0db1-6de2-47c1-8a04-69938a1fcaad.PNG)

Screenshot of Carousel in the Chrome browser as a reference which works
![chr](https://user-images.githubusercontent.com/52027687/141466510-3c5f9a4b-2340-4a46-b58f-f3bcbdce63b9.PNG)

**Comment by devnook** [comment]
I believe this got fixed in #7207 . I tested it in FF 96 to confirm, but please reopen if this persists, noting the FF version number.
