### ISSUE TITLE
"Custom controls have associated labels" contains unassociated content.

### ISSUE THREAD

**Issue by jsunsawyer** [GoogleChrome/web.dev#6774]
### What page(s) need to be updated?

https://web.dev/custom-controls-labels/

### Why is this update needed?

The content of the page does not correspond to the page title.

**Comment by rachelandrew** [comment]
@malchata this relates to the Lighthouse docs, so flagging it up as you move those.

**Comment by malchata** [comment]
Got it. These are under "accessibility audits", which will not be migrated to d.c.c., but will instead be redirected to point to Deque's accessibility docs 1:1 as best as we can.

**Comment by rachelandrew** [comment]
Thanks for the report @jsunsawyer this page is being removed as part of https://github.com/GoogleChrome/web.dev/pull/7404
