### ISSUE TITLE
Must have features for the carousel

### ISSUE THREAD

**Issue by gssakash** [GoogleChrome/web.dev#6776]
**Is your feature request related to a problem? Please describe.**
This isn't related to a problem. But, I noticed that the carousel is missing essential features.

**Describe the solution you'd like**

These are the must-have features for the carousel :
 - Addition of left and right arrow buttons to move around easily.
 - Scrolling Feature - Ability to move the carousel around by dragging your mouse over it.

**Describe alternatives you've considered**
There are many ways of doing this and some of them are listed over [here](https://web.dev/carousel-best-practices/). 

**Additional context**
I think that some APIs like [this](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap) can be useful to implement the above features.

**Comment by tomayac** [comment]
Bug report for the carousel widget on https://web.dev/learn/. Scroll the carousel as in the screenshot below. Mouse over the "Learn PWA" card and note how its border highlights, meaning the entire card is a click target. Click on the right half of the card and notice how it doesn't open the resource, but instead scrolls the carousel to the next card, "Learn CSS".

![image](https://user-images.githubusercontent.com/145676/150167337-50d5fccd-2a90-4d6a-b708-3ee0abc4db21.png)

**Comment by gssakash** [comment]
It would be great if this issue on the Mozilla Firefox Browser could be fixed. #6771
