### ISSUE TITLE
Fast content - Avoiding Google Optimize A/B testing performance issues

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#678]
This guide is part of a collection of guides to help developers load Google resources effectively.

This particular guide covers how to avoid Google Optimize A/B testing performance issues.

Katie, Milica, let me know if you are up for this. Assigning to you both at the start.

**Comment by Meggin** [comment]
I'm pretty sure we aren't launching Google resource guides until after IO, so changing the labeling here. Let me know if this is landing-- I can add the label back in!

**Comment by robdodson** [comment]
Closing as stale. See #674
