### ISSUE TITLE
New PWA training

### ISSUE THREAD

**Issue by guettli** [GoogleChrome/web.dev#6787]
**Describe the bug**

About: https://web.dev/new-pwa-training/

The new PWA training contains much too much blublublala.

Today I read the first two slides and learned nothing.

I guess my feedback sounds unfriendly to you.

Sorry if this hurts you personally, but I really wanted to let you know
what I think.

**Comment by rachelandrew** [comment]
Hi @guettli I believe this training is designed to be delivered in person, rather than followed as a course. I don't think there is anything actionable here however so I'm closing the issue.
