### ISSUE TITLE
Performance Test analysis is missing

### ISSUE THREAD

**Issue by Collie-IT** [GoogleChrome/web.dev#6801]
**Describe the bug**
The list with failed and passed test cases is missing for performance measurement.

**To Reproduce**

1. Go to https://web.dev/measure/
2. Run audit
3. Scroll down

**Expected behavior**
I can see the testcases similar to SEO or Best Practice  

**Screenshots**
Missing Testli
![2021-11-16_18h26_44](https://user-images.githubusercontent.com/40590185/142036310-03af9808-74c5-4bbc-aeee-18b344f5ef5a.png)
st

**Comment by paulirish** [comment]
Sorry. We updated the PSI API to serve LH v9 payloads but the v8 can't opportunities & diagnostics from that payload.

While there is a backcompat fix.. the most straightforward is updating to the v9 lighthouse renderer. I have that in a PR here:: #6806

**Comment by paulirish** [comment]
fix is in. deployment coming soon
