### ISSUE TITLE
Fast content - Find and fix scrolling performance issues

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#681]
This guide covers how to find and fix scrolling performance issues. This may need to have a more detailed codelab, in addition to a guide with embeds.

It's important, whomever is on this, to look at existing docs on /web relating to scrolling performance. 

We may want to point to this new doc as the canonical doc from /web once it is complete.

**Comment by Meggin** [comment]
Addy-- assigned to you, as not too sure who's on this yet.

**Comment by Meggin** [comment]
@addyosmani - pretty sure this can be moved off v1 list. Can you confirm?

**Comment by Meggin** [comment]
Changing labels post-Google IO. Keeping it open though, as I presume we still want this content.

**Comment by robdodson** [comment]
Going to close this as stale for now. When we have concrete migration steps we can reopen this.
