### ISSUE TITLE
Form validation regex

### ISSUE THREAD

**Issue by j4k0xb** [GoogleChrome/web.dev#6812]
**Describe the bug**
The initial pattern only allows lowercase letters (`pattern="[a-z]{2,20}"`)
But in the following task
> How would you change the pattern to also allow uppercase letters?

it shows `[A-z]{2,20}` as the solution which also includes the following characters: [ \ ] ^ _ `

**To Reproduce**
1. Go to https://web.dev/learn/forms/validation/#pattern-attribute
2. Click on 'Toggle answer'

**Expected behavior**
The pattern should be `[a-zA-Z]{2,20}`

**Screenshots**
ascii table:
![image](https://user-images.githubusercontent.com/55899582/142123011-bf47d11e-f22a-4333-89ab-959f9391427f.png)

**Comment by samdutton** [comment]
Thanks @j4k0xb ! Good catch. I'll check/fix.
