### ISSUE TITLE
Finish the Comunity form.

### ISSUE THREAD

**Issue by Pegorim** [GoogleChrome/web.dev#6817]
**Describe the bug**
When I click to join the comunity banner, I am directed to a form but I cannot imput any sort of text in the placeholder. 

**To Reproduce**
1. Go to homepage
2. Click on click on the apply now to join our web dev community link.
3. Scroll down to try to answer the questions in the form.

**Expected behavior**
there is no error message and nothing happens at the site to me. 

**Screenshots**
<img width="1244" alt="Screen Shot 2021-11-17 at 9 47 21 AM" src="https://user-images.githubusercontent.com/14262063/142203953-23e7856e-8c93-4c57-b399-81a3b04f0c23.png">
<img width="921" alt="Screen Shot 2021-11-17 at 9 51 48 AM" src="https://user-images.githubusercontent.com/14262063/142204142-c5f25b21-04b3-4ffb-99f9-b69077f746df.png">
<img width="894" alt="Screen Shot 2021-11-17 at 9 51 59 AM" src="https://user-images.githubusercontent.com/14262063/142204153-9de4f49d-ef83-40c3-b103-87f281004201.png">

**Comment by fish-404** [comment]
When I click "Apply now", I was told 

> Sorry, but this survey has been closed.

![image](https://user-images.githubusercontent.com/29678177/142980157-d2e75613-d616-468d-9e3e-0456a2eb0325.png)

**Comment by devnook** [comment]
The form is discontinued now.
