### ISSUE TITLE
Fast content - Find and fix layout thrashing issues

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#682]
This guide covers how to find and fix layout thrashing issues.

This may be both a guide and codelab.

It's important whomever writes this guide to look at overlap in /web runtime performance guides on the same topic.

**Comment by Meggin** [comment]
Addy, assigning to you for now, as I can't assign Michael DiBlasio just yet.

**Comment by Meggin** [comment]
@addyosmani - pretty sure this one can be moved off v1 list. Can you confirm?

**Comment by Meggin** [comment]
Changing labels post-Google IO. Keeping it open though, as I presume we still want this content.

**Comment by robdodson** [comment]
Going to close this as stale for now. When we have concrete migration steps we can reopen this.
