### ISSUE TITLE
Fast content - Measuring the business metrics impact of performance investments

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#683]
This guide covers how to measure business metrics (maybe ROI) impact of performance investments.

Good to look at overlap with e-commerce guides!

**Comment by Meggin** [comment]
Addy, assigning to you for now, until I can assign to Lina.

**Comment by Meggin** [comment]
This doc is in late stages of pull request review: https://github.com/GoogleChrome/web.dev/pull/916

**Comment by addyosmani** [comment]
@samdutton I saw https://web.dev/value-of-speed/ landed. Is there a plan for an ecommerce collection of content to be pushed on web.dev in the future? Asking as I'd love to figure out whether some of Martin and Lina's work is planned to go into there vs under /fast. We were planning to look at performance culture as a topic in the second half of the year so a good time to start chatting about it :)
