### ISSUE TITLE
Handbook and content markup changes

### ISSUE THREAD

**Issue by hankchizljaw** [GoogleChrome/web.dev#6830]
A list of items that need to have their markup changed, based on the [new design system](https://web.dev/design-system/).

[Here is the current state of the handbook components reference, using the new system](https://deploy-preview-6769--web-dev-staging.netlify.app/handbook/web-dev-components/) from #6769 

## Markup changes 

- [ ] Button - use the markup from the [Button pattern](https://web.dev/design-system/component/button/) and [Button with icon pattern](https://web.dev/design-system/component/button/#with-icon)
- [ ] Primary Button - use the markup from the [Primary button pattern](https://web.dev/design-system/component/button/#primary) and [Primary button with icon pattern](https://web.dev/design-system/component/button/#primary-with-icon)
- [ ] Secondary Button - use the markup from the [Secondary button pattern](https://web.dev/design-system/component/button/#secondary) and remove the icon variant
- [ ] Icon button - use the markup from the [Icon button pattern](https://web.dev/design-system/component/icon-button/) and remove the "round" version
- [ ] Columns - replace `w-columns` with `switcher` 
- [ ] Stats - use the markup from the [Stats pattern](https://web.dev/design-system/component/stats/)
- [ ] Tables - replace `w-table-wrapper` with `table-wrapper`
- [ ] Figures - no longer need classes: just use good ol' HTML
- [ ] Tooltips - use examples from the [Tooltips pattern](https://web.dev/design-system/component/tooltips/). Also, remove the "You can left- or right-align a tooltip" section

**Comment by rachelandrew** [comment]
@andy-piccalilli ok this is looking good, so we don't really need to worry about old articles, but should use the new system once #6769 lands for new content?

**Comment by andy-piccalilli** [comment]
Yeh as soon as #6759 lands, we're in new markup land. 

What I've done so far is is `@extend` to support these common elements ([line 5 - 15](https://github.com/GoogleChrome/web.dev/blob/main/src/scss/_rollout.scss#L5)) in temporary rollout patching area. I did a quick look for `w-table-wrapper` in md files and 253 representation in 132 files is quite a lot.

To mitigate risk of changing that much content, I'd be happy to move those 3 extensions to the main `next.scss`, but we definitely need to switch stats in old content. There's 42 of those in 25 files.

**Comment by rachelandrew** [comment]
@andy-piccalilli so if you roll in the extensions, old articles will be fine other than those using stats which will be unstyled until updated?

When do you want to merge #6769 ?

**Comment by andy-piccalilli** [comment]
Yep that's right. I say we aim for early next week (ideally Monday) so it's live with enough time before thanksgiving for issues to become apparent. 

What would be really helpful too is if you could get that deploy preview in front of some tech writers to they can look at posts they think might be problematic. I think I've found some of the gnarliest ones, but I bet there are some naughty posts hiding out. 

cc/ @devnook @MichaelSolati

**Comment by rachelandrew** [comment]
I've asked the tech writers and also the general web.dev chat to see if anyone has time to have a poke around.

**Comment by andy-piccalilli** [comment]
Thanks, Rachel!

**Comment by rachelandrew** [comment]
https://deploy-preview-6769--web-dev-staging.netlify.app/speculative-prerendering/#implementing-a-revamped-prerendering-solution

line height looks off, and no margin round code blocks, also can't see the anchor.

**Comment by rachelandrew** [comment]
another one that highlights inline code https://deploy-preview-6769--web-dev-staging.netlify.app/bundling-non-js-resources/#ambiguous-relative-urls

**Comment by mihajlija** [comment]
Pagination on /blog doesn't seem to work on staging

https://deploy-preview-6769--web-dev-staging.netlify.app/blog/2

**Comment by rachelandrew** [comment]
The video at the top of this page is displaying pushed over to the right https://deploy-preview-6829--web-dev-staging.netlify.app/svgcode/

**Comment by andy-piccalilli** [comment]
> Pagination on /blog doesn't seem to work on staging
> 
> https://deploy-preview-6769--web-dev-staging.netlify.app/blog/2

Seems to be working fine to me. This section hasn't been affected by #6769 either 👍

**Comment by andy-piccalilli** [comment]
> 

Good catch because I imagine flow content inside a list item isn't only present in this article

**Comment by andy-piccalilli** [comment]
> The video at the top of this page is displaying pushed over to the right https://deploy-preview-6829--web-dev-staging.netlify.app/svgcode/

Is this the right URL, @rachelandrew? It seems to be a different PR

**Comment by mihajlija** [comment]
/blog/2 works now, probably a server error @andy-piccalilli 

Loving the TOC btw!

**Comment by andy-piccalilli** [comment]
Thank you!

**Comment by andy-piccalilli** [comment]
Pushed some tweaks up to #6769 that when netlify finishes building, covers the list/code spacing issues
