### ISSUE TITLE
Card Heading is overflowing from the Card when words length is large

### ISSUE THREAD

**Issue by itsashutoshhans** [GoogleChrome/web.dev#6836]
**Describe the bug**
The css is broken for the card and Card Heading is overflowing when words length is large.

**To Reproduce**
1. Go to 'https://web.dev/tags/javascript/2/'
2. Scroll till you find the card with the heading "Monitor your web page's total memory usage with `measureUserAgentSpecificMemory()`"
3. The heading is overflowing

**Expected behavior**
The text should not overflow from the card.

**Screenshots**
![image](https://user-images.githubusercontent.com/18111502/142588647-8657c208-8aeb-4c3e-a73f-783fbd00bcad.png)

**Comment by royalarjun001** [comment]
#6882 looks similar to this defect, it might get fixed with PR https://github.com/GoogleChrome/web.dev/pull/6848
