### ISSUE TITLE
Fast content - optimize Framework loading

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#684]
This is likely to be a set of guides around optimizing loading when using a Framework. There's all kinds of ways to organize this content-- like we could organize Framework answers in audit guides... as well as have an end to end make your framework-app faster. 

Creating this issue to track this work, as we figure out the best way forward.

**Comment by Meggin** [comment]
It's worth calling out that this is important-- it's a high priority for v1 launch!

**Comment by Meggin** [comment]
Things to cover: 

* React / Next, Angular.
* Server rendering (SSR)
* Code-splitting
* Differential 2015+ Loading JavaScript
* Tree-shaking
* Bundle analysis

**Comment by Meggin** [comment]
React guides being tracked in this pull request: https://github.com/GoogleChrome/web.dev/pull/747

**Comment by Meggin** [comment]
@housseindjirdeh - do we want to close this issue, and create new ones for each framework? Leaving it open until we decide next steps. Changing labels though, just post-Google IO.

**Comment by robdodson** [comment]
Let's close this and create tickets for each framework.

Vue: https://github.com/GoogleChrome/web.dev/issues/976
Angular: https://github.com/GoogleChrome/web.dev/issues/975
