### ISSUE TITLE
Remove calc in clamp function

### ISSUE THREAD

**Issue by Krutsch** [GoogleChrome/web.dev#6854]
### What page(s) need to be updated?
src/site/content/en/learn/css/the-cascade/index.md

Provide a list of URLs.
https://web.dev/learn/css/the-cascade/

### Why is this update needed?
Make it easier to write clamp for developers. Calc is already being used in clamp.

**Comment by rachelandrew** [comment]
@argyleink happy with this? There is a linked PR that needs the CLA signed, but wanted your thoughts.

**Comment by argyleink** [comment]
i'm fine with this edit yep 👍🏻
