### ISSUE TITLE
Audit guide - document security audits

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#687]
As part of improving audit content, we will need to document new security audits.

These audits might be custom audits-- not fully baked into DevTools at the start, so will need to make sure we have a solid pattern for custom audit content.

Also might want to link up audit docs with CSP evaluator too. This might be a separate issue, as at the moment, it is a separate tool, but including it here-- as the security audits relating to CSP may also align with the CSP evaluator.

**Comment by Meggin** [comment]
In addition to new security audits, we may want to include CSP content in Secure section.

There's quite a bit of existing content on CSP that could be migrated and re-used or at least referenced in first around of security audits:

- https://csp.withgoogle.com
- [Chrome extension](https://chrome.google.com/webstore/detail/csp-mitigator/gijlobangojajlbodabkpjpheeeokhfa?hl=en) to help developers adopt [CSP based on script nonces
](https://csp.withgoogle.com/docs/strict-csp.html)
- [CSP on /web](https://developers.google.com/web/fundamentals/security/csp/)

**Comment by Meggin** [comment]
@kosamari - you OK for me to move this off the Google IO (v1 content) list?

**Comment by Meggin** [comment]
@kosamari - cleaning up issues a bit.

Do you have the bandwidth to work on Security docs?

**Comment by robdodson** [comment]
Going to close this as stale.
