### ISSUE TITLE
Card heading is leaking out of the card view in the list search result

### ISSUE THREAD

**Issue by royalarjun001** [GoogleChrome/web.dev#6882]
**Describe the bug**
One of the cards heading for a blog is leaking out from the card boundary.

**To Reproduce**
1. Go to '[Web dev home page](https://web.dev/).'
2. Click on the search icon on the top right corner
3. Type 'memory' in the text box and search.
3. Scroll down to search results of blogs ( card grid view )
4. See having card header leaking out of the card view.

**Expected behavior**
Card heading should remain in the boundary of the cards.

**Screenshots**
![image](https://user-images.githubusercontent.com/3795050/143214989-27c2a432-5fcb-4897-a552-2aa9f59e8471.png)

**Comment by MichaelSolati** [comment]
Should be fixed by #6848
