### ISSUE TITLE
Document how to optimize web sites in various frameworks

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#689]
We've typically showed developers best practices for things like perf and reliability in vanilla JS, and then hoped that they could figure out how to apply those best practices to their own code in a framework of choice.

That's kind of challenging-- as it's not as obvious as it seems.

We want to show developers how to make their sites as awesome as possible in the simplest way-- so we should show them how to do things like improve performance using sample code that matches their framework code.

It's worth noting that there's lots to decide around this-- and we will need to most likely created a series of issues to track the work.

This is just the starting point-- we need to show developers how to create fast, reliable, secure, installable, and more apps in their frameworks.

It's also worth noting that we are gonna have to choose the first set of frameworks that we cover-- and how we can possible allow for additional framework examples over time.

Lots of work to do here, and decisions to make-- this is the mega-issue to start tracking this work.

**Comment by Meggin** [comment]
Pull request tracking these docs here: https://github.com/GoogleChrome/web.dev/pull/747

**Comment by Meggin** [comment]
We will be starting with React.

**Comment by Meggin** [comment]
I've moved this to be outside of v1 release, as we are specifically tracking optimizing loading in frameworks in this issue: https://github.com/GoogleChrome/web.dev/issues/684. I don't want to remove it though-- as we will want to do more with framework auditing once stack packs are accessible in Lighthouse.

**Comment by robdodson** [comment]
Going to close this because it seems like we have a good model of applying the 6 principles to different frameworks. Houssein pioneered this with React and we'll be doing it again with Angular and Vue soon.
