### ISSUE TITLE
Wrong attribute for checkbox

### ISSUE THREAD

**Issue by jpalardy** [GoogleChrome/web.dev#6896]
**Describe the bug**
In [this section](https://web.dev/learn/forms/form-fields/#type), the text says to use `selected` on a checkbox. But for checkboxes, the `checked` attribute is what's needed.

**Screenshots**
<img width="866" alt="Screen Shot 2021-11-26 at 11 55 56 AM" src="https://user-images.githubusercontent.com/18142/143625333-d74fc3a5-b2b1-412a-bafe-64b9031ac214.png">

**Comment by sidverma32** [comment]
I think here we need to update the document instead `selected` attribute it will be `checked` for **CheckBox**  , i will pick this up!

**Comment by malchata** [comment]
Tag me on the new PR if you need a review, @sidverma32!
