### ISSUE TITLE
Smooth guides - document how to build awesome UI

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#690]
This is a mega issue to track the first round of guides that will teach developers how to build awesome UI. 

First round of guides will cover smooth layout.

We can create additional issues to track the smooth guides-- but gotta start somewhere. So this is the placeholder to make sure that we create content to help developers build awesome UI.

**Comment by Meggin** [comment]
Intrinsic layout content is being tracking in this pull request: https://github.com/GoogleChrome/web.dev/pull/762

**Comment by Meggin** [comment]
We've had a first round of reviews, but gonna keep status in r1, as there's still placeholder content. Likely to go through a few rounds. Looking great though!

**Comment by argyleink** [comment]
i've got 2 smooth animation articles in my mental hopper as well. shorter 1 offs, but gooduns.

**Comment by Meggin** [comment]
@argyleink -any chance we will land layout guides, or are we fairly sure they will be post Google IO?

**Comment by Meggin** [comment]
@robdodson - I would suggest we close this, as the 'Smooth' category is a big one. It would make sense to have issues per area, for example, an issue for docs in intrinsic layout, docs on animations, etc.

**Comment by robdodson** [comment]
yep. happy to close and we can create issues for individual guides when we've scoped out the section.
