### ISSUE TITLE
Definitions of good LCP for desktop and mobile appear to differ in lighthouse

### ISSUE THREAD

**Issue by runjak** [GoogleChrome/web.dev#6904]
**Describe the bug**

After reading [web.dev/lcp](https://web.dev/lcp/) and [web.dev/lighthouse-largest-contentful-paint](https://web.dev/lighthouse-largest-contentful-paint/) my impression was that an LCP measurement `<2.5s` would be classified as `good`.
I assume that this classification should be the same between lighthouse and what is described on `web.dev`.

I've recently looked at some lighthouse measurements and noticed that a measurement of `~2.4s` was marked as yellow when I would've expected it to be marked green.

I looked at the [lighthouse scoring calculator](https://googlechrome.github.io/lighthouse/scorecalc/#FCP=544&SI=1122&FMP=684&TTI=2358&FCI=6500&LCP=2368&TBT=183&CLS=0.02&device=mobile&version=8) for the measurements and noticed, that the coloring is different between mobile and desktop:

![Screenshot of lighthouse scoring calculator for the mobile case](https://user-images.githubusercontent.com/5417642/143868928-61aa9112-0c28-4b73-bf24-d8603c6672df.png)
![Screenshot of lighthouse scoring calculator for the desktop case](https://user-images.githubusercontent.com/5417642/143868924-6cfe5c8c-1173-41b8-9d0e-0537ee3cd12d.png)

I'm guessing that this classification for the LCP metric in lighthouse is defined in [lighthouse-core/audits/metrics/largest-contentful-paint.js#L36-L66](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/metrics/largest-contentful-paint.js#L36-L66).

My suggestion is that it could be an improvement to the pages [web.dev/lcp/](https://web.dev/lcp/) and [web.dev/lighthouse-largest-contentful-paint/](https://web.dev/lighthouse-largest-contentful-paint/) to note the differences between mobile and desktop.

**To Reproduce**
1. Perform a Desktop test with Lighthouse on a page where LCP takes `>=1.4s` and `<2.5s`.
2. Notice that LCP is marked as yellow/needs improvement.
3. Observe that this is different than described on [web.dev/lcp/](https://web.dev/lcp/).

**Expected behavior**

I would expect the description of LCP to match the behavior experienced in lighthouse. 

**Screenshots**

This is an example of the LCP being displayed in `yellow` in a lighthouse report for a `Desktop` device:
![Screenshot of an LCP measurement in a lighthouse report for desktop](https://user-images.githubusercontent.com/5417642/143870487-c160c348-a625-412d-821e-f281f57c1f4a.png)

The coloring appears to be in contrast to what a reader may learn when visiting [web.dev/lcp/](https://web.dev/lcp/).

**Comment by brendankenny** [comment]
@runjak sorry to send you on this long hunt for answers. Updating the metrics docs to include desktop scoring information is on our plate and should hopefully be taken care of soon.

I'll merge this issue into the similar https://github.com/GoogleChrome/lighthouse/issues/12693 so there's a single place for tracking progress.

**Comment by runjak** [comment]
No worries about the long hunt - thanks for taking care of this :+1:
