### ISSUE TITLE
Video player shift left

### ISSUE THREAD

**Issue by Sergdan1992** [GoogleChrome/web.dev#6907]
page: https://web.dev/svgcode/
If start watch video version, video player is shifted. 
![image](https://user-images.githubusercontent.com/55101680/143897639-526dd63e-0fd2-418d-ba6d-caeb411171bd.png)

**Comment by jpmedley** [comment]
@devnook @MichaelSolati 

I can't find anything wrong with the article source or the video itself. This looks like a problem with the YouTube shortcode. Can one of you look at this?
