### ISSUE TITLE
Reliable guide - document handling navigation requests

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#692]
This will be a detailed guide, or maybe multiple guides on handling navigation requests (depending on size).

- Smaller static sites: full HTML precaching example.
- Single Page Apps: App Shell Model example.
- Multi Page Apps: Streaming service worker templating example.
- Fallback: If none of those approaches work, use Navigation Preload for best performance.

**Comment by jeffposnick** [comment]
Here's a link to the draft (`@google.com` accounts only): https://docs.google.com/document/d/1z3eBb7mJc5JHKRWD68iJ0ndCATKfJgyP_j6ivqnpiMM/edit

**Comment by robdodson** [comment]
Hey @jeffposnick, is this something you'd still be interested in publishing? Do you feel like it's ok publishing it without #888?

**Comment by jeffposnick** [comment]
Yes, I'd absolutely love to get it published. You'd just need to drop the reference to the codelab.

**Comment by robdodson** [comment]
OK, assigning to @kaycebasques to track down someone to do a final review.

**Comment by jeffposnick** [comment]
As mentioned previously, it would still be nice to get this reviewed and published.

**Comment by jeffposnick** [comment]
As mentioned previously, it would still be nice to get this reviewed and published.

**Comment by robdodson** [comment]
@kaycebasques is this something Milica or Rachel could look at?

**Comment by kaycebasques** [comment]
@jeffposnick draft LGTM, please submit a PR

**Comment by jeffposnick** [comment]
I'm going to submit a PR.
