### ISSUE TITLE
Can't select a text in the row below the header.

### ISSUE THREAD

**Issue by yptr** [GoogleChrome/web.dev#6925]
**Describe the bug**
Padding of content-button's container doesn't allow to select text of the underlying row.

**To Reproduce**
1. Go to any article. E.g., https://web.dev/speculative-prerendering/
2. Scroll down to place header right above the text 
3. Try to select a text in the highest row

**Actual behavior**
Text can't be selected

**Expected behavior**
Text can be selected

**Screenshots**
![image](https://user-images.githubusercontent.com/45543713/144190467-1a3193cd-5168-47c4-9cc1-eadbb6065cca.png)

**Comment by MichaelSolati** [comment]
This has/should be fixes by the new design system (almost all posts have been converted over)
