### ISSUE TITLE
Reliable guide - document handling subresource requests

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#693]
This guide will cover:

- Mixing and matching the right strategy for each type of subresource request.
- Exploration of cache expiration, opaque responses, and quota best practices.

**Comment by Meggin** [comment]
@jeffposnick - you still gonna try and get this out for Google IO? Let me know if you are going to push it out, as I'll remove the v1 content label.

**Comment by jeffposnick** [comment]
I'm still catching up post-vacation, but I think I can reasonably get something out for review this week. I don't want to force the issue of landing it pre-I/O if it means causing you to have to rush a review when there are other priorities, though.

So feel free to remove the v1 content label and if things line up so that it does go live pre-I/O, that would be a bonus?

**Comment by jeffposnick** [comment]
I have a draft of this available at 
https://docs.google.com/document/d/1YPoy3DzR68gIBt58y4uHV7OPwH_CROoxxNu7O0MD-eI/edit (`@google.com` email address required).

It currently assumes that the related codelab will be #888 (which is blocked right now), but we can remove a reference to the codelab as needed if we wanted to decouple the dependencies.

CC: @addyosmani

**Comment by robdodson** [comment]
Hey @jeffposnick, is this something you'd still be interested in publishing? Do you feel like it's ok publishing it without #888?

**Comment by jeffposnick** [comment]
Yes, I'd absolutely love to get it published. You'd just need to drop the reference to the codelab.

**Comment by robdodson** [comment]
Assigning to @kaycebasques to find a reviewer.

**Comment by jeffposnick** [comment]
As mentioned previously, it would still be nice to get this reviewed and published.

**Comment by jeffposnick** [comment]
As mentioned previously, it would still be nice to get this reviewed and published.

**Comment by robdodson** [comment]
@kaycebasques is this something Milica or Rachel could look at?

**Comment by kaycebasques** [comment]
Howdy @jeffposnick this draft looks incomplete, please see my comments for details
