### ISSUE TITLE
Padding in FABs

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/web.dev#6931]
FABs need to get a more balanced padding:

![Screenshot 2021-12-01 at 14 59 25](https://user-images.githubusercontent.com/1914261/144247593-2f6f25d8-41a4-43c8-83a7-626e6f1c3b9b.png)

**Comment by jpmedley** [comment]
@devnook I'm looking at this because I'm the content sheriff this week. I feel like I don't need to assign these, but wanted to verify. Is there some way I should mark issues opened by you and Michael?
