### ISSUE TITLE
Reliable guide - UX considerations

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#694]
This guide will cover UX considerations when building reliable sites:

- Tradeoffs between freshness and reliability when using cache-first strategies. Broadcast Channel API and service worker lifecycle events provides hooks to notify users of changes.
- Update your UI to show users what's already cached and will work while offline.
- Give users (some) control over how much is cached.

**Comment by robdodson** [comment]
Hey @jeffposnick, it doesn't seem like there's a linked draft so I'm going to close this if that's ok. However, if this is something you'd like to pursue please let me know and we can reopen the ticket.
