### ISSUE TITLE
Subscription doesn’t work

### ISSUE THREAD

**Issue by isatmun** [GoogleChrome/web.dev#6941]
**Describe the bug**
Subscription doesn’t work on main page

**To Reproduce**
1. Go to homepage
2. Fill subscription form
3. Click subscribe button 

**Expected behavior**
Subscribed

**Screenshots**
![A04853CC-E922-426B-BB32-0CAD1E9D2C9E](https://user-images.githubusercontent.com/95216632/144316170-511cf751-e67b-4f00-9eb6-2b01d9b77bce.jpeg)

**Comment by MichaelSolati** [comment]
This form has been disabled and isn't presently on the home page... Can you try clearing your cache and reloading?

**Comment by isatmun** [comment]
Yes its gone now.
