### ISSUE TITLE
Reliable & audit guide - Use tools to keep site reliable

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#695]
The goal of this content is to explain to developers how to keep their sites reliable-- focusing on monitoring over time.

It could be covered in a single guide-- but there may also be cross-over in audit content (even just a cross-reference from audit content to this guide should work).

Noting the connection auditing once-off, and using audits to monitor over time.

**Comment by robdodson** [comment]
Also closing as stale. See #694.
