### ISSUE TITLE
Add the FOSS YouTube WordPress Plugin to list of recommended facades

### ISSUE THREAD

**Issue by embedplus** [GoogleChrome/web.dev#6953]
### What page(s) need to be updated?

https://web.dev/third-party-facades/

### Why is this update needed?
We think it can be a great resource to share given the pervasiveness of WordPress (and YouTube embedding). Over 200,000 sites use this [free WordPress plugin for embedding YouTube](https://wordpress.org/plugins/youtube-embed-plus/). With one click, it eliminates the third-party resources loaded from YouTube.com.

Thanks @patrickhulce for the bit of guidance in submitting this!

**Comment by rachelandrew** [comment]
Thanks for suggesting this, however we don't accept links to commercial products in our articles (even if there is a free version with limited functionality) unless there really would be no way to achieve the result otherwise.
