### ISSUE TITLE
Audit guide - cover all performance Lighthouse audits

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#696]
This issue tracks the coverage of all performance Lighthouse audits.

Some of that content lives in existing Lighthouse docs; some of it lives in newer principle guides. We will have a complete set in one place that we can link to.

**Comment by Meggin** [comment]
Came up with new approach for these guides-- tracking progress in this branch: https://github.com/GoogleChrome/web.dev/tree/performance-audits

**Comment by robdodson** [comment]
I think things generally look good.
Meggin—instead of doing a bunch of work in the old format, would you be ok switching over to the v1 branch? I can help you get set up. It should be a much nicer preview experience.

**Comment by Meggin** [comment]
Yes, I can work in the new branch.

**Comment by Meggin** [comment]
This is fixed.
