### ISSUE TITLE
Breadcrumb links are the wrong size in some blog posts

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#6963]
**Describe the bug**
The breakcrumb links are larger in [the Blibli case study](https://web.dev/blibli/) than in [other articles](https://web.dev/building-multiple-pwas-on-the-same-domain/). 

**To Reproduce**
Following the links above.

**Expected behavior**
They should be the same size.

**Screenshots**
In the Blibli case study:
![image](https://user-images.githubusercontent.com/8204171/144665367-c147aaef-6717-4b6d-8e4c-0a4fd6b4b020.png)

In other articles:
![image](https://user-images.githubusercontent.com/8204171/144665390-92941f5c-fcea-4984-be2d-e003ae367f89.png)

**Additional information**
I notice that the Blibli case study uses `layout: post-old` while the other articles uses `layout: post`.

**Comment by MichaelSolati** [comment]
I think that's cause it's using the old design system so it looks off compared to posts that have been updated. I would think this will get fixed when blibli is migrated. @devnook I don't think we need to track this, but I'd love your thoughts.

**Comment by rachelandrew** [comment]
@jpmedley I think this is fixed now more of the site is migrated, can you confirm?

**Comment by jpmedley** [comment]
It looks fixed to me.
