### ISSUE TITLE
Internal nav bar is missing "Case studies" tab

### ISSUE THREAD

**Issue by heyawhite** [GoogleChrome/web.dev#6973]
**Describe the bug**
When I visit some (but not all) pages that are internal to the  site, the tab "case  studies" is not available.

**To Reproduce**
1. Go to web.dev/tags/case-study
2. Click on the [Renault Group case study](https://web.dev/renault/)
3. See missing "Case studies" in shorter navigation. Looks like it may be the old layout? Is it possible this is just an old to new layout bug?

If you click [Mail.ru's Core Web Vitals case study](https://web.dev/mailru-cwv/) you will see the new navigation with "Case studies" available.

Other places the nav is missing content include the [Handbook](https://web.dev/handbook/)

**Screenshots**
Here's the Renault page, with the incorrect nav:
<img width="1326" alt="Incorrect navigation, missing case study" src="https://user-images.githubusercontent.com/2766281/144847437-83020148-2691-49f9-8e02-3d81a3a87d6f.png">

**Comment by rachelandrew** [comment]
@heyawhite I think this is now not an issue, can you confirm?

**Comment by heyawhite** [comment]
Yes, it is resolved!
