### ISSUE TITLE
Typo in "Available in:" section for Russian language

### ISSUE THREAD

**Issue by dmrnz** [GoogleChrome/web.dev#6988]
**Describe the bug**
Articles on web.dev have translations in different languages, including russian. But the word Русский (Russian) has "R" instead of "Р" as its first letter.

**To Reproduce**
1. Go to https://web.dev/vitals-field-measurement-best-practices (or any other article with russian translation)
2. Choose any language except Russian
3. See error

**Expected behavior**
Word "Русский" in "Available in" section

**Screenshots**
![image](https://user-images.githubusercontent.com/43438823/145080792-4f3d2742-c575-4fe6-ad35-3ef1703671de.png)

**Comment by MichaelSolati** [comment]
This was fixed with #6689 last week, thank you for reporting this though!
