### ISSUE TITLE
Very minor typo

### ISSUE THREAD

**Issue by ThisIsNotANamepng** [GoogleChrome/web.dev#6990]
A "shoould" where a "should" is supposed to be

**To Reproduce**
1. https://web.dev/add-manifest/#manifest-properties
2. In the third paragraph of the star section

**Comment by tinandanny** [comment]
> A "shoould" where a "should" is supposed to be
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. https://web.dev/add-manifest/#manifest-properties
> 2. In the third paragraph of the star section
> 

Stop emailing my husband

**Comment by Hatch11251** [comment]
Why are you fucking with me?

Jeramie

**Comment by tinandanny** [comment]
Bcuz idk wtf u ate

**Comment by Hatch11251** [comment]
What do you think I ate?

Jeramie
