### ISSUE TITLE
https://partidukkanim.com/

### ISSUE THREAD

**Issue by partidukkanimcom** [GoogleChrome/web.dev#701]
**Welcome!** Please use this template for reporting documentation issues on https://web.dev

_For questions about **Chrome DevTools**, checkout the
[`google-chrome-devtools`](https://stackoverflow.com/questions/tagged/google-chrome-devtools) tag on StackOverflow.
For questions about **Chrome**, check the [`google-chrome`](https://stackoverflow.com/questions/tagged/google-chrome)
tag. If you think you've found a Chrome bug, check out our 
[feedback page](https://developers.google.com/web/feedback/#how-to-file-a-good-bug) for more details on how to file it._

**Page Affected:** https://web.dev/TODO

**What needs to be done?**

_Please provide description of what's needs to be done here. Please be sure to include the link to the original page
and any supporting links/data._

**Comment by robdodson** [comment]
Hi @partidukkanimcom, were you encountering a problem?
