### ISSUE TITLE
details have very low flow-space

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/web.dev#7034]
details have very low flow-space, making them glued to. the paragraph before them
<img width="788" alt="Screenshot 2021-12-14 at 17 20 39" src="https://user-images.githubusercontent.com/1914261/146037675-6ca2412c-7a11-4b13-a09e-1c71d8050ee2.png">
.

**Comment by sidverma32** [comment]
@devnook Is this issue open to be picked up?

**Comment by devnook** [comment]
This is fixed now.
