### ISSUE TITLE
[Question] Median score metric

### ISSUE THREAD

**Issue by willstocks-tech** [GoogleChrome/web.dev#705]
Hi guys,

This one is by _no means_ a high priority issue - definitely more of a question (or maybe even an FYI):

I've run quite a few web.dev audits, however I've never once seen the "median score" line on any chart:
![image](https://user-images.githubusercontent.com/43744514/53970378-7b83a880-40f2-11e9-8bb3-0b45a5bea752.png)
Is it supposed to show? Or is it a "coming soon" feature? Or maybe even deprecated?

People love to compare themselves to others... and we all want to be _above average_ 😉 

Cheers

Will

**Comment by robdodson** [comment]
Ah good question. That used to show up so I think it is a bug. I'll look
into it. I may disable that line for now while we sort out the issue.

**Comment by willstocks-tech** [comment]
Super quick response @robdodson! 😁 

Ahhh, OK cool cool - I will keep an eye out for it in the future then

**Comment by robdodson** [comment]
Totally forgot there was an issue for this. Started leaving comments in #711.
