### ISSUE TITLE
Overflow of code content 

### ISSUE THREAD

**Issue by Anurella** [GoogleChrome/web.dev#7063]
**Describe the bug**
There is an overflow of the code content vertically when highlighted for the auto carousel section, overlapping other content. 

**To Reproduce**
1. Go to the Auto Carousel section and uncollapse it, the code content overflows vertically overlapping other content.

**Expected behavior**
The overflow content should happen inside the parent container.

**Screenshots**
 See <img width="517" alt="image" src="https://user-images.githubusercontent.com/24455861/146427571-742b2a60-c23c-43cd-abad-358faf3e207f.png">

**Comment by tesshuang** [comment]
This issue could be replicated in all the code components within [web.dev/patterns](https://web.dev/patterns/).

**Comment by rachelandrew** [comment]
Fixed in #7093
