### ISSUE TITLE
content: Update a type on blog about structuredClone

### ISSUE THREAD

**Issue by dusthijsvdh** [GoogleChrome/web.dev#7064]
### What page(s) need to be updated?
Deep-copying in JavaScript using structuredClone

Provide a list of URLs.
* https://web.dev/structured-clone/

### Why is this update needed?
There's a type in one of the last lines:
> Functions: If your object contains functions, they will be quiety discarded.
[Link to marked text](https://web.dev/structured-clone/#:~:text=Functions%3A%20If%20your%20object%20contains%20functions%2C%20they%20will%20be%20quiety%20discarded.)

Quiety should be quietly

**Comment by rachelandrew** [comment]
Fixed in #7070
