### ISSUE TITLE
Doesnt work on smartphone

### ISSUE THREAD

**Issue by sohrabsaran** [GoogleChrome/web.dev#7066]
**Describe the bug**
I expect that i should be able to perform drag and drop with my fingers and on the smartphone screen, but it does not seem to work.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by Hatch11251** [comment]
So where is it

Jeramie

**Comment by sohrabsaran** [comment]
https://web.dev/drag-and-drop/

**Comment by rachelandrew** [comment]
I don't have enough information to know what the problem is here. Can you provide some more information @sohrabsaran? please see the information in the template that describes how to report a bug.
