### ISSUE TITLE
Add markdown linting.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#708]
Maybe using something like Remark.
https://remark.js.org/

**Comment by mfriesenhahn** [comment]
Preliminary custom rules:
- no curly single quotation marks (includes apostrophes)
- no curly double quotation marks
- no spaces around em dashes or en dashes

**Comment by robdodson** [comment]
Probably want to combine [husky](https://github.com/typicode/husky) and [lint-staged](https://github.com/okonet/lint-staged) to make sure this only runs against staged files and not the entire project.
