### ISSUE TITLE
[Designcember site] Image is getting hide on click 

### ISSUE THREAD

**Issue by nsharma-26** [GoogleChrome/web.dev#7099]
**Describe the bug**
Image is getting hide on click. 
**To Reproduce**
1. Go to 'https://designcember.com/'
2. Scroll down to 11th image
3. Click on '11th image'
4. when you click on 11th image , image is getting hide but popup will show

**Expected behavior**
Image should not hide on click. it should be visible like other images on click

**Screenshots**
Please find below screenshot for bug 
1. Before clicking on image
![image](https://user-images.githubusercontent.com/71959534/147327922-068f1ebc-90c1-4a61-9f8a-ecb00309a98d.png)
2. After clicking on image
![image](https://user-images.githubusercontent.com/71959534/147327982-a28a770a-1307-4c3c-8f35-f5751ffa915f.png)

**Comment by rachelandrew** [comment]
Closing as the Designcember team were made aware of this, and it's not a web.dev site issue.
