### ISSUE TITLE
100% score text not readable on https://web.dev/measure/

### ISSUE THREAD

**Issue by jhvanderschee** [GoogleChrome/web.dev#7123]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.usecue.com/

### What happened?

The text is white on a white background (probably some old fireworks css). 

### What did you expect?

dark text

### What have you tried?

reloading, which did not work

### How were you running Lighthouse?

WebPageTest

### Lighthouse Version

dunno

### Chrome Version

dunno

### Node Version

dunno

### OS

dunno

### Relevant log output

```shell
I ran https://web.dev/measure/ in firefox.
```

**Comment by jwpgroup** [comment]
JUst to back the OP up on this... there is 100% a bug here.  If you score 100 on all four categories using web.dev, then the returned results are unreadable (all blank until you hover over them).  You can see this on the homepage of https://www.quizsytems.co.uk/ as an example.
