### ISSUE TITLE
Add Glitches to team page.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#713]
(Please ignore this issue till Monday 🍹)

Hey folks, when you have a chance could you please add the following Glitches to our team page at https://glitch.com/@webdev. Look for the **Add Project** button.

![image](https://user-images.githubusercontent.com/1066253/54078071-cdedd200-4276-11e9-9dda-5269d8ffe326.png)

I'm going to setup Github -> Glitch syncing from our `glitches/` directory and I'll need these glitches to be part of the team for our shared token to work.

Thank you!

@khempenius 
~~https://glitch.com/~imagemin-grunt~~
~~https://glitch.com/~imagemin-gulp~~
~~https://glitch.com/~imagemin-webpack~~
~~https://glitch.com/~responsive-images-multiple-sizes~~
~~https://glitch.com/~responsive-images-art-direction~~
~~https://glitch.com/~responsive-images-density-descriptors~~
~~https://glitch.com/~correct-dimensions~~
~~https://glitch.com/~font-observer~~

@demianrenzulli 
~~https://glitch.com/~defer-css-unoptimized~~
~~https://glitch.com/~defer-css-optimized~~

@mihajlija 	— would it be ok if we turn this into a Glitch project? We can also check it into the web.dev repo in the `glitches/` directory.
https://github.com/mihajlija/lighthouse-bot-starter

@petele
~~https://glitch.com/~make-it-installable~~

**Comment by demianrenzulli** [comment]
Done!

**Comment by robdodson** [comment]
Thank you! 😄

**Comment by khempenius** [comment]
Done!

**Comment by robdodson** [comment]
Great thank you!

**Comment by petele** [comment]
Done!

**Comment by robdodson** [comment]
Thank you! 🤗
