### ISSUE TITLE
Drag and Drop demo broken in Incognito

### ISSUE THREAD

**Issue by pwnall** [GoogleChrome/web.dev#7134]
**Describe the bug**
The demo on https://web.dev/drag-and-drop/ is broken in Incognito.

**To Reproduce**
Please see the description and steps in https://crbug.com/1273552

**Expected behavior**
Please see the Chromium bug for a description. The Glitch demo should stop using Storage (localStorage), or we should find a way to serve our demos from a 1P context.

**Screenshots**
Please see the Chromium bug for a video demo.

**Comment by dstmarthe** [comment]
Thanks for raising this issue. We are migrating to a new platform and issue tracker. I have moved this to our new tracker at: https://issuetracker.google.com/issues/298799199
