### ISSUE TITLE
BrowserCompat widget shows "preview" instead of icon.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#7139]
oh hai!

**Describe the bug**
In [this article](https://web.dev/structured-clone/) the BrowserCompat widget is showing the word "preview" next to Safari, instead of an icon.

![image](https://user-images.githubusercontent.com/1066253/148707497-27ee21d2-5f3b-458a-95b2-fcb27275dac7.png)

Also, this is a total nit but, do y'all think the widget would look nicer if the icons were a bit larger?

![image](https://user-images.githubusercontent.com/1066253/148707596-3d565059-4217-4f0f-9320-9f0870f1d3b9.png)

I think the original design from Jiwoong had the icons larger and closer together, and then we made a separate smaller version for Patterns page because it was being used in a smaller area. But it may make sense to have a larger variant for articles, and a smaller one on Patterns.

**Comment by jpmedley** [comment]
Rob! Nice to you again.

Regarding "preview" this is what's in the BCD, indicating that this feature is so far only in Safari preview. Do you think this should say, "Safari preview" or do you have another idea?

**Comment by robdodson** [comment]
I'm not sure what it should say, but the visual appearance of the text breaking out of the circle definitely seems like a bug.

![image](https://user-images.githubusercontent.com/1066253/149609367-b2c0e283-a828-4af3-a0b0-bab55ac0823e.png)

It seems like maybe there should be an icon to signify something is a preview. Maybe a science beaker? I think MDN has something like that when it indicates something is experimental.

Also, now that I'm looking at it more closely, it looks like the red X for not supported browsers is not centered. It's slightly shifted down and to the left.

![image](https://user-images.githubusercontent.com/1066253/149609424-b3e10aba-107b-4107-842b-c918e7f67412.png)

**Comment by jpmedley** [comment]
I agree about how it looks. We need to fix this stuff. 

I don't think a beaker is the right symbol. The beaker on MDN means that a feature is experimental. I'm worried that a beaker could be taken erroneously to mean that some aspect of the API is still in question.

**Comment by MichaelSolati** [comment]
@robdodson hello there! I'm actually working on the browser compat now so I can work on this/these

**Comment by MichaelSolati** [comment]
@robdodson and @jpmedley how about an eye?

![image](https://user-images.githubusercontent.com/11811422/152269444-c899553f-eaf7-4d70-a555-5fdb6b827898.png)

**Comment by jpmedley** [comment]
The idea's good. The problem is that at this resolution, I didn't know it was an eye until you told me. An eye in profile might make better use of the round space and hence be more easily recognizable. I'm thinking a simplified version of this, but I don't know if there's enough space to make that legible.

![image](https://user-images.githubusercontent.com/8204171/152394267-95443e58-f9fe-4154-8d7a-41fa5df9db25.png)

**Comment by MichaelSolati** [comment]
@jpmedley ok, I think I'll need to use an svg for this, but I'm sure I can find one. I'll look and later today and share when i have a good one.

**Comment by jpmedley** [comment]
Awesome!
