### ISSUE TITLE
"Make it installable" PWA codelab doesn't work

### ISSUE THREAD

**Issue by dfabulich** [GoogleChrome/web.dev#7146]
The "Make it installable" PWA codelab doesn't work. When you follow the instructions, you don't get an Install button.

**To Reproduce**
1. Go to https://web.dev/codelab-make-installable/
2. Click "Remix to edit"
3. Copy the sample code into line 5, `/* Put code here */`
4. Click "View app" to see it in action.

Here's my sample fork. https://glitch.com/edit/#!/ludicrous-fork-cacao

**Expected behavior**
The "Install" button should appear at the bottom of the screen.

**Actual behavior**
The "Install" button doesn't appear.

**Explanation**
The problem is that the codelab is listening for the `onbeforeinstallprompt` event, but that event can't fire, for three reasons:

1. **The `onbeforeinstallprompt` never fires on `<iframe>`d sites.** By default, web.dev attempts to run the PWA in an `<iframe>` (on a custom glitch.com domain, e.g. https://ludicrous-fork-cacao.glitch.me) inside another `<iframe>` (on glitch.com). To eliminate the top-level `<iframe>`, the codelab would have to link to https://glitch.com/edit/#!/make-it-installable directly, (i.e. launching Glitch in "full screen" mode,) rather than embedding it in the codelab `<iframe>` layout. 
2. **There are two layers of `<iframe>`.** Launching Glitch in "full screen" mode only eliminates _one_ layer of `<iframe>`. The user would then need to click the "..." menu in the upper-right corner of the app preview to "Open in new window" to launch the app in a top-level tab. (I think it would also be wise to include a button in the code lab to pop the app out of its `<iframe>`, like the `requireHTTPS` link that's already there.)
3. **A branch new `glitch.me` domain won't meet the user-engagement heuristic at first.** Even if we do launch the app in a top-level tab, even _then_ the Install button won't show up, because the install criteria for a PWA are that the app "meets a user engagement heuristic." As of Jan 2022, to activate the `onbeforeinstallprompt` event, the user has to click at least once on the page, and remain on the page for at least 30 seconds. So the documentation needs to be updated to tell the codelab user to click somewhere on the page, and wait 30 seconds for the button to show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/96150/148874501-4537f63b-f41e-4231-8b8b-fd00adc76fbb.png)

**Comment by tomayac** [comment]
Calling out that the app needs to be run in its own window will do the job. @dfabulich, https://ludicrous-fork-cacao.glitch.me/ is installable.

**Comment by dfabulich** [comment]
I'll follow up in the PR (which is doesn't fix the problem, at the time I write this), but even if the PR were amended, it would only fix two of the three problems I identified.

https://ludicrous-fork-cacao.glitch.me/ doesn't have the `onbeforeinstallprompt` event fire until it meets the [user-engagement heuristics](https://web.dev/install-criteria/), i.e. the user has to click somewhere on the page and wait 30 seconds. (It's very difficult to test this, but the easiest way is to create a fresh new Chrome profile and visit the page in that profile. The install button won't appear until you've waited 30 seconds and clicked somewhere on the page.

Since this codelab is intended to teach developers how to use `onbeforeinstallprompt`, the codelab code sample should be updated to make it clearer when/why the user-engagement heuristics haven't been met.
