### ISSUE TITLE
Question about variable fonts article

### ISSUE THREAD

**Issue by plesiecki** [GoogleChrome/web.dev#7158]
Hello!

I have a question about fallback technique from https://web.dev/variable-fonts/#fallbacks.

This technique cause Chrome to download both static and variable fonts. It isn't necessary beneficial for performance. Do you consider this as a good practice? Or is this a Chrome bug?

Have a nice day. Peace

**Comment by heyawhite** [comment]
Adding @tomayac as one of the original post authors and @malchata for performance expertise. If either of you think someone else would be better equipped to answer this question, feel free to re-assign.

**Comment by malchata** [comment]
I actually don't know much about variable fonts, but in practice, unnecessarily loading additional assets is definitely an anti-pattern we don't want to prescribe. Do you have a codepen (or other demo) that reproduces this?

**Comment by tomayac** [comment]
The way to solve this would be:

```css
@supports (font-variation-settings: normal) {
  /* CSS for browsers with font variation support. */
}

@supports not (font-variation-settings: normal) {
  /* CSS for browsers without font variation support. */
}
```

The `@supports` rule is not supported by Internet Explorer, so this browser would not see any styling. If this is a problem, you could always use one of the [oldschool hacks](https://stackoverflow.com/a/20541859/6255000) to target relevant older browsers specifically.

I'll update the code accordingly in the article.

**Comment by plesiecki** [comment]
@malchata Here goes the repro https://codepen.io/plesiecki/full/jOGoPeZ if you still would like to see. 
Actually on my Chrome 99.0.4838.3 it's kinda funky.

<details>
  <summary>With code like this...</summary>

```
/* open-sans-latin-300-normal */
@font-face {
  font-weight: 300;
  font-family: 'Open Sans';
  font-style: normal;
  src: url('https://cdn.jsdelivr.net/npm/@fontsource/open-sans/files/open-sans-latin-300-normal.woff2') format('woff2');
  font-display: swap;
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}

/* open-sans-latin-400-normal */
@font-face {
  font-weight: 400;
  font-family: 'Open Sans';
  font-style: normal;
  src: url('https://cdn.jsdelivr.net/npm/@fontsource/open-sans/files/open-sans-latin-400-normal.woff2') format('woff2');
  font-display: swap;
  unicode-range: U+00??,U+0131,U+0152-0153,U+02bb-02bc,U+02c6,U+02da,U+02dc,U+2000-206f,U+2074,U+20ac,U+2122,U+2191,U+2193,U+2212,U+2215,U+feff,U+fffd;
}

/* open-sans-latin-600-normal */
@font-face {
  font-weight: 600;
  font-family: 'Open Sans';
  font-style: normal;
  src: url('https://cdn.jsdelivr.net/npm/@fontsource/open-sans/files/open-sans-latin-600-normal.woff2') format('woff2');
  font-display: swap;
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}

/* open-sans-latin-700-normal */
@font-face {
  font-weight: 700;
  font-family: 'Open Sans';
  font-style: normal;
  src: url('https://cdn.jsdelivr.net/npm/@fontsource/open-sans/files/open-sans-latin-700-normal.woff2') format('woff2');
  font-display: swap;
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}

@supports (font-variation-settings: normal) {
  /* open-sans-latin-variable-wghtOnly-normal */
  @font-face {
    font-weight: 300 800;
    font-family: 'Open Sans';
    font-style: normal;
    src: url('https://cdn.jsdelivr.net/npm/@fontsource/open-sans/files/open-sans-latin-variable-wghtOnly-normal.woff2') format('woff2 supports variations'), url('https://cdn.jsdelivr.net/npm/@fontsource/open-sans/files/open-sans-latin-variable-wghtOnly-normal.woff2') format('woff2-variations');
    font-display: swap;
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
  }
}
```
</details>

... Chrome downloads 300, 600, 700 and variable variants but no 400.

It gets funkier when variable font declaration define `font-weight` as `300 700`. Then Chrome doesn't download variable variant at all. Instead it downloads all static variants.

Actually in Firefox it works as you would expect. FF downloads only variable variant in any case.

**Comment by plesiecki** [comment]
I would like to reopen this issue for a moment @tomayac.
I've noticed that with `font-weight: 300 1000` Chrome downloads just variable fonts. 
I guess the article should take into account Chrome's weird behaviour.
Could you guys confirm this unexpected behaviour, please? I would like report bug in Chrome.

**Comment by tomayac** [comment]
Could you create a minimal reproduction case on a platform like [Glitch](https://glitch.com/), create a [new Chromium bug](https://new.crbug.com/) and then paste the link to the bug here, so I can help triage it to the right team? Thanks in advance for your help!

**Comment by plesiecki** [comment]
I've submitted a bug https://crbug.com/1291112.

**Comment by tomayac** [comment]
Thank you, I have looped in the right engineer on that.
