### ISSUE TITLE
Broken links on /handbook/web-dev-components

### ISSUE THREAD

**Issue by binyamin** [GoogleChrome/web.dev#7171]
**Summary**
Several links on [`/handbook/web-dev-components`](https://web.dev/handbook/web-dev-components/) are missing a proceeding slash, so they point to a non-existant page.

**To Reproduce**
1. Go to [the button section on the page in question](https://web.dev/handbook/web-dev-components/#buttons)
2. Click on "detailed specification"
3. Gasp in horror when you see a 404 message _(optional)_

**Possible Solutions**
Just gonna throw this out there: Should there be a system which checks for broken links when a page is updated?

**Comment by heyawhite** [comment]
There are actually multiple errors here around detailed specs! Good catch.

+1 to a system that flags broken links -- I've opened a request for our linter to check for broken links: https://github.com/GoogleChrome/web.dev/issues/7189

**Comment by heyawhite** [comment]
This error has been fixed. Thanks again!
