### ISSUE TITLE
"Chek your understanding" web tab flex not shown correctly

### ISSUE THREAD

**Issue by fish-404** [GoogleChrome/web.dev#7184]
**Describe the bug**
"Checking your understanding" filed web tab `flex` not correct. 
`web-assessment__content` class `display: flex` cause the tablist the tab panel display inline. 

**To Reproduce**
1. Go to https://web.dev/learn/forms/form-element/#web-assessment-0 (or other learning material with self assessment)
2. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/29678177/149885579-447cf036-a45d-488d-958b-030713fa015b.png)

**Comment by devnook** [comment]
Thanks @fish-404 ! Can you please sign the CLA agreement so that we can merge you PR? Details:
https://github.com/GoogleChrome/web.dev/pull/7185/checks?check_run_id=4850052118
