### ISSUE TITLE
Articles about font loading contradict each other

### ISSUE THREAD

**Issue by Discostu36** [GoogleChrome/web.dev#7213]
The web.dev documents about font loading have contradicting information.

These pages advise to and/or explain how to preload fonts:
* https://web.dev/font-display/ 
* https://web.dev/codelab-preload-web-fonts/ (by @garimamimani)
* https://web.dev/preload-optional-fonts/ (by @housseindjirdeh)

But this one advises against preloading fonts:
* https://web.dev/font-best-practices/ (by @khempenius)

Are the older articles outdated? Or is this a matter of opinion? What is currently the best way to go?

**Comment by tunetheweb** [comment]
I softened the warning against preload in #8797 which I think addresses this. And yes, it is a bit of a matter of opinion.
