### ISSUE TITLE
Localized collections should link to localized contents.

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#7225]
**Describe the bug**
Localized collections page is translated properly. However, the articles in that pages are linked to English contents regardless of if they are translated or not. Readers will not be able to find the translated articles.

**To Reproduce**
1. Go to https://web.dev/i18n/ja/secure/
2. Click on "Samesite cookies explained"

**Expected behavior**
Linked to https://web.dev/i18n/ja/samesite-cookies-explained/ so that the article is displayed in Japanese.

In currently implementation, it is linked to Linked to https://web.dev/samesite-cookies-explained/ so it's displayed in English despite it's already translated.

(Note that however if the browser is configured to Japanese as the primary lang for ex, the URLs won't have `/i18n/ja` and always displays Japanese contents where possible. I know this makes it lower priority, but someone how configures English as primary, but prefers Japanese where possible will have hard time finding translated contents.)

**Comment by devnook** [comment]
@MichaelSolati you were implementing localized learn pages recently, can you have a look?
