### ISSUE TITLE
Find a way to clearly distinguish static and instance methods here and on dcc.

### ISSUE THREAD

**Issue by domenic** [GoogleChrome/web.dev#7249]
In https://github.com/GoogleChrome/developer.chrome.com/pull/1934 @jpmedley is promoting a confusing style of referring to JavaScript object methods, where he pretends everything is a static method. E.g. in that example he suggested directing readers to the nonexistent `HTMLInputElement.showPicker()` method, which does not exist.

The static properties of `HTMLInputElement` are: `ATTRIBUTE_NODE`, `CDATA_SECTION_NODE`, ..., `name`, `length`, `prototype`, `apply`, `bind`, `call`, .... I.e., `HTMLInputElement.showPicker === undefined`, and trying to call `HTMLInputElement.showPicker()` will throw an exception. Whereas `HTMLInputElement.ATTRIBUTE_NODE === 2`, and trying to call `HTMLInputElement.bind()` will work.

I hope we can avoid misleading readers in this way, and clearly distinguish between static and instance methods. In specifications this kind of mistake would be completely unacceptable, and I hope in developer-facing documentation---where the audience is less experienced---it would also be avoided.

In specifications the style we use to refer to instance method is one of: `HTMLInputElement.prototype.showPicker()`, `HTMLInputElement`'s `showPicker()` method, or `inputElement.showPicker()`. I don't know which of those would be better for your site. But I do know documenting completely-fictitious entities such as `HTMLInputElement.showPicker()` is not reasonable.

Examples of this kind of style causing developer confusion in the past: https://github.com/mdn/content/issues/5244 https://github.com/mdn/content/discussions/5121

**Comment by rachelandrew** [comment]
Hi @domenic 

I've read through the linked thread (which seems to have been resolved) and also the discussion on MDN. It looks like this has been a used convention on MDN for some time though they are changing it now, is that correct? If so, it seems reasonable that we may have used that convention in the past here. I don't think anyone is deliberately trying to mislead developers.

That doesn't mean we need to continue using it in future, and given the discussion on MDN I think we should also move away from it and choose another convention. 

The style guide says [not to make a code element plural or possessive](https://developers.google.com/style/code-in-text), and for the reasons outlined in the MDN discussion I'm not keen on including `prototype`.

I'll ask the other writers to take a look and see if we can come up with a good alternative.

**Comment by rachelandrew** [comment]
@domenic I've been tracking this long running thread in https://github.com/orgs/mdn/discussions/248 on MDN, and I'd like us to align with how MDN are doing this. Does that make sense to you?

**Comment by domenic** [comment]
That sounds great to me!

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. Closing because content is frozen on this site. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/u/1/issues/298888662
