### ISSUE TITLE
Scroll not working on quiz results

### ISSUE THREAD

**Issue by EzraEn1** [GoogleChrome/web.dev#7262]
**Describe the bug**
Quiz results do not scroll in PWA.

**To Reproduce**
1. Go to a quiz with enough options to overflow in results.
2. Click on an answer, and check it.
3. Scroll down.
4. See error.

**Expected behavior**
Quiz results would scroll, and I would be able to proceed.

**Screenshots**
See overscroll shadow near bottom.
![Screenshot_20220129-013105_Chrome.png](https://user-images.githubusercontent.com/7076802/151594128-57c9cf73-f236-4ea0-a30c-264011e6d720.png)

**Comment by MichaelSolati** [comment]
@EzraEn1 what URL were you on? (What page is this quiz on?)

**Comment by EzraEn1** [comment]
Here on the [Learn Responsive Design!](https://web.dev/learn/design) page, down at the bottom. Both 2nd and 3rd questions produce long enough feedback in their results that I am able to identify that they are unscrollable.

**Comment by EzraEn1** [comment]
Attached below I have a screen recording in order to answer any other questions regarding the nature of the issue. https://user-images.githubusercontent.com/7076802/151915008-a518786e-0282-466e-83b7-eae916175546.mp4

**Comment by MichaelSolati** [comment]
Super useful, thank you. I'll work on this tomorrow.
