### ISSUE TITLE
Going to https://web.dev/svgcode/ slows the browser down

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#7266]
It seems like the videos on https://web.dev/svgcode/ cause performance problems with some browsers.

**Comment by otherjoel** [comment]
Observed on Firefox 96.0.3 on Win 10 Pro running on Xeon E5-1650 v3 @ 3.50GHz with 32GB RAM.

**Comment by otherjoel** [comment]
To clarify, on my Windows computer above, Firefox become nearly unresponsive/severely laggy in responding to mouse input when visiting the linked page.

Firefox 96.0.3 on my M1 Max MBP with 32GB RAM does not suffer any lag while viewing that page, but CPU usage as shown in Activity Monitor jumps to between 20–40%.

When visiting the page in Safari 15.3 on the same M1 Max MBP there are no discernible problems.

**Comment by tomayac** [comment]
After some more investigation this seems to be a Firefox issue. I have opened https://bugzilla.mozilla.org/show_bug.cgi?id=1752792 and am closing the present issue. Please track the Mozilla issue instead.
