### ISSUE TITLE
Storage & Quota Test https://storage-quota.glitch.me/ bugs

### ISSUE THREAD

**Issue by derMart** [GoogleChrome/web.dev#7268]
**Describe the bug**
Several functions on https://storage-quota.glitch.me/ do not work.
This tool is developed by the author of and for this article: https://web.dev/storage-for-the-web/ and also referenced there.
It is not possible to add several items, also calculation of items stored is not working.
Cause is that idbKV object is not (yet) loaded, when first accessed by updateCount. See:
![Screenshot from 2022-01-29 11-50-52](https://user-images.githubusercontent.com/1069456/151658275-7cd4b424-2528-4f8b-82e0-a8fa79f2f0cc.png)

**To Reproduce**
1. [Go to 'https://storage-quota.glitch.me/'](https://storage-quota.glitch.me/)
2. Click on 'Add 1MB' IndexedDB

**Expected behavior**
All functions should work

**Comment by beaufortfrancois** [comment]
@petele I've had a quick look at this issue and it seems like it could be addressed by applying this diff.

```diff
-      import { get, set, clear, keys, del } from 'https://cdn.jsdelivr.net/npm/idb-keyval@5/dist/esm/index.js';
+      import { get, set, clear, keys, del } from 'https://cdn.jsdelivr.net/npm/idb-keyval@6/+esm';
```

Thank you @derMart for reporting this!

**Comment by petele** [comment]
Awesome - thanks Francois! I've made that change, and it seems to be working now.
