### ISSUE TITLE
Examples are broken for the article: Control focus with tabindex

### ISSUE THREAD

**Issue by kenmorechalfant** [GoogleChrome/web.dev#7269]
**Describe the bug**
None of the examples on this page work. They don't have any styles to show that they are focused and therefore look like nothing's happening. 

**To Reproduce**
1. Go to: https://web.dev/control-focus-with-tabindex/
2. Click into an embedded example and press TAB

**Expected behavior**
Focused element is visibly distinct

**Result**
Focused element is no different from unfocused element

**Comment by rachelandrew** [comment]
I've just tested this in Chrome and it works as expected with a blue focus ring, so I'll need some more info as to which browser and so on this isn't working in.

**Comment by kenmorechalfant** [comment]
I'm using Chrome Version 97.0.4692.102 on Chrome OS. 
Google Pixelbook (eve, version 97.14324.0)

If I click into any of the example windows and press tab it will take multiple tabs to get the Glitch links at the bottom so it's as if it is focusing the elements correctly but they just don't look focused: no outline, no visual change at all.

**Comment by rachelandrew** [comment]
@kenmorechalfant is this better? https://peppermint-shelled-pink.glitch.me

**Comment by kenmorechalfant** [comment]
@rachelandrew Yes, now I see a thick yellow dashed outline on the focused element.

**Comment by rachelandrew** [comment]
@kenmorechalfant thanks for your patience with this! So I think the issue was that in dark mode it was so faint as to be barely visible. I've got a preview of a version with fixed demos here, hopefully that now looks ok for you? https://deploy-preview-7365--web-dev-staging.netlify.app/control-focus-with-tabindex/

**Comment by kenmorechalfant** [comment]
@rachelandrew Happy to help. I didn't think of it at first but I may have been seeing problems because of the Chrome Flag "[Auto Dark Mode for Web Contents](https://developer.chrome.com/blog/auto-dark-theme/)"; can't remember when I turned it on exactly but regardless I have it on now and that last link you sent looks all good 👍
