### ISSUE TITLE
won't load page 

### ISSUE THREAD

**Issue by OctaKitty888** [GoogleChrome/web.dev#7272]
**Describe the bug**
Loops the screen I'm trying to go to to upload documents. Bug is really sitting next to me. I need documents to be able to get passed them. Can't get any work done.

**To Reproduce**
1. Go to 'q-link.com'
2. Click on 'login'
3. Scroll down to 'type email and zipcode, summit'
4. Go to 'upload documents'
5. Error starts then'loops you back to previous screen'

**Expected behavior**
Load next page then able to upload documents to website.

**Comment by OctaKitty888** [comment]
Need help updating my Firefox and Chrome without having to go to playstore

**Comment by rachelandrew** [comment]
This is not the place for help with updating your browser.
