### ISSUE TITLE
Pages look broken

### ISSUE THREAD

**Issue by mohamedfasil** [GoogleChrome/web.dev#7298]
**Describe the bug**
Layout for the article seems broken on Macbook 16inch chrome 
**To Reproduce**
1. Go to 'https://web.dev/optimize-lcp'
2. See error

**Expected behavior**
The layout should be fine, but looks broken

**Screenshots**
<img width="1728" alt="Screenshot 2022-02-02 at 6 33 22 PM" src="https://user-images.githubusercontent.com/529158/152159062-f6e1dd28-20aa-475e-94d9-37dc7ad257c3.png">
<img width="1728" alt="Screenshot 2022-02-02 at 6 33 29 PM" src="https://user-images.githubusercontent.com/529158/152159085-97ea616e-1d96-434f-8dad-51d452407f77.png">

**Comment by mohamedfasil** [comment]
@jpmedley, yes thats what I meant, I'm on chrome v85 
![Screenshot 2022-02-03 at 10 27 13 AM](https://user-images.githubusercontent.com/529158/152283752-ab13a8db-3ad4-439b-ad51-2669181f0bb4.png)

**Comment by MichaelSolati** [comment]
@mohamedfasil a slew of the new CSS properties we use are features available in Chrome as of version 87 (released November 17, 2020).

Could you please update your Chrome to version 87 or later?

**Comment by mohamedfasil** [comment]
@MichaelSolati do you guys only support latest chrome for the web.dev site ?
Unfortunately this is on my office laptop, and I don't have admin privileges to turn on auto updates, a lot of users might have same use-case as me.

**Comment by MichaelSolati** [comment]
@devnook you may want to look at this

**Comment by MichaelSolati** [comment]
The issue stems from `margin-inline` and `padding-inline` which Chrome only supported starting with v87.

**Comment by devnook** [comment]
Hi @mohamedfasil ! I am sorry you experience this issue. We aim to support all modern browsers. However, we cannot guarantee support for a browser more than 1 year old, like Chrome 85. We have < 2% users on a Chrome 87 or older, and will most probably not have resources to prioritize support for this request.
