### ISSUE TITLE
Use font-display

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#731]
Adding this as a note to myself to see about using font-display and any other tricks we can use because the site has a lot of Google fonts.

**Comment by addyosmani** [comment]
Until we ship support for font-display in Google Fonts, I'd reco self-hosting and customizing font-display:swap ourselves 😄

**Comment by robdodson** [comment]
@addyosmani do I get this for free now? didn't google fonts add it to their stylesheet?

**Comment by addyosmani** [comment]
You get this for free now :) https://addyosmani.com/blog/google-fonts-font-display/

**Comment by robdodson** [comment]
ah ok cool so we should add the display param to our fonts. I need to check if we are allowed to do that with the current infra.

**Comment by robdodson** [comment]
Looks like this is a little bit trickier than I thought. We use the Material Icons font since DevSite used it previously. When we do display=swap on that, it causes all kinds of gnarly FOUC...

**Comment by robdodson** [comment]
See: https://www.zachleat.com/web/font-display-icon-fonts/

The best option is to not use material icons but that's a bigger can of worms.

**Comment by arpitansu** [comment]
Google Fonts Now Supports font-display.
