### ISSUE TITLE
Text inside `Aside` component is not rendered

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#7332]
**Describe the bug**
The text inside `Aside` box is not rendered. See https://web.dev/security-headers/#recommended-usages-2 as an example. Perhaps this is caused by being inside a `Details` section?

<img width="860" alt="Screen Shot 2022-02-10 at 23 56 54" src="https://user-images.githubusercontent.com/218144/153433735-e1976c85-bbb3-4cfc-9b1d-4ac14a39256d.png">

**Comment by rachelandrew** [comment]
@agektmr it seems odd the way this article is structured with that information inside a details element. That may be causing the issue but I think it might be better to create different heading structure, which would also have the benefit of improving the side nav. At the moment the "How to use" section doesn't show in the sidebar.

**Comment by agektmr** [comment]
My hypothesis at the moment is that the issue is occurring where the section is indented (+hidden inside details element). I'll find time to investigate it and unindent them if needed.

BTW, what do you mean by "sidebar"? I think what is used to be called sidebar is now at the top of the page?
