### ISSUE TITLE
11ty build speed investigation

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/web.dev#7339]
@devnook mentioned (and I noticed myself...) that the `npm run eleventy` step of the build process takes a bit of time, even for subsequent builds where some degree of caching is going on.

I ran `npm --node-options --inspect-brk run eleventy` and then [attached Chrome DevTool's profiler](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27) to take a peak at whether there were any particular hotspots. I'll add more to this thread as I find them.

## lodash/isPlainObject

One area that immediately stood out is calls to [`lodash/isPlainObject`](https://github.com/lodash/lodash/blob/2da024c3b4f9947a48517639de7560457cd4ec6c/isPlainObject.js), inside of 11ty's [`Merge.js`](https://github.com/11ty/eleventy/blob/08fe54e03da025cda24c4b25b5b8a8d0007b4689/src/Util/Merge.js#L1). I used [`module-alias`](https://github.com/ilearnio/module-alias) to swap that out for the implementation in [`typechecker`](https://github.com/bevry/typechecker) (see https://github.com/GoogleChrome/web.dev/commit/d41833e5c711a52e4b85ea0db1911a062ad8b375), and local build times improved _substantially_. The following are comparisons of the build with a warm cache on my M1 Macbook Pro.

Before:

``` sh
$ npm run eleventy 

> web.dev@3.0.0 eleventy /Users/.../git/web.dev
> eleventy --quiet

Eleventy is building, please wait…
Wrote 3372 files in 55.20 seconds (16.4ms each, v0.12.1)
```

After:

``` sh
$ npm --node-options '--require "module-alias/register"' run eleventy

> web.dev@3.0.0 eleventy /Users/.../git/web.dev
> eleventy --quiet

Eleventy is building, please wait…
Wrote 3372 files in 40.55 seconds (12.0ms each, v0.12.1)
```

You can reproduce them by checking out the https://github.com/GoogleChrome/web.dev/tree/isPlainObject-patch branch and running `npm --node-options '--require "module-alias/register"' run eleventy`

I know that we're not on the latest 11ty release, but they seem to still be using `lodash/isPlainObject` in v1.0.0, so I will follow up on the 11ty project to see if they would consider officially switching off of `lodash/isPlainObject`.

## luxon/DateTime

Another hotspot is in calls to the `luxon` library, via the `DateTime` class in [`pretty-date.js`](https://github.com/GoogleChrome/web.dev/blob/isPlainObject-patch/src/site/_filters/pretty-date.js). This is code that we control as part of our custom filter, and I'm going to investigate exactly what the output is supposed to be, and whether there's anything more efficient we could be using instead.

**Comment by jeffposnick** [comment]
Something else that can help speed things up is upgrading our recommended version of node from https://github.com/GoogleChrome/web.dev/blob/3c907dd2bc78e0a1eff09f4e9dbf331033cd429c/package.json#L185-L187 to node v16.

I am not exactly sure why node v16 performs better, but it seems clear that it does. The build times of 55 seconds (and 40 seconds with the more efficient `isPlainObject`) were tested with node v14. When I updates to node v16 (despite the current `engine` requirement in our `package.json`), the build times went down to 36 seconds with the unpatched `isPlainObject`, and **25 seconds** with the patch.

I'll open a separate issue to track updating any of our dependencies that might be keeping us stuck on node v14 so that we can encourage folks to use node v16, without any warnings.

**Comment by pdehaan** [comment]
@jeffposnick Have you noticed any performance/build improvements (or <i>un</i>improvements) between 0.12.1 and 1.0.0?
Curious if you've tried upgrading to 1.0.0 yet and how the process was.

**Comment by jeffposnick** [comment]
11ty v1.0.0 does appear to be faster, yes. (Given that we were already opted-in to data-deep-merge, the new default in v1.0.0 is a no-op for us.)

Here's the breakdown of 11ty v1.0.0 performance on my M1 Macbook Pro, across node v14 and node v16, both with and without the `isPlainObject` patch:

### node v14

```sh
$ npm run eleventy     

> web.dev@3.0.0 eleventy /Users/.../git/web.dev
> eleventy --quiet

Eleventy is building, please wait…
[11ty] Wrote 3372 files in 45.27 seconds (13.4ms each, v1.0.0)
```

```sh
$ npm --node-options '--require "module-alias/register"' run eleventy

> web.dev@3.0.0 eleventy /Users/.../git/web.dev
> eleventy --quiet

Eleventy is building, please wait…
[11ty] Wrote 3372 files in 33.01 seconds (9.8ms each, v1.0.0)
```

### node v16

```sh
$ npm run eleventy                                                   

> web.dev@3.0.0 eleventy
> eleventy --quiet

Eleventy is building, please wait…
[11ty] Wrote 3372 files in 32.00 seconds (9.5ms each, v1.0.0)
```

```sh
$ npm --node-options '--require "module-alias/register"' run eleventy

> web.dev@3.0.0 eleventy
> eleventy --quiet

Eleventy is building, please wait…
[11ty] Wrote 3372 files in 20.60 seconds (6.1ms each, v1.0.0)
```

So! We started out at **55 seconds** with `lodash/isPlainObject`, on node v14, and with 11ty v0.12.1.

When we patch out `isPlainObject`, update to node v16, and move to 11ty v1.0.0, the build time gets down to **21 seconds**.

**Comment by jeffposnick** [comment]
Another thing to look into is the performance impact of using `html-minifier`. When I remove it from out 11ty config, our `ELEVENTY_ENV=prod npm --node-options '--max_old_space_size=8192' run eleventy` build times go from **340 seconds** to **247 seconds**.

We probably still want to minify our HTML, though, so we should look into whether there are any faster options.

**Comment by devnook** [comment]
One thing to keep in mind is that the most troublesome is the build time during local development (for authors and devs). While improvements to prod build are still great, it's good to remember they solve a different use case.

**Comment by jeffposnick** [comment]
Yup! I think the 11ty 1.0.1, as soon as https://www.npmjs.com/package/@11ty/eleventy is updated, will help the most for local development.
