### ISSUE TITLE
Courses section has big layout shifts

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#7345]
**Describe the bug**
Visit a page like https://web.dev/learn/css/grid/

Notice that when the page loads, the sidebar appears to initially take up the entire page and then quickly shifts into the correct position. If you run the performance panel you'll see the layout shifts getting flagged.

![image](https://user-images.githubusercontent.com/1066253/153632209-bd3a484f-43b6-487c-b9ca-917b20975072.png)

These big shifts are bad for CWV and could cause the course pages to get down-ranked on Search.

**Comment by rachelandrew** [comment]
@hankchizljaw did you manage to investigate this?

**Comment by hankchizljaw** [comment]
Looking at it tomorrow
