### ISSUE TITLE
Add support for mermaid diagrams

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#7362]
Add support for mermaid style diagrams in Markdown, similar to what GitHub has done https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

**Comment by jeffposnick** [comment]
There are some [`markdown-it` plugins](http://mermaid-js.github.io/mermaid/#:~:text=Preview%20Sequence%20Diagrams-,Markdown%2DIt,-Textual%20UML%20Parser) linked to from the Mermaid docs.

(Also, it's somewhat awkward that this needs to be addressed in both the d.c.c. (https://github.com/GoogleChrome/developer.chrome.com/issues/2129) and web.dev side of things. It might be worth investigating whether our Markdown setup could be shared in https://github.com/GoogleChrome/webdev-infra instead for better consistency.)
