### ISSUE TITLE
Learn CSS : outdated text about `::backdrop` pseudo-element browser support

### ISSUE THREAD

**Issue by kalitine** [GoogleChrome/web.dev#7378]
**Describe the bug**
The text referring to the current browser supporting `::backdrop` pseudo-element is outdated.

**To Reproduce**
1. Go to [Learn CSS -> Pseudo-elements -> ::backdrop section](https://web.dev/learn/css/pseudo-elements/#::backdrop)
4. See the text : "The `::backdrop` pseudo-element is supported in all major browsers apart from Safari."

**Expected behavior**
Safari supports `::backdrop` pseudo-element since v15.4 (see https://caniuse.com/?search=%3A%3Abackdrop%20)

**Comment by rachelandrew** [comment]
Hi @kalitine - Safari 15.4 is still in beta so this text is correct. We will update it once 15.4 is available.
