### ISSUE TITLE
Installation Criteria in Learn PWA is missing a few things

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#7411]
* Use this template to request updates to existing content.
* Delete any fields that aren't relevant to your issue. 
* Update the title of this issue with a brief summary of the work to be done.

### What page(s) need to be updated?

[Installation Criteria](https://web.dev/learn/pwa/installation/#installation-criteria)

### Why is this update needed?
It's missing a few items.
* There's no mention of user engagement heuristics.
* It would also be useful to provide [browser-specific links](https://web.dev/install-criteria/#criteria) the way Pete's article does.

@tropicadri I can take care of this if you want.

**Comment by jpmedley** [comment]
@tropicadri I meant to make you aware of this when I opened it. I plan to do this myself, unless you want to.

**Comment by tropicadri** [comment]
Go ahead if you have the bandwidth, thanks for letting me know.
