### ISSUE TITLE
Missing " on codepen in Help users enter data in forms

### ISSUE THREAD

**Issue by QuegoFreki** [GoogleChrome/web.dev#7418]
**Describe the bug**
On the exemple of Pre-select an option on https://web.dev/learn/forms/form-fields/ the orange option is not displayed because the closing " on the value is missing

**To Reproduce**
1. Go to https://web.dev/learn/forms/form-fields/#pre-select-an-option 
2. Click on the select in the codepen exemple
3. The orange option is not displayed

**Expected behavior**
The orange value should be displayed in the select

**Screenshots**
![image](https://user-images.githubusercontent.com/99971498/156133861-533d5a47-4187-4159-b493-bc3432824595.png)

**Comment by jeffposnick** [comment]
Thanks for reporting—I _think_ those Codepen embeds are owned by @rachelandrew.

**Comment by rachelandrew** [comment]
they are in the web.dev account, but yes I have access to them :)
