### ISSUE TITLE
Listing translations alphabetically by underlying language code may not be best. 

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#7430]
**Is your feature request related to a problem? Please describe.**
The top of web.dev articles lists all all available translations of the article. The order appears random (see the image), but they seem to be ordered alphabetically by language code (except or 'en', which always appears to be last). This is not a problem when the number of translations is small. It could come across as a difficult mess if the list of translations is large.

![image](https://user-images.githubusercontent.com/8204171/156447598-67bb03b4-4326-4ce3-9a23-279a3a823020.png)

**Describe the solution you'd like**
Languages should be grouped by script. Within a script group, languages should be sorted in a way that is appropriate for that script. For example, languages rendered in the Latin script should be sorted alphabetically. 

**Describe alternatives you've considered**
Off hand, I can't think of any.

**Comment by jeffposnick** [comment]
It would also be nice to use `new Intl.ListFormat(lang).format(...)` instead of `join(', ')` to translate the array of language links into a localized list, including a final conjunction ("and" or the local equivalent).
