### ISSUE TITLE
Request for a new "Update" aside.

### ISSUE THREAD

**Issue by malchata** [GoogleChrome/web.dev#7435]
**Is your feature request related to a problem? Please describe.**
web.dev currently has a number of usual variations of the [aside component](https://web.dev/handbook/web-dev-components/#asides). Asides are a useful way for writers to interrupt the main flow of an article to call out some side note, pitfall, important note, and so on.

Currently, we lack an "update" variation on the aside component, which would be useful to use in select cases where updates concerning a developing situation around a certain API or metric can be effectively communicated. For example, we are currently using an "important" aside at this top of [this post](https://web.dev/responsiveness/) when an "update" aside would have been more appropriate.

**Describe the solution you'd like**
Asides that use a variation different than the default use a string to denote the variation type (for example, `'important'` or `'caution'`). An update aside should be something like this:

```
{% Aside 'update' %}
This unsolved mystery has new information. Check out this new video from Robert Stack to learn more.
{% endAside %}
```

cc: @philipwalton

**Comment by heyawhite** [comment]
I've made a request about examples as well: https://github.com/GoogleChrome/developer.chrome.com/issues/2170

**Comment by mihajlija** [comment]
+1 for the need for some sort of Updates component, especially on dcc as we are hosting things that are under active development there.

**Comment by mihajlija** [comment]
Not stale

**Comment by matthiasrohmer** [comment]
Resolved by https://github.com/GoogleChrome/web.dev/pull/9119.

**Comment by heyawhite** [comment]
Note of availability / design in the docs: https://web.dev/handbook/web-dev-components/#update-asides
