### ISSUE TITLE
Interop 2022: Subgrid screenshot doesn't look quite right

### ISSUE THREAD

**Issue by ishitatsuyuki** [GoogleChrome/web.dev#7453]
### What page(s) need to be updated?

https://web.dev/interop-2022/

### Why is this update needed?

The subgrid screenshot doesn't look quite right...

![image](https://user-images.githubusercontent.com/12389383/156933103-fd755210-8745-4cc3-ba24-8af4e89bba2a.png)

This is how it's supposed to look:

![image](https://user-images.githubusercontent.com/12389383/156933134-5151dca8-350c-49ad-aab7-ed237e88a18b.png)

Did you accidentally capture this in a browser without subgrid support?

cc @foolip

**Comment by rachelandrew** [comment]
@ishitatsuyuki good catch, thank you. I've just opened a PR to fix this.

**Comment by foolip** [comment]
@ishitatsuyuki thanks for reporting!
