### ISSUE TITLE
CodelabsCallout returns undefined and it was printed

### ISSUE THREAD

**Issue by leader22** [GoogleChrome/web.dev#7466]
**Describe the bug**

![image](https://user-images.githubusercontent.com/6259812/157156151-bd558cf1-8e3e-4bd3-8ba8-7a1056ccdad6.png)

> https://web.dev/i18n/ja/http-cache/

It seems that it happens for translated pages.

https://github.com/GoogleChrome/web.dev/blob/abeb34cbb879fbca93b4765989ebde53524f3e5d/src/site/_includes/components/CodelabsCallout.js#L37

If I fix this line to return `''`(empty string, also matches function typings), `undefined` has gone but empty `div` still remains.

**To Reproduce**

1. Go to https://web.dev/i18n/ja/http-cache/
2. Scroll down to bottom
3. See `undefined` 

I found the same issue in 

- https://web.dev/i18n/ja/serve-images-webp/
- https://web.dev/i18n/es/sign-up-form-best-practices/
- etc...

**Expected behavior**

Render Codelabs component properly or render nothing.

**Comment by jpmedley** [comment]
@jeffposnick
