### ISSUE TITLE
Translated pages displaying inconsistent translation list results

### ISSUE THREAD

**Issue by tannerdolby** [GoogleChrome/web.dev#7476]
**Describe the bug**
The https://web.dev/i18n/en/browser-fs-access/ page which is under the "English" translation, displays the "English" item in the "Available in: " translation list, but for other translated pages like https://web.dev/i18n/es/browser-fs-access/, the language of the translated page i.e. "Español" is not included in the list.

**To Reproduce**
1. Go to 'https://web.dev/i18n/en/browser-fs-access/'
2. Scroll down to the "Available in: "  translation list
3. See that "English" is included in the list of translations even though that is the translated page we are currently viewing
4. Go to 'https://web.dev/i18n/en/browser-fs-access/' and check the "Available in: " list to see that "Español" is not part of the list.

**Expected behavior**
I think it makes sense to not display the language in the available translations list when were currently viewing that translated page, so I expected the /i18n/en/ pages to not display "English" in the translations list. 

It does seem good/preferred to have "English" added in the available translations list on the "main" page https://web.dev/browser-fs-access/ like currently implemented which is not apart of /i18n/* pages.

**Screenshots**
_screenshot of the "/i18n/en" page containing "English" in translations list_
<img width="651" alt="Screen Shot 2022-03-08 at 12 25 53 PM" src="https://user-images.githubusercontent.com/48612525/157319290-ddf03287-ee5f-4a1a-9185-1b7ca8920cdc.png">

_screenshot of the "/i18n/es" page which doesn't contain "Spanish" in translations list_
<img width="658" alt="Screen Shot 2022-03-08 at 12 26 01 PM" src="https://user-images.githubusercontent.com/48612525/157319316-08fc242b-a464-42d4-a296-374fb2d5c8c0.png">

**Comment by jpmedley** [comment]
cc: @devnook @rachelandrew
