### ISSUE TITLE
Footer license note isn't accessible

### ISSUE THREAD

**Issue by Snugug** [GoogleChrome/web.dev#75]
I'd make a PR for this but I can't get the CSS to show up locally.

On `/learn`, the license information in the footer isn't accessible. In order for this to be compliant at this size, that font color needs to be made darker.

![Footer Color Accessibility, inaccessible](https://user-images.githubusercontent.com/377188/47859661-c6945480-ddbc-11e8-8184-869a169a8ed8.png)

Changing the color slightly makes it AA accessible

![Footer Color Accessibility, accessible](https://user-images.githubusercontent.com/377188/47860040-a022e900-ddbd-11e8-91b3-ce2c2720307b.png)

Changing it to the same color as the `devsite-content-footer` component background actually makes it AAA accessible

![Footer Color Accessibility, accessible, mimic footer component](https://user-images.githubusercontent.com/377188/47860144-de200d00-ddbd-11e8-92d1-a7b106f86c95.png)

**Comment by robdodson** [comment]
Should be fixed by cl/226246002
