### ISSUE TITLE
Updating the Origin Trial information & the demo app for Prerender2

### ISSUE THREAD

**Issue by uskay** [GoogleChrome/web.dev#7506]
Three fix proposals to make the [Prerender2 article](https://web.dev/speculative-prerendering/#same-origin-prerendering-trial) consistent with the actual OT behavior:

1. Suggestion to make the OT limitation explicitly written for prerender2 that it is **[only for Android](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/prerender/prerender_origin_trial_browsertest.cc;l=330?q=origin%20trial%20prerender2&ss=chromium%2Fchromium%2Fsrc)** 
2. Suggestion to update the writing of the OT period to be available until M100
3. Suggestion to update https://prerender2-specrules.glitch.me/ 's OT token (it's now expired)

- [x]  For 1 & 2 I'll propose a PR.
- [x] For 3 if you want me to fix it, please share collaboration access to the glitch project.

@addyosmani

**Comment by addyosmani** [comment]
@uskay Please feel free to update the OT token! You can update the code for the demos here https://glitch.com/edit/#!/prerender2-speculationrules?path=README.md%3A1%3A0 I've shared access with your Glitch account.

Could you ping me with a follow-up PR when thats done and we can update the article? (note the Glitch is at a different URL to the one in the article)
