### ISSUE TITLE
Scroll-snap example is not working

### ISSUE THREAD

**Issue by bamaboy** [GoogleChrome/web.dev#7520]
**Describe the bug**
The [scroll-snap example](https://codepen.io/web-dot-dev/pen/XWeNPzY) from [ui-patterns page](https://web.dev/learn/design/ui-patterns/#carousels) is not working in the latest Chrome version.

It happens because of `overflow-inline: auto` property.
It took me some time before I  found out that this property available in Firefox browser only.
Wouldn't be better to replace `overflow-inline` with `overflow-x` in the example?
Because example shows how `scroll-snap-align` property works and it seems fine to use `overflow-x` in that case.
Or at least mention that example won't work in Chrome?

**To Reproduce**
1. Go to [ui-patterns page](https://web.dev/learn/design/ui-patterns/#carousels)
2. Open the [scroll-snap example](https://codepen.io/web-dot-dev/pen/XWeNPzY)
3. `scroll-snap-align: start` property doesn't seem to work

**Expected behavior**
When the iframe content is scrolled card items should stick to the left corner

**Screenshots**
![Mar-17-2022 13-24-31](https://user-images.githubusercontent.com/10559998/158789353-44b39539-3958-4920-820e-c77550ae78bf.gif)

**Comment by jeffposnick** [comment]
@rachelandrew, I'm not sure if you wrote all the original (anonymous) content, but I see that you're the one who submitted the PR. Could you investigate or follow-up with the original author?

**Comment by rachelandrew** [comment]
@bamaboy thanks for reporting this, I've updated the CodePen and the linked PR will fix the copy once it is deployed.
