### ISSUE TITLE
https://web.dev/learn/ layout is broken

### ISSUE THREAD

**Issue by azu** [GoogleChrome/web.dev#7523]
**Describe the bug**

https://web.dev/learn/ Collections layout is broken.

**To Reproduce**

0. New Secret Window in Chrome 
1. Go to https://web.dev/learn/
2. Scroll down to Collection

**Expected behavior**

Grid Layout
https://web.archive.org/web/20220306115328/https://web.dev/learn/

<img width="1682" alt="image" src="https://user-images.githubusercontent.com/19714/158949299-77d730df-cedd-4b4e-94f0-7c5f77d1c92b.png">

**Screenshots**

screenshot on body node
![image](https://user-images.githubusercontent.com/19714/158949180-e0819a7f-cf53-4667-85f1-a3673f9e9fa6.png)

Tested environments:

- Gogle Chrome: 99.0.4844.74（Official Build） （arm64）macOS
- Firefox: 98.0.1 (64 bit) macOS

**Comment by jeffposnick** [comment]
This was fixed in the short-term via the roll-back in https://github.com/GoogleChrome/web.dev/pull/7528

We'll look more closely to figure out what went wrong when that page's HTML was minified.
