### ISSUE TITLE
content: TODO Update deferred CSS implementation recommendations

### ISSUE THREAD

**Issue by kentr** [GoogleChrome/web.dev#7567]
### What page(s) need to be updated?

* https://web.dev/defer-non-critical-css/

### Why is this update needed?

The implementation recommendations for deferred CSS loading  appear outdated.

There is an [aside](https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/fast/defer-non-critical-css/index.md?plain=1#L124) on the page which recommends that in production "functions like loadCSS" are better than the vanilla / native implementation given on this page:

> In this guide, you used vanilla code to implement this optimization. In a real production scenario, it's a good practice to use functions like [loadCSS](https://github.com/filamentgroup/loadCSS/blob/master/README.md), that can encapsulate this behavior and work well across browsers.

However, the `loadCSS` documentation contradicts the above by [recommending a vanilla / native implementation very similar to the one on this page](https://github.com/filamentgroup/loadCSS/blob/master/README.md#how-to-use):

> As a primary pattern, we recommend loading asynchronous CSS like this from HTML:
> `<link rel="stylesheet" href="/path/to/my.css" media="print" onload="this.media='all'; this.onload=null;">`
> This article explains why this approach is best: https://www.filamentgroup.com/lab/load-css-simpler/
>That is probably all you need! But if you want to load a CSS file from a JavaScript function, read on...

### What's the deadline?

Since the advice on this page appears outdated, I suggest ASAP.

I'm happy to submit a PR after maintainers review this issue.

**Comment by jeffposnick** [comment]
CC: @demianrenzulli, as he's the original author.

**Comment by fredericDelaporte** [comment]
This page is going on recommending loadCSS while it is now an archived GitHub project, on top of having its documentation contradicting the page.
