### ISSUE TITLE
Remove URL button aligned to top in Firefox

### ISSUE THREAD

**Issue by adamopenweb** [GoogleChrome/web.dev#757]
On https://web.dev/measure using Firefox the remove URL button is vertically aligned to the top vs. middle in Chrome.

```html
<div class="lh-enterurl lh-enterurl--switch">
   <input type="url" class="lh-input" placeholder="Enter a web page URL" pattern="https?://.*" minlength="7" required="">
   <button class="lh-enterurl__close" aria-label="Remove URL"></button>
</div>
```

![image](https://user-images.githubusercontent.com/6587558/55029907-9f475980-4fe1-11e9-8daa-af8148a279cf.png)

Tested in Firefox 66-68 on MacOS and Windows 10.

**Comment by robdodson** [comment]
Going to roll this into #773 as there's an additional bug on that page we should fix in FF.
