### ISSUE TITLE
pwa blank screen after installed and start up first time

### ISSUE THREAD

**Issue by meiqi502** [GoogleChrome/web.dev#7575]
**Describe the bug**
after add pwa to home screen and start up auto first time, it work weill, but when i jump to a new page using window.history api, new page show blank screen, but actually i found that all the request was successful, and when drag the devTool i found that page had been rendered and it seems like just a blank mask uppon the page. And after i close and restart the pwa, it works well and blank screen was disappeared.  i don't think it is a bug of chrome but want to ask for help, thank you!

**To Reproduce**
……

**Expected behavior**
……

**Screenshots**
1、blank page
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/10473648/160132263-03dc3638-df2d-4497-8ba3-d224b0556f34.png">

2、drag devTool found the page had been rendered
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/10473648/160132183-f4f27088-f014-4784-84b9-19958aa4a92f.png">

**Comment by jeffposnick** [comment]
I'm sorry, but as this is not related to a content issue with web.dev, we are unable to assist in this issue tracker.
