### ISSUE TITLE
"Properly size images" warning triggered by incorrect handling of picture srcset for mobile

### ISSUE THREAD

**Issue by ErikJJonsson** [GoogleChrome/web.dev#7576]
When measuring page quality with web.dev we have noted that responsive images are not loaded correctly.
This is generating a "Properly size images" warning and a lower scrore.

**To Reproduce**
1. Go to web.dev
2. Click on Measure
3. Enter URL: https://art-prod.azureedge.net/utstallningar/tidigare-utstallningar/da-bfa1-utstallning/
4. Click on Run audit
5. Wait for audit to finish
6. Scroll down to Opportunities
7. Expand Properly sized images

The issue can also be reproduced in Chrome running in responsive mode.
But if the Chrome window size is decreased to mobile size instead the correct image size is loaded.
So maybe web.dev is using Chrome(Chromium) as "engine" and is using a large window (somehow).

**Expected behavior**
No "Properly sized images" should be shown and the correct image (size) for mobile should be loaded.

**Screenshots**
![bild](https://user-images.githubusercontent.com/48356833/160144984-970db8bd-c9c9-42c7-9478-e257873f5893.png)

**Comment by rachelandrew** [comment]
@ErikJJonsson apologies for such a slow reply on this, however the Measure tool has been moved to Pagespeed Insights (https://web.dev/measure/), if this is still a problem over there, you could raise the issue with that team.
