### ISSUE TITLE
Error in Same Origin Policy quiz

### ISSUE THREAD

**Issue by NiedziolkaMichal** [GoogleChrome/web.dev#7584]
**Describe the bug**
Sample 4 of a quiz present in https://web.dev/same-origin-policy/ contains a mistake. The image can always be drawn, but depending on CORS policy, canvas might become tainted and it will not be possible to get its content. Methods getImageData, toBlob and toDataURL will throw an exception. Same mistake is repeated in [What is permitted and what is blocked?](https://web.dev/same-origin-policy/#what-is-permitted-and-what-is-blocked) right next to keyword "images".

**Comment by heyawhite** [comment]
@agektmr to confirm. If that's the case, I can address in an update.

**Comment by agektmr** [comment]
@NiedziolkaMichal You are right. I'm surprised now one noticed this mistake until now.

The answer for the quiz should be updated for example:

"Yes. Although the image is on a different origin, loading it via an image source does not require CORS. However, accessing the binary of the image using JavaScript such as `getImageData`, `toBlob` or `toDataURL` requires explicit permission by CORS."

And the description for the image should be something like:

"Embedding cross-origin images is permitted. However, reading cross-origin images (such as retrieving binary data from a cross-origin image using JavaScript) is blocked."

**Comment by NiedziolkaMichal** [comment]
@agektmr That sounds good, thank you
