### ISSUE TITLE
Clarify lazy loading auto versus eager

### ISSUE THREAD

**Issue by tunetheweb** [GoogleChrome/web.dev#7588]
### What page(s) need to be updated?

https://web.dev/browser-level-image-lazy-loading/#the-loading-attribute

### Why is this update needed?

As per [this Twitter thread](https://twitter.com/addyosmani/status/1508510605560274944?s=21&t=ehkSr5T-6jYasxMZGhqMvQ) Chrome supports lazy loading `auto` (the default but not in the spec) but [the spec](https://html.spec.whatwg.org/multipage/urls-and-fetching.html#lazy-loading-attributes) states `eager` is “the default state”. This is confusing to developers as that thread shows.

Is there a difference? Apparently used to be for Lite Mode but won’t be once it’s fully deprecated?

There’s also an argument that having `eager` being faster than the default (as it’s name implies) might be a good thing. But that would be a spec change and it’s already shipped in the three main browsers so this may be too big a change.

### What's the deadline?

No deadline

#### Is it a hard deadline?

Nope

**Comment by kurtextrem** [comment]
Maybe it would make sense to clarify (either per spec, or by mentioning it in the article) that `fetchpriority` is the correct tool to boost images compared to adding `loading=eager`

**Comment by addyosmani** [comment]
@kurtextrem now that `fetchpriority` is shipping to stable, I would be comfortable with us cross-referencing it as the preferred solution for signaling a desired boost in image fetch priority compared to `loading=eager` (difference use-case).

In terms of next steps on @tunetheweb's issue: I'm going to confirm that dropping `auto` in favor of focusing on `eager` as the default expectation here would make sense as Lite Mode is being deprecated. We don't (afaik) have other plans for the `auto` value.

**Comment by tunetheweb** [comment]
I'd still like to see an addition to the article here. @addyosmani , happy to draft a PR if you like?

**Comment by addyosmani** [comment]
A PR would be very much welcomed. Thank you!
