### ISSUE TITLE
LinkedIn link not displayed in author card.

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#7590]
Some authors have a `"linkedin"` meta data field, but its content (unlike, for example, Twitter or home page)  is not surfaced in author cards. We should probably surface LinkedIn as well, or retire the `"linkedin"` field and ask authors to make their LinkedIn page their home page instead.

**Comment by matthiasrohmer** [comment]
Merged into https://github.com/GoogleChrome/web.dev/issues/7591.
