### ISSUE TITLE
Glitch embed failing because of incorrect permissions

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#7630]
**Describe the bug**
The [demo in the keyboard lock article](https://web.dev/keyboard-lock/#demo) fails.

**To Reproduce**
1. Go to [this page](https://web.dev/keyboard-lock/#demo) and open DevTools.
2. Click 'Enter full screen'. 

The following message appears in the console: "Blocked opening 'https://keyboard-lock.glitch.me/' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set."

**Expected behavior**
The glitch opens in a new window.

**Comment by albajarazeth** [comment]
Hello! I am going to pick this up since no one has worked on it : )

**Comment by AaronForinton** [comment]
Hi @albajarazeth please let me know once a PR is raised. Thanks for picking this up.

**Comment by albajarazeth** [comment]
For sure!

**Comment by AaronForinton** [comment]
@albajarazeth You're right, though the issue wasn't raised in the wrong repository, the article has migrated sites since this issue was originally raised. Let me just copy this issue into the developer.chrome.com repository and I'll tag you there.

**Comment by AaronForinton** [comment]
The new issue is at: https://github.com/GoogleChrome/developer.chrome.com/issues/5611
