### ISSUE TITLE
Got error message, no description 

### ISSUE THREAD

**Issue by juancrescente** [GoogleChrome/web.dev#7633]
I entered the website
Entered the URL https://yourafricansafari.com/
Got a message that says error

that’s it

**Comment by jpmedley** [comment]
@juancrescente,

Thank you for submitting this. Unfortunately, this is for reporting an issue with a specific web site that we run. To report an issue with Chrome:

1. Click the Settings menu. (It's in the upper right corner of Chrome and looks like three vertical dots.)
2. Select **Help**, then **Report an isse**.

Before doing that, you should try going to the web site again. It's probably an issue with that site and not with Chrome.
