### ISSUE TITLE
Learn HTML 06: Attributes

### ISSUE THREAD

**Issue by rachelandrew** [GoogleChrome/web.dev#7694]

**Comment by Krish-bhardwaj** [comment]
Hi , i am new to opensource have decent knowledge of web dev , can you explain me this issue so that i can propose a pr for this . if you could assign me this issue that would be really great .

**Comment by the-lazy-learner** [comment]
I'd love to be able to contribute to the content on web.dev. It would also be very nice if it was possible to collaborate with other people.
