### ISSUE TITLE
Safari: Measure URL placeholder obscured in safari

### ISSUE THREAD

**Issue by co16353sidak** [GoogleChrome/web.dev#772]
the url placeholder on the measure page gets obscured in safari.
URL: https://web.dev/measure
Screenshot: 
<img width="1012" alt="Screenshot 2019-04-05 at 11 00 40 PM" src="https://user-images.githubusercontent.com/35738138/55645719-e5c56100-57f6-11e9-9093-42a62d875173.png">

According to me there seems to be some added padding to the input search bar which is pushing the text down and obscuring the content. would love to work on this as my first issue
🥇 

(could be added to issue #751 checklist )

**Comment by robdodson** [comment]
Hey @co16353sidak thanks for reporting this. Unfortunately the custom elements that we use on the site are not open sourced so we'll have to fix this one ourselves. Really appreciate the offer to help though! We should be open sourcing the CSS for the site pretty soon.

**Comment by robdodson** [comment]
Looks fixed in latest.
