### ISSUE TITLE
Switched examples on "min(), max(), and clamp()" article

### ISSUE THREAD

**Issue by rafaelmoreton** [GoogleChrome/web.dev#7734]
**Describe the bug**
The example videos from the [min-max-clamp article's 'perfect width' section](https://web.dev/min-max-clamp/#the-perfect-width) are switched. The min() example video show under the max() paragraph and vice versa

**To Reproduce**
1. Go to https://web.dev/min-max-clamp/#the-perfect-width
2. Scroll down to the second and third embedded videos from this section

**Expected behavior**
Each example video should show right under the paragraph that describes it.

**Comment by Krish-bhardwaj** [comment]
Hi , i am new to opensource have decent knowledge of web dev , can  i work on this issue . if you could assign me this issue that would be really great .

**Comment by rafaelmoreton** [comment]
Hi, Krish. Sorry, but since I'm not an admin of this repo I'm afraid I'm not in position of assigning issues.
