### ISSUE TITLE
Navigation for web push articles not working

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/web.dev#7750]
**Describe the bug**
See https://twitter.com/nhoizey/status/1516390052120694786

Referencing: https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/blog/push-notifications-how-push-works/index.md

**To Reproduce**
1. Go to https://web.dev/push-notifications-how-push-works/
2. Read "Lets go through each step in more detail." at the very end of the article
3. See there is no link to the next page

**Expected behavior**
There should be an action to go to the next page

**Comment by gauntface** [comment]
Thanks for picking this up @rachelandrew 

I should have added, on my old version of this I had links for the previous and next page: https://web-push-book.gauntface.com/how-push-works/

**Comment by jpmedley** [comment]
The easiest thing was to remove the offending sentence so the the reader continues on to the next heading, "Where to go next". This has [gone line](https://web.dev/push-notifications-how-push-works/#:~:text=That%27s%20the%20whole,go%20next%20%23) so closing the ticket.
