### ISSUE TITLE
GitHub suggesting reviewers not in our organization

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#7757]
**Describe the bug**
I don't know whether this is a GitHub problem or a problem with our tool chain. I just opened a PR. The suggested reviewer is someone who is not even in Google, much less part of DevRel.

![image](https://user-images.githubusercontent.com/8204171/164268265-fb977209-34ba-40bf-ab45-a49696fbc681.png)

**Comment by jeffposnick** [comment]
GitHub [suggests reviewers for PRs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review#:~:text=Suggested%20reviewers%20are%20based%20on%20git%20blame%20data.) based on which users have previously committed changes to the files. Andy Bell has recently committed changes to a number of files, particularly those related to layout.

If the suggestion were someone who had no involvement at all with those files or our repo, it would be a bug that we would escalate with GitHub. As it is, it doesn't seem like a bug to me, and it's not something we can control.
