### ISSUE TITLE
"Learn more" buttons on /web-components are broken

### ISSUE THREAD

**Issue by AndrewJakubowicz** [GoogleChrome/web.dev#7759]
On the page https://web.dev/web-components/, the "Learn More" buttons seem to all be broken.

**Steps to reproduce the behavior:**

1. Go to https://web.dev/web-components/
2. Click on "Learn more" under any of the four sections.
3. Nothing happens

**Expected behavior**
The button should navigate to a page, instead of doing nothing.

Tested on:
 - Chrome 100
 - Safari 15.4

**Screenshots**

https://user-images.githubusercontent.com/15080861/164337463-95a74264-19d8-40f8-87ab-b21131023246.mov

**Comment by jeffposnick** [comment]
This page was migrated over from d.g.c. in #7644, and it looks like there are some issues with the translation.

CC: @rachelandrew @simgobb

**Comment by rachelandrew** [comment]
I'm looking into this, also mentioned in https://twitter.com/LeaVerou/status/1519142455433732100
