### ISSUE TITLE
Make comments more distinguishable from regular code in code blocks

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#7762]
Currently comments don't stand out very much:

<img width="432" alt="Screen Shot 2022-04-20 at 16 30 43" src="https://user-images.githubusercontent.com/145676/164396898-319af7b5-9b11-4f8e-83b0-2d149c53b9ef.png">
<img width="430" alt="Screen Shot 2022-04-20 at 16 31 13" src="https://user-images.githubusercontent.com/145676/164396905-bbb6dc64-cc6c-4c3a-919c-a22ddb6d6ed4.png">

Compare the above to, for example, GitHub's syntax highlighting:

```js
elem.addEventListener('dragover', (e) => {
  // Prevent navigation.
  e.preventDefault();
});
```

The comment color seems to be defined in [`/_syntax-highlighting.scss`](https://github.com/GoogleChrome/web.dev/blob/main/src/scss/blocks/_syntax-highlighting.scss), which in turn references https://github.com/GoogleChrome/web.dev/blob/89854a7c595c04558043f589e1926ec5be77fbcf/src/site/_data/design/tokens.json#L173-L174.

For a concrete proposal, I suggest making comments green-ish, which is a color traditionally a lot of themes use for comments. To throw something in the ring, `#216204` meets AAA recommendations in light mode, `#83dc73` in dark mode.

**Comment by dstmarthe** [comment]
Thanks for raising this. We're moving to a new platform, and I'm not sure if we can make these sort of changes on there, but I have migrated this feature request to our new issue tracker just in case.
See it here: https://issuetracker.google.com/issues/298556753
