### ISSUE TITLE
content: variable fonts format specifier in the `src` descriptor needs updates

### ISSUE THREAD

**Issue by myakura** [GoogleChrome/web.dev#7774]
### What page(s) need to be updated?

* https://web.dev/variable-fonts/#loading-variable-font-files
  (source: [/src/site/content/en/blog/variable-fonts/index.md](https://github.com/GoogleChrome/web.dev/blob/e5e87746c542aa87d7314681f1bb0037035c4e28/src/site/content/en/blog/variable-fonts/index.md) )

### Why is this update needed?

The article recommends to put `format("woff2 supports variations")` and `format("woff2-variations")` to specify variable fonts in the `@font-face` rule.

https://github.com/GoogleChrome/web.dev/blob/e5e87746c542aa87d7314681f1bb0037035c4e28/src/site/content/en/blog/variable-fonts/index.md?plain=1#L327-L345

The spec has changed multiple times since the publication of the article; the `_format_ supports _technology_` argument has gone. The current draft replaces it with the [`tech()` functional notation](https://drafts.csswg.org/css-fonts-4/#font-face-src-parsing); however, no browser engine supports the syntax (nor the old `_format_ supports _technology_`).

So I would rather suggest dropping the first description entirely and just to use `format("woff2-variations")` for now. I know it's an old syntax and is deprecated, but that's the only one browsers currently support.

**Comment by jeffposnick** [comment]
CC: @una @argyleink @jh3y @bramus — would one of you be able to evaluate this change? I think it would entail more than just removing `url('RobotoFlex-VF.woff2') format('woff2 supports variations')` from the inline example, as there is explanatory text that may need updating as well.

**Comment by argyleink** [comment]
seems like updating the code and copy to the latest text may be easier? then the blog patch is just updating it to newer experimental syntax? same tips and suggestions apply from the blog text, just corrections to the latest syntax? we don't even delete anything, change `format('woff2 supports variations')` to `tech('variations')` and update the links?

could also remove the fallback explanation and syntax too, but that seemed useful in the post? aka, i could go either way. but the post was trying to show how to use modern syntax with fallbacks, and we should keep that tip?

**Comment by myakura** [comment]
> seems like updating the code and copy to the latest text may be easier? then the blog patch is just updating it to newer experimental syntax? same tips and suggestions apply from the blog text, just corrections to the latest syntax? we don't even delete anything, change `format('woff2 supports variations')` to `tech('variations')` and update the links?

Yeah that is easier to do. sent a PR https://github.com/GoogleChrome/web.dev/pull/7900
