### ISSUE TITLE
[File System Access article] rename, move, and remove – do they exist?

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/web.dev#7786]
https://web.dev/file-system-access/#deleting-files-and-folders-in-a-directory

#7084 added references to these methods, but they don't seem to actually exist. I see no mention of them in the [spec](https://wicg.github.io/file-system-access/). cc @tomayac 

Chrome canary:

<img width="377" alt="image" src="https://user-images.githubusercontent.com/4071474/164965125-24ff51c6-b50e-4a3f-86ec-f1d67e98c9fa.png">

**Comment by tomayac** [comment]
The methods `move()` and `remove()` exist in Chrome Canary 103 (and I think even 102):

<img width="545" alt="Screen Shot 2022-04-25 at 09 20 51" src="https://user-images.githubusercontent.com/145676/165039677-a4acf081-cf53-4b1f-8d2f-335318482205.png">

The `rename()` function was consolidated with `move()` in https://github.com/GoogleChrome/web.dev/commit/403c3028c2e88bd2153415b4cda96c9dad2d841c. 

Note the [warning](https://web.dev/file-system-access/#:~:text=Warning,origin%20trial%20enabled.) though:

> _"Due to some open questions regarding cross-file-system moves, `move()` is temporarily disabled for folders and moves outside of the [origin private file system](https://web.dev/file-system-access/#accessing-the-origin-private-file-system). This feature is currently only available in the origin private file system to those with the [AccessHandles origin trial](https://developer.chrome.com/origintrials/#/view_trial/3378825620434714625) enabled."_
