### ISSUE TITLE
The `BrowserCompat` macro should indicate when features are deprecated

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#7798]
**Is your feature request related to a problem? Please describe.**
The new How-to section that @tomayac is working on lists both an old and a new way to accomplish a task. Some of the old methods of doing things are only provided as a fallback while the new gains market share. 

Many of them are deprecated. The BrowserCompat macro should show them as such.

**Describe the solution you'd like**

The records in the browser compatibility data contain a boolean member at *`category.feature`*`.status.deprecated` to indicate whether the *specification* is deprecated. For example, the deprecation status of `navigator.canShare()` is located at `api.Navigator.canShare.status.deprecated`. 

When `deprecated` is false, the BrowserCompat macro should show it in some way.

**Describe alternatives you've considered**
We could add a note to the how-to articles. Since this is being tracked for us anyway, we should take advantage of the available data.

**Additional context**
If we find that the deprecation status of a feature is out of date, we can submit a PR to the compat database and all users of that data including MDN will benefit.

**Comment by jeffposnick** [comment]
This sounds like a reasonable feature, but I want to learn a bit more about how and how often this would be used.

For instance, the `status.deprecated` for `navigator.canShare()` is `false`, so... I'm assuming that we wouldn't want to display anything special? Wouldn't we want to only display something special when `status.deprecated: true`?

Assuming we only wanted to display something for features where `status.deprecated: true`, how many of those do you think we'll likely end up embedding using `BrowserCompat`? If there are not likely to be very many instances where it happens, it would be harder to justify the engineering work at the moment.

**Comment by jpmedley** [comment]
>I'm assuming that we wouldn't want to display anything special? Wouldn't we want to only display something special when status.deprecated: true?

Absolutely. I was having trouble finding a concrete example of something that was false.

There are currently 720 deprecated items in the api branch of the BCD repo. 1228 for the repo overall.

`grep -r -n '"deprecated": true' ./ | wc -l`

How hard would this be? Seems like the desing work would take longer than the implementation.

**Comment by jeffposnick** [comment]
The design work taking longer than the implementation might be true, yup. (I don't know who would do the design work.)

I guess the bigger question is how often we actually expected to use `BrowserCompat` for a feature that's been deprecated in new content that we write? I know you mentioned something about an article that Tom was writing, but the underlying feature in that case isn't marked with `status.deprecated: true`. So it's more a question of whether this code/design would ever get displayed in a real article.

**Comment by jpmedley** [comment]
I'm working on one that needs it. It's one of Thomas's How-to articles. Those always show the new way followed by the old way. The old way will likely involve a deprecation. We need to show that the new idea isn't just a good idea. An old way could become deprecated while we're not looking

**Comment by jpmedley** [comment]
Historically, everything DevRel has worked on has been new, making the need for this minimal. I assume this macro will be used widely in Stable Channel. We will then have references to many more deprecated items than we have in the past.

**Comment by tomayac** [comment]
In the concrete case, this is about `document.execCommand()`. MDN presents this with a little trashcan icon 🗑:

<img width="652" alt="Screen Shot 2022-05-12 at 17 27 32" src="https://user-images.githubusercontent.com/145676/168111788-a5feed07-78a2-4caa-b4df-f2959edf2292.png">

**Comment by rachelandrew** [comment]
I'm not sure how common this case will be - though I'm happy for you to prove me wrong. I don't think the "old way" will commonly involve a deprecation. A lot of time time old ways use things that are still valid, just in an inefficient way.

I don't think there is anything wrong with the suggestion, it's just a matter of priorities, and how often we're going to encounter the situation.
