### ISSUE TITLE
Issue with "Chrome DevRel PR checks" bot

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/web.dev#7804]
Our PR bot config is set up so that "Eng team approval" is all that should be required for `*.js` and `*.json` files:

https://github.com/GoogleChrome/web.dev/blob/af9d12d938108f673dfe2045b9548c205d034fe3/.github/chrome-devrel-bot.json#L19-L39

https://github.com/GoogleChrome/web.dev/pull/7771/files is a PR that only includes changes to `*.js` and `*.json` files, and I've approved it, but https://github.com/GoogleChrome/web.dev/pull/7771/checks?check_run_id=6194499441 shows that the checked did not pass because "Content team approval failed".

**Comment by devnook** [comment]
The Pr actually changes one of .md files too: https://github.com/GoogleChrome/web.dev/pull/7771/files#diff-70ca957dd7c3b57e95695b84395c80d8c727a020f227d6fa8ff3c5892e56c1f0

This is why a content review was required.
