### ISSUE TITLE
web-copy-code messes with page focus order

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#7817]
**Describe the bug**
It looks like the web-copy-code element is positioning an invisible button at the top of the page so when you tab through an article, the focus keeps jumping up to the header.

**To Reproduce**
1. Go to https://web.dev/web-platform-04-2022/
2. Press Tab to move through the article, notice that tabbing past a code block moves focus to the top of the page.

**Expected behavior**
Focus should not jump to the top of the page when tabbing past a code block.

**Screenshots**
![image](https://user-images.githubusercontent.com/1066253/165977919-6ff76930-30fe-4bc1-9882-0ae81a879411.png)

**Comment by robdodson** [comment]
Some possible solutions would be to make the button display: none or visibility: hidden, that should remove it from the focus order. Or you could use `inert` on it (https://developer.chrome.com/blog/inert/)

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
