### ISSUE TITLE
Documentation for Implementing Banner to install Native App on mobile web app

### ISSUE THREAD

**Issue by winkylocc** [GoogleChrome/web.dev#7819]
The following page has documentation for implementing a smart app banner but can not be found, (404). 
https://web.dev/app-install-banners-native

Is there a reliable resource available for implementing this feature that doesn't blend the requirements for a PWA with it?

Can we also get a confirmation on if this feature is supported at all. It doesn't seem like it.

**Comment by jpmedley** [comment]
@rachelandrew I can't find this article in the repo. Is this a /web article that was misplaced during the move?

**Comment by rachelandrew** [comment]
@winkylocc where did you find a link for this page?

**Comment by winkylocc** [comment]
It is mentioned https://stackoverflow.com/questions/69854149/add-native-banner-on-web-app-no-pwa-not-working
and https://stackoverflow.com/a/66699454
and https://stackoverflow.com/q/55838392, mentioned https://www.drupal.org/project/appbanners/issues/3047715

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by winkylocc** [comment]
@rachelandrew It is mentioned [here](https://stackoverflow.com/questions/69854149/add-native-banner-on-web-app-no-pwa-not-working), [here](https://stackoverflow.com/a/66699454), [here](https://stackoverflow.com/q/55838392), [here](https://www.drupal.org/project/appbanners/issues/3047715), and also the first link on this google
[github](https://github.com/google/WebFundamentals/issues/6481) page.

**Comment by rachelandrew** [comment]
thanks - I think this is something that went astray during our content migration. I'll track it down.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue and relevant comments to our new tracker and you can see it at https://issuetracker.google.com/u/1/issues/298700528
