### ISSUE TITLE
 nomodule scripts have inconsistent behaviour on safari 12

### ISSUE THREAD

**Issue by luisvieiragmr** [GoogleChrome/web.dev#783]
Safari 12 has an inconsistent behaviour when implementing the differential module serving referenced at https://web.dev/fast/serve-modern-code-to-modern-browsers

Observed behaviour: when loaded with an empty cache both scripts referenced with the  `module` and `nomodule` attributes get downloaded but only the module script gets executed

Expected behaviour: only module scripts should get downloaded and executed

There's an issue opened at: https://bugs.webkit.org/show_bug.cgi?id=194337

It also has a small repro: https://jg-testpage.github.io/es-modules/module-nomodule/safari.html

**Comment by robdodson** [comment]
Thanks for reporting this @luisvieiragmr. @housseindjirdeh do you know if this warrants a note on the article? My main concern is that we'll forget to take the note down when the bug is finally fixed...

**Comment by housseindjirdeh** [comment]
Thanks a million for this @luisvieiragmr 

Yep, was chatting with @luisvieiragmr about this earlier. I think we should include a note at the very least that mentions that this bug persists with a specific version of Safari as the latest. Definitely brings us back to discussions of making sure things we mention get updated with future releases of tools 🤔

**Comment by robdodson** [comment]
yeah I wonder if we can have a space that we define in YAML that's like a reminder of sorts to tell us what stuff the article references.

```
browsers:
	# this means the article mentions something related to safari 12.1 which may not be true when safari is on version 12.1+
	- safari_12.1
	# similar for libraries...
libraries:
	- webpack_4.2
	- react_16.8
```

**Comment by robdodson** [comment]
One tricky thing to ponder... how would you handle browser APIs that are usually not versioned—until they are.

example: Web Components v0 -> Web Components v1

**Comment by robdodson** [comment]
@housseindjirdeh do you think you'll have a chance to add this note?

**Comment by robdodson** [comment]
Hey @housseindjirdeh, are you ok adding a note about the Safari behavior? I think we can separate the version tracking stuff into its own ticket.

**Comment by housseindjirdeh** [comment]
Merged in a note that covers this some time ago! https://github.com/GoogleChrome/web.dev/commit/dbf379225da4309ed66470b02905ccad2b024c5e

Apologies for not closing this ticket a lot sooner. Instead of singling out Safari behavior, I mentioned that double fetches can occur in some browsers and linked to Jason's article for ways to resolve it 🚀

**Comment by housseindjirdeh** [comment]
With regards to version tracking stuff, please let me know if you think it's worthwhile to implement sometime soon? 

More than happy to start exploring ways we can make that work for version-specific instances that we need to call out for.
