### ISSUE TITLE
[Case Study] Core Web Vitals Real-time Monitoring led to 99% of "good experience" pages at Skroutz.

### ISSUE THREAD

**Issue by katsampukas** [GoogleChrome/web.dev#7833]
#### A brief summary of the content proposal

[Skroutz.gr](https://www.skroutz.gr/) is the leading price comparison search engine and marketplace of Greece and a top-1000 ranked website globally by [Similar Web](https://www.similarweb.com/website/skroutz.gr). 

To solve rendering performance issues that we were facing occasionally, we established a **continuous monitoring** and alerting system of Core Web Vitals, using field data (real users).

This continuous monitoring helps to be in touch with rendering and speed issues and to organically establish a “fast speed mentality”.

We're going to explain how we set up the real-time monitoring and alerting system and also **3 incidents where Core Web Vitals proved to be essential** in delivering a better user experience. These are:
a. Server-side rendering gone wrong.
b. New page layout shifts.
c. CSS grid module issues.

Ιncorporating Core Web Vitals monitoring has led [Skroutz.gr](https://www.skroutz.gr/) to an impressive 99,5% of ~26 million pages seen as providing a “good page experience”!

#### What content already exists on this topic?

Some relevant case studies regarding Core Web Vitals are:

1. https://web.dev/rebelmouse/
2. https://web.dev/economic-times-cwv/
3. https://web.dev/renault/

However, I haven't read yet a case study discussing the real-time monitoring and alerting system and how this can be helpful.

#### Who will be authoring the content?

The content will be authored by me, [katsampukas](https://github.com/katsampukas), a senior front-end engineer at Skroutz.gr.

#### Are there any stakeholders who should be informed when this content changes?

No.

#### What area is your content related to?

Frontend, Performance, Core Web Vitals.

#### What kind of content are you creating?

Case Study.

**Comment by rachelandrew** [comment]
@katsampukas we're not currently looking for case studies submitted by third parties - sorry!
