### ISSUE TITLE
caniuse browser compatibility info outdated

### ISSUE THREAD

**Issue by ashleedawg** [GoogleChrome/web.dev#7834]
Browser compatibility info from [caniuse.com](https://caniuse.com/css-math-functions) is **outdated**., but instead of the static images, the tables could be kept current using an intermediary such as [caniuse.bitsofco.de](https://caniuse.bitsofco.de/).

Example: https://web.dev/min-max-clamp/ includes an [outdated image](https://web-dev.imgix.net/image/tcFciHGuF3MxnTr1y5ue01OGLBn2/ZIgePP41Quh7ubYh54vo.png?auto=format&w=1252) _(shows 89% support for css math functions)_ 
<img src="https://web-dev.imgix.net/image/tcFciHGuF3MxnTr1y5ue01OGLBn2/ZIgePP41Quh7ubYh54vo.png?auto=format&w=1252" width="600">

However a "live" image from a utility site like https://caniuse.bitsofco.de/ would keep the information on web.dev updated. The site has images updated daily (like below) or fully interactive embeds.

Example: https://caniuse.bitsofco.de/image/css-math-functions.png _(support for css math functions is actually 90%+)_
<img src="https://caniuse.bitsofco.de/image/css-math-functions.png" width="600">

I'm not affiliated with either site.

**Comment by rachelandrew** [comment]
@ashleedawg thanks - I'll update these using our MDN widget rather than Can I Use, as that will stay up to date.

**Comment by matthiasrohmer** [comment]
Those articles use the BrowserCompat widget in the meantime.
