### ISSUE TITLE
Serve standalone .js and .json files in CodePattern demos

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/web.dev#7853]
From @tomayac :

I'm working on the Advanced Apps patterns and ran into trouble with the existing design of the "CodePattern". Essentially I would want to show a pattern as in this [demo](https://app-badge-pwa.glitch.me/). It's an installable PWA that progressively enhances a favicon badge so it becomes a browser app badge once installed. 

You can see the problem in the [deploy preview](https://deploy-preview-7645--web-dev-staging.netlify.app/patterns/advanced-apps/badges/demo): while the in-browser-tab case seemingly works, it doesn't find the service worker file required for installation, which it looks for at [/patterns/advanced-apps/badges/sw.js](https://deploy-preview-7645--web-dev-staging.netlify.app/patterns/advanced-apps/badges/sw.js). The same happens for the manifest. Both files get listed in the [code preview](https://deploy-preview-7645--web-dev-staging.netlify.app/patterns/advanced-apps/badges/), so they are "there" visually in the "CodePen", but then not exposed on the path.

Is there a way I could get a service worker file and manifest exposed?

**Comment by devnook** [comment]
...and indeed we get CSP error in Prod for this:

https://web-dev-production-1--staging-duuagiud.web.app/patterns/advanced-apps/
<img width="1518" alt="Screenshot 2022-05-06 at 15 16 22" src="https://user-images.githubusercontent.com/1914261/167138897-34ec5bb5-4573-4e0d-88a1-576d746cd17f.png">

**Comment by tomayac** [comment]
Thanks for starting this Issue. Noting that the demo would also require `.svg` and `.png` files for the icons in the manifest.

**Comment by luxevwood** [comment]
ok
