### ISSUE TITLE
[Feature Request] AutoFill & AutoStart benchmark from URL parameters like on "PageSpeed"

### ISSUE THREAD

**Issue by MartinHotmann** [GoogleChrome/web.dev#7957]
I use link on websites prefilled URLs to benchmarks so when someone clicks on the link a new fresh benchmark is performed.

With [PageSpeed](https://pagespeed.web.dev) I do it like this:
https://pagespeed.web.dev/report?url=https://www.heldmayer.com

But with [web.dev/measure/](https://web.dev/measure/) I still do have some trouble, as the same thing here does not work:
https://web.dev/measure/?url=https://www.heldmayer.com

Are there any other workarounds, to create a link that automatically and prefilled performs a benchmark at [web.dev/measure/](https://web.dev/measure/)?

Thanks in advance!

**Comment by jeffposnick** [comment]
This seems reasonable to me. I don't feel great about having it automatically start an audit, but prefilling the input field makes sense.

**Comment by MartinHotmann** [comment]
Thanks! I actually would appreciate if it automatically would start just like at [PageSpeed](https://pagespeed.web.dev/). Maybe with an additional parameter like:

https://web.dev/measure/?url=https://www.heldmayer.com&run=true
? (order of queryStrings should not matter!)

Why do I want this? I often place links of benchmarks as PoW (proof of work) in imprints to have the links handy and noptify the owner about them, they then just have to click on them and have nothing more to do then wait.. this also is a "reaction" on the removing of the [premalinks from lighthouse](https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://www.heldmayer.com), which previously (some months ago) existed.. sadly they are gone.

The links looked something like this: https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://www.heldmayer.com

They have been my favourite. But yeah since they are gone I at least would like it if a link with some little modification at least again would output something equal (all 4 disciplins, not just performance like at GPSI)

For me it would be a great favour and I would probably go for links like this:

https://web.dev/measure/?run=true&url=https://www.heldmayer.com

since I like having the domain at the end as it appears for me to be cleaner, so would be awesome if the order would not play a role :)


Thanks in advance!

**Comment by MartinHotmann** [comment]
Or even cooler would be:

`url=https://www.heldmayer.com` will set the URL:
https://pagespeed.web.dev/report?url=https://www.heldmayer.com

`run=https://www.heldmayer.com` will set & run it:
https://pagespeed.web.dev/report?run=https://www.heldmayer.com

I like this approach the most :)
