### ISSUE TITLE
Googlers access

### ISSUE THREAD

**Issue by bendevjunior** [GoogleChrome/web.dev#7973]
I want to start contributing content to web.dev but I saw that I need Googlers access, how do I get it?

**Comment by rachelandrew** [comment]
Googlers are people who work for Google. You can contribute to this repo without working for Google. Just raise a PR against the thing you want to fix.

**Comment by bendevjunior** [comment]
To write an article you need to access the cdn and register the image, how would it be like to create an article would you send the image in pr ? or would put the image's absolute path (both author profile and featured image)

[Reference on web.dev](https://web.dev/handbook/markup-media/)

**Comment by rachelandrew** [comment]
Before writing an article you should raise an issue to "Propose new content", and fill in the details about your proposed article so we can take a look and see if it is a good fit for the site.

**Comment by bendevjunior** [comment]
thanks for clarifying @rachelandrew
