### ISSUE TITLE
Suggestion: copy text and link to text together in one clipboard

### ISSUE THREAD

**Issue by martoiu** [GoogleChrome/web.dev#7978]
It would be very handy if there was an option to copy the selected text together with the link to the text at the same time. 

I collect text for research and I want to return to the same text in context later, to reread it. This add-on for Firefox is therefore very handy. But I have to copy first the text then the link and then to paste them separately where I save them. It would be very handy if I could copy the text and the link to it in only one operation.

Many thanks in advance,

Mihai

**Comment by jeffposnick** [comment]
Can you please use https://crbug.com/new to report issues with the Chrome browser, extensions, or DevTools?

This issue tracker is reserved for reporting issues with the web content on https://developer.chrome.com/
