### ISSUE TITLE
Redirects to other domains only work with trailing `/`

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#7979]
If the user enters a URL without the trailing slash `/`, they are redirected to the version with `/` (for example, https://web.dev/svgcode → https://web.dev/svgcode/). This feature is lost with redirects to other domains:

❌ Doesn't work: https://web.dev/fugu-status → N/A
✅ Works: https://web.dev/fugu-status/ → https://developer.chrome.com/blog/fugu-status/

**Comment by tomayac** [comment]
Thanks, Jeffy, for the thorough investigation. If you want, I can also file that PR so you don’t have to. Just let me know.

**Comment by jeffposnick** [comment]
It's fine. I've got it.
