### ISSUE TITLE
URL instead of hyperlink

### ISSUE THREAD

**Issue by ItisEternity** [GoogleChrome/web.dev#7993]
**Describe the bug**
On https://web.dev/learn/pwa/capabilities/ page instead of a hyperlink there is URL text

**To Reproduce**
1. Go to 'https://web.dev/learn/pwa/capabilities/'
2. Scroll down to 'Orientation lock' bullet point
3. See the URL text instead of hyperlink

**Expected behavior**
Hyperlink 

**Screenshots**
![image](https://user-images.githubusercontent.com/77201958/170276797-cb50dc54-7567-4314-aab2-5339fd2aed89.png)

**Comment by jeffposnick** [comment]
Thanks for reporting!
