### ISSUE TITLE
Broken HTML on page

### ISSUE THREAD

**Issue by mbarker84** [GoogleChrome/web.dev#7996]
**Describe the bug**
The last two sections of [this page](https://web.dev/new-responsive) are centered and italicized, which on inspection appears to be a result of the paragraphs unintentionally rendering inside a `<figure>`. This results in those sections appearing confusing and difficult to read.

**To Reproduce**
1. Go to [web.dev/new-responsive](https://web.dev/new-responsive/#responsive-to-the-form-factor)
2. Scroll the page to see the different style of the last two sections

**Expected behavior**
The styling should be consistent with the other sections

**Screenshots**
![Screenshot 2022-05-26 at 10 09 23](https://user-images.githubusercontent.com/10262051/170458124-04c8ee54-543e-440e-98b0-21fc8ee681e3.png)
![Screenshot 2022-05-26 at 10 09 32](https://user-images.githubusercontent.com/10262051/170458131-b03e846a-d085-47c9-a354-5f8b51b6064a.png)

**Comment by mbarker84** [comment]
Proposed fix in PR #7997

**Comment by rachelandrew** [comment]
Fixed in #7997
