### ISSUE TITLE
Add d.c.c. links to collection pages in a clear way

### ISSUE THREAD

**Issue by rachelandrew** [GoogleChrome/web.dev#7999]
In https://github.com/GoogleChrome/web.dev/pull/7998 is a request to add offsite links to a collection.

I found a previous example and have got the offsite links working, however we could do with a good way of flagging these, especially when linking to experimental APIs.

**Comment by rachelandrew** [comment]
Apparently there used to be a little arrow icon indicating an offsite link, that would be useful for links in other content, though I think these blocks of external links in a collection could do with a clear indication. Could we have a flag to add to the group that would then style their box differently?

**Comment by heyawhite** [comment]
+1 to this issue
