### ISSUE TITLE
[Blog] Entendendo dados estruturados 

### ISSUE THREAD

**Issue by bendevjunior** [GoogleChrome/web.dev#8016]
- Proposed title: Entendendo dados estruturados 
- Proposed by: bendevjunior
- Content summary: Vamos entender um pouco sobre dados estruturados e qual sua função e importância para um website
- [Draf](https://docs.google.com/document/d/1gDJZmmGW0IODky27KkolHC9LnfEqh6lVN9szNvsZvDE/edit)

**Comment by bendevjunior** [comment]
It remains to upload a photo of the author and the article, as I do not have access to the CDN I need help with this

Author photo: https://bendevoficial.com/fotos/bendev.jpg
Post photo: https://bendevoficial.com/fotos/google-seo-photo.jpg

[I already requested the PR regarding this issue](https://github.com/GoogleChrome/web.dev/pull/8017)

**Comment by rachelandrew** [comment]
@bendevjunior Is this a translation of an existing article? 

The primary language of web.dev is English so we can't accept a new article in languages other than English as we don't have any editing capacity. We do have translations of existing article to other languages, however the initial article is written in English.

**Comment by bendevjunior** [comment]
@rachelandrew Hello, I updated the article now it has the English and Portuguese version :)

**Comment by rachelandrew** [comment]
@bendevjunior I can only see Portuguese in the Google doc, I've closed the PR as if the article is published it would only be after our review process, which we do in English, in Google docs format. Thanks!

**Comment by bendevjunior** [comment]
Hi @rachelandrew  sorry :(, I changed the draft to English awaiting your approval

**Comment by rachelandrew** [comment]
Hi @bendevjunior - this isn't the sort of content we publish on this site, it's pitched more to beginners as a basic overview, which isn't the audience we serve, so I'll not be going forward with this. We do have details of the audience, plus details of voice and tone for this site in our [handbook](https://web.dev/handbook/).

In future if you have an idea for a post, then you should talk to us first ([by raising an issue](https://github.com/GoogleChrome/web.dev/issues/new?template=propose-new-content.md) as I originally explained) so we can let you know if it sounds like something we would publish. In general, if you want to publish on other sites, it really is worth reading their guidelines so you don't spend time writing something that is not going to work for the site.

Some other places you could post your piece are:

- https://dev.to/
- https://hashnode.com/
