### ISSUE TITLE
Async CSS suggestion should be updated to respect CSP

### ISSUE THREAD

**Issue by idontusenumbers** [GoogleChrome/web.dev#8018]
**Describe the bug**
On https://web.dev/defer-non-critical-css/

The suggested method to work around blocking CSS is to use a onload handler. This is typically in violation of most CSPs.

> Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'strict-dynamic' 'nonce-cf7b4d067fced743'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

**Comment by tunetheweb** [comment]
Fixed with #9736
