### ISSUE TITLE
Reenable PWA category

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/web.dev#802]
The service worker checks were broken on the PSI backend.
As of today, they are fixed thanks to @hoten's work.

web.dev is clear to start surfacing PWA results again.

**Comment by robdodson** [comment]
![omg](https://user-images.githubusercontent.com/1066253/55763916-f99edc00-5a1d-11e9-9b0e-066e96ac15a5.gif)

That is very exciting news.

**Comment by robdodson** [comment]
We should finally get around to doing this, but it won't be as easy as turning that category back on. We'll need to do a few additional steps:

1. We have a design from Huge to make the /measure page configurable. This will let folks opt out of specific categories like PWA. We got this feedback loud and clear when we originally launched with the PWA category enabled.
2. We'll have to make the design accomodate the new PWA badge. Unfortunately Huge's design still used the old score gauge treatment so we'll have to ask Chrome UX to update the design for us.

**Comment by paulirish** [comment]
Cooool! Can you share the design?

**Comment by robdodson** [comment]
yep i'll email it to you

**Comment by robdodson** [comment]
I'm going to put this on our Q1 2020 project board. Not sure if we'll _finish_ in Q1 but I'd like to at least get started during this quarter.

**Comment by dstmarthe** [comment]
We are moving to a new platform and content on this site is now frozen. As this is about the site, we'll have to close this thread.
