### ISSUE TITLE
Allow for multiple authors for a given Web.dev guide

### ISSUE THREAD

**Issue by demianrenzulli** [GoogleChrome/web.dev#805]
I'm not sure if this is currently available, but I just didn't find a way to do it:

Most times guides involved many reviewers but a single author, but sometimes they can be the result of multiple collaborators. 
Other sites, like Web Fundamentals allow for multiple authors ([example](https://developers.google.com/web/updates/2019/02/rendering-on-the-web)).

Would be useful to count with something like that.

**Comment by robdodson** [comment]
👍

Going to fold this in to #771
