### ISSUE TITLE
Understanding "same-site" and "same-origin"

### ISSUE THREAD

**Issue by guettli** [GoogleChrome/web.dev#8072]
**Describe the bug**

> By examining the value of Sec-Fetch-Site, you can determine if the request is "same-site", "same-origin", 
> or "cross-site" ("schemeful-same-site" is not captured in Sec-Fetch-Site).

Source: [Bottom of **Understanding "same-site" and "same-origin"**](https://web.dev/same-site-same-origin/#how-to-check-if-a-request-is-%22same-site%22-%22same-origin%22-or-%22cross-site%22)

It is unclear what "you can determine" here.

From the point of view of a backend developer, you must not trust http-headers. 

I guess above  "you can determine" means that JS developers can detect check which kind of request
they just did. 

Please have second look at the above quote, maybe there is a way to make it more precise.

**Comment by agektmr** [comment]
Hi @guettli, thank you for the feedback.
Since browser blocks websites from manually adding HTTP headers that start with `Sec-`, the server can safely expect that they are genuinely generated by the browser. Even if a random curl command or another server issues the header, it won't harm the client since they are not a browser.
Happy to add a note to the section about it if that makes sense.

**Comment by heyawhite** [comment]
Re-opened as I don't believe #8078 addressed this issue -- it was related to the same subject, but not the sentence in question.

**Comment by mhoad** [comment]
@agektmr Just wanted to add that I also had a similar set of thoughts while reading the original article and trying to understand under what specific circumstances the assumptions I might normally make when writing a server may not be true here. You mentioned a random curl request and the logic makes total sense as to why that isn't a problem. But I think maybe a paragraph at the end to help developers understand the threat model a bit better would be a big win for everyone.

**Comment by AaronForinton** [comment]
This was resolved by #8113.
