### ISSUE TITLE
New title card on landing page has white text on white for part of the title.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#8096]
![image](https://user-images.githubusercontent.com/8204171/172165612-f24dab5c-5bcc-43e4-965e-3c20b5979541.png)

**Comment by jpmedley** [comment]
I can open the PR. Maybe something like this:
![image](https://user-images.githubusercontent.com/8204171/172431619-84500d14-9b5b-431b-ae82-69810a2ae873.png)

**Comment by rachelandrew** [comment]
@jpmedley Yeah I think it's because the text wraps up from the bottom so at a larger size, with that particular image it wraps onto white. I think shortening the text is a good move for now, and we probably need to be careful with the images we choose in future!
