### ISSUE TITLE
Background color on text has low contrast ratio on dark mode

### ISSUE THREAD

**Issue by charisTheo** [GoogleChrome/web.dev#8102]
Custom background color styles used [here](https://github.com/GoogleChrome/web.dev/blob/1a827e2026f92f1d6392fda2a72b9b1ddbb56744/src/site/content/en/blog/smoothness/index.md?plain=1#L375) make the text to have a low contrast ratio on dark mode.

![image](https://user-images.githubusercontent.com/9759549/172336748-b4d5eb40-0401-4b9c-af2e-e88f9c332a86.png)

**Comment by jeffposnick** [comment]
Thanks for pointing this out. CC: @malchata, who I believe owns these docs.
