### ISSUE TITLE
Example Stale While Revalidate needs a few fixes

### ISSUE THREAD

**Issue by brainfoolong** [GoogleChrome/web.dev#8110]
A buggy code example for https://web.dev/learn/pwa/serving/#stale-while-revalidate

The example provided have a few issues which result in a broken page which cannot respond correctly when the service worker is registered and results are uncached (new page, second visit).

Notice that this example is the complete service worker, no extra code added.

This code
```js
self.addEventListener("fetch", event => {
   event.respondWith(
     caches.match(event.request).then(cachedResponse => {
         const networkFetch = fetch(event.request).then(response => {
           // update the cache with a clone of the network response
           caches.open("pwa-assets").then(cache => {
               cache.put(event.request, response.clone());
           });
         });
         // prioritize cached response over network
         return cachedResponse || networkFetch;
     }
   )
  )
});
```

Should be replaced with

```js
self.addEventListener('fetch', event => {
  event.respondWith(
    caches.match(event.request).then(cachedResponse => {
        const networkFetch = fetch(event.request).then(response => {
          // update the cache with a clone of the network response
          const responseClone = response.clone()
          caches.open(url.searchParams.get('name')).then(cache => {
            cache.put(event.request, responseClone)
          })
          return response
        }).catch(function (reason) {
          console.error('ServiceWorker fetch failed: ', reason)
        })
        // prioritize cached response over network
        return cachedResponse || networkFetch
      }
    )
  )
})
```
First change is `return response` to fix following errors: `The FetchEvent for "<URL>" resulted in a network error response: an object that was not a Response was passed to respondWith().`

Second change is `const responseClone = response.clone()` to clone response before it is returned, otherwise you will get following errors: `Uncaught (in promise) TypeError: Failed to execute 'clone' on 'Response': Response body is already used`

**Comment by jeffposnick** [comment]
Those changes both seem correct to me.

CC: @tropicadri and @jpmedley, who both worked on bringing this content to web.dev.

**Comment by tropicadri** [comment]
Yes, those two changes make sense to me. thank you for flagging. I'll fix them as soon as I have a chance.

**Comment by tomayac** [comment]
@tropicadri Friendly ping.
