### ISSUE TITLE
Homepage lists same article in two different languages

### ISSUE THREAD

**Issue by sebastianbenz** [GoogleChrome/web.dev#8121]
Screenshot from https://web.dev/: 

<img width="1273" alt="Screen Shot 2022-06-10 at 20 20 20" src="https://user-images.githubusercontent.com/380472/173127125-7263668f-ac26-4220-88b9-59ddd645f644.png">

**Comment by rachelandrew** [comment]
@devnook looks like we should be filtering on `en-US` here, if I switch the homepage into different languages only the footer changes, everything else is English so we should just show English case studies.
