### ISSUE TITLE
Menu Links Still Clickable on Website When Search is Open

### ISSUE THREAD

**Issue by StillOnMyWay** [GoogleChrome/web.dev#8131]
**Describe the bug**

When the search bar is open, the main nav links are still right there in the bar and are still clickable if you are clickout out of the search box, removing focus. You end up on another page completely. Short screen recording of the bug happening on Chrome 102 below.

**Screenshots**
Screen Recording of Bug - https://app.claap.io/threed-software/search-bug-on-web-dev-c-HGm4RhKene-Tq448OJK57E3

**Comment by jeffposnick** [comment]
This might be an unintended consequence of https://github.com/GoogleChrome/web.dev/pull/8105
