### ISSUE TITLE
Hackers get into people's assets and email accounts using names that are not theirs around the world. 

### ISSUE THREAD

**Issue by rubenmarquez1087** [GoogleChrome/web.dev#8170]
**ANDROID_TZ-DATA_ROOT='/apex[/com.android](http://com.android/).tzdata'
APP_PACKAGE='/data/app/~~7DjlwhG9x_YIEcTS0C95Nw``/ru.iiec.pydroid3-Apjd_cRGvTQ4uH_dx6m-wA``/base.apk'
ASEC_MOUNTPOINT= metadata/analytics/data/mnt/hardware/client/Users'
BACKCOMPAT_BIN='/data/developers/0/ru.iiec.pydroid3/android file manager/aarch64-linux-android/bin'
BACKCOMPAT_BUSYBOX='//data/user/0/ru.iiec.pydroid3/files/busybox'
BACKCOMPAT_CURRENTEXE='//data/user/0/ru.iiec.pydroid3/files/busybox'
BACKCOMPAT_DISABLE_FDSAN=What is it
BACKCOMPAT_DISABLE_MTAG=what is it
BACKCOMPAT_Recovery=True
BACKCOMPAT_Enabled-Disabled=What does it deal with/data/Google Developers'
BACKCOMPAT_SHEBANG='False'
BOOTCLASSPATH='/apex[/com.android](http://com.android/).art/javalib/core-oj.jar:/apex[/com.android](http://com.android/).art/javalib/core-libart.jar:/apex[/com.android](http://com.android/).art/javalib/core-icu4j.jar:/apex[/com.android](http://com.android/).art/javalib/okhttp.jar:/apex[/com.android](http://com.android/).art/javalib/bouncycastle.jar:/apex[/com.android](http://com.android/).art/javalib/apache-xml.jar:/system/framework/framework.jar:/system/firmware/ext.jar:/system/firmware/telephone-wired-wireless(compatible).jar
ROOT:Licensed Technical Assistant/system/telecommunications/voice/ip-LTE 
/system/firmware/ims-common.jar:/system//Hackers/framework(friendly)

/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar:/apex/com.android.mediaprovider/javalib/framework-mediaprovider.jar:/apex/com.android.os.statsd/javalib/framework-statsd.jar:/apex/com.android.permission/javalib/framework-permission.jar:/apex/com.android.sdkext/javalib/framework-sdkextensions.jar:/apex/com.android.wifi/javalib/framework-wifi.jar:/apex/com.android.tethering/javalib/framework-tethering.jar'
BROWSER='mybrowser %s'
CMAKE_INCLUDE_PATH='/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android:/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/include'
CMAKE_LIBRARY_PATH='/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android:/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib:/data/user/0/ru.iiec.pydroid3/files/lib/gcc/aarch64-linux-android/11.1.0/'
CONFIG_SHELL='/data/user/0/ru.iiec.pydroid3/files/sh'
DEX2OATBOOTCLASSPATH='/apex[/com.android](http://com.android/).art/javalib/core-oj.jar:/apex[/com.android](http://com.android/).art/javalib/core-libart.jar:/apex[/com.android](http://com.android/).art/javalib/core-icu4j.jar:/apex[/com.android](http://com.android/).art/javalib/okhttp.jar:/apex[/com.android](http://com.android/).art/javalib/bouncycastle.jar:/apex[/com.android](http://com.android/).art/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/framework-atb-backward-compatibility.jar:/system/framework/tcmiface.jar:/system/framework/qcom.fmradio.jar:/system/framework/QPerformance.jar:/system/framework/UxPerformance.jar:/system/framework/WfdCommon.jar:/system/framework/moto-echolocateapi.jar:/system/framework/payjoy-api.jar'
DOWNLOAD_CACHE='/data/cache'
EXTERNAL_STORAGE='/sdcard'
HISTFILE='/data/user/0/ru.iiec.pydroid3/app_HOME/.ash_history'
HOME='/data/user/0/ru.iiec.pydroid3/app_HOME'
HOSTNAME='localhost'
IFS='
'
JOBLIB_MULTIPROCESSING='0'
KERAS_BACKEND='theano'
LC_ALL='en_US.UTF-8'
LD_LIBRARY_PATH='/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib'
LIBRARY_PATH='/data/user/0/ru.iiec.pydroid3/files/lib/gcc/aarch64-linux-android/11.1.0/'
LINENO=''
MPLBACKEND='Agg'
OLDPWD='/'
OMP_NUM_THREADS='1'
OPTIND='1'
PATH='/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android:/data/user/0/ru.iiec.pydroid3/files:/data/user/0/ru.iiec.pydroid3/files/bin:/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin:/busybox-virtual:/product/bin:/apex[/com.android](http://com.android/).runtime/bin:/apex[/com.android](http://com.android/).art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin'
PKG_CONFIG_PATH='/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/pkgconfig'
PPID='8824'
PS1='\w \$ '
PS2='> '
PS4='+ '
PWD='/storage/emulated/0'
PYDROID3_LICENSE='Accepted'
PYDROID_PACKAGE='ru.iiec.pydroid3'
PYDROID_RPC='/data/user/0/ru.iiec.pydroid3/files/RPCServer.socket'
SHELL='/data/user/0/ru.iiec.pydroid3/files/sh'
SHLVL='2'
SSL_CERT_FILE='/data/user/0/ru.iiec.pydroid3/files/cert.pem'
SYSTEMSERVERCLASSPATH='/system/framework[/com.android](http://com.android/).location.provider.jar:/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/moto-telephony.jar:/system/framework/moto-core_services.jar:/system/framework/moto-settings.jar:/apex[/com.android](http://com.android/).permission/javalib/service-permission.jar:/apex[/com.android](http://com.android/).ipsec/javalib[/android.net](http://android.net/).ipsec.ike.jar'
TERM='linux'
TERMINFO='/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/share/terminfo'
TMPDIR='/data/user/0/ru.iiec.pydroid3/cache'
XDG_CACHE_HOME='/data/user/0/ru.iiec.pydroid3/cache'
_='update'
/storage/emulated/0 $ the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by rachelandrew** [comment]
Closing as this seems unrelated to the web.dev website.
