### ISSUE TITLE
Learn Performance 01: Loading versus runtime performance

### ISSUE THREAD

**Issue by rachelandrew** [GoogleChrome/web.dev#8179]

**Comment by dstmarthe** [comment]
@rachelandrew May I list these 'Learn Performance' issues on one IssueTracker post?

**Comment by malchata** [comment]
Hey, @dstmarthe! I structured the content for this course, and I think the MVP we land will be different enough from what I envisioned in the origin content plan to warrant not porting these over to the new tracker.

**Comment by dstmarthe** [comment]
Hey @malchata, thanks for letting me know! I shall proceed with closing these then.
