### ISSUE TITLE
An article imported from HTML5Rocks has a mixed title and content

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#8205]
**Describe the bug**
Search results to https://www.html5rocks.com/tutorials/workers/basics/ redirected me to https://web.dev/workers-basics/ which the URL and the content seems fine, but the title is "Introducing WebSockets - Bringing Sockets to the Web" which contradicts the content. The title, authors are wrong, rest (the content) seems to be correct.

I also found the valid WebSocket article here: https://web.dev/websockets-basics/

Not sure what is the correct title and authors for https://web.dev/workers-basics/ so I'll leave it here.

**Comment by rachelandrew** [comment]
@agektmr probably a copy and paste error, I'll figure out what it was supposed to be and fix it. Thanks!

**Comment by AaronForinton** [comment]
Hi @rachelandrew - if you know the corrected title, I'm happy to take this one on.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298303557
