### ISSUE TITLE
Improve search results for metrics

### ISSUE THREAD

**Issue by malchata** [GoogleChrome/web.dev#8220]
**Describe the bug**
When searching for a metric (such as [INP](https://web.dev/inp/), the 

**To Reproduce**
1. Go to web.dev
2. Click on the search icon to open the search box
3. Type "INP" in the search box
4. Note that the INP page is the sixth result.

**Expected behavior**
INP (and any other metric page for its respective query) should be the first result.

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content/code on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
