### ISSUE TITLE
Broken links in webpage

### ISSUE THREAD

**Issue by vivamoto** [GoogleChrome/web.dev#8223]
**Describe the bug**
Several broken links in the blog post [Loading Third-Party JavaScript](https://web.dev/optimizing-content-efficiency-loading-third-party-javascript/)
Here I post just some examples, you can find more in the post.

**To Reproduce**
1. Go to [https://web.dev/optimizing-content-efficiency-loading-third-party-javascript/](https://web.dev/optimizing-content-efficiency-loading-third-party-javascript/)
2. Click on the links in these words:
[unoptimized image files](https://web.dev/web/tools/lighthouse/audits/unoptimized-images)
[too much JavaScript](https://web.dev/web/fundamentals/performance/optimizing-content-efficiency/javascript-startup-optimization/)
[unoptimized image files](https://web.dev/web/tools/lighthouse/audits/unoptimized-images)
[HTTP caching](https://web.dev/web/fundamentals/performance/optimizing-content-efficiency/http-caching),
[server compression](https://web.dev/web/fundamentals/performance/optimizing-content-efficiency/optimize-encoding-and-transfer)
[document.write()](https://web.dev/web/updates/2016/08/removing-document-write)
[harmful](https://web.dev/web/tools/lighthouse/audits/document-write)
[PageSpeed Insights](https://web.dev/speed/pagespeed/insights/)

3. See error
404
Sorry, we couldn't find that page.

**Expected behavior**
I should be able to follow the links.

**Screenshots**
No need for screenshots; just click the links and see the error.

**Comment by malchata** [comment]
@heyawhite, actually I think a lot of these have equivalent links to someplace, so the learn PWA course landing page is probably not optimal.

I'll have to take this one on and find the right pages to link to, but some of these are Lighthouse audit pages which have moved to d.c.c., and will get redirects set up by @brendankenny from web.dev to there.
