### ISSUE TITLE
Add an explanation on how to use Service Worker on cross-origin isolated environment

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#8226]
As per discussed at https://github.com/GoogleChrome/web.dev/pull/8206#discussion_r901607012
Explain how to use a service worker on a cross-origin isolated environment to https://web.dev/coop-coep

cc: @ArthurSonzogni

**Comment by dstmarthe** [comment]
We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298556734
