### ISSUE TITLE
Replace prefetch with preload in 'Responsive images'

### ISSUE THREAD

**Issue by RomFouq** [GoogleChrome/web.dev#8228]
**Describe the bug**
The guide [Responsive images](https://web.dev/learn/design/responsive-images/#loading-hints) advises to use [`prefetch`](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/prefetch) to prioritize downloading some images. However, `prefetch` is used to pre-download resources useful for the next navigation, not the current page.
[`preload`](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload) should be used instead, which does have the effect of prioritizing the image for the current page.

**Expected behavior**
The two occurences of `prefetch` and the occurence of `pre-fetch` should read `preload` in [Responsive images](https://web.dev/learn/design/responsive-images/#loading-hints).

**Comment by jeffposnick** [comment]
I believe the original author was @adactio, but I'm not sure who is responsible for maintenance/fixes for this content.

Assigning to @rachelandrew for triage.

**Comment by malchata** [comment]
My two: `prefetch` can be used to queue up downloading of resources used for the current navigation, it's just a lower priority fetch than preload.

**Comment by RomFouq** [comment]
Here the article discusses 'important images,' images that should be loaded as early as possible, e.g. hero images.
`prefetch` indicates to the browser that the resource can be useful a following navigation, but resources of the current page of course have higher priorities, since rendering the current page is more important than preparing for a future one.
So `prefetch`ing a resource used in the current page is not useful, as it would be loaded normally anyway (it should  be discovered by the preload scanner), before getting `prefetch`ed.

In the case of the article, `preloading` is clearly the value to use, as we want to load the image as early as possible, with high priority. It is also the strategy recommended in [Preloading responsive images](https://web.dev/preload-responsive-images/).
