### ISSUE TITLE
content: FLoC is still listed

### ISSUE THREAD

**Issue by myakura** [GoogleChrome/web.dev#8278]
### What page(s) need to be updated?

* https://web.dev/secure/#protect-users-from-tracking ([source](https://github.com/GoogleChrome/web.dev/blob/main/src/site/_data/paths/secure.json#L55))
* https://web.dev/floc/ ([source](https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/blog/floc/index.md))

### Why is this update needed?

Because Chrome is no longer pursuing (right?) FLoC, but it appears on those pages without mentioning it is superseded by the Topics API (like in #7237).

**Comment by heyawhite** [comment]
That is correct, we stopped development in 2021. I'll update the blog post and remove it from the secure page. It will still appear in the blog.

**Comment by heyawhite** [comment]
This document has been updated.

**Comment by Mzul86** [comment]
Approve me web

**Comment by Mzul86** [comment]
Please support me
