### ISSUE TITLE
content: Streaming requests with the fetch API seemly not work 

### ISSUE THREAD

**Issue by songhn233** [GoogleChrome/web.dev#8288]
### What page(s) need to be updated?

[fetch-upload-streaming](https://web.dev/fetch-upload-streaming)

### Why is this update needed?

The article describes that Request can use Stream as a body in Chrome 95, but I opened the demo in subsequent versions  and was told that the current browser does not support this feature

Also, [caniuse](https://caniuse.com/mdn-api_request_request_readablestream_request_body) says that any version does not support this feature. However, I don't see the article revealing that this feature requires a specific flag to be enabled.

**Comment by tomayac** [comment]
They just requested a TAG review: https://github.com/w3ctag/design-reviews/issues/754.

**Comment by tomayac** [comment]
It’s unclear to me what the supposed current implementation status should be. [Comment 76](https://bugs.chromium.org/p/chromium/issues/detail?id=688906#c76) says support was removed for HTTP/1.1. @jakearchibald, do you have more background?

**Comment by jakearchibald** [comment]
I'll figure out what's going on with this

**Comment by nwtgck** [comment]
@songhn233 Hi!

I use this feature a lot. I enable "Experimental Web Platform features" in `chrome://flags/`. I hope this would be helpful for you.
<img width="779" alt="image" src="https://user-images.githubusercontent.com/10933561/178470366-8a6da648-6096-42a0-9e48-2cae19e8b451.png">

**Comment by jakearchibald** [comment]
PR up https://github.com/GoogleChrome/web.dev/pull/8317
