### ISSUE TITLE
Spotty connection

### ISSUE THREAD

**Issue by fedolive** [GoogleChrome/web.dev#8307]
**Describe the bug**
I'm not able to navigate to any site. Every time I log in to open my email there's an error. 
"interstitial wrapper"? not sure how to go about that.

**To Reproduce**
1. Go to 'any site'
2. Click on 'enter'
3. See an error
(one of the many, sometimes it works, sometimes it doesn't)
[chrome_issues.log](https://github.com/GoogleChrome/web.dev/files/9079532/chrome_issues.log)

**Expected behavior**
To open my email or any site at any point and time.

**Screenshots**
N/A

**Comment by rachelandrew** [comment]
@fedolive this site is for issues with the site at web.dev, not Gmail or the Chrome browser.
