### ISSUE TITLE
Topic pitch: optimizing video delivery on the web

### ISSUE THREAD

**Issue by dougsillars** [GoogleChrome/web.dev#831]
As video becomes more prevalent on the web, I think it is time to begin best practices guides for video.

We could discuss:
best implementation of attributes:  preload, autoplay, etc.
encoding for video
video sizing (dimensions and MB)
optimising background videos

Mp4 vs. streaming
streaming
how to choose and implement a player
picking streams to encode
Optimization for fast startup (and why fast startup is important)
How to reduce stalls

This can be one epic large post, or a series of shorter (or both)

**Comment by robdodson** [comment]
Hey Doug, thanks for the suggestion. I agree, loading video is an important and big topic to cover :)

We're currently working on a new blog that'll be rolling out soon. We haven't completely sorted out our publishing model yet, but I think posts on how to do video effectively could be cool.

cc @samdutton who is one of our video experts.

**Comment by samdutton** [comment]
A series about video performance could be really useful. 

I did some content about this ages ago:
• [High Performance Video for the Web](https://www.youtube.com/watch?v=Fm3Bagcf9Oo)  
• [developers.google.com/web/fundamentals/media/video](https://developers.google.com/web/fundamentals/media/video)

The content would, of course, also need to cover adaptive streaming.

@beaufortfrancois fyi

**Comment by dougsillars** [comment]
That was my thought, adaptive video and how to deliver video performantly..

**Comment by addyosmani** [comment]
@robdodson where is the best home for this content? A new video section? /fast? Elsewhere?

**Comment by robdodson** [comment]
I think I'd prefer a media section that focuses on video and audio. This is
mostly to keep /fast from ballooning.

**Comment by dougsillars** [comment]
Rob - How can I start building this for the site?  Is there a style guide, etc?

**Comment by robdodson** [comment]
Let me check with some folks. We should have a style guide ready next week but we haven't quite worked out our external contribution model yet. I'll report back when I know a bit more.

**Comment by robdodson** [comment]
hey @dougsillars can you shoot me a DM on twitter with your contact info?

**Comment by robdodson** [comment]
This is up at https://web.dev/video-basics/
