### ISSUE TITLE
Pagespeed Insights - URL Diff shown on redirect very confusing

### ISSUE THREAD

**Issue by dwsmart** [GoogleChrome/web.dev#8325]
**Describe the bug**
If you test a URL that redirects in pagespeed insights, you get a "Showing results for URL: " that's not user friendly, due to it showing a diff style output

**To Reproduce**
1. Go to [https://pagespeed.web.dev/report?url=https%3A%2F%2Ftamethebots.com%2Fheadless%2F](https://pagespeed.web.dev/report?url=https%3A%2F%2Ftamethebots.com%2Fheadless%2F)
2. See the output of the "Showing results for URL" section. There's no explanation that the blue is added characters, red is removed characters, so it looks like it redirected to: https://tamethebots.com/tools/fetch-reandless/r not https://tamethebots.com/tools/fetch-render

**Expected behavior**
Give the URL you tested is in the URL bar just above, it would be much clearer to just output the final URL here, like it used to. 
At the very least, explain the diff output though.
**Screenshots**
![image](https://user-images.githubusercontent.com/11179452/178748358-8cf62954-dac4-47c5-96b3-b6dd8ff6b9ec.png)

**Comment by rachelandrew** [comment]
@dwsmart closing this as the tool is no longer part of web.dev, as the measure tool has moved to Pagespeed Insights, see https://web.dev/measure/

If this is still a issue over there, perhaps raise an issue with that team.
