### ISSUE TITLE
Browser Compatibility component shows incorrect data

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#8333]
**Describe the bug**

the browser compat macro in [Building a button component](https://web.dev/building-a-button-component/) seems to show that `<button>` elements are only available in Edge. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#browser_compatibility), the source this macro pulls from, they have been available to all browsers for a very long time.

![image](https://user-images.githubusercontent.com/8204171/179083107-eaf16855-f32a-4d19-89ce-204e4a01fca3.png)

**To Reproduce**
Follow the links above to compare data that should be identical.

**Expected behavior**
The component on web.dev should show the data that's on MDN.

**Comment by jeffposnick** [comment]
The `support` fields for `button` look like:

```json
"support": {
  "chrome": {
    "version_added": true
  },
  "chrome_android": {
    "version_added": true
  },
  "edge": {
    "version_added": "12"
  },
  "firefox": {
    "version_added": true
  },
}
```

I think we can get away with treating `true` as if it were version 1.

**Comment by jeffposnick** [comment]
I could use a ✅ if you think that would properly capture the meaning.

**Comment by argyleink** [comment]
ty jeff!
