### ISSUE TITLE
Confusion about where layering actually happens

### ISSUE THREAD

**Issue by ajain-bst** [GoogleChrome/web.dev#8338]
The article [web.dev/animations-overview](https://web.dev/animations-overview/)
confused me about which step of the rendering pipeline the creation of layers actually happen on.

From the Rendering Pipeline section:
"Paint: Fill out the pixels for each element into layers.
Composite: Draw the layers to the screen."

Okay, so this makes me think that layering must be happening on the paint step, and that composition involves just drawing the layers to screen.

But then, in the Animating Composite Properties section:
"Compositing is the process of separating the page into layers,..."

So, i got confused about where actually the separation into layers happen.

I did find the answer through the Inside look at modern browser browser series (its composite!), but i think it could be reworded here.

**Comment by dstmarthe** [comment]
hanks for raising this. We’re moving to a new platform and issue tracker so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/u/1/issues/298556754
