### ISSUE TITLE
php code block not escaped properly on https://web.dev/eventsource-basics/

### ISSUE THREAD

**Issue by MaxCSwann** [GoogleChrome/web.dev#8346]
**Describe the bug**
A php code block is not escaped on the article https://web.dev/eventsource-basics/#server-examples. This looks correct in the source markdown file however https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/blog/eventsource-basics/index.md#server-examples

**To Reproduce**
1. Go to 'https://web.dev/eventsource-basics/#server-examples'
4. See that there should be an end of code block after "sendMsg($serverTime, 'server time: ' . date("h:i:s", time()));" and before "Here's a similiar implementation using [Node JS](http://nodejs.org/):"

**Expected behavior**
The codeblock component should end. This is potentially just an issue with the php formatted code block. The markdown looks correct and other js formatted codeblocks are closing as they should

**Screenshots**
<img width="642" alt="code-block-display-error" src="https://user-images.githubusercontent.com/23646039/179404337-52103eb1-954c-45a9-8b21-c5ed30976100.png">

**Comment by heyawhite** [comment]
My guess is that the php needs to be closed out with `?>`. I'll add a fix.
