### ISSUE TITLE
content: mention "any maskable" value for `purpose` field in Maskable icons section of 012 Web app manifest 

### ISSUE THREAD

**Issue by rdela** [GoogleChrome/web.dev#8356]
### What page(s) need to be updated?

[012 Web app manifest > Maskable icons](https://web.dev/learn/pwa/web-app-manifest/#maskable-icons)

### Why is this update needed?

Despite this mention in [Add a web app manifest](https://web.dev/add-manifest/), in the [icons](https://web.dev/add-manifest/#icons) section (which is linked from Resources at the bottom):

> To use [maskable icons](https://web.dev/maskable-icon/), sometimes referred to as adaptive icons on Android, you'll also need to add `"purpose": "any maskable"` to the icon property.

…and the detailed explanation of `purpose` in [MDN > References > Web app manifests > icons > Values](https://developer.mozilla.org/en-US/docs/Web/Manifest/icons#values) (helpfully linked in the [Further reading](https://web.dev/add-manifest/#further-reading) section of Add a web app manifest):

> [`purpose`](https://w3c.github.io/manifest/#purpose-member) can have one or more of the following values, separated by spaces:
> […]
> - `maskable`: The image is designed with [icon masks and safe zone](https://w3c.github.io/manifest/#icon-masks) in mind, such that any part of the image outside the safe zone can safely be ignored and masked away by the user agent.
> - `any`: The user agent is free to display the icon in any context (this is the default value).

…the [Maskable icons](https://web.dev/learn/pwa/web-app-manifest/#maskable-icons) section of the 012 Web app manifest page does not mention the option of adding both `any` and `maskable`, which would seem to be a far more common use case than the separate maskable 512px icon in the code example. At least a sentence mentioning `"any maskable"` being the better value for an icon that serves both general and maskable purposes would seem to reduce developer confusion and eliminate probable incorrect usage of `purpose`, or possible unnecessary duplication of icons to satisfy the requirements as currently explained in 012 Web app manifest > Maskable icons.

### What's the deadline?

None, but happy to open a PR with this suggested language at the end of the Maskable icons section, immediately before the [Icons in Safari](https://web.dev/learn/pwa/web-app-manifest/#icons-in-safari) section, open to improvement:

If your icon serves general and maskable purposes, you can set `purpose` to  `"any maskable"`; `purpose` accepts one or more of `monochrome`, `maskable`, or `any`, separated by spaces. Refer to the [MDN Web App Manifest documentation](https://developer.mozilla.org/docs/Web/Manifest) for details.

#### Is it a hard deadline?

No

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform, and since all content on this site is frozen, we'll deal with this over there.. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298526955
