### ISSUE TITLE
Learn Forms: aria-hidden="true" should not be paired with the hidden attribute

### ISSUE THREAD

**Issue by greatgraphicdesign** [GoogleChrome/web.dev#8383]
[This page](https://web.dev/learn/forms/security-privacy/) suggests invalid HTML. It shows an example with aria-hidden="true" and the hidden attribute on the same input tag. According to the kind devs at [StackOverflow](https://stackoverflow.com/questions/31107040/whats-the-difference-between-html-hidden-and-aria-hidden-attributes), the aria attribute is not needed because hidden renders it invisible to screen readers.

**Comment by AaronForinton** [comment]
Thanks for this suggestion @greatgraphicdesign - I've confirmed you're correct and I've added a PR to remove this from the Learn page. It has already been removed from the codelab it shows up in.
