### ISSUE TITLE
Consider an alternative way of providing metadata for Twitter Spaces

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/web.dev#8387]
The code in https://github.com/GoogleChrome/web.dev/pull/8323 introduced `/spaces/`, with metadata for each event provided in a Markdown file under https://github.com/GoogleChrome/web.dev/tree/main/src/site/content/en/spaces

This works, but it also means that each of those Markdown files ends up generating an empty HTML file under `dist/en/spaces/.../` during the 11ty build. It seems like those empty HTML files are just side-effects, which makes me think there might be a better way of providing the metadata that's in each event's Markdown frontmatter.

Perhaps a dedicated JSON/YAML file could do the same thing, with an array for all the events?

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
