### ISSUE TITLE
Headings on the Ten Modern Layouts article look broken

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#8393]
👋

On this page https://web.dev/one-line-layouts/ the headings appear broken.
![image](https://user-images.githubusercontent.com/1066253/180495302-62917180-dd6c-4d97-9949-ae7699ded3e2.png)

**Comment by rakshitgondwal** [comment]
Hey! @robdodson 
I would like to take upon this issue. Can you please give me a little more brief about the issue?
