### ISSUE TITLE
Migrate the Extending Workbox article to d.c.c.

### ISSUE THREAD

**Issue by rachelandrew** [GoogleChrome/web.dev#8404]
https://web.dev/extending-workbox/

Seems like it should live alongside the other Workbox stuff.

**Comment by malchata** [comment]
Hey, @jeffposnick, do you think maybe this post should be deleted and redirected to https://developer.chrome.com/docs/workbox/using-plugins/ or do you think this needs to be preserved somehow?

**Comment by jeffposnick** [comment]
I'm fine with redirecting it to https://developer.chrome.com/docs/workbox/using-plugins/, since the same video is available embedded on the top of that page.
