### ISSUE TITLE
Installation prompt article has a demo page with an error in json, rendering it broken

### ISSUE THREAD

**Issue by azivkovi** [GoogleChrome/web.dev#8418]
On https://web.dev/learn/pwa/installation-prompt/ there is a link to https://mlearn-pwa-web-app-manifest-promotional.glitch.me/ where a demo of PWA prompt should appear. It doesn't because of an error in manifest.json. From console:

`Error: Parse error on line 34:
...s": "512x512",     }   ],   }
----------------------^
Expecting 'STRING', got '}'`

Problem appears to be a trailing comma.

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
