### ISSUE TITLE
Eyedropper article translation [zh]

### ISSUE THREAD

**Issue by Minya2020** [GoogleChrome/web.dev#8436]
[zh] translate eyedropper anricle
related blog post address:  src/site/content/en/blog/eyedropper
draft:https://docs.google.com/document/d/1SRmHIWtfA7khOOHWHG4nNGuuwxnG-YjVpuInfFFueX8/edit?usp=sharing

is this way right?What more do I need to do?

#### What kind of content are you creating?
Blog Post

**Comment by dstmarthe** [comment]
Thanks for raising this, but this article doesn't exist on Web.Dev. I see it on the developer.chrome site - but not in the web.dev src you mentioned. Additionally we are moving to a new platform, so creating articles will have a different process. Our new issue tracker resides at: https://issuetracker.google.com/issues?q=status:open%20componentid:1400680&s=created_time:desc
