### ISSUE TITLE
Broken content

### ISSUE THREAD

**Issue by Jxck** [GoogleChrome/web.dev#8438]
**Describe the bug**

in https://web.dev/new-patterns-july-2022/
article broken after Theming section.
Seems failed to build.

**To Reproduce**
1. Go to https://web.dev/new-patterns-july-2022/
2. Scroll down to bottom
3. content ends suddenly.

**Expected behavior**
Content should be visible.

**Comment by rachelandrew** [comment]
Thanks for raising this @Jxck it's now fixed.
