### ISSUE TITLE
New layout patterns from GUI Challenges not allowing inline event handlers in prod

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/web.dev#8453]
The add element button called a function inline `onclick` and the console is trying to alert me that's not ok per some guidelines. Task is to update the demo's to not use inline event handlers, so the demo functionality can work in localhost and production.

**To Reproduce**
1. Go to [https://web.dev/patterns/layout/](https://web.dev/patterns/layout/)
2. Expand "Autobot"
3. Click the "Add element" button
4. See error in console

**Expected behavior**
An element to be added to the demo layout

**Screenshots**
![Screenshot 2022-08-02 10 41 15 AM](https://user-images.githubusercontent.com/1134620/182439423-ba5a8c32-9d2a-4a4c-a28f-00931186c989.png)

**Comment by enu71** [comment]
thinks for letting me know .

**Comment by argyleink** [comment]
also Theme Switch

**Comment by argyleink** [comment]
fixed
