### ISSUE TITLE
Anusmita's author profile 

### ISSUE THREAD

**Issue by heyawhite** [GoogleChrome/web.dev#8473]
Anusmita needs to [create a new author's profile](https://web.dev/handbook/author-profile/).

### Note for content sherrif

This was created to walk through our GitHub processes. Please do not re-assign this issue.

**Comment by dstmarthe** [comment]
Hi, I'm involved with migrating this site to a new non-Github-based platform. There will definitely be new processes for creating author profiles and articles - which will be outlined at a later date. As I'm clearing these issues out, I gotta close this.
