### ISSUE TITLE
Needs keyboard-only user consideration

### ISSUE THREAD

**Issue by aardrian** [GoogleChrome/web.dev#8477]
**Describe the bug**
The post _[Overflow](https://web.dev/learn/css/overflow/)_ in the _[Learn CSS](https://web.dev/learn/css/)_ evergreen course goes into detail about overflowing areas that scroll. It does not, however, note that scrolling containers are a problem for keyboard-only users.

While Chromium is working to add a feature to make scrolling areas keyboard-accessible ([Issue 907284: WebUI regressions caused by Keyboard-accessible scroll containers](https://bugs.chromium.org/p/chromium/issues/detail?id=907284)), so far only Firefox has the feature built in.

**To Reproduce**
1. Go to https://web.dev/learn/css/overflow/
2. Go to any embedded example that is a scrolling box.
3. Attempt to scroll by navigating the example with only a keyboard.

**Expected behavior**
Scrolling boxes need a way to accept keyboard focus so a keyboard user can use the arrow keys to scroll.

Give them `tabindex="0"`. Note that once you do this, to conform to WCAG they will also need an accessible name and appropriate role.

While this makes for a verbose page for screen reader users, this is the only/best choice for supporting keyboard-only users (caret browsing does not suffice: _[Keyboard-Only Scrolling Areas](https://adrianroselli.com/2022/06/keyboard-only-scrolling-areas.html)_).

I have other posts that discuss scenarios in more detail:

- [Keyboard and Overflow](https://adrianroselli.com/2016/02/keyboard-and-overflow.html), 2016
- [Under-Engineered Responsive Tables](https://adrianroselli.com/2020/11/under-engineered-responsive-tables.html), 2020
- [Using CSS to Enforce Accessibility](https://adrianroselli.com/2021/06/using-css-to-enforce-accessibility.html), 2021

**Potential Fix**
For any container that scrolls, consider the following HTML:
```HTML
<div tabindex="0" role="[region|group]" aria-labelledby="[appropriate existing text]">
    content
</div>
```

And the following CSS to enforce the keyboard-friendly structure while also giving a visual cue on focus:
```CSS
[role][aria-labelledby][tabindex] {
  overflow: auto;
}
[role][aria-labelledby][tabindex]:focus {
  outline: .1em solid ActiveText;
}
```

Obviously the selector can change based on the `role` and/or accName chosen (`aria-labelledby` or `aria-label`). The color I chose for the outline is a system color, so that can (should) be changed too.

**Comment by rachelandrew** [comment]
@aardrian thank you for raising this, I have a PR adding a section on the issue https://github.com/GoogleChrome/web.dev/pull/8505.

Preview: https://deploy-preview-8505--web-dev-staging.netlify.app/learn/css/overflow/#scrolling-and-accessibility

I need to go through and update the CodePens so they also allow for focus. I did the chat example below this section so I could test the behaviour but I need to do the others.

**Comment by aardrian** [comment]
@rachelandrew This looks lovely, thank you!

I made one edit suggestion, though I am sure you would have seen it on another read-through.

**Comment by rachelandrew** [comment]
hah yes - I think I got halfway through rearranging that sentence and the heat got to me or something :D
