### ISSUE TITLE
Unable to view the animation patterns - CSP

### ISSUE THREAD

**Issue by maneeswarmutyala** [GoogleChrome/web.dev#8482]
**Describe the bug**
Unable to view and play with the animation patterns due to csp.

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'strict-dynamic' 'sha256-lvhFs7LPDhBBXHWotjdTp292ztQcrw/OC0t60QgrPWI=' 'sha256-bn2OuMCn5/yM+fMtaRzdEyKfsiRiL1rT36jkshEuVTo=' 'sha256-48A4Dz3O2+FQ2x9QUpa3oClLJqL6veT2RhDX6W6IVXk=' 'sha256-IgMAsv+gzUabvEezSxPP/1yKIYDY16pdv3cp6EIirLU=' 'sha256-QHAyyy6fCJ8Rz89oba+QvsksgitqK3b1tHEUajPAyCM=' 'sha256-Kypz4tCeSu9TDLbPqpbLuVU+13/zyB0UDBLGtyPGR1I=' 'sha256-iR+zIq3+42MzYNhV/+cXP1NlBRyjqhG+O6r/6GLk8ng=' 'sha256-xDejsr8X0SHC6JzsXBtH1GkkpndGomtvTSb6sOFsuJI=' 'sha256-mbqpTaiezCVtSf0xRXMq8E90CemIkT6YthtoQvi0Vf4=' 'sha256-fM/gQ+eAA1sJw/5jpDiOW4ZQWJ0KhODvbN9gwYUIwLM=' 'sha256-QHGQPs40Wp++gRbi0zE4yO17tjjcn7jrn1OIOTU7Ib8=' 'sha256-d3yp6pbEtRk/FXwgNZkTy3+nk2DmQvSubpg7x3TasvY=' 'sha256-9FBkyWL+iGrJoGQ60dJZcgLSx70JpTxd6lJXlBMLgFI=' 'sha256-DtI0jacx1NRhLWJTJwcEneNEAJ3Qk57SY4OoSdD4yZY=' 'sha256-hNBIh0HbVUqkThnSgb5KAKdjwkWmBLnucTrmhuFnnfA=' 'sha256-YJxmIlZWu8tceA5HT3rJUwFUoo1tqGaYSxqQO++ax9I=' 'sha256-FL1Ihd/HvyQJR2MMYiU7K1O92f9jeLVcw9yipF8BCvs=' 'sha256-tMTtCX24g6Q8pO969onot0YAN00zgHjDyOVaLx4EpPM=' 'sha256-wz1/y6pG3TDQC4sgnxyJi6gRi4oCjeqURon072PuBXU=' 'sha256-6myrIj76pNNiqz9/iL0O8H0sGsQ9YrJZ7FlHGWkE46U=' 'sha256-UU3kz21DzwpW13UMrM5gkb2o0O+GRvZLhrOSFTa5zZE=' 'sha256-EQmo6dq1Rrz5uU9fQmxNItGHBJrfTO33roesKg6OZ3A=' 'sha256-S2tP2PqGt4zJwaoGoHAUMlVehSYMH+JXiSCsjHVUxSw=' 'unsafe-inline' http: https:". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

**To Reproduce**
1. Go to https://web.dev/patterns/animation/
2. Open any demo and move cursor on it(hover). Animation is not working as expected.
3. Open dev tools. 
4. See error in console

**Expected behavior**
Animations should work properly

**Comment by devnook** [comment]
Fixed in #8480
