### ISSUE TITLE
Make the blog more visible

### ISSUE THREAD

**Issue by bramus** [GoogleChrome/web.dev#8484]
The only way to access the blog when visiting web.dev is through the top navigation menu. The contents of the homepage do not expose the blog in any other way. On mobile this top navigation menu is collapsed, making access to the blog a somewhat hidden feature. A section on the homepage that exposes the blog more prominently  –cfr. what DCC does– would be a nice addition to solve this, and possibly direct more users to it.

Furthermore, the section on https://web.dev/about/ that describes the project only lists how-tos (/learn) and case-studies. Adding blog there would make a nice addition as well.

**Comment by rachelandrew** [comment]
Yeah the homepage needs some work, it's on the list.

**Comment by vonDubenshire** [comment]
It has been almost two months and I noticed no change.

If you scroll down the page it would be easy to add a section that says BLOG with three recent posts. 

![Screenshot_20220925-211619](https://user-images.githubusercontent.com/40748193/192180979-5ac11429-d3bb-4893-ac65-c39942f6a299.png)

**Comment by matthiasrohmer** [comment]
The updated homepage now surfaces a bunch of posts across the various themes of the site. @bramus, feel free to create another issue if that doesn't satisfy your need yet.
