### ISSUE TITLE
Consider rephrasing "Gmail HTML" or adding an explanation as to what it means

### ISSUE THREAD

**Issue by umaar** [GoogleChrome/web.dev#8496]
The [Rendering on the Web](https://web.dev/rendering-on-the-web/) article shows this image:

![image](https://user-images.githubusercontent.com/381495/183934413-1a4ae33b-fad8-429e-aec6-a290f640e143.png)

Looking at the bottom left, I was convinced Gmail is not a server app, yet it was in the server column. Took me a while to realise "Gmail HTML" is referring to the [Basic HTML View](https://support.google.com/mail/answer/15049?hl=en) (I disabled JS on Gmail, and then was prompted to use the HTML view).

I wonder if it's worth updating the image, or adding a caption, to mention that point. I feel like some people won't know what "Gmail HTML" is and it could be a tad confusing as "regular" Gmail looks and feels like a JavaScript powered app.

**Comment by dstmarthe** [comment]
Thanks for raising this issue. We’re moving to a new platform. This seems like a thoughtful update so I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298303552
