### ISSUE TITLE
I think <dialog> can be used for Modal instead <div> in Web-vitals patterns examples

### ISSUE THREAD

**Issue by jitendravyas** [GoogleChrome/web.dev#8504]
I think `<dialog>` can be used for Modal instead `<div>`
https://web.dev/patterns/web-vitals-patterns/notices-pattern-set/notice-modal/

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298216474
