### ISSUE TITLE
Broken images on "Capturing an Image from the User"

### ISSUE THREAD

**Issue by westonruter** [GoogleChrome/web.dev#8506]
**Describe the bug**

At https://web.dev/media-capturing-images/ there are there are two broken images. Source:

```html
<img src=images/ios-chooser.png width=250>
<img src=images/android-chooser.png width=250>
```

These are returning 404

**To Reproduce**
1. Go to page
2. See broken images

**Expected behavior**

No broken images.

**Screenshots**

> <img width="785" alt="image" src="https://user-images.githubusercontent.com/134745/184244993-643fd843-f97b-46fc-bd1f-04aefb0af9db.png">

**Comment by AaronForinton** [comment]
Hello @westonruter - I just wanted to let you know I'm officially on the hunt for these missing images. I'll keep you in the loop! Do you have any idea where they are, just to start me off on my search?

**Comment by westonruter** [comment]
@AaronForinton It seems the content is old and was migrated from developers.google.com in https://github.com/GoogleChrome/web.dev/pull/7624

The original URL was https://developers.google.com/web/fundamentals/media/capturing-images

The original images appear to have been captured by the Wayback Machine: https://web.archive.org/web/20220318083726/https://developers.google.com/web/fundamentals/media/capturing-images

![iOS Chooser](https://web.archive.org/web/20220321201428im_/https://developers.google.com/web/fundamentals/media/capturing-images/images/ios-chooser.png)

![Android Chooser](https://web.archive.org/web/20220318083726im_/https://developers.google.com/web/fundamentals/media/capturing-images/images/android-chooser.png)
