### ISSUE TITLE
Make iframe CWV eligibility clearer

### ISSUE THREAD

**Issue by tunetheweb** [GoogleChrome/web.dev#8547]
### What page(s) need to be updated?

Provide a list of URLs.
- https://web.dev/vitals/
- https://web.dev/lcp/
- https://web.dev/cls/
- https://web.dev/fid/
- https://web.dev/inp/

### Why is this update needed?

After reading my [CrUX RUM Doc](https://web.dev/crux-and-rum-differences/) Someone raised to me that [they didn't realise](https://webperformance.slack.com/archives/C04BK7K1X/p1660663925699789?thread_ts=1660572444.598339&cid=C04BK7K1X) that content within an iframe would affect the top-level page CWV, rather than the iframe CWV. They "got it" when it was explained to them (and someone else said: "CrUX is trying to capture the experience for end users. End users have no idea if a piece of content in a tab comes from the main frame or an iframe. That's why the metrics are counted against the main frame.")

I had a hunt around our docs and we never made this clear.

We have pieces [like this](https://web.dev/lcp/#differences-between-the-metric-and-the-api):

> The API does not consider elements within iframes, but to properly measure LCP you should consider them. Sub-frames can use the API to report their `largest-contentful-paint` entries to the parent frame for aggregation.

Which kind of implies this, but never explicitly says it.

And we've often said ads, and third-party content can contribute to LCP and CLS issues, but people could have thought this was due to the whole iframe loading late, rather than content within it.

Do you think we should add something to the main web vitals page (https://web.dev/vitals/) to make this clear? And/or each metric' "What elements are considered?" section to make this clear?

### What's the deadline?

No deadline

#### Is it a hard deadline?

Nope

**Comment by rviscomi** [comment]
> Do you think we should add something to the main web vitals page (https://web.dev/vitals/) to make this clear?

Maybe not going into technical detail in the overview page itself, but we could add something to the [JS](https://web.dev/vitals/#measure-core-web-vitals-in-javascript) section to the effect of "Note that the CWV measured in JS using public APIs may differ from the CWV reported by CrUX. Read [this article](https://web.dev/crux-and-rum-differences/) for more info."

> And/or each metric' "What elements are considered?" section to make this clear?

Yeah I think it'd be good to add these special cases to each metric's docs where applicable.

**Comment by malchata** [comment]
I think clarifying this would be a good step, and I'd be happy to do so for the INP doc, where appropriate. However, that doc is going to get some additional restructuring after I get back from Canada this week from talking with the speed metrics team.
