### ISSUE TITLE
Improvement in the steps for Building the site in README.md

### ISSUE THREAD

**Issue by yashikabhargava** [GoogleChrome/web.dev#8552]
### What would you like to share?

The steps for building the project are unclear from a beginner's perspective, and information about forking the project and adding upstream is missing.

### ScreenShot
![chrome](https://user-images.githubusercontent.com/76060661/185225959-3202064b-e559-4a41-be90-8c07f0ced24a.PNG)

### Would you like to work on this issue?

- [x] Yes, I want to work on this issue!

**Comment by matthiasrohmer** [comment]
Can you elaborate on the details you are missing and the goal you were trying to achieve? Then we are happy to add answers to this to the README or link to the relevant sections in our project wiki which covers some topics in more detail, like [building](https://github.com/GoogleChrome/web.dev/wiki/Builds).

**Comment by yashikabhargava** [comment]
![chrome](https://user-images.githubusercontent.com/76060661/185377614-abf044fe-b2b1-45aa-a55b-5db9e36eba64.PNG)

### Detail missing 

In the above screenshot of README.md, we can see it provides information about how to clone the project but before that one more step i.e. the step to fork the project & after cloning the step of how to add upstream is missing.

### goal

To make it easier for beginners to set up the project locally and contribute.

**Comment by badges7** [comment]
None

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298296170
