### ISSUE TITLE
Language automatic detection

### ISSUE THREAD

**Issue by zprjk** [GoogleChrome/web.dev#8559]
**Is your feature request related to a problem? Please describe.**
Browsing web.dev falls back to my native language despite I've set my Browser to English. (One annoying thing is even if I swtich to English in the website it resets after sometime. I browser web.dev not so often)

**Describe the solution you'd like**
Detect Language via Browser configuration instead of Region location.

**Comment by developer-diganta** [comment]
Is anyone working on this issue? If not, can I give it a try?

**Comment by Arsinam80m** [comment]
arsinam80m

**Comment by Arsinam80m** [comment]
arsinam80@gmail.com

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content/code on this site is now frozen. As this is about the site, it won't be relevant with the new platform.
