### ISSUE TITLE
HTML code block not rendered properly in aside on `prefers-reduced-motion` article

### ISSUE THREAD

**Issue by hughlilly** [GoogleChrome/web.dev#8569]
The HTML aside in the ["`prefers-reduced-motion`" article](https://web.dev/prefers-reduced-motion) is not being rendered properly. In fact, the `html` language tag that is supposed to be interpreted by Eleventy (?) shows up as part of the code block. Screenshot below.

This comes from:
https://github.com/GoogleChrome/web.dev/blob/b7d5046cfe0730f3ba92238d904b9d41e0a5dbf1/src/site/content/en/blog/prefers-reduced-motion/index.md?plain=1#L155-L158 

**Expected behavior**
The code should be rendered as an HTML code block.

**Screenshots**
<img width="789" alt="Screen Shot 2022-08-21 at 12 59 24 PM" src="https://user-images.githubusercontent.com/12046008/185771033-f21b44ae-d883-41cd-8625-72e4b0c4af7e.png">

I’m using Safari 15.6 (17613.3.9.1.5) on macOS 12.5, but see the same problem in Chrome 104.0.5112.101 (Official Build) (x86_64) and Firefox 103.0.2 (64-bit).

**Comment by matthiasrohmer** [comment]
Thanks for the report! Markdown in ` {% aside %}` blocks is parsed differently than in the rest of the document. It uses markdown-it's `renderInline` method which does not support code block syntax, but only markdown inline elements.

I'll update the articles to make the code snippet inline.
