### ISSUE TITLE
Headers have the same id

### ISSUE THREAD

**Issue by Yohn** [GoogleChrome/web.dev#8574]
Hello,
I was wanting to share a link [Choose the Right Image Format](https://web.dev/choose-the-right-image-format/#choose-the-right-image-format) with a new colleague and when I clicked the link it brought me to the top of the page instead of the 1st sub header within the article.

**To Reproduce**
1. Go to [Choose the Right Image Format](https://web.dev/choose-the-right-image-format/#choose-the-right-image-format)
2. Scroll down to the header text right above the picture, and click the hashtag tag that appears to link to that section.

**Expected behavior**
Expected the page to display right at that header, but it went to the top of the page. The article and this header have the same text, which made them have the same ID on the elements.

**Screenshots**
![web dev-header-id](https://user-images.githubusercontent.com/2002591/186197641-d007d8ba-0b80-401f-a345-8ab710dc6202.jpg)

https://github.com/GoogleChrome/web.dev/blob/1c7e48e7e9ea20e8e41f4123b6e34473a8480333/src/site/content/en/fast/choose-the-right-image-format/index.md?plain=1#L3

https://github.com/GoogleChrome/web.dev/blob/1c7e48e7e9ea20e8e41f4123b6e34473a8480333/src/site/content/en/fast/choose-the-right-image-format/index.md?plain=1#L43
-------
I wasn't sure what it should be changed to, but figured I would let ya'll know.

Great article nonetheless! Thanks for all your hard work!

**Comment by matthiasrohmer** [comment]
Thanks for raising this! I suspect that might be true for other articles as well, not too sure yet how to go about this. The first headline and its id are created here:

https://github.com/GoogleChrome/web.dev/blob/5667e3a8b9ea757ea2a6c00218b230c566b80f2a/src/site/_includes/partials/post-next.njk#L79

There we could easily pre or append something like `h1` to the id to make a collision less likely. Though this introduces ugly URLs if someone really wants to share a link to the top of the page.
