### ISSUE TITLE
Add recommended security headers

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#8623]
**Describe the bug**
We can follow our own security best practices to keep the website safer. I'm not sure if it really makes sense to apply some of them to static sites, but let's see.

- `X-Frame-Options: DENY`: Prevents other sites to embed. This can be applied to all pages except ones that expects to be embedded.
- `X-Content-Type-Options: nosniff` effective only for IE, but won't harm.
- `Cross-Origin-Opener-Policy: same-origin-allow-popups`: Prevents other sites to communicate over `postMessage` when opened with `window.open`. This can be applied to all pages except ones that expects to be communicated.
- `Content-Security-Policy`: Looks like this is already applied.
- `Strict-Transport-Security`: Looks like this is already applied.

https://web.dev/security-headers/

**Comment by agektmr** [comment]
`CSP: frame-ancestors 'self'` was already set so `X-Frame-Options: DENY` is needed.

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform/backend.  As this is about the site, then it shouldn’t be an issue after the move.
