### ISSUE TITLE
`break-all` sometimes leaves bad breaks

### ISSUE THREAD

**Issue by tunetheweb** [GoogleChrome/web.dev#8632]
**Describe the bug**
This is ugly:

<img width="780" alt="Header breaks code word unnecessarily" src="https://user-images.githubusercontent.com/10931297/188197711-e62fc80b-310a-48be-a13f-4c1995ddd121.png">

**To Reproduce**
1. Go to https://web.dev/speculative-prerendering/#in-browser-speculation-rules-for-prefetch-and-prerender
2. Notice header breaks on `prefetch` leave it as `prefetc` and `h` which is a bit ugly and unnecessary since it would line break cleanly before or after the word.

**Expected behavior**
We should only break code if we absolutely have to.

Removing the `word-break: break-all;` from below code fixes this, but not sure of other implications for longer code segments that do need to force this break?

https://github.com/GoogleChrome/web.dev/blob/17058e904c4baa4fa0b4591827e40991e5792af9/src/scss/next.scss#L378-L399

**Comment by rachelandrew** [comment]
@tunetheweb @matthiasrohmer if you also add `overflow-wrap: break-word` (as well as removing `word-wrap: break-all`) it will wrap on the instance of a very long word.

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Text/Wrapping_Text

**Comment by tunetheweb** [comment]
That's what I did in #8665. Forgot about this issue but will open PR to do the same here.
