### ISSUE TITLE
Update URL of DevTools page

### ISSUE THREAD

**Issue by skmohammadi** [GoogleChrome/web.dev#8644]
### What page(s) need to be updated?

https://web.dev/critical-rendering-path-constructing-the-object-model/

### Why is this update needed?

The mentioned resource page about DevToos is not exists (404):

https://web.dev/web/tools/chrome-devtools/

**Comment by skarthikeyan96** [comment]
@robdodson any chance there is an update url for this `https://web.dev/web/tools/chrome-devtools/`. I can make the content update via PR

**Comment by heyawhite** [comment]
These broken URLs have been fixed, and directed to the appropriate docs on developer.chrome.com
