### ISSUE TITLE
:modal article: demo doesn't open in fullscreen

### ISSUE THREAD

**Issue by myakura** [GoogleChrome/web.dev#8651]
**Describe the bug**

The demo on https://web.dev/is-it-modal/ doesn't work as expected.

**To Reproduce**

1. Go to https://web.dev/is-it-modal/
2. Scroll down to the last demo (the one with white ": m o d a l" on the dark background)
3. Click or tap the "Take it full screen" button

**Expected behavior**

The demo page inside codepen iframe opens in fullscreen.

**Screenshots**

<img width="1200" alt="Screenshot: article with DevTools showing errors after clicking on the button in the codepen demo" src="https://user-images.githubusercontent.com/413984/189136465-618b1944-84f3-48e9-b905-a5ece3de0067.png">

**Comment by rachelandrew** [comment]
Fixed in #8652

**Comment by myakura** [comment]
confirming it's working now. thanks for the quick merge!
