### ISSUE TITLE
Time to first Byte page wrong illustration 

### ISSUE THREAD

**Issue by qunodmitrek** [GoogleChrome/web.dev#8657]
When visiting TTFB page at https://web.dev/ttfb/ image contains wrong text saying „TTFB - Interaction to next paint“ https://web-dev.imgix.net/image/W3z1f5ZkBJSgL1V1IfloTIctbIF3/eNXaxPi9NdUVSTDRJFkV.svg

**To Reproduce**
1. Go to web.dev/ttfb
2. Locate the image with percentiles to be considered good/poor
3. See text

**Expected behavior**
„Time to first byte“ as the text on the image

**Comment by AaronForinton** [comment]
Looks like this has been fixed.
