### ISSUE TITLE
Focus styles do not show in Glitch for Keyboard Access article

### ISSUE THREAD

**Issue by Amani-Maklad** [GoogleChrome/web.dev#8670]
**Describe the bug**

**To Reproduce**
1. Go to https://web.dev/keyboard-access/
2. Scroll down to Logical tab order
4. See error in the example. which is the border color for the kiwi, peach and coconut buttons in both examples are in black which make the tab focus does not appear because the focus is in black too.
5. I tried to open the same link in firefox, google chrome, google chrome incognito mode, edge, internet explorer and all show the same border style, which is black border and pressing tab button to switch between buttons does not appear because the foucs is in black color too.
6. I am using:
   - Windows 10 Pro Version 21H2.
   -  Google Chrome browser Version 105.0.5195.102 (Official Build) (64-bit).

**Expected behavior**
I expexted to see where the focus should appear when pressing tab button to switch between the buttons.

**Screenshots**

![Screenshot 2022-09-13 163248](https://user-images.githubusercontent.com/96262605/189929405-03a91660-ac96-408c-9bf0-f920fd975e47.png)

**Comment by matthiasrohmer** [comment]
Did you click into the Glitch iframe before pressing tab? Otherwise this might be a Windows platform related problem, as the correct focus styles appear for me on macOS:

<img width="496" alt="image" src="https://user-images.githubusercontent.com/12857772/190388486-36bfa2db-d26c-4715-8859-424ce26ed2ec.png">

**Comment by Amani-Maklad** [comment]
Yes, I clicked into the iframe before pressing the tab.
I opened the link in my macOS andit shows exactly like your screenshot.
look like the page is using the default outline color which is black on windows and blue on macOS.

![Capture](https://user-images.githubusercontent.com/96262605/190417214-235900a8-9b89-4a7c-8ccc-0881c0cfbb21.PNG)

**Comment by matthiasrohmer** [comment]
Hah, that makes sense... We'll add an explicit focus color to accommodate Windows, thanks for reporting!

**Comment by dstmarthe** [comment]
Closing this issue since we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
