### ISSUE TITLE
Refactor 'how-pwa-scoring-works' in the PWA Audits into just one page

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChrome/web.dev#868]
How PWA Scoring works is on every page, suggest to pull it out into one page. We kinda need to have it in one place otherwise search might pick it up as dupicated content.

eg https://web-dev-staging.appspot.com/service-worker/#how-pwa-scoring-works

*Update*

It looks like it's broadly a choice across all the scoring pages to have similar includes - I personally would remove all these extra bits and add a link to a page for each scoring system that just describes what they are doing. After reading one audit, I then got a tad frustrated reading the 2nd one in the PWA category.

**Comment by PaulKinlan** [comment]
Hmm, I see that it is included as a Template {% include 'content/lighthouse-pwa/scoring.njk' %} - my general feedback reading this is that it was a heap of bloat that I didn't really care for and it added obscured some other content lower down that page.

**Comment by PaulKinlan** [comment]
huh - I can't find scoring.njk

**Comment by robdodson** [comment]
They should all be in here
https://github.com/GoogleChrome/web.dev/tree/master/src/site/_includes/content

*From: *Paul Kinlan <notifications@github.com>
*Date: *Thu, May 2, 2019, 6:16 PM
*To: *GoogleChrome/web.dev
*Cc: *Subscribed

huh - I can't find scoring.njk

**Comment by Meggin** [comment]
For PWA and best practices scoring, how about I update the includes to be asides that link to scoring paragraphs in scoring guides?

**Comment by Meggin** [comment]
Also gonna change include for 'What is Aria', to be an aside that points to ARIA docs on /web.

**Comment by robdodson** [comment]
+1 to the above suggestions.
