### ISSUE TITLE
Uses Application Cache

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChrome/web.dev#869]
I know this is probably lighthouse, but it should be the negative of this, the best practice title reads like you use AppCache

https://web-dev-staging.appspot.com/appcache-manifest/

**Comment by Meggin** [comment]
The titles, at least in perf, are aligned with Lighthouse report titles,
failure text when it's available. The idea behind that is the developers
search the text they see in the report for more information, so aligning of
titles helps with this. What d'ya think would be the best game plan here?

**Comment by robdodson** [comment]
I think I'm going to close this unless there's any follow up? We use the same text as what Lighthouse displays, so if we change it we should change it in Lighthouse as well.
