### ISSUE TITLE
Asides with bullet points are not rendered as lists

### ISSUE THREAD

**Issue by gaul** [GoogleChrome/web.dev#8696]
**Describe the bug**
Asides with bullet points are not rendered as lists.

**To Reproduce**
1. Go to https://web.dev/rail/#:~:text=Recognize%20the%20factors%20that%20affect%20page%20load%20performance
2. Scroll down to "Recognize the factors that affect page load performance"
3. See lack of bullet points

**Expected behavior**
Four asterisks render as bullet points.

**Screenshots**
![image](https://user-images.githubusercontent.com/848247/191195227-a75db2f5-4afe-40d4-8eb8-a906afb50a51.png)

Related to #7640?

**Comment by AaronForinton** [comment]
<img width="923" alt="Screenshot 2022-11-24 at 23 19 25" src="https://user-images.githubusercontent.com/89849359/203873574-7141369e-2587-469e-9787-ae7fd8aa1a65.png">

Closing because this appears to have been fixed.
