### ISSUE TITLE
Few broken images in an article

### ISSUE THREAD

**Issue by osmium8** [GoogleChrome/web.dev#8712]
**Describe the bug**
Few broken images in the article 'Service worker mindset'.

**To Reproduce**
1. Go to ['Service worker mindest'](https://web.dev/service-worker-mindset/)

**Expected behavior**
All images in the article should load.

**Comment by jpmedley** [comment]
@petele There's at least one broken image on this page.

**Comment by heyawhite** [comment]
@petele assigning based on early comment, but feel free to re-assign to a TW

**Comment by AaronForinton** [comment]
Just a note that the missing image is a .gif - you can find it [archived here](https://web.archive.org/web/20220206151705/https://web.dev/service-worker-mindset/). Wondering how you'd like to proceed on that basis @petele @heyawhite
