### ISSUE TITLE
Safari bug

### ISSUE THREAD

**Issue by greyskymedia** [GoogleChrome/web.dev#8717]
#8709 does't work in safari

**Comment by matthiasrohmer** [comment]
Are you referring to this new article here: https://web.dev/speedy-css-tip-animated-loader/?

I just gave the linked CodePen at https://codepen.io/web-dot-dev/pen/oNdeWep a quick try in Safari 16 and it worked as described.

Feel free to reopen with more details!

**Comment by greyskymedia** [comment]
Yep that one. 15.6.1... I still need to run the latest update.
