### ISSUE TITLE
content: Remove references to  jankfree.com from https://web.dev/speed-rendering/

### ISSUE THREAD

**Issue by andreban** [GoogleChrome/web.dev#8722]
Remove references to  jankfree.com from https://web.dev/speed-rendering/.  The domain [jankfree.com](http://www.jankfree.com/), referenced a couple of times in the article doesn't exists anymore and instead links to a site offering to purchase the domain.

### What page(s) need to be updated?

Provide a list of URLs.
- https://web.dev/speed-rendering/

### Why is this update needed?

The domain [jankfree.com](http://www.jankfree.com/), referenced a couple of times in the article doesn't exists anymore and instead links to a site offering to purchase the domain.

### What's the deadline?
None?

#### Is it a hard deadline?
None :)

If yes, please explain why.
It isn't :)

**Comment by Deloww** [comment]
> Remove references to jankfree.com from https://web.dev/speed-rendering/. The domain [jankfree.com](http://www.jankfree.com/), referenced a couple of times in the article doesn't exists anymore and instead links to a site offering to purchase the domain.
> 
> ### What page(s) need to be updated?
> Provide a list of URLs.
> 
> * https://web.dev/speed-rendering/
> 
> ### Why is this update needed?
> The domain [jankfree.com](http://www.jankfree.com/), referenced a couple of times in the article doesn't exists anymore and instead links to a site offering to purchase the domain.
> 
> ### What's the deadline?
> None?
> 
> #### Is it a hard deadline?
> None :)
> 
> If yes, please explain why. It isn't :)
