### ISSUE TITLE
Link returning a 404

### ISSUE THREAD

**Issue by davidekete** [GoogleChrome/web.dev#8723]
An anchor text in [the web app manifest](https://web.dev/learn/pwa/web-app-manifest/) section (The installation criteria in the first warning). Clicking this link takes you to a 404 page. 

1. Go to  [the web app manifest](https://web.dev/learn/pwa/web-app-manifest/) section.
2. Click on installation criteria in the first warning.
3. See 404 page.

It is linked to [this page](https://web.dev/learn/pwa/web-app-manifest/installation/#installation-criteria) (which does not exist), instead of [this page](https://web.dev/learn/pwa/installation/#installation-criteria).

**Comment by Abhiram-Gullapalli** [comment]
I think the issue is resolved now, I didn't find the 404 page when tried to reproduce the same steps.

**Comment by davidekete** [comment]
<img width="1440" alt="Screenshot 2022-09-27 at 2 33 16 PM" src="https://user-images.githubusercontent.com/88355936/192541058-14826dde-ecd1-4986-ba52-a86a7948275b.png">
The issue hasn't been fixed, it still leads to a 404.

**Comment by Abhiram-Gullapalli** [comment]
OOh!

**Comment by Abhiram-Gullapalli** [comment]
Just opened a pr regarding it, it'll get resolved once it gets accepted.
