### ISSUE TITLE
Learn HTML: Incorrect information about the doctype

### ISSUE THREAD

**Issue by zcorpan** [GoogleChrome/web.dev#8751]
**Describe the bug**

The doctype section says

> The first thing in any HTML document is the preamble. For HTML, all you need is `<!DOCTYPE html>`. This may look like an HTML element, but it isn't. It's a document type declaration or DTD. 

This is incorrect. DTD stands for Document Type *Definition*, which is the thing the document type declaration references (in SGML and XML). HTML these days doesn't have a DTD.

> The DTD tells the browser you're using HTML.

No, it doesn't. The MIME type `text/html` tells the browser you're using HTML. It will be HTML regardless of the doctype.

> If omitted, browsers may use a different rendering mode known as [quirks mode](https://developer.mozilla.org/docs/Web/HTML/Quirks_Mode_and_Standards_Mode). Including the DOCTYPE helps prevent quirks mode.

Yes. This could be more precise and say "will" instead of "may", as there's no uncertainty.

Exception:  in `<iframe srcdoc="...">` the doctype is optional and the document will be in no-quirks mode.

**To Reproduce**
1. Go to https://web.dev/learn/html/document-structure/#lessdoctype-htmlgreater

**Comment by estelle** [comment]
Thank you for the excellent feedback. I've submitted a PR.

**Comment by zcorpan** [comment]
Thanks, but the new text is still wrong. ^_^ Doctype != DTD.

I can submit a PR tho.
