### ISSUE TITLE
Learn HTML: value of the lang attribute

### ISSUE THREAD

**Issue by zcorpan** [GoogleChrome/web.dev#8752]
**Describe the bug**

> The value of the [lang attribute](https://developer.mozilla.org/docs/Web/HTML/Global_attributes/lang#language_tag_syntax) is a two-letter ISO language code

Should say 2-or-3-letter.

**To Reproduce**
1. Go to https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang#language_tag_syntax

**Comment by ChasBelov** [comment]
In an email exchange with a representative of WebAIM, they told me that screen readers can behave incorrectly with three-letter ISO language codes and that two-letter codes result in a more dependable screen-reader experience.

**Comment by rachelandrew** [comment]
Assigning to @estelle as we want to represent best practice in addition to what is in the spec, so if this a11y info is correct then it might be we want to add a note to say three-letter codes are valid but might be problematic.
