### ISSUE TITLE
content: Correct alternatives to preferred-reduce-motion

### ISSUE THREAD

**Issue by ChasBelov** [GoogleChrome/web.dev#8762]
* Use this template to request updates to existing content.
* Delete any fields that aren't relevant to your issue. 
* Update the title of this issue with a brief summary of the work to be done.

### What page(s) need to be updated?

Provide a list of URLs.
https://web.dev/learn/accessibility/motion/#progressive-enhancement-for-movement

### Why is this update needed?
The section appears to conflate supporting reduced motion with meeting the WCAG 2.0 AA rules on keeping animations to below five seconds. This is a problem because they are completely different issues. Advice given can lead to some site visitors with attention deficit or vestibular disorders being unable to use websites built using this advice.

### What's the deadline?
None

### What is the content to be replaced, if any?
Alternatively, as shown in the next set of examples, you can code all your animations to stop moving within five seconds or less instead of playing on an infinite loop.

### What is the replacement content?
Even brief animations less than the 5 seconds specified in WCAG 2.0 AA can be problematic for some people. The safest action for site visitors who have selected Prefers Reduced Motion is to only serve animation when the visitor activates a play-animation button and allow them to pause the animation as well.

**Comment by dstmarthe** [comment]
Thanks for raising this. Content on this site is now frozen. We're moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298540702
