### ISSUE TITLE
content: Clarify use of reduced motion as a tool

### ISSUE THREAD

**Issue by ChasBelov** [GoogleChrome/web.dev#8764]
* Use this template to request updates to existing content.
* Delete any fields that aren't relevant to your issue. 
* Update the title of this issue with a brief summary of the work to be done.

### What page(s) need to be updated?

Provide a list of URLs.
https://web.dev/learn/accessibility/why/ (section titled "Seizure and vestibular disorders")

### Why is this update needed?
Use of the word "reduce" may be an accident of the setting's history, as the setting inherited first use. Windows 10 calls it "Show animation in Windows" and Android calls it "Remove animations".

### What's the deadline?
None

### What is the content to be replaced, if any?
**Tools include:** Operating system settings to reduce motion.

### What is the replacement content?
**Tools include:** Operating system settings to reduce or remove motion.

**Comment by heyawhite** [comment]
@ChasBelov great point. I've integrated your suggestion through that section, so you won't read it exactly as you've written.

You can read a preview of the updated content here: https://github.com/GoogleChrome/web.dev/pull/8783/files#diff-f4a9d5368cadeafaa197f4ba94cdbda8eb72e0e2a6ea54012f41cbbf2e640a9c
