### ISSUE TITLE
LearnAccessibility – wrong link URL

### ISSUE THREAD

**Issue by zbianca** [GoogleChrome/web.dev#8777]
**Describe the bug**
LearnAccessibility Seizure section contains the same links as in the previous section – wrong link to article and video.

**To Reproduce**
1. Go to 'Learn Accessibility'
2. Click on '001 What is digital accessibility measured?'
3. Scroll down to 'Seizure and vestibular disorders'
4. The last paragraph contains the same links as in the previous section, Cognitive impairments.

**Expected behavior**
The exactly links need to be confirmed with the author, [Carie Fisher](https://github.com/cehfisher), but possibly: 
- https://youtu.be/UjmhDyJhgvs
- https://www.nytimes.com/2022/05/17/opinion/my-disability-roadmap-adulthood.html

**Comment by heyawhite** [comment]
This has been fixed
