### ISSUE TITLE
Typo in description of How is digital accessibility measured page

### ISSUE THREAD

**Issue by shawnthompson** [GoogleChrome/web.dev#8791]
**Describe the bug**
There is a typo in description for the word disabilities on [How is digital accessibility measured?](https://web.dev/learn/accessibility/measure/) page

> Introduction to measuring accessibility of digital products so that everyone, including people with disabilies, can still interact in a meaningful and equal way.

The word ** disabilies** should be ** disabilities**

**To Reproduce**
1. Go to 'https://web.dev/learn/accessibility/measure/'
2. See error

**Expected behavior**
The word disabilities should be spelt right.

**Screenshots**
![image](https://user-images.githubusercontent.com/2575266/193840330-694e258a-ae9d-4252-8f61-775aacf59e89.png)

**Comment by heyawhite** [comment]
Oh that's a fun one. Fix out shortly.

**Comment by shawnthompson** [comment]
@heyawhite  I was going to put in a PR but I wasn't sure if there was a process to do it.

**Comment by heyawhite** [comment]
@shawnthompson no specific process, anyone is welcome to open a PR and fix directly!

To merge any changes from contributors, they must sign a CLA. If you are not currently covered under a CLA, please visit https://cla.developers.google.com/. That makes it much easier for us to review and merge changes.

Thanks again for pointing it out. If you see anything else, feel free to open an Issue or a PR :)
