### ISSUE TITLE
/security is taken by a migrated blog post

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#8802]
**Describe the bug**
https://web.dev/security is taken by a small blog post created by one of batch migration. I think the slug is too broad and misleading. I'd move it to somewhere else or ditch it entirely as it's a trivial content and outdated.

I'd instead redirect https://web.dev/secure to https://web.dev/security.

**Comment by rachelandrew** [comment]
@AaronForinton could you deal with this one? I think we can lose the blog post currently at /security, as it's pretty old. I think then add a redirect for /security to /secure in the redirects yaml file.

**Comment by AaronForinton** [comment]
@rachelandrew PR is now attached.
