### ISSUE TITLE
EditorConfig compliance

### ISSUE THREAD

**Issue by pepelsbey** [GoogleChrome/web.dev#8812]
**Is your feature request related to a problem? Please describe.**

There’s [.editorconfig](https://github.com/GoogleChrome/web.dev/blob/main/.editorconfig) at the root of this repository. Though if you’d run `npx editorconfig-checker@4.0.0` it’d get you 9754 errors.

Just today I was creating [a PR with fixes](https://github.com/GoogleChrome/web.dev/pull/8811) for one article, but the diff was too distracting for a good PR: 90% were trimmed trailing spaces. So I had to disable my EditorConfig extension to file a sensible PR.

**Describe the solution you'd like**

It would be good to:

- Add a linting npm script
- Add an action that would check new PRs against the config
- Start work on aligning existing content with the config

**Describe alternatives you've considered**

There might be a git-hook that’d force the config, but I don’t think it would be a good DX.

**Additional context**

I’m happy to send a PR with the script and GitHub action for it. Also, I can help to create a series of PRs that would align existing code and content with the config.

**Comment by pepelsbey** [comment]
I’m happy to take this issue as a weekend project and fix the code style to match the EditorConfig. Let me know if you’d like that.

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new non-Github platform so many processes will be different that what it is now. As this is about the site, then it shouldn’t be an issue after the move.
