### ISSUE TITLE
When filing an issue, include the URL of the page

### ISSUE THREAD

**Issue by estelle** [GoogleChrome/web.dev#8814]
**Is your feature request related to a problem? Please describe.**
Would be fantastic if, when the user selects "file a bug" under "contribute" in the web.dev footer area, if the URL of the current page was included in the issue.

When addressing issues, sometimes it's not immediately apparent where the content that has the issue is located; automatically including the URL would reduce the chance of this happening.

**Describe the solution you'd like**
Add the URL of the current page as a parameter so the issue can include the URL

**Describe alternatives you've considered**
Optionally, adding a request for the OP to include the URL would be helpful, but automatically adding it helps ensure the URL is included.

**Comment by dstmarthe** [comment]
Thanks for raising this. We're moving to a new platform away from Github with a new issue tracker that does actually request that the issuer provide a url of the relevant page. While it's still in development - on the staging site I can see that the 'File a Bug' does GET the URL of the page it was clicked on. So, this will most likely be a feature after the move or the alternative. Sorry for closing this but we won't be using GH anymore and the new public issue tracker resides at 
https://issuetracker.google.com/issues?q=status:open%20componentid:1400680&s=created_time:desc
