### ISSUE TITLE
Give more helpful error message if no author data exists for author

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/web.dev#8829]
https://github.com/GoogleChrome/web.dev/blob/f788b08fd09fe02209982cf41148aa2de56287f0/src/site/_filters/expand-authors.js#L16

Executes if a page specifies an author in its frontmatter that does not exist in the authorsData.json. This could also happen if either the key in the JSON has a typo or the author name in the frontmatter. However the message should give the hint to check both.

**Comment by dstmarthe** [comment]
Moving to a new non-Github platform, so this will either be not an issue or a different issue.
