### ISSUE TITLE
Investigate and fix high memory usage for production builds

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/web.dev#8830]
Production builds slightly differ from other environment builds by performing some additional tasks, like building CSP hashes, all languages, ... So naturally prod builds are a little more resource intensive, but currently builds can only be performed by setting `NODE_OPTIONS=--max_old_space_size=8192` while during build memory usage of the node process is hovering somewhere between 6.5 and 7.5GB. That's absurd and need to be fixed.

**Comment by matthiasrohmer** [comment]
Digging through a heap snapshot of the build hints at the following potentially non-ideal snippets:

https://github.com/GoogleChrome/web.dev/blob/019d836bca0a9003c7cdeba6a756b7e1e7f7b333/src/site/_filters/find-by-url.js#L35-L50

https://github.com/GoogleChrome/web.dev/blob/019d836bca0a9003c7cdeba6a756b7e1e7f7b333/src/site/_collections/hooks/utils.js#L29-L46

**Comment by matthiasrohmer** [comment]
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/12857772/195109075-437afd15-dc2f-45c3-bd1f-f15769f6c8c9.png">

Eleventy's internal merge is costly, but that's also no surprise.

**Comment by matthiasrohmer** [comment]
We are not affected by any of memory-related issues introduced with 11ty 1.0. Downgrading to 0.12.1 not only builds much slower but also uses 3.2GB compared to the 2.2GB building only the English locale for production uses.

**Comment by Rosie2937** [comment]
>

**Comment by dstmarthe** [comment]
We are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
