### ISSUE TITLE
Performance audits - add scoring guide

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#884]
I've added scoring descriptions to every performance guide.

However, it would make sense to re-factor this post-v1.

We should have a performance scoring guide that covers how scoring works for performance in a general sense.

Then each audit guide will cover scoring specific to that audit.

Removes repetition while still keeping the audit specifics.

**Comment by kaycebasques** [comment]
Fixed: https://web.dev/performance-scoring/
