### ISSUE TITLE
Remove references to old/new design system

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/web.dev#8840]
The new design system has been rolled out, meaning we can remove som dead ends in our code base:

https://github.com/GoogleChrome/web.dev/blob/e1517346482c63822e683ba2fa3a21551365e19a/src/site/_includes/components/Compare.js#L19-L27

https://github.com/GoogleChrome/web.dev/blob/e1517346482c63822e683ba2fa3a21551365e19a/src/site/_includes/components/Banner.js#L22-L33

https://github.com/GoogleChrome/web.dev/blob/e1517346482c63822e683ba2fa3a21551365e19a/src/site/_includes/components/CompareCaption.js#L17-L26

https://github.com/GoogleChrome/web.dev/blob/e1517346482c63822e683ba2fa3a21551365e19a/src/lib/utils/is-design-system-context.js#L1-L5

https://github.com/GoogleChrome/web.dev/blob/e1517346482c63822e683ba2fa3a21551365e19a/.eleventy.js#L153-L165

**Comment by devnook** [comment]
We also need to rename xxx-next.njk templates to just xxx.njk and delete obsolete ones.

**Comment by devnook** [comment]
Prerequisite: https://github.com/GoogleChrome/developer.chrome.com/issues/3955

**Comment by dstmarthe** [comment]
Closing this as we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
