### ISSUE TITLE
Draw locale from context instead of path for components/shortcodes

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/web.dev#8841]
The shortcodes relying on translations currently inflect the language code from the page path which is brittle. Since 11ty 1.0 shortcodes get the render context which already holds the locale (`this.ctx.locale`) to use.

https://github.com/GoogleChrome/web.dev/blob/e1517346482c63822e683ba2fa3a21551365e19a/src/site/_includes/components/Compare.js#L36

Other shortcodes affected: Compare, Aside, BrowserCompat, Compare, Instruction, SignPosts, StackOverflow

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
