### ISSUE TITLE
A minor redesign of the web.dev homepage

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/web.dev#8842]

**Comment by akshitarora921** [comment]
@devnook, please add more details

**Comment by tokyodanj** [comment]
Hey @devnook - are you able to provide details here? Did you say Rachael could help?

**Comment by rachelandrew** [comment]
We are having a meeting about this tomorrow. After that we'll have more details.

**Comment by tokyodanj** [comment]
@devnook - design ready for review - link added to [google doc](https://docs.google.com/document/d/1W_iFdCLmgm1CjC26xCB4AUC11k9neNmR-XQB5bckPu4/edit?usp=sharing)

**Comment by devnook** [comment]
@MarcSWD whats the status?
