### ISSUE TITLE
Hit fs only once instead of for every `Aside` render

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/web.dev#8843]
https://github.com/GoogleChrome/web.dev/blob/3c050f00b047cc302218de698a8814fa72d7e876/src/site/_includes/components/Aside.js#L48-L57

`fs.readFileSync` gets called with every occurrence of `{% Aside %}`. The icons should instead be loaded once on module evaluation and then reused.

**Comment by dstmarthe** [comment]
We are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
