### ISSUE TITLE
Accessibility audits - lots more to do on scoring

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#885]
I've added scoring descriptions to some accessibility guides but didn't fully understand how it works.

We need to add a new accessibility scoring guide.

And we need to explain how scoring works specifically for each audit.

**Comment by robdodson** [comment]
These now follow the same severity levels that deque uses in axe. PR explanation here: https://github.com/GoogleChrome/lighthouse/pull/8823

**Comment by robdodson** [comment]
This is fixed by https://web.dev/accessibility-scoring/
