### ISSUE TITLE
Error loading page *please help*

### ISSUE THREAD

**Issue by frazarz80** [GoogleChrome/web.dev#8851]
**Describe the bug**
Error loading page

**To Reproduce**
1. Go to 'http://autoglassmatters.com'

**Expected behavior**
'Load my website' (http://autoglassmatters.com) 

**Screenshots**

**Comment by frazarz80** [comment]
Need help fixing my webpages loading error. Google seems to be no help

**Comment by frazarz80** [comment]
![Uploading Screenshot_2022-10-11-18-30-26.png…]()

**Comment by rachelandrew** [comment]
@frazarz80 this is for issues with the web.dev website and not a general website help forum. Please try somewhere like https://stackoverflow.com/
