### ISSUE TITLE
Consolidation of /measure and PSI

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/web.dev#8852]
So far the difference between PSI and web.dev/measure were the additional categories that /measure was presenting and PSI did not. However, we will soon launch a new version of PSI where all the differences are removed. This creates the following problems:

- there will be ambiguity between the 2 tools (why there are 2? what's the difference?)
- the current FAQ on /measure becomes incorrect and misleading
- we need to maintain /measure with no obvious added value to the user

The solution we propose is as follows:

- Remove the PSI banner from the homepage of [web.dev](http://web.dev/)
- Remove the Url input tool from the /measure page and replace it with a static page
- Use said PSI banner as a hero banner on that static page
- Add a paragraph of text explaining why the tool was removed and advantages of tools consolidation.

**Comment by devnook** [comment]
@malchata will help with the copy for the explainer text.

**Comment by tokyodanj** [comment]
Hey @malchata - we'll be working on the design for this page next week. It would be great to have draft copy for the explainer text on Monday if possible? Thanks.

**Comment by devnook** [comment]
Let's use this copy for the design, and the exact wording can be adjusted/approved later.

**Comment by malchata** [comment]
If you need anything further from me on this end @devnook and @tokyodanj, just ping me here or email me.

**Comment by tokyodanj** [comment]
@devnook - design ready for review - link added to [google doc](https://docs.google.com/document/d/1W_iFdCLmgm1CjC26xCB4AUC11k9neNmR-XQB5bckPu4/edit?usp=sharing)

**Comment by Niamhtokyo** [comment]
Designs approved - ready for dev implementation.
