### ISSUE TITLE
Icons in table of contents have inconsistent sizing

### ISSUE THREAD

**Issue by zarahzachz** [GoogleChrome/web.dev#8855]
**Describe the bug**
When viewing your ["Accessible to all"](https://web.dev/accessible/) site, I noticed the `svg` in your table of contents have varying sizes (see image below for reference).

![Screen Shot 2022-10-12 at 9 27 32 AM](https://user-images.githubusercontent.com/5159392/195356386-ae7cc083-3110-4f8c-981d-736d47ad0aed.png)

This appears to be caused by your use of `flex` - when the associated text is lengthy and wraps to multiple lines, the container for the `svg` shrinks, making the icon appear smaller than the other icons in the table of contents. This can be fixed by adding `flex-shrink: 0` to [this file](https://github.com/GoogleChrome/web.dev/blob/012f1ca066ec373c607b382849befd3cfa3350fc/src/scss/pages/_path.scss#L11).

**To Reproduce**
1. Go to https://web.dev/accessible/
2. Scroll down to the table of contents section
3. See error

I'm currently using Chrome 106.0.5249.103 on Mac 12.6

**Expected behavior**
`svg` should visually appear the same size.

**Comment by matthiasrohmer** [comment]
This is now fixed, thanks for reporting! 🙂
