### ISSUE TITLE
Subscription doesn't work

### ISSUE THREAD

**Issue by pawelkowala** [GoogleChrome/web.dev#8868]
**Describe the bug**
Mobile Chrome
Desktop Chrome/Edge

https://web.dev/about/ subscribe form does nothing

**To Reproduce**
1. Go to https://web.dev/about/ and scroll to Developer Newsletter
2. Fill in the details in the form
3. tick both checkboxes and submit
4. Nothing happens, in the console you can find the error

index-950041fd.js:1 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'getResponse')
    at Z.captchaCheck (index-950041fd.js:1:1095)
    at Z.onSubmit (index-950041fd.js:1:1907)

**Expected behavior**
Form submitted, success message shown

**Screenshots**

**Comment by matthiasrohmer** [comment]
Thanks for the report! Sign-up is indeed broken on the About page, by a missing external script. While the fix is on its way you can instead sign up from the homepage 🙂
