### ISSUE TITLE
Fantom/draft articles in the search results

### ISSUE THREAD

**Issue by pepelsbey** [GoogleChrome/web.dev#8872]
**Describe the bug**

There is a fantom (draft?) article in the search results.

For example https://web.dev/en/spaces/2022-10-13-chrometober/

There might be more.

**To Reproduce**

1. Go to [web.dev](https://web.dev/)
2. Search for “Chrometober”
3. Click “How we built Chrometober” in the search results

**Expected behavior**

- No results in the search if it’s still a draft
- Working article if it’s published

**Screenshots**

<img width="662" alt="image" src="https://user-images.githubusercontent.com/105274/195986557-6faf2a46-4fbc-4762-ae78-0d80d3952ab6.png">

**Comment by matthiasrohmer** [comment]
Thanks for the report! That is indeed a bug.

The Twitter Space from your example has already happened and therefore does not show up on the Spaces page anymore: https://web.dev/spaces/

This page is rendered from child pages that do not have any layout and should not be rendered nor surfaced in search. Fix is on it's way with #8877.

**Comment by matthiasrohmer** [comment]
Created a follow-up issue at https://github.com/GoogleChrome/web.dev/issues/8882 - 404 pages are actually in place, while what you discovered are indeed rendered pages that should not be there 🙂

**Comment by dstmarthe** [comment]
Hi. Thanks for raising this issue. As we are migrating to a new platform, this it shouldn't be an issue after the move.
