### ISSUE TITLE
Course pages print error to the console

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/web.dev#8881]
Visiting https://web.dev/learn/design/ prints

```
Uncaught SyntaxError: Identifier 'initialCourse' has already been declared (at (index):1:4965)
```

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
