### ISSUE TITLE
Prevent Twitter Spaces partials from being built

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/web.dev#8882]
<img width="253" alt="image" src="https://user-images.githubusercontent.com/12857772/196172684-6d4fb7c7-5b7e-4fd0-b39b-61c4d1267980.png">

For some reason the Spaces detail pages are being built to `dist` despite having `permalink: false` set.

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
