### ISSUE TITLE
Pagespeeds Insights does not detect parent <ul> elements.

### ISSUE THREAD

**Issue by hidvegigabor** [GoogleChrome/web.dev#8899]
**Describe the bug**
Pagespeeds insights (or chromium) has a bug since years. When I measure our website ([https://www.easyocm.hu/](https://www.easyocm.hu/)) it says some `<li>` elements don't have `<ul>` or `<ol>` parents. This is not true at all. If you check the website's source code, there are `<ul>` elements.

**To Reproduce**
1. Go to https://web.dev/measure/?url=https%3A%2F%2Fwww.easyocm.hu%2F
2. Click on Run Audit
3. Scroll down to Accessibility, and open down Tables and lists

**Expected behavior**
Since every `<li>` has a `<ul>` parent in the source code, this should not happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/64589237/196883257-d7ea786f-68b7-4f8a-af9e-c0b6b01687a0.png)
![image](https://user-images.githubusercontent.com/64589237/196883517-8463eb80-329e-427a-87e3-cb1581ae20b9.png)

**Comment by AaronForinton** [comment]
I'm closing this as obsolete because PageSpeed Insights now has [its own URL.](https://pagespeed.web.dev/)
