### ISSUE TITLE
content: Sec-CH-UA and reduced UA documentation is confusing

### ISSUE THREAD

**Issue by slightlyoff** [GoogleChrome/web.dev#8916]
### What page(s) need to be updated?

 - https://web.dev/user-agent-client-hints/
 - https://developer.chrome.com/docs/privacy-sandbox/user-agent/
 - https://developer.chrome.com/docs/multidevice/user-agent/

### Why is this update needed?

[See Twitter discussion here](https://twitter.com/slightlylate/status/1583928775053479936?s=20&t=D3EmDYvAJSMszu5WZMCsHg).

These pages are ambiguous about the current behavior of Chrome and other Chromium-based browsers.

A small list of issues with them:

 - Inconsistent UA versions throughout
 - No clear callouts for which strings, at which points, *accurately* represent the current version (important in light of Safari deciding to lie to developers)
 - Examples that appear to undermine the plain reading of the text
 - In at least one case, an incorrect example [appears to show a version number *going backwards*](https://developer.chrome.com/docs/privacy-sandbox/user-agent/#how-does-the-reduced-ua-and-ua-ch-work) after Accept-CH dance.

Taken together, it's impossible to understand from these pages what the current situation is and what developers should expect, either in the first, or in subsequent requests post Accept-CH.

**Comment by slightlyoff** [comment]
Unable to assign an owner, so adding a comment to cc:

@miketaylr @yoavweiss @rowan-m @heyawhite

**Comment by tomayac** [comment]
“This page in particular doesn't document "Not a Brand" at all https://t.co/ON7eV84QZp or GREASE or anything (which also explains why it's so full of junk) https://t.co/4oUiw855ef "randomly including additional, intentionally incorrect" data”— http://twitter.com/dfabu/status/1584726710859182080

**Comment by rowan-m** [comment]
Looks like some docs related to Chromium-only functionality were migrated over to `developer.chrome.com`, so I've been making a few updates over on https://github.com/GoogleChrome/developer.chrome.com/pull/4781

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform, and as content is frozen at web.dev I’ve moved this issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298303554
