### ISSUE TITLE
There is no direct link to the `/patterns` route

### ISSUE THREAD

**Issue by BlackWind001** [GoogleChrome/web.dev#8936]
The page https://web.dev/patterns/ and its child content(s) are a very important resource.
As a developer, I remember visiting them a while ago and although I didn't bookmark it on my browser, I knew what to search for
on the search engine to get to the resources.
I was only able to access them because I knew they existed. However, for new developers using web.dev, this might will not be apparent.
I do not see any direct navigation link to the `/patterns` route on the home page of `web.dev` which is confusing considering all the information that it holds.
Please do add a direct navigation link for such resources and if there are other such resources which exist on the website but aren't apparent, please make them accessible as well.
I think this qualifies as a UX bug.

**To Reproduce**
1. Go to 'web.dev'
2. Search for 'patterns'
3. You won't see a result.

**Expected behavior**
A direct navigation link that users can easily find.

**Comment by BlackWind001** [comment]
For example, the `/learn` route has a direct link in the nav bar.

**Comment by rachelandrew** [comment]
@BlackWind001 thanks for raising this, we're currently working on a bit of a refresh of the site that will make these things more visible as they were added after the site was initially designed. So I hope to have this improved soon.

**Comment by BlackWind001** [comment]
Great to hear about the site refresh. Can't wait to see it.
Thanks for the quick reply.

**Comment by devnook** [comment]
This is live now.
