### ISSUE TITLE
Consolidation of web.dev / dcc visual assets

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/web.dev#8941]
We have various partial design Figma files and assets in Google drive floating around. It would be good to consoslidate them in one place, and have a master design reference for dcc and web.dev, respectively.

**Comment by tokyodanj** [comment]
Hey @devnook - we've created a new master Figma file and have started consolidating the web.dev pages, components and design system. All future work will be created in this file. We'll share it with you next week.

We'll do the same once we have the DCC figma files. Any luck sourcing those?

**Comment by tokyodanj** [comment]
Quick update re web.dev - we've noticed the design files aren't consistent with the live site in places e.g. subtle changes to type styling, colours and spacing. We'll update the master figma design system to reflect the live site to make sure we're in sync.

**Comment by tokyodanj** [comment]
@devnook yeah, the web.dev and dcc figmas are up to date so this can be marked as complete. Thanks
