### ISSUE TITLE
Poor one sided content article about Building a Better Web on YouTube - add issues that could be fixed in the future that could be useful to developers reading the article

### ISSUE THREAD

**Issue by summercms** [GoogleChrome/web.dev#8942]
* Use this template to request updates to existing content.
* Delete any fields that aren't relevant to your issue. 
* Update the title of this issue with a brief summary of the work to be done.

### What page(s) need to be updated?

https://web.dev/better-youtube-web-part1/

### Why is this update needed?

The title says: "Building a Better Web - Part 1: A faster YouTube on web"

The purpose of the web dot dev website is to show and help developers understand ways to improve the web by making better websites for users!

However, this article highlights one big problem many Googler's seem to miss and completely ignore time and time again!

The article focuses on speed and performance claiming this will help make the web a better place!

However, anyone that's ever used YouTube would agree that the coding design is shockingly terrible! Which a good developer would ask the simple question! 

Why bother to fix the website speed and performance when the video controls are so poorly designed that users struggle to be able to use the website in the first place!

Here's a screenshot showing the problem on YouTube:

![image](https://user-images.githubusercontent.com/57409060/198038929-f7914105-c63d-405c-b435-046a9646a7cb.png)

When a video has a white background, you can't even use the video player controls because you can't even see them! **It is impossible to see the volume slide bar and the video position slide bar as they are white on a white background!**

I'm a developer that tries to make a better web by making a website user friendly! That means not just focusing on speed and Core Web Vitals. But a whole list of things that effect the website's end-user! Web dot dev has a section on Accessibility!

For example, if I worked at YouTube I would code the video player to be able to use it when the video has a white background. I would code the video player controls to pass wai aria contrast issues!

The article even has a section titled: "State-management across components" and shows the video controls! But doesn't even bother to mention this issue about the poor accessibility!

The article should be balanced instead of trying to come across saying "we are doing an amazing job at YouTube and there are no issues at all".

Instead the article should also mention issues that the youtube team intend to fix and improve in the future that are related to the topics on the web dot dev website, e.g. Video Controls Do Not Pass Basic Accessibility!

---

### Conflict of Interest

The author: [Addy Osmani](https://web.dev/authors/addyosmani/)

He created the [Priority Hints](https://web.dev/priority-hints/) API that is mentioned in that article, but the article doesn't mention that.

### What's the deadline?

No dead line, the title says part 1. So maybe the authors could add this to part 1 or add it to a part 2.

#### Is it a hard deadline?

No hard dead line.

If yes, please explain why.

**Comment by rachelandrew** [comment]
@summercms thanks for raising this issue, however this particular article was about performance. There are further articles planned in the series, however it's not possible for any one article to cover every aspect of something, so these aren't changes we will add to the existing article.

To raise issues with YouTube, then you can do that [here](https://support.google.com/youtube/answer/4347644). The site is run by Google Web Developer Relations, and none of us work on YouTube so raising issues here won't help with your core requests.

**Comment by summercms** [comment]
@rachelandrew 

And what about the `Conflict of Interest` in the article?

The author: [Addy Osmani](https://web.dev/authors/addyosmani/) makes no mention that he was the main creator of the Priority Hints API.

![image](https://user-images.githubusercontent.com/57409060/198311091-900b97c0-5598-4db6-b144-ab3f24827d7a.png)

And you said:

> none of us work on YouTube

So basically the article is a plug for his API. I would suggest web dot dev at least at to the bottom of the article a mention he was the creator of the api mentioned in the article.

**Comment by rachelandrew** [comment]
That's not a conflict of interest. Googlers work on many web APIs and platform features, I write about CSS and am on the CSSWG for example. All of that information is publicly available in the specs we work on as this work is done in the open.

Work such as this on YouTube also serves to help validate that the spec work and platform features are useful.

**Comment by summercms** [comment]
Web dot dev has lost me as a follower, if you want to defend low quality content like that and not be transparent that's your loss.
