### ISSUE TITLE
Missing "/" in the url parameter on sharing the "Portals" directory

### ISSUE THREAD

**Issue by mayeedwin** [GoogleChrome/web.dev#899]
**What to change**
❌ https:/web.dev/hands-on-portals/ 

**What to change to**
✅ https://web.dev/hands-on-portals/ 

Cheers 🎉

**Comment by robdodson** [comment]
Hey @mayeedwin, quick question, where did you see this error?

**Comment by robdodson** [comment]
oh I think I found it, it's on the share button.

**Comment by mayeedwin** [comment]
> oh I think I found it, it's on the share button.

Great : )

**Comment by robdodson** [comment]
I thought I fixed this but noticed it's now adding an extra slash after the web.dev/ :P

**Comment by mayeedwin** [comment]
: ( 😎

**Comment by robdodson** [comment]
should be fixed now :)
