### ISSUE TITLE
Typo in Document Structure page on Learn HTML course

### ISSUE THREAD

**Issue by the-lazy-learner** [GoogleChrome/web.dev#8990]
**Describe the bug**
The word `alternate` is mistakenly typed as `alternative` on [Document Structure](https://web.dev/learn/html/document-structure/) in the Learn HTML course. Thank you for providing useful educational content to the public.

**To Reproduce**
Scroll down to the 'Alternate versions of the site' heading on the page to notice the typo.

**Screenshots**
![image](https://user-images.githubusercontent.com/13695177/199557073-2579fb4d-33b0-44a3-b060-3a290a0bade1.png)

**Comment by AaronForinton** [comment]
Thanks for spotting this. I've opened a PR and that addresses this and issue #8989
