### ISSUE TITLE
Contast of content in a caption in the article "Video and audio" (Learn Accessibility course)

### ISSUE THREAD

**Issue by TatianaFokina** [GoogleChrome/web.dev#8994]
**Describe the bug**
When users prefer a dark theme on web.dev platform, they can't see an icon with dots in a caption under a screenshot with YouTube IU in the article "[Video and audio](https://web.dev/learn/accessibility/video-audio/)" (Learn Accessibility section).

**To Reproduce**
1. Go to "[Video and audio](https://web.dev/learn/accessibility/video-audio/)". It's Learn Accessibility section.
2. Switch to a dark theme.
3. Scroll down to [a part about transcripts](https://web.dev/learn/accessibility/video-audio/#transcripts) and find the image with YouTube UI.
4. See error in the caption under this image.

**Expected behavior**
Users should see the icon with three dots with a dark theme too. Maybe it will be better use a text description of this button instead of use the icon.

**Screenshots**
![The page of article in a dark theme. The caption under the picture says "Under the video title, click and select Show transcript from the dropdawn menu. The transcripts will show up to the right of bottom of the video, depending of your screen size. An yellow error points to a blank space between words in the caption."](https://user-images.githubusercontent.com/17615202/199701751-78e70303-e434-4464-b29d-7f52b3eb84d3.png)

**Comment by heyawhite** [comment]
@TatianaFokina thank you for catching this! I'll update it this week.
