### ISSUE TITLE
Default back to app.webmanifest not manifest.json

### ISSUE THREAD

**Issue by mayeedwin** [GoogleChrome/web.dev#900]
With trying to have PWA Installable on all platforms, Android, IoS and Windows devices, `app.webmanifest` works best for all. It also looks descriptive in relation to PWAs as opposed to `manifest.json`

Reference doc on web.dev here : https://web.dev/add-manifest-react/

**Comment by robdodson** [comment]
Tagging in @petele our PWA expert.

Pete do you think we should update the posts to use `app.webmanifest` instead? I actually hadn't seen it until now but I guess it's what [MDN uses](https://developer.mozilla.org/en-US/docs/Web/Manifest).

**Comment by mayeedwin** [comment]
> Tagging in @petele our PWA expert.
> 
> Pete do you think we should update the posts to use `app.webmanifest` instead? I actually hadn't seen it until now but I guess it's what [MDN uses](https://developer.mozilla.org/en-US/docs/Web/Manifest).

Sure, this will be great.

**Comment by housseindjirdeh** [comment]
Thanks for logging this @mayeedwin 🙏 

Curious as well if `app.webmanifest` is more widely used. Will update the React-specific manifest guide accordingly if so.

**Comment by mayeedwin** [comment]
> Thanks for logging this @mayeedwin 
> 
> Curious as well if `app.webmanifest` is more widely used. Will update the React-specific manifest guide accordingly if so.

Sure, it's. Perfectly. And you're welcome 💪

**Comment by petele** [comment]
The current working draft of the [spec](https://www.w3.org/TR/appmanifest/#media-type-registration) only calls out the extension (`.webmanifest`). As far as I know, all browsers will support any file extension, and changing that behaviour now would break a number of sites. 

Unfortunately I don't have any data about what extension is used the most, but will see if I can find anything.

It can't hurt to change it to `.webmanifest`, but I don't think developers should be concerned about changing it to that if they're already using something else.

**Comment by mayeedwin** [comment]
> The current working draft of the [spec](https://www.w3.org/TR/appmanifest/#media-type-registration) only calls out the extension (`.webmanifest`). As far as I know, all browsers will support any file extension, and changing that behaviour now would break a number of sites.
> 
> Unfortunately I don't have any data about what extension is used the most, but will see if I can find anything.
> 
> It can't hurt to change it to `.webmanifest`, but I don't think developers should be concerned about changing it to that if they're already using something else.

Awesome. It doesn't break anything, true. The new extension name is more semantic. When I was exploring PWAs on Windows platform sometime back, uhm, `.webmanifest` extension worked out but `.json' failed. Gladly the new Chromium Edge, understands this.
