### ISSUE TITLE
Unnecessary `:visited` is in the `:link` section of learn/css/pseudo-classes

### ISSUE THREAD

**Issue by oshikiri** [GoogleChrome/web.dev#9043]
**Describe the bug**

Unnecessary `:visited` exists at the `:link` section of https://web.dev/learn/css/pseudo-classes/

```md
### `:link`

The [`:link`](https://developer.mozilla.org/docs/Web/CSS/:linkhttps://github.com/GoogleChrome/web.dev/commit/3d5ec42b49823e1ba7db41b633133cbab7755b25
pseudo-class can be applied to any `<a>` element that has a `href` value that **hasn't been** visited yet.
`:visited`
```

https://github.com/GoogleChrome/web.dev/blob/f6e398e06ef9e7c011ef59cc5de7cc93c87b9689/src/site/content/en/learn/css/pseudo-classes/index.md#link

**To Reproduce**
1. Go to https://web.dev/learn/css/pseudo-classes/#link
2. See "The :link pseudo-class can be applied to any <a> element that has a href value that hasn't been visited yet. :visited"

**Expected behavior**
I think the `:visited` should be the h3 heading of the next paragraph

**Screenshots**

![image](https://user-images.githubusercontent.com/10720090/201115011-8c9e28a1-fdf1-410b-ac63-2edc04b0ca3e.png)

https://web.dev/learn/css/pseudo-classes/#link

**Comment by AaronForinton** [comment]
Thank you for spotting this @oshikiri, and I think you're right about it being the h3 heading of the next paragraph.

**Comment by oshikiri** [comment]
Thank you for fixing!
