### ISSUE TITLE
Simplify and improve example for fallback CSS for variable fonts

### ISSUE THREAD

**Issue by RoelN** [GoogleChrome/web.dev#9076]
As @nicksherman explains:

>  I typically avoid the `not` qualifier for the fallback styles and instead set them as the non-conditional defaults. They can still be overridden with the @supports as progressive enhancement. That way the fallbacks don’t rely on support for @supports.

### What page(s) need to be updated?

https://web.dev/variable-fonts/#fallbacks

### Why is this update needed?

This example isn't best practise, it doesn't account for when @supports isn't supported.

**Comment by RoelN** [comment]
Oh I see @tomayac added this because of a Chrome bug mentioned in https://github.com/GoogleChrome/web.dev/issues/7158. I think the "oldschool hacks".

This suggestion is not present in the es, pt and ru versions of this document. Should it be added there?

**Comment by tomayac** [comment]
If you dominate either of those languages, I guess PRs would be welcome.

**Comment by RoelN** [comment]
I don't, unfortunately. I'll close this issue as the example is as intended. Is there a process for asking for translations by native speakers?

**Comment by tomayac** [comment]
> Is there a process for asking for translations by native speakers?

@rachelandrew on the latest on this question. Thanks. Rachel!

**Comment by rachelandrew** [comment]
Unfortunately we don't have writers for those languages right now. In general updates are submitted from the community.

**Comment by dkruythoff** [comment]
Is it ok to bypass the PR system and hand this ES piece here? 
----
La regla `@supprts` no es soportada por Internet Explorer, así que este navigador no muestrara nada. Si esto es un problema, puedes usar una de las [oldschool hacks](https://stackoverflow.com/a/20541859/6255000) para apuntar a relevantes navigadores viejos.

**Comment by wordsmeet** [comment]
> Is it ok to bypass the PR system and hand this ES piece here?
> 
> --
> 
> La regla `@supports` no es soportada por Internet Explorer, así que este navigador no muestrara nada. Si esto es un problema, puedes usar una de las [oldschool hacks](https://stackoverflow.com/a/20541859/6255000) para apuntar a relevantes navigadores viejos.

Hi, everyone. Roel asked me to pipe in on the Spanish above. Without knowing the English paragraph it came from, I can only offer an approximation.
> The '@supports' rule, etc.
> La regla “@supports” es incompatible con Internet Explorer; por ello, no verá nada en este navegador. Si eso fuera un problema, puede usar una de las soluciones temporales tradicionales (https://stackoverflow.com/a/20541859/6255000 ) para conocer los navegadores viejos que sí puede usar.

**Comment by tomayac** [comment]
Thanks, opened https://github.com/GoogleChrome/web.dev/pull/9096 that adds the clarification to the Spanish version of the article.
