### ISSUE TITLE
Blog article hero images are too big, hurt UX

### ISSUE THREAD

**Issue by aaronpeters** [GoogleChrome/web.dev#9081]
**Is your feature request related to a problem? Please describe.**
On my macbook pro 13" in Chrome, the hero image at top of blog article pages is so big that it pushes the real content out of viewport. The article title is still visible, but that is too little. Coming from web.dev home page, I already know the title and it frustrates me that on article page load I have to scroll to see any content.
IMHO, on many/most article pages, the hero image is purely decorative and adds little value other than 'a nice looking visual'.
Example: https://web.dev/new-patterns-for-amazing-apps/ ... a keyboard ... how does that help the UX?

**Describe the solution you'd like**
Make the images smaller (lower the height) so the contents of the `header` (title, subtitle, dates, author) is visible without scrolling on common devices/screens.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AaronForinton** [comment]
Hey @aaronpeters (and great first name, by the way) - are you able to attach a screenshot of your display on a 13 inch machine so we can see exactly how the content is being affected?

**Comment by aaronpeters** [comment]
Here you go:

![Screenshot 2022-11-16 at 14 58 38](https://user-images.githubusercontent.com/283259/202200857-51a22279-2355-45a0-b75e-49952d762a4a.png)

**Comment by dstmarthe** [comment]
We are moving to a new platform and the UI for the blogs will be different. From what I can see in staging there will be no hero images on reading/learning content, so this will not be an issue after the move. Thanks for raising this though, in the first place.
