### ISSUE TITLE
Have Learn overview pages include H3 links in navigation menu

### ISSUE THREAD

**Issue by tunetheweb** [GoogleChrome/web.dev#9111]
**Is your feature request related to a problem? Please describe.**

There is nothing in the menu on the Learn overview pages:

![image](https://user-images.githubusercontent.com/10931297/203513025-ed0cfe37-74b4-402d-a004-2cb266f62aaa.png)

This is especially apparent on mobilem, where the drop down menu is fairly useless:

<img width="189" alt="image" src="https://user-images.githubusercontent.com/10931297/203513171-b615d931-1f53-46da-9c16-26446061f65c.png">

**Describe the solution you'd like**

We should link to each of the H3 headings, like we do on the non-overview Learn pages.

**Describe alternatives you've considered**

I looked to see if a simple markup fix, but this page is dynamically generated, so thought better to raise an issue rather than go straight to PR

**Comment by tunetheweb** [comment]
Still an issue

**Comment by dstmarthe** [comment]
Thanks for raising this issue. However, we're moving to a new platform and these learn modules already have a completely different looking UI. Sections and headings are a lot more defined than what they are now, as you are requesting. So, closing this as content on this version of the site is now frozen and it will no longer be an issue after the move!
