### ISSUE TITLE
web.dev page content issue

### ISSUE THREAD

**Issue by armgp** [GoogleChrome/web.dev#9118]
**Describe the bug**
The content in webpage web.dev has each letter printed in different lines.

**To Reproduce**
1. Go to https://web.dev/'
2. scroll

**Screenshots**

![Screenshot from 2022-11-25 14-09-20](https://user-images.githubusercontent.com/49094298/203937989-7e09915b-0f4e-446e-9c65-39db0af81a09.png)

**Comment by rachelandrew** [comment]
@armgp I can't reproduce this. Which browser are you using? You can [go here](https://www.whatsmybrowser.org/) and give me the link, if you like.

**Comment by armgp** [comment]
brave browser https://www.whatsmybrowser.org/b/LPUCZ

**Comment by armgp** [comment]
Brave browser https://www.whatsmybrowser.org/b/DUWL5
