### ISSUE TITLE
content: provide an official list of the status codes that can be returned by FCM for web push

### ISSUE THREAD

**Issue by collimarco** [GoogleChrome/web.dev#9128]
### What page(s) need to be updated?

https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/blog/push-notifications-web-push-protocol/index.md#response-from-push-service

### Why is this update needed?

On that page is present a list of *status codes* returned by a *push service*.

Is that a generic list for a generic push service?

Or it is the "official" list of status codes that can be returned by FCM (using the web push standard)?

Please add a link to an  "official" list of status codes that can be returned by FCM specifically.

**Comment by dstmarthe** [comment]
Thanks for suggesting this. We are migrating to a new platform and issue tracker. I've moved this issue to our new tracker. You can see it here: https://issuetracker.google.com/u/1/issues/298540726
