### ISSUE TITLE
Cookie banner is LCP element on mobile posts without a banner

### ISSUE THREAD

**Issue by tunetheweb** [GoogleChrome/web.dev#9130]
**Describe the bug**

Many of our posts have a banner image, however those that do not (e.g. https://web.dev/enable-https/) have an H1 , that is smaller than the cookie banner text. This means, for those visitors that have not accepted the cookie banner, the cookie banner text is picked as the LCP element and, because it loads quite late, this results in failing CWV for those pages. On that example page 56.1% of page views have the cookie banner text as LCP image.

Overall, looking at Google Analytics it only affects 7.3% of LCP elements.

**To Reproduce**
1. Go to https://web.dev/enable-https/ with Moto G4 emulation
2.Note the LCP element (either using the [web-vitals extension](https://chrome.google.com/webstore/detail/web-vitals/ahfhijdlegdabablpippeagghigmibma?hl=en) or dev tools).

**Expected behavior**
We should aim to pass CWV as much as possible for your pages, to set a good example for the community.

Additionally the most important user content is the H1 IMHO.

**Options**

As I can see it, our options are:

**1. Increase the size of the H1 element.**

To me it does seem a little small on mobile. It's currently set to this:

```css
font-size: clamp(1.75rem, 1.39rem + 1.79vw, 3rem)
```

Increasing the minimum size of `1.75rem` to `2.5rem` is sufficient to make this the LCP element for two line H1s on mobile, without impacting desktop. This would not fix it for 1-line H1s without a banner image ([example page](https://web.dev/browser-sandbox/)), but maybe we're OK with that as it's rare?

<img width="665" alt="image" src="https://user-images.githubusercontent.com/10931297/204269686-a28e83e1-29f4-46a1-8523-3091b87c66fd.png">

To be honest I think that looks better on mobile (and also on actual mobile when you try it there), so don't think this is a "hack" to get around LCP - currently the LCP element is incorrect and the H1 is too small IMHO.

How to do that is more tricky. That style is automatically generated using our [gorko config](https://github.com/Andy-set-studio/gorko) and, from a quick look, I can't see an easy way to change just the minimum size, but I'm not totally familiar with this library. Alternatively we could replace this:

https://github.com/GoogleChrome/web.dev/blob/5a0a738ff65fd1f6302e618fdb51efe8e77362c1/src/scss/next.scss#L65-L67

to `size-6`, but that seems a bit blunt, and would also affect desktop 

**2. Reduce the size of the cookie banner text**

This could be achieved by adding a `text-size-0` class to this:

https://github.com/GoogleChrome/web.dev/blob/5a0a738ff65fd1f6302e618fdb51efe8e77362c1/src/lib/components/Snackbar/index.js#L63-L66

<img width="660" alt="image" src="https://user-images.githubusercontent.com/10931297/204272447-f0b3a721-2ccd-4cb7-bcf5-2e1724d0d69f.png">

That could work for two-line headlines, but would need to be really small for one line ones.

**3. Split the cookie banner text into two paragraphs**

As LCP is based on block elements, having two `<p>` paragraphs of text would reduce the size of this. But it's one sentence at the moment, and splitting just to fix this LCP issue with the current design feels a bit icky. Plus not sure who signed off on this text and how much effort that would need.

Ultimately, I think the issue is the H1 is too small on mobile, rather than the cookie banner is too big.

**4. Make the Cookie banner text load earlier**

This could work, but at the detriment to the rest of the page load. It deliberately waits until DomContentLoaded event until the JavaScript is loaded for this reason, hence why it's so slow.

However, this still has the same issues as 3 - ultimately, I think the issue is the H1 is too small on mobile, rather than the cookie banner is too big.

So my vote is to increase the heading size on mobile, and open to ideas how to do this.

CC: @charisTheo who first raised this to me, and @gilbertococchi who chimed too.

**Comment by tunetheweb** [comment]
Still an issue

**Comment by dstmarthe** [comment]
Hi. Thanks for raising this. We are moving to a new non-Github platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move. Our new issue tracker is located at https://issuetracker.google.com/issues?q=status:open%20componentid:1400680&s=created_time:desc
