### ISSUE TITLE
With dark theme enabled, scroll bar is white

### ISSUE THREAD

**Issue by rakleed** [GoogleChrome/web.dev#9142]
**Describe the bug**

With dark theme enabled, a scroll bar is white.

**To Reproduce**

1. Go to https://web.dev/color-scheme/

**Expected behavior**

With a dark theme enabled, the scroll bar is dark. To make it, just add `color-scheme: dark` property to your CSS for the dark theme.

**Screenshots**

![screenshot-web-dev-color-scheme-1669834433237](https://user-images.githubusercontent.com/19418601/204884101-00ba098c-3d2a-4db0-adbe-154d202cfa04.png)

**Comment by rakleed** [comment]
.

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site ui, then it shouldn’t be an issue after the move.
