### ISSUE TITLE
<video> is listed as both current and future element for which LCP is measured

### ISSUE THREAD

**Issue by jaredcaraway** [GoogleChrome/web.dev#9144]
**Describe the bug**
The section discussing which elements LCP is calculated for includes `<video>`:

> What elements are considered? [#](https://web.dev/lcp/#what-elements-are-considered)
> As currently specified in the [Largest Contentful Paint API](https://wicg.github.io/largest-contentful-paint/), the types of elements considered for Largest Contentful Paint are:
> ...
> `<video>` elements (the poster image is used)

...but further down the page says that `<video>` is among elements that may be factored into LCP score in the future:

> Note, restricting the elements to this limited set was intentional in order to keep things simple in the beginning. Additional elements (e.g. `<svg>`, `<video>`) may be added in the future as more research is conducted.

Is there some distinction between the two `<video>` references or should the second reference be removed? Is it the case that `<video>` elements are currently measured by their poster images, but in the future will be measured differently?

I feel this bit could be worded more clearly. Once I gain a better understanding, I'll be glad to submit a PR updating the copy. Thanks! 🙂

**Comment by philipwalton** [comment]
Today, for `<video>` elements, only the poster image is used as the LCP candidate (if a poster image is specified). The frames from the video itself are not considered, though work is being done to include the first frame of the video as an LCP candidate as well.

Does that help clarify? Let me know if there are any specific changes you think we can make to the text to make that more clear.
