### ISSUE TITLE
Include <ErrorBoundary> info in React.lazy() docs

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/web.dev#915]
CC: @housseindjirdeh 

The https://web.dev/code-splitting-suspense/ docs do a great job of covering `React.lazy()` and `<Suspense>`. One thing that they don't mention, though, is that lazy-loading might fail (see [this presentation/site](https://pawll.glitch.me/) for some common failure scenarios), and that an [`<ErrorBoundary>`](https://reactjs.org/docs/error-boundaries.html) can be used to detect and handle that failure gracefully.

I am happy to submit a PR with some recommendations and links if you think that would be useful.

**Comment by housseindjirdeh** [comment]
Thanks so much, and this is a great point :)

Please feel free to submit a PR. Otherwise I can definitely go ahead and include a mention of it (along with an example app that demonstrates it as well maybe)

**Comment by jeffposnick** [comment]
I'm happy to put together the PR.
