### ISSUE TITLE
Codepen animation and css doesn't work in Safari

### ISSUE THREAD

**Issue by Jozebel11** [GoogleChrome/web.dev#9166]
**Describe the bug**
In the blog https://web.dev/building-chrometober/.  Codepen animation examples don't look and animate as they should on Safari.
<img width="1792" alt="Screenshot 2022-12-03 at 21 34 29" src="https://user-images.githubusercontent.com/97992665/205463667-b73cd215-66bb-460b-a46a-7a3f1a1e768b.png">

This issue does NOT happen on Google Chrome.

**To Reproduce**
1. Open 'https://web.dev/building-chrometober/' on Safari
2. Scroll down to the Codepen examples as shown in the screen shots
3. See error

**Expected behavior**
To function as they do on Google Chrome
<img width="1792" alt="Screenshot 2022-12-03 at 22 01 28" src="https://user-images.githubusercontent.com/97992665/205463872-65e44398-754c-4d3a-910e-1fc157d509d5.png">

**Comment by aaaaaahello** [comment]
+

**Comment by dstmarthe** [comment]
Thanks for raising this. We are moving to a new platform and issue tracker. I have submitted this in the new issue tracker and you can see it here: https://issuetracker.google.com/issues/298556756
