### ISSUE TITLE
small typo in Question 3 of web.dev/learn/css/pseudo-classes/

### ISSUE THREAD

**Issue by mtness** [GoogleChrome/web.dev#9188]
**Describe the bug**
it reads "psuedo"

**To Reproduce**
1. Go to 'https://web.dev/learn/css/pseudo-classes/'
3. Scroll down to bottom of page, see "test your knowlege, question 3"

**Expected behavior**
it should read "pseudo"

**Screenshots**
![Snap51](https://user-images.githubusercontent.com/15540/206278695-7d3c0b31-a289-4131-8362-9c429efe938f.png)

**Comment by AaronForinton** [comment]
Thanks for flagging this. It should be fixed within the next 24 hours.
