### ISSUE TITLE
Include mention of defer attribute for module/nomodule

### ISSUE THREAD

**Issue by housseindjirdeh** [GoogleChrome/web.dev#922]
More context [here](https://mobile.twitter.com/AndyDavies/status/1130589949684850688).

It's worth mentioning that `defer` should be considered for the nomodule script since modules are deferred automatically.

--> in web.dev/serve-modern-code-to-modern-browsers/

**Comment by robdodson** [comment]
Hey @housseindjirdeh, friendly ping. Do you think you'll have bandwidth to work on this?

**Comment by housseindjirdeh** [comment]
Thanks for the ping :)

I'll find some time this week!
