### ISSUE TITLE
Suggestion: Add Instruction on how to add Brotli in Apache or Nginix

### ISSUE THREAD

**Issue by evenstensberg** [GoogleChrome/web.dev#923]
It would be nice with a guide on how to add Brotli on the server side, such as with Apache or Nginix.

**Comment by robdodson** [comment]
tentatively assigning to addy to find resourcing.

**Comment by IvanBila** [comment]
Hi, @robdodson @addyosmani @Meggin is someone working on this? asking because I have something on the works and looking forward to opening a PR.

**Comment by addyosmani** [comment]
We have not yet assigned anyone to write this guide so it's definitely open to be taken :) as web.dev has a new content proposal process (you can see it in our issue template when filing a new issue), that might be a good place to start.

that way we can get a rough idea if the content you've already been exploring is in line with what we are hoping to get out for this guide.

**Comment by robdodson** [comment]
Going to close this as stale because we haven't been able to find an owner for it yet. Happy to reopen if anyone on the speed team is interested in taking it. cc @philipwalton in case there's interest.
