### ISSUE TITLE
content: Replace featured Chrometober asset with Year in Review video post

### ISSUE THREAD

**Issue by laurenju** [GoogleChrome/web.dev#9235]
* Use this template to request updates to existing content.
* Delete any fields that aren't relevant to your issue. 
* Update the title of this issue with a brief summary of the work to be done.

### What page(s) need to be updated?

web.dev

### Why is this update needed?

Chrometober has come and gone and we're posting a new Year in Review video that highlights the team's work over 2022.
Assets: https://docs.google.com/presentation/d/1NZiyYtEeu3d7G_LQ1f28tOJYmmfVhAlkpx0wabhprjM/edit#slide=id.g1aedea5a399_10_0
Copy: Watch the progress we made together on the web.

### What's the deadline?

December 14, 2022 or as soon as possible.

#### Is it a hard deadline?

As soon as possible.

**Comment by rachelandrew** [comment]
@AaronForinton can you make the update to the homepage? The file is en/index.md and you should be able to see the block that includes the Chrometober copy and image.

**Comment by AaronForinton** [comment]
@laurenju The gif assets we've got at the moment are a bit heavy for the page as it stands. Is it possible to get those at a smaller file size? If it can't be optimized I can do it as a static asset.

**Comment by laurenju** [comment]
![ChapterVideo_GIF_1280x628_B_v3](https://user-images.githubusercontent.com/4546422/207381357-f1b3a0cd-5cbb-473c-bc80-ea38819cdab7.gif)

@AaronForinton The agency optimized it from 7mb to 2.5mb. Let me know if that works!

**Comment by AaronForinton** [comment]
@laurenju Thank you! That worked, and I've opened a PR at #9240.

**Comment by laurenju** [comment]
![ChapterVideo_GIF_1280x628_B_v5](https://user-images.githubusercontent.com/4546422/207475776-c49bd7e9-bc60-4591-ac1b-b1005860101c.gif)
Adding it also in .gif format just in case.
