### ISSUE TITLE
content: Reframe 'Understanding "same-site" and "same-origin"' around new definition of "same-site"

### ISSUE THREAD

**Issue by recvfrom** [GoogleChrome/web.dev#9241]
### What page(s) need to be updated?

https://web.dev/same-site-same-origin/

### Why is this update needed?

The page currently notes that "same-site" does not take into account the scheme, but then talks about "schemeful same-site" in a separate section and says that the definition of "same-site" is evolving to consider the scheme. Given that some time has passed and the HTML spec has been updated to make the definition of "same-site" schemeful, I think it'd be worth updating the article in the following ways:
 - the "same-site" section should describe the "schemeful same-site" behavior
 - the existing "schemeful same-site" section could be replaced with a "schemelessly same-site" section that presents how "same-site" used to worked

I think this would be very helpful because the page is such a great reference for understanding the "same-site" and "same-origin" concepts, but if a reader skips the "schemeful same-site" section they walk away with a misunderstanding of what "same-site" means today.

**Comment by domenic** [comment]
See https://html.spec.whatwg.org/#schemelessly-same-site and the definitions and examples following this for some corroboration.

**Comment by agektmr** [comment]
This is a great feedback. I'll get to this shortly.

**Comment by raywhite714** [comment]
Could someone help me out I received bitcoins from Satoshi masters file I need help please

**Comment by agektmr** [comment]
@domenic @recvfrom Could you please clarify a few things?
- Do you have a link to a discussion where the change is agreed in the spec?
- Approximately when can we say this change happened?
- Can we consider `Sec-Fetch-Site: same-site` now follows the schemeful same-site concept across all supporting browsers?

**Comment by domenic** [comment]
- https://github.com/whatwg/url/issues/448
- Approximately November 2019
- I am 80% sure this is true, because I believe all browsers implemented Sec-Fetch-Site after this change. But I am not confident; maybe @recvfrom is.

**Comment by recvfrom** [comment]
I'm not familiar with Sec-Fetch-Site at all, unfortunately :(

**Comment by agektmr** [comment]
Do you know if Chrome follows this?

**Comment by domenic** [comment]
It does.

**Comment by agektmr** [comment]
Thanks. Then I'll assume all browsers follow the updated spec.

**Comment by recvfrom** [comment]
The updated content looks great - thanks @agektmr!
