### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by radosslav** [GoogleChrome/web.dev#9244]
**Describe the bug**
Two links return 404.

**To Reproduce**
1. Go to [https://web.dev/identity/](https://web.dev/identity/)
2. Click on: 

[[Codelab] Use cross-platform browser features to build a sign-in form](https://web.dev/identity/codelab-sign-in-form-best-practices)

[[Codelab] Sign-up form best practices codelab](https://web.dev/identity/codelab-sign-up-form-best-practices)

3. Both links are broken because of missing / no longer available pages.
4. The right URLs are:
[https://web.dev/codelab-sign-in-form-best-practices/](https://web.dev/codelab-sign-in-form-best-practices/)
[https://web.dev/codelab-sign-up-form-best-practices/](https://web.dev/codelab-sign-up-form-best-practices/)

**Comment by joseearias** [comment]
Hi! Seeing that this issue hasn't been fixed yet, I'm going to pick it up.
