### ISSUE TITLE
[aria-hidden="true"] elements contain focusable descendents in homepage

### ISSUE THREAD

**Issue by charisTheo** [GoogleChrome/web.dev#9252]
**Describe the bug**
Article cards in web.dev homepage have `aria-hidden="true"` attributes whereas they are not decorative elements but can be clicked and navigate to an article page. These elements are currently hidden from assistive technologies. 

Although each of the article cards have a link to their page below in another element within the card, the hero image of the article is hidden from assistive technologies with the current functionality described above.

**To Reproduce**
1. Go to https://web.dev/#main:~:text=to%20z%2Dindex.-,Case%20studies,-Learn%20why%20and
2. Inspect the two cards `<article class="card">`
3. Their first `<a>` children have `aria-hidden="true"` whereas they are links pointing to an article page

**Expected behavior**
As this is not a decorative element, remove the `aria-hidden="true"` attribute

**Screenshots**
<img width="1696" alt="Screenshot 2022-12-15 at 15 30 33" src="https://user-images.githubusercontent.com/9759549/207907776-99318170-8a90-47f9-ad80-dcbbbfeb4d0c.png">
<img width="563" alt="Screenshot 2022-12-15 at 15 59 25" src="https://user-images.githubusercontent.com/9759549/207908088-e9e36d8f-f340-47f6-a8ab-2582f5a22313.png">

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
