### ISSUE TITLE
content: Link to Learn HTML web.dev content from within Learn CSS instead of MDN

### ISSUE THREAD

**Issue by richardcarrigan** [GoogleChrome/web.dev#9255]
### What page(s) need to be updated?

https://web.dev/learn/css/

### Why is this update needed?

The intro encourages users to visit MDN to learn HTML instead of the existing Learn HTML course within web.dev.

### What's the deadline?

N/A

**Comment by AaronForinton** [comment]
@richardcarrigan Thanks you for spotting this!
