### ISSUE TITLE
content: TODO - Reconsider using links to external, paywalled references in the learning site

### ISSUE THREAD

**Issue by nateUX** [GoogleChrome/web.dev#9258]
### What page(s) need to be updated?
Provide a list of URLs.
https://web.dev/learn/accessibility/why/

### Why is this update needed?
The links to nytimes article are subscription only, making them inaccessible to many people attempting to learn this topic. It appears that nytimes does provide some allotment of free articles, but there is no information regarding how many that is or how often (if ever) it resets. 

![image](https://user-images.githubusercontent.com/5717928/208250963-448affa9-e7cc-4033-b4b6-4f847ab3a3f6.png)

**Comment by rachelandrew** [comment]
If you know of an alternative free article that covers the same subject then I'd be happy to consider adding it, this is however not required reading to follow the course (and there is also a video to watch) so I'm happy to keep the link to it. Given that a lot of journalism is behind paywalls (in order that these publications can keep publishing) there will sometimes be useful content behind a paywall.

**Comment by nateUX** [comment]
> If you know of an alternative free article that covers the same subject then I'd be happy to consider adding it,

@rachelandrew The author of the NYTimes articles (James Robinson) has also published very similar articles on their own site. Some portions are exactly the same. Those links seem to be publicly available. Hope this helps.


| NYTimes link | Author Link |
| :------------- | :------------- |
| [I Stutter. But This Is What You’re Not Hearing.](https://www.nytimes.com/2022/08/23/opinion/stutter-speech-listening.html)  | [STUTTERING](https://www.james-r.com/stuttering-coming-soon)  |
| [I Have Face Blindness. This Is How I Recognize You.](https://www.nytimes.com/2022/08/30/opinion/face-blindness-prosopagnosia.html)  | [Proso](https://www.james-r.com/faceblindness)  |
| [I’m Going Blind. This Is What I Want You to See.](https://www.nytimes.com/2022/08/16/opinion/blindness-retinitis-pigmentosa.html) | [Retinitis Pigmentosa – YVONNE](https://www.james-r.com/nyt-rp)
