### ISSUE TITLE
background-repeat "round" definition is incorrect

### ISSUE THREAD

**Issue by dariuswiles** [GoogleChrome/web.dev#9263]
**Describe the bug**
On page:
https://web.dev/learn/css/backgrounds/#repeating-background-images

the definition of `background-repeat` includes the following description:
> - `round`: The image repeats horizontally and vertically to fit as many instances into the space available, without cropping, compressing, or stretching it.

This is incorrect as the background image _will_ compress or stretch if an repeated number of images do not exactly fit the space. [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/background-repeat) explains it like this:
>  `round`  As the allowed space increases in size, the repeated images will stretch (leaving no gaps) until there is room (space left >= half of the image width) for another one to be added. When the next image is added, all of the current ones compress to allow room. Example: An image with an original width of 260px, repeated three times, might stretch until each repetition is 300px wide, and then another image will be added. They will then compress to 225px. 

The current definition should be corrected.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298556755
