### ISSUE TITLE
Clean up CourseLinks gtag usage

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/web.dev#9277]
https://github.com/GoogleChrome/web.dev/pull/9168 introduces a generic `logEvent` function that adds all relevant information to analytics events. 

src/lib/components/CourseLinks/index.js until now is an exemption, as it is inlined and hence uses a direct `gtag` call which should be avoided.

**Comment by tunetheweb** [comment]
Change of plan here. As these are not used, we'll just remove them.
