### ISSUE TITLE
content: TODO - Rephrase sentence to match course progress

### ISSUE THREAD

**Issue by nateUX** [GoogleChrome/web.dev#9278]
### What page(s) need to be updated?
https://web.dev/learn/accessibility/javascript/

Specifically, the sentence, "As we learned in the Document module, the page title is essential for screen reader users."

### Why is this update needed?
As of now,  Javascript is section 004 of the course. The Document module is section 006. The reader has likely not learned about the page title's importance to screen readers yet. 

### Potential Solution
"As we will learn in the Document module, the page title is essential for screen reader users."

**Comment by nateUX** [comment]
On the same page:
"In the Keyboard focus module, we covered focus order and indicator styles."

While this sentence is accurate in the sense that the "we" (the authors of the page) have covered the content; "we" (the readers of the page) have not covered that yet.

### Potential Solution
"In the Keyboard focus module, we will cover focus order and indicator styles."

### Alternative Solution
Move the JavaScript page later in the course.

**Comment by heyawhite** [comment]
Thank you for catching and suggesting this change. As we've published somewhat out of order, we hadn't reconfigured the order of our table of contents. I'll address this shortly.

**Comment by heyawhite** [comment]
An updated table of contents should be live in about an hour. JavaScript is now after The Document and Keyboard focus. Thank you again!
