### ISSUE TITLE
Implement GTM and remove analytics.njk if possible

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/web.dev#9280]
At the same time, we should look into removing analytics.njk and doing everything in app.js. 

For this to happen, if we switch to GTM, many GTM tags interact with the global dataLayer object, so we'd just have to test to see if it works to define/reference those locally in a module.

From Philip:
My understanding of how it works: when the gtm.js script loads, it overrides the dataLayer.push() method so it can hook into future push() calls. So we'd just have to test to see/ensure that our module-level reference to dataLayer doesn't start pointing to a different object after gtm.js loads

See #9168

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
