### ISSUE TITLE
Incorrect sample projects in CWV pages

### ISSUE THREAD

**Issue by tunetheweb** [GoogleChrome/web.dev#9282]
**Describe the bug**
As mentioned in https://github.com/GoogleChrome/web.dev/pull/9253#issuecomment-1362105162 I think that PR added extra sample categories in error to the CWV pages.

**To Reproduce**
1. Go to https://web.dev/vitals/
2. Notice it had the following tags: `Appears in: [Sample Collection Template](https://web.dev/example-collection/)|[Core Web Vitals](https://web.dev/learn-core-web-vitals/)`
3. The first shouldn’t be there and 404s when you click on it.
4. Also appears on other pages like this one: https://web.dev/vitals-business-impact/
5. Also there should be a space between tags for pages with multiple tags. For example https://web.dev/lcp/ should be “Appears in: Core Web Vitals | Metrics” and not “Appears in: Core Web Vitals|Metrics” but looking back I think that’s always been wrong, whereas above error is new.

**Expected behavior**

Sample pages are hidden

**Screenshots**

![0320249C-6A27-48A3-8B6B-74AC1E001469](https://user-images.githubusercontent.com/10931297/209006438-b9c6f09b-148b-44af-9bd7-438c7df598e5.jpeg)

**Comment by rachelandrew** [comment]
@devnook I think we're going to need to exclude the https://web.dev/handbook/content-types/example-collection/ page if we want to keep it as an example.

**Comment by tunetheweb** [comment]
Thanks for the quick action @devnook !
