### ISSUE TITLE
Quiz is incorrect or very confusing...I think incorrect

### ISSUE THREAD

**Issue by nateUX** [GoogleChrome/web.dev#9299]
**Describe the bug**
The quiz provided at the end of the [Document](https://web.dev/learn/accessibility/more-html/#page-language) page is either confusing or incorrect. 

**To Reproduce**
1. Go to quiz at bottom of page
2. Click on 3rd answer "Set `lang` on each element." (I think this is the correct answer)
3. Click on "Check"
4. See response that states the answer is incorrect.
5. Click on second answer "Include all languages in the `<html>` element."
6. Click on "Recheck"
7. See that answer is stated as correct but details of answer indicate that only 1 language can be provided in `<html>` implying that the answer is incorrect.

**Expected behavior**
The correct answer ( I think the 3rd one) to be identified as correct. If the 2nd is, in fact, the correct one then the phrasing should reinforce how it is correct as opposed to the third one.

Additionally, if the context to the second answer is true (the fact about only being able to place 1 language in the html tag), please educate the reader about that fact before testing them on it. It does not appear to be mentioned in the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/5717928/209552302-2e8d7254-5205-426d-be2b-2e600c85b824.png)

**Comment by heyawhite** [comment]
@nateUX thank you for creating this issue. You're right, the correct answer is the third one. We'll add some more context around this question in the module.

**Comment by heyawhite** [comment]
Several updates will soon be published which address your concerns.

First, new content under "Page langauge" which directly states only one language can be used in the `lang` attribute, along with a comparison example.

![The page states: The lang attribute can only have one language associated with it. This means the html attribute can only have one language, even if there are multiple languages on the page. Set lang to the primary language of the page.](https://user-images.githubusercontent.com/2766281/212184003-2296a55f-e37e-4635-a487-8adb56363811.png)

Second, the quiz was updated. The correct answer is the third, as stated. Plus, the options now have examples and the reason the third one is corrects should now be clearer.

![Corrected quiz](https://user-images.githubusercontent.com/2766281/212184444-3be49d47-d893-49ed-9242-dc773681c4c9.png)

If you have further suggestions or find other errors, open a new issue, and I'll do my best to address it.
