### ISSUE TITLE
content: TODO  PNGOUT may contain a trojan

### ISSUE THREAD

**Issue by dovematrix** [GoogleChrome/web.dev#9320]
https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/blog/responsive-images/index.md
https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/blog/responsive-images/index.md#reduce-the-file-size

PNG OUT URL  (http://www.advsys.net/ken/util/pngout.htm)
Malwarebytes Premium blocked this website because it may contain a Trojan.

**Comment by tomayac** [comment]
Google Safe Browsing doesn't consider the URL as problematic ([check](https://transparencyreport.google.com/safe-browsing/search?url=http:%2F%2Fwww.advsys.net%2Fken%2Futil%2Fpngout.htm&hl=en)). Closing the issue.
