### ISSUE TITLE
Perfromance of images on the web

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [GoogleChrome/web.dev#9321]
* Use this template to propose new content.
* Delete any fields that aren't relevant to your issue.
* Update the title of this issue with a brief summary of the work to be done.

### Workflow for Googlers

Fill out the web.dev content proposal form: https://docs.google.com/forms/d/e/1FAIpQLSc65CDClpUu7R2ECacLz3B1a6hOCWdFAk2vkWXIbZjzNSXq_Q/viewform?resourcekey=0-t3rJNkt5V2-iE2N42KhrhQ

Don't create an issue here on GitHub! Your GitHub issue will be closed
immediately and you'll be asked to fill out the form instead.

### Content proposal form for contributors who don't have access to Googlers

Fill out this section ONLY if you want to contribute new content to web.dev but don't have access to
Googlers.

#### Provide a brief title for your content proposal
Performance of images on the web

#### Provide a brief summary of your content proposal
Images have been an integral part of the web, since its inception. But, the effect they have on the performance of applications we ship to the web is usually negative.

In this article, the reader &mdash; after reading it &mdash; will have an understanding of the best practices on how to optimize images, and properly serve responsive images that are compatible with the DPR of various devices, so that they do not end up shipping unnecessary amounts of data to the end-user, which in turn slows down the page load of such application.

This article will also walk the user through the caveats that come along with optimizing images when they're using JavaScript frameworks. This article takes Next.js &mdash; the React framework for building production-ready applications &mdash; into perspective.

#### What content already exists on this topic?

[Optimize for Core Web Vitals](https://www.youtube.com/watch?v=AQqFZ5t8uNc&t=1295s)

#### Who will be authoring the content?

@kaf-lamed-beyt 

#### Are there any stakeholders who should be informed when this content changes?

None. 

#### What area is your content related to?

- Performance

#### What kind of content are you creating?

- Blog Post

**Comment by rachelandrew** [comment]
Hi @kaf-lamed-beyt thanks for this, however we already have some very similar content in progress. 

We don't typically publish a lot of third party content here, in particular about specific frameworks because it gets out of date very quickly. So you might have better luck with your proposal somewhere like Smashing Magazine.

**Comment by kaf-lamed-beyt** [comment]
Oh! 

I guess I shouldn't have made my summary revolve totally around a particular framework though. I have a draft [here](https://www.dropbox.com/scl/fi/ur98eij1p95qfre96bumw/Image-Performance-On-The-Web.paper?dl=0&rlkey=n669ql25nwm6lzip30rze9n5i) if you'd still love to take a look.
