### ISSUE TITLE
Music makes web.dev 2022 year summary video unavailable to users

### ISSUE THREAD

**Issue by menneske** [GoogleChrome/web.dev#9324]
On web.devs front page, a video claiming to describe 2022s greatest achivements to the web is presented. There is no subtitles, and the music is so loud that I couldn't follow what was said. A shame, cuz it seemed to be an interesting story. This is a common error, but a website that claims to focus on user experience shouldn't be having this kind of flawed content. Like the Iframes of the 90s, the popups of 00s, subscribe to newsletters nagging, or SoMe begging of the last decade - background music should obviously be ridiculed - at least on platforms like web.dev. I will leave this website disappointed, and be less likely to ever return.

**To Reproduce**
1. Go to  https://www.youtube.com/watch?v=W9O4CuSUKb8
2. Click on '....' play

**Expected behavior**
Make it possible to turn off the music (make another version)

**Comment by dstmarthe** [comment]
Thanks for raising this issue. We are moving to a new platform and issue tracker, so I have moved this to our new issue tracker. You can see it here: https://issuetracker.google.com/u/1/issues/298647522
