### ISSUE TITLE
Incorrect demo code for attributes section

### ISSUE THREAD

**Issue by dreambo8563** [GoogleChrome/web.dev#9331]
**Describe the bug**
Incorrect demo code for attributes section

**To Reproduce**
1. Go to ['...'](https://web.dev/learn/html/attributes/)
2. Scroll down to <label> part
4. See the code in highlight description

**Expected behavior**
>html <label>Send me a reminder   <input type="number" name="min"> before the workshop resumes</input></label>.

**Screenshots**
>html <label>Send me a reminder</label> <input type="number" name="min"> before the workshop resumes</label>.

**Comment by rachelandrew** [comment]
@dreambo8563 can you let me know what article this relates to?

**Comment by dreambo8563** [comment]
@rachelandrew , I check the article, this issued is already gone. closed
