### ISSUE TITLE
Missing  double quotation in contenteditable demo code

### ISSUE THREAD

**Issue by dreambo8563** [GoogleChrome/web.dev#9332]
**Describe the bug**
Missing  double quotation in contenteditable demo code

**To Reproduce**
1. Go to https://web.dev/learn/html/attributes/#contenteditable
2. `editor.setAttribute("contenteditable", "false);`

**Expected behavior**
`editor.setAttribute("contenteditable", "false");`

**Comment by albajarazeth** [comment]
Hey! I'm diving into OS this looks like a good first issue, can I pick this up?
