### ISSUE TITLE
How to implement login best practice in flutter or dart

### ISSUE THREAD

**Issue by HARIS4820** [GoogleChrome/web.dev#9337]
I am newbie for programming i started to learn flutter. In web.dev documention there is no example or code avilable for dart. Dart is developed by google. Web.dev documention need to update for dart language also.
Help to flutter developers

**Comment by rachelandrew** [comment]
Hi @HARIS4820 the Flutter docs are here https://docs.flutter.dev/

This site doesn't cover Flutter and Dart.
