### ISSUE TITLE
Adjustable sidebar width 

### ISSUE THREAD

**Issue by alvinjiooo** [GoogleChrome/web.dev#9342]
**Is your feature request related to a problem? Please describe.**
For https://github.com/GoogleChrome/web.dev/pull/9198, 
in https://deploy-preview-9198--web-dev-staging.netlify.app/patterns/media/microphone-process/
The Demo section is quite narrow due to sidebar is now taking too much width.
Is there a way to make it adjustable.

**Describe the solution you'd like**
To make sidebar width adjustable for reserving more width to Demo section in https://deploy-preview-9198--web-dev-staging.netlify.app/patterns/media/microphone-process/

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
