### ISSUE TITLE
[Bug] Autobot CSS Demo fails due to CSP violation

### ISSUE THREAD

**Issue by bivens-dev** [GoogleChrome/web.dev#9344]
**Describe the bug**
The Autobot demo located at https://web.dev/patterns/layout/autobot/demo.html does not work as it relies on an inline script which fails to meet the site's CSP policies.

**To Reproduce**
1. Go to https://web.dev/patterns/layout/autobot/demo.html
2. Click on 'add element'
3. See error in devtools console

**Expected behavior**
Demo should work as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/113126707/210904550-7c62b8c7-3944-4dd7-8e55-9a350fefecad.png)

**Update**
This appears to impact all CSS layout demos which feature an 'add element' button upon further testing

**Comment by bivens-dev** [comment]
Just checked this again and it still seems to be an issue (tested on phone so couldn’t check devtools)

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it https://issuetracker.google.com/issues/298464202
