### ISSUE TITLE
Publishing Google Sites on custom domain by CName, although is successful, but website showed Finished Domain error message 

### ISSUE THREAD

**Issue by londonprobioticstechnology** [GoogleChrome/web.dev#9363]
Publishing Google Sites on custom domain by CName (has even added Google Search Console to the domain by .txt) although is successful, but website showed Finished Domain error message. Please advise how should I proceed? Is there an A record and AAAA record needed alongside the CName record? 

Please advise. 
Thank you.

**Comment by rachelandrew** [comment]
@londonprobioticstechnology this repo is for issues with the content of the website at web.dev, it isn't a general help forum. The Google Sites help community is here https://support.google.com/sites/community?hl=en
