### ISSUE TITLE
Example link not working

### ISSUE THREAD

**Issue by abhishekdubey1** [GoogleChrome/web.dev#9364]
**Describe the bug**
The [example](http://paulkinlan.github.com/touch-patterns/touch-event-order-with-fixed-viewport.html) in [this](https://web.dev/mobile-touchandmouse/##1-clicking-and-tapping-the-natural-order-of-things) page/section doesn't work

**To Reproduce**
1. Go to https://web.dev/mobile-touchandmouse/##1-clicking-and-tapping-the-natural-order-of-things
2. Click on `example`
3. See error

**Expected behavior**
The example should be present.

**Screenshots**
<img width="1440" alt="Screenshot 2023-01-09 at 1 09 16 PM" src="https://user-images.githubusercontent.com/54868382/211260182-a750ffca-7501-4b06-b224-56a0c307e6e8.png">

**Comment by AaronForinton** [comment]
cc @PaulKinlan

**Comment by Abhiram-Gullapalli** [comment]
Can i work on this, seems like a missing link

**Comment by AaronForinton** [comment]
Hi @Abhiram-Gullapalli, tag me in any PR you raise and I'll happily review it.
