### ISSUE TITLE
content: Replace Timeline with Performance tab in Style Recalculation Cost example

### ISSUE THREAD

**Issue by cseas** [GoogleChrome/web.dev#9400]
### What page(s) need to be updated?

https://web.dev/reduce-the-scope-and-complexity-of-style-calculations/#measure-your-style-recalculation-cost

### Why is this update needed?

The Timeline tab in Chrome DevTools doesn't exist anymore. The example and screenshots shown are also outdated. The section needs to be rewritten with examples of the Performance tab.

### What's the deadline?

Should've been rewritten already.

#### Is it a hard deadline?

Yes, the existing content references a DevTools tab that doesn't exist anymore.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298467931
