### ISSUE TITLE
Design ability to highlight latest posts on a home page

### ISSUE THREAD

**Issue by tunetheweb** [GoogleChrome/web.dev#9404]
**Is your feature request related to a problem? Please describe.**

Currently there is no way to automatically flag the latest post in the home page. This requires an edit to the home page to "feature" the post. These featured posts can be in the general section at the top, or in each featured section below (Web platform news, CSS and UI, Performance...etc.)

**Describe the solution you'd like**

Should we have a way of automatically updating the home page to highlight latest posts, without having to remember to also update the home page?

**Option 1 - Add a dedicated "Latest" section to the home page**

This could be a dedicated section (which would also allow posts without a dedicated home page section - do we have any of those? - to be highlighted on the home page)

In some cases we may also have a new post that we don't want to specially highlight in the dedicated section (e.g. because we want the current Performance highlighted posts to be kept there longer term, but published a less-important "Performance" blog that maybe deserves a short time on the home page, until it gets pushed off by newer posts). This would be another argument for a dedicated section.

Could also consider merging sections in any "latest" section, so it includes Blog posts, Case Studies, Patterns, Learn. Would need to think about when a new Learn course drops though as it might have 10 new sections that basically takes over any "Latest" section in entirety. Though maybe that's no bad thing?

**Option 2 - Add ability to pull in the "latest post" for a section**

Alternatively (or additionally?) it could as an option in the dedicated section. For example the Performance section could have one panel dedicated to the latest Performance post (and could decide which panel that is by using some "latest" keyword or function in the YAML config for that section.

Similarly, the "Case studies" section at the top could be auto updated with the latest case study.

**Describe alternatives you've considered**
Continue to manually curate featured posts, but not everyone remembers to do this.

**Comment by rachelandrew** [comment]
I don't really see the need to have a generic latest posts section, because clicking on **Blog** gives you that list.

I do like the idea of automatically including the latest for a tag chosen for each section. We could reserve the top left box for example for that. 

Note that the aim of these panels isn't to be comprehensive, but more give people a guide into the range of content there is for a topic area(patterns, articles, potentially links to experimental or Chrome-only stuff on d.c.c.) You can also add additional rows to your panel.

**Comment by mollietokyo** [comment]
**Estimate:**

Design - 4hrs
Dev -  3.5 days

**Comment by tokyodanj** [comment]
Design ready for review @devnook  @matthiasrohmer

**Comment by tokyodanj** [comment]
Design approved - option 1A

**Comment by mollietokyo** [comment]
Estimate for dev = 2.5 days (SPR-3)
