### ISSUE TITLE
Links in Manual Testing Basics lead to a pre-fixed example page

### ISSUE THREAD

**Issue by CTByars** [GoogleChrome/web.dev#9419]
**Describe the bug**
In step 1 of the Demo: Manual test section, two links to a CodePen demo page are provided. The linked CodePen pages have already had the updates that are outlined in steps 2-4 completed. So a reader following along is unable to manually test the page and see the issues that are described.

**To Reproduce**
1. Go to the Manual Testing Basics page  https://web.dev/learn/accessibility/test-manual/
2. Navigate to the "Step 1" section
3. Click on either of the related hyperlinks "CodePen demo" (links to https://codepen.io/web-dot-dev/pen/PoBZgrW) or "debug mode" (links to https://cdpn.io/pen/debug/PoBZgrW).

**Expected behavior**
The user should be brought to a version of the Medical Mysteries Club page that still contains the errors pointed out in steps 2-4. Currently, the user is brought to a version of the example page where all the updates explained in the document have been resolved. 

**Screenshots**

**Comment by heyawhite** [comment]
@CTByars thanks for catching this! It will be updated to the correct Codepen, which is https://codepen.io/web-dot-dev/pen/NWBaMzb
