### ISSUE TITLE
The image link in README.md is no longer working

### ISSUE THREAD

**Issue by ShihTingJustin** [GoogleChrome/web.dev#9473]
**Describe the bug**
The image link in README.md is no longer working.

**To Reproduce**
https://github.com/GoogleChrome/web.dev#webdev

**Expected behavior**
The image should display normally.

**Screenshots**
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/56827791/215499590-972a57a6-839d-462c-99af-a56046f145d5.png">

**Comment by AaronForinton** [comment]
Attaching the asset: 

![badge](https://user-images.githubusercontent.com/89849359/216378788-71088b40-8b60-44b6-9a18-08a8b90850dc.svg)
