### ISSUE TITLE
chrome developer tool bug

### ISSUE THREAD

**Issue by KYUNGSUB** [GoogleChrome/web.dev#9477]
[Bug]
I set border to 10px but border of developer tools is wrong. it show me 9.6.

[To Reproduce]
1. I wrote HTML file like the below.
<!DOCTYPE html>
<html lang="ko">
<head>
	<meta charset="UTF-8">
  <title>박스모델</title>  
	<style>
    div {
      margin-bottom:20px;
    }
		.box1 {
			width:200px;
			height:100px;
      padding:20px;
      border:10px solid #ccc;
		}
    .box2 {
      box-sizing: border-box;
			width:200px;
			height:100px;
      padding:20px;
      border:10px solid #00f;
    }
	</style>
</head>
<body>
  <div class="box1"></div>
  <div class="box2"></div>
</body>
</html>

2. In browser, I call file path as the below.
file:///D:/education/Front_End/HTML/Do%20it!%20HTML+CSS+%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%20%EC%9B%B9%20%ED%91%9C%EC%A4%80%EC%9D%98%20%EC%A0%95%EC%84%9D/sources/08/box-sizing.html

3. press the F12 key to show developer tools.
4. Select "Elements tab"
5. press "<div class="box2"></div>" region
6. Click the "Computed" tab and look box model. 
7. See error that border is 9.6 (I set border 10px but it was 9.6)
8. I activate Microsoft Edge browser and I call same file like chrome.
9. Edge show that border is 10px.

[**Expected behavior**]
border : 10px not 9.6

**Describe the bug**

**To Reproduce**
11. Click on '....'
12. Scroll down to '....'
13. See error

**Expected behavior**

**Screenshots**
[At chrome browser]
![image](https://user-images.githubusercontent.com/1498680/215687461-254b29fb-05bb-49eb-be86-4f44197d8d60.png)

[At Edge browser]
![image](https://user-images.githubusercontent.com/1498680/215687742-e264ead4-b602-41cb-8fad-568a8978d5f2.png)

**Comment by KYUNGSUB** [comment]
Excuse me.
So what can I do for solving this problem?
Best Regards...

========================================================
서경섭(SEO KYUNGSUB)                       (예수, 진, 성, 봉사)
HHP : 82-10-9530-3135,          E-Mail : ***@***.***
========================================================

-----Original Message-----

**Comment by AaronForinton** [comment]
Hi there @KYUNGSUB. To submit a Chromium bug, please follow the steps outlined on [this page](https://www.chromium.org/for-testers/bug-reporting-guidelines/). You can also find the board [here](https://bugs.chromium.org/p/chromium/issues/list).
