### ISSUE TITLE
`BrowserCompat` is not accessible

### ISSUE THREAD

**Issue by kurtextrem** [GoogleChrome/web.dev#9484]
**Describe the bug**
The "eye" icon (or in general any icon) of the `BrowserCompat` table is not really accessible, as screenreaders will say "eye" instead of something meaningful. In addition, I don't even know what the eye icon wants to tell me, since there is neither a description nor a title on hover (if you leave out the context of the text above the table).

**To Reproduce**
1. Go to https://web.dev/web-platform-01-2023/#the-scrollend-event
2. Hover over the "eye" icon (or use a screen reader)

**Expected behavior**
The icon has a title that is a clear and concise title of what the it wants to tell you.

**Comment by matthiasrohmer** [comment]
This is now fixed - instead of Emojis there are properly labeled icons.

**Comment by kurtextrem** [comment]
Thank you!
