### ISSUE TITLE
Rework code sample in "Implement error handling when using the Fetch API"

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [GoogleChrome/web.dev#9519]
### What page(s) need to be updated?

https://web.dev/fetch-api-error-handling/#when-the-network-status-code-represents-an-error

### Why is this update needed?

The code sample here could be improved to avoid introducing potentially unfamiliar concepts to readers (e.g., the optional chaining operator), to keep the code short, and to address the problem more idiomatically:

```js
let response;

try {
  response = await fetch('https://httpbin.org/status/429');
} catch (error) {
  console.log('There was an error', error);
}

// Uses the 'optional chaining' operator
if (response?.ok) {
  console.log('Use the response here!');
} else {
  console.log(`HTTP Response Code: ${response?.status}`)
}
```

Rather than conditionally assigning a response, we can throw an error if `Response.ok` is falsy:

```js
try {
  const response = await fetch('https://httpbin.org/status/429');
  // network error in the 4xx–5xx range
  if (!response.ok) {
    throw new Error(`${response.status} ${response.statusText}`);
  }
  // use response here if we didn't throw above
  doSomethingWith(response);
} catch (error) {
  console.log(error);
}
```

Happy to contribute an edit for this upon approval.

**Comment by jakearchibald** [comment]
I agree with the proposed change. However, I think it's worth pointing out why the fetch API doesn't throw in these cases: you still have a response.

For example, a 404 response can still be an image, and an `<img>` will render it. A 403 response can still parse as JSON, and provide further details about the error than can be included in the status text etc etc.

**Comment by AaronForinton** [comment]
@AleksandrHovhannisyan Are still happy to contribute an edit? If not I'll raise a PR with your suggested sample change and tag you.

**Comment by AleksandrHovhannisyan** [comment]
Oh, my bad, I thought Jake wanted to tackle it since he self-assigned. Does this repo use assignments for folks who oversee/review PRs for a ticket?

**Comment by AleksandrHovhannisyan** [comment]
Sorry, between work and personal stuff I don't think I'll have the bandwidth to put in a PR. I don't wanna hold this up. Please feel free to assign someone else!

**Comment by AaronForinton** [comment]
@AleksandrHovhannisyan No problem, I'll open a PR and tag you once it's opened so you can follow its progress at your leisure.

**Comment by dstmarthe** [comment]
Hi all. We're moving to a new platform and content on this site is now frozen. I'm migrating content issues to our new issue tracker. The way content is submitted will also be different since we are moving away from Github. So, I've replicated this issue on our new tracker. As you are the authors I encourage you to comment to be CC'd and provide additional context if needed: https://issuetracker.google.com/u/1/issues/298700529
