### ISSUE TITLE
`CodePattern` component should allow for preloading supporting code

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#9522]
(See the [Google doc](https://docs.google.com/document/d/1Vzc1ieHE8lZqWOpXVN9v9oaahfrYwAPYZ6MaeyeaoN8/edit?usp=sharing&resourcekey=0-O7BMDa07Pj6b894Y5Eag8w) for the full background.)

Inspired by CodePen, we propose an improvement to the existing [CodePattern component](https://github.com/GoogleChrome/web.dev/blob/main/src/site/_includes/components/CodePattern.js) in web.dev, namely the possibility of preloading the code pattern with external CSS, JS, and potentially HTML resources.

Unlike with CodePen, though, were such preloads are not easily exposed to the user, we propose to initially hide preloads via a [filter](https://github.com/GoogleChrome/web.dev/blob/f3d6e739f9cb0351e064b8506c1cdbfd6a36e084/src/lib/patterns.js#L64-L67), but add expandable tabs to the component that teases initially shrunk supporting resources under a More… tab, which the user can then click to see the expanded tabs, like Supporting JS in the mock below. 

![Screenshot 2023-02-07 at 13 22 44](https://user-images.githubusercontent.com/145676/217243780-0d991c70-fa2e-4272-8936-6ea756feb1b5.png)

**Comment by matthiasrohmer** [comment]
@tomayac, you are now able to add supporting JS and/or CSS to code patterns by adding an asset prefixed with `supporting-` to code patterns. They get surfaced in an initially collapsed "More..." tab. Feel free to raise follow-up issues if you miss anything related in that context.
