### ISSUE TITLE
Design a page for CSS triggers

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/web.dev#9529]
The team used to maintain csstriggers.com (the site which is currently live there has nothing to do with the old project), which listed all CSS properties and their impact on the browser rendering pipeline. The page looked like this: https://www.lmame-geek.com/css-triggers/

While we don't maintain the page anymore the team is currently looking into recollecting the data and making it available for web.dev to display. Therefore we need a design how this would look on web.dev.

**Comment by tokyodanj** [comment]
Design has been created in Figma. Ready for review

**Comment by tokyodanj** [comment]
Design feedback received from Ewa - amendments in progress.

**Comment by tokyodanj** [comment]
Amended as per comments in Figma. Ready for review

**Comment by tokyodanj** [comment]
Design approved in Figma
