### ISSUE TITLE
FABs take up too much space on mobile.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#953]
View an article on a mobile device. The FABs take up a lot of room and really distract from the reading experience. Wondering if we should just get rid of them on mobile or make them fixed at the bottom?

Moving to an internal tracking tool

**Comment by jpmedley** [comment]
What is a FAB?

**Comment by robdodson** [comment]
a material design floating action button
https://material.io/design/components/buttons-floating-action-button.html

**Comment by robdodson** [comment]
Put together a mock of the mobile view to illustrate the issue.

<img width="277" alt="Screen Shot 2019-07-11 at 10 50 32 PM" src="https://user-images.githubusercontent.com/1066253/61105323-674c1100-a42e-11e9-83fd-6b491ea2094e.png">
