### ISSUE TITLE
Carousel on the Component Patterns page does not function as a carousel

### ISSUE THREAD

**Issue by Jozebel11** [GoogleChrome/web.dev#9545]
**Describe the bug**
The carousel on the Component Patterns page does not function as a carousel. 

**To Reproduce**
1. Go to 'home page'
2. Click on 'Patterns' on the nav bar
3. Scroll down to and click on 'Component Patterns'
4. Click on 'Carousel'
5. See error

**Expected behavior**
The images should slide across like a carousel, using buttons to move to the next image.

**Screenshots**

<img width="1112" alt="Screenshot 2023-02-09 at 18 01 10" src="https://user-images.githubusercontent.com/97992665/217902360-9efedb4d-bb7a-4fee-9195-d02bf3fce93c.png">

**Comment by matthiasrohmer** [comment]
Hey @Jozebel11, can you give some more context on this, like used browser, browser version, ...? It renders fine in latest Chrome:

<img width="888" alt="image" src="https://user-images.githubusercontent.com/12857772/219447661-6e47974b-17a1-4c69-9096-1e001b30aa0c.png">

Safari:

<img width="853" alt="image" src="https://user-images.githubusercontent.com/12857772/219447807-dc4e85c7-bc48-484b-b1b4-5ab5dac9ec36.png">

and Firefox for me:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/12857772/219448450-e2de8a5c-d601-4d74-b007-f0b55111f1b7.png">

**Comment by Jozebel11** [comment]
I am using Safari Version 15.2 (17612.3.6.1.6) where it doesn't render correctly.

When I use Chrome it renders correctly.

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new non-Github based platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
