### ISSUE TITLE
Broken Links in The Basics of Web Workers

### ISSUE THREAD

**Issue by Freytag** [GoogleChrome/web.dev#9549]
**Describe the bug**
On [The Basics of Web Workers](https://web.dev/workers-basics/) article in the [Transferrable objects](https://web.dev/workers-basics/#transferrable-objects) section there is a [DEMO](http://html5-demos.appspot.com/static/workers/transferables/index.html) link to an external site that does not exist. 

In the [Demos](https://web.dev/workers-basics/#demos) and [References](https://web.dev/workers-basics/#references) there are more links that do not take you to a working page. 

**To Reproduce**
1. Go to [The Basics of Web Workers](https://web.dev/workers-basics/) article
3. Scroll down to the bottom of the [Transferrable objects](https://web.dev/workers-basics/#transferrable-objects) section
2. Click on **DEMO** in *check out this [DEMO](http://html5-demos.appspot.com/static/workers/transferables/index.html)*

**Expected behavior**
A working webpage with the demo 

**Screenshots**
<img width="796" alt="Screenshot 2023-02-09 at 1 28 42 PM" src="https://user-images.githubusercontent.com/1278024/217943228-8599a33b-fa43-4db0-b7ed-e3c84370e2ed.png">
<img width="651" alt="Screenshot 2023-02-09 at 1 31 53 PM" src="https://user-images.githubusercontent.com/1278024/217944169-d1882d93-1521-4b52-ace4-74397015865a.png">

**Comment by Freytag** [comment]
Here is the appropiate URL for ["Using web workers"](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers)

**Comment by AaronForinton** [comment]
Thanks for raising this @Freytag. I've given the article of a bit of a dust-off and removed deprecated links. I've also linked to a newer article from 2020 with more information in the use cases section.
