### ISSUE TITLE
Updates to the Chrome DevRel floating tab

### ISSUE THREAD

**Issue by harleenkbatra** [GoogleChrome/web.dev#9551]
On all web.dev pages, we now have a floating tab calling attributing the content to the Chrome DevRel team (related PR: 

Suggest a few tweaks to current design:

- On mobile (I have an Android), the banner is cutting off content on the side so we should have him reduce the size of it to match the margins in a responsive way. (Please ensure we test this across all devices and browsers)

- Also, for the Chrome DevRel logo, which I don't think is standardized at all, we should ideally have the logo come before the text, so we can keep consistency. I've made a note to have some of these internal brands documented in our new brand guidelines as well.

Thanks

**Comment by mollietokyo** [comment]
Estimate = 0.5 days (design) / 1 day (dev)

**Comment by tokyodanj** [comment]
Design work is done - option 5C preferred by Harleen. 

Matthias creating a working demo for testing.

**Comment by harleenkbatra** [comment]
Thanks both

**Comment by matthiasrohmer** [comment]
We just launched the updated version of the ribbon with https://github.com/GoogleChrome/web.dev/pull/9632. It is considerably smaller and auto-hides after scrolling past the first viewport.
