### ISSUE TITLE
PerformanceObserver example is not valid

### ISSUE THREAD

**Issue by fedebertolini** [GoogleChrome/web.dev#9557]
**Describe the bug**
The `PerformanceObserver` [example code](https://github.com/GoogleChrome/web.dev/blob/22c06fce1e75b6f5433064f5ca5938c3f036ff29/src/site/content/en/fast/navigation-and-resource-timing/index.md?plain=1#L164-L192) in the "Acquiring timings in application code" section of the Navigation and Resource timing doc is not valid according to the W3C specs, and breaks in Firefox.

The example code passes an options object with two properties, which isn't valid according to [point 3.3.1.3 of the Performance Observer's observe spec](https://www.w3.org/TR/2019/WD-performance-timeline-2-20190321/#observe-method).

**Spec:**
> If options's entryTypes is present and any other member is also present, then throw a SyntaxError.

**Example code:**
```js
perfObserver.observe({
  // Polls for Navigation Timing and Resource Timing entries
  // (but can poll for other entry types as well):
  entryTypes: [
    'navigation',
    'resource'
  ],
  buffered: true
});
```

This works fine in some browsers, but breaks in Firefox [[ref to source code](https://searchfox.org/mozilla-central/source/dom/performance/PerformanceObserver.cpp#172-177)]. This happens even when passing `buffered: false`.

**To Reproduce**
1. Open any site with latest Firefox version
2. Open the console
3. Paste and execute the following code

```js
const perfObserver = new PerformanceObserver(console.log);

perfObserver.observe({
  entryTypes: ['navigation', 'resource'],
  buffered: true
});
```

**Expected behavior**
The code throws a `TypeError` which is actually what's expected according to the official specs. What I think should be fixed is the example in the [web.dev article](https://web.dev/navigation-and-resource-timing/#acquiring-timings-in-application-code)

**Screenshots**
Error in Firefox when calling `observe` passing `entryTypes` and `buffered`.
<img width="952" alt="Screenshot 2023-02-10 at 14 52 58" src="https://user-images.githubusercontent.com/1497562/218108700-f475b89a-a96c-44bd-a80c-56a25f0239f3.png">

**Comment by fedebertolini** [comment]
The [MDN PerformanceObserver.observe docs](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver/observe#parameters) mention this about the `entryTypes` option:
> An array of string objects, each specifying one performance entry type to observe. May not be used together with the "type", "buffered", or "durationThreshold" options.

The web.dev article example could be changed to the following snippet to make it valid:
```js
perfObserver.observe({
  // Polls for Navigation Timing entries
  // (but can poll for other entry types as well):
  type: 'navigation',
  buffered: true
});
```

**Comment by tunetheweb** [comment]
Agreed. @malchata can you correct this since it's your article?

See also here for an alternative to collect multiple entries with buffered flag: https://github.com/WICG/soft-navigations/issues/10#issuecomment-1387379763
