### ISSUE TITLE
Remove speculation rules experiment after origin trial expired

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/web.dev#9559]
Related to https://github.com/GoogleChrome/web.dev/pull/9532. The origin trial expires 22 Mar 2023.

**Comment by tunetheweb** [comment]
Leave open

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new non-Github based platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
