### ISSUE TITLE
Light picture at the page header in dark theme

### ISSUE THREAD

**Issue by moyous** [GoogleChrome/web.dev#9586]
**Describe the bug**
Picture on light background in the page header with enabled dark theme.

**To Reproduce**
1. Go to https://web.dev/learn/css with viewport **(min-width: 80em)** to see desktop sidebar.
2. Look at wrong picture at the top left corner of the page.

**Expected behavior**
Picture with the dark background color same as background color at the sidebar and contrast title "Learn CSS!".

**Screenshots**
<img width="509" alt="Wrong picture" src="https://user-images.githubusercontent.com/26393844/218835629-33e7b78d-c684-49ac-b0d2-b3745274abe7.png">

**Comment by simgobb** [comment]
Removing the white background and changing the grey font to white works for the LearnCSS page, but not so much on the other course pages. 

Agreed with @matthiasrohmer and @tokyodanj to assess it from a design point of view first.

**Comment by dstmarthe** [comment]
Thanks for raising the issue. Closing this as we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move.
