### ISSUE TITLE
By Chrome DevRel ribbon obscures content.

### ISSUE THREAD

**Issue by bryanwood** [GoogleChrome/web.dev#9589]
When reading articles on a mobile (iPhone 12 mini) the right side of the content is covered by the "By Chrome DevRel" ribbon.

**To Reproduce**
See https://web.dev/cq-stable/

**Expected behavior**
Content isn't covered up.

**Screenshots**

![image](https://user-images.githubusercontent.com/1381261/218959158-c9c8262c-6680-4e1c-b740-84b55a48f540.png)

**Comment by rachelandrew** [comment]
I think this is already raised in https://github.com/GoogleChrome/web.dev/issues/9551

**Comment by matthiasrohmer** [comment]
Thanks for your feedback! We just launched an updated version of the ribbon via https://github.com/GoogleChrome/web.dev/pull/9632 which should also work for smaller devices.
