### ISSUE TITLE
Content feedback for discover-performance-opportunities-with-lighthouse

### ISSUE THREAD

**Issue by alankent** [GoogleChrome/web.dev#96]
Content: https://web.dev/fast/discover-performance-opportunities-with-lighthouse

- “Press Control+Shift+J or Command+Shift+J (Mac) to open DevTools.” Add “(Windows)” - it only says (Mac) at present.
- CMD-Shift-J on my Mac external keyboard opened the “Downloads” area, not DevTools.
- “Run Lighthouse from Chrome DevTools” - the numbered points after images are being reset to 1 for each image.
- “Click the Audits tab. If you don't see this tab, click More Panels *and then select *Audits from the list.” “and then select” formatting is messed up, I assume because spaces are in the right place for "*" formatting.
- “Make sure that the *Clear Storage *checkbox is enabled.” - “*” markup messed up again.
- “For example, if you run some audits with *Simulated Fast 3G, 4x CPU Slowdown *throttling enabled ”. "*" formatting messed up.
- “Hover over a metric to learn more about it. Click *Learn more *to read documentation about it.” - "*" formatting messed up.

**Comment by robdodson** [comment]
> “Press Control+Shift+J or Command+Shift+J (Mac) to open DevTools.” Add “(Windows)” - it only says (Mac) at present.

Decided to leave this as-is because ctrl-shift-j is windows + linux. I think it may be ok to leave it implied since only mac users will have a command key on their keyboard.

> “Run Lighthouse from Chrome DevTools” - the numbered points after images are being reset to 1 for each image.

Decided to leave this as well. I kind of like that the numbers get reset after large page breaks.
