### ISSUE TITLE
Unable to switch language

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#9600]
**Describe the bug**
Switching language using the bottom language switcher works fine when I land on the article, for example at https://web.dev/same-site-same-origin/, however, when my browser's language is set to Japanese and land on https://web.dev/i18n/ja/same-site-same-origin/, switching the language redirect me back to the original one making it unable to switch language.

**To Reproduce**
1. Go to https://web.dev/i18n/ja/same-site-same-origin/
2. Select the language to "English" at the bottom of the page.

**Expected behavior**
The URL is changed to https://web.dev/i18n/en/same-site-same-origin/ and the content will be displayed in English.

**Screenshots**
The URL is continued to be https://web.dev/i18n/ja/same-site-same-origin/ and the content continues to be displayed in Japanese.

**Comment by dstmarthe** [comment]
Thanks for raising this. However we are moving to a new platform and content on this site in now frozen. The backend will be completely different so this shouldn't be an issue after the move.
