### ISSUE TITLE
What if the user would like some of his disk back?

### ISSUE THREAD

**Issue by jidanni** [GoogleChrome/web.dev#9608]
In https://web.dev/storage-for-the-web/#how-much one thing overlooked
is "[What if the user would like some of his disk back?](https://bugs.chromium.org/p/chromium/issues/detail?id=1413011#c5)"
I.e., the article should consider what if using more space is OK now,
but then the winds change, and the user wants some of his space back.

**Comment by AaronForinton** [comment]
Hi @petele - not sure if you've been made aware of this ticket and [the associated issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1413011) yet.

**Comment by jidanni** [comment]
Like I mentioned in that associated issue:
Yes, your computer looks good now,
but not several years later after heavy chrome use.

Then chrome will have gobbled up up to 60% of the empty space on the disk.

The problem is: what if we want a little back?

Well, the only solution is to have "planned ahead", and first put some junk
files on the disk, so years later when we want some of our space back,
we simply remove the junk files, because we can remove them, but not
chrome's files, without damaging chrome!

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and issue tracker, so content on this site is now frozen. I’ve moved this content update to our new tracker and you can see it at https://issuetracker.google.com/u/1/issues/298700527
