### ISSUE TITLE
push notification permission prompt's text limit

### ISSUE THREAD

**Issue by roeniss** [GoogleChrome/web.dev#961]
Hi, my name is Roeniss Moon and I am not familiar with github yet. So if this issue is not appropriate please let me know. Thank you.

---

# Version
Chrome: 74.0.3729.169(official build) (64 bit)
MacBook Pro: Retina, 13-inch, Early 2015
Country: South Korea
Found at: today

## Problem that I saw
![image](https://user-images.githubusercontent.com/26613280/58788901-d7919680-8627-11e9-9faf-b9c8e90979ca.png)

In korean, a text in permission prompt is cut. So I can't figure out the full text.
The original site's name in this picture is "www.XXXXX.com" (I am not sure I could make the name public). If site's name was "www.ABCDEFGH.com" the result that I can see would be only "...DEFGH.com".

On the other hand, It always shows full text in English:
![image](https://user-images.githubusercontent.com/26613280/58789272-b8473900-8628-11e9-8f26-facb9f74b5b4.png)
(image from https://developers.google.com/web/fundamentals/codelabs/push-notifications/?hl=ko)

## Conclusion
I suggest a few solutions.
1. Horizontal Scroll in prompt screen
2. Dynamic width based on text (see below)

### Reference
I checked Firefox also. They use slightly different approach I think:
![image](https://user-images.githubusercontent.com/26613280/58789486-36a3db00-8629-11e9-9c05-26d05bd715a4.png)

I'm not sure where the limits are but, at least, Firefox has more width-tolerance.

**Comment by robdodson** [comment]
Hey @roeniss this sounds like it might be a bug in Chrome? I'd suggest filing it in the Chrome bug tracker at http://crbug.com.
