### ISSUE TITLE
Create documentation for the ```codePattern``` component

### ISSUE THREAD

**Issue by mamieorine** [GoogleChrome/web.dev#9634]
The codePattern feature hasn't been documented into the handbook yet.

According to the enhancement of the codePattern feature in #9552, this improvement should be documented and added to the handbook (https://web.dev/handbook/) to demonstrate to the author how it works. 

Note: documentation follow-up issue for https://github.com/GoogleChrome/web.dev/issues/9522.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform so the code and structure of these components may be different, but I am moving this issue to our new tracker as I imagine there will be a new `codePattern` component You can see it at https://issuetracker.google.com/u/1/issues/298703875
