### ISSUE TITLE
content: PWA install criteria needs updates

### ISSUE THREAD

**Issue by myakura** [GoogleChrome/web.dev#9651]
### What page(s) need to be updated?

Installation
https://web.dev/learn/pwa/installation/#installation-criteria

What does it take to be installable?
https://web.dev/install-criteria/

### Why is this update needed?

They still note that Chrome PWAs need service workers with fetch() handlers to be installable, which is no longer true.

The drop for service worker requirement only briefly covered in the [dcc blog post](https://developer.chrome.com/blog/default-offline/); I havn't seen any blink-dev intent-to-change messages or existing article updates.

There are couple of BlinkOn talks covers about the subject; but they don't link to the crbug entry when the change has landed...
Installing Any Page as an App [BlinkOn 17] - YouTube
https://www.youtube.com/watch?v=ktTdZgrP56Q

Installing any site as an app - Google Slides
https://docs.google.com/presentation/d/14-Tsw2gsSu16esbYjJHkFCGxt6YD4UZrokSyQmXs4Nw/edit?resourcekey=0-OjxSocV5oWJkck1ysYD3rA#slide=id.g18a08463e90_0_22

Lightning Talks - Session 1 [BlinkOn 17] - YouTube
https://www.youtube.com/watch?v=39qvqvuJxT8&list=PL9ioqAuyl6UK-7T_fmKuIwrvH9oMm57ep&index=4

So I want some clarification when that happend, and what exactly PWAs need to be installable in 2023.

Also, there are links in the https://web.dev/install-criteria/ to other vendors' resources; Samsung and UC Browsers' pages are gone, and Edge page mentioning installation has moved to https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/ .

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll have to address this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298467930
