### ISSUE TITLE
Your tester is being engaged

### ISSUE THREAD

**Issue by fernandeshenrique15** [GoogleChrome/web.dev#968]
Hello, there is a way to circumvent this tester that is being used in bad faith by a competitor of our company. They are analyzing when the test is coming from you and submitting another site in place of the original site, generating great but false ratings. We kindly ask you to review how the approach is being done so that other companies will not do this anymore, because it is disloyal to us that we work tirelessly to deliver a better real experience. Thank you.

Website you are selling falsely: https://imob.ingaia.com.br/
Site used in the example: https://www.spinimoveis.com/

Thank you

--

Original

O analisador esta sendo enganado

Olá, existe uma forma de burlar este testador que esta sendo usado de má fé por um concorrente da nossa empresa. Eles estão analisando quando o teste esta vindo de vocês e apresentando outro site no lugar do site original, gerando notas ótimas, porém falsa. Pedimos a gentileza que reveja como esta sendo feito a abordagem para que outras empresas não façam mais isto, pois é desleal conosco que trabalhamos incansavelmente para entregar uma melhor experiência real. Obrigado.

Site que esta vendendo a inverdade: https://imob.ingaia.com.br/
Site usado como exemplo: https://www.spinimoveis.com/

Obrigado

**Comment by robdodson** [comment]
Hi @fernandeshenrique15 I'm not sure I understand the issue.

Are you saying that when someone runs [our measure tool](https://web.dev/measure) against imob.ingaia.com.br that they redirect it to analyze spinimoveis.com?

I ran our measure tool against imob.ingaia.com.br and it seemed to return results that were only for that site.

It's important to mention that our site, web.dev, and our measure tool have no affect on search ranking.

I'm going to close this because it doesn't seem like a bug but I'm happy to continue the discussion.

**Comment by fernandeshenrique15** [comment]
Hi, when you test the site spinimoveis.com, the system of the site analyzes the user agents and open a site with simple HTML so that there is a great note, this information of 100% of performance is sold on the site https: // imob. ingaia.com.br/ as a resource. In the native browser tool you can test and view more real information about the site, check out these images:

Oi, quando você testa o site spinimoveis.com, o sistema do site analisa o user agents e abrem um site com HTML simples para que haja uma nota ótima, esta informação de 100% de performance é vendida no site https://imob.ingaia.com.br/ como um recurso. Na ferramenta nativa do navegador é possível realizar o teste e visualizar informações mais reais sobre o site, confira nestas imagens:

![image](https://user-images.githubusercontent.com/12588636/58912968-a7162f00-86f1-11e9-993c-32094c4cdf26.png)

![image](https://user-images.githubusercontent.com/12588636/58912870-77ffbd80-86f1-11e9-8a7a-a0241899a1f6.png)

Although it does not affect search ranking, the site sells erroneous information to its customers due to verification failure:

Embora não afete o ranking de pesquisa, o site vende uma informação errada para os seus clientes devido a falha na verificação: 
![image](https://user-images.githubusercontent.com/12588636/58911735-da0af380-86ee-11e9-830a-c4fde0d44717.png)

**Comment by robdodson** [comment]
One of the items on my todo list this quarter is to add a clear FAQ to the measure tool that explains that the score does not directly affect your search ranking.

Aside from that I don't know if there's anything we can do on a technical level to prevent them from UA sniffing our bot. Really sorry, I know that's super frustrating :(

If I think of anything I'll update this ticket.
