### ISSUE TITLE
Incorrect quote causes incorrect input type

### ISSUE THREAD

**Issue by djoume** [GoogleChrome/web.dev#9685]
**Describe the bug**
In [the attributes/label section](https://web.dev/learn/html/attributes/#lesslabelgreater)

It looks like ” (right double quotation mark) is used instead of " (double quotes) to quote the attribute of the elements, this results in the wrong type of input being rendered (text instead of radio) and the quotation marks appearing in the value:

![image](https://user-images.githubusercontent.com/34644/222273889-9600a95f-06b3-4d58-8d35-9594c58a5b4e.png)

**Comment by AaronForinton** [comment]
The codepen has now been updated to include only straight quotation marks.
