### ISSUE TITLE
Patterns are causing duplicate content issues in Search Console

### ISSUE THREAD

**Issue by rachelandrew** [GoogleChrome/web.dev#9717]
In Google Search Console > Page Indexing, there are lots of duplicate content issues which seem to be related to patterns, I'm not sure why, but might be worth figuring out, we may need to mark something as canonical to make sure we're not getting some part of the patterns indexed rather than the main page.

**Comment by dstmarthe** [comment]
Closing as we are migrating to a new platform and content on this site will be frozen.
