### ISSUE TITLE
content: Install Criteria

### ISSUE THREAD

**Issue by KenjiBaheux** [GoogleChrome/web.dev#9742]
### What page(s) need to be updated?
https://web.dev/install-criteria/

### Why is this update needed?
Outdated requirement(s) since Chrome M103(?):
 - fetch handler not required anymore
 - possibly some fields not required anymore too (will ping someone who knows the finer details).

### What's the deadline?
As soon as possible since the guidance is outdated.

#### Is it a hard deadline?
No.

**Comment by myakura** [comment]
tagging #9651

**Comment by KenjiBaheux** [comment]
Looks like the change isn't yet fully launched. Sorry for jumping too quick on this.
