### ISSUE TITLE
Demo in CSS Trigonometric functions article doesn't work across browsers

### ISSUE THREAD

**Issue by myakura** [GoogleChrome/web.dev#9743]
**Describe the bug**

The second demo in the [CSS Trigonometric functions article](https://web.dev/css-trig-functions/) ( https://codepen.io/web-dot-dev/pen/ExePgOg ) doesn't work in Firefox and Safari.

**To Reproduce**

1. Open https://codepen.io/web-dot-dev/pen/ExePgOg in Firefox and Safari

**Expected behavior**

There are dots on the circle rotating counter-clockwise.

**Screenshots**

<img width="1854" alt="Screenshot: Demo shown in Firefox (left) and Safari (right)" src="https://user-images.githubusercontent.com/413984/223977598-424617d1-c1ca-433c-a64c-c1be12eae697.png">

In Firefox I see a dot without color staying at the center of the circle. In Safari I see colored dots on the circle but they are not moving.

**Comment by bramus** [comment]
The lack of rotation is expected in Safari and Firefox, as they currently don’t support `@property`. This is a non-essential trait of the demo. The demo caters for this, by hiding the controls in that case.

Firefox does seem to have an issue with positioning the dots, which I will need to look into. Thanks for reporting.
