### ISSUE TITLE
Vue learning path.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#976]
Similar to web.dev/react. Let's create a learning path for Vue that follows the six principles.

**Comment by kayandra** [comment]
I would love to send in the learning path for Vue. Or is someone working on it already?

**Comment by housseindjirdeh** [comment]
Thanks @kayandra!

We haven't started on Vue yet and are working on getting Angular content out in the meantime. We do plan to have members from the Vue community help us write the learning path/content so we'll definitely let you know when that begins :)

**Comment by kayandra** [comment]
@housseindjirdeh thanks! will be on the look out

**Comment by robdodson** [comment]
Hey @housseindjirdeh is this something we're still thinking of working on?

**Comment by kaycebasques** [comment]
@housseindjirdeh I'm happy to re-open this if you have concrete plans to work on this collection.
