### ISSUE TITLE
The importance of headers in web accessibility: how to use them correctly

### ISSUE THREAD

**Issue by FranciscoImanolSuarez** [GoogleChrome/web.dev#9762]
#### Provide a short title for your content proposal
The importance of headers in web accessibility: how to use them correctly

#### Provide a brief summary of your content proposal
In this article you will learn the importance of headers in improving web accessibility and how to use them properly. Discover how headers can improve user experience and search engine optimization.

Please explain how this content will help me become a better web developer.
It will allow you to understand the importance of using headers correctly on the website and also how to validate site structures on a general level.
#### What content already exists on this topic?
They have content on accessibility but I did not find one related to this topic.
Please provide a list of URLs.
https://web.dev/learn/accessibility/
#### Who will be the author of the content?
Francisco Imanol Suarez
Provide a list of GitHub usernames.
FranciscoImanolSuarez
#### Is there any stakeholder that should be informed when I change this content?
No, all content is my own

#### What area is your content related to?
Accessibility
Choose one of the following: Accessibility, PWAs/Capabilities, Frontend, Holotypes, Performance, Privacy/Security, Other.

#### What type of content are you creating?
Guide/Blog
Choose one of the following: Blog post, Case study, Codelab, Guide, Other.

**Comment by FranciscoImanolSuarez** [comment]
I can upload it in English and Spanish.

I have the Spanish version at the following link: https://imanolsuarez.dev/encabezados

**Comment by rachelandrew** [comment]
Hi @FranciscoImanolSuarez - thanks for this, however we don't typically accept external content proposals. 

Perhaps try [Smashing Magazine](https://www.smashingmagazine.com/write-for-us/)? Or somewhere like [dev.to](https://dev.to/).
