### ISSUE TITLE
Space missing between consecutive `a` and `em` elements

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/web.dev#9774]
Under https://web.dev/better-responsiveness-metric/#interaction-types, the aside reads:

> The [current metric](https://web.dev/inp/)_only_ considers keyboard, mouse, and touch events, and does _not_ consider hover or scrolling when calculating INP.

There's a space missing between the `current metric` link and the emphasized `only` text.

However, there is a space in the [source code](https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/blog/better-responsiveness-metric/index.md?plain=1):

```md
The [current metric](/inp/) _only_ considers keyboard, mouse, and touch events, and does _not_ consider hover or scrolling when calculating INP.
```

So it's not clear if this is a bug in the way the markdown gets rendered to HTML or if it's more of a presentation issue in CSS.

**Expected:**

<img width="763" alt="image" src="https://user-images.githubusercontent.com/1120896/225299790-a6ba14d8-aee9-4828-b4c0-94f8e7cafd23.png">

**Actual:**

<img width="758" alt="image" src="https://user-images.githubusercontent.com/1120896/225299837-1b2f6ca0-29ce-41a3-9ef5-0554c7bdbff9.png">

**Comment by rviscomi** [comment]
I think this bug may be resurfacing between `strong` and `a` elements in the objective asides on the updated https://web.dev/optimize-inp/ page:

<img width="525" alt="image" src="https://github.com/GoogleChrome/web.dev/assets/1120896/d4e920bd-dcc8-4c22-af45-66dde2fd71f8">

cc @malchata

**Comment by malchata** [comment]
cc: @devnook

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are migrating to a new platform and content/code on this site is now frozen. As this is about the site code, have to close it.
