### ISSUE TITLE
Implement frontend for CSS triggers page

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/web.dev#9818]
Implementation follow-up for https://github.com/GoogleChrome/web.dev/issues/9529. Make sure to start with a design doc, describing how to break down the interactive parts into web components, to fit the web.dev architecture.

**Comment by matthiasrohmer** [comment]
On hold until the CSS/UI team reached consensus wether a revival of the CSS triggers page as is or a better more narrowed down guide is better suited.

**Comment by caseycarroll** [comment]
The CSS Triggers page is a resource I dearly miss! I would love to see a revival of this or something similar on web.dev, maybe on the animations page: https://web.dev/animations/ 

While the authors point out that transform and opacity are best for performance, I think CSS triggers would help reinforce that guidance.

**Comment by dstmarthe** [comment]
We are moving to a new platform and issue tracker. The site UI and infrastructure will change with the move. Content is now frozen for this site - so I will have to close this issue. The new issue tracker is specifically for content on the website, so I urge you to submit an issue for the revival of the CSS triggers page with any additional details. Issue tracker: https://issuetracker.google.com/u/1/issues?q=status:open%20componentid:1400680&s=created_time:desc
