### ISSUE TITLE
"Bringing service workers to Google Search" case study

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/web.dev#982]
**Describe the article you'd like to see**

I have a case study that's already gone through the proper internal approval channels talking about the use of service workers in the Google Search web app (i.e. for users who visit https://www.google.com/; this isn't a post about indexing).

After discussing with @harleenkbatra08, we're planning on posting this as a blog entry.

---

If you plan to write the article yourself be sure to read through [our wiki](https://github.com/googlechrome/web.dev/wiki) which explains how to add a new post to the site.

**Comment by carolrivero** [comment]
+"Content" Project

Thanks for the heads up, Jeffy. 

A few followup questions:
- Do you have a target review + publish date?
- To help us prioritize, does the blog have dependencies (eg, marketing promo, etc)? If so, what are the dependencies?

**Comment by jeffposnick** [comment]
We're done with internal reviews at this point, but I was working with @harleenkbatra08 on the final images to use prior to publication. So the dates are dependent on that.

@harleenkbatra08 might be able to shed some light on the marketing side of things.
