### ISSUE TITLE
start headless chrome differs when we do not provide default url explicit 

### ISSUE THREAD

**Issue by krzysztofg-ion** [GoogleChrome/web.dev#9834]
**Describe the bug**
Before, when I open a chrome with this attributes:
`chrome\path --headless --no-sandbox --remote-debugging-port=9222`
I was able to read properties from `localhost:9222/json` path.

Now (Chrome 111.*) I need to provide default page in start command
`chrome\path --headless --no-sandbox --remote-debugging-port=9222 about:blank`
otherwise the response from `localhost:9222/json` is this 5 characters: `[   ]`

But docs says that now url means default one, so we have a breaking change?

**Expected behavior**
`chrome\path --headless --no-sandbox --remote-debugging-port=9222` returns the same data as 
`chrome\path --headless --no-sandbox --remote-debugging-port=9222 about:blank`

**Comment by dstmarthe** [comment]
If this is in reference to an article I recommend linking that article on doc and submitting this issue again to https://issuetracker.google.com/issues?q=status:open%20componentid:1400680&s=created_time:desc

This is our new issue tracker as we our migrating our sites to a non-Github-based platform. Thanks.
