### ISSUE TITLE
web.dev action banner should be dismissable

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#9835]
The banner is always there. It should be possible to permanently dismiss it, similar to the sister site `developer.chrome.com`'s banner. 

<img width="1333" alt="Screenshot 2023-03-29 at 18 15 12" src="https://user-images.githubusercontent.com/145676/228616854-746f4bd9-49c7-48d5-974d-2a010eb47d69.png">

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content on this site is now frozen. As this is about the site, then it shouldn’t be an issue after the move. Also, seems like it was dealt with in the merged thread.
