### ISSUE TITLE
 Codepen result not rendered correctly in the Tables article in the Presenting Data section

### ISSUE THREAD

**Issue by jojostyles** [GoogleChrome/web.dev#9866]
**Describe the bug**
The Codepend in the Tables article under the Presenting Data section is not being rendered correctly. It it supposed to show icons that show to the user that the columns are sortable, however this does not happen (see the screen shot).

**To Reproduce**
1. Go to https://web.dev/learn/html/tables/#presenting-data
2. Scroll down to the first Codepen of that section, and if the section has changed since this issue has been raised, then scroll down to the Codepen that is meant to be showing that columns are sortable using icons (svg elements).
3. See error

**Expected behavior**
The table columns should show that they are sortable using icons.

**Screenshots**
<img width="561" alt="image" src="https://user-images.githubusercontent.com/15014598/229642614-7fe248ae-8952-4c7b-936c-eeff9dcbf58f.png">

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298215268
