### ISSUE TITLE
Wrong authors for Web Worker article

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#9879]
**Describe the bug**
[The Basics of Web Workers](https://web.dev/workers-basics/) is not authored by Malte and myself. There was a similar issue on [WebSockets](https://web.dev/websockets-basics/) article, but this is likely happened in the content migration from Web Fundamentals to web.dev.

I don't know who's the original author, but can someone please fix this?

Maybe @rachelandrew ?

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298215267
