### ISSUE TITLE
Add more disability tools such as Text To Speech to your site.

### ISSUE THREAD

**Issue by frog-o** [GoogleChrome/web.dev#9882]
**Is your feature request related to a problem?** 
*Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]*
 
I always frustrated that people don't support people with dyslexia or other reading problems although TTS is part of the browser for some reason people don't use it  or dark-mode for people who are sensitive to light these should be part of the browser but i know you can't do that; 

**Describe the solution you'd like**
However you can have a 

`<div></div>`

bellow each menu items start page with disability tools to let you highlight, speak highlight text (or the whole page), bookmark, skip to page and others tools. To help people with dyslexia or just a little difficulty reading.

**Describe alternatives you've considered**
Although I not blind I find your site very difficult to read, it is to much for me and if i send the page to my text to speech it too small and keep finding i have to open another page.  Or in other words Links to next page and previous pages are not followed. On some sites I can download a pdf which works great because I found a good pdf reader that does text to speech really well.

**Additional context**
You should not have to ask the OS for everything IMHO the website should allow all disability tools by default in a none distracting way.
I love site that have a" read me this article button "and i think we could do better by having a stander disability button with a set of tools that allow dark-mode ,reading text and more that can be turned off and customized in the webpage settings.

**Comment by rachelandrew** [comment]
@frog-o thanks for your message and we'll bear it in mind for future planning. I am working on creating PDF and ebook versions of some of our courses, so hopefully that will be helpful if you find PDFs easier with tools that you use.

**Comment by raha1364** [comment]
اکانت حساب موبایلم  تلگرام  اینستا جمیل  وات ساپ  کلا تمامیه موبایلم توسط فردی در آلمان هک شده تمامحسابهای بانکی وسرمایه گذاری وکیف پورارز دیچیتالم خالی وصفرشده لطفا کمکم کنید

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll keep this in mind over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298216473
