### ISSUE TITLE
Incorrect example code

### ISSUE THREAD

**Issue by timakro** [GoogleChrome/web.dev#9924]
[This example](https://github.com/GoogleChrome/web.dev/blob/4fe623659007471bf2e114ce2fb3086292041f3d/src/site/content/en/learn/pwa/caching/index.md?plain=1#L128-L136) from https://web.dev/learn/pwa/caching/ page is incorrect because an arrow function is passed to `event.waitUntil` instead of a Promise. The code inside the body of the arrow function never runs.

**Comment by djmitche** [comment]
You can also use an IIFE, at the cost of some extra parens:
```js
const urlsToCache = ["/", "app.js", "styles.css", "logo.svg"];
self.addEventListener("install", (event) => {
   event.waitUntil((async () => {
      const cache = await caches.open("pwa-assets");
      return cache.addAll(urlsToCache);
   })());
});
```

**Comment by miketaylr** [comment]
bad stalebot.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new non-Github based platform and so we’ll have to make fix this over there. I’ve moved the issue and relevant comments to our new tracker and you can see it at https://issuetracker.google.com/issues/298526959
