### ISSUE TITLE
Incorrect media query.

### ISSUE THREAD

**Issue by Yasir-Khan22** [GoogleChrome/web.dev#9930]
#**Describe the bug**
Either the wrong media query is defined or Gif/Video is incorrect under `Combinations` section.
Note: apologies in advance if you find me dumb.

**To Reproduce**
1. Go to 'https://web.dev/learn/design/media-queries/'
2. Scroll down to 'Combinations'
3. Click on 'Edit on CODEPEN'
4. the content is actually not going into `column-count: 2;`

**Expected behavior**
The content should go into 2-columns after resizing to `50em` breakpoint.

**Screenshots**

**Comment by dstmarthe** [comment]
This seems like a valid issue to me. Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/298215265
