### ISSUE TITLE
Utilise the `rssFeeds` utility to display external feeds on the web.dev author profile page.

### ISSUE THREAD

**Issue by mamieorine** [GoogleChrome/web.dev#9932]
Related issue [#71](https://github.com/GoogleChrome/webdev-infra/issues/71)

Explore how to utilise the implemented utility for fetching RSS feeds, the work from [#71](https://github.com/GoogleChrome/webdev-infra/issues/71), with web.dev and d.c.c ([#6077](https://github.com/GoogleChrome/developer.chrome.com/issues/6077)). 

The `rssFeeds` method in the webdev-infra ideally reads the `authorsData.json` file on both web.dev and d.c.c, loops over all authors and looks for a  `external` key, which contains the configurable list of arbitrary sources, then write an new “external-posts.json” file, containing all data needed for the updated author page layout, to the specific path for both web.dev and d.c.c. 

Example format of the “external-posts.json”:

```
[
 {
  "danristic":  [
      {
        "source": "una.im",
        "url": "https://una.im/2015-resolutions/",
        "title": "2015 Resolutions",
        "date": "Wed, 31 Dec 2014 00:00:00 GMT",
        "summary": "This is a personal post about my 2014 in review (because a lot happened) and my goals for 2015. Happy New Year!"
      }
      ...
    ],
  }, {
   "paulkinlan": [
      {
        "source": "https://web.dev/authors/paulkinlan/feed.xml",
        "url": "https://web.dev/media-capturing-images/",
        "title": "Capturing an image from the user",
        "date": "2016-08-23T00:00:00Z",
        "summary": ""
      },
      ...
    ]
  }
]
```

To utilise this method with web.dev,  we need to create a new job to deal with external data RSS feeds. Please see the example of [The job for gathering the the tweet feeds](https://github.com/GoogleChrome/developer.chrome.com/blob/main/external/build/tweets.js).

Then, enhance the logic in the author collection to be able to read the feeds from the written “external-posts.json” file and display feeds on the updated author page as per the design in Figma.

**Comment by dstmarthe** [comment]
Thanks for raising this. However, we are moving to a new platform and content/code on this site is now frozen. As this is about the site code, have to close it.
