### ISSUE TITLE
Browser Compat widget too indented on mobile

### ISSUE THREAD

**Issue by tunetheweb** [GoogleChrome/web.dev#9933]
**Describe the bug**

The browser compat widget has too much left white space on mobile:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/10931297/233624245-3350f309-8afd-4869-876d-e381647e5e88.png">

**To Reproduce**
1. Go to https://web.dev/lcp/ on mobile (or mobile emulation_
3. Scroll down to the Browser Compat widget
4. See error above

Also on my (large!) iPhone 14 it causes the page to overflow on the right and leads to an annoying horizontal scroll

**Expected behavior**

No white space on left.

**Comment by matthiasrohmer** [comment]
Fixed with https://github.com/GoogleChrome/web.dev/commit/de50f21d4e243a2e0a883928f4dbbb430a6fa73b.
