### ISSUE TITLE
content: Misleading or incorrect info about COEP header value

### ISSUE THREAD

**Issue by sgbeal** [GoogleChrome/web.dev#9944]
### What page(s) need to be updated?

- <https://web.dev/why-coop-coep/> (<https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/blog/why-coop-coep/index.md>)

### Why is this update needed?

This snippet:

> The require-corp keyword is the only accepted value for COEP.

... is either incorrect or misleading (leaving out context for which it may well be the only legal value). COEP has 3 valid values:

<https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy>

and at least one of the others ("credentialless") suffices for access to SharedArrayBuffer and OPFS, as demonstrated locally with the sqlite3 WASM build's test suite:

![image](https://user-images.githubusercontent.com/235303/234282143-0b120e1f-dae9-482d-96c5-7b852d69cc52.png)

**Comment by rachelandrew** [comment]
@agektmr could you take a look at this issue?

**Comment by agektmr** [comment]
Ack. I'll have a look.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at  https://issuetracker.google.com/issues/298216472
