### ISSUE TITLE
Migrate updated filter frontend from developer.chrome.com to web.dev

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/web.dev#9947]
https://github.com/GoogleChrome/developer.chrome.com/pull/5747 will introduce a new set of reusable web components to developer.chrome.com which allow to easily filter on-page content.

The same set of filters will also be used for the new author pages @mamieorine is working on and therefore should be made available for web.dev too. Either by copying them here, or transferring them to webdev-infra - whatever is more feasible, please evaluate.

**Comment by simgobb** [comment]
Migrated the component files and styles from DCC. Corrected the imports and the file structure to match the one already used in web.dev for web components. 

There are still some issues in terms of behaviour that could be linked to a different version of Lit used on Web.dev.

Next steps will be converting the components and fixing all the CSS to be in line with web.dev's style.

**Comment by dstmarthe** [comment]
Closing this because we are migrating to a new platform and content on web.dev is frozen. If you would like to raise the issue again after migration you can submit an issue on the new tracker at https://issuetracker.google.com/issues?q=status:open%20componentid:1400680&s=created_time:desc
