### ISSUE TITLE
Migrate check workflow from developer.chrome.com and add link checker

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/web.dev#9953]
We revamped the check workflow for developer.chrome.com a while back and now web.dev has a different UX, which is confusing for contributors to both repositories. The checks from d.c.c need to be migrated to this repo and old checks/dependencies/actions need to be removed.

Additionally to the checks existing on d.c.c we should add the new link checking capabilities to web.dev

**Comment by Blazzike** [comment]
Messaging you directly @matthiasrohmer on Chat, however for others: just checking exactly what this issue is referring to. :)
