### ISSUE TITLE
Web Vitals query

### ISSUE THREAD

**Issue by dbeaver12** [GoogleChrome/web.dev#9966]
Hi..
With ref to a ticket raised on MMU system (71365077), we would like to check on these prior to use in Manchester Metropolitan university one of our departments-
1.	When was software last updated
2.	Is software still on active development
3.	Are the software provider committed to patching the software in event of security incident or known security vulnerabilities.
Please could answer the above-mentioned question about the Web Vitals.
Thanks, and Regards,
Jesu 
Jesu Mathew 
Software Licensing Administrator

**Comment by AaronForinton** [comment]
Hi there @dbeaver12. Since this repo focuses on documentation requests for the web.dev site, I'm going to close this issue. Please direct this query to the relevant area of [https://stackoverflow.com/](https://stackoverflow.com/).

**Comment by dbeaver12** [comment]
Hi..
With ref to a ticket raised on MMU system (71365077), we would like to check on these prior to use in Manchester Metropolitan university one of our departments-

When was software last updated
Is software still on active development
Are the software provider committed to patching the software in event of security incident or known security vulnerabilities.
Please could answer the above-mentioned question about the Web Vitals.
Thanks, and Regards,
Jesu
Jesu Mathew
Software Licensing Administrator

**Comment by dbeaver12** [comment]
Hi..
With ref to a ticket raised on MMU system (71365077), we would like to check on these prior to use in Manchester Metropolitan university one of our departments-

When was software last updated
Is software still on active development
Are the software provider committed to patching the software in event of security incident or known security vulnerabilities.
Our Information security dept checked oon this one as urgent -Please update us on this -
 **The chrome add-on page states that data is not sold to 3rd parties, outside of approved use cases. Is it possible to contact the vendor / developer to understand what data (if any) would be sold, and the use cases for selling this data.**

Please could answer the above-mentioned question about the Web Vitals.
Thanks, and Regards,
Jesu
Jesu Mathew
Software Licensing Administrator

**Comment by dbeaver12** [comment]
Hi..
With ref to a ticket raised on MMU system (71365077), we would like to check on these prior to use in Manchester Metropolitan university one of our departments-

When was software last updated
Is software still on active development
Are the software provider committed to patching the software in event of security incident or known security vulnerabilities.

**Our Information security dept checked on this one as urgent -Please update us on this -
The chrome add-on page states that data is not sold to 3rd parties, outside of approved use cases. Is it possible to contact the vendor / developer to understand what data (if any) would be sold, and the use cases for selling this data.

Please could answer the above-mentioned question about the Web Vitals.**
Thanks, and Regards,
Jesu

Jesu Mathew
Software Licensing Administrator
