### ISSUE TITLE
Web Components and SEO

### ISSUE THREAD

**Issue by AVGP** [GoogleChrome/web.dev#997]
I'd love to write an article on what the new Googlebot means for web developers working with Web Components and what our best practices and guidelines for web components look like from an SEO perspective.

This is intended to address the questions coming from the web developer and SEO communities on this topic since we announced the new Googlebot at I/O

I'd be happy to write that article, btw :)

**Comment by carolrivero** [comment]
Martin, 
Please provide an estimated publish date. Thanks.

**Comment by AVGP** [comment]
@carolrivero I'd aim for June 28th - does that sound good?

**Comment by carolrivero** [comment]
Yes, Thanks, Martin. Adding this to the Content project board to queue it up.
