### ISSUE TITLE
Redundant highlight class in CSS example section of unset value

### ISSUE THREAD

**Issue by Dimas-e63s** [GoogleChrome/web.dev#9976]
**Describe the bug**
In CSS tutorial in the inheritance lesson in the demonstration of `all` property, `color` declaration has the redundant `highlight-line-active` and `highlight-line` classes

**To Reproduce**
1. Go to https://web.dev/learn/css/inheritance/#the-unset-keyword
2. FInd the text 
```If you change the aside p rule to all: unset instead, it doesn't matter what global styles are applied to p in the future, they will always be unset```
3. Scroll down to the code example
4. See error (`color: unset` has `highlight-line` class applied)

**Expected behavior**
Color declaration in the code example of `all` property doesn't have the `highlight-line` class

**Screenshots**
If applicable, add screenshots to help explain your problem
<img width="807" alt="Zrzut ekranu 2023-04-30 o 08 17 14" src="https://user-images.githubusercontent.com/69429935/235338866-6aab5856-b986-4baf-b749-e56abf1b19ce.png">
.

**Comment by Dimas-e63s** [comment]
@AaronForinton I would like to work on it. Can I?

**Comment by AaronForinton** [comment]
Hi @Dimas-e63s. Absolutely! Just tag me in the PR when you're done and I'll be able to get it merged.
