### ISSUE TITLE
H4 styles look like links.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#998]
**Describe the bug**
Our h4 styles look too much link links. This can make it confusing when you're scanning a post.

**Screenshots**

h4 example:
![image](https://user-images.githubusercontent.com/1066253/59306138-7f264e80-8c50-11e9-8622-60149a6521b9.png)

link example:
![image](https://user-images.githubusercontent.com/1066253/59306175-92d1b500-8c50-11e9-8880-7e7136d846ab.png)

**Comment by jpmedley** [comment]
Also, headings aren't typically in smaller type than the content they introduce.

**Comment by robdodson** [comment]
Very noticeable on this page:
/prefers-color-scheme/#why-dark-mode
